## LASA filecode 245 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_245 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I"
    ),
    variable_name = c(
      "bmspec#",
      "bmspec01",
      "bmspec02",
      "bmspec03",
      "bmspec04",
      "bmspec05",
      "bmspec06",
      "bmspec07",
      "bmspec08",
      "bmspec09",
      "bmspec10",
      "bmspec11",
      "bmspec12",
      "bmspec13",
      "bmspec14",
      "bmspec15",
      "bmspec16",
      "bmspec17",
      "bmspec18",
      "bmspec19",
      "bmspec20",
      "bmspec21",
      "bmspec22",
      "bmspec23",
      "bmspec24",
      "bmspec25",
      "bmspec26",
      "bmspec27",
      "bmspec28",
      "bmspec29",
      "bmspec30",
      "bmspec31",
      "bmspec32",
      "bmspec33",
      "bmspec34",
      "bmspec35",
      "bmspec#",
      "bmspec01",
      "bmspec02",
      "bmspec03",
      "bmspec04",
      "bmspec05",
      "bmspec06",
      "bmspec07",
      "bmspec08",
      "bmspec09",
      "bmspec10",
      "bmspec11",
      "bmspec12",
      "bmspec13",
      "bmspec14",
      "bmspec15",
      "bmspec16",
      "bmspec17",
      "bmspec18",
      "bmspec19",
      "bmspec20",
      "bmspec21",
      "bmspec22",
      "bmspec23",
      "bmspec24",
      "bmspec25",
      "bmspec26",
      "bmspec27",
      "bmspec28",
      "bmspec29",
      "bmspec30",
      "bmspec33",
      "bmspec34",
      "bmspec35",
      "bmspec36",
      "bmspec#",
      "bmspec01",
      "bmspec02",
      "bmspec03",
      "bmspec04",
      "bmspec05",
      "bmspec06",
      "bmspec07",
      "bmspec08",
      "bmspec09",
      "bmspec10",
      "bmspec11",
      "bmspec12",
      "bmspec13",
      "bmspec14",
      "bmspec15",
      "bmspec16",
      "bmspec17",
      "bmspec18",
      "bmspec19",
      "bmspec20",
      "bmspec21",
      "bmspec22",
      "bmspec23",
      "bmspec24",
      "bmspec25",
      "bmspec26",
      "bmspec27",
      "bmspec28",
      "bmspec29",
      "bmspec30",
      "bmspec31",
      "bmspec32",
      "cmspec#",
      "cmspec01",
      "cmspec02",
      "cmspec03",
      "cmspec04",
      "cmspec05",
      "cmspec06",
      "cmspec07",
      "cmspec08",
      "cmspec09",
      "cmspec10",
      "cmspec11",
      "cmspec12",
      "cmspec13",
      "cmspec14",
      "cmspec15",
      "cmspec16",
      "cmspec17",
      "cmspec18",
      "cmspec19",
      "cmspec20",
      "cmspec21",
      "cmspec22",
      "cmspec23",
      "cmspec24",
      "cmspec25",
      "cmspec26",
      "cmspec27",
      "cmspec28",
      "cmspec29",
      "cmspec30",
      "cmspec31",
      "cmspec32",
      "dmspec#",
      "dmspec01",
      "dmspec02",
      "dmspec03",
      "dmspec04",
      "dmspec05",
      "dmspec06",
      "dmspec07",
      "dmspec08",
      "dmspec09",
      "dmspec10",
      "dmspec11",
      "dmspec12",
      "dmspec13",
      "dmspec14",
      "dmspec15",
      "dmspec16",
      "dmspec17",
      "dmspec18",
      "dmspec19",
      "dmspec20",
      "dmspec21",
      "dmspec22",
      "dmspec23",
      "dmspec24",
      "dmspec25",
      "dmspec26",
      "dmspec27",
      "dmspec28",
      "dmspec29",
      "dmspec30",
      "dmspec31",
      "dmspec32",
      "dmspec33",
      "dmspec34",
      "emspec#",
      "emspec01",
      "emspec02",
      "emspec03",
      "emspec04",
      "emspec05",
      "emspec06",
      "emspec07",
      "emspec08",
      "emspec09",
      "emspec10",
      "emspec11",
      "emspec12",
      "emspec13",
      "emspec14",
      "emspec15",
      "emspec16",
      "emspec17",
      "emspec18",
      "emspec19",
      "emspec20",
      "emspec21",
      "emspec22",
      "emspec23",
      "emspec24",
      "emspec25",
      "emspec26",
      "emspec27",
      "emspec28",
      "emspec29",
      "emspec30",
      "emspec31",
      "emspec32",
      "emspec33",
      "emspec34",
      "fmspec#",
      "fmspec01",
      "fmspec02",
      "fmspec03",
      "fmspec04",
      "fmspec05",
      "fmspec06",
      "fmspec07",
      "fmspec08",
      "fmspec09",
      "fmspec10",
      "fmspec11",
      "fmspec12",
      "fmspec13",
      "fmspec14",
      "fmspec15",
      "fmspec16",
      "fmspec17",
      "fmspec18",
      "fmspec19",
      "fmspec20",
      "fmspec21",
      "fmspec22",
      "fmspec23",
      "fmspec24",
      "fmspec25",
      "fmspec26",
      "fmspec27",
      "fmspec28",
      "fmspec29",
      "fmspec30",
      "fmspec31",
      "fmspec32",
      "fmspec33",
      "fmspec34",
      "fmspec35",
      "gmspec#",
      "gmspec01",
      "gmspec02",
      "gmspec03",
      "gmspec04",
      "gmspec05",
      "gmspec06",
      "gmspec07",
      "gmspec08",
      "gmspec09",
      "gmspec10",
      "gmspec11",
      "gmspec12",
      "gmspec13",
      "gmspec14",
      "gmspec15",
      "gmspec16",
      "gmspec17",
      "gmspec18",
      "gmspec19",
      "gmspec20",
      "gmspec21",
      "gmspec22",
      "gmspec23",
      "gmspec24",
      "gmspec25",
      "gmspec26",
      "gmspec27",
      "gmspec28",
      "gmspec29",
      "gmspec30",
      "gmspec31",
      "gmspec32",
      "gmspec33",
      "gmspec34",
      "gmspec35",
      "hmspec#",
      "hmspec01",
      "hmspec02",
      "hmspec03",
      "hmspec04",
      "hmspec05",
      "hmspec06",
      "hmspec07",
      "hmspec08",
      "hmspec09",
      "hmspec10",
      "hmspec11",
      "hmspec12",
      "hmspec13",
      "hmspec14",
      "hmspec15",
      "hmspec16",
      "hmspec17",
      "hmspec18",
      "hmspec19",
      "hmspec20",
      "hmspec21",
      "hmspec22",
      "hmspec23",
      "hmspec24",
      "hmspec25",
      "hmspec26",
      "hmspec27",
      "hmspec28",
      "hmspec29",
      "hmspec30",
      "hmspec33",
      "hmspec34",
      "hmspec35",
      "hmspec36",
      "imspec#",
      "imspec01",
      "imspec02",
      "imspec03",
      "imspec04",
      "imspec05",
      "imspec06",
      "imspec07",
      "imspec08",
      "imspec09",
      "imspec10",
      "imspec11",
      "imspec12",
      "imspec13",
      "imspec14",
      "imspec15",
      "imspec16",
      "imspec17",
      "imspec18",
      "imspec19",
      "imspec20",
      "imspec21",
      "imspec22",
      "imspec23",
      "imspec24",
      "imspec25",
      "imspec26",
      "imspec27",
      "imspec28",
      "imspec29",
      "imspec30",
      "imspec33",
      "imspec34",
      "imspec35",
      "imspec36"
    ),
    canonical_name = c(
      "mspec#",
      "mspec01",
      "mspec02",
      "mspec03",
      "mspec04",
      "mspec05",
      "mspec06",
      "mspec07",
      "mspec08",
      "mspec09",
      "mspec10",
      "mspec11",
      "mspec12",
      "mspec13",
      "mspec14",
      "mspec15",
      "mspec16",
      "mspec17",
      "mspec18",
      "mspec19",
      "mspec20",
      "mspec21",
      "mspec22",
      "mspec23",
      "mspec24",
      "mspec25",
      "mspec26",
      "mspec27",
      "mspec28",
      "mspec29",
      "mspec30",
      "mspec31",
      "mspec32",
      "mspec33",
      "mspec34",
      "mspec35",
      "mspec#",
      "mspec01",
      "mspec02",
      "mspec03",
      "mspec04",
      "mspec05",
      "mspec06",
      "mspec07",
      "mspec08",
      "mspec09",
      "mspec10",
      "mspec11",
      "mspec12",
      "mspec13",
      "mspec14",
      "mspec15",
      "mspec16",
      "mspec17",
      "mspec18",
      "mspec19",
      "mspec20",
      "mspec21",
      "mspec22",
      "mspec23",
      "mspec24",
      "mspec25",
      "mspec26",
      "mspec27",
      "mspec28",
      "mspec29",
      "mspec30",
      "mspec33",
      "mspec34",
      "mspec35",
      "mspec36",
      "mspec#",
      "mspec01",
      "mspec02",
      "mspec03",
      "mspec04",
      "mspec05",
      "mspec06",
      "mspec07",
      "mspec08",
      "mspec09",
      "mspec10",
      "mspec11",
      "mspec12",
      "mspec13",
      "mspec14",
      "mspec15",
      "mspec16",
      "mspec17",
      "mspec18",
      "mspec19",
      "mspec20",
      "mspec21",
      "mspec22",
      "mspec23",
      "mspec24",
      "mspec25",
      "mspec26",
      "mspec27",
      "mspec28",
      "mspec29",
      "mspec30",
      "mspec31",
      "mspec32",
      "mspec#",
      "mspec01",
      "mspec02",
      "mspec03",
      "mspec04",
      "mspec05",
      "mspec06",
      "mspec07",
      "mspec08",
      "mspec09",
      "mspec10",
      "mspec11",
      "mspec12",
      "mspec13",
      "mspec14",
      "mspec15",
      "mspec16",
      "mspec17",
      "mspec18",
      "mspec19",
      "mspec20",
      "mspec21",
      "mspec22",
      "mspec23",
      "mspec24",
      "mspec25",
      "mspec26",
      "mspec27",
      "mspec28",
      "mspec29",
      "mspec30",
      "mspec31",
      "mspec32",
      "mspec#",
      "mspec01",
      "mspec02",
      "mspec03",
      "mspec04",
      "mspec05",
      "mspec06",
      "mspec07",
      "mspec08",
      "mspec09",
      "mspec10",
      "mspec11",
      "mspec12",
      "mspec13",
      "mspec14",
      "mspec15",
      "mspec16",
      "mspec17",
      "mspec18",
      "mspec19",
      "mspec20",
      "mspec21",
      "mspec22",
      "mspec23",
      "mspec24",
      "mspec25",
      "mspec26",
      "mspec27",
      "mspec28",
      "mspec29",
      "mspec30",
      "mspec31",
      "mspec32",
      "mspec33",
      "mspec34",
      "mspec#",
      "mspec01",
      "mspec02",
      "mspec03",
      "mspec04",
      "mspec05",
      "mspec06",
      "mspec07",
      "mspec08",
      "mspec09",
      "mspec10",
      "mspec11",
      "mspec12",
      "mspec13",
      "mspec14",
      "mspec15",
      "mspec16",
      "mspec17",
      "mspec18",
      "mspec19",
      "mspec20",
      "mspec21",
      "mspec22",
      "mspec23",
      "mspec24",
      "mspec25",
      "mspec26",
      "mspec27",
      "mspec28",
      "mspec29",
      "mspec30",
      "mspec31",
      "mspec32",
      "mspec33",
      "mspec34",
      "mspec#",
      "mspec01",
      "mspec02",
      "mspec03",
      "mspec04",
      "mspec05",
      "mspec06",
      "mspec07",
      "mspec08",
      "mspec09",
      "mspec10",
      "mspec11",
      "mspec12",
      "mspec13",
      "mspec14",
      "mspec15",
      "mspec16",
      "mspec17",
      "mspec18",
      "mspec19",
      "mspec20",
      "mspec21",
      "mspec22",
      "mspec23",
      "mspec24",
      "mspec25",
      "mspec26",
      "mspec27",
      "mspec28",
      "mspec29",
      "mspec30",
      "mspec31",
      "mspec32",
      "mspec33",
      "mspec34",
      "mspec35",
      "mspec#",
      "mspec01",
      "mspec02",
      "mspec03",
      "mspec04",
      "mspec05",
      "mspec06",
      "mspec07",
      "mspec08",
      "mspec09",
      "mspec10",
      "mspec11",
      "mspec12",
      "mspec13",
      "mspec14",
      "mspec15",
      "mspec16",
      "mspec17",
      "mspec18",
      "mspec19",
      "mspec20",
      "mspec21",
      "mspec22",
      "mspec23",
      "mspec24",
      "mspec25",
      "mspec26",
      "mspec27",
      "mspec28",
      "mspec29",
      "mspec30",
      "mspec31",
      "mspec32",
      "mspec33",
      "mspec34",
      "mspec35",
      "mspec#",
      "mspec01",
      "mspec02",
      "mspec03",
      "mspec04",
      "mspec05",
      "mspec06",
      "mspec07",
      "mspec08",
      "mspec09",
      "mspec10",
      "mspec11",
      "mspec12",
      "mspec13",
      "mspec14",
      "mspec15",
      "mspec16",
      "mspec17",
      "mspec18",
      "mspec19",
      "mspec20",
      "mspec21",
      "mspec22",
      "mspec23",
      "mspec24",
      "mspec25",
      "mspec26",
      "mspec27",
      "mspec28",
      "mspec29",
      "mspec30",
      "mspec33",
      "mspec34",
      "mspec35",
      "mspec36",
      "mspec#",
      "mspec01",
      "mspec02",
      "mspec03",
      "mspec04",
      "mspec05",
      "mspec06",
      "mspec07",
      "mspec08",
      "mspec09",
      "mspec10",
      "mspec11",
      "mspec12",
      "mspec13",
      "mspec14",
      "mspec15",
      "mspec16",
      "mspec17",
      "mspec18",
      "mspec19",
      "mspec20",
      "mspec21",
      "mspec22",
      "mspec23",
      "mspec24",
      "mspec25",
      "mspec26",
      "mspec27",
      "mspec28",
      "mspec29",
      "mspec30",
      "mspec33",
      "mspec34",
      "mspec35",
      "mspec36"
    ),
    variable_label = c(
      "# of specialists reported",
      "internist",
      "lung specialist",
      "cardiologist",
      "endocrinologist",
      "gastro-enterologist",
      "nephrologist",
      "rheumatologist",
      "haemotologist",
      "oncologist",
      "geriatrist",
      "neurologist",
      "rehabilitation specialist",
      "dermatologist",
      "radiologist",
      "radiotherapist",
      "nuclear medicine physician",
      "surgeon",
      "vascular surgeon",
      "orthopaedist",
      "urologist",
      "plastic surgeon",
      "chest surgeon",
      "neurosurgeon",
      "oral/dental surgeon",
      "anaesthesiologist",
      "gynaecologist",
      "ear/nose/throat specialist",
      "opthalmologist",
      "clinical chemist / blood examination",
      "audiologist",
      "psychologist",
      "chiropractor",
      "phlebologist",
      "podologist",
      "tropical doctor",
      "# of specialists reported",
      "internist",
      "lung specialist",
      "cardiologist",
      "endocrinologist",
      "gastro-enterologist",
      "nephrologist",
      "rheumatologist",
      "haemotologist",
      "oncologist",
      "geriatrist",
      "neurologist",
      "rehabilitation specialist",
      "dermatologist",
      "radiologist",
      "radiotherapist",
      "nuclear medicine physician",
      "surgeon",
      "vascular surgeon",
      "orthopaedist",
      "urologist",
      "plastic surgeon",
      "chest surgeon",
      "neurosurgeon",
      "oral/dental surgeon",
      "anaesthesiologist",
      "gynaecologist",
      "ear/nose/throat specialist",
      "opthalmologist",
      "clinical chemist / blood examination",
      "audiologist",
      "phlebologist",
      "podologist",
      "geneticist",
      "medical microbiologist",
      "# of specialists reported",
      "internist",
      "lung specialist",
      "cardiologist",
      "endocrinologist",
      "gastro-enterologist",
      "nephrologist",
      "rheumatologist",
      "haemotologist",
      "oncologist",
      "geriatrist",
      "neurologist",
      "rehabilitation specialist",
      "dermatologist",
      "radiologist",
      "radiotherapist",
      "nuclear medicine physician",
      "surgeon",
      "vascular surgeon",
      "orthopaedist",
      "urologist",
      "plastic surgeon",
      "chest surgeon",
      "neurosurgeon",
      "oral/dental surgeon",
      "anaesthesiologist",
      "gynaecologist",
      "ear/nose/throat specialist",
      "opthalmologist",
      "clinical chemist / blood examination",
      "audiologist",
      "psychologist",
      "chiropractor",
      "# of specialists reported",
      "internist",
      "lung specialist",
      "cardiologist",
      "endocrinologist",
      "gastro-enterologist",
      "nephrologist",
      "rheumatologist",
      "haemotologist",
      "oncologist",
      "geriatrist",
      "neurologist",
      "rehabilitation specialist",
      "dermatologist",
      "radiologist",
      "radiotherapist",
      "nuclear medicine physician",
      "surgeon",
      "vascular surgeon",
      "orthopaedist",
      "urologist",
      "plastic surgeon",
      "chest surgeon",
      "neurosurgeon",
      "oral/dental surgeon",
      "anaesthesiologist",
      "gynaecologist",
      "ear/nose/throat specialist",
      "opthalmologist",
      "clinical chemist / blood examination",
      "audiologist",
      "psychologist",
      "chiropractor",
      "# of specialists reported",
      "internist",
      "lung specialist",
      "cardiologist",
      "endocrinologist",
      "gastro-enterologist",
      "nephrologist",
      "rheumatologist",
      "haemotologist",
      "oncologist",
      "geriatrist",
      "neurologist",
      "rehabilitation specialist",
      "dermatologist",
      "radiologist",
      "radiotherapist",
      "nuclear medicine physician",
      "surgeon",
      "vascular surgeon",
      "orthopaedist",
      "urologist",
      "plastic surgeon",
      "chest surgeon",
      "neurosurgeon",
      "oral/dental surgeon",
      "anaesthesiologist",
      "gynaecologist",
      "ear/nose/throat specialist",
      "opthalmologist",
      "clinical chemist / blood examination",
      "audiologist",
      "psychologist",
      "chiropractor",
      "phlebologist",
      "podologist",
      "# of specialists reported",
      "internist",
      "lung specialist",
      "cardiologist",
      "endocrinologist",
      "gastro-enterologist",
      "nephrologist",
      "rheumatologist",
      "haemotologist",
      "oncologist",
      "geriatrist",
      "neurologist",
      "rehabilitation specialist",
      "dermatologist",
      "radiologist",
      "radiotherapist",
      "nuclear medicine physician",
      "surgeon",
      "vascular surgeon",
      "orthopaedist",
      "urologist",
      "plastic surgeon",
      "chest surgeon",
      "neurosurgeon",
      "oral/dental surgeon",
      "anaesthesiologist",
      "gynaecologist",
      "ear/nose/throat specialist",
      "opthalmologist",
      "clinical chemist / blood examination",
      "audiologist",
      "psychologist",
      "chiropractor",
      "phlebologist",
      "podologist",
      "# of specialists reported",
      "internist",
      "lung specialist",
      "cardiologist",
      "endocrinologist",
      "gastro-enterologist",
      "nephrologist",
      "rheumatologist",
      "haemotologist",
      "oncologist",
      "geriatrist",
      "neurologist",
      "rehabilitation specialist",
      "dermatologist",
      "radiologist",
      "radiotherapist",
      "nuclear medicine physician",
      "surgeon",
      "vascular surgeon",
      "orthopaedist",
      "urologist",
      "plastic surgeon",
      "chest surgeon",
      "neurosurgeon",
      "oral/dental surgeon",
      "anaesthesiologist",
      "gynaecologist",
      "ear/nose/throat specialist",
      "opthalmologist",
      "clinical chemist / blood examination",
      "audiologist",
      "psychologist",
      "chiropractor",
      "phlebologist",
      "podologist",
      "geneticist",
      "# of specialists reported",
      "internist",
      "lung specialist",
      "cardiologist",
      "endocrinologist",
      "gastro-enterologist",
      "nephrologist",
      "rheumatologist",
      "haemotologist",
      "oncologist",
      "geriatrist",
      "neurologist",
      "rehabilitation specialist",
      "dermatologist",
      "radiologist",
      "radiotherapist",
      "nuclear medicine physician",
      "surgeon",
      "vascular surgeon",
      "orthopaedist",
      "urologist",
      "plastic surgeon",
      "chest surgeon",
      "neurosurgeon",
      "oral/dental surgeon",
      "anaesthesiologist",
      "gynaecologist",
      "ear/nose/throat specialist",
      "opthalmologist",
      "clinical chemist / blood examination",
      "audiologist",
      "psychologist",
      "chiropractor",
      "phlebologist",
      "podologist",
      "geneticist",
      "# of specialists reported",
      "internist",
      "lung specialist",
      "cardiologist",
      "endocrinologist",
      "gastro-enterologist",
      "nephrologist",
      "rheumatologist",
      "haemotologist",
      "oncologist",
      "geriatrist",
      "neurologist",
      "rehabilitation specialist",
      "dermatologist",
      "radiologist",
      "radiotherapist",
      "nuclear medicine physician",
      "surgeon",
      "vascular surgeon",
      "orthopaedist",
      "urologist",
      "plastic surgeon",
      "chest surgeon",
      "neurosurgeon",
      "oral/dental surgeon",
      "anaesthesiologist",
      "gynaecologist",
      "ear/nose/throat specialist",
      "opthalmologist",
      "clinical chemist / blood examination",
      "audiologist",
      "phlebologist",
      "podologist",
      "geneticist",
      "medical microbiologist",
      "# of specialists reported",
      "internist",
      "lung specialist",
      "cardiologist",
      "endocrinologist",
      "gastro-enterologist",
      "nephrologist",
      "rheumatologist",
      "haemotologist",
      "oncologist",
      "geriatrist",
      "neurologist",
      "rehabilitation specialist",
      "dermatologist",
      "radiologist",
      "radiotherapist",
      "nuclear medicine physician",
      "surgeon",
      "vascular surgeon",
      "orthopaedist",
      "urologist",
      "plastic surgeon",
      "chest surgeon",
      "neurosurgeon",
      "oral/dental surgeon",
      "anaesthesiologist",
      "gynaecologist",
      "ear/nose/throat specialist",
      "opthalmologist",
      "clinical chemist / blood examination",
      "audiologist",
      "phlebologist",
      "podologist",
      "geneticist",
      "medical microbiologist"
    ),
    harmonized_var_label = c(
      "Number of medical specialists reported",
      "Internist",
      "Lung specialist",
      "Cardiologist",
      "Endocrinologist",
      "Gastro-enterologist",
      "Nephrologist",
      "Rheumatologist",
      "Haemotologist",
      "Oncologist",
      "Geriatrist",
      "Neurologist",
      "Rehabilitation specialist",
      "Dermatologist",
      "Radiologist",
      "Radiotherapist",
      "Nuclear medicine physician",
      "Surgeon",
      "Vascular surgeon",
      "Orthopaedist",
      "Urologist",
      "Plastic surgeon",
      "Chest surgeon",
      "Neurosurgeon",
      "Oral/dental surgeon",
      "Anaesthesiologist",
      "Gynaecologist",
      "Ear/nose/throat specialist",
      "Opthalmologist",
      "Clinical chemist / blood examination",
      "Audiologist",
      "Psychologist",
      "Chiropractor",
      "Phlebologist",
      "Podologist",
      "Medical specialist type 35",
      "Number of medical specialists reported",
      "Internist",
      "Lung specialist",
      "Cardiologist",
      "Endocrinologist",
      "Gastro-enterologist",
      "Nephrologist",
      "Rheumatologist",
      "Haemotologist",
      "Oncologist",
      "Geriatrist",
      "Neurologist",
      "Rehabilitation specialist",
      "Dermatologist",
      "Radiologist",
      "Radiotherapist",
      "Nuclear medicine physician",
      "Surgeon",
      "Vascular surgeon",
      "Orthopaedist",
      "Urologist",
      "Plastic surgeon",
      "Chest surgeon",
      "Neurosurgeon",
      "Oral/dental surgeon",
      "Anaesthesiologist",
      "Gynaecologist",
      "Ear/nose/throat specialist",
      "Opthalmologist",
      "Clinical chemist / blood examination",
      "Audiologist",
      "Phlebologist",
      "Podologist",
      "Medical specialist type 35",
      "Medical microbiologist",
      "Number of medical specialists reported",
      "Internist",
      "Lung specialist",
      "Cardiologist",
      "Endocrinologist",
      "Gastro-enterologist",
      "Nephrologist",
      "Rheumatologist",
      "Haemotologist",
      "Oncologist",
      "Geriatrist",
      "Neurologist",
      "Rehabilitation specialist",
      "Dermatologist",
      "Radiologist",
      "Radiotherapist",
      "Nuclear medicine physician",
      "Surgeon",
      "Vascular surgeon",
      "Orthopaedist",
      "Urologist",
      "Plastic surgeon",
      "Chest surgeon",
      "Neurosurgeon",
      "Oral/dental surgeon",
      "Anaesthesiologist",
      "Gynaecologist",
      "Ear/nose/throat specialist",
      "Opthalmologist",
      "Clinical chemist / blood examination",
      "Audiologist",
      "Psychologist",
      "Chiropractor",
      "Number of medical specialists reported",
      "Internist",
      "Lung specialist",
      "Cardiologist",
      "Endocrinologist",
      "Gastro-enterologist",
      "Nephrologist",
      "Rheumatologist",
      "Haemotologist",
      "Oncologist",
      "Geriatrist",
      "Neurologist",
      "Rehabilitation specialist",
      "Dermatologist",
      "Radiologist",
      "Radiotherapist",
      "Nuclear medicine physician",
      "Surgeon",
      "Vascular surgeon",
      "Orthopaedist",
      "Urologist",
      "Plastic surgeon",
      "Chest surgeon",
      "Neurosurgeon",
      "Oral/dental surgeon",
      "Anaesthesiologist",
      "Gynaecologist",
      "Ear/nose/throat specialist",
      "Opthalmologist",
      "Clinical chemist / blood examination",
      "Audiologist",
      "Psychologist",
      "Chiropractor",
      "Number of medical specialists reported",
      "Internist",
      "Lung specialist",
      "Cardiologist",
      "Endocrinologist",
      "Gastro-enterologist",
      "Nephrologist",
      "Rheumatologist",
      "Haemotologist",
      "Oncologist",
      "Geriatrist",
      "Neurologist",
      "Rehabilitation specialist",
      "Dermatologist",
      "Radiologist",
      "Radiotherapist",
      "Nuclear medicine physician",
      "Surgeon",
      "Vascular surgeon",
      "Orthopaedist",
      "Urologist",
      "Plastic surgeon",
      "Chest surgeon",
      "Neurosurgeon",
      "Oral/dental surgeon",
      "Anaesthesiologist",
      "Gynaecologist",
      "Ear/nose/throat specialist",
      "Opthalmologist",
      "Clinical chemist / blood examination",
      "Audiologist",
      "Psychologist",
      "Chiropractor",
      "Phlebologist",
      "Podologist",
      "Number of medical specialists reported",
      "Internist",
      "Lung specialist",
      "Cardiologist",
      "Endocrinologist",
      "Gastro-enterologist",
      "Nephrologist",
      "Rheumatologist",
      "Haemotologist",
      "Oncologist",
      "Geriatrist",
      "Neurologist",
      "Rehabilitation specialist",
      "Dermatologist",
      "Radiologist",
      "Radiotherapist",
      "Nuclear medicine physician",
      "Surgeon",
      "Vascular surgeon",
      "Orthopaedist",
      "Urologist",
      "Plastic surgeon",
      "Chest surgeon",
      "Neurosurgeon",
      "Oral/dental surgeon",
      "Anaesthesiologist",
      "Gynaecologist",
      "Ear/nose/throat specialist",
      "Opthalmologist",
      "Clinical chemist / blood examination",
      "Audiologist",
      "Psychologist",
      "Chiropractor",
      "Phlebologist",
      "Podologist",
      "Number of medical specialists reported",
      "Internist",
      "Lung specialist",
      "Cardiologist",
      "Endocrinologist",
      "Gastro-enterologist",
      "Nephrologist",
      "Rheumatologist",
      "Haemotologist",
      "Oncologist",
      "Geriatrist",
      "Neurologist",
      "Rehabilitation specialist",
      "Dermatologist",
      "Radiologist",
      "Radiotherapist",
      "Nuclear medicine physician",
      "Surgeon",
      "Vascular surgeon",
      "Orthopaedist",
      "Urologist",
      "Plastic surgeon",
      "Chest surgeon",
      "Neurosurgeon",
      "Oral/dental surgeon",
      "Anaesthesiologist",
      "Gynaecologist",
      "Ear/nose/throat specialist",
      "Opthalmologist",
      "Clinical chemist / blood examination",
      "Audiologist",
      "Psychologist",
      "Chiropractor",
      "Phlebologist",
      "Podologist",
      "Medical specialist type 35",
      "Number of medical specialists reported",
      "Internist",
      "Lung specialist",
      "Cardiologist",
      "Endocrinologist",
      "Gastro-enterologist",
      "Nephrologist",
      "Rheumatologist",
      "Haemotologist",
      "Oncologist",
      "Geriatrist",
      "Neurologist",
      "Rehabilitation specialist",
      "Dermatologist",
      "Radiologist",
      "Radiotherapist",
      "Nuclear medicine physician",
      "Surgeon",
      "Vascular surgeon",
      "Orthopaedist",
      "Urologist",
      "Plastic surgeon",
      "Chest surgeon",
      "Neurosurgeon",
      "Oral/dental surgeon",
      "Anaesthesiologist",
      "Gynaecologist",
      "Ear/nose/throat specialist",
      "Opthalmologist",
      "Clinical chemist / blood examination",
      "Audiologist",
      "Psychologist",
      "Chiropractor",
      "Phlebologist",
      "Podologist",
      "Medical specialist type 35",
      "Number of medical specialists reported",
      "Internist",
      "Lung specialist",
      "Cardiologist",
      "Endocrinologist",
      "Gastro-enterologist",
      "Nephrologist",
      "Rheumatologist",
      "Haemotologist",
      "Oncologist",
      "Geriatrist",
      "Neurologist",
      "Rehabilitation specialist",
      "Dermatologist",
      "Radiologist",
      "Radiotherapist",
      "Nuclear medicine physician",
      "Surgeon",
      "Vascular surgeon",
      "Orthopaedist",
      "Urologist",
      "Plastic surgeon",
      "Chest surgeon",
      "Neurosurgeon",
      "Oral/dental surgeon",
      "Anaesthesiologist",
      "Gynaecologist",
      "Ear/nose/throat specialist",
      "Opthalmologist",
      "Clinical chemist / blood examination",
      "Audiologist",
      "Phlebologist",
      "Podologist",
      "Medical specialist type 35",
      "Medical microbiologist",
      "Number of medical specialists reported",
      "Internist",
      "Lung specialist",
      "Cardiologist",
      "Endocrinologist",
      "Gastro-enterologist",
      "Nephrologist",
      "Rheumatologist",
      "Haemotologist",
      "Oncologist",
      "Geriatrist",
      "Neurologist",
      "Rehabilitation specialist",
      "Dermatologist",
      "Radiologist",
      "Radiotherapist",
      "Nuclear medicine physician",
      "Surgeon",
      "Vascular surgeon",
      "Orthopaedist",
      "Urologist",
      "Plastic surgeon",
      "Chest surgeon",
      "Neurosurgeon",
      "Oral/dental surgeon",
      "Anaesthesiologist",
      "Gynaecologist",
      "Ear/nose/throat specialist",
      "Opthalmologist",
      "Clinical chemist / blood examination",
      "Audiologist",
      "Phlebologist",
      "Podologist",
      "Medical specialist type 35",
      "Medical microbiologist"
    ),
    var_type = c(
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    `mspec#` = list(
      `2B` = c(`-2` = "na, see BMEDSPEC in LASA2B045", `-1` = "na, asked"),
      `3B` = c(`-2` = "na, see BMEDSPEC in LASA3B045", `-1` = "na, asked"),
      B = c(`-4` = "na, short version", `-2` = "na, see BMEDSPEC in LASAB045", `-1` = "na, asked"),
      C = c(`-2` = "na, see CMEDSPEC in LASAC045", `-1` = "na, asked"),
      D = c(`-2` = "na, see DMEDSPEC in LASAD045", `-1` = "na, asked"),
      E = c(`-2` = "na, see EMEDSPEC in LASAE045", `-1` = "na, asked"),
      F = c(`-2` = "na, see FMEDSPEC in LASAF045", `-1` = "na, asked"),
      G = c(`-2` = "na, see GMEDSPEC in LASAG045", `-1` = "na, asked"),
      H = c(`-2` = "na, see HMEDSPEC in LASAH045", `-1` = "na, asked"),
      I = c(`-2` = "na, see IMEDSPEC in LASAI045", `-1` = "na, asked")
    ),
    mspec01 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec02 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec03 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec04 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec05 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec06 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec07 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec08 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec09 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec10 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec11 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec12 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec13 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec14 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec15 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec16 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec17 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec18 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec19 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec20 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec21 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec22 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec23 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec24 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec25 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec26 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec27 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec28 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec29 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec30 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec31 = list(
      `2B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4
    ),
    mspec32 = list(
      `2B` = not_reported_reported,
      B = not_reported_reported,
      C = not_reported_reported_9,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4
    ),
    mspec33 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec34 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      D = not_reported_reported_5,
      E = not_reported_reported_6,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec35 = list(
      `2B` = not_reported_reported,
      `3B` = not_reported_reported,
      F = not_reported_reported_3,
      G = not_reported_reported_4,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    ),
    mspec36 = list(
      `3B` = not_reported_reported,
      H = not_reported_reported_7,
      I = not_reported_reported_8
    )
  ),

  value_labels_harmonized = list(
    `mspec#` = c(
      `-4` = "short version",
      `-2` = "not applicable, see medical specialist contact",
      `-1` = "asked / no answer"
    ),
    mspec01 = not_reported_reported_2,
    mspec02 = not_reported_reported_2,
    mspec03 = not_reported_reported_2,
    mspec04 = not_reported_reported_2,
    mspec05 = not_reported_reported_2,
    mspec06 = not_reported_reported_2,
    mspec07 = not_reported_reported_2,
    mspec08 = not_reported_reported_2,
    mspec09 = not_reported_reported_2,
    mspec10 = not_reported_reported_2,
    mspec11 = not_reported_reported_2,
    mspec12 = not_reported_reported_2,
    mspec13 = not_reported_reported_2,
    mspec14 = not_reported_reported_2,
    mspec15 = not_reported_reported_2,
    mspec16 = not_reported_reported_2,
    mspec17 = not_reported_reported_2,
    mspec18 = not_reported_reported_2,
    mspec19 = not_reported_reported_2,
    mspec20 = not_reported_reported_2,
    mspec21 = not_reported_reported_2,
    mspec22 = not_reported_reported_2,
    mspec23 = not_reported_reported_2,
    mspec24 = not_reported_reported_2,
    mspec25 = not_reported_reported_2,
    mspec26 = not_reported_reported_2,
    mspec27 = not_reported_reported_2,
    mspec28 = not_reported_reported_2,
    mspec29 = not_reported_reported_2,
    mspec30 = not_reported_reported_2,
    mspec31 = not_reported_reported_2,
    mspec32 = not_reported_reported_2,
    mspec33 = not_reported_reported_2,
    mspec34 = not_reported_reported_2,
    mspec35 = not_reported_reported_2,
    mspec36 = not_reported_reported_2
  )
)
