## LASA filecode 011 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_011 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "C",
      "D",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB"
    ),
    variable_name = c(
      "bnupers",
      "bhhnch",
      "bhhnnonk",
      "bhhnothf",
      "bhhnsib",
      "bhhnstch",
      "bhhpart",
      "bnupers",
      "bnupers",
      "cnupers",
      "dnupers",
      "enupers",
      "fhhnch",
      "fhhnnonk",
      "fhhnothf",
      "fhhnsib",
      "fhhnstch",
      "fhhpart",
      "fnupers",
      "ghhnch",
      "ghhnnonk",
      "ghhnothf",
      "ghhnsib",
      "ghhnstch",
      "ghhpart",
      "gnupers",
      "hhhnch",
      "hhhnnonk",
      "hhhnothf",
      "hhhnsib",
      "hhhnstch",
      "hhhpart",
      "hnupers",
      "ihhnch",
      "ihhnnonk",
      "ihhnothf",
      "ihhnsib",
      "ihhnstch",
      "ihhpart",
      "inupers",
      "jhhnch",
      "jhhnnonk",
      "jhhnothf",
      "jhhnsib",
      "jhhnstch",
      "jhhpart",
      "jnupers",
      "khhnch",
      "khhnnonk",
      "khhnothf",
      "khhnsib",
      "khhnstch",
      "khhpart",
      "knupers",
      "bnupers"
    ),
    canonical_name = c(
      "nupers",
      "hhnch",
      "hhnnonk",
      "hhnothf",
      "hhnsib",
      "hhnstch",
      "hhpart",
      "nupers",
      "nupers",
      "nupers",
      "nupers",
      "nupers",
      "hhnch",
      "hhnnonk",
      "hhnothf",
      "hhnsib",
      "hhnstch",
      "hhpart",
      "nupers",
      "hhnch",
      "hhnnonk",
      "hhnothf",
      "hhnsib",
      "hhnstch",
      "hhpart",
      "nupers",
      "hhnch",
      "hhnnonk",
      "hhnothf",
      "hhnsib",
      "hhnstch",
      "hhpart",
      "nupers",
      "hhnch",
      "hhnnonk",
      "hhnothf",
      "hhnsib",
      "hhnstch",
      "hhpart",
      "nupers",
      "hhnch",
      "hhnnonk",
      "hhnothf",
      "hhnsib",
      "hhnstch",
      "hhpart",
      "nupers",
      "hhnch",
      "hhnnonk",
      "hhnothf",
      "hhnsib",
      "hhnstch",
      "hhpart",
      "nupers",
      "nupers"
    ),
    variable_label = c(
      "# other persons in household (partner excluded)",
      "number of children in household",
      "number of nonkin persons in household",
      "number of other family members in household",
      "number of siblings in household",
      "number of stepchildren in household",
      "partner in household",
      "# other persons in household",
      "Number of persons in household",
      "# other persons in household (partner excluded)",
      "# other persons in household (partner excluded)",
      "# other persons in household (partner excluded)",
      "number of children in household",
      "number of nonkin persons in household",
      "number of other family members in household",
      "number of siblings in household",
      "number of stepchildren in household",
      "partner in household",
      "# other persons in household",
      "number of children in household",
      "number of nonkin persons in household",
      "number of other family members in household",
      "number of siblings in household",
      "number of stepchildren in household",
      "partner in household",
      "# other persons in household",
      "number of children in household",
      "number of nonkin persons in household",
      "number of other family members in household",
      "number of siblings in household",
      "number of stepchildren in household",
      "partner in household",
      "# other persons in household",
      "number of children in household",
      "number of nonkin persons in household",
      "number of other family members in household",
      "number of siblings in household",
      "number of stepchildren in household",
      "partner in household",
      "# other persons in household",
      "number of children in household",
      "number of nonkin persons in household",
      "number of other family members in household",
      "number of siblings in household",
      "number of stepchildren in household",
      "partner in household",
      "# other persons in household",
      "number of children in household",
      "number of nonkin persons in household",
      "number of other family members in household",
      "number of siblings in household",
      "number of stepchildren in household",
      "partner in household",
      "# other persons in household",
      "# other persons in household"
    ),
    harmonized_var_label = c(
      "Number of other persons in household",
      "Number of children in household",
      "Number of nonkin persons in household",
      "Number of other family members in household",
      "Number of siblings in household",
      "Number of stepchildren in household",
      "Partner in household",
      "Number of other persons in household",
      "Number of other persons in household",
      "Number of other persons in household",
      "Number of other persons in household",
      "Number of other persons in household",
      "Number of children in household",
      "Number of nonkin persons in household",
      "Number of other family members in household",
      "Number of siblings in household",
      "Number of stepchildren in household",
      "Partner in household",
      "Number of other persons in household",
      "Number of children in household",
      "Number of nonkin persons in household",
      "Number of other family members in household",
      "Number of siblings in household",
      "Number of stepchildren in household",
      "Partner in household",
      "Number of other persons in household",
      "Number of children in household",
      "Number of nonkin persons in household",
      "Number of other family members in household",
      "Number of siblings in household",
      "Number of stepchildren in household",
      "Partner in household",
      "Number of other persons in household",
      "Number of children in household",
      "Number of nonkin persons in household",
      "Number of other family members in household",
      "Number of siblings in household",
      "Number of stepchildren in household",
      "Partner in household",
      "Number of other persons in household",
      "Number of children in household",
      "Number of nonkin persons in household",
      "Number of other family members in household",
      "Number of siblings in household",
      "Number of stepchildren in household",
      "Partner in household",
      "Number of other persons in household",
      "Number of children in household",
      "Number of nonkin persons in household",
      "Number of other family members in household",
      "Number of siblings in household",
      "Number of stepchildren in household",
      "Partner in household",
      "Number of other persons in household",
      "Number of other persons in household"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    nupers = list(
      `2B` = none_3,
      `3B` = none_2,
      B = c(`-3` = "na, wrong skip", `-2` = "na, not liv independently", `0` = "none"),
      C = none_3,
      D = none_3,
      E = none_3,
      F = none_2,
      G = none_2,
      H = none_2,
      I = none_2,
      J = none_2,
      K = none_2,
      MB = c(`-3` = "na, wrong skip", `-1` = "na, asked", `0` = "none")
    ),
    hhnch = list(
      `3B` = na_see_f_g_h_b_i_j_knupers,
      F = na_see_f_g_h_b_i_j_knupers,
      G = na_see_f_g_h_b_i_j_knupers,
      H = na_see_f_g_h_b_i_j_knupers,
      I = na_see_f_g_h_b_i_j_knupers,
      J = na_see_f_g_h_b_i_j_knupers,
      K = na_see_f_g_h_b_i_j_knupers
    ),
    hhnnonk = list(
      `3B` = na_see_f_g_h_b_i_j_knupers,
      F = na_see_f_g_h_b_i_j_knupers,
      G = na_see_f_g_h_b_i_j_knupers,
      H = na_see_f_g_h_b_i_j_knupers,
      I = na_see_f_g_h_b_i_j_knupers,
      J = na_see_f_g_h_b_i_j_knupers,
      K = na_see_f_g_h_b_i_j_knupers
    ),
    hhnothf = list(
      `3B` = na_see_f_g_h_b_i_j_knupers,
      F = na_see_f_g_h_b_i_j_knupers,
      G = na_see_f_g_h_b_i_j_knupers,
      H = na_see_f_g_h_b_i_j_knupers,
      I = na_see_f_g_h_b_i_j_knupers,
      J = na_see_f_g_h_b_i_j_knupers,
      K = na_see_f_g_h_b_i_j_knupers
    ),
    hhnsib = list(
      `3B` = na_see_f_g_h_b_i_j_knupers,
      F = na_see_f_g_h_b_i_j_knupers,
      G = na_see_f_g_h_b_i_j_knupers,
      H = na_see_f_g_h_b_i_j_knupers,
      I = na_see_f_g_h_b_i_j_knupers,
      J = na_see_f_g_h_b_i_j_knupers,
      K = na_see_f_g_h_b_i_j_knupers
    ),
    hhnstch = list(
      `3B` = na_see_f_g_h_b_i_j_knupers,
      F = na_see_f_g_h_b_i_j_knupers,
      G = na_see_f_g_h_b_i_j_knupers,
      H = na_see_f_g_h_b_i_j_knupers,
      I = na_see_f_g_h_b_i_j_knupers,
      J = na_see_f_g_h_b_i_j_knupers,
      K = na_see_f_g_h_b_i_j_knupers
    ),
    hhpart = list(
      `3B` = no_partner_in_household_partner_in_household,
      F = no_partner_in_household_partner_in_household,
      G = no_partner_in_household_partner_in_household,
      H = no_partner_in_household_partner_in_household,
      I = no_partner_in_household_partner_in_household,
      J = no_partner_in_household_partner_in_household,
      K = no_partner_in_household_partner_in_household
    )
  ),

  value_labels_harmonized = list(
    hhnch = not_available_routing,
    hhnnonk = not_available_routing,
    hhnothf = not_available_routing,
    hhnsib = not_available_routing,
    hhnstch = not_available_routing,
    hhpart = c(
      `-2` = "not available, routing",
      `0` = "no partner in household",
      `1` = "partner in household"
    ),
    nupers = c(
      `-3` = "not available, wrong skip",
      `-2` = "not available",
      `-1` = "not available, asked",
      `0` = "none"
    )
  )
)
