## LASA filecode 036 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_036 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "B",
      "B",
      "C",
      "C",
      "D",
      "D",
      "E",
      "E",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bsubhea1",
      "bsubhea2",
      "bsubhea3",
      "bsubhea1",
      "bsubhea2",
      "bsubhea1",
      "bsubhea2",
      "csubhea1",
      "csubhea2",
      "dsubhea1",
      "dsubhea2",
      "esubhea1",
      "esubhea2",
      "fsubhea1",
      "fsubhea2",
      "fsubhea4",
      "gsubhea1",
      "gsubhea2",
      "gsubhea4",
      "hsubhea1",
      "hsubhea2",
      "hsubhea4",
      "isubhea1",
      "isubhea2",
      "isubhea4",
      "jsubhea1",
      "jsubhea2",
      "jsubhea4",
      "ksubhea1",
      "ksubhea2",
      "ksubhea4"
    ),
    canonical_name = c(
      "subhea1",
      "subhea2",
      "subhea3",
      "subhea1",
      "subhea2",
      "subhea1",
      "subhea2",
      "subhea1",
      "subhea2",
      "subhea1",
      "subhea2",
      "subhea1",
      "subhea2",
      "subhea1",
      "subhea2",
      "subhea4",
      "subhea1",
      "subhea2",
      "subhea4",
      "subhea1",
      "subhea2",
      "subhea4",
      "subhea1",
      "subhea2",
      "subhea4",
      "subhea1",
      "subhea2",
      "subhea4",
      "subhea1",
      "subhea2",
      "subhea4"
    ),
    variable_label = c(
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health compared to 10 years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago"
    ),
    harmonized_var_label = c(
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health compared to 10 years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago",
      "Self-perceived health",
      "Self-perceived health compared to age peers",
      "Self-perceived health 3 (or 4) years ago"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    subhea1 = list(
      `2B` = excellent_good_fair_sometimes_good_bad_poor,
      `3B` = excellent_good_fair_sometimes_good_bad_poor,
      B = excellent_good_fair_sometimes_good_bad_poor,
      C = excellent_good_fair_sometimes_good_bad_poor,
      D = excellent_good_fair_sometimes_good_bad_poor,
      E = excellent_good_fair_sometimes_good_bad_poor,
      F = excellent_good_fair_sometimes_good_bad_poor,
      G = excellent_good_fair_sometimes_good_bad_poor,
      H = excellent_good_fair_sometimes_good_bad_poor,
      I = excellent_good_fair_sometimes_good_bad_poor,
      J = excellent_good_fair_sometimes_good_bad_poor,
      K = excellent_good_fair_sometimes_good_bad_poor
    ),
    subhea2 = list(
      `2B` = much_better_a_little_better_do_not_know_just_as_good,
      `3B` = much_better_a_little_better_do_not_know_just_as_good,
      B = much_better_a_little_better_do_not_know_just_as_good,
      C = much_better_a_little_better_do_not_know_just_as_good,
      D = much_better_a_little_better_do_not_know_just_as_good,
      E = much_better_a_little_better_do_not_know_just_as_good,
      F = much_better_a_little_better,
      G = much_better_a_little_better,
      H = much_better_a_little_better,
      I = much_better_a_little_better,
      J = much_better_a_little_better,
      K = much_better_a_little_better
    ),
    subhea3 = list(
      `2B` = much_better_a_little_better_do_not_know_just_as_good
    ),
    subhea4 = list(
      F = excellent_good_fair_sometimes_good_bad_poor,
      G = excellent_good_fair_sometimes_good_bad_poor,
      H = excellent_good_fair_sometimes_good_bad_poor,
      I = excellent_good_fair_sometimes_good_bad_poor,
      J = excellent_good_fair_sometimes_good_bad_poor,
      K = excellent_good_fair_sometimes_good_bad_poor
    )
  ),

  value_labels_harmonized = list(
    subhea1 = excellent_good_fair_sometimes_good_bad_poor_2,
    subhea2 = much_better_a_little_better_do_not_know_just_as_good_2,
    subhea3 = much_better_a_little_better_do_not_know_just_as_good_2,
    subhea4 = excellent_good_fair_sometimes_good_bad_poor_2
  )
)
