## LASA filecode 155 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_155 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bmcodt1",
      "bmcodt2",
      "bmcodt3",
      "bmcodtp",
      "bmcodtp1",
      "bmcodtp2",
      "bmcodtp3",
      "bmcodtp4",
      "bmcodtp5",
      "bmcodtpoth",
      "bmcormis",
      "bmnotest",
      "bmcodt1",
      "bmcodt2",
      "bmcodt3",
      "bmcodtp",
      "bmcodtp1",
      "bmcodtp2",
      "bmcodtp3",
      "bmcodtp4",
      "bmcodtp5",
      "bmcormis",
      "bmnotest",
      "bmcodt1",
      "bmcodt2",
      "bmcodt3",
      "bmcodtp",
      "bmcodtp1",
      "bmcodtp2",
      "bmcodtp3",
      "bmcodtp4",
      "bmcodtp5",
      "bmcodtpoth",
      "bmcormis",
      "bmnotest",
      "cmcodt1",
      "cmcodt2",
      "cmcodt3",
      "cmcodtp",
      "cmcodtp1",
      "cmcodtp2",
      "cmcodtp3",
      "cmcodtp4",
      "cmcodtp5",
      "cmcodtpoth",
      "cmcormis",
      "cmnotest",
      "dmcodt1",
      "dmcodt2",
      "dmcodt3",
      "dmcodtp",
      "dmcodtp1",
      "dmcodtp2",
      "dmcodtp3",
      "dmcodtp4",
      "dmcodtp5",
      "dmcodtpoth",
      "dmcormis",
      "dmnotest",
      "emcodt1",
      "emcodt2",
      "emcodt3",
      "emcodtp",
      "emcodtp1",
      "emcodtp2",
      "emcodtp3",
      "emcodtp4",
      "emcodtp5",
      "emnotest",
      "fmcodt1",
      "fmcodt2",
      "fmcodt3",
      "fmcodtp",
      "fmcodtp1",
      "fmcodtp2",
      "fmcodtp3",
      "fmcodtp4",
      "fmcodtp5",
      "fmcormis",
      "fmnotest",
      "gmcodt1",
      "gmcodt2",
      "gmcodt3",
      "gmcodtp",
      "gmcodtp1",
      "gmcodtp2",
      "gmcodtp3",
      "gmcodtp4",
      "gmcodtp5",
      "gmcormis",
      "gmnotest",
      "hmcodt1",
      "hmcodt2",
      "hmcodt3",
      "hmcodtp",
      "hmcodtp1",
      "hmcodtp2",
      "hmcodtp3",
      "hmcodtp4",
      "hmcodtp5",
      "hmcormis",
      "hmnotest",
      "imcodt1",
      "imcodt2",
      "imcodt3",
      "imcodtp",
      "imcodtp1",
      "imcodtp2",
      "imcodtp3",
      "imcodtp4",
      "imcodtp5",
      "imnotest",
      "jmcodt1",
      "jmcodt2",
      "jmcodt3",
      "jmcodtp",
      "jmcodtp1",
      "jmcodtp2",
      "jmcodtp3",
      "jmcodtp4",
      "jmcodtp5",
      "jmcodtpoth",
      "jmnotest",
      "kmcodt1",
      "kmcodt2",
      "kmcodt3",
      "kmcodtp",
      "kmcodtp1",
      "kmcodtp2",
      "kmcodtp3",
      "kmcodtp4",
      "kmcodtp5",
      "kmnotest"
    ),
    canonical_name = c(
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mcodtpoth",
      "mcormis",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mcormis",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mcodtpoth",
      "mcormis",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mcodtpoth",
      "mcormis",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mcodtpoth",
      "mcormis",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mcormis",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mcormis",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mcormis",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mcodtpoth",
      "mnotest",
      "mcodt1",
      "mcodt2",
      "mcodt3",
      "mcodtp",
      "mcodtp1",
      "mcodtp2",
      "mcodtp3",
      "mcodtp4",
      "mcodtp5",
      "mnotest"
    ),
    variable_label = c(
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other specification",
      "coding task: reason no trial(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other specification",
      "coding task: reason no trial(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other specification",
      "coding task: reason no trial(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other specification",
      "coding task: reason no trial(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other specification",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "(part of) Coding test done"
    ),
    harmonized_var_label = c(
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other specification",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other specification",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other specification",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other specification",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "Coding task: reason no trail(s)",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other specification",
      "(part of) Coding test done",
      "Coding: trial 1",
      "Coding: trial 2",
      "Coding: trial 3",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "(part of) Coding test done"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mcodt1 = list(
      `2B` = no_valid_data_no_trial,
      `3B` = no_valid_data_no_trial,
      B = no_trial,
      C = no_valid_data_no_trial,
      D = no_valid_data_no_trial,
      E = no_valid_data_no_trial,
      F = no_valid_data_no_trial,
      G = no_valid_data_no_trial,
      H = no_valid_data_no_trial,
      I = no_valid_data_no_trial,
      J = no_valid_data_no_trial,
      K = no_valid_data_no_trial
    ),
    mcodt2 = list(
      `2B` = no_valid_data_no_trial,
      `3B` = no_valid_data_no_trial,
      B = no_trial,
      C = no_valid_data_no_trial,
      D = no_valid_data_no_trial,
      E = no_valid_data_no_trial,
      F = no_valid_data_no_trial,
      G = no_valid_data_no_trial,
      H = no_valid_data_no_trial,
      I = no_valid_data_no_trial,
      J = no_valid_data_no_trial,
      K = no_valid_data_no_trial
    ),
    mcodt3 = list(
      `2B` = no_valid_data_no_trial,
      `3B` = no_valid_data_no_trial,
      B = no_trial,
      C = no_valid_data_no_trial,
      D = no_valid_data_no_trial,
      E = no_valid_data_no_trial,
      F = no_valid_data_no_trial,
      G = no_valid_data_no_trial,
      H = no_valid_data_no_trial,
      I = no_valid_data_no_trial,
      J = no_valid_data_no_trial,
      K = no_valid_data_no_trial
    ),
    mcodtpoth = list(
      `2B` = extra_instructions_other_disturbing_factors,
      B = extra_instructions_other_disturbing_factors,
      C = extra_instructions_other_disturbing_factors,
      D = extra_instructions_other_disturbing_factors,
      J = extra_instructions_other_disturbing_factors_2
    ),
    mcormis = list(
      `2B` = complete_test_done_visus_problems_refused_cognitive,
      `3B` = to_be_coded_short_interview_interview_terminated,
      B = complete_test_done_visus_problems_refused_cognitive,
      C = complete_test_done_visus_problems_refused_cognitive,
      D = complete_test_done_visus_problems_refused_cognitive,
      F = to_be_coded_short_interview_interview_terminated,
      G = to_be_coded_short_interview_interview_terminated,
      H = to_be_coded_short_interview_interview_terminated
    ),
    mnotest = list(
      `2B` = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      `3B` = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      B = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      C = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      D = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      E = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      F = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      G = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      H = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      I = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      J = test_not_done_1_trial_done_2_trials_done_3_trials_done,
      K = test_not_done_1_trial_done_2_trials_done_3_trials_done
    ),
    mcodtp = list(
      `3B` = no_yes_82,
      B = not_mentioned_mentioned_13,
      C = not_mentioned_mentioned_25,
      D = not_mentioned_mentioned_25,
      E = not_mentioned_mentioned_25,
      F = no_yes_82,
      G = no_yes_82,
      H = no_yes_82,
      I = no_yes_82,
      J = no_yes_82,
      K = no_yes_82
    ),
    mcodtp1 = list(
      `3B` = not_mentioned_mentioned_25,
      F = not_mentioned_mentioned_25,
      G = not_mentioned_mentioned_25,
      H = not_mentioned_mentioned_25,
      I = not_mentioned_mentioned_25,
      J = not_mentioned_mentioned_25,
      K = not_mentioned_mentioned_25
    ),
    mcodtp2 = list(
      `3B` = not_mentioned_mentioned_25,
      F = not_mentioned_mentioned_25,
      G = not_mentioned_mentioned_25,
      H = not_mentioned_mentioned_25,
      I = not_mentioned_mentioned_25,
      J = not_mentioned_mentioned_25,
      K = not_mentioned_mentioned_25
    ),
    mcodtp3 = list(
      `3B` = not_mentioned_mentioned_25,
      F = not_mentioned_mentioned_25,
      G = not_mentioned_mentioned_25,
      H = not_mentioned_mentioned_25,
      I = not_mentioned_mentioned_25,
      J = not_mentioned_mentioned_25,
      K = not_mentioned_mentioned_25
    ),
    mcodtp4 = list(
      `3B` = not_mentioned_mentioned_25,
      F = not_mentioned_mentioned_25,
      G = not_mentioned_mentioned_25,
      H = not_mentioned_mentioned_25,
      I = not_mentioned_mentioned_25,
      J = not_mentioned_mentioned_25,
      K = not_mentioned_mentioned_25
    ),
    mcodtp5 = list(
      `3B` = not_mentioned_mentioned_25,
      F = not_mentioned_mentioned_25,
      G = not_mentioned_mentioned_25,
      H = not_mentioned_mentioned_25,
      I = not_mentioned_mentioned_25,
      J = not_mentioned_mentioned_25,
      K = not_mentioned_mentioned_25
    )
  ),

  value_labels_harmonized = list(
    mcodt1 = no_valid_data_no_trial,
    mcodt2 = no_valid_data_no_trial,
    mcodt3 = no_valid_data_no_trial,
    mcodtp = c(
      `-4` = "no valid data",
      `-3` = "no test",
      `-2` = "no particularities",
      `0` = "not mentioned / no",
      `1` = "mentioned / yes"
    ),
    mcodtp1 = not_mentioned_mentioned_25,
    mcodtp2 = not_mentioned_mentioned_25,
    mcodtp3 = not_mentioned_mentioned_25,
    mcodtp4 = not_mentioned_mentioned_25,
    mcodtp5 = not_mentioned_mentioned_25,
    mcodtpoth = extra_instructions_other_disturbing_factors_2,
    mcormis = c(
      `-4` = "no valid data",
      `-2` = "valid score",
      `0` = "complete test done / to be coded",
      `1` = "visus problems / short interview",
      `2` = "refused / interview terminated",
      `3` = "cognitive / too many missings",
      `4` = "physical / refused test",
      `5` = "technical / not able to (cognitive)",
      `6` = "unknown / not able to (physical)",
      `7` = "technical/interruption"
    ),
    mnotest = test_not_done_1_trial_done_2_trials_done_3_trials_done
  )
)
