## LASA filecode 031 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_031 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bsense03",
      "bsense04",
      "bsense05",
      "bsense06",
      "bsense09",
      "bsense10",
      "bsense11",
      "bsense12",
      "bsense13",
      "bsense01",
      "bsense02",
      "bsense03",
      "bsense04",
      "bsense05",
      "bsense06",
      "bsense08",
      "bsense09",
      "bsense10",
      "bsense11",
      "bsense12",
      "bsense13",
      "bsense18",
      "bsense19",
      "bsense20",
      "bsense7a",
      "bsense7b",
      "bsense01",
      "bsense02",
      "bsense03",
      "bsense04",
      "bsense05",
      "bsense06",
      "bsense07",
      "bsense08",
      "bsense09",
      "bsense10",
      "bsense11",
      "bsense12",
      "bsense13",
      "bsense14",
      "csense01",
      "csense02",
      "csense03",
      "csense04",
      "csense05",
      "csense06",
      "csense07",
      "csense08",
      "csense09",
      "csense10",
      "csense11",
      "csense12",
      "csense13",
      "csense14",
      "dsense01",
      "dsense02",
      "dsense03",
      "dsense04",
      "dsense05",
      "dsense06",
      "dsense07",
      "dsense08",
      "dsense09",
      "dsense10",
      "dsense11",
      "dsense12",
      "dsense13",
      "dsense14",
      "esense01",
      "esense02",
      "esense03",
      "esense04",
      "esense05",
      "esense06",
      "esense07",
      "esense08",
      "esense09",
      "esense10",
      "esense11",
      "esense12",
      "esense13",
      "esense14",
      "fmsens01",
      "fmsens02",
      "fmsens03",
      "fmsens04",
      "fmsens05",
      "fmsens06",
      "fmsens07",
      "fmsens08",
      "fmsens09",
      "fmsens10",
      "fmsens11",
      "fmsens12",
      "fmsens13",
      "fmsens14",
      "fmsens15",
      "gmsens01",
      "gmsens02",
      "gmsens03",
      "gmsens04",
      "gmsens05",
      "gmsens06",
      "gmsens07",
      "gmsens08",
      "gmsens09",
      "gmsens10",
      "gmsens11",
      "gmsens12",
      "gmsens13",
      "gmsens14",
      "gmsens15",
      "hmsens01",
      "hmsens02",
      "hmsens03",
      "hmsens04",
      "hmsens05",
      "hmsens06",
      "hmsens08",
      "hmsens09",
      "hmsens10",
      "hmsens11",
      "hmsens12",
      "hmsens13",
      "hmsens16",
      "hmsens17",
      "hmsens18",
      "hmsens19",
      "hmsens20",
      "hmsens7a",
      "hmsens7b",
      "imsens01",
      "imsens03",
      "imsens04",
      "imsens05",
      "imsens06",
      "imsens08",
      "imsens09",
      "imsens10",
      "imsens11",
      "imsens12",
      "imsens13",
      "imsens16",
      "imsens17",
      "imsens18",
      "imsens19",
      "imsens20",
      "imsens7a",
      "imsens7b",
      "jmsens01",
      "jmsens03",
      "jmsens04",
      "jmsens05",
      "jmsens06",
      "jmsens08",
      "jmsens08a",
      "jmsens08b",
      "jmsens09",
      "jmsens09a",
      "jmsens09b",
      "jmsens10a",
      "jmsens10b",
      "jmsens11",
      "jmsens11a",
      "jmsens11b",
      "jmsens12a",
      "jmsens12b",
      "jmsens16",
      "jmsens16a",
      "jmsens16b",
      "jmsens17a",
      "jmsens17b",
      "jmsens21",
      "jmsens22a",
      "jmsens22b",
      "jmsens7a",
      "jmsens7b",
      "jmsens7c",
      "kmsens01",
      "kmsens03",
      "kmsens04",
      "kmsens05",
      "kmsens06",
      "kmsens08",
      "kmsens08a",
      "kmsens08b",
      "kmsens09",
      "kmsens09a",
      "kmsens09b",
      "kmsens10a",
      "kmsens10b",
      "kmsens11",
      "kmsens11a",
      "kmsens11b",
      "kmsens12a",
      "kmsens12b",
      "kmsens16",
      "kmsens16a",
      "kmsens16b",
      "kmsens17a",
      "kmsens17b",
      "kmsens21",
      "kmsens22a",
      "kmsens22b",
      "kmsens7a",
      "kmsens7b",
      "kmsens7c",
      "bsense03",
      "bsense05",
      "bsense09",
      "bsense11",
      "bsense13",
      "bsense18",
      "bsense19",
      "bsense20",
      "bsense7a",
      "bsense7b"
    ),
    canonical_name = c(
      "sense03",
      "sense04",
      "sense05",
      "sense06",
      "sense09",
      "sense10",
      "sense11",
      "sense12",
      "sense13",
      "sense01",
      "sense02",
      "sense03",
      "sense04",
      "sense05",
      "sense06",
      "sense08",
      "sense09",
      "sense10",
      "sense11",
      "sense12",
      "sense13",
      "sense18",
      "sense19",
      "sense20",
      "sense7a",
      "sense7b",
      "sense01",
      "sense02",
      "sense03",
      "sense04",
      "sense05",
      "sense06",
      "sense07",
      "sense08",
      "sense09",
      "sense10",
      "sense11",
      "sense12",
      "sense13",
      "sense14",
      "sense01",
      "sense02",
      "sense03",
      "sense04",
      "sense05",
      "sense06",
      "sense07",
      "sense08",
      "sense09",
      "sense10",
      "sense11",
      "sense12",
      "sense13",
      "sense14",
      "sense01",
      "sense02",
      "sense03",
      "sense04",
      "sense05",
      "sense06",
      "sense07",
      "sense08",
      "sense09",
      "sense10",
      "sense11",
      "sense12",
      "sense13",
      "sense14",
      "sense01",
      "sense02",
      "sense03",
      "sense04",
      "sense05",
      "sense06",
      "sense07",
      "sense08",
      "sense09",
      "sense10",
      "sense11",
      "sense12",
      "sense13",
      "sense14",
      "msens01",
      "msens02",
      "msens03",
      "msens04",
      "msens05",
      "msens06",
      "msens07",
      "msens08",
      "msens09",
      "msens10",
      "msens11",
      "msens12",
      "msens13",
      "msens14",
      "msens15",
      "msens01",
      "msens02",
      "msens03",
      "msens04",
      "msens05",
      "msens06",
      "msens07",
      "msens08",
      "msens09",
      "msens10",
      "msens11",
      "msens12",
      "msens13",
      "msens14",
      "msens15",
      "msens01",
      "msens02",
      "msens03",
      "msens04",
      "msens05",
      "msens06",
      "msens08",
      "msens09",
      "msens10",
      "msens11",
      "msens12",
      "msens13",
      "msens16",
      "msens17",
      "msens18",
      "msens19",
      "msens20",
      "msens7a",
      "msens7b",
      "msens01",
      "msens03",
      "msens04",
      "msens05",
      "msens06",
      "msens08",
      "msens09",
      "msens10",
      "msens11",
      "msens12",
      "msens13",
      "msens16",
      "msens17",
      "msens18",
      "msens19",
      "msens20",
      "msens7a",
      "msens7b",
      "msens01",
      "msens03",
      "msens04",
      "msens05",
      "msens06",
      "msens08",
      "msens08a",
      "msens08b",
      "msens09",
      "msens09a",
      "msens09b",
      "msens10a",
      "msens10b",
      "msens11",
      "msens11a",
      "msens11b",
      "msens12a",
      "msens12b",
      "msens16",
      "msens16a",
      "msens16b",
      "msens17a",
      "msens17b",
      "msens21",
      "msens22a",
      "msens22b",
      "msens7a",
      "msens7b",
      "msens7c",
      "msens01",
      "msens03",
      "msens04",
      "msens05",
      "msens06",
      "msens08",
      "msens08a",
      "msens08b",
      "msens09",
      "msens09a",
      "msens09b",
      "msens10a",
      "msens10b",
      "msens11",
      "msens11a",
      "msens11b",
      "msens12a",
      "msens12b",
      "msens16",
      "msens16a",
      "msens16b",
      "msens17a",
      "msens17b",
      "msens21",
      "msens22a",
      "msens22b",
      "msens7a",
      "msens7b",
      "msens7c",
      "sense03",
      "sense05",
      "sense09",
      "sense11",
      "sense13",
      "sense18",
      "sense19",
      "sense20",
      "sense7a",
      "sense7b"
    ),
    variable_label = c(
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "R usually wears glasses or contact lenses",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "R hears noises, beeping, etc: nowadays",
      "R hears noises, beeping, etc: frequency",
      "R hears noises, beeping, etc: how annoying",
      "R possesses hearing aid (HA)",
      "R wears hearing aid(s) (HA) how many hours",
      "Respondent wears glasses: observation",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "Respondent wears hearing aid (HA): observation",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Respondent has speech defect: observation",
      "Respondent wears glasses: observation",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "Respondent wears hearing aid (HA): observation",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Respondent has speech defect: observation",
      "R usually wears glasses or contact lenses (in D: observation)",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "R usually wears hearing aid (HA)",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Respondent has speech defect: observation",
      "R usually wears glasses or contact lenses (in D: observation)",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "R usually wears hearing aid (HA)",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Respondent has speech defect: observation",
      "R usually wears glasses or contact lenses",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "R usually wears hearing aid (HA)",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "R has speech defect: observation",
      "R has problems understanding written text (dyslexic)",
      "R usually wears glasses or contact lenses",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "R usually wears hearing aid (HA)",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "R has speech defect: observation",
      "R has problems understanding written text (dyslexic)",
      "R usually wears glasses or contact lenses",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Can understand 1 person at party without HA",
      "Can understand 1 person at party with HA",
      "R hears noises, beeping, etc: nowadays",
      "R hears noises, beeping, etc: frequency",
      "R hears noises, beeping, etc: how annoying",
      "R possesses hearing aid (HA)",
      "R wears hearing aid(s) (HA) how many hours",
      "R usually wears glasses or contact lenses",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Can understand 1 person at party without HA",
      "Can understand 1 person at party with HA",
      "R hears noises, beeping, etc: nowadays",
      "R hears noises, beeping, etc: frequency",
      "R hears noises, beeping, etc: how annoying",
      "R possesses hearing aid (HA)",
      "R wears hearing aid(s) (HA) how many hours",
      "R usually wears glasses or contact lenses",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "No HA/not using HA: hear well enough (subjective)",
      "1 HA: hear well enough (subjective)",
      "2HA: hear well enough (subjective)",
      "No HA/not using HA: follow conversation 3/4 persons",
      "1 HA: follow conversation 3/4 persons without HA",
      "2 HA: follow conversation 3/4 persons without HA",
      "1 HA: follow conversation 3/4 persons with HA",
      "2 HA: follow conversation 3/4 persons with HA",
      "No HA/not using HA: have conversation 1 person",
      "1 HA: have conversation 1 person without HA",
      "2 HA: have conversation 1 person without HA",
      "1 HA: have conversation 1 person with HA",
      "2 HA: have conversation 1 person with HA",
      "No HA/not using HA: can understand 1 person at party",
      "1 HA: can understand 1 person at party without HA",
      "2 HA: can understand 1 person at party without HA",
      "1 HA: can understand 1 person at party with HA",
      "2 HA: can understand 1 person at party with HA",
      "No HA/not using HA: subjective rating hearing (scale 0-9)",
      "1 or 2 HA: subjective rating hearing without HA (scale 0-9)",
      "1 or 2 HA: subjective rating hearing with HA (scale 0-9)",
      "R possesses hearing aid(s) (HA)",
      "1 or 2 HA: R wears HA how many hours",
      "1 or 2 HA: R is wearing HA right now",
      "R usually wears glasses or contact lenses",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "No HA/not using HA: hear well enough (subjective)",
      "1 HA: hear well enough (subjective)",
      "2HA: hear well enough (subjective)",
      "No HA/not using HA: follow conversation 3/4 persons",
      "1 HA: follow conversation 3/4 persons without HA",
      "2 HA: follow conversation 3/4 persons without HA",
      "1 HA: follow conversation 3/4 persons with HA",
      "2 HA: follow conversation 3/4 persons with HA",
      "No HA/not using HA: have conversation 1 person",
      "1 HA: have conversation 1 person without HA",
      "2 HA: have conversation 1 person without HA",
      "1 HA: have conversation 1 person with HA",
      "2 HA: have conversation 1 person with HA",
      "No HA/not using HA: can understand 1 person at party",
      "1 HA: can understand 1 person at party without HA",
      "2 HA: can understand 1 person at party without HA",
      "1 HA: can understand 1 person at party with HA",
      "2 HA: can understand 1 person at party with HA",
      "No HA/not using HA: subjective rating hearing (scale 0-9)",
      "1 or 2 HA: subjective rating hearing without HA (scale 0-9)",
      "1 or 2 HA: subjective rating hearing with HA (scale 0-9)",
      "R possesses hearing aid(s) (HA)",
      "1 or 2 HA: R wears HA how many hours",
      "1 or 2 HA: R is wearing HA right now",
      "Small print in paper with or without glasses etc",
      "Recognize face 4 meter with or without glasses etc",
      "Follow conversation 3/4 persons: with or without HA",
      "Have conversation 1 person: with or without HA",
      "Can use normal telephone",
      "R hears noises, beeping, etc: nowadays",
      "R hears noises, beeping, etc: frequency",
      "R hears noises, beeping, etc: how annoying",
      "R possesses hearing aid (HA)",
      "R wears hearing aid(s) (HA) how many hours"
    ),
    harmonized_var_label = c(
      "Small print in paper: visual difficulty",
      "Small print in paper with glasses etc",
      "Recognize face at 4 meters: visual difficulty",
      "Recognize face 4 meter with glasses etc",
      "Follow conversation with 3/4 persons: hearing difficulty",
      "Follow conversation 4 persons: with HA",
      "Have conversation with 1 person: hearing difficulty",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Respondent wears glasses: observation",
      "Subjective: see well enough",
      "Small print in paper: visual difficulty",
      "Small print in paper with glasses etc",
      "Recognize face at 4 meters: visual difficulty",
      "Recognize face 4 meter with glasses etc",
      "Subjective: hear well enough",
      "Follow conversation with 3/4 persons: hearing difficulty",
      "Follow conversation 4 persons: with HA",
      "Have conversation with 1 person: hearing difficulty",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "R hears noises, beeping, etc: nowadays",
      "R hears noises, beeping, etc: frequency",
      "R hears noises, beeping, etc: how annoying",
      "R possesses hearing aid (HA)",
      "R wears hearing aid(s) (HA) how many hours",
      "Respondent wears glasses: observation",
      "Subjective: see well enough",
      "Small print in paper: visual difficulty",
      "Small print in paper with glasses etc",
      "Recognize face at 4 meters: visual difficulty",
      "Recognize face 4 meter with glasses etc",
      "Respondent wears hearing aid (HA): observation",
      "Subjective: hear well enough",
      "Follow conversation with 3/4 persons: hearing difficulty",
      "Follow conversation 4 persons: with HA",
      "Have conversation with 1 person: hearing difficulty",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Respondent has speech defect: observation",
      "Respondent wears glasses: observation",
      "Subjective: see well enough",
      "Small print in paper: visual difficulty",
      "Small print in paper with glasses etc",
      "Recognize face at 4 meters: visual difficulty",
      "Recognize face 4 meter with glasses etc",
      "Respondent wears hearing aid (HA): observation",
      "Subjective: hear well enough",
      "Follow conversation with 3/4 persons: hearing difficulty",
      "Follow conversation 4 persons: with HA",
      "Have conversation with 1 person: hearing difficulty",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Respondent has speech defect: observation",
      "Respondent wears glasses: observation",
      "Subjective: see well enough",
      "Small print in paper: visual difficulty",
      "Small print in paper with glasses etc",
      "Recognize face at 4 meters: visual difficulty",
      "Recognize face 4 meter with glasses etc",
      "Respondent wears hearing aid (HA): observation",
      "Subjective: hear well enough",
      "Follow conversation with 3/4 persons: hearing difficulty",
      "Follow conversation 4 persons: with HA",
      "Have conversation with 1 person: hearing difficulty",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Respondent has speech defect: observation",
      "Respondent wears glasses: observation",
      "Subjective: see well enough",
      "Small print in paper: visual difficulty",
      "Small print in paper with glasses etc",
      "Recognize face at 4 meters: visual difficulty",
      "Recognize face 4 meter with glasses etc",
      "Respondent wears hearing aid (HA): observation",
      "Subjective: hear well enough",
      "Follow conversation with 3/4 persons: hearing difficulty",
      "Follow conversation 4 persons: with HA",
      "Have conversation with 1 person: hearing difficulty",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Respondent has speech defect: observation",
      "R usually wears glasses or contact lenses",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "R usually wears hearing aid (HA)",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "R has speech defect: observation",
      "R has problems understanding written text (dyslexic)",
      "R usually wears glasses or contact lenses",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "R usually wears hearing aid (HA)",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "R has speech defect: observation",
      "R has problems understanding written text (dyslexic)",
      "R usually wears glasses or contact lenses",
      "Subjective: see well enough",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Can understand 1 person at party without HA",
      "Can understand 1 person at party with HA",
      "R hears noises, beeping, etc: nowadays",
      "R hears noises, beeping, etc: frequency",
      "R hears noises, beeping, etc: how annoying",
      "R possesses hearing aid (HA)",
      "R wears hearing aid(s) (HA) how many hours",
      "R usually wears glasses or contact lenses",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "Subjective: hear well enough",
      "Follow conversation 4 persons: without HA",
      "Follow conversation 4 persons: with HA",
      "Have conversation 1 person: without HA",
      "Have conversation 1 person: with HA",
      "Can use normal telephone",
      "Can understand 1 person at party without HA",
      "Can understand 1 person at party with HA",
      "R hears noises, beeping, etc: nowadays",
      "R hears noises, beeping, etc: frequency",
      "R hears noises, beeping, etc: how annoying",
      "R possesses hearing aid (HA)",
      "R wears hearing aid(s) (HA) how many hours",
      "R usually wears glasses or contact lenses",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "Subjective: hear well enough",
      "1 HA: hear well enough (subjective)",
      "2HA: hear well enough (subjective)",
      "Follow conversation 4 persons: without HA",
      "1 HA: follow conversation 3/4 persons without HA",
      "2 HA: follow conversation 3/4 persons without HA",
      "1 HA: follow conversation 3/4 persons with HA",
      "2 HA: follow conversation 3/4 persons with HA",
      "Have conversation 1 person: without HA",
      "1 HA: have conversation 1 person without HA",
      "2 HA: have conversation 1 person without HA",
      "1 HA: have conversation 1 person with HA",
      "2 HA: have conversation 1 person with HA",
      "Can understand 1 person at party without HA",
      "1 HA: can understand 1 person at party without HA",
      "2 HA: can understand 1 person at party without HA",
      "1 HA: can understand 1 person at party with HA",
      "2 HA: can understand 1 person at party with HA",
      "No HA/not using HA: subjective rating hearing (scale 0-9)",
      "1 or 2 HA: subjective rating hearing without HA (scale 0-9)",
      "1 or 2 HA: subjective rating hearing with HA (scale 0-9)",
      "R possesses hearing aid (HA)",
      "R wears hearing aid(s) (HA) how many hours",
      "1 or 2 HA: R is wearing HA right now",
      "R usually wears glasses or contact lenses",
      "Small print in paper without glasses etc",
      "Small print in paper with glasses etc",
      "Recognize face 4 meter without glasses etc",
      "Recognize face 4 meter with glasses etc",
      "Subjective: hear well enough",
      "1 HA: hear well enough (subjective)",
      "2HA: hear well enough (subjective)",
      "Follow conversation 4 persons: without HA",
      "1 HA: follow conversation 3/4 persons without HA",
      "2 HA: follow conversation 3/4 persons without HA",
      "1 HA: follow conversation 3/4 persons with HA",
      "2 HA: follow conversation 3/4 persons with HA",
      "Have conversation 1 person: without HA",
      "1 HA: have conversation 1 person without HA",
      "2 HA: have conversation 1 person without HA",
      "1 HA: have conversation 1 person with HA",
      "2 HA: have conversation 1 person with HA",
      "Can understand 1 person at party without HA",
      "1 HA: can understand 1 person at party without HA",
      "2 HA: can understand 1 person at party without HA",
      "1 HA: can understand 1 person at party with HA",
      "2 HA: can understand 1 person at party with HA",
      "No HA/not using HA: subjective rating hearing (scale 0-9)",
      "1 or 2 HA: subjective rating hearing without HA (scale 0-9)",
      "1 or 2 HA: subjective rating hearing with HA (scale 0-9)",
      "R possesses hearing aid (HA)",
      "R wears hearing aid(s) (HA) how many hours",
      "1 or 2 HA: R is wearing HA right now",
      "Small print in paper: visual difficulty",
      "Recognize face at 4 meters: visual difficulty",
      "Follow conversation with 3/4 persons: hearing difficulty",
      "Have conversation with 1 person: hearing difficulty",
      "Can use normal telephone",
      "R hears noises, beeping, etc: nowadays",
      "R hears noises, beeping, etc: frequency",
      "R hears noises, beeping, etc: how annoying",
      "R possesses hearing aid (HA)",
      "R wears hearing aid(s) (HA) how many hours"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "text",
      "categorical",
      "text",
      "text",
      "categorical",
      "text",
      "categorical",
      "text",
      "text",
      "categorical",
      "text",
      "categorical",
      "text",
      "text",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "text",
      "categorical",
      "text",
      "text",
      "categorical",
      "text",
      "categorical",
      "text",
      "text",
      "categorical",
      "text",
      "categorical",
      "text",
      "text",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    sense03 = list(
      `2B` = c(
        `-5` = "na, interview terminated",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      `3B` = yes_without_difficulty_yes_with_some_difficulty_6,
      B = yes_without_difficulty_yes_with_some_difficulty_6,
      C = yes_without_difficulty_yes_with_some_difficulty_3,
      D = yes_without_difficulty_yes_with_some_difficulty,
      E = yes_without_difficulty_yes_with_some_difficulty,
      MB = yes_without_difficulty_yes_with_some_difficulty_7
    ),
    sense04 = list(
      `2B` = c(
        `-2` = "na, see BSENSE03",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot",
        `5` = "R does not use aid"
      ),
      `3B` = c(
        `-2` = "na, see BSENSE03",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot",
        `5` = "R does not have glasses or contact lenses"
      ),
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BSENSE03",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      C = c(
        `-2` = "na, see CSENSE03",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      D = yes_without_difficulty_yes_with_some_difficulty_16,
      E = yes_without_difficulty_yes_with_some_difficulty_16
    ),
    sense05 = list(
      `2B` = yes_without_difficulty_yes_with_some_difficulty_12,
      `3B` = c(
        `-2` = "na, see BSENS01",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      B = yes_without_difficulty_yes_with_some_difficulty_4,
      C = yes_without_difficulty_yes_with_some_difficulty_3,
      D = yes_without_difficulty_yes_with_some_difficulty,
      E = yes_without_difficulty_yes_with_some_difficulty,
      MB = yes_without_difficulty_yes_with_some_difficulty_7
    ),
    sense06 = list(
      `2B` = yes_without_difficulty_yes_with_some_difficulty_17,
      `3B` = yes_without_difficulty_yes_with_some_difficulty_17,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BSENSE05",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      C = c(
        `-2` = "na, see CSENSE05",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      D = yes_without_difficulty_yes_with_some_difficulty_18,
      E = yes_without_difficulty_yes_with_some_difficulty_18
    ),
    sense09 = list(
      `2B` = c(
        `-2` = "na, see BSENSE03",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no I cannot"
      ),
      `3B` = c(
        `-2` = "na, see BSENSE7A",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no I cannot"
      ),
      B = yes_without_difficulty_yes_with_some_difficulty_6,
      C = c(
        `-2` = "na, see CSENSE01",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no I cannot"
      ),
      D = yes_without_difficulty_yes_with_some_difficulty_19,
      E = yes_without_difficulty_yes_with_some_difficulty_19,
      MB = c(
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no I cannot"
      )
    ),
    sense10 = list(
      `2B` = yes_without_difficulty_yes_with_some_difficulty_20,
      `3B` = yes_without_difficulty_yes_with_some_difficulty_20,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BSENSE09",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      C = c(
        `-2` = "na, see CSENSE09",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      D = yes_without_difficulty_yes_with_some_difficulty_21,
      E = yes_without_difficulty_yes_with_some_difficulty_21
    ),
    sense11 = list(
      `2B` = yes_without_difficulty_yes_with_some_difficulty_12,
      `3B` = yes_without_difficulty_yes_with_some_difficulty_13,
      B = yes_without_difficulty_yes_with_some_difficulty_4,
      C = yes_without_difficulty_yes_with_some_difficulty_3,
      D = yes_without_difficulty_yes_with_some_difficulty,
      E = yes_without_difficulty_yes_with_some_difficulty,
      MB = yes_without_difficulty_yes_with_some_difficulty_7
    ),
    sense12 = list(
      `2B` = yes_without_difficulty_yes_with_some_difficulty_22,
      `3B` = yes_without_difficulty_yes_with_some_difficulty_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BSENSE11",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      C = c(
        `-2` = "na, see CSENSE11",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      D = yes_without_difficulty_yes_with_some_difficulty_23,
      E = yes_without_difficulty_yes_with_some_difficulty_23
    ),
    sense13 = list(
      `2B` = yes_without_difficulty_yes_with_some_difficulty_12,
      `3B` = yes_without_difficulty_yes_with_some_difficulty_13,
      B = yes_without_difficulty_yes_with_some_difficulty_4,
      C = yes_without_difficulty_yes_with_some_difficulty_3,
      D = yes_without_difficulty_yes_with_some_difficulty,
      E = yes_without_difficulty_yes_with_some_difficulty,
      MB = yes_without_difficulty_yes_with_some_difficulty_7
    ),
    sense01 = list(
      `3B` = no_yes_5,
      B = no_yes_5,
      C = no_yes_5,
      D = no_yes_5,
      E = no_yes_5
    ),
    sense02 = list(
      `3B` = yes_without_difficulty_yes_with_some_difficulty_6,
      B = yes_without_difficulty_yes_with_some_difficulty_4,
      C = yes_without_difficulty_yes_with_some_difficulty_3,
      D = yes_without_difficulty_yes_with_some_difficulty,
      E = yes_without_difficulty_yes_with_some_difficulty
    ),
    sense08 = list(
      `3B` = yes_without_difficulty_yes_with_some_difficulty_13,
      B = yes_without_difficulty_yes_with_some_difficulty_4,
      C = yes_without_difficulty_yes_with_some_difficulty_3,
      D = yes_without_difficulty_yes_with_some_difficulty,
      E = yes_without_difficulty_yes_with_some_difficulty
    ),
    sense18 = list(
      `3B` = c(`-2` = "na, see BSENSE7A", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      MB = no_yes
    ),
    sense19 = list(
      `3B` = some_of_the_time_most_of_the_time_all_of_the_time,
      MB = some_of_the_time_most_of_the_time_all_of_the_time
    ),
    sense20 = list(
      `3B` = not_annoying_at_all_a_bit_annoying_rather_annoying,
      MB = not_annoying_at_all_a_bit_annoying_rather_annoying
    ),
    sense7a = list(
      `3B` = no_never_had_before_yes_possess_one_without_use,
      MB = c(
        `-1` = "na, asked",
        `1` = "no, never had before",
        `2` = "yes, possess one or two without use",
        `3` = "yes, possess one or two with use"
      )
    ),
    sense7b = list(
      `3B` = vs_1_hr_a_day_1_4_hrs_a_day_4_8_hrs_a_day_all_day,
      MB = vs_1_hr_a_day_1_4_hrs_a_day_4_8_hrs_a_day_all_day
    ),
    sense07 = list(
      B = no_yes_268,
      C = no_yes_269,
      D = no_yes_160,
      E = no_yes_160
    ),
    sense14 = list(
      B = no_yes_268,
      C = no_yes_269,
      D = no_yes_160,
      E = no_yes_160
    ),
    msens01 = list(
      F = no_yes,
      G = no_yes_191,
      H = no_yes_191,
      I = no_yes_191,
      J = no_yes,
      K = no_yes
    ),
    msens02 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_2,
      G = yes_without_difficulty_yes_with_some_difficulty_2,
      H = yes_without_difficulty_yes_with_some_difficulty_14
    ),
    msens03 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_2,
      G = yes_without_difficulty_yes_with_some_difficulty_2,
      H = yes_without_difficulty_yes_with_some_difficulty_14,
      I = yes_without_difficulty_yes_with_some_difficulty_24,
      J = yes_without_difficulty_yes_with_some_difficulty_8,
      K = yes_without_difficulty_yes_with_some_difficulty_8
    ),
    msens04 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_25,
      G = yes_without_difficulty_yes_with_some_difficulty_25,
      H = c(
        `-2` = "na, see HMSENS03",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot",
        `5` = "R does not have glasses or contact lenses"
      ),
      I = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see IMSENS03",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot",
        `5` = "R does not have glasses or contact lenses"
      ),
      J = yes_without_difficulty_yes_with_some_difficulty_26,
      K = yes_without_difficulty_yes_with_some_difficulty_26
    ),
    msens05 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_2,
      G = yes_without_difficulty_yes_with_some_difficulty_2,
      H = yes_without_difficulty_yes_with_some_difficulty_14,
      I = yes_without_difficulty_yes_with_some_difficulty_24,
      J = yes_without_difficulty_yes_with_some_difficulty_8,
      K = yes_without_difficulty_yes_with_some_difficulty_8
    ),
    msens06 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_27,
      G = yes_without_difficulty_yes_with_some_difficulty_27,
      H = c(
        `-2` = "na, see HMSENS05",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot",
        `5` = "R does not have glasses or contact lenses"
      ),
      I = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see IMSENS05",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot",
        `5` = "R does not have glasses or contact lenses"
      ),
      J = yes_without_difficulty_yes_with_some_difficulty_28,
      K = yes_without_difficulty_yes_with_some_difficulty_28
    ),
    msens07 = list(
      F = no_yes_99,
      G = no_yes_99
    ),
    msens08 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_2,
      G = yes_without_difficulty_yes_with_some_difficulty_2,
      H = yes_without_difficulty_yes_with_some_difficulty_29,
      I = yes_without_difficulty_yes_with_some_difficulty_15,
      J = yes_without_difficulty_yes_with_some_difficulty_9,
      K = yes_without_difficulty_yes_with_some_difficulty_9
    ),
    msens09 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_30,
      G = yes_without_difficulty_yes_with_some_difficulty_30,
      H = c(
        `-2` = "na, see HMSENS7A",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no I cannot"
      ),
      I = c(
        `-2` = "na, see IMSENS7A",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no I cannot"
      )
    ),
    msens10 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_31,
      G = yes_without_difficulty_yes_with_some_difficulty_31,
      H = c(
        `-2` = "na, see HMSENS09",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot",
        `5` = "R does not have a hearing aid"
      ),
      I = c(
        `-2` = "na, see IMSENS09",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot",
        `5` = "R does not have a hearing aid"
      )
    ),
    msens11 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_2,
      G = yes_without_difficulty_yes_with_some_difficulty_2,
      H = yes_without_difficulty_yes_with_some_difficulty_29,
      I = yes_without_difficulty_yes_with_some_difficulty_15,
      J = yes_without_difficulty_yes_with_some_difficulty_9,
      K = yes_without_difficulty_yes_with_some_difficulty_9
    ),
    msens12 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_32,
      G = yes_without_difficulty_yes_with_some_difficulty_32,
      H = c(
        `-2` = "na, see HMSENS11",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot",
        `5` = "R does not have a hearing aid"
      ),
      I = c(
        `-2` = "na, see IMSENS11",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot",
        `5` = "R does not have a hearing aid"
      )
    ),
    msens13 = list(
      F = yes_without_difficulty_yes_with_some_difficulty_2,
      G = yes_without_difficulty_yes_with_some_difficulty_2,
      H = c(
        `-2` = "na, see HMSENS7A1",
        `-1` = "na, asked",
        `1` = "yes, without difficulty",
        `2` = "yes, with some difficulty",
        `3` = "yes, with much difficulty",
        `4` = "no, I cannot"
      ),
      I = yes_without_difficulty_yes_with_some_difficulty_15
    ),
    msens14 = list(
      F = no_yes_99,
      G = no_yes_99
    ),
    msens15 = list(
      F = no_yes_99,
      G = no_yes_99
    ),
    msens16 = list(
      H = c(
        `-2` = "na, see HMSENS7A",
        `-1` = "na, asked",
        `1` = "hardly ever",
        `2` = "sometimes",
        `3` = "often",
        `4` = "almost always",
        `5` = "R does not have a hearing aid"
      ),
      I = c(
        `-2` = "na, see IMSENS7A",
        `-1` = "na, asked",
        `1` = "hardly ever",
        `2` = "sometimes",
        `3` = "often",
        `4` = "almost always",
        `5` = "R does not have a hearing aid"
      ),
      J = hardly_ever_sometimes_often_almost_always,
      K = hardly_ever_sometimes_often_almost_always
    ),
    msens17 = list(
      H = c(
        `-2` = "na, see HMSENS16",
        `-1` = "na, asked",
        `1` = "hardly ever",
        `2` = "sometimes",
        `3` = "often",
        `4` = "almost always",
        `5` = "R does not have a hearing aid"
      ),
      I = c(
        `-2` = "na, see IMSENS16",
        `-1` = "na, asked",
        `1` = "hardly ever",
        `2` = "sometimes",
        `3` = "often",
        `4` = "almost always",
        `5` = "R does not have a hearing aid"
      )
    ),
    msens18 = list(
      H = c(`-2` = "na, see HMSENS7A", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      I = c(`-2` = "na, see IMSENS7A", `-1` = "na, asked", `1` = "no", `2` = "yes")
    ),
    msens19 = list(
      H = c(
        `-2` = "na, see HMSENS18",
        `-1` = "na, asked",
        `1` = "some of the time",
        `2` = "most of the time",
        `3` = "all of the time"
      ),
      I = c(
        `-2` = "na, see IMSENS18",
        `-1` = "na, asked",
        `1` = "some of the time",
        `2` = "most of the time",
        `3` = "all of the time"
      )
    ),
    msens20 = list(
      H = c(
        `-2` = "na, see HMSENS18",
        `-1` = "na, asked",
        `1` = "not annoying at all",
        `2` = "a bit annoying",
        `3` = "rather annoying",
        `4` = "most annoying"
      ),
      I = c(
        `-2` = "na, see IMSENS18",
        `-1` = "na, asked",
        `1` = "not annoying at all",
        `2` = "a bit annoying",
        `3` = "rather annoying",
        `4` = "most annoying"
      )
    ),
    msens7a = list(
      H = no_never_had_before_yes_possess_one_without_use,
      I = no_never_had_before_yes_possess_one_without_use,
      J = no_never_had_before_yes_possess_one_without_use_2,
      K = no_never_had_before_yes_possess_one_without_use_2
    ),
    msens7b = list(
      H = c(
        `-2` = "na, see HMSENS7A",
        `-1` = "na, asked",
        `1` = "< 1 hr a day",
        `2` = "1-4 hrs a day",
        `3` = "4-8 hrs a day",
        `4` = "all day"
      ),
      I = c(
        `-2` = "na, see IMSENS7A",
        `-1` = "na, asked",
        `1` = "< 1 hr a day",
        `2` = "1-4 hrs a day",
        `3` = "4-8 hrs a day",
        `4` = "all day"
      ),
      J = vs_1_hr_a_day_1_4_hrs_a_day_4_8_hrs_a_day_all_day_2,
      K = vs_1_hr_a_day_1_4_hrs_a_day_4_8_hrs_a_day_all_day_2
    ),
    msens10a = list(
      J = yes_without_difficulty_yes_with_some_difficulty_10,
      K = yes_without_difficulty_yes_with_some_difficulty_10
    ),
    msens12a = list(
      J = yes_without_difficulty_yes_with_some_difficulty_10,
      K = yes_without_difficulty_yes_with_some_difficulty_10
    ),
    msens17a = list(
      J = hardly_ever_sometimes_often_almost_always_2,
      K = hardly_ever_sometimes_often_almost_always_2
    ),
    msens21 = list(
      J = na_see_j_kmsens7a_na_asked,
      K = na_see_j_kmsens7a_na_asked
    ),
    msens7c = list(
      J = no_r_is_not_wearing_ha_yes_r_is_wearing_1_ha_left,
      K = no_r_is_not_wearing_ha_yes_r_is_wearing_1_ha_left
    )
  ),

  value_labels_harmonized = list(
    msens01 = c(`-5` = "not available, section not done", `-1` = "not available", `1` = "no", `2` = "yes"),
    msens02 = yes_without_difficulty_yes_with_some_difficulty_11,
    msens03 = yes_without_difficulty_yes_with_some_difficulty_33,
    msens04 = yes_without_difficulty_yes_with_some_difficulty_34,
    msens05 = yes_without_difficulty_yes_with_some_difficulty_33,
    msens06 = yes_without_difficulty_yes_with_some_difficulty_35,
    msens07 = no_yes_43,
    msens08 = yes_without_difficulty_yes_with_some_difficulty_11,
    msens09 = yes_without_difficulty_yes_with_some_difficulty_36,
    msens10 = yes_without_difficulty_yes_with_some_difficulty_37,
    msens10a = yes_without_difficulty_yes_with_some_difficulty_38,
    msens11 = yes_without_difficulty_yes_with_some_difficulty_11,
    msens12 = yes_without_difficulty_yes_with_some_difficulty_37,
    msens12a = yes_without_difficulty_yes_with_some_difficulty_38,
    msens13 = yes_without_difficulty_yes_with_some_difficulty_11,
    msens14 = no_yes_43,
    msens15 = no_yes_43,
    msens16 = hardly_ever_sometimes_often_almost_always_3,
    msens17 = hardly_ever_sometimes_often_almost_always_3,
    msens17a = c(
      `-2` = "not available, routing",
      `-1` = "not available",
      `1` = "hardly ever",
      `2` = "sometimes",
      `3` = "often",
      `4` = "almost always",
      `5` = "R does not wear a HA in this situation"
    ),
    msens18 = no_yes_43,
    msens19 = some_of_the_time_most_of_the_time_all_of_the_time_2,
    msens20 = not_annoying_at_all_a_bit_annoying_rather_annoying_2,
    msens21 = not_available_routing_not_available,
    msens7a = c(
      `-5` = "not available, section not done",
      `-1` = "not available",
      `1` = "no, never had before",
      `2` = "yes, possess one without use",
      `3` = "yes, possess two without use",
      `4` = "yes, possess one with use",
      `5` = "yes, possess two with use of one",
      `6` = "yes, possess two with use"
    ),
    msens7b = vs_1_hr_a_day_1_4_hrs_a_day_4_8_hrs_a_day_all_day_3,
    msens7c = c(
      `-2` = "not available, routing",
      `-1` = "not available",
      `1` = "no, R is not wearing HA",
      `2` = "yes, R is wearing 1 HA, left",
      `3` = "yes, R is wearing 1 HA, right",
      `4` = "yes, R is wearing 2 HA"
    ),
    sense01 = c(`-5` = "not available, interview terminated", `-1` = "not available", `1` = "no", `2` = "yes"),
    sense02 = yes_without_difficulty_yes_with_some_difficulty_5,
    sense03 = c(
      `-5` = "not available, interview terminated",
      `-2` = "not available, routing",
      `-1` = "not available",
      `1` = "yes, without difficulty",
      `2` = "yes, with some difficulty",
      `3` = "yes, with much difficulty",
      `4` = "no, I cannot"
    ),
    sense04 = yes_without_difficulty_yes_with_some_difficulty_34,
    sense05 = yes_without_difficulty_yes_with_some_difficulty_5,
    sense06 = yes_without_difficulty_yes_with_some_difficulty_35,
    sense07 = no_yes_43,
    sense08 = yes_without_difficulty_yes_with_some_difficulty_5,
    sense09 = yes_without_difficulty_yes_with_some_difficulty_36,
    sense10 = yes_without_difficulty_yes_with_some_difficulty_39,
    sense11 = yes_without_difficulty_yes_with_some_difficulty_5,
    sense12 = yes_without_difficulty_yes_with_some_difficulty_39,
    sense13 = yes_without_difficulty_yes_with_some_difficulty_5,
    sense14 = no_yes_43,
    sense18 = no_yes_43,
    sense19 = some_of_the_time_most_of_the_time_all_of_the_time_2,
    sense20 = not_annoying_at_all_a_bit_annoying_rather_annoying_2,
    sense7a = c(
      `-5` = "not available, section not done",
      `-1` = "not available",
      `1` = "no, never had before",
      `2` = "coding category 2",
      `3` = "coding category 3",
      `4` = "yes, possess one with use",
      `5` = "yes, possess two with use of one",
      `6` = "yes, possess two with use"
    ),
    sense7b = vs_1_hr_a_day_1_4_hrs_a_day_4_8_hrs_a_day_all_day_3
  )
)
