## LASA filecode 106 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_106 <- list(
  variables = data.frame(
    wave = c(
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bqworkd",
      "bqworkd1",
      "bqworkd10",
      "bqworkd11",
      "bqworkd12",
      "bqworkd13",
      "bqworkd14",
      "bqworkd15",
      "bqworkd16",
      "bqworkd17",
      "bqworkd18",
      "bqworkd19",
      "bqworkd2",
      "bqworkd20",
      "bqworkd21",
      "bqworkd3",
      "bqworkd4",
      "bqworkd5",
      "bqworkd6",
      "bqworkd7",
      "bqworkd8",
      "bqworkd9",
      "iqworkd",
      "iqworkd1",
      "iqworkd10",
      "iqworkd11",
      "iqworkd12",
      "iqworkd13",
      "iqworkd14",
      "iqworkd15",
      "iqworkd16",
      "iqworkd17",
      "iqworkd18",
      "iqworkd19",
      "iqworkd2",
      "iqworkd20",
      "iqworkd21",
      "iqworkd3",
      "iqworkd4",
      "iqworkd5",
      "iqworkd6",
      "iqworkd7",
      "iqworkd8",
      "iqworkd9",
      "jqworkd",
      "jqworkd1",
      "jqworkd10",
      "jqworkd11",
      "jqworkd12",
      "jqworkd13",
      "jqworkd14",
      "jqworkd15",
      "jqworkd16",
      "jqworkd17",
      "jqworkd18",
      "jqworkd19",
      "jqworkd2",
      "jqworkd20",
      "jqworkd21",
      "jqworkd3",
      "jqworkd4",
      "jqworkd5",
      "jqworkd6",
      "jqworkd7",
      "jqworkd8",
      "jqworkd9",
      "kqworkd",
      "kqworkd1",
      "kqworkd10",
      "kqworkd11",
      "kqworkd12",
      "kqworkd13",
      "kqworkd14",
      "kqworkd15",
      "kqworkd16",
      "kqworkd17",
      "kqworkd18",
      "kqworkd19",
      "kqworkd2",
      "kqworkd20",
      "kqworkd21",
      "kqworkd3",
      "kqworkd4",
      "kqworkd5",
      "kqworkd6",
      "kqworkd7",
      "kqworkd8",
      "kqworkd9",
      "bqworkYN",
      "bqworkn1",
      "bqworkn10",
      "bqworkn11",
      "bqworkn12",
      "bqworkn13",
      "bqworkn2",
      "bqworkn3",
      "bqworkn4",
      "bqworkn5",
      "bqworkn6",
      "bqworkn7",
      "bqworkn8",
      "bqworkn9",
      "bqworkp1",
      "bqworkp10",
      "bqworkp11",
      "bqworkp12",
      "bqworkp13",
      "bqworkp2",
      "bqworkp3",
      "bqworkp4",
      "bqworkp5",
      "bqworkp6",
      "bqworkp7",
      "bqworkp8",
      "bqworkp9"
    ),
    canonical_name = c(
      "qworkd",
      "qworkd1",
      "qworkd10",
      "qworkd11",
      "qworkd12",
      "qworkd13",
      "qworkd14",
      "qworkd15",
      "qworkd16",
      "qworkd17",
      "qworkd18",
      "qworkd19",
      "qworkd2",
      "qworkd20",
      "qworkd21",
      "qworkd3",
      "qworkd4",
      "qworkd5",
      "qworkd6",
      "qworkd7",
      "qworkd8",
      "qworkd9",
      "qworkd",
      "qworkd1",
      "qworkd10",
      "qworkd11",
      "qworkd12",
      "qworkd13",
      "qworkd14",
      "qworkd15",
      "qworkd16",
      "qworkd17",
      "qworkd18",
      "qworkd19",
      "qworkd2",
      "qworkd20",
      "qworkd21",
      "qworkd3",
      "qworkd4",
      "qworkd5",
      "qworkd6",
      "qworkd7",
      "qworkd8",
      "qworkd9",
      "qworkd",
      "qworkd1",
      "qworkd10",
      "qworkd11",
      "qworkd12",
      "qworkd13",
      "qworkd14",
      "qworkd15",
      "qworkd16",
      "qworkd17",
      "qworkd18",
      "qworkd19",
      "qworkd2",
      "qworkd20",
      "qworkd21",
      "qworkd3",
      "qworkd4",
      "qworkd5",
      "qworkd6",
      "qworkd7",
      "qworkd8",
      "qworkd9",
      "qworkd",
      "qworkd1",
      "qworkd10",
      "qworkd11",
      "qworkd12",
      "qworkd13",
      "qworkd14",
      "qworkd15",
      "qworkd16",
      "qworkd17",
      "qworkd18",
      "qworkd19",
      "qworkd2",
      "qworkd20",
      "qworkd21",
      "qworkd3",
      "qworkd4",
      "qworkd5",
      "qworkd6",
      "qworkd7",
      "qworkd8",
      "qworkd9",
      "qworkyn",
      "qworkn1",
      "qworkn10",
      "qworkn11",
      "qworkn12",
      "qworkn13",
      "qworkn2",
      "qworkn3",
      "qworkn4",
      "qworkn5",
      "qworkn6",
      "qworkn7",
      "qworkn8",
      "qworkn9",
      "qworkp1",
      "qworkp10",
      "qworkp11",
      "qworkp12",
      "qworkp13",
      "qworkp2",
      "qworkp3",
      "qworkp4",
      "qworkp5",
      "qworkp6",
      "qworkp7",
      "qworkp8",
      "qworkp9"
    ),
    variable_label = c(
      "work demands: ever had a job?",
      "work demands: use of force",
      "work demands: think of solutions",
      "work demands: when to take time off",
      "work demands: variation in tasks",
      "work demands: learn new things",
      "work demands: requires creativity",
      "work demands: requires thinking intensively",
      "work demands: requires focus",
      "work demands: requires attention",
      "work demands: help and support of colleagues",
      "work demands: colleagues willing to listen to work related problems",
      "work demands: using tools that cause vibration or shaking",
      "work demands: help and support of supervisor",
      "work demands: supervisor willing to listen to work related problems",
      "work demands: uncomfortable position",
      "work demands: standing for a long time",
      "work demands: kneeling down or squatting",
      "work demands: working very fast",
      "work demands: a lot of work",
      "work demands: control over how to do the job",
      "work demands: control over sequence of tasks",
      "work demands: ever had a job?",
      "work demands: use of force",
      "work demands: think of solutions",
      "work demands: when to take time off",
      "work demands: variation in tasks",
      "work demands: learn new things",
      "work demands: requires creativity",
      "work demands: requires thinking intensively",
      "work demands: requires focus",
      "work demands: requires attention",
      "work demands: help and support of colleagues",
      "work demands: colleagues willing to listen to work related problems",
      "work demands: using tools that cause vibration or shaking",
      "work demands: help and support of supervisor",
      "work demands: supervisor willing to listen to work related problems",
      "work demands: uncomfortable position",
      "work demands: standing for a long time",
      "work demands: kneeling down or squatting",
      "work demands: working very fast",
      "work demands: a lot of work",
      "work demands: control over how to do the job",
      "work demands: control over sequence of tasks",
      "work demands: ever had a job?",
      "work demands: use of force",
      "work demands: think of solutions",
      "work demands: when to take time off",
      "work demands: variation in tasks",
      "work demands: learn new things",
      "work demands: requires creativity",
      "work demands: requires thinking intensively",
      "work demands: requires focus",
      "work demands: requires attention",
      "work demands: help and support of colleagues",
      "work demands: colleagues willing to listen to work related problems",
      "work demands: using tools that cause vibration or shaking",
      "work demands: help and support of supervisor",
      "work demands: supervisor willing to listen to work related problems",
      "work demands: uncomfortable position",
      "work demands: standing for a long time",
      "work demands: kneeling down or squatting",
      "work demands: working very fast",
      "work demands: a lot of work",
      "work demands: control over how to do the job",
      "work demands: control over sequence of tasks",
      "work demands: ever had a job?",
      "work demands: use of force",
      "work demands: think of solutions",
      "work demands: when to take time off",
      "work demands: variation in tasks",
      "work demands: learn new things",
      "work demands: requires creativity",
      "work demands: requires thinking intensively",
      "work demands: requires focus",
      "work demands: requires attention",
      "work demands: help and support of colleagues",
      "work demands: colleagues willing to listen to work related problems",
      "work demands: using tools that cause vibration or shaking",
      "work demands: help and support of supervisor",
      "work demands: supervisor willing to listen to work related problems",
      "work demands: uncomfortable position",
      "work demands: standing for a long time",
      "work demands: kneeling down or squatting",
      "work demands: working very fast",
      "work demands: a lot of work",
      "work demands: control over how to do the job",
      "work demands: control over sequence of tasks",
      "work demands: ever had a job?",
      "work demands: use of force",
      "work demands: variation in tasks",
      "work demands: requires thinking intensively",
      "work demands: colleagues willing to listen to work related problems",
      "work demands: supervisor willing to listen to work related problems",
      "work demands: using tools that cause vibration or shaking",
      "work demands: uncomfortable position",
      "work demands: standing for a long time",
      "work demands: kneeling down or squatting",
      "work demands: working very fast",
      "work demands: a lot of work",
      "work demands: control over how to do the job",
      "work demands: control over sequence of tasks",
      "work demanded: use of force",
      "work demanded: variation in tasks",
      "work demanded: requires thinking intensively",
      "work demanded: colleagues willing to listen to work related problems",
      "work demanded: supervisor willing to listen to work related problems",
      "work demanded: using tools that cause vibration or shaking",
      "work demanded: uncomfortable position",
      "work demanded: standing for a long time",
      "work demanded: kneeling down or squatting",
      "work demanded: working very fast",
      "work demanded: a lot of work",
      "work demanded: control over how to do the job",
      "work demanded: control over sequence of tasks"
    ),
    harmonized_var_label = c(
      "work demands: ever had a job?",
      "work demands: use of force",
      "work demands: think of solutions",
      "work demands: when to take time off",
      "work demands: variation in tasks",
      "work demands: learn new things",
      "work demands: requires creativity",
      "work demands: requires thinking intensively",
      "work demands: requires focus",
      "work demands: requires attention",
      "work demands: help and support of colleagues",
      "work demands: colleagues willing to listen to work related problems",
      "work demands: using tools that cause vibration or shaking",
      "work demands: help and support of supervisor",
      "work demands: supervisor willing to listen to work related problems",
      "work demands: uncomfortable position",
      "work demands: standing for a long time",
      "work demands: kneeling down or squatting",
      "work demands: working very fast",
      "work demands: a lot of work",
      "work demands: control over how to do the job",
      "work demands: control over sequence of tasks",
      "work demands: ever had a job?",
      "work demands: use of force",
      "work demands: think of solutions",
      "work demands: when to take time off",
      "work demands: variation in tasks",
      "work demands: learn new things",
      "work demands: requires creativity",
      "work demands: requires thinking intensively",
      "work demands: requires focus",
      "work demands: requires attention",
      "work demands: help and support of colleagues",
      "work demands: colleagues willing to listen to work related problems",
      "work demands: using tools that cause vibration or shaking",
      "work demands: help and support of supervisor",
      "work demands: supervisor willing to listen to work related problems",
      "work demands: uncomfortable position",
      "work demands: standing for a long time",
      "work demands: kneeling down or squatting",
      "work demands: working very fast",
      "work demands: a lot of work",
      "work demands: control over how to do the job",
      "work demands: control over sequence of tasks",
      "work demands: ever had a job?",
      "work demands: use of force",
      "work demands: think of solutions",
      "work demands: when to take time off",
      "work demands: variation in tasks",
      "work demands: learn new things",
      "work demands: requires creativity",
      "work demands: requires thinking intensively",
      "work demands: requires focus",
      "work demands: requires attention",
      "work demands: help and support of colleagues",
      "work demands: colleagues willing to listen to work related problems",
      "work demands: using tools that cause vibration or shaking",
      "work demands: help and support of supervisor",
      "work demands: supervisor willing to listen to work related problems",
      "work demands: uncomfortable position",
      "work demands: standing for a long time",
      "work demands: kneeling down or squatting",
      "work demands: working very fast",
      "work demands: a lot of work",
      "work demands: control over how to do the job",
      "work demands: control over sequence of tasks",
      "work demands: ever had a job?",
      "work demands: use of force",
      "work demands: think of solutions",
      "work demands: when to take time off",
      "work demands: variation in tasks",
      "work demands: learn new things",
      "work demands: requires creativity",
      "work demands: requires thinking intensively",
      "work demands: requires focus",
      "work demands: requires attention",
      "work demands: help and support of colleagues",
      "work demands: colleagues willing to listen to work related problems",
      "work demands: using tools that cause vibration or shaking",
      "work demands: help and support of supervisor",
      "work demands: supervisor willing to listen to work related problems",
      "work demands: uncomfortable position",
      "work demands: standing for a long time",
      "work demands: kneeling down or squatting",
      "work demands: working very fast",
      "work demands: a lot of work",
      "work demands: control over how to do the job",
      "work demands: control over sequence of tasks",
      "work demands: ever had a job?",
      "work demands: use of force",
      "work demands: variation in tasks",
      "work demands: requires thinking intensively",
      "work demands: colleagues willing to listen to work related problems",
      "work demands: supervisor willing to listen to work related problems",
      "work demands: using tools that cause vibration or shaking",
      "work demands: uncomfortable position",
      "work demands: standing for a long time",
      "work demands: kneeling down or squatting",
      "work demands: working very fast",
      "work demands: a lot of work",
      "work demands: control over how to do the job",
      "work demands: control over sequence of tasks",
      "work demanded: use of force",
      "work demanded: variation in tasks",
      "work demanded: requires thinking intensively",
      "work demanded: colleagues willing to listen to work related problems",
      "work demanded: supervisor willing to listen to work related problems",
      "work demanded: using tools that cause vibration or shaking",
      "work demanded: uncomfortable position",
      "work demanded: standing for a long time",
      "work demanded: kneeling down or squatting",
      "work demanded: working very fast",
      "work demanded: a lot of work",
      "work demanded: control over how to do the job",
      "work demanded: control over sequence of tasks"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qworkd = list(
      `3B` = never_had_a_job_has_had_a_job,
      I = never_had_a_job_has_had_a_job,
      J = never_had_a_job_has_had_a_job,
      K = never_had_a_job_has_had_a_job
    ),
    qworkd1 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd10 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd11 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd12 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd13 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd14 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd15 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd16 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd17 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd18 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_not_applicable_3,
      K = never_sometimes_often_all_the_time_not_applicable_4
    ),
    qworkd19 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_not_applicable_3,
      K = never_sometimes_often_all_the_time_not_applicable_4
    ),
    qworkd2 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd20 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_not_applicable_3,
      K = never_sometimes_often_all_the_time_not_applicable_4
    ),
    qworkd21 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_not_applicable_3,
      K = never_sometimes_often_all_the_time_not_applicable_4
    ),
    qworkd3 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd4 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd5 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd6 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd7 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd8 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkd9 = list(
      `3B` = never_sometimes_often_all_the_time_3,
      I = never_sometimes_often_all_the_time_not_applicable,
      J = never_sometimes_often_all_the_time_4,
      K = never_sometimes_often_all_the_time_5
    ),
    qworkn1 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn10 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn11 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn12 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn13 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn2 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn3 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn4 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn5 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn6 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn7 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn8 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkn9 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp1 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp10 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp11 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp12 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp13 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp2 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp3 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp4 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp5 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp6 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp7 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp8 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkp9 = list(
      MB = never_sometimes_often_all_the_time
    ),
    qworkyn = list(
      MB = c(`-1` = "na, asked", `1` = "never had a job", `2` = "had a job", `3` = "has a job")
    )
  ),

  value_labels_harmonized = list(
    qworkd = c(`-1` = "not available, asked", `1` = "never had a job", `2` = "has/had a job"),
    qworkd1 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd10 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd11 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd12 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd13 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd14 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd15 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd16 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd17 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd18 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd19 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd2 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd20 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd21 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd3 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd4 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd5 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd6 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd7 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd8 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkd9 = never_sometimes_often_all_the_time_not_applicable_2,
    qworkn1 = never_sometimes_often_all_the_time_2,
    qworkn10 = never_sometimes_often_all_the_time_2,
    qworkn11 = never_sometimes_often_all_the_time_2,
    qworkn12 = never_sometimes_often_all_the_time_2,
    qworkn13 = never_sometimes_often_all_the_time_2,
    qworkn2 = never_sometimes_often_all_the_time_2,
    qworkn3 = never_sometimes_often_all_the_time_2,
    qworkn4 = never_sometimes_often_all_the_time_2,
    qworkn5 = never_sometimes_often_all_the_time_2,
    qworkn6 = never_sometimes_often_all_the_time_2,
    qworkn7 = never_sometimes_often_all_the_time_2,
    qworkn8 = never_sometimes_often_all_the_time_2,
    qworkn9 = never_sometimes_often_all_the_time_2,
    qworkp1 = never_sometimes_often_all_the_time_2,
    qworkp10 = never_sometimes_often_all_the_time_2,
    qworkp11 = never_sometimes_often_all_the_time_2,
    qworkp12 = never_sometimes_often_all_the_time_2,
    qworkp13 = never_sometimes_often_all_the_time_2,
    qworkp2 = never_sometimes_often_all_the_time_2,
    qworkp3 = never_sometimes_often_all_the_time_2,
    qworkp4 = never_sometimes_often_all_the_time_2,
    qworkp5 = never_sometimes_often_all_the_time_2,
    qworkp6 = never_sometimes_often_all_the_time_2,
    qworkp7 = never_sometimes_often_all_the_time_2,
    qworkp8 = never_sometimes_often_all_the_time_2,
    qworkp9 = never_sometimes_often_all_the_time_2,
    qworkyn = c(`-1` = "not available, asked", `1` = "never had a job", `2` = "had a job", `3` = "has a job")
  )
)
