## LASA filecode 171 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_171 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H"
    ),
    variable_name = c(
      "bmcalf02",
      "bmcalf03",
      "bmcalf04",
      "bmcalf06",
      "bmcalf1",
      "bmcalf12",
      "bmcalf13",
      "bmcalf01",
      "bmcalf02",
      "bmcalf03",
      "bmcalf04",
      "bmcalf06",
      "bmcalf12",
      "bmcalf13",
      "brm171",
      "bmcalf01",
      "bmcalf02",
      "bmcalf03",
      "bmcalf04",
      "bmcalf05",
      "bmcalf06",
      "bmcalf07",
      "bmcalf08",
      "bmcalf09",
      "bmcalf10",
      "bmcalf11",
      "dmcalf02",
      "dmcalf03",
      "dmcalf04",
      "dmcalf06",
      "dmcalf12",
      "dmcalf13",
      "dmcalf1a",
      "dmcalf1b",
      "drm161",
      "emcalf02",
      "emcalf03",
      "emcalf04",
      "emcalf06",
      "emcalf12",
      "emcalf13",
      "emcalf1a",
      "emcalf1b",
      "erm161",
      "fmcalf02",
      "fmcalf1a",
      "fmcalf1b",
      "frm161",
      "gmcalf02",
      "gmcalf03",
      "gmcalf04",
      "gmcalf06",
      "gmcalf12",
      "gmcalf13",
      "gmcalf1a",
      "gmcalf1b",
      "grm161",
      "hmcalf01",
      "hmcalf02",
      "hmcalf03",
      "hmcalf04",
      "hmcalf06",
      "hmcalf12",
      "hmcalf13",
      "hrm171"
    ),
    canonical_name = c(
      "mcalf02",
      "mcalf03",
      "mcalf04",
      "mcalf06",
      "mcalf1",
      "mcalf12",
      "mcalf13",
      "mcalf01",
      "mcalf02",
      "mcalf03",
      "mcalf04",
      "mcalf06",
      "mcalf12",
      "mcalf13",
      "rm171",
      "mcalf01",
      "mcalf02",
      "mcalf03",
      "mcalf04",
      "mcalf05",
      "mcalf06",
      "mcalf07",
      "mcalf08",
      "mcalf09",
      "mcalf10",
      "mcalf11",
      "mcalf02",
      "mcalf03",
      "mcalf04",
      "mcalf06",
      "mcalf12",
      "mcalf13",
      "mcalf1a",
      "mcalf1b",
      "rm161",
      "mcalf02",
      "mcalf03",
      "mcalf04",
      "mcalf06",
      "mcalf12",
      "mcalf13",
      "mcalf1a",
      "mcalf1b",
      "rm161",
      "mcalf02",
      "mcalf1a",
      "mcalf1b",
      "rm161",
      "mcalf02",
      "mcalf03",
      "mcalf04",
      "mcalf06",
      "mcalf12",
      "mcalf13",
      "mcalf1a",
      "mcalf1b",
      "rm161",
      "mcalf01",
      "mcalf02",
      "mcalf03",
      "mcalf04",
      "mcalf06",
      "mcalf12",
      "mcalf13",
      "rm171"
    ),
    variable_label = c(
      "Calf particularities",
      "Calf: refused",
      "Calf: R sitting down",
      "Calf: on right leg",
      "Measured calf in cm",
      "Calf: no bare leg",
      "Calf: much space between tape and leg",
      "Measured calf in cm",
      "Calf particularities",
      "Calf: refused",
      "Calf: R sitting down",
      "Calf: on right leg",
      "Calf: no bare leg",
      "Calf: much space between tape and leg",
      "Reason missing: LASAH/B171",
      "circumference: in cm",
      "measurement: remarks Y/N",
      "remark: refused",
      "remark: sitting down",
      "remark: not physically able",
      "remark: on right calf",
      "remark: impediments",
      "remark: edema present",
      "remark: support stocking",
      "remark: long underwear",
      "remark other",
      "Calf particularities",
      "Calf: refused",
      "Calf: R sitting down",
      "Calf: on right leg",
      "Calf: no bare leg",
      "Calf: much space between tape and leg",
      "Measured calf (1) in cm",
      "Measured calf (2) in cm",
      NA_character_,
      "Calf particularities",
      "Calf: refused",
      "Calf: R sitting down",
      "Calf: on right leg",
      "Calf: no bare leg",
      "Calf: much space between tape and leg",
      "Measured calf (1) in cm",
      "Measured calf (2) in cm",
      NA_character_,
      "Calf particularities",
      "Measured calf (1) in cm",
      "Measured calf (2) in cm",
      NA_character_,
      "Calf particularities",
      "Calf: refused",
      "Calf: R sitting down",
      "Calf: on right leg",
      "Calf: no bare leg",
      "Calf: much space between tape and leg",
      "Measured calf (1) in cm",
      "Measured calf (2) in cm",
      NA_character_,
      "Measured calf in cm",
      "Calf particularities",
      "Calf: refused",
      "Calf: R sitting down",
      "Calf: on right leg",
      "Calf: no bare leg",
      "Calf: much space between tape and leg",
      "Reason missing: LASAH/B171"
    ),
    harmonized_var_label = c(
      "calf measurement particularities",
      "calf particularity: refused",
      "calf particularity: respondent sitting down",
      "calf particularity: on right leg",
      "measured calf in cm",
      "calf particularity: no bare leg",
      "calf particularity: much space between tape and leg",
      "measured calf circumference in cm",
      "calf measurement particularities",
      "calf particularity: refused",
      "calf particularity: respondent sitting down",
      "calf particularity: on right leg",
      "calf particularity: no bare leg",
      "calf particularity: much space between tape and leg",
      "reason missing / data status",
      "measured calf circumference in cm",
      "calf measurement particularities",
      "calf particularity: refused",
      "calf particularity: respondent sitting down",
      "calf particularity: not physically able",
      "calf particularity: on right leg",
      "calf particularity: impediments",
      "calf particularity: edema present",
      "calf particularity: support stocking",
      "calf particularity: long underwear",
      "calf particularity: other",
      "calf measurement particularities",
      "calf particularity: refused",
      "calf particularity: respondent sitting down",
      "calf particularity: on right leg",
      "calf particularity: no bare leg",
      "calf particularity: much space between tape and leg",
      "measured calf (1) in cm",
      "measured calf (2) in cm",
      "data status",
      "calf measurement particularities",
      "calf particularity: refused",
      "calf particularity: respondent sitting down",
      "calf particularity: on right leg",
      "calf particularity: no bare leg",
      "calf particularity: much space between tape and leg",
      "measured calf (1) in cm",
      "measured calf (2) in cm",
      "data status",
      "calf measurement particularities",
      "measured calf (1) in cm",
      "measured calf (2) in cm",
      "data status",
      "calf measurement particularities",
      "calf particularity: refused",
      "calf particularity: respondent sitting down",
      "calf particularity: on right leg",
      "calf particularity: no bare leg",
      "calf particularity: much space between tape and leg",
      "measured calf (1) in cm",
      "measured calf (2) in cm",
      "data status",
      "measured calf circumference in cm",
      "calf measurement particularities",
      "calf particularity: refused",
      "calf particularity: respondent sitting down",
      "calf particularity: on right leg",
      "calf particularity: no bare leg",
      "calf particularity: much space between tape and leg",
      "reason missing / data status"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mcalf02 = list(
      `2B` = c(`-3` = "na, wrong skip", `-2` = "na, see BRM161", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      `3B` = not_mentioned_mentioned_291,
      B = no_yes_not_done_various_reasons,
      D = no_yes_346,
      E = no_yes_346,
      F = c(
        `-2` = "na, see FRM161",
        `-1` = "na, asked",
        `1` = "no particularities",
        `2` = "no bare leg",
        `3` = "much space between tape and leg",
        `4` = "R sitting down",
        `5` = "on right leg",
        `6` = "R refused"
      ),
      G = no_yes_344,
      H = not_mentioned_mentioned_291
    ),
    mcalf03 = list(
      `2B` = not_mentioned_mentioned_235,
      `3B` = not_mentioned_mentioned_170,
      B = no_yes_not_done_various_reasons,
      D = not_mentioned_mentioned_171,
      E = not_mentioned_mentioned_171,
      G = not_mentioned_mentioned_236,
      H = not_mentioned_mentioned_170
    ),
    mcalf04 = list(
      `2B` = not_mentioned_mentioned_235,
      `3B` = not_mentioned_mentioned_170,
      B = no_yes_not_done_various_reasons,
      D = not_mentioned_mentioned_171,
      E = not_mentioned_mentioned_171,
      G = not_mentioned_mentioned_236,
      H = not_mentioned_mentioned_170
    ),
    mcalf06 = list(
      `2B` = not_mentioned_mentioned_235,
      `3B` = not_mentioned_mentioned_170,
      B = no_yes_not_done_various_reasons,
      D = not_mentioned_mentioned_171,
      E = not_mentioned_mentioned_171,
      G = not_mentioned_mentioned_236,
      H = not_mentioned_mentioned_170
    ),
    mcalf1 = list(
      `2B` = na_wrong_skip_na_see_brm161_na_asked
    ),
    mcalf12 = list(
      `2B` = not_mentioned_mentioned_235,
      `3B` = not_mentioned_mentioned_170,
      D = not_mentioned_mentioned_171,
      E = not_mentioned_mentioned_171,
      G = not_mentioned_mentioned_236,
      H = not_mentioned_mentioned_170
    ),
    mcalf13 = list(
      `2B` = not_mentioned_mentioned_235,
      `3B` = not_mentioned_mentioned_170,
      D = not_mentioned_mentioned_171,
      E = not_mentioned_mentioned_171,
      G = not_mentioned_mentioned_236,
      H = not_mentioned_mentioned_170
    ),
    mcalf01 = list(
      `3B` = na_see_h_brm171_na_asked,
      B = c(`-3` = "not in sample", `-1` = "no measurement"),
      H = na_see_h_brm171_na_asked
    ),
    rm171 = list(
      `3B` = to_be_coded_short_version_interview_terminated,
      H = to_be_coded_short_version_interview_terminated
    ),
    mcalf05 = list(
      B = no_yes_not_done_various_reasons
    ),
    mcalf07 = list(
      B = no_yes_not_done_various_reasons
    ),
    mcalf08 = list(
      B = no_yes_not_done_various_reasons
    ),
    mcalf09 = list(
      B = no_yes_not_done_various_reasons
    ),
    mcalf10 = list(
      B = no_yes_not_done_various_reasons
    ),
    mcalf11 = list(
      B = no_yes_not_done_various_reasons
    ),
    mcalf1a = list(
      D = na_wrong_skip_na_see_d_erm161_na_asked,
      E = na_wrong_skip_na_see_d_erm161_na_asked,
      F = na_see_frm161_na_asked,
      G = na_see_grm161_na_asked
    ),
    mcalf1b = list(
      D = na_wrong_skip_na_see_d_erm161_na_asked,
      E = na_wrong_skip_na_see_d_erm161_na_asked,
      F = na_see_frm161_na_asked,
      G = na_see_grm161_na_asked
    ),
    rm161 = list(
      D = interview_terminated,
      E = interview_terminated,
      F = short_version_interview_terminated_2,
      G = to_be_coded_short_version_interview_terminated
    )
  ),

  value_labels_harmonized = list(
    mcalf01 = c(`-3` = "not in sample", `-2` = "na, see H/BRM171", `-1` = "measurement missing"),
    mcalf02 = c(
      `-3` = "not applicable / skipped",
      `-2` = "na, see BRM161",
      `-1` = "na, asked",
      `0` = "not mentioned",
      `1` = "particularity status",
      `2` = "particularity status or category",
      `3` = "measurement/particularity status",
      `4` = "R sitting down",
      `5` = "on right leg",
      `6` = "R refused"
    ),
    mcalf03 = not_mentioned_particularity_status_yes,
    mcalf04 = not_mentioned_particularity_status_yes,
    mcalf05 = no_yes_not_done_various_reasons,
    mcalf06 = not_mentioned_particularity_status_yes,
    mcalf07 = no_yes_not_done_various_reasons,
    mcalf08 = no_yes_not_done_various_reasons,
    mcalf09 = no_yes_not_done_various_reasons,
    mcalf1 = na_wrong_skip_na_see_brm161_na_asked,
    mcalf10 = no_yes_not_done_various_reasons,
    mcalf11 = no_yes_not_done_various_reasons,
    mcalf12 = not_mentioned_mentioned_292,
    mcalf13 = not_mentioned_mentioned_292,
    mcalf1a = na_wrong_skip_na_see_frm161_na_asked,
    mcalf1b = na_wrong_skip_na_see_frm161_na_asked,
    rm161 = to_be_coded_short_version_interview_terminated,
    rm171 = to_be_coded_short_version_interview_terminated
  )
)
