## LASA filecode 114 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_114 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F"
    ),
    variable_name = c(
      "bqseff01",
      "bqseff02",
      "bqseff03",
      "bqseff04",
      "bqseff05",
      "bqseff06",
      "bqseff07",
      "bqseff08",
      "bqseff09",
      "bqseff10",
      "bqseff01",
      "bqseff02",
      "bqseff03",
      "bqseff04",
      "bqseff05",
      "bqseff06",
      "bqseff07",
      "bqseff08",
      "bqseff09",
      "bqseff10",
      "cqseff01",
      "cqseff02",
      "cqseff03",
      "cqseff04",
      "cqseff05",
      "cqseff06",
      "cqseff07",
      "cqseff08",
      "cqseff09",
      "cqseff10",
      "dqseff01",
      "dqseff02",
      "dqseff03",
      "dqseff04",
      "dqseff05",
      "dqseff06",
      "dqseff07",
      "dqseff08",
      "dqseff09",
      "dqseff10",
      "eqseff01",
      "eqseff02",
      "eqseff03",
      "eqseff04",
      "eqseff05",
      "eqseff06",
      "eqseff07",
      "eqseff08",
      "eqseff09",
      "eqseff10",
      "fqseff01",
      "fqseff02",
      "fqseff03",
      "fqseff04",
      "fqseff05",
      "fqseff06",
      "fqseff07",
      "fqseff08",
      "fqseff09",
      "fqseff10"
    ),
    canonical_name = c(
      "qseff01",
      "qseff02",
      "qseff03",
      "qseff04",
      "qseff05",
      "qseff06",
      "qseff07",
      "qseff08",
      "qseff09",
      "qseff10",
      "qseff01",
      "qseff02",
      "qseff03",
      "qseff04",
      "qseff05",
      "qseff06",
      "qseff07",
      "qseff08",
      "qseff09",
      "qseff10",
      "qseff01",
      "qseff02",
      "qseff03",
      "qseff04",
      "qseff05",
      "qseff06",
      "qseff07",
      "qseff08",
      "qseff09",
      "qseff10",
      "qseff01",
      "qseff02",
      "qseff03",
      "qseff04",
      "qseff05",
      "qseff06",
      "qseff07",
      "qseff08",
      "qseff09",
      "qseff10",
      "qseff01",
      "qseff02",
      "qseff03",
      "qseff04",
      "qseff05",
      "qseff06",
      "qseff07",
      "qseff08",
      "qseff09",
      "qseff10",
      "qseff01",
      "qseff02",
      "qseff03",
      "qseff04",
      "qseff05",
      "qseff06",
      "qseff07",
      "qseff08",
      "qseff09",
      "qseff10"
    ),
    variable_label = c(
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)",
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)",
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)",
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)",
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)",
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)"
    ),
    harmonized_var_label = c(
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "Self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "Self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "Self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)",
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "Self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "Self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "Self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)",
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "Self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "Self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "Self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)",
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "Self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "Self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "Self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)",
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "Self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "Self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "Self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)",
      "Self efficacy 1: flexible (+)",
      "Self efficacy 2: reaction time (+)",
      "Self efficacy 3: strong (-)",
      "Self efficacy 4: good condition (+)",
      "Self efficacy 5: move smoothly (-)",
      "Self efficacy 6: stairs (+)",
      "Self efficacy 7: strong grip (+)",
      "Self efficacy 8: walk fast (-)",
      "Self efficacy 9: good balance (+)",
      "Self efficacy 10: active (-)"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qseff01 = list(
      `2B` = much_more_flexible_more_flexible_just_as_flexible,
      B = much_more_flexible_more_flexible_just_as_flexible,
      C = much_more_flexible_more_flexible_just_as_flexible,
      D = much_more_flexible_more_flexible_just_as_flexible,
      E = much_more_flexible_more_flexible_just_as_flexible,
      F = much_more_flexible_more_flexible_just_as_flexible
    ),
    qseff02 = list(
      `2B` = much_better_better_just_as_good_worse_much_worse,
      B = much_better_better_just_as_good_worse_much_worse,
      C = much_better_better_just_as_good_worse_much_worse,
      D = much_better_better_just_as_good_worse_much_worse,
      E = much_better_better_just_as_good_worse_much_worse,
      F = much_better_better_just_as_good_worse_much_worse
    ),
    qseff03 = list(
      `2B` = much_less_strong_less_strong_just_as_strong_stronger,
      B = much_less_strong_less_strong_just_as_strong_stronger,
      C = much_less_strong_less_strong_just_as_strong_stronger,
      D = much_less_strong_less_strong_just_as_strong_stronger,
      E = much_less_strong_less_strong_just_as_strong_stronger,
      F = much_less_strong_less_strong_just_as_strong_stronger
    ),
    qseff04 = list(
      `2B` = much_better_better_just_as_good_worse_much_worse,
      B = much_better_better_just_as_good_worse_much_worse,
      C = much_better_better_just_as_good_worse_much_worse,
      D = much_better_better_just_as_good_worse_much_worse,
      E = much_better_better_just_as_good_worse_much_worse,
      F = much_better_better_just_as_good_worse_much_worse
    ),
    qseff05 = list(
      `2B` = much_less_smoothly_less_smoothly_just_as_smoothly,
      B = much_less_smoothly_less_smoothly_just_as_smoothly,
      C = much_less_smoothly_less_smoothly_just_as_smoothly,
      D = much_less_smoothly_less_smoothly_just_as_smoothly,
      E = much_less_smoothly_less_smoothly_just_as_smoothly,
      F = much_less_smoothly_less_smoothly_just_as_smoothly
    ),
    qseff06 = list(
      `2B` = much_more_easy_more_easy_just_as_easy_more_difficult,
      B = much_more_easy_more_easy_just_as_easy_more_difficult,
      C = much_more_easy_more_easy_just_as_easy_more_difficult,
      D = much_more_easy_more_easy_just_as_easy_more_difficult,
      E = much_more_easy_more_easy_just_as_easy_more_difficult,
      F = much_more_easy_more_easy_just_as_easy_more_difficult
    ),
    qseff07 = list(
      `2B` = much_greater_greater_smaller_less_much_smaller,
      B = much_greater_greater_smaller_less_much_smaller,
      C = much_greater_greater_smaller_less_much_smaller,
      D = much_greater_greater_smaller_less_much_smaller,
      E = much_greater_greater_smaller_less_much_smaller,
      F = much_greater_greater_smaller_less_much_smaller
    ),
    qseff08 = list(
      `2B` = much_slower_slower_just_as_fast_faster_much_faster,
      B = much_slower_slower_just_as_fast_faster_much_faster,
      C = much_slower_slower_just_as_fast_faster_much_faster,
      D = much_slower_slower_just_as_fast_faster_much_faster,
      E = much_slower_slower_just_as_fast_faster_much_faster,
      F = much_slower_slower_just_as_fast_faster_much_faster
    ),
    qseff09 = list(
      `2B` = much_better_better_just_as_good_worse_much_worse,
      B = much_better_better_just_as_good_worse_much_worse,
      C = much_better_better_just_as_good_worse_much_worse,
      D = much_better_better_just_as_good_worse_much_worse,
      E = much_better_better_just_as_good_worse_much_worse,
      F = much_better_better_just_as_good_worse_much_worse
    ),
    qseff10 = list(
      `2B` = much_less_active_less_active_just_as_active_more_active,
      B = much_less_active_less_active_just_as_active_more_active,
      C = much_less_active_less_active_just_as_active_more_active,
      D = much_less_active_less_active_just_as_active_more_active,
      E = much_less_active_less_active_just_as_active_more_active,
      F = much_less_active_less_active_just_as_active_more_active
    )
  ),

  value_labels_harmonized = list(
    qseff01 = c(
      `-1` = "not available",
      `1` = "much more flexible",
      `2` = "more flexible",
      `3` = "just as flexible",
      `4` = "less flexible",
      `5` = "much less flexible"
    ),
    qseff02 = much_better_better_just_as_good_worse_much_worse_2,
    qseff03 = c(
      `-1` = "not available",
      `1` = "much less strong",
      `2` = "less strong",
      `3` = "just as strong",
      `4` = "stronger",
      `5` = "much stronger"
    ),
    qseff04 = much_better_better_just_as_good_worse_much_worse_2,
    qseff05 = c(
      `-1` = "not available",
      `1` = "much less smoothly",
      `2` = "less smoothly",
      `3` = "just as smoothly",
      `4` = "more smoothly",
      `5` = "much more smoothly"
    ),
    qseff06 = c(
      `-1` = "not available",
      `1` = "much more easy",
      `2` = "more easy",
      `3` = "just as easy",
      `4` = "more difficult",
      `5` = "much more difficult"
    ),
    qseff07 = c(
      `-1` = "not available",
      `1` = "much greater",
      `2` = "greater",
      `3` = "smaller",
      `4` = "less",
      `5` = "much smaller"
    ),
    qseff08 = c(
      `-1` = "not available",
      `1` = "much slower",
      `2` = "slower",
      `3` = "just as fast",
      `4` = "faster",
      `5` = "much faster"
    ),
    qseff09 = much_better_better_just_as_good_worse_much_worse_2,
    qseff10 = c(
      `-1` = "not available",
      `1` = "much less active",
      `2` = "less active",
      `3` = "just as active",
      `4` = "more active",
      `5` = "much more active"
    )
  )
)
