## LASA filecode 156 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_156 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bm15wrp0",
      "bm15wrp1",
      "bm15wrp2",
      "bm15wrp3",
      "bm15wrp4",
      "bm15wrp5",
      "bm15wrpx",
      "bm15wrth",
      "bm15wrtm",
      "bm15wt",
      "bm15wt1nd",
      "bm15wt1no",
      "bm15wt2nd",
      "bm15wt2no",
      "bm15wt3nd",
      "bm15wt3no",
      "bm15wtdr",
      "bm15wth",
      "bm15wtm",
      "bm15wtp0",
      "bm15wtp1",
      "bm15wtp2",
      "bm15wtp3",
      "bm15wtp4",
      "bm15wtp5",
      "bm15wtpx",
      "bm15wtr",
      "bm15wtrnd",
      "bm15wtrno",
      "bmrecali",
      "bmwtt1",
      "bmwtt2",
      "bmwtt3",
      "bm15wrp0",
      "bm15wrp1",
      "bm15wrp2",
      "bm15wrp3",
      "bm15wrp4",
      "bm15wrp5",
      "bm15wrpx",
      "bm15wrt",
      "bm15wrtm",
      "bm15wt",
      "bm15wt1nd",
      "bm15wt1no",
      "bm15wt2nd",
      "bm15wt2no",
      "bm15wt3nd",
      "bm15wt3no",
      "bm15wth",
      "bm15wtp0",
      "bm15wtp1",
      "bm15wtp2",
      "bm15wtp3",
      "bm15wtp4",
      "bm15wtp5",
      "bm15wtpx",
      "bm15wtr",
      "bm15wtrnd",
      "bm15wtrno",
      "bmrecali",
      "bmwtdr",
      "bmwtt1",
      "bmwtt2",
      "bmwtt3",
      "bm15twtrh",
      "bm15wt101",
      "bm15wt102",
      "bm15wt103",
      "bm15wt104",
      "bm15wt105",
      "bm15wt106",
      "bm15wt107",
      "bm15wt108",
      "bm15wt109",
      "bm15wt110",
      "bm15wt111",
      "bm15wt112",
      "bm15wt113",
      "bm15wt114",
      "bm15wt115",
      "bm15wt1nd",
      "bm15wt1no",
      "bm15wt201",
      "bm15wt202",
      "bm15wt203",
      "bm15wt204",
      "bm15wt205",
      "bm15wt206",
      "bm15wt207",
      "bm15wt208",
      "bm15wt209",
      "bm15wt210",
      "bm15wt211",
      "bm15wt212",
      "bm15wt213",
      "bm15wt214",
      "bm15wt215",
      "bm15wt2nd",
      "bm15wt2no",
      "bm15wt301",
      "bm15wt302",
      "bm15wt303",
      "bm15wt304",
      "bm15wt305",
      "bm15wt306",
      "bm15wt307",
      "bm15wt308",
      "bm15wt309",
      "bm15wt310",
      "bm15wt311",
      "bm15wt312",
      "bm15wt313",
      "bm15wt314",
      "bm15wt315",
      "bm15wt3nd",
      "bm15wt3no",
      "bm15wth",
      "bm15wtm",
      "bm15wtr01",
      "bm15wtr02",
      "bm15wtr03",
      "bm15wtr04",
      "bm15wtr05",
      "bm15wtr06",
      "bm15wtr07",
      "bm15wtr08",
      "bm15wtr09",
      "bm15wtr10",
      "bm15wtr11",
      "bm15wtr12",
      "bm15wtr13",
      "bm15wtr14",
      "bm15wtr15",
      "bm15wtrm",
      "bm15wtrnd",
      "bm15wtrno",
      "bmrecal",
      "c15wtrth",
      "c15wtrtm",
      "cm15wdrm",
      "cm15wpt1",
      "cm15wpt2",
      "cm15wpt3",
      "cm15wpt4",
      "cm15wpt5",
      "cm15wrp0",
      "cm15wrp1",
      "cm15wrp2",
      "cm15wrp3",
      "cm15wrp4",
      "cm15wrp5",
      "cm15wrpx",
      "cm15wt",
      "cm15wt1nd",
      "cm15wt1no",
      "cm15wt2nd",
      "cm15wt2no",
      "cm15wt3nd",
      "cm15wt3no",
      "cm15wth",
      "cm15wtm",
      "cm15wtp0",
      "cm15wtpx",
      "cm15wtr",
      "cm15wtrm",
      "cm15wtrnd",
      "cm15wtrno",
      "cmrecalc",
      "cmrecali",
      "cmwtdr",
      "dm15wrp0",
      "dm15wrp1",
      "dm15wrp2",
      "dm15wrp3",
      "dm15wrp4",
      "dm15wrp5",
      "dm15wrpx",
      "dm15wrth",
      "dm15wrtm",
      "dm15wt",
      "dm15wt1nd",
      "dm15wt1no",
      "dm15wt2nd",
      "dm15wt2no",
      "dm15wt3nd",
      "dm15wt3no",
      "dm15wtdr",
      "dm15wth",
      "dm15wtm",
      "dm15wtp0",
      "dm15wtp1",
      "dm15wtp2",
      "dm15wtp3",
      "dm15wtp4",
      "dm15wtp5",
      "dm15wtpx",
      "dm15wtr",
      "dm15wtrnd",
      "dm15wtrno",
      "dmrecali",
      "dmwtt1",
      "dmwtt2",
      "dmwtt3",
      "em15wrp0",
      "em15wrp1",
      "em15wrp2",
      "em15wrp3",
      "em15wrp4",
      "em15wrp5",
      "em15wrpx",
      "em15wrth",
      "em15wrtm",
      "em15wt",
      "em15wt1nd",
      "em15wt1no",
      "em15wt2nd",
      "em15wt2no",
      "em15wt3nd",
      "em15wt3no",
      "em15wtdr",
      "em15wth",
      "em15wtm",
      "em15wtp0",
      "em15wtp1",
      "em15wtp2",
      "em15wtp3",
      "em15wtp4",
      "em15wtp5",
      "em15wtpx",
      "em15wtr",
      "em15wtrnd",
      "em15wtrno",
      "emrecali",
      "emwtt1",
      "emwtt2",
      "emwtt3",
      "fm15wrp0",
      "fm15wrp1",
      "fm15wrp2",
      "fm15wrp3",
      "fm15wrp4",
      "fm15wrp5",
      "fm15wrpx",
      "fm15wrth",
      "fm15wrtm",
      "fm15wt",
      "fm15wt1nd",
      "fm15wt1no",
      "fm15wt2nd",
      "fm15wt2no",
      "fm15wt3nd",
      "fm15wt3no",
      "fm15wtdr",
      "fm15wth",
      "fm15wtm",
      "fm15wtp0",
      "fm15wtp1",
      "fm15wtp2",
      "fm15wtp3",
      "fm15wtp4",
      "fm15wtp5",
      "fm15wtpx",
      "fm15wtr",
      "fm15wtrnd",
      "fm15wtrno",
      "fmrecali",
      "fmrm15wt",
      "fmwtt1",
      "fmwtt2",
      "fmwtt3",
      "gm15wrp0",
      "gm15wrp1",
      "gm15wrp2",
      "gm15wrp3",
      "gm15wrp4",
      "gm15wrp5",
      "gm15wrpx",
      "gm15wrth",
      "gm15wrtm",
      "gm15wt",
      "gm15wt1nd",
      "gm15wt1no",
      "gm15wt2nd",
      "gm15wt2no",
      "gm15wt3nd",
      "gm15wt3no",
      "gm15wtdr",
      "gm15wth",
      "gm15wtm",
      "gm15wtp0",
      "gm15wtp1",
      "gm15wtp2",
      "gm15wtp3",
      "gm15wtp4",
      "gm15wtp5",
      "gm15wtpx",
      "gm15wtr",
      "gm15wtrnd",
      "gm15wtrno",
      "gmrecali",
      "gmrm15wt",
      "gmwtt1",
      "gmwtt2",
      "gmwtt3",
      "hm15wrp0",
      "hm15wrp1",
      "hm15wrp2",
      "hm15wrp3",
      "hm15wrp4",
      "hm15wrp5",
      "hm15wrpx",
      "hm15wrt",
      "hm15wrtm",
      "hm15wt",
      "hm15wt1nd",
      "hm15wt1no",
      "hm15wt2nd",
      "hm15wt2no",
      "hm15wt3nd",
      "hm15wt3no",
      "hm15wth",
      "hm15wtp0",
      "hm15wtp1",
      "hm15wtp2",
      "hm15wtp3",
      "hm15wtp4",
      "hm15wtp5",
      "hm15wtpx",
      "hm15wtr",
      "hm15wtrnd",
      "hm15wtrno",
      "hmrecali",
      "hmwtdr",
      "hmwtt1",
      "hmwtt2",
      "hmwtt3",
      "im15wrp0",
      "im15wrp1",
      "im15wrp2",
      "im15wrp3",
      "im15wrp4",
      "im15wrp5",
      "im15wrpx",
      "im15wrt",
      "im15wrtm",
      "im15wt",
      "im15wt1nd",
      "im15wt1no",
      "im15wt2nd",
      "im15wt2no",
      "im15wt3nd",
      "im15wt3no",
      "im15wth",
      "im15wtp0",
      "im15wtp1",
      "im15wtp2",
      "im15wtp3",
      "im15wtp4",
      "im15wtp5",
      "im15wtpx",
      "im15wtr",
      "im15wtrnd",
      "im15wtrno",
      "imrecali",
      "imwtdr",
      "imwtt1",
      "imwtt2",
      "imwtt3",
      "jm15wrp0",
      "jm15wrp1",
      "jm15wrp2",
      "jm15wrp3",
      "jm15wrp4",
      "jm15wrp5",
      "jm15wrpx",
      "jm15wrt",
      "jm15wrtm",
      "jm15wt",
      "jm15wt1nd",
      "jm15wt1no",
      "jm15wt2nd",
      "jm15wt2no",
      "jm15wt3nd",
      "jm15wt3no",
      "jm15wth",
      "jm15wtp0",
      "jm15wtp1",
      "jm15wtp2",
      "jm15wtp3",
      "jm15wtp4",
      "jm15wtp5",
      "jm15wtpx",
      "jm15wtr",
      "jm15wtrnd",
      "jm15wtrno",
      "jmrecali",
      "jmwtdr",
      "jmwtt1",
      "jmwtt2",
      "jmwtt3",
      "km15wrp0",
      "km15wrp1",
      "km15wrp2",
      "km15wrp3",
      "km15wrp4",
      "km15wrp5",
      "km15wrpx",
      "km15wrt",
      "km15wrtm",
      "km15wt",
      "km15wt1nd",
      "km15wt1no",
      "km15wt2nd",
      "km15wt2no",
      "km15wt3nd",
      "km15wt3no",
      "km15wth",
      "km15wtp0",
      "km15wtp1",
      "km15wtp2",
      "km15wtp3",
      "km15wtp4",
      "km15wtp5",
      "km15wtpx",
      "km15wtr",
      "km15wtrnd",
      "km15wtrno",
      "kmrecali",
      "kmwtdr",
      "kmwtt1",
      "kmwtt2",
      "kmwtt3"
    ),
    canonical_name = c(
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wrth",
      "m15wrtm",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wtdr",
      "m15wth",
      "m15wtm",
      "m15wtp0",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wtpx",
      "m15wtr",
      "m15wtrnd",
      "m15wtrno",
      "mrecali",
      "mwtt1",
      "mwtt2",
      "mwtt3",
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wrt",
      "m15wrtm",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wth",
      "m15wtp0",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wtpx",
      "m15wtr",
      "m15wtrnd",
      "m15wtrno",
      "mrecali",
      "mwtdr",
      "mwtt1",
      "mwtt2",
      "mwtt3",
      "m15wrth",
      "m15wt101",
      "m15wt102",
      "m15wt103",
      "m15wt104",
      "m15wt105",
      "m15wt106",
      "m15wt107",
      "m15wt108",
      "m15wt109",
      "m15wt110",
      "m15wt111",
      "m15wt112",
      "m15wt113",
      "m15wt114",
      "m15wt115",
      "m15wt1nd",
      "m15wt1no",
      "m15wt201",
      "m15wt202",
      "m15wt203",
      "m15wt204",
      "m15wt205",
      "m15wt206",
      "m15wt207",
      "m15wt208",
      "m15wt209",
      "m15wt210",
      "m15wt211",
      "m15wt212",
      "m15wt213",
      "m15wt214",
      "m15wt215",
      "m15wt2nd",
      "m15wt2no",
      "m15wt301",
      "m15wt302",
      "m15wt303",
      "m15wt304",
      "m15wt305",
      "m15wt306",
      "m15wt307",
      "m15wt308",
      "m15wt309",
      "m15wt310",
      "m15wt311",
      "m15wt312",
      "m15wt313",
      "m15wt314",
      "m15wt315",
      "m15wt3nd",
      "m15wt3no",
      "m15wth",
      "m15wtm",
      "m15wtr01",
      "m15wtr02",
      "m15wtr03",
      "m15wtr04",
      "m15wtr05",
      "m15wtr06",
      "m15wtr07",
      "m15wtr08",
      "m15wtr09",
      "m15wtr10",
      "m15wtr11",
      "m15wtr12",
      "m15wtr13",
      "m15wtr14",
      "m15wtr15",
      "m15wtrm",
      "m15wtrnd",
      "m15wtrno",
      "mrecal",
      "m15wrth",
      "m15wrtm",
      "m15wdrm",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wth",
      "m15wtm",
      "m15wtp0",
      "m15wtpx",
      "m15wtr",
      "m15wtrm",
      "m15wtrnd",
      "m15wtrno",
      "mrecalc",
      "mrecali",
      "mwtdr",
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wrth",
      "m15wrtm",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wtdr",
      "m15wth",
      "m15wtm",
      "m15wtp0",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wtpx",
      "m15wtr",
      "m15wtrnd",
      "m15wtrno",
      "mrecali",
      "mwtt1",
      "mwtt2",
      "mwtt3",
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wrth",
      "m15wrtm",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wtdr",
      "m15wth",
      "m15wtm",
      "m15wtp0",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wtpx",
      "m15wtr",
      "m15wtrnd",
      "m15wtrno",
      "mrecali",
      "mwtt1",
      "mwtt2",
      "mwtt3",
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wrth",
      "m15wrtm",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wtdr",
      "m15wth",
      "m15wtm",
      "m15wtp0",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wtpx",
      "m15wtr",
      "m15wtrnd",
      "m15wtrno",
      "mrecali",
      "mrm15wt",
      "mwtt1",
      "mwtt2",
      "mwtt3",
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wrth",
      "m15wrtm",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wtdr",
      "m15wth",
      "m15wtm",
      "m15wtp0",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wtpx",
      "m15wtr",
      "m15wtrnd",
      "m15wtrno",
      "mrecali",
      "mrm15wt",
      "mwtt1",
      "mwtt2",
      "mwtt3",
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wrt",
      "m15wrtm",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wth",
      "m15wtp0",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wtpx",
      "m15wtr",
      "m15wtrnd",
      "m15wtrno",
      "mrecali",
      "mwtdr",
      "mwtt1",
      "mwtt2",
      "mwtt3",
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wrt",
      "m15wrtm",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wth",
      "m15wtp0",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wtpx",
      "m15wtr",
      "m15wtrnd",
      "m15wtrno",
      "mrecali",
      "mwtdr",
      "mwtt1",
      "mwtt2",
      "mwtt3",
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wrt",
      "m15wrtm",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wth",
      "m15wtp0",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wtpx",
      "m15wtr",
      "m15wtrnd",
      "m15wtrno",
      "mrecali",
      "mwtdr",
      "mwtt1",
      "mwtt2",
      "mwtt3",
      "m15wrp0",
      "m15wrp1",
      "m15wrp2",
      "m15wrp3",
      "m15wrp4",
      "m15wrp5",
      "m15wrpx",
      "m15wrt",
      "m15wrtm",
      "m15wt",
      "m15wt1nd",
      "m15wt1no",
      "m15wt2nd",
      "m15wt2no",
      "m15wt3nd",
      "m15wt3no",
      "m15wth",
      "m15wtp0",
      "m15wtp1",
      "m15wtp2",
      "m15wtp3",
      "m15wtp4",
      "m15wtp5",
      "m15wtpx",
      "m15wtr",
      "m15wtrnd",
      "m15wtrno",
      "mrecali",
      "mwtdr",
      "mwtt1",
      "mwtt2",
      "mwtt3"
    ),
    variable_label = c(
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other specification",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "number of words correct: recall",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 words recall: interval in minutes",
      "Number of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: visually handicapped",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "Time: by interviewer (before recall)",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time by interviewer (after 3 trials)",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "numbers of words correct: trial 1",
      "number of words correct: trial 2",
      "number of words correct: trial 3",
      "Time: hours",
      "15 words (1): word 1",
      "15 words (1): word 2",
      "15 words (1): word 3",
      "15 words (1): word 4",
      "15 words (1): word 5",
      "15 words (1): word 6",
      "15 words (1): word 7",
      "15 words (1): word 8",
      "15 words (1): word 9",
      "15 words (1): word 10",
      "15 words (1): word 11",
      "15 words (1): word 12",
      "15 words (1): word 13",
      "15 words (1): word 14",
      "15 words (1): word 15",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): word 1",
      "15 words (2): word 2",
      "15 words (2): word 3",
      "15 words (2): word 4",
      "15 words (2): word 5",
      "15 words (2): word 6",
      "15 words (2): word 7",
      "15 words (2): word 8",
      "15 words (2): word 9",
      "15 words (2): word 10",
      "15 words (2): word 11",
      "15 words (2): word 12",
      "15 words (2): word 13",
      "15 words (2): word 14",
      "15 words (2): word 15",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): word 1",
      "15 words (3): word 2",
      "15 words (3): word 3",
      "15 words (3): word 4",
      "15 words (3): word 5",
      "15 words (3): word 6",
      "15 words (3): word 7",
      "15 words (3): word 8",
      "15 words (3): word 9",
      "15 words (3): word 10",
      "15 words (3): word 11",
      "15 words (3): word 12",
      "15 words (3): word 13",
      "15 words (3): word 14",
      "15 words (3): word 15",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time interview: hours",
      "Time interview: minutes",
      "15 words (recall): word 1",
      "15 words (recall): word 2",
      "15 words (recall): word 3",
      "15 words (recall): word 4",
      "15 words (recall): word 5",
      "15 words (recall): word 6",
      "15 words (recall): word 7",
      "15 words (recall): word 8",
      "15 words (recall): word 9",
      "15 words (recall): word 10",
      "15 words (recall): word 11",
      "15 words (recall): word 12",
      "15 words (recall): word 13",
      "15 words (recall): word 14",
      "15 words (recall): word 15",
      "Time: minutes",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 word test time interval in minutes",
      "Recall time: hours by interviewer",
      "Recall time: minutes by interviewer",
      "reason no recall test",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "recall particul: no particularities",
      "recall particul: other present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul other: specification",
      "15 word test done?",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities other: specification",
      "15wt Recall done",
      "15 wt: reason no test(s)",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by computer",
      "15 wt: interval in min. by interviewer",
      "Number of words correct: recall",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other specification",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "number of words correct: recall",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 words recall: interval in minutes",
      "Number of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other specification",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "number of words correct: recall",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 words recall: interval in minutes",
      "Number of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other specification",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "number of words correct: recall",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 words recall: interval in minutes",
      "Reason missing (part of) 15 words test",
      "Number of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other specification",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "number of words correct: recall",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 words recall: interval in minutes",
      "Reason missing (part of) 15 words test",
      "Number of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: visually handicapped",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "Time: by interviewer (before recall)",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time by interviewer (after 3 trials)",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "numbers of words correct: trial 1",
      "number of words correct: trial 2",
      "number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: visually handicapped",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "Time: by interviewer (before recall)",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time by interviewer (after 3 trials)",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "numbers of words correct: trial 1",
      "number of words correct: trial 2",
      "number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: visually handicapped",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "Time: by interviewer (before recall)",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time by interviewer (after 3 trials)",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "numbers of words correct: trial 1",
      "number of words correct: trial 2",
      "number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: visually handicapped",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "Time: by interviewer (before recall)",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time by interviewer (after 3 trials)",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: visually handicapped",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "numbers of words correct: trial 1",
      "number of words correct: trial 2",
      "number of words correct: trial 3"
    ),
    harmonized_var_label = c(
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "number of words correct: recall",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "numbers of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "Time: by interviewer (before recall)",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time: hours by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "numbers of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall time: hours by interviewer",
      "15 words (1): word 1",
      "15 words (1): word 2",
      "15 words (1): word 3",
      "15 words (1): word 4",
      "15 words (1): word 5",
      "15 words (1): word 6",
      "15 words (1): word 7",
      "15 words (1): word 8",
      "15 words (1): word 9",
      "15 words (1): word 10",
      "15 words (1): word 11",
      "15 words (1): word 12",
      "15 words (1): word 13",
      "15 words (1): word 14",
      "15 words (1): word 15",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): word 1",
      "15 words (2): word 2",
      "15 words (2): word 3",
      "15 words (2): word 4",
      "15 words (2): word 5",
      "15 words (2): word 6",
      "15 words (2): word 7",
      "15 words (2): word 8",
      "15 words (2): word 9",
      "15 words (2): word 10",
      "15 words (2): word 11",
      "15 words (2): word 12",
      "15 words (2): word 13",
      "15 words (2): word 14",
      "15 words (2): word 15",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): word 1",
      "15 words (3): word 2",
      "15 words (3): word 3",
      "15 words (3): word 4",
      "15 words (3): word 5",
      "15 words (3): word 6",
      "15 words (3): word 7",
      "15 words (3): word 8",
      "15 words (3): word 9",
      "15 words (3): word 10",
      "15 words (3): word 11",
      "15 words (3): word 12",
      "15 words (3): word 13",
      "15 words (3): word 14",
      "15 words (3): word 15",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "15 words (recall): word 1",
      "15 words (recall): word 2",
      "15 words (recall): word 3",
      "15 words (recall): word 4",
      "15 words (recall): word 5",
      "15 words (recall): word 6",
      "15 words (recall): word 7",
      "15 words (recall): word 8",
      "15 words (recall): word 9",
      "15 words (recall): word 10",
      "15 words (recall): word 11",
      "15 words (recall): word 12",
      "15 words (recall): word 13",
      "15 words (recall): word 14",
      "15 words (recall): word 15",
      "15 wt: reason no test(s)",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 word test time interval in minutes",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "reason no recall test",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities other: specification",
      "15wt recall done",
      "15 wt: reason no test(s)",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by computer",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "number of words correct: recall",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "numbers of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "number of words correct: recall",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "numbers of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "number of words correct: recall",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "Reason missing (part of) 15 words test",
      "numbers of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "recall time: hours by interviewer",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "number of words correct: recall",
      "Time: hours by interviewer",
      "Time: minutes by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "Reason missing (part of) 15 words test",
      "numbers of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "Time: by interviewer (before recall)",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time: hours by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "numbers of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "Time: by interviewer (before recall)",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time: hours by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "numbers of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "Time: by interviewer (before recall)",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time: hours by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "numbers of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3",
      "recall particul: no particularities",
      "recall particul: others present",
      "recall particul: auditory handicap",
      "recall particul: radio or tv noise",
      "recall particul: interrupted",
      "recall particul: other reason",
      "recall particul: other: specification",
      "Time: by interviewer (before recall)",
      "recall time: minutes by interviewer",
      "15 words test done",
      "15 words (1): number of doubles",
      "15 words (1): number of others",
      "15 words (2): number of doubles",
      "15 words (2): number of others",
      "15 words (3): number of doubles",
      "15 words (3): number of others",
      "Time: hours by interviewer",
      "particularities: no particularities",
      "particularities: others present",
      "particularities: auditory handicap",
      "particularities: radio or tv noise",
      "particularities: interrupted",
      "particularities: other reason",
      "particularities other: specification",
      "15wt recall done",
      "15 words (recall): number of doubles",
      "15 words (recall): number of others",
      "15 wt: interval in min. by interviewer",
      "number of words correct: recall",
      "numbers of words correct: trial 1",
      "Number of words correct: trial 2",
      "Number of words correct: trial 3"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "text",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    m15wrp0 = list(
      `2B` = not_mentioned_mentioned_19,
      `3B` = not_mentioned_mentioned_19,
      C = not_mentioned_mentioned_217,
      D = not_mentioned_mentioned_19,
      E = not_mentioned_mentioned_19,
      F = not_mentioned_mentioned_19,
      G = not_mentioned_mentioned_19,
      H = not_mentioned_mentioned_19,
      I = not_mentioned_mentioned_19,
      J = not_mentioned_mentioned_19,
      K = not_mentioned_mentioned_19
    ),
    m15wrp1 = list(
      `2B` = not_mentioned_mentioned_231,
      `3B` = not_mentioned_mentioned_232,
      C = not_mentioned_mentioned_217,
      D = not_mentioned_mentioned_231,
      E = not_mentioned_mentioned_231,
      F = not_mentioned_mentioned_231,
      G = not_mentioned_mentioned_231,
      H = not_mentioned_mentioned_232,
      I = not_mentioned_mentioned_232,
      J = not_mentioned_mentioned_232,
      K = not_mentioned_mentioned_232
    ),
    m15wrp2 = list(
      `2B` = not_mentioned_mentioned_19,
      `3B` = not_mentioned_mentioned_19,
      C = not_mentioned_mentioned_217,
      D = not_mentioned_mentioned_19,
      E = not_mentioned_mentioned_19,
      F = not_mentioned_mentioned_19,
      G = not_mentioned_mentioned_19,
      H = not_mentioned_mentioned_19,
      I = not_mentioned_mentioned_19,
      J = not_mentioned_mentioned_19,
      K = not_mentioned_mentioned_19
    ),
    m15wrp3 = list(
      `2B` = not_mentioned_mentioned_19,
      `3B` = not_mentioned_mentioned_19,
      C = not_mentioned_mentioned_217,
      D = not_mentioned_mentioned_19,
      E = not_mentioned_mentioned_19,
      F = not_mentioned_mentioned_19,
      G = not_mentioned_mentioned_19,
      H = not_mentioned_mentioned_19,
      I = not_mentioned_mentioned_19,
      J = not_mentioned_mentioned_19,
      K = not_mentioned_mentioned_19
    ),
    m15wrp4 = list(
      `2B` = not_mentioned_mentioned_19,
      `3B` = not_mentioned_mentioned_19,
      C = not_mentioned_mentioned_217,
      D = not_mentioned_mentioned_19,
      E = not_mentioned_mentioned_19,
      F = not_mentioned_mentioned_19,
      G = not_mentioned_mentioned_19,
      H = not_mentioned_mentioned_19,
      I = not_mentioned_mentioned_19,
      J = not_mentioned_mentioned_19,
      K = not_mentioned_mentioned_19
    ),
    m15wrp5 = list(
      `2B` = not_mentioned_mentioned_19,
      `3B` = not_mentioned_mentioned_19,
      C = not_mentioned_mentioned_217,
      D = not_mentioned_mentioned_19,
      E = not_mentioned_mentioned_19,
      F = not_mentioned_mentioned_19,
      G = not_mentioned_mentioned_19,
      H = not_mentioned_mentioned_19,
      I = not_mentioned_mentioned_19,
      J = not_mentioned_mentioned_19,
      K = not_mentioned_mentioned_19
    ),
    m15wrpx = list(
      `2B` = to_be_coded_extra_instructions_other_disturbing_factors,
      `3B` = to_be_coded_extra_instructions_other_disturbing_factors_2,
      C = c(
        `-4` = "interview terminated",
        `-3` = "no test",
        `-2` = "no particularities",
        `-1` = "no other reason",
        `0` = "to be coded",
        `1` = "extra instructions",
        `2` = "other disturbing factors",
        `3` = "R confused/not fit"
      ),
      D = to_be_coded_extra_instructions_other_disturbing_factors,
      E = to_be_coded_extra_instructions_other_disturbing_factors,
      F = to_be_coded_extra_instructions_other_disturbing_factors,
      G = to_be_coded_extra_instructions_other_disturbing_factors,
      H = to_be_coded_extra_instructions_other_disturbing_factors_2,
      I = to_be_coded_extra_instructions_other_disturbing_factors_2,
      J = to_be_coded_extra_instructions_other_disturbing_factors_2,
      K = to_be_coded_extra_instructions_other_disturbing_factors_2
    ),
    m15wrth = list(
      `2B` = no_test_no_valid_time_data,
      D = no_test_no_valid_time_data,
      E = no_test_no_valid_time_data,
      F = no_test_no_valid_time_data,
      G = no_test_no_valid_time_data
    ),
    m15wrtm = list(
      `2B` = no_recall_test,
      `3B` = no_recall_test_no_answer_asked,
      D = no_recall_test,
      E = no_recall_test,
      F = no_recall_test,
      G = no_recall_test,
      H = no_recall_test_no_answer_asked,
      I = no_recall_test_no_answer_asked,
      J = no_recall_test_no_answer_asked,
      K = no_recall_test_no_answer_asked
    ),
    m15wt = list(
      `2B` = vs_15_wt_not_done_15_wt_done,
      `3B` = vs_15_wt_not_done_15_wt_done,
      C = vs_15_wt_not_done_15_wt_done_2,
      D = vs_15_wt_not_done_15_wt_done,
      E = vs_15_wt_not_done_15_wt_done,
      F = vs_15_wt_not_done_15_wt_done,
      G = vs_15_wt_not_done_15_wt_done,
      H = vs_15_wt_not_done_15_wt_done,
      I = vs_15_wt_not_done_15_wt_done,
      J = vs_15_wt_not_done_15_wt_done,
      K = vs_15_wt_not_done_15_wt_done
    ),
    m15wtdr = list(
      `2B` = no_answer_asked,
      D = no_answer_asked,
      E = no_answer_asked,
      F = no_answer_asked,
      G = no_answer_asked
    ),
    m15wth = list(
      `2B` = no_test,
      `3B` = no_test_no_valid_time_data,
      B = no_valid_data_2,
      D = no_test,
      E = no_test,
      F = no_test,
      G = no_test,
      H = no_test_no_valid_time_data,
      I = no_test_no_valid_time_data,
      J = no_test_no_valid_time_data,
      K = no_test_no_valid_time_data
    ),
    m15wtm = list(
      `2B` = no_answer_asked,
      D = no_answer_asked,
      E = no_answer_asked,
      F = no_answer_asked,
      G = no_answer_asked
    ),
    m15wtp0 = list(
      `2B` = not_mentioned_mentioned_15,
      `3B` = not_mentioned_mentioned_15,
      C = c(
        `-4` = "interview terminated",
        `-3` = "no test",
        `-2` = "no particularities",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      D = not_mentioned_mentioned_15,
      E = not_mentioned_mentioned_15,
      F = not_mentioned_mentioned_15,
      G = not_mentioned_mentioned_15,
      H = not_mentioned_mentioned_15,
      I = not_mentioned_mentioned_15,
      J = not_mentioned_mentioned_15,
      K = not_mentioned_mentioned_15
    ),
    m15wtp1 = list(
      `2B` = not_mentioned_mentioned_218,
      `3B` = not_mentioned_mentioned_233,
      D = not_mentioned_mentioned_218,
      E = not_mentioned_mentioned_218,
      F = not_mentioned_mentioned_218,
      G = not_mentioned_mentioned_218,
      H = not_mentioned_mentioned_233,
      I = not_mentioned_mentioned_233,
      J = not_mentioned_mentioned_233,
      K = not_mentioned_mentioned_233
    ),
    m15wtp2 = list(
      `2B` = not_mentioned_mentioned_15,
      `3B` = not_mentioned_mentioned_15,
      D = not_mentioned_mentioned_15,
      E = not_mentioned_mentioned_15,
      F = not_mentioned_mentioned_15,
      G = not_mentioned_mentioned_15,
      H = not_mentioned_mentioned_15,
      I = not_mentioned_mentioned_15,
      J = not_mentioned_mentioned_15,
      K = not_mentioned_mentioned_15
    ),
    m15wtp3 = list(
      `2B` = not_mentioned_mentioned_15,
      `3B` = not_mentioned_mentioned_15,
      D = not_mentioned_mentioned_15,
      E = not_mentioned_mentioned_15,
      F = not_mentioned_mentioned_15,
      G = not_mentioned_mentioned_15,
      H = not_mentioned_mentioned_15,
      I = not_mentioned_mentioned_15,
      J = not_mentioned_mentioned_15,
      K = not_mentioned_mentioned_15
    ),
    m15wtp4 = list(
      `2B` = not_mentioned_mentioned_15,
      `3B` = not_mentioned_mentioned_15,
      D = not_mentioned_mentioned_15,
      E = not_mentioned_mentioned_15,
      F = not_mentioned_mentioned_15,
      G = not_mentioned_mentioned_15,
      H = not_mentioned_mentioned_15,
      I = not_mentioned_mentioned_15,
      J = not_mentioned_mentioned_15,
      K = not_mentioned_mentioned_15
    ),
    m15wtp5 = list(
      `2B` = not_mentioned_mentioned_15,
      `3B` = not_mentioned_mentioned_15,
      D = not_mentioned_mentioned_15,
      E = not_mentioned_mentioned_15,
      F = not_mentioned_mentioned_15,
      G = not_mentioned_mentioned_15,
      H = not_mentioned_mentioned_15,
      I = not_mentioned_mentioned_15,
      J = not_mentioned_mentioned_15,
      K = not_mentioned_mentioned_15
    ),
    m15wtpx = list(
      `2B` = to_be_coded_extra_instructions_other_disturbing_factors_3,
      `3B` = to_be_coded_extra_instructions_other_disturbing_factors_4,
      C = c(
        `-4` = "interview terminated",
        `-3` = "no test",
        `-2` = "no particularities",
        `-1` = "no other reason",
        `0` = "to be coded",
        `1` = "extra instructions",
        `2` = "other disturbing factors",
        `3` = "R confused/not fit",
        `4` = "stopped/technical",
        `5` = "not specified"
      ),
      D = to_be_coded_extra_instructions_other_disturbing_factors_3,
      E = to_be_coded_extra_instructions_other_disturbing_factors_3,
      F = to_be_coded_extra_instructions_other_disturbing_factors_3,
      G = to_be_coded_extra_instructions_other_disturbing_factors_3,
      H = to_be_coded_extra_instructions_other_disturbing_factors_4,
      I = to_be_coded_extra_instructions_other_disturbing_factors_4,
      J = to_be_coded_extra_instructions_other_disturbing_factors_4,
      K = to_be_coded_extra_instructions_other_disturbing_factors_4
    ),
    m15wtr = list(
      `2B` = recall_test_not_done_recall_test_done,
      `3B` = recall_test_not_done_recall_test_done,
      C = c(`-4` = "interview terminated", `1` = "yes", `2` = "no"),
      D = recall_test_not_done_recall_test_done,
      E = recall_test_not_done_recall_test_done,
      F = recall_test_not_done_recall_test_done,
      G = recall_test_not_done_recall_test_done,
      H = recall_test_not_done_recall_test_done,
      I = recall_test_not_done_recall_test_done,
      J = recall_test_not_done_recall_test_done,
      K = recall_test_not_done_recall_test_done
    ),
    mrecali = list(
      `2B` = recall_test_not_done_no_valid_time_data,
      `3B` = recall_test_not_done_no_valid_time_data,
      C = no_valid_time_data,
      D = recall_test_not_done_no_valid_time_data,
      E = recall_test_not_done_no_valid_time_data,
      F = recall_test_not_done_no_valid_time_data,
      G = recall_test_not_done_no_valid_time_data,
      H = recall_test_not_done_no_valid_time_data,
      I = recall_test_not_done_no_valid_time_data,
      J = recall_test_not_done_no_valid_time_data,
      K = recall_test_not_done_no_valid_time_data
    ),
    m15wrt = list(
      `3B` = no_test_no_valid_time_data,
      H = no_test_no_valid_time_data,
      I = no_test_no_valid_time_data,
      J = no_test_no_valid_time_data,
      K = no_test_no_valid_time_data
    ),
    m15wt1no = list(
      `3B` = no_answer_asked,
      C = interview_terminated_2,
      H = no_answer_asked,
      I = no_answer_asked,
      J = no_answer_asked,
      K = no_answer_asked
    ),
    m15wtrno = list(
      `3B` = no_recall_test_h_b_1_no_answer_asked_i_j_km15wtrnd_15_words_recall_number_of_doubles,
      B = no_valid_data_2,
      C = c(`-1` = "no recall test"),
      H = no_recall_test_h_b_1_no_answer_asked_i_j_km15wtrnd_15_words_recall_number_of_doubles,
      I = no_recall_test_h_b_1_no_answer_asked_i_j_km15wtrnd_15_words_recall_number_of_doubles,
      J = no_recall_test_h_b_1_no_answer_asked_i_j_km15wtrnd_15_words_recall_number_of_doubles,
      K = no_recall_test_h_b_1_no_answer_asked_i_j_km15wtrnd_15_words_recall_number_of_doubles
    ),
    mwtdr = list(
      `3B` = no_recall_test,
      C = interview_terminated_2,
      H = no_recall_test,
      I = no_recall_test,
      J = no_recall_test,
      K = no_recall_test
    ),
    mwtt1 = list(
      `3B` = no_test,
      H = no_test,
      I = no_test,
      J = no_test,
      K = no_test
    ),
    mwtt2 = list(
      `3B` = no_test,
      H = no_test,
      I = no_test,
      J = no_test,
      K = no_test
    ),
    mwtt3 = list(
      `3B` = no_test,
      H = no_test,
      I = no_test,
      J = no_test,
      K = no_test
    ),
    m15wt101 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt102 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt103 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt104 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt105 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt106 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt107 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt108 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt109 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt110 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt111 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt112 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt113 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt114 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt115 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt201 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt202 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt203 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt204 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt205 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt206 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt207 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt208 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt209 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt210 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt211 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt212 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt213 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt214 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt215 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt301 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt302 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt303 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt304 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt305 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt306 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt307 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt308 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt309 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt310 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt311 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt312 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt313 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt314 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wt315 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr01 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr02 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr03 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr04 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr05 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr06 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr07 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr08 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr09 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr10 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr11 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr12 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr13 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr14 = list(
      B = not_mentioned_mentioned_2
    ),
    m15wtr15 = list(
      B = not_mentioned_mentioned_2
    ),
    mrecal = list(
      B = no_valid_time_data
    ),
    m15wdrm = list(
      C = recall_done_see_cm15wtrm_refused
    ),
    m15wt1nd = list(
      C = no_test_2
    ),
    m15wtrm = list(
      C = test_partially_done_skipped_refused_cognitive_physical
    ),
    mrecalc = list(
      C = no_valid_time_data
    ),
    mrm15wt = list(
      F = to_be_coded_short_version_interview_terminated_2,
      G = to_be_coded_short_version_interview_terminated_2
    )
  ),

  value_labels_harmonized = list(
    m15wdrm = recall_done_see_cm15wtrm_refused,
    m15wrp0 = not_mentioned_mentioned_234,
    m15wrp1 = c(
      `-4` = "interview terminated",
      `-3` = "no recall test",
      `-2` = "no particularities / na, see d/e/b/f/gm15wrp0",
      `-1` = "no other reason",
      `0` = "not mentioned",
      `1` = "mentioned"
    ),
    m15wrp2 = not_mentioned_mentioned_234,
    m15wrp3 = not_mentioned_mentioned_234,
    m15wrp4 = not_mentioned_mentioned_234,
    m15wrp5 = not_mentioned_mentioned_234,
    m15wrpx = c(
      `-4` = "interview terminated",
      `-3` = "no test",
      `-2` = "no particularities / na, see d/e/b/f/gm15wrp0",
      `-1` = "no other reason",
      `0` = "to be coded",
      `1` = "extra instructions",
      `2` = "other disturbing factors",
      `3` = "R confused/not fit",
      `4` = "stopped/technical",
      `5` = "not specified"
    ),
    m15wrt = no_test_no_valid_time_data,
    m15wrth = no_test_no_valid_time_data,
    m15wrtm = no_recall_test_no_answer_asked,
    m15wt = vs_15_wt_not_done_15_wt_done_2,
    m15wt101 = not_mentioned_mentioned_2,
    m15wt102 = not_mentioned_mentioned_2,
    m15wt103 = not_mentioned_mentioned_2,
    m15wt104 = not_mentioned_mentioned_2,
    m15wt105 = not_mentioned_mentioned_2,
    m15wt106 = not_mentioned_mentioned_2,
    m15wt107 = not_mentioned_mentioned_2,
    m15wt108 = not_mentioned_mentioned_2,
    m15wt109 = not_mentioned_mentioned_2,
    m15wt110 = not_mentioned_mentioned_2,
    m15wt111 = not_mentioned_mentioned_2,
    m15wt112 = not_mentioned_mentioned_2,
    m15wt113 = not_mentioned_mentioned_2,
    m15wt114 = not_mentioned_mentioned_2,
    m15wt115 = not_mentioned_mentioned_2,
    m15wt1nd = no_test_2,
    m15wt1no = c(`-4` = "interview terminated", `-1` = "no answer, asked"),
    m15wt201 = not_mentioned_mentioned_2,
    m15wt202 = not_mentioned_mentioned_2,
    m15wt203 = not_mentioned_mentioned_2,
    m15wt204 = not_mentioned_mentioned_2,
    m15wt205 = not_mentioned_mentioned_2,
    m15wt206 = not_mentioned_mentioned_2,
    m15wt207 = not_mentioned_mentioned_2,
    m15wt208 = not_mentioned_mentioned_2,
    m15wt209 = not_mentioned_mentioned_2,
    m15wt210 = not_mentioned_mentioned_2,
    m15wt211 = not_mentioned_mentioned_2,
    m15wt212 = not_mentioned_mentioned_2,
    m15wt213 = not_mentioned_mentioned_2,
    m15wt214 = not_mentioned_mentioned_2,
    m15wt215 = not_mentioned_mentioned_2,
    m15wt301 = not_mentioned_mentioned_2,
    m15wt302 = not_mentioned_mentioned_2,
    m15wt303 = not_mentioned_mentioned_2,
    m15wt304 = not_mentioned_mentioned_2,
    m15wt305 = not_mentioned_mentioned_2,
    m15wt306 = not_mentioned_mentioned_2,
    m15wt307 = not_mentioned_mentioned_2,
    m15wt308 = not_mentioned_mentioned_2,
    m15wt309 = not_mentioned_mentioned_2,
    m15wt310 = not_mentioned_mentioned_2,
    m15wt311 = not_mentioned_mentioned_2,
    m15wt312 = not_mentioned_mentioned_2,
    m15wt313 = not_mentioned_mentioned_2,
    m15wt314 = not_mentioned_mentioned_2,
    m15wt315 = not_mentioned_mentioned_2,
    m15wtdr = no_answer_asked,
    m15wth = c(`-2` = "no test", `-1` = "no valid data / no valid time data"),
    m15wtm = no_answer_asked,
    m15wtp0 = c(
      `-4` = "interview terminated",
      `-3` = "no test",
      `-2` = "no particularities / no test",
      `0` = "not mentioned",
      `1` = "mentioned"
    ),
    m15wtp1 = not_mentioned_mentioned_218,
    m15wtp2 = not_mentioned_mentioned_15,
    m15wtp3 = not_mentioned_mentioned_15,
    m15wtp4 = not_mentioned_mentioned_15,
    m15wtp5 = not_mentioned_mentioned_15,
    m15wtpx = c(
      `-4` = "interview terminated",
      `-3` = "no test",
      `-2` = "no particularities / na, see d/e/b/f/gm15wtp5",
      `-1` = "no other reason",
      `0` = "to be coded",
      `1` = "extra instructions",
      `2` = "other disturbing factors",
      `3` = "R confused/not fit",
      `4` = "stopped/technical",
      `5` = "not specified"
    ),
    m15wtr = c(
      `-4` = "interview terminated",
      `1` = "yes / recall test not done",
      `2` = "no / recall test done"
    ),
    m15wtr01 = not_mentioned_mentioned_2,
    m15wtr02 = not_mentioned_mentioned_2,
    m15wtr03 = not_mentioned_mentioned_2,
    m15wtr04 = not_mentioned_mentioned_2,
    m15wtr05 = not_mentioned_mentioned_2,
    m15wtr06 = not_mentioned_mentioned_2,
    m15wtr07 = not_mentioned_mentioned_2,
    m15wtr08 = not_mentioned_mentioned_2,
    m15wtr09 = not_mentioned_mentioned_2,
    m15wtr10 = not_mentioned_mentioned_2,
    m15wtr11 = not_mentioned_mentioned_2,
    m15wtr12 = not_mentioned_mentioned_2,
    m15wtr13 = not_mentioned_mentioned_2,
    m15wtr14 = not_mentioned_mentioned_2,
    m15wtr15 = not_mentioned_mentioned_2,
    m15wtrm = test_partially_done_skipped_refused_cognitive_physical,
    m15wtrno = c(
      `-2` = "no recall test h/b/ -1: no answer, asked i/j/km15wtrnd 15 words (recall): number of doubles",
      `-1` = "no valid data / no recall test"
    ),
    mrecal = no_valid_time_data,
    mrecalc = no_valid_time_data,
    mrecali = recall_test_not_done_no_valid_time_data,
    mrm15wt = to_be_coded_short_version_interview_terminated_2,
    mwtdr = c(`-4` = "interview terminated", `-2` = "no recall test"),
    mwtt1 = no_test,
    mwtt2 = no_test,
    mwtt3 = no_test
  )
)
