## LASA filecode 165 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_165 <- list(
  variables = data.frame(
    wave = c(
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bmAcor",
      "bmAdub",
      "bmAnot",
      "bmAoth",
      "bmApa_0",
      "bmApa_1",
      "bmApa_2",
      "bmApa_3",
      "bmApa_4",
      "bmApa_5",
      "bmDWcor",
      "bmDWdub",
      "bmDWnot",
      "bmDWoth",
      "bmDWpa_0",
      "bmDWpa_1",
      "bmDWpa_2",
      "bmDWpa_3",
      "bmDWpa_4",
      "bmDWpa_5",
      "hmAcor",
      "hmAdub",
      "hmAnot",
      "hmAoth",
      "hmApa_0",
      "hmApa_1",
      "hmApa_2",
      "hmApa_3",
      "hmApa_4",
      "hmApa_5",
      "hmDWcor",
      "hmDWdub",
      "hmDWnot",
      "hmDWoth",
      "hmDWpa_0",
      "hmDWpa_1",
      "hmDWpa_2",
      "hmDWpa_3",
      "hmDWpa_4",
      "hmDWpa_5",
      "imAcor",
      "imAdub",
      "imAnot",
      "imAoth",
      "imApa_0",
      "imApa_1",
      "imApa_2",
      "imApa_3",
      "imApa_4",
      "imApa_5",
      "imApa_5sp",
      "imArm",
      "imDWcor",
      "imDWdub",
      "imDWnot",
      "imDWoth",
      "imDWpa_0",
      "imDWpa_1",
      "imDWpa_2",
      "imDWpa_3",
      "imDWpa_4",
      "imDWpa_5",
      "imDWpa_5sp",
      "imDWrem",
      "jmAcor",
      "jmAdub",
      "jmAnot",
      "jmAoth",
      "jmApa_0",
      "jmApa_1",
      "jmApa_2",
      "jmApa_3",
      "jmApa_4",
      "jmApa_5",
      "jmDWcor",
      "jmDWdub",
      "jmDWnot",
      "jmDWoth",
      "jmDWpa_0",
      "jmDWpa_1",
      "jmDWpa_2",
      "jmDWpa_3",
      "jmDWpa_4",
      "jmDWpa_5",
      "kmAcor",
      "kmAdub",
      "kmAnot",
      "kmAoth",
      "kmApa_0",
      "kmApa_1",
      "kmApa_2",
      "kmApa_3",
      "kmApa_4",
      "kmApa_5",
      "kmDWcor",
      "kmDWdub",
      "kmDWnot",
      "kmDWoth",
      "kmDWpa_0",
      "kmDWpa_1",
      "kmDWpa_2",
      "kmDWpa_3",
      "kmDWpa_4",
      "kmDWpa_5",
      "bAcor",
      "bAdub",
      "bAnot",
      "bAoth",
      "bArm",
      "bSWcor",
      "bSWdub",
      "bSWnot",
      "bSWoth",
      "bSWpa_0",
      "bSWpa_1",
      "bSWpa_2",
      "bSWpa_3",
      "bSWpa_4",
      "bSWpa_5",
      "bSWpa_5sp",
      "bSWrm"
    ),
    canonical_name = c(
      "mAcor",
      "mAdub",
      "mAnot",
      "mAoth",
      "mApa_0",
      "mApa_1",
      "mApa_2",
      "mApa_3",
      "mApa_4",
      "mApa_5",
      "mDWcor",
      "mDWdub",
      "mDWnot",
      "mDWoth",
      "mDWpa_0",
      "mDWpa_1",
      "mDWpa_2",
      "mDWpa_3",
      "mDWpa_4",
      "mDWpa_5",
      "mAcor",
      "mAdub",
      "mAnot",
      "mAoth",
      "mApa_0",
      "mApa_1",
      "mApa_2",
      "mApa_3",
      "mApa_4",
      "mApa_5",
      "mDWcor",
      "mDWdub",
      "mDWnot",
      "mDWoth",
      "mDWpa_0",
      "mDWpa_1",
      "mDWpa_2",
      "mDWpa_3",
      "mDWpa_4",
      "mDWpa_5",
      "mAcor",
      "mAdub",
      "mAnot",
      "mAoth",
      "mApa_0",
      "mApa_1",
      "mApa_2",
      "mApa_3",
      "mApa_4",
      "mApa_5",
      "mApa_5sp",
      "mArm",
      "mDWcor",
      "mDWdub",
      "mDWnot",
      "mDWoth",
      "mDWpa_0",
      "mDWpa_1",
      "mDWpa_2",
      "mDWpa_3",
      "mDWpa_4",
      "mDWpa_5",
      "mDWpa_5sp",
      "mDWrem",
      "mAcor",
      "mAdub",
      "mAnot",
      "mAoth",
      "mApa_0",
      "mApa_1",
      "mApa_2",
      "mApa_3",
      "mApa_4",
      "mApa_5",
      "mDWcor",
      "mDWdub",
      "mDWnot",
      "mDWoth",
      "mDWpa_0",
      "mDWpa_1",
      "mDWpa_2",
      "mDWpa_3",
      "mDWpa_4",
      "mDWpa_5",
      "mAcor",
      "mAdub",
      "mAnot",
      "mAoth",
      "mApa_0",
      "mApa_1",
      "mApa_2",
      "mApa_3",
      "mApa_4",
      "mApa_5",
      "mDWcor",
      "mDWdub",
      "mDWnot",
      "mDWoth",
      "mDWpa_0",
      "mDWpa_1",
      "mDWpa_2",
      "mDWpa_3",
      "mDWpa_4",
      "mDWpa_5",
      "Acor",
      "Adub",
      "Anot",
      "Aoth",
      "Arm",
      "SWcor",
      "SWdub",
      "SWnot",
      "SWoth",
      "SWpa_0",
      "SWpa_1",
      "SWpa_2",
      "SWpa_3",
      "SWpa_4",
      "SWpa_5",
      "SWpa_5sp",
      "SWrm"
    ),
    variable_label = c(
      "number of animals correct",
      "number of animals double",
      "fluency animals done?",
      "number of other Animals",
      "Animals particularities",
      "Animals particularities: others present",
      "Animals particularities: visually handicapped",
      "Animals particularities: radio or tv noise",
      "Animals particularities: interrupted",
      "Animals particularities: other reason",
      "number of D-words correct",
      "number of D-words double",
      "fluency D-words done?",
      "number of other than D-words",
      "D-words particularities",
      "D-words particularities: others present",
      "D-words particularities: visually handicapped",
      "D-words particularities: radio or tv noise",
      "D-words particularities: interrupted",
      "D-words particularities: other reason",
      "number of animals correct",
      "number of animals double",
      "fluency animals done?",
      "number of other Animals",
      "Animals particularities",
      "Animals particularities: others present",
      "Animals particularities: auditory handicap",
      "Animals particularities: radio or tv noise",
      "Animals particularities: interrupted",
      "Animals particularities: other reason",
      "number of D-words correct",
      "number of D-words double",
      "fluency D-words done?",
      "number of other than D-words",
      "D-words particularities",
      "D-words particularities: others present",
      "D-words particularities: auditory handicap",
      "D-words particularities: radio or tv noise",
      "D-words particularities: interrupted",
      "D-words particularities: other reason",
      "number of animals correct",
      "number of animals double",
      "fluency animals done?",
      "number of other Animals",
      "Animals particularities",
      "Animals particularities: others present",
      "Animals particularities: auditory handicap",
      "Animals particularities: radio or tv noise",
      "Animals particularities: interrupted",
      "Animals particularities: other reason",
      "Animals particularities: other reason specification",
      "fluency: reason no Animals trial",
      "number of D-words correct",
      "number of D-words double",
      "fluency D-words done?",
      "number of other than D-words",
      "D-words particularities",
      "D-words particularities: others present",
      "D-words particularities: auditory handicap",
      "D-words particularities: radio or tv noise",
      "D-words particularities: interrupted",
      "D-words particularities: other reason",
      "D-words particularities: other reason specification",
      "fluency: reason no D-words trial",
      "number of animals correct",
      "number of animals double",
      "fluency animals done?",
      "number of other Animals",
      "Animals particularities",
      "Animals particularities: others present",
      "Animals particularities: auditory handicap",
      "Animals particularities: radio or tv noise",
      "Animals particularities: interrupted",
      "Animals particularities: other reason",
      "number of D-words correct",
      "number of D-words double",
      "fluency D-words done?",
      "number of other than D-words",
      "D-words particularities",
      "D-words particularities: others present",
      "D-words particularities: auditory handicap",
      "D-words particularities: radio or tv noise",
      "D-words particularities: interrupted",
      "D-words particularities: other reason",
      "number of animals correct",
      "number of animals double",
      "fluency animals done?",
      "number of other Animals",
      "Animals particularities",
      "Animals particularities: others present",
      "Animals particularities: auditory handicap",
      "Animals particularities: radio or tv noise",
      "Animals particularities: interrupted",
      "Animals particularities: other reason",
      "number of D-words correct",
      "number of D-words double",
      "fluency D-words done?",
      "number of other than D-words",
      "D-words particularities",
      "D-words particularities: others present",
      "D-words particularities: auditory handicap",
      "D-words particularities: radio or tv noise",
      "D-words particularities: interrupted",
      "D-words particularities: other reason",
      "number of Animals correct",
      "number of Animals double",
      "fluency Animals done?",
      "number of other Animals",
      "fluency: reason no Animals trial",
      "number of Supermarket-words correct",
      "number of Supermarket-words double",
      "fluency Supermarket-words done?",
      "number of other than Supermarket-words",
      "Supermarket words particularities",
      "Supermarket words part.: others present",
      "Supermarket words part.: auditory handicap",
      "Supermarket words part.: radio or tv noise",
      "Supermarket words part.: interrupted",
      "Supermarket words part.: other reason",
      "specification part.: other reason",
      "fluency: reason no Supermarket-words trial"
    ),
    harmonized_var_label = c(
      "number of animals correct",
      "number of duplicate animal words",
      "animal fluency test status",
      "number of non-animal words",
      "animal test particularities present",
      "animal particularity: others present",
      "animal particularity: sensory handicap",
      "animal particularity: radio or television noise",
      "animal particularity: interrupted",
      "animal particularity: other reason",
      "number of D-words correct",
      "number of duplicate D-words",
      "D-word fluency test status",
      "number of non-D words",
      "D-word test particularities present",
      "D-word particularity: others present",
      "D-word particularity: sensory handicap",
      "D-word particularity: radio or television noise",
      "D-word particularity: interrupted",
      "D-word particularity: other reason",
      "number of animals correct",
      "number of duplicate animal words",
      "animal fluency test status",
      "number of non-animal words",
      "animal test particularities present",
      "animal particularity: others present",
      "animal particularity: sensory handicap",
      "animal particularity: radio or television noise",
      "animal particularity: interrupted",
      "animal particularity: other reason",
      "number of D-words correct",
      "number of duplicate D-words",
      "D-word fluency test status",
      "number of non-D words",
      "D-word test particularities present",
      "D-word particularity: others present",
      "D-word particularity: sensory handicap",
      "D-word particularity: radio or television noise",
      "D-word particularity: interrupted",
      "D-word particularity: other reason",
      "number of animals correct",
      "number of duplicate animal words",
      "animal fluency test status",
      "number of non-animal words",
      "animal test particularities present",
      "animal particularity: others present",
      "animal particularity: sensory handicap",
      "animal particularity: radio or television noise",
      "animal particularity: interrupted",
      "animal particularity: other reason",
      "animal particularity: other reason specification",
      "reason no animal fluency trial",
      "number of D-words correct",
      "number of duplicate D-words",
      "D-word fluency test status",
      "number of non-D words",
      "D-word test particularities present",
      "D-word particularity: others present",
      "D-word particularity: sensory handicap",
      "D-word particularity: radio or television noise",
      "D-word particularity: interrupted",
      "D-word particularity: other reason",
      "D-word particularity: other reason specification",
      "reason no D-word fluency trial",
      "number of animals correct",
      "number of duplicate animal words",
      "animal fluency test status",
      "number of non-animal words",
      "animal test particularities present",
      "animal particularity: others present",
      "animal particularity: sensory handicap",
      "animal particularity: radio or television noise",
      "animal particularity: interrupted",
      "animal particularity: other reason",
      "number of D-words correct",
      "number of duplicate D-words",
      "D-word fluency test status",
      "number of non-D words",
      "D-word test particularities present",
      "D-word particularity: others present",
      "D-word particularity: sensory handicap",
      "D-word particularity: radio or television noise",
      "D-word particularity: interrupted",
      "D-word particularity: other reason",
      "number of animals correct",
      "number of duplicate animal words",
      "animal fluency test status",
      "number of non-animal words",
      "animal test particularities present",
      "animal particularity: others present",
      "animal particularity: sensory handicap",
      "animal particularity: radio or television noise",
      "animal particularity: interrupted",
      "animal particularity: other reason",
      "number of D-words correct",
      "number of duplicate D-words",
      "D-word fluency test status",
      "number of non-D words",
      "D-word test particularities present",
      "D-word particularity: others present",
      "D-word particularity: sensory handicap",
      "D-word particularity: radio or television noise",
      "D-word particularity: interrupted",
      "D-word particularity: other reason",
      "number of animals correct",
      "number of duplicate animal words",
      "animal fluency test status",
      "number of non-animal words",
      "reason no animal fluency trial",
      "number of supermarket words correct",
      "number of duplicate supermarket words",
      "supermarket-word fluency test status",
      "number of non-supermarket words",
      "supermarket-word test particularities present",
      "supermarket-word particularity: others present",
      "supermarket-word particularity: auditory handicap",
      "supermarket-word particularity: radio or television noise",
      "supermarket-word particularity: interrupted",
      "supermarket-word particularity: other reason",
      "supermarket-word particularity: other reason specification",
      "reason no supermarket-word fluency trial"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "text"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mAcor = list(
      `3B` = no_trial,
      H = no_trial,
      I = no_trial,
      J = no_trial,
      K = no_trial
    ),
    mAdub = list(
      `3B` = no_trial,
      H = no_trial,
      I = no_trial,
      J = no_trial,
      K = no_trial
    ),
    mAnot = list(
      `3B` = test_not_done_test_done_test_done_score_0,
      H = test_not_done_test_done_test_done_score_0,
      I = test_not_done_test_done_test_done_score_0,
      J = test_not_done_test_done_test_done_score_0,
      K = test_not_done_test_done_test_done_score_0
    ),
    mAoth = list(
      `3B` = no_trial,
      H = no_trial,
      I = no_trial,
      J = no_trial,
      K = no_trial
    ),
    mApa_0 = list(
      `3B` = no_yes_34,
      H = no_yes_34,
      I = no_yes_34,
      J = no_yes_34,
      K = no_yes_34
    ),
    mApa_1 = list(
      `3B` = not_mentioned_mentioned_13,
      H = not_mentioned_mentioned_13,
      I = not_mentioned_mentioned_13,
      J = not_mentioned_mentioned_13,
      K = not_mentioned_mentioned_13
    ),
    mApa_2 = list(
      `3B` = not_mentioned_mentioned_13,
      H = not_mentioned_mentioned_13,
      I = not_mentioned_mentioned_13,
      J = not_mentioned_mentioned_13,
      K = not_mentioned_mentioned_13
    ),
    mApa_3 = list(
      `3B` = not_mentioned_mentioned_13,
      H = not_mentioned_mentioned_13,
      I = not_mentioned_mentioned_13,
      J = not_mentioned_mentioned_13,
      K = not_mentioned_mentioned_13
    ),
    mApa_4 = list(
      `3B` = not_mentioned_mentioned_13,
      H = not_mentioned_mentioned_13,
      I = not_mentioned_mentioned_13,
      J = not_mentioned_mentioned_13,
      K = not_mentioned_mentioned_13
    ),
    mApa_5 = list(
      `3B` = not_mentioned_mentioned_13,
      H = not_mentioned_mentioned_13,
      I = not_mentioned_mentioned_13,
      J = not_mentioned_mentioned_13,
      K = not_mentioned_mentioned_13
    ),
    mDWcor = list(
      `3B` = no_trial,
      H = no_trial,
      I = no_trial,
      J = no_trial,
      K = no_trial
    ),
    mDWdub = list(
      `3B` = no_trial,
      H = no_trial,
      I = no_trial,
      J = no_trial,
      K = no_trial
    ),
    mDWnot = list(
      `3B` = test_not_done_test_done_test_done_score_0,
      H = test_not_done_test_done_test_done_score_0,
      I = test_not_done_test_done_test_done_score_0,
      J = test_not_done_test_done_test_done_score_0,
      K = test_not_done_test_done_test_done_score_0
    ),
    mDWoth = list(
      `3B` = no_trial,
      H = no_trial,
      I = no_trial,
      J = no_trial,
      K = no_trial
    ),
    mDWpa_0 = list(
      `3B` = no_yes_34,
      H = no_yes_34,
      I = no_yes_34,
      J = no_yes_34,
      K = no_yes_34
    ),
    mDWpa_1 = list(
      `3B` = not_mentioned_mentioned_13,
      H = not_mentioned_mentioned_13,
      I = not_mentioned_mentioned_13,
      J = not_mentioned_mentioned_13,
      K = not_mentioned_mentioned_13
    ),
    mDWpa_2 = list(
      `3B` = not_mentioned_mentioned_13,
      H = not_mentioned_mentioned_13,
      I = not_mentioned_mentioned_13,
      J = not_mentioned_mentioned_13,
      K = not_mentioned_mentioned_13
    ),
    mDWpa_3 = list(
      `3B` = not_mentioned_mentioned_13,
      H = not_mentioned_mentioned_13,
      I = not_mentioned_mentioned_13,
      J = not_mentioned_mentioned_13,
      K = not_mentioned_mentioned_13
    ),
    mDWpa_4 = list(
      `3B` = not_mentioned_mentioned_13,
      H = not_mentioned_mentioned_13,
      I = not_mentioned_mentioned_13,
      J = not_mentioned_mentioned_13,
      K = not_mentioned_mentioned_13
    ),
    mDWpa_5 = list(
      `3B` = not_mentioned_mentioned_13,
      H = not_mentioned_mentioned_13,
      I = not_mentioned_mentioned_13,
      J = not_mentioned_mentioned_13,
      K = not_mentioned_mentioned_13
    ),
    Acor = list(
      MB = no_trial
    ),
    Adub = list(
      MB = no_trial
    ),
    Anot = list(
      MB = test_not_done_test_done_test_done_score_0_2
    ),
    Aoth = list(
      MB = no_trial
    ),
    SWcor = list(
      MB = no_trial
    ),
    SWdub = list(
      MB = no_trial
    ),
    SWnot = list(
      MB = test_not_done_test_done_test_done_score_0_2
    ),
    SWoth = list(
      MB = no_trial
    ),
    SWpa_0 = list(
      MB = no_yes_34
    ),
    SWpa_1 = list(
      MB = not_mentioned_mentioned_13
    ),
    SWpa_2 = list(
      MB = not_mentioned_mentioned_13
    ),
    SWpa_3 = list(
      MB = not_mentioned_mentioned_13
    ),
    SWpa_4 = list(
      MB = not_mentioned_mentioned_13
    ),
    SWpa_5 = list(
      MB = not_mentioned_mentioned_13
    )
  ),

  value_labels_harmonized = list(
    Acor = no_trial,
    Adub = no_trial,
    Anot = test_not_done_test_done_test_done_score_0_2,
    Aoth = no_trial,
    SWcor = no_trial,
    SWdub = no_trial,
    SWnot = test_not_done_test_done_test_done_score_0_2,
    SWoth = no_trial,
    SWpa_0 = no_yes_34,
    SWpa_1 = not_mentioned_mentioned_103,
    SWpa_2 = not_mentioned_mentioned_103,
    SWpa_3 = not_mentioned_mentioned_103,
    SWpa_4 = not_mentioned_mentioned_103,
    SWpa_5 = not_mentioned_mentioned_103,
    mAcor = no_trial,
    mAdub = no_trial,
    mAnot = test_not_done_test_done_test_done_score_0,
    mAoth = no_trial,
    mApa_0 = no_yes_34,
    mApa_1 = not_mentioned_mentioned_103,
    mApa_2 = not_mentioned_mentioned_103,
    mApa_3 = not_mentioned_mentioned_103,
    mApa_4 = not_mentioned_mentioned_103,
    mApa_5 = not_mentioned_mentioned_103,
    mDWcor = no_trial,
    mDWdub = no_trial,
    mDWnot = test_not_done_test_done_test_done_score_0,
    mDWoth = no_trial,
    mDWpa_0 = no_yes_34,
    mDWpa_1 = not_mentioned_mentioned_103,
    mDWpa_2 = not_mentioned_mentioned_103,
    mDWpa_3 = not_mentioned_mentioned_103,
    mDWpa_4 = not_mentioned_mentioned_103,
    mDWpa_5 = not_mentioned_mentioned_103
  )
)
