## LASA filecode 222 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_222 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G"
    ),
    variable_name = c(
      "bmcraven",
      "bravatot",
      "bravbtot",
      "brmcrav",
      "bcraven",
      "bravatot",
      "bravbtot",
      "brmcrav",
      "ccraven",
      "cravatot",
      "cravbtot",
      "crmcrav",
      "dcraven",
      "dravatot",
      "dravbtot",
      "drmcrav",
      "emcraven",
      "emrmcrav",
      "emrvatot",
      "emrvbtot",
      "fmcraven",
      "fmrmcrab",
      "fmrmcrav",
      "fmrvatot",
      "fmrvbtot",
      "gmcraven",
      "gmrmcrab",
      "gmrmcrav",
      "gmrvatot",
      "gmrvbtot"
    ),
    canonical_name = c(
      "craven",
      "ravatot",
      "ravbtot",
      "rmcrav",
      "craven",
      "ravatot",
      "ravbtot",
      "rmcrav",
      "craven",
      "ravatot",
      "ravbtot",
      "rmcrav",
      "craven",
      "ravatot",
      "ravbtot",
      "rmcrav",
      "craven",
      "rmcrav",
      "ravatot",
      "ravbtot",
      "craven",
      "rmcrab",
      "rmcrav",
      "ravatot",
      "ravbtot",
      "craven",
      "rmcrab",
      "rmcrav",
      "ravatot",
      "ravbtot"
    ),
    variable_label = c(
      "Total score coloured raven",
      "Total c. raven score section A",
      "Total c. raven score section B",
      "Reason, no valid data on c. raven",
      "Total score coloured raven",
      "Total c. raven score section A",
      "Total c. raven score section B",
      "Reason, no valid data on c. raven",
      "Total score coloured raven",
      "Total c. raven score section A",
      "Total c. raven score section B",
      "Reason, no valid data on c. raven",
      "Total score coloured raven",
      "Total c. raven score section A",
      "Total c. raven score section B",
      "Reason, no valid data on c. raven",
      "Total score coloured raven",
      "Reason, no valid data on c. raven",
      "Total c. raven score section A",
      "Total c. raven score section B",
      "Total score coloured raven",
      "Reason, no valid data b-section c. raven",
      "Reason, no valid data on c. raven",
      "Total c. raven score section A",
      "Total c. raven score section B",
      "Total score coloured raven",
      "Reason, no valid data b-section c. raven",
      "Reason, no valid data on c. raven",
      "Total c. raven score section A",
      "Total c. raven score section B"
    ),
    harmonized_var_label = c(
      "Total coloured Raven score",
      "Total coloured Raven score, section A",
      "Total coloured Raven score, section B",
      "Reason for missing/invalid coloured Raven score",
      "Total coloured Raven score",
      "Total coloured Raven score, section A",
      "Total coloured Raven score, section B",
      "Reason for missing/invalid coloured Raven score",
      "Total coloured Raven score",
      "Total coloured Raven score, section A",
      "Total coloured Raven score, section B",
      "Reason for missing/invalid coloured Raven score",
      "Total coloured Raven score",
      "Total coloured Raven score, section A",
      "Total coloured Raven score, section B",
      "Reason for missing/invalid coloured Raven score",
      "Total coloured Raven score",
      "Reason for missing/invalid coloured Raven score",
      "Total coloured Raven score, section A",
      "Total coloured Raven score, section B",
      "Total coloured Raven score",
      "Reason for missing/invalid coloured Raven section B score",
      "Reason for missing/invalid coloured Raven score",
      "Total coloured Raven score, section A",
      "Total coloured Raven score, section B",
      "Total coloured Raven score",
      "Reason for missing/invalid coloured Raven section B score",
      "Reason for missing/invalid coloured Raven score",
      "Total coloured Raven score, section A",
      "Total coloured Raven score, section B"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    craven = list(
      `2B` = no_valid_data,
      B = na_see_brmcrav,
      C = no_valid_data,
      D = no_valid_data,
      E = no_valid_data,
      F = no_valid_data,
      G = no_valid_data
    ),
    ravatot = list(
      `2B` = no_valid_data,
      B = na_see_brmcrav,
      C = no_valid_data,
      D = no_valid_data,
      E = no_valid_data,
      F = no_valid_data,
      G = no_valid_data
    ),
    ravbtot = list(
      `2B` = no_valid_data,
      B = na_see_brmcrav,
      C = no_valid_data,
      D = no_valid_data,
      E = no_valid_data,
      F = no_valid_data,
      G = no_valid_data
    ),
    rmcrav = list(
      `2B` = short_version_interview_terminated_too_many_missings_2,
      B = short_version_interview_terminated_too_many_missings_4,
      C = short_version_interview_terminated_too_many_missings_4,
      D = short_version_interview_terminated_too_many_missings_2,
      E = short_version_interview_terminated_too_many_missings_2,
      F = short_version_interview_terminated_too_many_missings_5,
      G = to_be_coded_short_version_interview_terminated_3
    ),
    rmcrab = list(
      F = short_version_interview_terminated_too_many_missings_5,
      G = to_be_coded_short_version_interview_terminated_3
    )
  ),

  value_labels_harmonized = list(
    craven = no_valid_data,
    ravatot = no_valid_data,
    ravbtot = no_valid_data,
    rmcrab = c(
      `-2` = "valid score",
      `-1` = "see FMRMCRAV",
      `0` = "- to be coded -",
      `1` = "short version",
      `2` = "interview terminated",
      `3` = "too many missings",
      `4` = "refused test",
      `5` = "not able to (cognitive)",
      `6` = "not able to (physical)",
      `7` = "technical problems",
      `8` = "unknown"
    ),
    rmcrav = c(
      `-2` = "valid score",
      `-1` = "see FMRMCRAV",
      `0` = "- to be coded -",
      `1` = "short version",
      `2` = "interview terminated",
      `3` = "too many missings",
      `4` = "refused test",
      `5` = "not able to (cognitive)",
      `6` = "not able to complete test (physical)",
      `7` = "technical problems",
      `8` = "unknown"
    )
  )
)
