## LASA filecode 166 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_166 <- list(
  variables = data.frame(
    wave = c(
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "hmDSb01",
      "hmDSb02",
      "hmDSb03",
      "hmDSb04",
      "hmDSb05",
      "hmDSb06",
      "hmDSb07",
      "hmDSbsp",
      "hmDSbw",
      "hmDSf01",
      "hmDSf02",
      "hmDSf03",
      "hmDSf04",
      "hmDSf05",
      "hmDSf06",
      "hmDSf07",
      "hmDSf08",
      "hmDSfsp",
      "hmDSfw",
      "hmDStot",
      "imDSb01",
      "imDSb02",
      "imDSb03",
      "imDSb04",
      "imDSb05",
      "imDSb06",
      "imDSb07",
      "imDSbsp",
      "imDSbw",
      "imDSf01",
      "imDSf02",
      "imDSf03",
      "imDSf04",
      "imDSf05",
      "imDSf06",
      "imDSf07",
      "imDSf08",
      "imDSfsp",
      "imDSfw",
      "imDStot",
      "jmDSb01",
      "jmDSb02",
      "jmDSb03",
      "jmDSb04",
      "jmDSb05",
      "jmDSb06",
      "jmDSb07",
      "jmDSbsp",
      "jmDSbw",
      "jmDSf01",
      "jmDSf02",
      "jmDSf03",
      "jmDSf04",
      "jmDSf05",
      "jmDSf06",
      "jmDSf07",
      "jmDSf08",
      "jmDSfsp",
      "jmDSfw",
      "jmDStot",
      "kmDSb01",
      "kmDSb02",
      "kmDSb03",
      "kmDSb04",
      "kmDSb05",
      "kmDSb06",
      "kmDSb07",
      "kmDSbsp",
      "kmDSbw",
      "kmDSf01",
      "kmDSf02",
      "kmDSf03",
      "kmDSf04",
      "kmDSf05",
      "kmDSf06",
      "kmDSf07",
      "kmDSf08",
      "kmDSfsp",
      "kmDSfw",
      "kmDStot",
      "kmdsbwp_1",
      "kmdsbwp_2",
      "kmdsbwp_3",
      "kmdsbwp_4",
      "kmdsbwp_5",
      "kmdsfwp_1",
      "kmdsfwp_2",
      "kmdsfwp_3",
      "kmdsfwp_4",
      "kmdsfwp_5"
    ),
    canonical_name = c(
      "mDSb01",
      "mDSb02",
      "mDSb03",
      "mDSb04",
      "mDSb05",
      "mDSb06",
      "mDSb07",
      "mDSbsp",
      "mDSbw",
      "mDSf01",
      "mDSf02",
      "mDSf03",
      "mDSf04",
      "mDSf05",
      "mDSf06",
      "mDSf07",
      "mDSf08",
      "mDSfsp",
      "mDSfw",
      "mDStot",
      "mDSb01",
      "mDSb02",
      "mDSb03",
      "mDSb04",
      "mDSb05",
      "mDSb06",
      "mDSb07",
      "mDSbsp",
      "mDSbw",
      "mDSf01",
      "mDSf02",
      "mDSf03",
      "mDSf04",
      "mDSf05",
      "mDSf06",
      "mDSf07",
      "mDSf08",
      "mDSfsp",
      "mDSfw",
      "mDStot",
      "mDSb01",
      "mDSb02",
      "mDSb03",
      "mDSb04",
      "mDSb05",
      "mDSb06",
      "mDSb07",
      "mDSbsp",
      "mDSbw",
      "mDSf01",
      "mDSf02",
      "mDSf03",
      "mDSf04",
      "mDSf05",
      "mDSf06",
      "mDSf07",
      "mDSf08",
      "mDSfsp",
      "mDSfw",
      "mDStot",
      "mDSb01",
      "mDSb02",
      "mDSb03",
      "mDSb04",
      "mDSb05",
      "mDSb06",
      "mDSb07",
      "mDSbsp",
      "mDSbw",
      "mDSf01",
      "mDSf02",
      "mDSf03",
      "mDSf04",
      "mDSf05",
      "mDSf06",
      "mDSf07",
      "mDSf08",
      "mDSfsp",
      "mDSfw",
      "mDStot",
      "mdsbwp_1",
      "mdsbwp_2",
      "mdsbwp_3",
      "mdsbwp_4",
      "mdsbwp_5",
      "mdsfwp_1",
      "mdsfwp_2",
      "mdsfwp_3",
      "mdsfwp_4",
      "mdsfwp_5"
    ),
    variable_label = c(
      "Digit Span backwards: 2 numbers, attempt 1+2",
      "Digit Span backwards: 3 numbers, attempt 1+2",
      "Digit Span backwards: 4 numbers, attempt 1+2",
      "Digit Span backwards: 5 numbers, attempt 1+2",
      "Digit Span backwards: 6 numbers, attempt 1+2",
      "Digit Span backwards: 7 numbers, attempt 1+2",
      "Digit Span backwards: 8 numbers, attempt 1+2",
      "WAIS Digit Span: Span backwards",
      "WAIS Digit Span: number of correct backward items",
      "Digit Span forwards: 2 numbers, attempt 1+2",
      "Digit Span forwards: 3 numbers, attempt 1+2",
      "Digit Span forwards: 4 numbers, attempt 1+2",
      "Digit Span forwards: 5 numbers, attempt 1+2",
      "Digit Span forwards: 6 numbers, attempt 1+2",
      "Digit Span forwards: 7 numbers, attempt 1+2",
      "Digit Span forwards: 8 numbers, attempt 1+2",
      "Digit Span forwards: 9 numbers, attempt 1+2",
      "WAIS Digit Span: Span forwards",
      "WAIS Digit Span: number of correct forward items",
      "WAIS Digit Span: total number of correct items",
      "Digit Span backwards: 2 numbers, attempt 1+2",
      "Digit Span backwards: 3 numbers, attempt 1+2",
      "Digit Span backwards: 4 numbers, attempt 1+2",
      "Digit Span backwards: 5 numbers, attempt 1+2",
      "Digit Span backwards: 6 numbers, attempt 1+2",
      "Digit Span backwards: 7 numbers, attempt 1+2",
      "Digit Span backwards: 8 numbers, attempt 1+2",
      "WAIS Digit Span: Span backwards",
      "WAIS Digit Span: number of correct backward items",
      "Digit Span forwards: 2 numbers, attempt 1+2",
      "Digit Span forwards: 3 numbers, attempt 1+2",
      "Digit Span forwards: 4 numbers, attempt 1+2",
      "Digit Span forwards: 5 numbers, attempt 1+2",
      "Digit Span forwards: 6 numbers, attempt 1+2",
      "Digit Span forwards: 7 numbers, attempt 1+2",
      "Digit Span forwards: 8 numbers, attempt 1+2",
      "Digit Span forwards: 9 numbers, attempt 1+2",
      "WAIS Digit Span: Span forwards",
      "WAIS Digit Span: number of correct forward items",
      "WAIS Digit Span: total number of correct items",
      "Digit Span backwards: 2 numbers, attempt 1+2",
      "Digit Span backwards: 3 numbers, attempt 1+2",
      "Digit Span backwards: 4 numbers, attempt 1+2",
      "Digit Span backwards: 5 numbers, attempt 1+2",
      "Digit Span backwards: 6 numbers, attempt 1+2",
      "Digit Span backwards: 7 numbers, attempt 1+2",
      "Digit Span backwards: 8 numbers, attempt 1+2",
      "WAIS Digit Span: Span backwards",
      "WAIS Digit Span: number of correct backward items",
      "Digit Span forwards: 2 numbers, attempt 1+2",
      "Digit Span forwards: 3 numbers, attempt 1+2",
      "Digit Span forwards: 4 numbers, attempt 1+2",
      "Digit Span forwards: 5 numbers, attempt 1+2",
      "Digit Span forwards: 6 numbers, attempt 1+2",
      "Digit Span forwards: 7 numbers, attempt 1+2",
      "Digit Span forwards: 8 numbers, attempt 1+2",
      "Digit Span forwards: 9 numbers, attempt 1+2",
      "WAIS Digit Span: Span forwards",
      "WAIS Digit Span: number of correct forward items",
      "WAIS Digit Span: total number of correct items",
      "Digit Span backwards: 2 numbers, attempt 1+2",
      "Digit Span backwards: 3 numbers, attempt 1+2",
      "Digit Span backwards: 4 numbers, attempt 1+2",
      "Digit Span backwards: 5 numbers, attempt 1+2",
      "Digit Span backwards: 6 numbers, attempt 1+2",
      "Digit Span backwards: 7 numbers, attempt 1+2",
      "Digit Span backwards: 8 numbers, attempt 1+2",
      "WAIS Digit Span: span backwards",
      "WAIS Digit Span: number of correct items backward",
      "Digit Span forwards: 2 numbers, attempt 1+2",
      "Digit Span forwards: 3 numbers, attempt 1+2",
      "Digit Span forwards: 4 numbers, attempt 1+2",
      "Digit Span forwards: 5 numbers, attempt 1+2",
      "Digit Span forwards: 6 numbers, attempt 1+2",
      "Digit Span forwards: 7 numbers, attempt 1+2",
      "Digit Span forwards: 8 numbers, attempt 1+2",
      "Digit Span forwards: 9 numbers, attempt 1+2",
      "WAIS Digit Span: span forwards",
      "WAIS Digit Span: number of correct items forward",
      "WAIS Digit Span: total number of correct items",
      "Digit Span backwards: particularities: company others",
      "Digit Span backwards: particularities: hearing-impaired",
      "Digit Span backwards: particularities: radio or television",
      "Digit Span backwards: particularities: test interrupted",
      "Digit Span backwards: particularities: other",
      "Digit Span forwards: particularities: company others",
      "Digit Span forwards: particularities: hearing-impaired",
      "Digit Span forwards: particularities: radio or television",
      "Digit Span forwards: particularities: test interrupted",
      "Digit Span forwards: particularities: other"
    ),
    harmonized_var_label = c(
      "Digit Span backwards: 2 numbers, attempt 1+2",
      "Digit Span backwards: 3 numbers, attempt 1+2",
      "Digit Span backwards: 4 numbers, attempt 1+2",
      "Digit Span backwards: 5 numbers, attempt 1+2",
      "Digit Span backwards: 6 numbers, attempt 1+2",
      "Digit Span backwards: 7 numbers, attempt 1+2",
      "Digit Span backwards: 8 numbers, attempt 1+2",
      "WAIS Digit Span: span backwards",
      "WAIS Digit Span: number of correct backward items",
      "Digit Span forwards: 2 numbers, attempt 1+2",
      "Digit Span forwards: 3 numbers, attempt 1+2",
      "Digit Span forwards: 4 numbers, attempt 1+2",
      "Digit Span forwards: 5 numbers, attempt 1+2",
      "Digit Span forwards: 6 numbers, attempt 1+2",
      "Digit Span forwards: 7 numbers, attempt 1+2",
      "Digit Span forwards: 8 numbers, attempt 1+2",
      "Digit Span forwards: 9 numbers, attempt 1+2",
      "WAIS Digit Span: span forwards",
      "WAIS Digit Span: number of correct forward items",
      "WAIS Digit Span: total number of correct items",
      "Digit Span backwards: 2 numbers, attempt 1+2",
      "Digit Span backwards: 3 numbers, attempt 1+2",
      "Digit Span backwards: 4 numbers, attempt 1+2",
      "Digit Span backwards: 5 numbers, attempt 1+2",
      "Digit Span backwards: 6 numbers, attempt 1+2",
      "Digit Span backwards: 7 numbers, attempt 1+2",
      "Digit Span backwards: 8 numbers, attempt 1+2",
      "WAIS Digit Span: span backwards",
      "WAIS Digit Span: number of correct backward items",
      "Digit Span forwards: 2 numbers, attempt 1+2",
      "Digit Span forwards: 3 numbers, attempt 1+2",
      "Digit Span forwards: 4 numbers, attempt 1+2",
      "Digit Span forwards: 5 numbers, attempt 1+2",
      "Digit Span forwards: 6 numbers, attempt 1+2",
      "Digit Span forwards: 7 numbers, attempt 1+2",
      "Digit Span forwards: 8 numbers, attempt 1+2",
      "Digit Span forwards: 9 numbers, attempt 1+2",
      "WAIS Digit Span: span forwards",
      "WAIS Digit Span: number of correct forward items",
      "WAIS Digit Span: total number of correct items",
      "Digit Span backwards: 2 numbers, attempt 1+2",
      "Digit Span backwards: 3 numbers, attempt 1+2",
      "Digit Span backwards: 4 numbers, attempt 1+2",
      "Digit Span backwards: 5 numbers, attempt 1+2",
      "Digit Span backwards: 6 numbers, attempt 1+2",
      "Digit Span backwards: 7 numbers, attempt 1+2",
      "Digit Span backwards: 8 numbers, attempt 1+2",
      "WAIS Digit Span: span backwards",
      "WAIS Digit Span: number of correct backward items",
      "Digit Span forwards: 2 numbers, attempt 1+2",
      "Digit Span forwards: 3 numbers, attempt 1+2",
      "Digit Span forwards: 4 numbers, attempt 1+2",
      "Digit Span forwards: 5 numbers, attempt 1+2",
      "Digit Span forwards: 6 numbers, attempt 1+2",
      "Digit Span forwards: 7 numbers, attempt 1+2",
      "Digit Span forwards: 8 numbers, attempt 1+2",
      "Digit Span forwards: 9 numbers, attempt 1+2",
      "WAIS Digit Span: span forwards",
      "WAIS Digit Span: number of correct forward items",
      "WAIS Digit Span: total number of correct items",
      "Digit Span backwards: 2 numbers, attempt 1+2",
      "Digit Span backwards: 3 numbers, attempt 1+2",
      "Digit Span backwards: 4 numbers, attempt 1+2",
      "Digit Span backwards: 5 numbers, attempt 1+2",
      "Digit Span backwards: 6 numbers, attempt 1+2",
      "Digit Span backwards: 7 numbers, attempt 1+2",
      "Digit Span backwards: 8 numbers, attempt 1+2",
      "WAIS Digit Span: span backwards",
      "WAIS Digit Span: number of correct backward items",
      "Digit Span forwards: 2 numbers, attempt 1+2",
      "Digit Span forwards: 3 numbers, attempt 1+2",
      "Digit Span forwards: 4 numbers, attempt 1+2",
      "Digit Span forwards: 5 numbers, attempt 1+2",
      "Digit Span forwards: 6 numbers, attempt 1+2",
      "Digit Span forwards: 7 numbers, attempt 1+2",
      "Digit Span forwards: 8 numbers, attempt 1+2",
      "Digit Span forwards: 9 numbers, attempt 1+2",
      "WAIS Digit Span: span forwards",
      "WAIS Digit Span: number of correct forward items",
      "WAIS Digit Span: total number of correct items",
      "Digit Span backwards particularity: company others",
      "Digit Span backwards particularity: hearing-impaired",
      "Digit Span backwards particularity: radio or television",
      "Digit Span backwards particularity: test interrupted",
      "Digit Span backwards particularity: other",
      "Digit Span forwards particularity: company others",
      "Digit Span forwards particularity: hearing-impaired",
      "Digit Span forwards particularity: radio or television",
      "Digit Span forwards particularity: test interrupted",
      "Digit Span forwards particularity: other"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mDSb01 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSb02 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSb03 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSb04 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSb05 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSb06 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSb07 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSbsp = list(
      H = test_not_done_no_score_too_many_missings,
      I = test_not_done,
      J = test_not_done,
      K = test_not_done_2
    ),
    mDSbw = list(
      H = test_not_done_no_score_too_many_missings,
      I = test_not_done,
      J = test_not_done,
      K = test_not_done_2
    ),
    mDSf01 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSf02 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSf03 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSf04 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSf05 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSf06 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSf07 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSf08 = list(
      H = vs_0_correct_1_correct_2_correct_4,
      I = vs_0_correct_1_correct_2_correct,
      J = vs_0_correct_1_correct_2_correct,
      K = vs_0_correct_1_correct_2_correct_5
    ),
    mDSfsp = list(
      H = test_not_done_no_score_too_many_missings,
      I = test_not_done,
      J = test_not_done,
      K = test_not_done_2
    ),
    mDSfw = list(
      H = test_not_done_no_score_too_many_missings,
      I = test_not_done,
      J = test_not_done,
      K = test_not_done_2
    ),
    mDStot = list(
      H = c(`-3` = "test not done", `-2` = "DS backwards not done", `-1` = "no score, too many missings"),
      I = test_not_done,
      J = test_not_done,
      K = test_not_done_2
    ),
    mdsbwp_1 = list(
      K = not_mentioned_mentioned_168
    ),
    mdsbwp_2 = list(
      K = not_mentioned_mentioned_168
    ),
    mdsbwp_3 = list(
      K = not_mentioned_mentioned_168
    ),
    mdsbwp_4 = list(
      K = not_mentioned_mentioned_168
    ),
    mdsbwp_5 = list(
      K = not_mentioned_mentioned_168
    ),
    mdsfwp_1 = list(
      K = not_mentioned_mentioned_168
    ),
    mdsfwp_2 = list(
      K = not_mentioned_mentioned_168
    ),
    mdsfwp_3 = list(
      K = not_mentioned_mentioned_168
    ),
    mdsfwp_4 = list(
      K = not_mentioned_mentioned_168
    ),
    mdsfwp_5 = list(
      K = not_mentioned_mentioned_168
    )
  ),

  value_labels_harmonized = list(
    mDSb01 = vs_0_correct_1_correct_2_correct_6,
    mDSb02 = vs_0_correct_1_correct_2_correct_6,
    mDSb03 = vs_0_correct_1_correct_2_correct_6,
    mDSb04 = vs_0_correct_1_correct_2_correct_6,
    mDSb05 = vs_0_correct_1_correct_2_correct_6,
    mDSb06 = vs_0_correct_1_correct_2_correct_6,
    mDSb07 = vs_0_correct_1_correct_2_correct_6,
    mDSbsp = test_not_done_test_not_done_no_score_too_many_missings,
    mDSbw = test_not_done_test_not_done_no_score_too_many_missings,
    mDSf01 = vs_0_correct_1_correct_2_correct_6,
    mDSf02 = vs_0_correct_1_correct_2_correct_6,
    mDSf03 = vs_0_correct_1_correct_2_correct_6,
    mDSf04 = vs_0_correct_1_correct_2_correct_6,
    mDSf05 = vs_0_correct_1_correct_2_correct_6,
    mDSf06 = vs_0_correct_1_correct_2_correct_6,
    mDSf07 = vs_0_correct_1_correct_2_correct_6,
    mDSf08 = vs_0_correct_1_correct_2_correct_6,
    mDSfsp = test_not_done_test_not_done_no_score_too_many_missings,
    mDSfw = test_not_done_test_not_done_no_score_too_many_missings,
    mDStot = c(
      `-9` = "test not done",
      `-3` = "test not done",
      `-2` = "DS backwards not done",
      `-1` = "no score, too many missings"
    ),
    mdsbwp_1 = not_mentioned_mentioned_169,
    mdsbwp_2 = not_mentioned_mentioned_169,
    mdsbwp_3 = not_mentioned_mentioned_169,
    mdsbwp_4 = not_mentioned_mentioned_169,
    mdsbwp_5 = not_mentioned_mentioned_169,
    mdsfwp_1 = not_mentioned_mentioned_169,
    mdsfwp_2 = not_mentioned_mentioned_169,
    mdsfwp_3 = not_mentioned_mentioned_169,
    mdsfwp_4 = not_mentioned_mentioned_169,
    mdsfwp_5 = not_mentioned_mentioned_169
  )
)
