## LASA filecode 191 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_191 <- list(
  variables = data.frame(
    wave = c(
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H"
    ),
    variable_name = c(
      "bmRM191_1",
      "bmRM191_10",
      "bmRM191_2",
      "bmRM191_3",
      "bmRM191_4",
      "bmRM191_5",
      "bmRM191_6",
      "bmRM191_7",
      "bmRM191_8",
      "bmRM191_9",
      "bmRM191s1",
      "bmRM191s2",
      "bmacL",
      "bmacLst",
      "bmacR",
      "bmacRst",
      "bmvasL",
      "bmvasLst",
      "bmvasR",
      "bmvasRst",
      "emRM191",
      "emRM191_rem",
      "emacL",
      "emacLst",
      "emacR",
      "emacRst",
      "emvasL",
      "emvasLst",
      "emvasR",
      "emvasRst",
      "fmRM191",
      "fmRM191_1",
      "fmRM191_10",
      "fmRM191_2",
      "fmRM191_3",
      "fmRM191_4",
      "fmRM191_5",
      "fmRM191_6",
      "fmRM191_7",
      "fmRM191_8",
      "fmRM191_9",
      "fmRM191s1",
      "fmRM191s2",
      "fmvasL",
      "fmvasLst",
      "fmvasR",
      "fmvasRst",
      "gmRM191",
      "gmRM191_1",
      "gmRM191_10",
      "gmRM191_2",
      "gmRM191_3",
      "gmRM191_4",
      "gmRM191_5",
      "gmRM191_6",
      "gmRM191_7",
      "gmRM191_8",
      "gmRM191_9",
      "gmRM191s1",
      "gmRM191s2",
      "gmvasL",
      "gmvasLst",
      "gmvasR",
      "gmvasRst",
      "hmRM191_1",
      "hmRM191_10",
      "hmRM191_2",
      "hmRM191_3",
      "hmRM191_4",
      "hmRM191_5",
      "hmRM191_6",
      "hmRM191_7",
      "hmRM191_8",
      "hmRM191_9",
      "hmRM191s1",
      "hmRM191s2",
      "hmacL",
      "hmacLst",
      "hmacR",
      "hmacRst",
      "hmvasL",
      "hmvasLst",
      "hmvasR",
      "hmvasRst"
    ),
    canonical_name = c(
      "mrm191_1",
      "mrm191_10",
      "mrm191_2",
      "mrm191_3",
      "mrm191_4",
      "mrm191_5",
      "mrm191_6",
      "mrm191_7",
      "mrm191_8",
      "mrm191_9",
      "mrm191s1",
      "mrm191s2",
      "macl",
      "maclst",
      "macr",
      "macrst",
      "mvasl",
      "mvaslst",
      "mvasr",
      "mvasrst",
      "mrm191",
      "mrm191_rem",
      "macl",
      "maclst",
      "macr",
      "macrst",
      "mvasl",
      "mvaslst",
      "mvasr",
      "mvasrst",
      "mrm191",
      "mrm191_1",
      "mrm191_10",
      "mrm191_2",
      "mrm191_3",
      "mrm191_4",
      "mrm191_5",
      "mrm191_6",
      "mrm191_7",
      "mrm191_8",
      "mrm191_9",
      "mrm191s1",
      "mrm191s2",
      "mvasl",
      "mvaslst",
      "mvasr",
      "mvasrst",
      "mrm191",
      "mrm191_1",
      "mrm191_10",
      "mrm191_2",
      "mrm191_3",
      "mrm191_4",
      "mrm191_5",
      "mrm191_6",
      "mrm191_7",
      "mrm191_8",
      "mrm191_9",
      "mrm191s1",
      "mrm191s2",
      "mvasl",
      "mvaslst",
      "mvasr",
      "mvasrst",
      "mrm191_1",
      "mrm191_10",
      "mrm191_2",
      "mrm191_3",
      "mrm191_4",
      "mrm191_5",
      "mrm191_6",
      "mrm191_7",
      "mrm191_8",
      "mrm191_9",
      "mrm191s1",
      "mrm191s2",
      "macl",
      "maclst",
      "macr",
      "macrst",
      "mvasl",
      "mvaslst",
      "mvasr",
      "mvasrst"
    ),
    variable_label = c(
      "reason missing: blind rightside",
      "reason missing: equipment failure",
      "reason missing: blind leftside",
      "reason missing: mentally unable",
      "reason missing: physically unable",
      "reason missing: aphasia",
      "reason missing: illiterate",
      "reason missing: refused",
      "reason missing: short interview",
      "reason missing: insufficient light",
      "specification reason missing: blind rightside",
      "specification reason missing: blind leftside",
      "number of lines read correctly (left eye)",
      "number of lines read correctly (left eye pinhole)",
      "number of lines read correctly (right eye)",
      "number of lines read correctly (right eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (left eye)",
      "Visual Acuity Score, number of letters read correctly (left eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (right eye)",
      "Visual Acuity Score, number of letters read correctly (right eye pinhole)",
      "reason missing (partial) data",
      "remarks reason missing (partial) data",
      "number of lines read correctly (left eye)",
      "number of lines read correctly (left eye pinhole)",
      "number of lines read correctly (right eye)",
      "number of lines read correctly (right eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (left eye)",
      "Visual Acuity Score, number of letters read correctly (left eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (right eye)",
      "Visual Acuity Score, number of letters read correctly (right eye pinhole)",
      "reason missing (partial) data",
      "reason missing: blind rightside",
      "reason missing: equipment failure",
      "reason missing: blind leftside",
      "reason missing: mentally unable",
      "reason missing: physically unable",
      "reason missing: aphasia",
      "reason missing: illiterate",
      "reason missing: refused",
      "reason missing: short interview",
      "reason missing: insufficient light",
      "specification reason missing: blind rightside",
      "specification reason missing: blind leftside",
      "Visual Acuity Score, number of letters read correctly (left eye)",
      "Visual Acuity Score, number of letters read correctly (left eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (right eye)",
      "Visual Acuity Score, number of letters read correctly (right eye pinhole)",
      "reason missing (partial) data",
      "reason missing: blind rightside",
      "reason missing: equipment failure",
      "reason missing: blind leftside",
      "reason missing: mentally unable",
      "reason missing: physically unable",
      "reason missing: aphasia",
      "reason missing: illiterate",
      "reason missing: refused",
      "reason missing: short interview",
      "reason missing: insufficient light",
      "specification reason missing: blind rightside",
      "specification reason missing: blind leftside",
      "Visual Acuity Score, number of letters read correctly (left eye)",
      "Visual Acuity Score, number of letters read correctly (left eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (right eye)",
      "Visual Acuity Score, number of letters read correctly (right eye pinhole)",
      "reason missing: blind rightside",
      "reason missing: equipment failure",
      "reason missing: blind leftside",
      "reason missing: mentally unable",
      "reason missing: physically unable",
      "reason missing: aphasia",
      "reason missing: illiterate",
      "reason missing: refused",
      "reason missing: short interview",
      "reason missing: insufficient light",
      "specification reason missing: blind rightside",
      "specification reason missing: blind leftside",
      "number of lines read correctly (left eye)",
      "number of lines read correctly (left eye pinhole)",
      "number of lines read correctly (right eye)",
      "number of lines read correctly (right eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (left eye)",
      "Visual Acuity Score, number of letters read correctly (left eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (right eye)",
      "Visual Acuity Score, number of letters read correctly (right eye pinhole)"
    ),
    harmonized_var_label = c(
      "reason missing: blind rightside",
      "reason missing: equipment failure",
      "reason missing: blind leftside",
      "reason missing: mentally unable",
      "reason missing: physically unable",
      "reason missing: aphasia",
      "reason missing: illiterate",
      "reason missing: refused",
      "reason missing: short interview",
      "reason missing: insufficient light",
      "specification reason missing: blind rightside",
      "specification reason missing: blind leftside",
      "number of lines read correctly (left eye)",
      "number of lines read correctly (left eye pinhole)",
      "number of lines read correctly (right eye)",
      "number of lines read correctly (right eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (left eye)",
      "Visual Acuity Score, number of letters read correctly (left eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (right eye)",
      "Visual Acuity Score, number of letters read correctly (right eye pinhole)",
      "reason missing (partial) data",
      "remarks reason missing (partial) data",
      "number of lines read correctly (left eye)",
      "number of lines read correctly (left eye pinhole)",
      "number of lines read correctly (right eye)",
      "number of lines read correctly (right eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (left eye)",
      "Visual Acuity Score, number of letters read correctly (left eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (right eye)",
      "Visual Acuity Score, number of letters read correctly (right eye pinhole)",
      "reason missing (partial) data",
      "reason missing: blind rightside",
      "reason missing: equipment failure",
      "reason missing: blind leftside",
      "reason missing: mentally unable",
      "reason missing: physically unable",
      "reason missing: aphasia",
      "reason missing: illiterate",
      "reason missing: refused",
      "reason missing: short interview",
      "reason missing: insufficient light",
      "specification reason missing: blind rightside",
      "specification reason missing: blind leftside",
      "Visual Acuity Score, number of letters read correctly (left eye)",
      "Visual Acuity Score, number of letters read correctly (left eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (right eye)",
      "Visual Acuity Score, number of letters read correctly (right eye pinhole)",
      "reason missing (partial) data",
      "reason missing: blind rightside",
      "reason missing: equipment failure",
      "reason missing: blind leftside",
      "reason missing: mentally unable",
      "reason missing: physically unable",
      "reason missing: aphasia",
      "reason missing: illiterate",
      "reason missing: refused",
      "reason missing: short interview",
      "reason missing: insufficient light",
      "specification reason missing: blind rightside",
      "specification reason missing: blind leftside",
      "Visual Acuity Score, number of letters read correctly (left eye)",
      "Visual Acuity Score, number of letters read correctly (left eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (right eye)",
      "Visual Acuity Score, number of letters read correctly (right eye pinhole)",
      "reason missing: blind rightside",
      "reason missing: equipment failure",
      "reason missing: blind leftside",
      "reason missing: mentally unable",
      "reason missing: physically unable",
      "reason missing: aphasia",
      "reason missing: illiterate",
      "reason missing: refused",
      "reason missing: short interview",
      "reason missing: insufficient light",
      "specification reason missing: blind rightside",
      "specification reason missing: blind leftside",
      "number of lines read correctly (left eye)",
      "number of lines read correctly (left eye pinhole)",
      "number of lines read correctly (right eye)",
      "number of lines read correctly (right eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (left eye)",
      "Visual Acuity Score, number of letters read correctly (left eye pinhole)",
      "Visual Acuity Score, number of letters read correctly (right eye)",
      "Visual Acuity Score, number of letters read correctly (right eye pinhole)"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    macl = list(
      `3B` = no_data_2,
      E = no_data_2,
      H = no_data_2
    ),
    maclst = list(
      `3B` = no_data_2,
      E = no_data_2,
      H = no_data_2
    ),
    macr = list(
      `3B` = no_data_2,
      E = no_data_2,
      H = no_data_2
    ),
    macrst = list(
      `3B` = no_data_2,
      E = no_data_2,
      H = no_data_2
    ),
    mrm191_1 = list(
      `3B` = not_mentioned_mentioned_20,
      F = not_mentioned_mentioned_20,
      G = not_mentioned_mentioned_20,
      H = not_mentioned_mentioned_20
    ),
    mrm191_10 = list(
      `3B` = not_mentioned_mentioned_20,
      F = not_mentioned_mentioned_20,
      G = not_mentioned_mentioned_20,
      H = not_mentioned_mentioned_20
    ),
    mrm191_2 = list(
      `3B` = not_mentioned_mentioned_20,
      F = not_mentioned_mentioned_20,
      G = not_mentioned_mentioned_20,
      H = not_mentioned_mentioned_20
    ),
    mrm191_3 = list(
      `3B` = not_mentioned_mentioned_20,
      F = not_mentioned_mentioned_20,
      G = not_mentioned_mentioned_20,
      H = not_mentioned_mentioned_20
    ),
    mrm191_4 = list(
      `3B` = not_mentioned_mentioned_20,
      F = not_mentioned_mentioned_20,
      G = not_mentioned_mentioned_20,
      H = not_mentioned_mentioned_20
    ),
    mrm191_5 = list(
      `3B` = not_mentioned_mentioned_20,
      F = not_mentioned_mentioned_20,
      G = not_mentioned_mentioned_20,
      H = not_mentioned_mentioned_20
    ),
    mrm191_6 = list(
      `3B` = not_mentioned_mentioned_20,
      F = not_mentioned_mentioned_20,
      G = not_mentioned_mentioned_20,
      H = not_mentioned_mentioned_20
    ),
    mrm191_7 = list(
      `3B` = not_mentioned_mentioned_20,
      F = not_mentioned_mentioned_20,
      G = not_mentioned_mentioned_20,
      H = not_mentioned_mentioned_20
    ),
    mrm191_8 = list(
      `3B` = not_mentioned_mentioned_20,
      F = not_mentioned_mentioned_20,
      G = not_mentioned_mentioned_20,
      H = not_mentioned_mentioned_20
    ),
    mrm191_9 = list(
      `3B` = not_mentioned_mentioned_20,
      F = not_mentioned_mentioned_20,
      G = not_mentioned_mentioned_20,
      H = not_mentioned_mentioned_20
    ),
    mrm191s1 = list(
      `3B` = c(
        `-2` = "na, see BMRM191_1",
        `1` = "still perception of light",
        `2` = "no perception of light",
        `3` = "prosthesis"
      ),
      F = c(
        `-2` = "na, see FMRM191_1",
        `1` = "still perception of light",
        `2` = "no perception of light",
        `3` = "prosthesis"
      ),
      G = c(
        `-2` = "na, see GMRM191_1",
        `1` = "still perception of light",
        `2` = "no perception of light",
        `3` = "prosthesis"
      ),
      H = c(
        `-2` = "na, see HMRM191_1",
        `1` = "still perception of light",
        `2` = "no perception of light",
        `3` = "prosthesis"
      )
    ),
    mrm191s2 = list(
      `3B` = c(
        `-2` = "na, see BMRM191_2",
        `1` = "still perception of light",
        `2` = "no perception of light",
        `3` = "prosthesis"
      ),
      F = c(
        `-2` = "na, see FMRM191_2",
        `1` = "still perception of light",
        `2` = "no perception of light",
        `3` = "prosthesis"
      ),
      G = c(
        `-2` = "na, see GMRM191_2",
        `1` = "still perception of light",
        `2` = "no perception of light",
        `3` = "prosthesis"
      ),
      H = c(
        `-2` = "na, see HMRM191_2",
        `1` = "still perception of light",
        `2` = "no perception of light",
        `3` = "prosthesis"
      )
    ),
    mvasl = list(
      `3B` = no_data,
      E = no_data,
      F = no_data,
      G = no_data,
      H = no_data
    ),
    mvaslst = list(
      `3B` = no_data,
      E = no_data,
      F = no_data,
      G = no_data,
      H = no_data
    ),
    mvasr = list(
      `3B` = no_data,
      E = no_data,
      F = no_data,
      G = no_data,
      H = no_data
    ),
    mvasrst = list(
      `3B` = no_data,
      E = no_data,
      F = no_data,
      G = no_data,
      H = no_data
    ),
    mrm191 = list(
      E = short_interview_insufficient_light,
      F = short_interview_insufficient_light,
      G = short_interview_insufficient_light
    )
  ),

  value_labels_harmonized = list(
    macl = no_valid_data_8,
    maclst = no_valid_data_8,
    macr = no_valid_data_8,
    macrst = no_valid_data_8,
    mrm191 = c(
      `-3` = "no valid data",
      `-2` = "(partial) valid data",
      `1` = "short interview",
      `2` = "insufficient light",
      `3` = "visually impaired/(partially) blind",
      `4` = "physically unable",
      `5` = "aphasia/illiterate",
      `6` = "equipment failure",
      `7` = "refused"
    ),
    mrm191_1 = not_mentioned_mentioned_20,
    mrm191_10 = not_mentioned_mentioned_20,
    mrm191_2 = not_mentioned_mentioned_20,
    mrm191_3 = not_mentioned_mentioned_20,
    mrm191_4 = not_mentioned_mentioned_20,
    mrm191_5 = not_mentioned_mentioned_20,
    mrm191_6 = not_mentioned_mentioned_20,
    mrm191_7 = not_mentioned_mentioned_20,
    mrm191_8 = not_mentioned_mentioned_20,
    mrm191_9 = not_mentioned_mentioned_20,
    mrm191s1 = still_perception_of_light_no_perception_of_light,
    mrm191s2 = still_perception_of_light_no_perception_of_light,
    mvasl = no_valid_data_9,
    mvaslst = no_valid_data_9,
    mvasr = no_valid_data_9,
    mvasrst = no_valid_data_9
  )
)
