## LASA filecode 022 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_022 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G"
    ),
    variable_name = c(
      "bmraabmis",
      "bmrava1",
      "bmrava10",
      "bmrava11",
      "bmrava12",
      "bmrava2",
      "bmrava3",
      "bmrava4",
      "bmrava5",
      "bmrava6",
      "bmrava7",
      "bmrava8",
      "bmrava9",
      "bmravamis",
      "bmravb1",
      "bmravb10",
      "bmravb11",
      "bmravb12",
      "bmravb2",
      "bmravb3",
      "bmravb4",
      "bmravb5",
      "bmravb6",
      "bmravb7",
      "bmravb8",
      "bmravb9",
      "bmravbmis",
      "braabmis",
      "brava1",
      "brava10",
      "brava11",
      "brava12",
      "brava2",
      "brava3",
      "brava4",
      "brava5",
      "brava6",
      "brava7",
      "brava8",
      "brava9",
      "bravamis",
      "bravb1",
      "bravb10",
      "bravb11",
      "bravb12",
      "bravb2",
      "bravb3",
      "bravb4",
      "bravb5",
      "bravb6",
      "bravb7",
      "bravb8",
      "bravb9",
      "bravbmis",
      "craabmis",
      "crava1",
      "crava10",
      "crava11",
      "crava12",
      "crava2",
      "crava3",
      "crava4",
      "crava5",
      "crava6",
      "crava7",
      "crava8",
      "crava9",
      "cravamis",
      "cravb1",
      "cravb10",
      "cravb11",
      "cravb12",
      "cravb2",
      "cravb3",
      "cravb4",
      "cravb5",
      "cravb6",
      "cravb7",
      "cravb8",
      "cravb9",
      "cravbmis",
      "draabmis",
      "drava1",
      "drava10",
      "drava11",
      "drava12",
      "drava2",
      "drava3",
      "drava4",
      "drava5",
      "drava6",
      "drava7",
      "drava8",
      "drava9",
      "dravamis",
      "dravb1",
      "dravb10",
      "dravb11",
      "dravb12",
      "dravb2",
      "dravb3",
      "dravb4",
      "dravb5",
      "dravb6",
      "dravb7",
      "dravb8",
      "dravb9",
      "dravbmis",
      "emrabmis",
      "emrava1",
      "emrava10",
      "emrava11",
      "emrava12",
      "emrava2",
      "emrava3",
      "emrava4",
      "emrava5",
      "emrava6",
      "emrava7",
      "emrava8",
      "emrava9",
      "emravamis",
      "emravb1",
      "emravb10",
      "emravb11",
      "emravb12",
      "emravb2",
      "emravb3",
      "emravb4",
      "emravb5",
      "emravb6",
      "emravb7",
      "emravb8",
      "emravb9",
      "emravbmis",
      "fmrabmis",
      "fmrava1",
      "fmrava10",
      "fmrava11",
      "fmrava12",
      "fmrava2",
      "fmrava3",
      "fmrava4",
      "fmrava5",
      "fmrava6",
      "fmrava7",
      "fmrava8",
      "fmrava9",
      "fmravamis",
      "fmravb1",
      "fmravb10",
      "fmravb11",
      "fmravb12",
      "fmravb2",
      "fmravb3",
      "fmravb4",
      "fmravb5",
      "fmravb6",
      "fmravb7",
      "fmravb8",
      "fmravb9",
      "fmravbmis",
      "gmrabmis",
      "gmrava1",
      "gmrava10",
      "gmrava11",
      "gmrava12",
      "gmrava2",
      "gmrava3",
      "gmrava4",
      "gmrava5",
      "gmrava6",
      "gmrava7",
      "gmrava8",
      "gmrava9",
      "gmravamis",
      "gmravb1",
      "gmravb10",
      "gmravb11",
      "gmravb12",
      "gmravb2",
      "gmravb3",
      "gmravb4",
      "gmravb5",
      "gmravb6",
      "gmravb7",
      "gmravb8",
      "gmravb9",
      "gmravbmis"
    ),
    canonical_name = c(
      "mraabmis",
      "mrava1",
      "mrava10",
      "mrava11",
      "mrava12",
      "mrava2",
      "mrava3",
      "mrava4",
      "mrava5",
      "mrava6",
      "mrava7",
      "mrava8",
      "mrava9",
      "mravamis",
      "mravb1",
      "mravb10",
      "mravb11",
      "mravb12",
      "mravb2",
      "mravb3",
      "mravb4",
      "mravb5",
      "mravb6",
      "mravb7",
      "mravb8",
      "mravb9",
      "mravbmis",
      "raabmis",
      "rava1",
      "rava10",
      "rava11",
      "rava12",
      "rava2",
      "rava3",
      "rava4",
      "rava5",
      "rava6",
      "rava7",
      "rava8",
      "rava9",
      "ravamis",
      "ravb1",
      "ravb10",
      "ravb11",
      "ravb12",
      "ravb2",
      "ravb3",
      "ravb4",
      "ravb5",
      "ravb6",
      "ravb7",
      "ravb8",
      "ravb9",
      "ravbmis",
      "raabmis",
      "rava1",
      "rava10",
      "rava11",
      "rava12",
      "rava2",
      "rava3",
      "rava4",
      "rava5",
      "rava6",
      "rava7",
      "rava8",
      "rava9",
      "ravamis",
      "ravb1",
      "ravb10",
      "ravb11",
      "ravb12",
      "ravb2",
      "ravb3",
      "ravb4",
      "ravb5",
      "ravb6",
      "ravb7",
      "ravb8",
      "ravb9",
      "ravbmis",
      "raabmis",
      "rava1",
      "rava10",
      "rava11",
      "rava12",
      "rava2",
      "rava3",
      "rava4",
      "rava5",
      "rava6",
      "rava7",
      "rava8",
      "rava9",
      "ravamis",
      "ravb1",
      "ravb10",
      "ravb11",
      "ravb12",
      "ravb2",
      "ravb3",
      "ravb4",
      "ravb5",
      "ravb6",
      "ravb7",
      "ravb8",
      "ravb9",
      "ravbmis",
      "mraabmis",
      "mrava1",
      "mrava10",
      "mrava11",
      "mrava12",
      "mrava2",
      "mrava3",
      "mrava4",
      "mrava5",
      "mrava6",
      "mrava7",
      "mrava8",
      "mrava9",
      "mravamis",
      "mravb1",
      "mravb10",
      "mravb11",
      "mravb12",
      "mravb2",
      "mravb3",
      "mravb4",
      "mravb5",
      "mravb6",
      "mravb7",
      "mravb8",
      "mravb9",
      "mravbmis",
      "mraabmis",
      "mrava1",
      "mrava10",
      "mrava11",
      "mrava12",
      "mrava2",
      "mrava3",
      "mrava4",
      "mrava5",
      "mrava6",
      "mrava7",
      "mrava8",
      "mrava9",
      "mravamis",
      "mravb1",
      "mravb10",
      "mravb11",
      "mravb12",
      "mravb2",
      "mravb3",
      "mravb4",
      "mravb5",
      "mravb6",
      "mravb7",
      "mravb8",
      "mravb9",
      "mravbmis",
      "mraabmis",
      "mrava1",
      "mrava10",
      "mrava11",
      "mrava12",
      "mrava2",
      "mrava3",
      "mrava4",
      "mrava5",
      "mrava6",
      "mrava7",
      "mrava8",
      "mrava9",
      "mravamis",
      "mravb1",
      "mravb10",
      "mravb11",
      "mravb12",
      "mravb2",
      "mravb3",
      "mravb4",
      "mravb5",
      "mravb6",
      "mravb7",
      "mravb8",
      "mravb9",
      "mravbmis"
    ),
    variable_label = c(
      "# of missing answers total test",
      "C. Raven Section A: item 1",
      "C. Raven Section A: item 10",
      "C. Raven Section A: item 11",
      "C. Raven Section A: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section A: item 3",
      "C. Raven Section A: item 4",
      "C. Raven Section A: item 5",
      "C. Raven Section A: item 6",
      "C. Raven Section A: item 7",
      "C. Raven Section A: item 8",
      "C. Raven Section A: item 9",
      "# of missing answers first Raven test (A)",
      "C. Raven Section B: item 1",
      "C. Raven Section B: item 10",
      "C. Raven Section B: item 11",
      "C. Raven Section B: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section B: item 3",
      "C. Raven Section B: item 4",
      "C. Raven Section B: item 5",
      "C. Raven Section B: item 6",
      "C. Raven Section B: item 7",
      "C. Raven Section B: item 8",
      "C. Raven Section B: item 9",
      "# of missing answers second Raven test (B)",
      "#N of missing answers total test",
      "C. Raven Section A: item 1",
      "C. Raven Section A: item 10",
      "C. Raven Section A: item 11",
      "C. Raven Section A: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section A: item 3",
      "C. Raven Section A: item 4",
      "C. Raven Section A: item 5",
      "C. Raven Section A: item 6",
      "C. Raven Section A: item 7",
      "C. Raven Section A: item 8",
      "C. Raven Section A: item 9",
      "#N of missing answers first (A) Raven test",
      "C. Raven Section B: item 1",
      "C. Raven Section B: item 10",
      "C. Raven Section B: item 11",
      "C. Raven Section B: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section B: item 3",
      "C. Raven Section B: item 4",
      "C. Raven Section B: item 5",
      "C. Raven Section B: item 6",
      "C. Raven Section B: item 7",
      "C. Raven Section B: item 8",
      "C. Raven Section B: item 9",
      "#N of missing answers second (B) Raven test",
      "# of missing answers total test",
      "C. Raven Section A: item 1",
      "C. Raven Section A: item 10",
      "C. Raven Section A: item 11",
      "C. Raven Section A: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section A: item 3",
      "C. Raven Section A: item 4",
      "C. Raven Section A: item 5",
      "C. Raven Section A: item 6",
      "C. Raven Section A: item 7",
      "C. Raven Section A: item 8",
      "C. Raven Section A: item 9",
      "# of missing answers first Raven test (A)",
      "C. Raven Section B: item 1",
      "C. Raven Section B: item 10",
      "C. Raven Section B: item 11",
      "C. Raven Section B: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section B: item 3",
      "C. Raven Section B: item 4",
      "C. Raven Section B: item 5",
      "C. Raven Section B: item 6",
      "C. Raven Section B: item 7",
      "C. Raven Section B: item 8",
      "C. Raven Section B: item 9",
      "# of missing answers second Raven test (B)",
      "# of missing answers total test",
      "C. Raven Section A: item 1",
      "C. Raven Section A: item 10",
      "C. Raven Section A: item 11",
      "C. Raven Section A: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section A: item 3",
      "C. Raven Section A: item 4",
      "C. Raven Section A: item 5",
      "C. Raven Section A: item 6",
      "C. Raven Section A: item 7",
      "C. Raven Section A: item 8",
      "C. Raven Section A: item 9",
      "# of missing answers first Raven test (A)",
      "C. Raven Section B: item 1",
      "C. Raven Section B: item 10",
      "C. Raven Section B: item 11",
      "C. Raven Section B: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section B: item 3",
      "C. Raven Section B: item 4",
      "C. Raven Section B: item 5",
      "C. Raven Section B: item 6",
      "C. Raven Section B: item 7",
      "C. Raven Section B: item 8",
      "C. Raven Section B: item 9",
      "# of missing answers second Raven test (B)",
      "# of missing answers total test",
      "C. Raven Section A: item 1",
      "C. Raven Section A: item 10",
      "C. Raven Section A: item 11",
      "C. Raven Section A: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section A: item 3",
      "C. Raven Section A: item 4",
      "C. Raven Section A: item 5",
      "C. Raven Section A: item 6",
      "C. Raven Section A: item 7",
      "C. Raven Section A: item 8",
      "C. Raven Section A: item 9",
      "# of missing answers first Raven test (A)",
      "C. Raven Section B: item 1",
      "C. Raven Section B: item 10",
      "C. Raven Section B: item 11",
      "C. Raven Section B: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section B: item 3",
      "C. Raven Section B: item 4",
      "C. Raven Section B: item 5",
      "C. Raven Section B: item 6",
      "C. Raven Section B: item 7",
      "C. Raven Section B: item 8",
      "C. Raven Section B: item 9",
      "# of missing answers second Raven test (B)",
      "# of missing answers total test",
      "C. Raven Section A: item 1",
      "C. Raven Section A: item 10",
      "C. Raven Section A: item 11",
      "C. Raven Section A: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section A: item 3",
      "C. Raven Section A: item 4",
      "C. Raven Section A: item 5",
      "C. Raven Section A: item 6",
      "C. Raven Section A: item 7",
      "C. Raven Section A: item 8",
      "C. Raven Section A: item 9",
      "# of missing answers first Raven test (A)",
      "C. Raven Section B: item 1",
      "C. Raven Section B: item 10",
      "C. Raven Section B: item 11",
      "C. Raven Section B: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section B: item 3",
      "C. Raven Section B: item 4",
      "C. Raven Section B: item 5",
      "C. Raven Section B: item 6",
      "C. Raven Section B: item 7",
      "C. Raven Section B: item 8",
      "C. Raven Section B: item 9",
      "# of missing answers second Raven test (B)",
      "# of missing answers total test",
      "C. Raven Section A: item 1",
      "C. Raven Section A: item 10",
      "C. Raven Section A: item 11",
      "C. Raven Section A: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section A: item 3",
      "C. Raven Section A: item 4",
      "C. Raven Section A: item 5",
      "C. Raven Section A: item 6",
      "C. Raven Section A: item 7",
      "C. Raven Section A: item 8",
      "C. Raven Section A: item 9",
      "# of missing answers first Raven test (A)",
      "C. Raven Section B: item 1",
      "C. Raven Section B: item 10",
      "C. Raven Section B: item 11",
      "C. Raven Section B: item 12",
      "C. Raven Section A: item 2",
      "C. Raven Section B: item 3",
      "C. Raven Section B: item 4",
      "C. Raven Section B: item 5",
      "C. Raven Section B: item 6",
      "C. Raven Section B: item 7",
      "C. Raven Section B: item 8",
      "C. Raven Section B: item 9",
      "# of missing answers second Raven test (B)"
    ),
    harmonized_var_label = c(
      "Medical interview: # of missing answers total test",
      "Medical interview C. Raven Section A: item 1",
      "Medical interview C. Raven Section A: item 10",
      "Medical interview C. Raven Section A: item 11",
      "Medical interview C. Raven Section A: item 12",
      "Medical interview C. Raven Section A: item 2",
      "Medical interview C. Raven Section A: item 3",
      "Medical interview C. Raven Section A: item 4",
      "Medical interview C. Raven Section A: item 5",
      "Medical interview C. Raven Section A: item 6",
      "Medical interview C. Raven Section A: item 7",
      "Medical interview C. Raven Section A: item 8",
      "Medical interview C. Raven Section A: item 9",
      "Medical interview: # of missing answers first Raven test (A)",
      "Medical interview C. Raven Section B: item 1",
      "Medical interview C. Raven Section B: item 10",
      "Medical interview C. Raven Section B: item 11",
      "Medical interview C. Raven Section B: item 12",
      "Medical interview C. Raven Section B: item 2",
      "Medical interview C. Raven Section B: item 3",
      "Medical interview C. Raven Section B: item 4",
      "Medical interview C. Raven Section B: item 5",
      "Medical interview C. Raven Section B: item 6",
      "Medical interview C. Raven Section B: item 7",
      "Medical interview C. Raven Section B: item 8",
      "Medical interview C. Raven Section B: item 9",
      "Medical interview: # of missing answers second Raven test (B)",
      "Main interview: # of missing answers total test",
      "Main interview C. Raven Section A: item 1",
      "Main interview C. Raven Section A: item 10",
      "Main interview C. Raven Section A: item 11",
      "Main interview C. Raven Section A: item 12",
      "Main interview C. Raven Section A: item 2",
      "Main interview C. Raven Section A: item 3",
      "Main interview C. Raven Section A: item 4",
      "Main interview C. Raven Section A: item 5",
      "Main interview C. Raven Section A: item 6",
      "Main interview C. Raven Section A: item 7",
      "Main interview C. Raven Section A: item 8",
      "Main interview C. Raven Section A: item 9",
      "Main interview: # of missing answers first Raven test (A)",
      "Main interview C. Raven Section B: item 1",
      "Main interview C. Raven Section B: item 10",
      "Main interview C. Raven Section B: item 11",
      "Main interview C. Raven Section B: item 12",
      "Main interview C. Raven Section B: item 2",
      "Main interview C. Raven Section B: item 3",
      "Main interview C. Raven Section B: item 4",
      "Main interview C. Raven Section B: item 5",
      "Main interview C. Raven Section B: item 6",
      "Main interview C. Raven Section B: item 7",
      "Main interview C. Raven Section B: item 8",
      "Main interview C. Raven Section B: item 9",
      "Main interview: # of missing answers second Raven test (B)",
      "Main interview: # of missing answers total test",
      "Main interview C. Raven Section A: item 1",
      "Main interview C. Raven Section A: item 10",
      "Main interview C. Raven Section A: item 11",
      "Main interview C. Raven Section A: item 12",
      "Main interview C. Raven Section A: item 2",
      "Main interview C. Raven Section A: item 3",
      "Main interview C. Raven Section A: item 4",
      "Main interview C. Raven Section A: item 5",
      "Main interview C. Raven Section A: item 6",
      "Main interview C. Raven Section A: item 7",
      "Main interview C. Raven Section A: item 8",
      "Main interview C. Raven Section A: item 9",
      "Main interview: # of missing answers first Raven test (A)",
      "Main interview C. Raven Section B: item 1",
      "Main interview C. Raven Section B: item 10",
      "Main interview C. Raven Section B: item 11",
      "Main interview C. Raven Section B: item 12",
      "Main interview C. Raven Section B: item 2",
      "Main interview C. Raven Section B: item 3",
      "Main interview C. Raven Section B: item 4",
      "Main interview C. Raven Section B: item 5",
      "Main interview C. Raven Section B: item 6",
      "Main interview C. Raven Section B: item 7",
      "Main interview C. Raven Section B: item 8",
      "Main interview C. Raven Section B: item 9",
      "Main interview: # of missing answers second Raven test (B)",
      "Main interview: # of missing answers total test",
      "Main interview C. Raven Section A: item 1",
      "Main interview C. Raven Section A: item 10",
      "Main interview C. Raven Section A: item 11",
      "Main interview C. Raven Section A: item 12",
      "Main interview C. Raven Section A: item 2",
      "Main interview C. Raven Section A: item 3",
      "Main interview C. Raven Section A: item 4",
      "Main interview C. Raven Section A: item 5",
      "Main interview C. Raven Section A: item 6",
      "Main interview C. Raven Section A: item 7",
      "Main interview C. Raven Section A: item 8",
      "Main interview C. Raven Section A: item 9",
      "Main interview: # of missing answers first Raven test (A)",
      "Main interview C. Raven Section B: item 1",
      "Main interview C. Raven Section B: item 10",
      "Main interview C. Raven Section B: item 11",
      "Main interview C. Raven Section B: item 12",
      "Main interview C. Raven Section B: item 2",
      "Main interview C. Raven Section B: item 3",
      "Main interview C. Raven Section B: item 4",
      "Main interview C. Raven Section B: item 5",
      "Main interview C. Raven Section B: item 6",
      "Main interview C. Raven Section B: item 7",
      "Main interview C. Raven Section B: item 8",
      "Main interview C. Raven Section B: item 9",
      "Main interview: # of missing answers second Raven test (B)",
      "Medical interview: # of missing answers total test",
      "Medical interview C. Raven Section A: item 1",
      "Medical interview C. Raven Section A: item 10",
      "Medical interview C. Raven Section A: item 11",
      "Medical interview C. Raven Section A: item 12",
      "Medical interview C. Raven Section A: item 2",
      "Medical interview C. Raven Section A: item 3",
      "Medical interview C. Raven Section A: item 4",
      "Medical interview C. Raven Section A: item 5",
      "Medical interview C. Raven Section A: item 6",
      "Medical interview C. Raven Section A: item 7",
      "Medical interview C. Raven Section A: item 8",
      "Medical interview C. Raven Section A: item 9",
      "Medical interview: # of missing answers first Raven test (A)",
      "Medical interview C. Raven Section B: item 1",
      "Medical interview C. Raven Section B: item 10",
      "Medical interview C. Raven Section B: item 11",
      "Medical interview C. Raven Section B: item 12",
      "Medical interview C. Raven Section B: item 2",
      "Medical interview C. Raven Section B: item 3",
      "Medical interview C. Raven Section B: item 4",
      "Medical interview C. Raven Section B: item 5",
      "Medical interview C. Raven Section B: item 6",
      "Medical interview C. Raven Section B: item 7",
      "Medical interview C. Raven Section B: item 8",
      "Medical interview C. Raven Section B: item 9",
      "Medical interview: # of missing answers second Raven test (B)",
      "Medical interview: # of missing answers total test",
      "Medical interview C. Raven Section A: item 1",
      "Medical interview C. Raven Section A: item 10",
      "Medical interview C. Raven Section A: item 11",
      "Medical interview C. Raven Section A: item 12",
      "Medical interview C. Raven Section A: item 2",
      "Medical interview C. Raven Section A: item 3",
      "Medical interview C. Raven Section A: item 4",
      "Medical interview C. Raven Section A: item 5",
      "Medical interview C. Raven Section A: item 6",
      "Medical interview C. Raven Section A: item 7",
      "Medical interview C. Raven Section A: item 8",
      "Medical interview C. Raven Section A: item 9",
      "Medical interview: # of missing answers first Raven test (A)",
      "Medical interview C. Raven Section B: item 1",
      "Medical interview C. Raven Section B: item 10",
      "Medical interview C. Raven Section B: item 11",
      "Medical interview C. Raven Section B: item 12",
      "Medical interview C. Raven Section B: item 2",
      "Medical interview C. Raven Section B: item 3",
      "Medical interview C. Raven Section B: item 4",
      "Medical interview C. Raven Section B: item 5",
      "Medical interview C. Raven Section B: item 6",
      "Medical interview C. Raven Section B: item 7",
      "Medical interview C. Raven Section B: item 8",
      "Medical interview C. Raven Section B: item 9",
      "Medical interview: # of missing answers second Raven test (B)",
      "Medical interview: # of missing answers total test",
      "Medical interview C. Raven Section A: item 1",
      "Medical interview C. Raven Section A: item 10",
      "Medical interview C. Raven Section A: item 11",
      "Medical interview C. Raven Section A: item 12",
      "Medical interview C. Raven Section A: item 2",
      "Medical interview C. Raven Section A: item 3",
      "Medical interview C. Raven Section A: item 4",
      "Medical interview C. Raven Section A: item 5",
      "Medical interview C. Raven Section A: item 6",
      "Medical interview C. Raven Section A: item 7",
      "Medical interview C. Raven Section A: item 8",
      "Medical interview C. Raven Section A: item 9",
      "Medical interview: # of missing answers first Raven test (A)",
      "Medical interview C. Raven Section B: item 1",
      "Medical interview C. Raven Section B: item 10",
      "Medical interview C. Raven Section B: item 11",
      "Medical interview C. Raven Section B: item 12",
      "Medical interview C. Raven Section B: item 2",
      "Medical interview C. Raven Section B: item 3",
      "Medical interview C. Raven Section B: item 4",
      "Medical interview C. Raven Section B: item 5",
      "Medical interview C. Raven Section B: item 6",
      "Medical interview C. Raven Section B: item 7",
      "Medical interview C. Raven Section B: item 8",
      "Medical interview C. Raven Section B: item 9",
      "Medical interview: # of missing answers second Raven test (B)"
    ),
    var_type = c(
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mrava1 = list(
      `2B` = correct_13,
      E = correct,
      F = correct,
      G = correct
    ),
    mrava10 = list(
      `2B` = correct_14,
      E = correct_2,
      F = correct_2,
      G = correct_2
    ),
    mrava11 = list(
      `2B` = correct_13,
      E = correct,
      F = correct,
      G = correct
    ),
    mrava12 = list(
      `2B` = correct_15,
      E = correct_3,
      F = correct_3,
      G = correct_3
    ),
    mrava2 = list(
      `2B` = correct_15,
      E = correct_3,
      F = correct_3,
      G = correct_3
    ),
    mrava3 = list(
      `2B` = correct_36,
      E = correct_4,
      F = correct_4,
      G = correct_4
    ),
    mrava4 = list(
      `2B` = correct_16,
      E = correct_5,
      F = correct_5,
      G = correct_5
    ),
    mrava5 = list(
      `2B` = correct_17,
      E = correct_6,
      F = correct_6,
      G = correct_6
    ),
    mrava6 = list(
      `2B` = correct_14,
      E = correct_2,
      F = correct_2,
      G = correct_2
    ),
    mrava7 = list(
      `2B` = correct_17,
      E = correct_6,
      F = correct_6,
      G = correct_6
    ),
    mrava8 = list(
      `2B` = correct_16,
      E = correct_5,
      F = correct_5,
      G = correct_5
    ),
    mrava9 = list(
      `2B` = c(`-2` = "na, see C/DRMCRAV in LAS2B222", `-1` = "na, asked", `1` = "correct"),
      E = correct_4,
      F = correct_4,
      G = correct_4
    ),
    mravb1 = list(
      `2B` = correct_16,
      E = correct_5,
      F = correct_5,
      G = correct_5
    ),
    mravb10 = list(
      `2B` = correct_14,
      E = correct_2,
      F = correct_2,
      G = correct_2
    ),
    mravb11 = list(
      `2B` = correct_13,
      E = correct,
      F = correct,
      G = correct
    ),
    mravb12 = list(
      `2B` = correct_15,
      E = correct_3,
      F = correct_3,
      G = correct_3
    ),
    mravb2 = list(
      `2B` = correct_17,
      E = correct_6,
      F = correct_6,
      G = correct_6
    ),
    mravb3 = list(
      `2B` = correct_36,
      E = correct_4,
      F = correct_4,
      G = correct_4
    ),
    mravb4 = list(
      `2B` = correct_16,
      E = correct_5,
      F = correct_5,
      G = correct_5
    ),
    mravb5 = list(
      `2B` = correct_36,
      E = correct_4,
      F = correct_4,
      G = correct_4
    ),
    mravb6 = list(
      `2B` = correct_14,
      E = correct_2,
      F = correct_2,
      G = correct_2
    ),
    mravb7 = list(
      `2B` = correct_15,
      E = correct_3,
      F = correct_3,
      G = correct_3
    ),
    mravb8 = list(
      `2B` = correct_17,
      E = correct_6,
      F = correct_6,
      G = correct_6
    ),
    mravb9 = list(
      `2B` = correct_13,
      E = correct,
      F = correct,
      G = correct
    ),
    raabmis = list(
      B = no_valid_data_interview_broken_off,
      C = na_see_c_drmcrav_in_lasac_d_e222,
      D = na_see_c_drmcrav_in_lasac_d_e222
    ),
    rava1 = list(
      B = correct_18,
      C = correct_7,
      D = correct_7
    ),
    rava10 = list(
      B = correct_19,
      C = correct_8,
      D = correct_8
    ),
    rava11 = list(
      B = correct_18,
      C = correct_7,
      D = correct_7
    ),
    rava12 = list(
      B = correct_20,
      C = correct_9,
      D = correct_9
    ),
    rava2 = list(
      B = correct_20,
      C = correct_9,
      D = correct_9
    ),
    rava3 = list(
      B = correct_21,
      C = correct_10,
      D = correct_10
    ),
    rava4 = list(
      B = correct_22,
      C = correct_11,
      D = correct_11
    ),
    rava5 = list(
      B = correct_23,
      C = correct_12,
      D = correct_12
    ),
    rava6 = list(
      B = correct_19,
      C = correct_8,
      D = correct_8
    ),
    rava7 = list(
      B = correct_23,
      C = correct_12,
      D = correct_12
    ),
    rava8 = list(
      B = correct_22,
      C = correct_11,
      D = correct_11
    ),
    rava9 = list(
      B = correct_21,
      C = correct_10,
      D = correct_10
    ),
    ravamis = list(
      B = no_valid_data_interview_broken_off,
      C = na_see_c_drmcrav_in_lasac_d_e222,
      D = na_see_c_drmcrav_in_lasac_d_e222
    ),
    ravb1 = list(
      B = correct_22,
      C = correct_11,
      D = correct_11
    ),
    ravb10 = list(
      B = correct_19,
      C = correct_8,
      D = correct_8
    ),
    ravb11 = list(
      B = correct_18,
      C = correct_7,
      D = correct_7
    ),
    ravb12 = list(
      B = correct_20,
      C = correct_9,
      D = correct_9
    ),
    ravb2 = list(
      B = correct_23,
      C = correct_12,
      D = correct_12
    ),
    ravb3 = list(
      B = correct_21,
      C = correct_10,
      D = correct_10
    ),
    ravb4 = list(
      B = correct_22,
      C = correct_11,
      D = correct_11
    ),
    ravb5 = list(
      B = correct_21,
      C = correct_10,
      D = correct_10
    ),
    ravb6 = list(
      B = correct_19,
      C = correct_8,
      D = correct_8
    ),
    ravb7 = list(
      B = correct_20,
      C = correct_9,
      D = correct_9
    ),
    ravb8 = list(
      B = correct_23,
      C = correct_12,
      D = correct_12
    ),
    ravb9 = list(
      B = correct_18,
      C = correct_7,
      D = correct_7
    ),
    ravbmis = list(
      B = no_valid_data_interview_broken_off,
      C = na_see_c_drmcrav_in_lasac_d_e222,
      D = na_see_c_drmcrav_in_lasac_d_e222
    ),
    mraabmis = list(
      E = na_see_e_f_gmrmcrav_in_lasaf_g222,
      F = na_see_e_f_gmrmcrav_in_lasaf_g222,
      G = na_see_e_f_gmrmcrav_in_lasaf_g222
    ),
    mravamis = list(
      E = na_see_e_f_gmrmcrav_in_lasaf_g222,
      F = na_see_e_f_gmrmcrav_in_lasaf_g222,
      G = na_see_e_f_gmrmcrav_in_lasaf_g222
    ),
    mravbmis = list(
      E = na_see_e_f_gmrmcrav_in_lasaf_g222,
      F = na_see_e_f_gmrmcrav_in_lasaf_g222,
      G = na_see_e_f_gmrmcrav_in_lasaf_g222
    )
  ),

  value_labels_harmonized = list(
    mraabmis = not_available_routing,
    mrava1 = correct_24,
    mrava10 = correct_25,
    mrava11 = correct_24,
    mrava12 = correct_26,
    mrava2 = correct_26,
    mrava3 = correct_27,
    mrava4 = correct_28,
    mrava5 = correct_29,
    mrava6 = correct_25,
    mrava7 = correct_29,
    mrava8 = correct_28,
    mrava9 = correct_27,
    mravamis = not_available_routing,
    mravb1 = correct_28,
    mravb10 = correct_25,
    mravb11 = correct_24,
    mravb12 = correct_26,
    mravb2 = correct_29,
    mravb3 = correct_27,
    mravb4 = correct_28,
    mravb5 = correct_27,
    mravb6 = correct_25,
    mravb7 = correct_26,
    mravb8 = correct_29,
    mravb9 = correct_24,
    mravbmis = not_available_routing,
    raabmis = not_available_no_valid_data,
    rava1 = correct_30,
    rava10 = correct_31,
    rava11 = correct_30,
    rava12 = correct_32,
    rava2 = correct_32,
    rava3 = correct_33,
    rava4 = correct_34,
    rava5 = correct_35,
    rava6 = correct_31,
    rava7 = correct_35,
    rava8 = correct_34,
    rava9 = correct_33,
    ravamis = not_available_no_valid_data,
    ravb1 = correct_34,
    ravb10 = correct_31,
    ravb11 = correct_30,
    ravb12 = correct_32,
    ravb2 = correct_35,
    ravb3 = correct_33,
    ravb4 = correct_34,
    ravb5 = correct_33,
    ravb6 = correct_31,
    ravb7 = correct_32,
    ravb8 = correct_35,
    ravb9 = correct_30,
    ravbmis = not_available_no_valid_data
  )
)
