## LASA filecode 073 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_073 <- list(
  variables = data.frame(
    wave = c(
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "blo1",
      "blo10",
      "blo11",
      "blo2",
      "blo3",
      "blo4",
      "blo5",
      "blo6",
      "blo7",
      "blo8",
      "blo9",
      "blorat",
      "blosom",
      "blo1",
      "blo10",
      "blo11",
      "blo2",
      "blo3",
      "blo4",
      "blo5",
      "blo6",
      "blo7",
      "blo8",
      "blo9",
      "blo_mode",
      "clo1",
      "clo10",
      "clo11",
      "clo2",
      "clo3",
      "clo4",
      "clo5",
      "clo6",
      "clo7",
      "clo8",
      "clo9",
      "dlo1",
      "dlo10",
      "dlo11",
      "dlo2",
      "dlo3",
      "dlo4",
      "dlo5",
      "dlo6",
      "dlo7",
      "dlo8",
      "dlo9",
      "elo1",
      "elo10",
      "elo11",
      "elo2",
      "elo3",
      "elo4",
      "elo5",
      "elo6",
      "elo7",
      "elo8",
      "elo9",
      "flo1",
      "flo10",
      "flo11",
      "flo2",
      "flo3",
      "flo4",
      "flo5",
      "flo6",
      "flo7",
      "flo8",
      "flo9",
      "florat",
      "flosom",
      "glo1",
      "glo10",
      "glo11",
      "glo2",
      "glo3",
      "glo4",
      "glo5",
      "glo6",
      "glo7",
      "glo8",
      "glo9",
      "glorat",
      "glosom",
      "hlo1",
      "hlo10",
      "hlo11",
      "hlo2",
      "hlo3",
      "hlo4",
      "hlo5",
      "hlo6",
      "hlo7",
      "hlo8",
      "hlo9",
      "hlorat",
      "hlosom",
      "ilo1",
      "ilo10",
      "ilo11",
      "ilo2",
      "ilo3",
      "ilo4",
      "ilo5",
      "ilo6",
      "ilo7",
      "ilo8",
      "ilo9",
      "ilorat",
      "ilosom",
      "blo1",
      "blo10",
      "blo11",
      "blo2",
      "blo3",
      "blo4",
      "blo5",
      "blo6",
      "blo7",
      "blo8",
      "blo9",
      "blorat",
      "blosom"
    ),
    canonical_name = c(
      "lo1",
      "lo10",
      "lo11",
      "lo2",
      "lo3",
      "lo4",
      "lo5",
      "lo6",
      "lo7",
      "lo8",
      "lo9",
      "lorat",
      "losom",
      "lo1",
      "lo10",
      "lo11",
      "lo2",
      "lo3",
      "lo4",
      "lo5",
      "lo6",
      "lo7",
      "lo8",
      "lo9",
      "lo_mode",
      "lo1",
      "lo10",
      "lo11",
      "lo2",
      "lo3",
      "lo4",
      "lo5",
      "lo6",
      "lo7",
      "lo8",
      "lo9",
      "lo1",
      "lo10",
      "lo11",
      "lo2",
      "lo3",
      "lo4",
      "lo5",
      "lo6",
      "lo7",
      "lo8",
      "lo9",
      "lo1",
      "lo10",
      "lo11",
      "lo2",
      "lo3",
      "lo4",
      "lo5",
      "lo6",
      "lo7",
      "lo8",
      "lo9",
      "lo1",
      "lo10",
      "lo11",
      "lo2",
      "lo3",
      "lo4",
      "lo5",
      "lo6",
      "lo7",
      "lo8",
      "lo9",
      "lorat",
      "losom",
      "lo1",
      "lo10",
      "lo11",
      "lo2",
      "lo3",
      "lo4",
      "lo5",
      "lo6",
      "lo7",
      "lo8",
      "lo9",
      "lorat",
      "losom",
      "lo1",
      "lo10",
      "lo11",
      "lo2",
      "lo3",
      "lo4",
      "lo5",
      "lo6",
      "lo7",
      "lo8",
      "lo9",
      "lorat",
      "losom",
      "lo1",
      "lo10",
      "lo11",
      "lo2",
      "lo3",
      "lo4",
      "lo5",
      "lo6",
      "lo7",
      "lo8",
      "lo9",
      "lorat",
      "losom",
      "lo1",
      "lo10",
      "lo11",
      "lo2",
      "lo3",
      "lo4",
      "lo5",
      "lo6",
      "lo7",
      "lo8",
      "lo9",
      "lorat",
      "losom"
    ),
    variable_label = c(
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      NA_character_,
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam"
    ),
    harmonized_var_label = c(
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      NA_character_,
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam",
      "There is always someone I can talk to about my day-to-day problems / Er is altijd wel iemand in mijn omgeving bij wie ik met mijn dagelijkse probleempjes terecht kan",
      "I often feel rejected / Vaak voel ik me in de steek gelaten",
      "I can call on my friends whenever I need them / Wanneer ik daar behoefte aan heb kan ik altijd bij mijn vrienden terecht",
      "I miss having a really close friend / Ik mis een echt goede vriend of vriendin",
      "I experience a general sense of emptiness / Ik ervaar een leegte om me heen",
      "There are plenty of people I can lean on when I have problems / Er zijn genoeg mensen op wie ik in geval van narigheid kan terugvallen",
      "I miss the pleasure of the company of others / Ik mis gezelligheid om me heen",
      "I find my circle of friends and acquaintances too limited / Ik vind mijn kring van kennissen te beperkt",
      "There are many people I can trust completely / Ik heb veel mensen op wie ik volledig kan vertrouwen",
      "There are enough people I feel close to / Er zijn voldoende mensen met wie ik me nauw verbonden voel",
      "I miss having people around me / Ik mis mensen om me heen",
      "I am among the not-moderate-severe-extreme lonely people / Als we de mensen zouden indelen in: niet eenzaam, matig eenzaam, sterk eenzaam, zeer sterk eenzaam, waar zou u zich dan nu toe rekenen?",
      "I sometimes feel lonely / Ik voel me soms wel eens eenzaam"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    lo1 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo10 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo11 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo2 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo3 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo4 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo5 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo6 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo7 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo8 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo9 = list(
      `3B` = no_more_or_less_yes,
      B = no_more_or_less_yes,
      C = no_more_or_less_yes,
      D = no_more_or_less_yes,
      E = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lorat = list(
      `3B` = not_lonely_niet_eenzaam_moderately_lonely_sterk_eenzaam,
      F = not_lonely_niet_eenzaam_moderately_lonely_sterk_eenzaam,
      G = not_lonely_niet_eenzaam_moderately_lonely_sterk_eenzaam,
      H = not_lonely_niet_eenzaam_moderately_lonely_sterk_eenzaam,
      I = not_lonely_niet_eenzaam_moderately_lonely_sterk_eenzaam,
      MB = not_lonely_niet_eenzaam_moderately_lonely_sterk_eenzaam
    ),
    losom = list(
      `3B` = no_more_or_less_yes,
      F = no_more_or_less_yes,
      G = no_more_or_less_yes,
      H = no_more_or_less_yes,
      I = no_more_or_less_yes,
      MB = no_more_or_less_yes
    ),
    lo_mode = list(
      B = c(
        `-5` = "computer or paper-and-pencil short version",
        `-4` = "refusal/skip by Interviewer",
        `-3` = "terminated interview",
        `1` = "computer",
        `2` = "paper-and-pencil"
      )
    )
  ),

  value_labels_harmonized = list(
    lo1 = no_more_or_less_yes_2,
    lo10 = no_more_or_less_yes_2,
    lo11 = no_more_or_less_yes_2,
    lo2 = no_more_or_less_yes_2,
    lo3 = no_more_or_less_yes_2,
    lo4 = no_more_or_less_yes_2,
    lo5 = no_more_or_less_yes_2,
    lo6 = no_more_or_less_yes_2,
    lo7 = no_more_or_less_yes_2,
    lo8 = no_more_or_less_yes_2,
    lo9 = no_more_or_less_yes_2,
    lo_mode = c(
      `-5` = "computer or paper-and-pencil short interview",
      `-4` = "refusal/skip by interviewernterviewer",
      `-3` = "interview terminated",
      `1` = "computer",
      `2` = "paper-and-pencil"
    ),
    lorat = c(
      `-4` = "refusal/skip by interviewernterviewer",
      `-3` = "not asked (interview terminated)",
      `-1` = "no answer",
      `1` = "not lonely/niet eenzaam",
      `2` = "moderately lonely/sterk eenzaam",
      `3` = "severely lonely/sterk eenzaam",
      `4` = "extremely lonely/zeer sterk eenzaam"
    ),
    losom = no_more_or_less_yes_2
  )
)
