## LASA filecode 044 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_044 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "blst1c01",
      "blst1c02",
      "blst1c03",
      "blst1c04",
      "blst1c05",
      "blst1c06",
      "blst1c07",
      "blst1c08",
      "blst1c09",
      "blst1c10",
      "blst1c11",
      "blst1c12",
      "blst1c13",
      "blst1c14",
      "blst1c15",
      "blst1c16",
      "blst1c17",
      "blst1c18",
      "blst1c19",
      "blst2c01",
      "blst2c02",
      "blst2c03",
      "blst2c04",
      "blst2c05",
      "blst2c06",
      "blst2c07",
      "blst2c08",
      "blst2c09",
      "blst2c10",
      "blst2c11",
      "blst2c12",
      "blst2c13",
      "blst2c14",
      "blst2c15",
      "blst2k09",
      "blst1c01",
      "blst1c02",
      "blst1c03",
      "blst1c04",
      "blst1c05",
      "blst1c06",
      "blst1c07",
      "blst1c08",
      "blst1c09",
      "blst1c10",
      "blst1c11",
      "blst1c12",
      "blst1c13",
      "blst1c14",
      "blst1c16",
      "blst1c17",
      "blst1c19",
      "blst1c1n",
      "blst2c01",
      "blst2c02",
      "blst2c03",
      "blst2c04",
      "blst2c05",
      "blst2c06",
      "blst2c07",
      "blst2c08",
      "blst2c09",
      "blst2c10",
      "blst2c11",
      "blst2c12",
      "blst2c13",
      "blst2c14",
      "blst2c15",
      "blst1c01",
      "blst1c02",
      "blst1c03",
      "blst1c04",
      "blst1c05",
      "blst1c06",
      "blst1c07",
      "blst1c08",
      "blst1c09",
      "blst1c10",
      "blst1c11",
      "blst1c12",
      "blst1c13",
      "blst1c14",
      "blst1c15",
      "blst1c16",
      "blst1c17",
      "blst1c18",
      "blst1c19",
      "blst1k01",
      "blst1k02",
      "blst1k03",
      "blst1k04",
      "blst1k05",
      "blst1k06",
      "blst1k07",
      "blst1k08",
      "blst1k09",
      "blst1k10",
      "blst1k11",
      "blst1k12",
      "blst1k13",
      "blst1k14",
      "blst1k15",
      "blst1k16",
      "blst1k17",
      "blst1k18",
      "blst1k19",
      "blst2c01",
      "blst2c02",
      "blst2c03",
      "blst2c04",
      "blst2c05",
      "blst2c06",
      "blst2c07",
      "blst2c08",
      "blst2c09",
      "blst2c10",
      "blst2c11",
      "blst2c12",
      "blst2c13",
      "blst2c14",
      "blst2c15",
      "blst2k01",
      "blst2k02",
      "blst2k03",
      "blst2k04",
      "blst2k05",
      "blst2k06",
      "blst2k07",
      "blst2k08",
      "blst2k09",
      "blst2k10",
      "blst2k11",
      "blst2k12",
      "blst2k13",
      "blst2k14",
      "blst2k15",
      "clst1c01",
      "clst1c02",
      "clst1c03",
      "clst1c04",
      "clst1c05",
      "clst1c06",
      "clst1c07",
      "clst1c08",
      "clst1c09",
      "clst1c10",
      "clst1c11",
      "clst1c12",
      "clst1c13",
      "clst1c14",
      "clst1c15",
      "clst1c16",
      "clst1c17",
      "clst1c18",
      "clst1c19",
      "clst2c01",
      "clst2c02",
      "clst2c03",
      "clst2c04",
      "clst2c05",
      "clst2c06",
      "clst2c07",
      "clst2c08",
      "clst2c09",
      "clst2c10",
      "clst2c11",
      "clst2c12",
      "clst2c13",
      "clst2c14",
      "clst2c15",
      "clst2k09",
      "dlst1c01",
      "dlst1c02",
      "dlst1c03",
      "dlst1c04",
      "dlst1c05",
      "dlst1c06",
      "dlst1c07",
      "dlst1c08",
      "dlst1c09",
      "dlst1c10",
      "dlst1c11",
      "dlst1c12",
      "dlst1c13",
      "dlst1c14",
      "dlst1c15",
      "dlst1c16",
      "dlst1c17",
      "dlst1c18",
      "dlst1c19",
      "dlst2c01",
      "dlst2c02",
      "dlst2c03",
      "dlst2c04",
      "dlst2c05",
      "dlst2c06",
      "dlst2c07",
      "dlst2c08",
      "dlst2c09",
      "dlst2c10",
      "dlst2c11",
      "dlst2c12",
      "dlst2c13",
      "dlst2c14",
      "dlst2c15",
      "dlst2k09",
      "elst1c01",
      "elst1c02",
      "elst1c03",
      "elst1c04",
      "elst1c05",
      "elst1c06",
      "elst1c07",
      "elst1c08",
      "elst1c09",
      "elst1c10",
      "elst1c11",
      "elst1c12",
      "elst1c13",
      "elst1c14",
      "elst1c15",
      "elst1c16",
      "elst1c17",
      "elst1c18",
      "elst1c19",
      "elst2c01",
      "elst2c02",
      "elst2c03",
      "elst2c04",
      "elst2c05",
      "elst2c06",
      "elst2c07",
      "elst2c08",
      "elst2c09",
      "elst2c10",
      "elst2c11",
      "elst2c12",
      "elst2c13",
      "elst2c14",
      "elst2c15",
      "elst2k09",
      "flst1c01",
      "flst1c02",
      "flst1c03",
      "flst1c04",
      "flst1c05",
      "flst1c06",
      "flst1c07",
      "flst1c08",
      "flst1c09",
      "flst1c10",
      "flst1c11",
      "flst1c12",
      "flst1c13",
      "flst1c14",
      "flst1c15",
      "flst1c16",
      "flst1c17",
      "flst1c18",
      "flst1c19",
      "flst2c01",
      "flst2c02",
      "flst2c03",
      "flst2c04",
      "flst2c05",
      "flst2c06",
      "flst2c07",
      "flst2c08",
      "flst2c09",
      "flst2c10",
      "flst2c11",
      "flst2c12",
      "flst2c13",
      "flst2c14",
      "flst2c15",
      "flst2k09",
      "glst1c01",
      "glst1c02",
      "glst1c03",
      "glst1c04",
      "glst1c05",
      "glst1c06",
      "glst1c07",
      "glst1c08",
      "glst1c09",
      "glst1c10",
      "glst1c11",
      "glst1c12",
      "glst1c13",
      "glst1c14",
      "glst1c15",
      "glst1c16",
      "glst1c17",
      "glst1c18",
      "glst1c19",
      "glst1c1n",
      "glst2c01",
      "glst2c02",
      "glst2c03",
      "glst2c04",
      "glst2c05",
      "glst2c06",
      "glst2c07",
      "glst2c08",
      "glst2c09",
      "glst2c10",
      "glst2c11",
      "glst2c12",
      "glst2c13",
      "glst2c14",
      "glst2c15",
      "glst2k09",
      "hlst1c01",
      "hlst1c02",
      "hlst1c03",
      "hlst1c04",
      "hlst1c05",
      "hlst1c06",
      "hlst1c07",
      "hlst1c08",
      "hlst1c09",
      "hlst1c10",
      "hlst1c11",
      "hlst1c12",
      "hlst1c13",
      "hlst1c14",
      "hlst1c16",
      "hlst1c17",
      "hlst1c19",
      "hlst1c1n",
      "hlst2c01",
      "hlst2c02",
      "hlst2c03",
      "hlst2c04",
      "hlst2c05",
      "hlst2c06",
      "hlst2c07",
      "hlst2c08",
      "hlst2c09",
      "hlst2c10",
      "hlst2c11",
      "hlst2c12",
      "hlst2c13",
      "hlst2c14",
      "hlst2c15",
      "Ilst2c06",
      "ilst1c01",
      "ilst1c02",
      "ilst1c03",
      "ilst1c04",
      "ilst1c08",
      "ilst1c09",
      "ilst1c10",
      "ilst1c11",
      "ilst1c12",
      "ilst1c13",
      "ilst1c14",
      "ilst1c16",
      "ilst1c17",
      "ilst1c18",
      "ilst1c19",
      "ilst1c1n",
      "ilst2c01",
      "ilst2c02",
      "ilst2c03",
      "ilst2c04",
      "ilst2c20",
      "ilst2c21",
      "Jlst2c06",
      "jlst1c01",
      "jlst1c02",
      "jlst1c03",
      "jlst1c04",
      "jlst1c08",
      "jlst1c09",
      "jlst1c10",
      "jlst1c11",
      "jlst1c12",
      "jlst1c13",
      "jlst1c14",
      "jlst1c16",
      "jlst1c17",
      "jlst1c18",
      "jlst1c19",
      "jlst1c1n",
      "jlst2c01",
      "jlst2c02",
      "jlst2c03",
      "jlst2c04",
      "jlst2c20",
      "bfac1",
      "bfac2",
      "bfac3",
      "bfacil",
      "blst1c01",
      "blst1c02",
      "blst1c03",
      "blst1c04",
      "blst1c12",
      "blst1c14",
      "blst1c16",
      "blst1c17",
      "blst1c1n",
      "blst2c01",
      "blst2c02",
      "blst2c06"
    ),
    canonical_name = c(
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c05",
      "lst1c06",
      "lst1c07",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c15",
      "lst1c16",
      "lst1c17",
      "lst1c18",
      "lst1c19",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c05",
      "lst2c06",
      "lst2c07",
      "lst2c08",
      "lst2c09",
      "lst2c10",
      "lst2c11",
      "lst2c12",
      "lst2c13",
      "lst2c14",
      "lst2c15",
      "lst2k09",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c05",
      "lst1c06",
      "lst1c07",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c16",
      "lst1c17",
      "lst1c19",
      "lst1c1n",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c05",
      "lst2c06",
      "lst2c07",
      "lst2c08",
      "lst2c09",
      "lst2c10",
      "lst2c11",
      "lst2c12",
      "lst2c13",
      "lst2c14",
      "lst2c15",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c05",
      "lst1c06",
      "lst1c07",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c15",
      "lst1c16",
      "lst1c17",
      "lst1c18",
      "lst1c19",
      "lst1k01",
      "lst1k02",
      "lst1k03",
      "lst1k04",
      "lst1k05",
      "lst1k06",
      "lst1k07",
      "lst1k08",
      "lst1k09",
      "lst1k10",
      "lst1k11",
      "lst1k12",
      "lst1k13",
      "lst1k14",
      "lst1k15",
      "lst1k16",
      "lst1k17",
      "lst1k18",
      "lst1k19",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c05",
      "lst2c06",
      "lst2c07",
      "lst2c08",
      "lst2c09",
      "lst2c10",
      "lst2c11",
      "lst2c12",
      "lst2c13",
      "lst2c14",
      "lst2c15",
      "lst2k01",
      "lst2k02",
      "lst2k03",
      "lst2k04",
      "lst2k05",
      "lst2k06",
      "lst2k07",
      "lst2k08",
      "lst2k09",
      "lst2k10",
      "lst2k11",
      "lst2k12",
      "lst2k13",
      "lst2k14",
      "lst2k15",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c05",
      "lst1c06",
      "lst1c07",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c15",
      "lst1c16",
      "lst1c17",
      "lst1c18",
      "lst1c19",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c05",
      "lst2c06",
      "lst2c07",
      "lst2c08",
      "lst2c09",
      "lst2c10",
      "lst2c11",
      "lst2c12",
      "lst2c13",
      "lst2c14",
      "lst2c15",
      "lst2k09",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c05",
      "lst1c06",
      "lst1c07",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c15",
      "lst1c16",
      "lst1c17",
      "lst1c18",
      "lst1c19",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c05",
      "lst2c06",
      "lst2c07",
      "lst2c08",
      "lst2c09",
      "lst2c10",
      "lst2c11",
      "lst2c12",
      "lst2c13",
      "lst2c14",
      "lst2c15",
      "lst2k09",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c05",
      "lst1c06",
      "lst1c07",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c15",
      "lst1c16",
      "lst1c17",
      "lst1c18",
      "lst1c19",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c05",
      "lst2c06",
      "lst2c07",
      "lst2c08",
      "lst2c09",
      "lst2c10",
      "lst2c11",
      "lst2c12",
      "lst2c13",
      "lst2c14",
      "lst2c15",
      "lst2k09",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c05",
      "lst1c06",
      "lst1c07",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c15",
      "lst1c16",
      "lst1c17",
      "lst1c18",
      "lst1c19",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c05",
      "lst2c06",
      "lst2c07",
      "lst2c08",
      "lst2c09",
      "lst2c10",
      "lst2c11",
      "lst2c12",
      "lst2c13",
      "lst2c14",
      "lst2c15",
      "lst2k09",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c05",
      "lst1c06",
      "lst1c07",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c15",
      "lst1c16",
      "lst1c17",
      "lst1c18",
      "lst1c19",
      "lst1c1n",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c05",
      "lst2c06",
      "lst2c07",
      "lst2c08",
      "lst2c09",
      "lst2c10",
      "lst2c11",
      "lst2c12",
      "lst2c13",
      "lst2c14",
      "lst2c15",
      "lst2k09",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c05",
      "lst1c06",
      "lst1c07",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c16",
      "lst1c17",
      "lst1c19",
      "lst1c1n",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c05",
      "lst2c06",
      "lst2c07",
      "lst2c08",
      "lst2c09",
      "lst2c10",
      "lst2c11",
      "lst2c12",
      "lst2c13",
      "lst2c14",
      "lst2c15",
      "lst2c06",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c16",
      "lst1c17",
      "lst1c18",
      "lst1c19",
      "lst1c1n",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c20",
      "lst2c21",
      "lst2c06",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c08",
      "lst1c09",
      "lst1c10",
      "lst1c11",
      "lst1c12",
      "lst1c13",
      "lst1c14",
      "lst1c16",
      "lst1c17",
      "lst1c18",
      "lst1c19",
      "lst1c1n",
      "lst2c01",
      "lst2c02",
      "lst2c03",
      "lst2c04",
      "lst2c20",
      "fac1",
      "fac2",
      "fac3",
      "facil",
      "lst1c01",
      "lst1c02",
      "lst1c03",
      "lst1c04",
      "lst1c12",
      "lst1c14",
      "lst1c16",
      "lst1c17",
      "lst1c1n",
      "lst2c01",
      "lst2c02",
      "lst2c06"
    ),
    variable_label = c(
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Home nurs serv/distr. nurs",
      "Cont. p 6 mo. Home help",
      "Cont. p 6 mo. Alpha help",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior service",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circle",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers UVV",
      "Cont. p 6 mo. Volunteers Zonnebloem",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Red Cross",
      "Cont. p 6 mo. Memorytraining",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Socio-psychogeriatric service (SPGD)",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Indication commission",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Nursing home-admission",
      "Cont. p 6 mo. Nursing home-observation",
      "Cont. p 6 mo. Nursing home-overnight stay",
      "Cont. p 6 mo. Nursing home-day care",
      "Cont. p 6 mo. Res home - day care",
      "Cont. p 6 mo. Res home - temporary admission",
      "Cont. p 6 mo. Res home - overnight stay",
      "Cont. p 6 mo. Res home - meals",
      "Cont. p 6 mo. Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Home nurse /district nurse",
      "Cont. p 6 mo. Home help",
      "Cont. p 6 mo. Alpha help",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior service",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circle",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers organisation, namely ...",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Memorytraining",
      "Cont. family physician: number of times",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Socio-psychogeriatric service (SPGD)",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Indication commission",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Nursing home-admission",
      "Cont. p 6 mo. Nursing home-observation",
      "Cont. p 6 mo. Nursing home-overnight stay",
      "Cont. p 6 mo. Nursing home-day care",
      "Cont. p 6 mo. Res home - day care",
      "Cont. p 6 mo. Res home - temporary admission",
      "Cont. p 6 mo. Res home - overnight stay",
      "Cont. p 6 mo. Res home - meals",
      "Cont. p 6 mo. Res home - social/creative activities",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Home nurs serv/distr. nurs",
      "Cont. p 6 mo. Home help",
      "Cont. p 6 mo. Alpha help",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior serv.",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circel",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers UVV",
      "Cont. p 6 mo. Volunteers Zonnebloem",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Red Cross",
      "Cont. p 6 mo. Memorytraining",
      "Know. Family physican",
      "Know. Dentist",
      "Know. Physiotherapist",
      "Know. Dietician",
      "Know. Home nursing services/district nur",
      "Know. Home help",
      "Know. Alpha help",
      "Know. Social work",
      "Know. Coordinated senior services",
      "Know. Telephonic help service",
      "Know. Telephone circel",
      "Know. Meals on wheels",
      "Know. Open eettafel",
      "Know. Volunteers UVV",
      "Know. volunteers Zonnebloem",
      "Know. Transportation service",
      "Know. Chores Service",
      "Know. Red Cross",
      "Know. Memory training",
      "Cont. p 6 mo. Cons offi. alcohol&drugs",
      "Cont. p 6 mo. Comm mental health care",
      "Cont. p 6 mo. Socio-psychiat. serv.(SPGD",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Indication commission",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Nursing home-admission",
      "Cont. p 6 mo. Nursing home-observation",
      "Cont. p 6 mo. Nursing home-overnight stay",
      "Cont. p 6 mo. Nursing home-day care",
      "Cont. p 6 mo. Res home - day care",
      "Cont. p 6 mo. Res home - temp. admission",
      "Cont. p 6 mo. Res home - overnight stay",
      "Cont. p 6 mo. Res home - meals",
      "Cont. p 6 mo. Res home - soci./creative",
      "Know. Cons. Office for alcohol and drugs",
      "Know. Comm Mental Health Care",
      "Know. Socio-Psychiatric service (SPGD)",
      "Know. Rehabilitation center",
      "Know. Admission team residental care",
      "Know. Alternative practitioner",
      "Know. Nursing home - admission",
      "Know. Nursing home - observation",
      "Know. Nursing home - overnight stay",
      "Know. Nursing home - day care",
      "Know. Residential home - day care",
      "Know. Residential home - temporary admis",
      "Know. Residential home - overnight stay",
      "Know. Residential home - meals",
      "Know. Residential home - social or creative",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Home nurs serv/distr. nurs",
      "Cont. p 6 mo. Home help",
      "Cont. p 6 mo. Alpha help",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior service",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circle",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers UVV",
      "Cont. p 6 mo. Volunteers Zonnebloem",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Red Cross",
      "Cont. p 6 mo. Memorytraining",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Socio-psychogeriatric service (SPGD)",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Indication commission",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Nursing home-admission",
      "Cont. p 6 mo. Nursing home-observation",
      "Cont. p 6 mo. Nursing home-overnight stay",
      "Cont. p 6 mo. Nursing home-day care",
      "Cont. p 6 mo. Res home - day care",
      "Cont. p 6 mo. Res home - temporary admission",
      "Cont. p 6 mo. Res home - overnight stay",
      "Cont. p 6 mo. Res home - meals",
      "Cont. p 6 mo. Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Home nurs serv/distr. nurs",
      "Cont. p 6 mo. Home help",
      "Cont. p 6 mo. Alpha help",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior service",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circle",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers UVV",
      "Cont. p 6 mo. Volunteers Zonnebloem",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Red Cross",
      "Cont. p 6 mo. Memorytraining",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Socio-psychogeriatric service (SPGD)",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Indication commission",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Nursing home-admission",
      "Cont. p 6 mo. Nursing home-observation",
      "Cont. p 6 mo. Nursing home-overnight stay",
      "Cont. p 6 mo. Nursing home-day care",
      "Cont. p 6 mo. Res home - day care",
      "Cont. p 6 mo. Res home - temporary admission",
      "Cont. p 6 mo. Res home - overnight stay",
      "Cont. p 6 mo. Res home - meals",
      "Cont. p 6 mo. Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Home nurs serv/distr. nurs",
      "Cont. p 6 mo. Home help",
      "Cont. p 6 mo. Alpha help",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior service",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circle",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers UVV",
      "Cont. p 6 mo. Volunteers Zonnebloem",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Red Cross",
      "Cont. p 6 mo. Memorytraining",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Socio-psychogeriatric service (SPGD)",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Indication commission",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Nursing home-admission",
      "Cont. p 6 mo. Nursing home-observation",
      "Cont. p 6 mo. Nursing home-overnight stay",
      "Cont. p 6 mo. Nursing home-day care",
      "Cont. p 6 mo. Res home - day care",
      "Cont. p 6 mo. Res home - temporary admission",
      "Cont. p 6 mo. Res home - overnight stay",
      "Cont. p 6 mo. Res home - meals",
      "Cont. p 6 mo. Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Home nurs serv/distr. nurs",
      "Cont. p 6 mo. Home help",
      "Cont. p 6 mo. Alpha help",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior service",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circle",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers UVV",
      "Cont. p 6 mo. Volunteers Zonnebloem",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Red Cross",
      "Cont. p 6 mo. Memorytraining",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Socio-psychogeriatric service (SPGD)",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Indication commission",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Nursing home-admission",
      "Cont. p 6 mo. Nursing home-observation",
      "Cont. p 6 mo. Nursing home-overnight stay",
      "Cont. p 6 mo. Nursing home-day care",
      "Cont. p 6 mo. Res home - day care",
      "Cont. p 6 mo. Res home - temporary admission",
      "Cont. p 6 mo. Res home - overnight stay",
      "Cont. p 6 mo. Res home - meals",
      "Cont. p 6 mo. Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Home nurs serv/distr. nurs",
      "Cont. p 6 mo. Home help",
      "Cont. p 6 mo. Alpha help",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior service",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circle",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers UVV",
      "Cont. p 6 mo. Volunteers Zonnebloem",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Red Cross",
      "Cont. p 6 mo. Memorytraining",
      "Cont. family physician: number of times",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Socio-psychogeriatric service (SPGD)",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Indication commission",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Nursing home-admission",
      "Cont. p 6 mo. Nursing home-observation",
      "Cont. p 6 mo. Nursing home-overnight stay",
      "Cont. p 6 mo. Nursing home-day care",
      "Cont. p 6 mo. Res home - day care",
      "Cont. p 6 mo. Res home - temporary admission",
      "Cont. p 6 mo. Res home - overnight stay",
      "Cont. p 6 mo. Res home - meals",
      "Cont. p 6 mo. Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Home nurse /district nurse",
      "Cont. p 6 mo. Home help",
      "Cont. p 6 mo. Alpha help",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior service",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circle",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers organisation, namely ...",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Memorytraining",
      "Cont. family physician: number of times",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Socio-psychogeriatric service (SPGD)",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Indication commission",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Nursing home-admission",
      "Cont. p 6 mo. Nursing home-observation",
      "Cont. p 6 mo. Nursing home-overnight stay",
      "Cont. p 6 mo. Nursing home-day care",
      "Cont. p 6 mo. Res home - day care",
      "Cont. p 6 mo. Res home - temporary admission",
      "Cont. p 6 mo. Res home - overnight stay",
      "Cont. p 6 mo. Res home - meals",
      "Cont. p 6 mo. Res home - social/creative activities",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior service",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circle",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers organisation, namely ...",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Red Cross",
      "Cont. p 6 mo. Memorytraining",
      "Cont. family physician: number of times",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Socio-psychogeriatric service (SPGD)",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Social alarm",
      "Cont. p 6 mo. Daycare: social/creative activities in group",
      "Cont. p 6 mo. Alternative practitioner",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Social work",
      "Cont. p 6 mo. Coordinated senior service",
      "Cont. p 6 mo. Telephonic help service",
      "Cont. p 6 mo. Telephone circle",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Open table (food)",
      "Cont. p 6 mo. Volunteers organisation, namely ...",
      "Cont. p 6 mo. Transportation service",
      "Cont. p 6 mo. Chores service",
      "Cont. p 6 mo. Red Cross",
      "Cont. p 6 mo. Memorytraining",
      "Cont. family physician: number of times",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Socio-psychogeriatric service (SPGD)",
      "Cont. p 6 mo. Rehabilitation center",
      "Cont. p 6 mo. Social alarm",
      "Facility 1: walker or a walking frame",
      "Facility 2: (sports) wheelchair",
      "Facility 3: mobility scooter",
      "Having facilities for disabled persons",
      "Cont. p 6 mo. Family physician",
      "Cont. p 6 mo. Dentist",
      "Cont. p 6 mo. Physiotherapist",
      "Cont. p 6 mo. Dietician",
      "Cont. p 6 mo. Meals on wheels",
      "Cont. p 6 mo. Volunteers organisation",
      "Cont. p 6 mo Transport services",
      "Cont. p 6 mo. Chores service",
      "Cont. family physician: number of times",
      "Cont. p 6 mo. Consultation office alcohol&drugs",
      "Cont. p 6 mo. Common mental health care",
      "Cont. p 6 mo. Alternative practitioner"
    ),
    harmonized_var_label = c(
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Home nurs serv/distr. nurs",
      "Cont. past 6 monthsnths Home help",
      "Cont. past 6 monthsnths Alpha help",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Volunteers Zonnebloem",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Red Cross",
      "Cont. past 6 monthsnths Memorytraining",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Indication commission",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Nursing home-admission",
      "Cont. past 6 monthsnths Nursing home-observation",
      "Cont. past 6 monthsnths Nursing home-overnight stay",
      "Cont. past 6 monthsnths Nursing home-day care",
      "Cont. past 6 monthsnths Res home - day care",
      "Cont. past 6 monthsnths Res home - temporary admission",
      "Cont. past 6 monthsnths Res home - overnight stay",
      "Cont. past 6 monthsnths Res home - meals",
      "Cont. past 6 monthsnths Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Home nurs serv/distr. nurs",
      "Cont. past 6 monthsnths Home help",
      "Cont. past 6 monthsnths Alpha help",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Memorytraining",
      "Cont. family physician: number of times",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Indication commission",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Nursing home-admission",
      "Cont. past 6 monthsnths Nursing home-observation",
      "Cont. past 6 monthsnths Nursing home-overnight stay",
      "Cont. past 6 monthsnths Nursing home-day care",
      "Cont. past 6 monthsnths Res home - day care",
      "Cont. past 6 monthsnths Res home - temporary admission",
      "Cont. past 6 monthsnths Res home - overnight stay",
      "Cont. past 6 monthsnths Res home - meals",
      "Cont. past 6 monthsnths Res home - social/creative activities",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Home nurs serv/distr. nurs",
      "Cont. past 6 monthsnths Home help",
      "Cont. past 6 monthsnths Alpha help",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Volunteers Zonnebloem",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Red Cross",
      "Cont. past 6 monthsnths Memorytraining",
      "Know. Family physican",
      "Know. Dentist",
      "Know. Physiotherapist",
      "Know. Dietician",
      "Know. Home nursing services/district nur",
      "Know. Home help",
      "Know. Alpha help",
      "Know. Social work",
      "Know. Coordinated senior services",
      "Know. Telephonic help service",
      "Know. Telephone circel",
      "Know. Meals on wheels",
      "Know. Open eettafel",
      "Know. Volunteers UVV",
      "Know. volunteers Zonnebloem",
      "Know. Transportation service",
      "Know. Chores Service",
      "Know. Red Cross",
      "Know. Memory training",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Indication commission",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Nursing home-admission",
      "Cont. past 6 monthsnths Nursing home-observation",
      "Cont. past 6 monthsnths Nursing home-overnight stay",
      "Cont. past 6 monthsnths Nursing home-day care",
      "Cont. past 6 monthsnths Res home - day care",
      "Cont. past 6 monthsnths Res home - temporary admission",
      "Cont. past 6 monthsnths Res home - overnight stay",
      "Cont. past 6 monthsnths Res home - meals",
      "Cont. past 6 monthsnths Res home - social/creative activities",
      "Know. Cons. Office for alcohol and drugs",
      "Know. Comm Mental Health Care",
      "Know. Socio-Psychiatric service (SPGD)",
      "Know. Rehabilitation center",
      "Know. Admission team residental care",
      "Know. Alternative practitioner",
      "Know. Nursing home - admission",
      "Know. Nursing home - observation",
      "Know. Nursing home - overnight stay",
      "Know. Nursing home - day care",
      "Know. Residential home - day care",
      "Know. Residential home - temporary admis",
      "Know. Residential home - overnight stay",
      "Know. Residential home - meals",
      "Know. Residential home - social or creative",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Home nurs serv/distr. nurs",
      "Cont. past 6 monthsnths Home help",
      "Cont. past 6 monthsnths Alpha help",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Volunteers Zonnebloem",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Red Cross",
      "Cont. past 6 monthsnths Memorytraining",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Indication commission",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Nursing home-admission",
      "Cont. past 6 monthsnths Nursing home-observation",
      "Cont. past 6 monthsnths Nursing home-overnight stay",
      "Cont. past 6 monthsnths Nursing home-day care",
      "Cont. past 6 monthsnths Res home - day care",
      "Cont. past 6 monthsnths Res home - temporary admission",
      "Cont. past 6 monthsnths Res home - overnight stay",
      "Cont. past 6 monthsnths Res home - meals",
      "Cont. past 6 monthsnths Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Home nurs serv/distr. nurs",
      "Cont. past 6 monthsnths Home help",
      "Cont. past 6 monthsnths Alpha help",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Volunteers Zonnebloem",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Red Cross",
      "Cont. past 6 monthsnths Memorytraining",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Indication commission",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Nursing home-admission",
      "Cont. past 6 monthsnths Nursing home-observation",
      "Cont. past 6 monthsnths Nursing home-overnight stay",
      "Cont. past 6 monthsnths Nursing home-day care",
      "Cont. past 6 monthsnths Res home - day care",
      "Cont. past 6 monthsnths Res home - temporary admission",
      "Cont. past 6 monthsnths Res home - overnight stay",
      "Cont. past 6 monthsnths Res home - meals",
      "Cont. past 6 monthsnths Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Home nurs serv/distr. nurs",
      "Cont. past 6 monthsnths Home help",
      "Cont. past 6 monthsnths Alpha help",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Volunteers Zonnebloem",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Red Cross",
      "Cont. past 6 monthsnths Memorytraining",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Indication commission",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Nursing home-admission",
      "Cont. past 6 monthsnths Nursing home-observation",
      "Cont. past 6 monthsnths Nursing home-overnight stay",
      "Cont. past 6 monthsnths Nursing home-day care",
      "Cont. past 6 monthsnths Res home - day care",
      "Cont. past 6 monthsnths Res home - temporary admission",
      "Cont. past 6 monthsnths Res home - overnight stay",
      "Cont. past 6 monthsnths Res home - meals",
      "Cont. past 6 monthsnths Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Home nurs serv/distr. nurs",
      "Cont. past 6 monthsnths Home help",
      "Cont. past 6 monthsnths Alpha help",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Volunteers Zonnebloem",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Red Cross",
      "Cont. past 6 monthsnths Memorytraining",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Indication commission",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Nursing home-admission",
      "Cont. past 6 monthsnths Nursing home-observation",
      "Cont. past 6 monthsnths Nursing home-overnight stay",
      "Cont. past 6 monthsnths Nursing home-day care",
      "Cont. past 6 monthsnths Res home - day care",
      "Cont. past 6 monthsnths Res home - temporary admission",
      "Cont. past 6 monthsnths Res home - overnight stay",
      "Cont. past 6 monthsnths Res home - meals",
      "Cont. past 6 monthsnths Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Home nurs serv/distr. nurs",
      "Cont. past 6 monthsnths Home help",
      "Cont. past 6 monthsnths Alpha help",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Volunteers Zonnebloem",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Red Cross",
      "Cont. past 6 monthsnths Memorytraining",
      "Cont. family physician: number of times",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Indication commission",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Nursing home-admission",
      "Cont. past 6 monthsnths Nursing home-observation",
      "Cont. past 6 monthsnths Nursing home-overnight stay",
      "Cont. past 6 monthsnths Nursing home-day care",
      "Cont. past 6 monthsnths Res home - day care",
      "Cont. past 6 monthsnths Res home - temporary admission",
      "Cont. past 6 monthsnths Res home - overnight stay",
      "Cont. past 6 monthsnths Res home - meals",
      "Cont. past 6 monthsnths Res home - social/creative activities",
      "Know. Nursing home - overnight stay",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Home nurs serv/distr. nurs",
      "Cont. past 6 monthsnths Home help",
      "Cont. past 6 monthsnths Alpha help",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Memorytraining",
      "Cont. family physician: number of times",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Indication commission",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Nursing home-admission",
      "Cont. past 6 monthsnths Nursing home-observation",
      "Cont. past 6 monthsnths Nursing home-overnight stay",
      "Cont. past 6 monthsnths Nursing home-day care",
      "Cont. past 6 monthsnths Res home - day care",
      "Cont. past 6 monthsnths Res home - temporary admission",
      "Cont. past 6 monthsnths Res home - overnight stay",
      "Cont. past 6 monthsnths Res home - meals",
      "Cont. past 6 monthsnths Res home - social/creative activities",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Red Cross",
      "Cont. past 6 monthsnths Memorytraining",
      "Cont. family physician: number of times",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Social alarm",
      "Cont. past 6 monthsnths Daycare: social/creative activities in group",
      "Cont. past 6 monthsnths Alternative practitioner",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Social work",
      "Cont. past 6 monthsnths Coordinated senior service",
      "Cont. past 6 monthsnths Telephonic help service",
      "Cont. past 6 monthsnths Telephone circle",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Open table (food)",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. past 6 monthsnths Red Cross",
      "Cont. past 6 monthsnths Memorytraining",
      "Cont. family physician: number of times",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Socio-psychogeriatric service (SPGD)",
      "Cont. past 6 monthsnths Rehabilitation center",
      "Cont. past 6 monthsnths Social alarm",
      "Facility 1: walker or a walking frame",
      "Facility 2: (sports) wheelchair",
      "Facility 3: mobility scooter",
      "Having facilities for disabled persons",
      "Cont. past 6 monthsnths Family physician",
      "Cont. past 6 monthsnths Dentist",
      "Cont. past 6 monthsnths Physiotherapist",
      "Cont. past 6 monthsnths Dietician",
      "Cont. past 6 monthsnths Meals on wheels",
      "Cont. past 6 monthsnths Volunteers UVV",
      "Cont. past 6 monthsnths Transportation service",
      "Cont. past 6 monthsnths Chores service",
      "Cont. family physician: number of times",
      "Cont. past 6 monthsnths Consultation office alcohol&drugs",
      "Cont. past 6 monthsnths Common mental health care",
      "Cont. past 6 monthsnths Alternative practitioner"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    lst1c01 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C01",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst1c02 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C02",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst1c03 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C03",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst1c04 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C04",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst1c05 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C05",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22
    ),
    lst1c06 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C06",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22
    ),
    lst1c07 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C07",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22
    ),
    lst1c08 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C08",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78
    ),
    lst1c09 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C09",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78
    ),
    lst1c10 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C10",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78
    ),
    lst1c11 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C11",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78
    ),
    lst1c12 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C12",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst1c13 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C13",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78
    ),
    lst1c14 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C14",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst1c15 = list(
      `2B` = not_mentioned_mentioned_3,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C15",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3
    ),
    lst1c16 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C16",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst1c17 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C17",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst1c18 = list(
      `2B` = not_mentioned_mentioned_3,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C18",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78
    ),
    lst1c19 = list(
      `2B` = not_mentioned_mentioned_3,
      `3B` = not_mentioned_mentioned_22,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST1C19",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_3,
      D = not_mentioned_mentioned_3,
      E = not_mentioned_mentioned_3,
      F = not_mentioned_mentioned_3,
      G = not_mentioned_mentioned_3,
      H = not_mentioned_mentioned_22,
      I = not_mentioned_mentioned_22,
      J = not_mentioned_mentioned_78
    ),
    lst2c01 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-4` = "na, short interview",
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K01",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45,
      I = not_mentioned_mentioned_202,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst2c02 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-4` = "na, short interview",
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K02",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45,
      I = not_mentioned_mentioned_202,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst2c03 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-4` = "na, short interview",
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K03",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45,
      I = not_mentioned_mentioned_202,
      J = not_mentioned_mentioned_78
    ),
    lst2c04 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K04",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45,
      I = not_mentioned_mentioned_202,
      J = not_mentioned_mentioned_78
    ),
    lst2c05 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K05",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45
    ),
    lst2c06 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K06",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45,
      I = not_mentioned_mentioned_202,
      J = not_mentioned_mentioned_78,
      MB = not_mentioned_mentioned_156
    ),
    lst2c07 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K07",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45
    ),
    lst2c08 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K08",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45
    ),
    lst2c09 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K09",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45
    ),
    lst2c10 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K10",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45
    ),
    lst2c11 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K11",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45
    ),
    lst2c12 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K12",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45
    ),
    lst2c13 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K13",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45
    ),
    lst2c14 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K14",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45
    ),
    lst2c15 = list(
      `2B` = not_mentioned_mentioned_7,
      `3B` = not_mentioned_mentioned_45,
      B = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BLST2K15",
        `-1` = "na, asked",
        `0` = "not mentioned",
        `1` = "mentioned"
      ),
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7,
      H = not_mentioned_mentioned_45
    ),
    lst2k09 = list(
      `2B` = not_mentioned_mentioned_7,
      B = not_mentioned_mentioned_100,
      C = not_mentioned_mentioned_7,
      D = not_mentioned_mentioned_7,
      E = not_mentioned_mentioned_7,
      F = not_mentioned_mentioned_7,
      G = not_mentioned_mentioned_7
    ),
    lst1c1n = list(
      `3B` = vs_98_times_or_more,
      G = c(
        `-3` = "na wrong skip",
        `-2` = "na, see GLST1C01",
        `-1` = "na, asked: R does not know",
        `98` = "98 times or more"
      ),
      H = vs_98_times_or_more,
      I = c(`-2` = "na, see ILST1C01", `-1` = "na, asked: R does not know", `98` = "98 times or more"),
      J = c(`-2` = "na, see JLST1C01", `-1` = "na, asked; R does not know", `98` = "98 times or more"),
      MB = c(`-2` = "na, see BLST1C01", `-1` = "na, asked; R does not know", `98` = "98 times or more")
    ),
    lst1k01 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k02 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k03 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k04 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k05 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k06 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k07 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k08 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k09 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k10 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k11 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k12 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k13 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k14 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k15 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k16 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k17 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k18 = list(
      B = not_mentioned_mentioned_84
    ),
    lst1k19 = list(
      B = not_mentioned_mentioned_84
    ),
    lst2k01 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k02 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k03 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k04 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k05 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k06 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k07 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k08 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k10 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k11 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k12 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k13 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k14 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2k15 = list(
      B = not_mentioned_mentioned_100
    ),
    lst2c20 = list(
      I = not_mentioned_mentioned_202,
      J = not_mentioned_mentioned_78
    ),
    lst2c21 = list(
      I = not_mentioned_mentioned_202
    ),
    fac1 = list(
      MB = not_mentioned_mentioned_270
    ),
    fac2 = list(
      MB = not_mentioned_mentioned_270
    ),
    fac3 = list(
      MB = not_mentioned_mentioned_270
    ),
    facil = list(
      MB = c(`-4` = "na, short/terminated interview", `1` = "no", `2` = "yes")
    )
  ),

  value_labels_harmonized = list(
    fac1 = not_mentioned_mentioned_6,
    fac2 = not_mentioned_mentioned_6,
    fac3 = not_mentioned_mentioned_6,
    facil = c(`-4` = "not available, interview terminated", `1` = "no", `2` = "yes"),
    lst1c01 = not_mentioned_mentioned_46,
    lst1c02 = not_mentioned_mentioned_46,
    lst1c03 = not_mentioned_mentioned_46,
    lst1c04 = not_mentioned_mentioned_46,
    lst1c05 = not_mentioned_mentioned_46,
    lst1c06 = not_mentioned_mentioned_46,
    lst1c07 = not_mentioned_mentioned_46,
    lst1c08 = not_mentioned_mentioned_46,
    lst1c09 = not_mentioned_mentioned_46,
    lst1c10 = not_mentioned_mentioned_46,
    lst1c11 = not_mentioned_mentioned_46,
    lst1c12 = not_mentioned_mentioned_46,
    lst1c13 = not_mentioned_mentioned_46,
    lst1c14 = not_mentioned_mentioned_46,
    lst1c15 = c(
      `-5` = "not available, interview terminated",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `0` = "not mentioned",
      `1` = "mentioned"
    ),
    lst1c16 = not_mentioned_mentioned_46,
    lst1c17 = not_mentioned_mentioned_46,
    lst1c18 = not_mentioned_mentioned_46,
    lst1c19 = not_mentioned_mentioned_46,
    lst1c1n = c(
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked: r does not know",
      `98` = "98 times or more"
    ),
    lst1k01 = not_mentioned_mentioned_85,
    lst1k02 = not_mentioned_mentioned_85,
    lst1k03 = not_mentioned_mentioned_85,
    lst1k04 = not_mentioned_mentioned_85,
    lst1k05 = not_mentioned_mentioned_85,
    lst1k06 = not_mentioned_mentioned_85,
    lst1k07 = not_mentioned_mentioned_85,
    lst1k08 = not_mentioned_mentioned_85,
    lst1k09 = not_mentioned_mentioned_85,
    lst1k10 = not_mentioned_mentioned_85,
    lst1k11 = not_mentioned_mentioned_85,
    lst1k12 = not_mentioned_mentioned_85,
    lst1k13 = not_mentioned_mentioned_85,
    lst1k14 = not_mentioned_mentioned_85,
    lst1k15 = not_mentioned_mentioned_85,
    lst1k16 = not_mentioned_mentioned_85,
    lst1k17 = not_mentioned_mentioned_85,
    lst1k18 = not_mentioned_mentioned_85,
    lst1k19 = not_mentioned_mentioned_85,
    lst2c01 = not_mentioned_mentioned_271,
    lst2c02 = not_mentioned_mentioned_271,
    lst2c03 = not_mentioned_mentioned_271,
    lst2c04 = not_mentioned_mentioned_46,
    lst2c05 = not_mentioned_mentioned_46,
    lst2c06 = not_mentioned_mentioned_46,
    lst2c07 = not_mentioned_mentioned_46,
    lst2c08 = not_mentioned_mentioned_46,
    lst2c09 = not_mentioned_mentioned_46,
    lst2c10 = not_mentioned_mentioned_46,
    lst2c11 = not_mentioned_mentioned_46,
    lst2c12 = not_mentioned_mentioned_46,
    lst2c13 = not_mentioned_mentioned_46,
    lst2c14 = not_mentioned_mentioned_46,
    lst2c15 = not_mentioned_mentioned_46,
    lst2c20 = not_mentioned_mentioned_285,
    lst2c21 = not_mentioned_mentioned_285,
    lst2k01 = not_mentioned_mentioned_112,
    lst2k02 = not_mentioned_mentioned_112,
    lst2k03 = not_mentioned_mentioned_112,
    lst2k04 = not_mentioned_mentioned_112,
    lst2k05 = not_mentioned_mentioned_112,
    lst2k06 = not_mentioned_mentioned_112,
    lst2k07 = not_mentioned_mentioned_112,
    lst2k08 = not_mentioned_mentioned_112,
    lst2k09 = c(
      `-5` = "not available, interview terminated",
      `-4` = "not available, short interview",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `0` = "not mentioned",
      `1` = "mentioned"
    ),
    lst2k10 = not_mentioned_mentioned_112,
    lst2k11 = not_mentioned_mentioned_112,
    lst2k12 = not_mentioned_mentioned_112,
    lst2k13 = not_mentioned_mentioned_112,
    lst2k14 = not_mentioned_mentioned_112,
    lst2k15 = not_mentioned_mentioned_112
  )
)
