## LASA filecode 273 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_273 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "blo",
      "bloemo",
      "blosoc",
      "blo",
      "bloemo",
      "blosoc",
      "blo",
      "bloemo",
      "blosoc",
      "clo",
      "cloemo",
      "closoc",
      "dlo",
      "dloemo",
      "dlosoc",
      "elo",
      "eloemo",
      "elosoc",
      "flo",
      "floemo",
      "flosoc",
      "glo",
      "gloemo",
      "glosoc",
      "hlo",
      "hloemo",
      "hlosoc",
      "ilo",
      "iloemo",
      "ilosoc",
      "jlo",
      "jloemo",
      "jlosoc",
      "blo",
      "bloemo",
      "blosoc"
    ),
    canonical_name = c(
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc",
      "lo",
      "loemo",
      "losoc"
    ),
    variable_label = c(
      "loneliness 11 items dichotomous",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness <scale de Jong Gierveld>",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness 11 items dichotomous",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness 11 items dichotomous",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness 11 items dichotomous",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness 11 items dichotomous",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness <scale de Jong Gierveld>",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness <scale de Jong Gierveld>",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness <scale de Jong Gierveld>",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness <scale de Jong Gierveld>",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness <scale de Jong Gierveld>",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>",
      "loneliness <scale de Jong Gierveld>",
      "emotional loneliness <scale de Jong Gierveld>",
      "social loneliness <scale de Jong Gierveld>"
    ),
    harmonized_var_label = c(
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)",
      "Loneliness score (De Jong Gierveld, 11 items)",
      "Emotional loneliness score (De Jong Gierveld)",
      "Social loneliness score (De Jong Gierveld)"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    lo = list(
      `2B` = refusal_skip_by_interviewer_terminated_interview,
      `3B` = short_version_refusal_skip_by_interviewer,
      B = refusal_skip_by_interviewer_terminated_interview,
      C = refusal_skip_by_interviewer_terminated_interview,
      D = refusal_skip_by_interviewer_terminated_interview,
      E = refusal_skip_by_interviewer_terminated_interview,
      F = c(
        `-4` = "refusal/skip by interviewer",
        `-3` = "terminated interview",
        `-1` = ">1 missing items",
        `0` = NA_character_,
        `11` = NA_character_
      ),
      G = c(
        `-5` = "short version",
        `-4` = "refusal/skip by interviewer",
        `-3` = "terminated interview",
        `-1` = ">1 missing items",
        `0` = NA_character_,
        `11` = NA_character_
      ),
      H = short_version_refusal_skip_by_interviewer,
      I = short_version_refusal_skip_by_interviewer,
      J = short_version_refusal_skip_by_interviewer,
      MB = short_version_refusal_skip_by_interviewer
    ),
    loemo = list(
      `2B` = short_version_refusal_skip_by_interviewer_4,
      `3B` = short_version_refusal_skip_by_interviewer_2,
      B = proxy_unit_nonresponse,
      C = proxy_unit_nonresponse,
      D = proxy_unit_nonresponse,
      E = proxy_unit_nonresponse,
      F = c(
        `-9` = "born <= 1907",
        `-5` = "short version",
        `-4` = "refusal/skip by interviewer",
        `-3` = "terminated interview",
        `-1` = ">1 missing items",
        `0` = NA_character_,
        `6` = NA_character_,
        `7` = "proxy (unit nonresponse)",
        `8` = "telephone interview (unit nonresponse)"
      ),
      G = short_version_refusal_skip_by_interviewer_4,
      H = short_version_refusal_skip_by_interviewer_2,
      I = short_version_refusal_skip_by_interviewer_2,
      J = short_version_refusal_skip_by_interviewer_2,
      MB = short_version_refusal_skip_by_interviewer_2
    ),
    losoc = list(
      `2B` = short_version_refusal_skip_by_interviewer_5,
      `3B` = short_version_refusal_skip_by_interviewer_3,
      B = unit_nonresponse_proxy_unit_nonresponse,
      C = unit_nonresponse_proxy_unit_nonresponse,
      D = unit_nonresponse_proxy_unit_nonresponse,
      E = unit_nonresponse_proxy_unit_nonresponse,
      F = c(
        `-9` = "born <= 1907",
        `-5` = "short version",
        `-4` = "refusal/skip by interviewer",
        `-3` = "terminated interview",
        `-1` = ">1 missing items",
        `0` = NA_character_,
        `5` = NA_character_,
        `6` = "unit nonresponse",
        `7` = "proxy (unit nonresponse)",
        `8` = "telephone interview (unit nonresponse)"
      ),
      G = short_version_refusal_skip_by_interviewer_5,
      H = short_version_refusal_skip_by_interviewer_3,
      I = short_version_refusal_skip_by_interviewer_3,
      J = short_version_refusal_skip_by_interviewer_3,
      MB = short_version_refusal_skip_by_interviewer_3
    )
  ),

  value_labels_harmonized = list(
    lo = c(
      `-5` = "short version",
      `-4` = "refusal/skip by interviewer",
      `-3` = "interview terminated",
      `-2` = ">1 missing items",
      `-1` = "missing-item threshold exceeded",
      `0` = NA_character_,
      `11` = NA_character_
    ),
    loemo = c(
      `-9` = "born <= 1907",
      `-5` = "short version",
      `-4` = "refusal/skip by interviewer",
      `-3` = "interview terminated",
      `-1` = ">1 missing items",
      `0` = NA_character_,
      `6` = "source-defined code 6",
      `7` = "proxy (unit nonresponse)",
      `8` = "telephone interview (unit nonresponse)",
      `9` = "born <=1907 or >1937"
    ),
    losoc = c(
      `-9` = "born <= 1907",
      `-5` = "short version",
      `-4` = "refusal/skip by interviewer",
      `-3` = "interview terminated",
      `-1` = ">1 missing items",
      `0` = NA_character_,
      `5` = NA_character_,
      `6` = "unit nonresponse",
      `7` = "proxy (unit nonresponse)",
      `8` = "telephone interview (unit nonresponse)",
      `9` = "born <=1907 or >1937"
    )
  )
)
