## LASA filecode 186 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_186 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bmbot1",
      "bmbot1#",
      "bmbot2_1",
      "bmbot2_2",
      "bmbot2_3",
      "bmbot41",
      "bmbot42",
      "bmbot43",
      "bmbot51",
      "bmbot52",
      "bmbot53",
      "bmbot6",
      "bmbot62",
      "bmbot63",
      "bmbot64",
      "bmbot65",
      "bmhippl",
      "bmhipplm",
      "bmhipply",
      "bmhippr",
      "bmhipprm",
      "bmhippro",
      "bmhippry",
      "bmbot1",
      "bmbot1#",
      "bmbot111",
      "bmbot112",
      "bmbot113",
      "bmbot114",
      "bmbot115",
      "bmbot2_1",
      "bmbot2_2",
      "bmbot2_3",
      "bmbot2_4",
      "bmbot2_5",
      "bmbot41d",
      "bmbot41m",
      "bmbot41y",
      "bmbot42d",
      "bmbot42m",
      "bmbot42y",
      "bmbot43d",
      "bmbot43m",
      "bmbot43y",
      "bmbot44d",
      "bmbot44m",
      "bmbot44y",
      "bmbot45d",
      "bmbot45m",
      "bmbot45y",
      "bmbot51",
      "bmbot52",
      "bmbot53",
      "bmbot54",
      "bmbot55",
      "bmbot6",
      "bmbot62",
      "bmbot63",
      "bmbot64",
      "bmbot65",
      "bmhipplm",
      "bmhipply",
      "bmhipprm",
      "bmhippro",
      "bmhippry",
      "cmbot1",
      "cmbot1#",
      "cmbot101",
      "cmbot102",
      "cmbot103",
      "cmbot104",
      "cmbot105",
      "cmbot2_1",
      "cmbot2_2",
      "cmbot2_3",
      "cmbot2_4",
      "cmbot2_5",
      "cmbot31",
      "cmbot32",
      "cmbot33",
      "cmbot34",
      "cmbot35",
      "cmbot41",
      "cmbot42",
      "cmbot43",
      "cmbot44",
      "cmbot45",
      "cmbot51",
      "cmbot52",
      "cmbot53",
      "cmbot54",
      "cmbot55",
      "cmbot6",
      "cmbot62",
      "cmbot63",
      "cmbot64",
      "cmbot65",
      "cmbot8",
      "cmbot8#",
      "cmbot91",
      "cmbot92",
      "cmbot93",
      "cmbot94",
      "cmbot95",
      "dmbot1",
      "dmbot1#",
      "dmbot2_1",
      "dmbot2_2",
      "dmbot2_3",
      "dmbot51",
      "dmbot52",
      "dmbot53",
      "dmbot6",
      "dmbot62",
      "dmbot63",
      "dmbot64",
      "dmbot65",
      "dmhipplm",
      "dmhipply",
      "dmhipprm",
      "dmhippro",
      "dmhippry",
      "embot1",
      "embot1#",
      "embot2_1",
      "embot2_2",
      "embot2_3",
      "embot51",
      "embot52",
      "embot53",
      "emhipply",
      "emhippro",
      "emhippry",
      "fmbot1",
      "fmbot1#",
      "fmbot111",
      "fmbot112",
      "fmbot113",
      "fmbot121",
      "fmbot122",
      "fmbot123",
      "fmbot131",
      "fmbot132",
      "fmbot133",
      "fmbot2_1",
      "fmbot2_2",
      "fmbot2_3",
      "fmbot41d",
      "fmbot41m",
      "fmbot41y",
      "fmbot42d",
      "fmbot42m",
      "fmbot42y",
      "fmbot43d",
      "fmbot43m",
      "fmbot43y",
      "fmbot51",
      "fmbot52",
      "fmbot53",
      "fmhipply",
      "fmhippro",
      "fmhippry",
      "gmbot1",
      "gmbot1#",
      "gmbot111",
      "gmbot112",
      "gmbot113",
      "gmbot121",
      "gmbot122",
      "gmbot123",
      "gmbot131",
      "gmbot132",
      "gmbot133",
      "gmbot2_1",
      "gmbot2_2",
      "gmbot2_3",
      "gmbot41d",
      "gmbot41m",
      "gmbot41y",
      "gmbot42d",
      "gmbot42m",
      "gmbot42y",
      "gmbot43d",
      "gmbot43m",
      "gmbot43y",
      "gmbot51",
      "gmbot52",
      "gmbot53",
      "gmhipply",
      "gmhippro",
      "gmhippry",
      "hmbot1",
      "hmbot1#",
      "hmbot111",
      "hmbot112",
      "hmbot113",
      "hmbot121",
      "hmbot122",
      "hmbot123",
      "hmbot131",
      "hmbot132",
      "hmbot133",
      "hmbot2_1",
      "hmbot2_2",
      "hmbot2_3",
      "hmbot41d",
      "hmbot41m",
      "hmbot41y",
      "hmbot42d",
      "hmbot42m",
      "hmbot42y",
      "hmbot43d",
      "hmbot43m",
      "hmbot43y",
      "hmbot51",
      "hmbot52",
      "hmbot53",
      "hmhipply",
      "hmhippro",
      "hmhippry",
      "hmkneply",
      "hmknepro",
      "hmknepry",
      "imbot1",
      "imbot1#",
      "imbot111",
      "imbot112",
      "imbot113",
      "imbot121",
      "imbot122",
      "imbot123",
      "imbot132",
      "imbot133",
      "imbot2_1",
      "imbot2_2",
      "imbot2_3",
      "imbot41d",
      "imbot41m",
      "imbot41y",
      "imbot42d",
      "imbot42m",
      "imbot42y",
      "imbot43d",
      "imbot43m",
      "imbot43y",
      "imbot51",
      "imbot52",
      "imbot53",
      "imhipply",
      "imhippro",
      "imhippry",
      "imkneply",
      "imknepro",
      "imknepry",
      "jmbot1",
      "jmbot1#",
      "jmbot111",
      "jmbot112",
      "jmbot113",
      "jmbot121",
      "jmbot122",
      "jmbot123",
      "jmbot131",
      "jmbot132",
      "jmbot133",
      "jmbot2_1",
      "jmbot2_2",
      "jmbot2_3",
      "jmbot41d",
      "jmbot41m",
      "jmbot41y",
      "jmbot42d",
      "jmbot42m",
      "jmbot42y",
      "jmbot43d",
      "jmbot43m",
      "jmbot43y",
      "jmbot51",
      "jmbot52",
      "jmbot53",
      "jmconsx1",
      "jmconsx2",
      "jmconsx3",
      "jmfallfrac",
      "jmfallfracd",
      "jmfallfracm",
      "jmfallfracy",
      "jmhipply",
      "jmhippro",
      "jmhippry",
      "jmkneply",
      "jmknepro",
      "jmknepry",
      "kmbot1",
      "kmbot1#",
      "kmbot111",
      "kmbot112",
      "kmbot113",
      "kmbot121",
      "kmbot122",
      "kmbot123",
      "kmbot2",
      "kmbot2_1",
      "kmbot2_2",
      "kmbot2_3",
      "kmbot3",
      "kmbot41d",
      "kmbot41m",
      "kmbot41y",
      "kmbot42d",
      "kmbot42m",
      "kmbot42y",
      "kmbot43d",
      "kmbot43m",
      "kmbot43y",
      "kmbot51",
      "kmbot52",
      "kmbot53",
      "kmconsx1",
      "kmconsx2",
      "kmconsx3",
      "kmfallfrac",
      "kmfallfracd",
      "kmfallfracm",
      "kmfallfracy",
      "kmhipply",
      "kmhippro",
      "kmhippry",
      "kmkneply",
      "kmknepro",
      "kmknepry",
      "bmbot1",
      "bmbot1#",
      "bmbot2_1",
      "bmbot2_2",
      "bmbot2_3",
      "bmbot41d",
      "bmbot41m",
      "bmbot41y",
      "bmbot42d",
      "bmbot42m",
      "bmbot42y",
      "bmbot43d",
      "bmbot43m",
      "bmbot43y"
    ),
    canonical_name = c(
      "mbot1",
      "mbot1#",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot41",
      "mbot42",
      "mbot43",
      "mbot51",
      "mbot52",
      "mbot53",
      "mbot6",
      "mbot62",
      "mbot63",
      "mbot64",
      "mbot65",
      "mhippl",
      "mhipplm",
      "mhipply",
      "mhippr",
      "mhipprm",
      "mhippro",
      "mhippry",
      "mbot1",
      "mbot1#",
      "mbot111",
      "mbot112",
      "mbot113",
      "mbot114",
      "mbot115",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot2_4",
      "mbot2_5",
      "mbot41d",
      "mbot41m",
      "mbot41y",
      "mbot42d",
      "mbot42m",
      "mbot42y",
      "mbot43d",
      "mbot43m",
      "mbot43y",
      "mbot44d",
      "mbot44m",
      "mbot44y",
      "mbot45d",
      "mbot45m",
      "mbot45y",
      "mbot51",
      "mbot52",
      "mbot53",
      "mbot54",
      "mbot55",
      "mbot6",
      "mbot62",
      "mbot63",
      "mbot64",
      "mbot65",
      "mhipplm",
      "mhipply",
      "mhipprm",
      "mhippro",
      "mhippry",
      "mbot1",
      "mbot1#",
      "mbot101",
      "mbot102",
      "mbot103",
      "mbot104",
      "mbot105",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot2_4",
      "mbot2_5",
      "mbot31",
      "mbot32",
      "mbot33",
      "mbot34",
      "mbot35",
      "mbot41",
      "mbot42",
      "mbot43",
      "mbot44",
      "mbot45",
      "mbot51",
      "mbot52",
      "mbot53",
      "mbot54",
      "mbot55",
      "mbot6",
      "mbot62",
      "mbot63",
      "mbot64",
      "mbot65",
      "mbot8",
      "mbot8#",
      "mbot91",
      "mbot92",
      "mbot93",
      "mbot94",
      "mbot95",
      "mbot1",
      "mbot1#",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot51",
      "mbot52",
      "mbot53",
      "mbot6",
      "mbot62",
      "mbot63",
      "mbot64",
      "mbot65",
      "mhipplm",
      "mhipply",
      "mhipprm",
      "mhippro",
      "mhippry",
      "mbot1",
      "mbot1#",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot51",
      "mbot52",
      "mbot53",
      "mhipply",
      "mhippro",
      "mhippry",
      "mbot1",
      "mbot1#",
      "mbot111",
      "mbot112",
      "mbot113",
      "mbot121",
      "mbot122",
      "mbot123",
      "mbot131",
      "mbot132",
      "mbot133",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot41d",
      "mbot41m",
      "mbot41y",
      "mbot42d",
      "mbot42m",
      "mbot42y",
      "mbot43d",
      "mbot43m",
      "mbot43y",
      "mbot51",
      "mbot52",
      "mbot53",
      "mhipply",
      "mhippro",
      "mhippry",
      "mbot1",
      "mbot1#",
      "mbot111",
      "mbot112",
      "mbot113",
      "mbot121",
      "mbot122",
      "mbot123",
      "mbot131",
      "mbot132",
      "mbot133",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot41d",
      "mbot41m",
      "mbot41y",
      "mbot42d",
      "mbot42m",
      "mbot42y",
      "mbot43d",
      "mbot43m",
      "mbot43y",
      "mbot51",
      "mbot52",
      "mbot53",
      "mhipply",
      "mhippro",
      "mhippry",
      "mbot1",
      "mbot1#",
      "mbot111",
      "mbot112",
      "mbot113",
      "mbot121",
      "mbot122",
      "mbot123",
      "mbot131",
      "mbot132",
      "mbot133",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot41d",
      "mbot41m",
      "mbot41y",
      "mbot42d",
      "mbot42m",
      "mbot42y",
      "mbot43d",
      "mbot43m",
      "mbot43y",
      "mbot51",
      "mbot52",
      "mbot53",
      "mhipply",
      "mhippro",
      "mhippry",
      "mkneply",
      "mknepro",
      "mknepry",
      "mbot1",
      "mbot1#",
      "mbot111",
      "mbot112",
      "mbot113",
      "mbot121",
      "mbot122",
      "mbot123",
      "mbot132",
      "mbot133",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot41d",
      "mbot41m",
      "mbot41y",
      "mbot42d",
      "mbot42m",
      "mbot42y",
      "mbot43d",
      "mbot43m",
      "mbot43y",
      "mbot51",
      "mbot52",
      "mbot53",
      "mhipply",
      "mhippro",
      "mhippry",
      "mkneply",
      "mknepro",
      "mknepry",
      "mbot1",
      "mbot1#",
      "mbot111",
      "mbot112",
      "mbot113",
      "mbot121",
      "mbot122",
      "mbot123",
      "mbot131",
      "mbot132",
      "mbot133",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot41d",
      "mbot41m",
      "mbot41y",
      "mbot42d",
      "mbot42m",
      "mbot42y",
      "mbot43d",
      "mbot43m",
      "mbot43y",
      "mbot51",
      "mbot52",
      "mbot53",
      "mconsx1",
      "mconsx2",
      "mconsx3",
      "mfallfrac",
      "mfallfracd",
      "mfallfracm",
      "mfallfracy",
      "mhipply",
      "mhippro",
      "mhippry",
      "mkneply",
      "mknepro",
      "mknepry",
      "mbot1",
      "mbot1#",
      "mbot111",
      "mbot112",
      "mbot113",
      "mbot121",
      "mbot122",
      "mbot123",
      "mbot2",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot3",
      "mbot41d",
      "mbot41m",
      "mbot41y",
      "mbot42d",
      "mbot42m",
      "mbot42y",
      "mbot43d",
      "mbot43m",
      "mbot43y",
      "mbot51",
      "mbot52",
      "mbot53",
      "mconsx1",
      "mconsx2",
      "mconsx3",
      "mfallfrac",
      "mfallfracd",
      "mfallfracm",
      "mfallfracy",
      "mhipply",
      "mhippro",
      "mhippry",
      "mkneply",
      "mknepro",
      "mknepry",
      "mbot1",
      "mbot1#",
      "mbot2_1",
      "mbot2_2",
      "mbot2_3",
      "mbot41d",
      "mbot41m",
      "mbot41y",
      "mbot42d",
      "mbot42m",
      "mbot42y",
      "mbot43d",
      "mbot43m",
      "mbot43y"
    ),
    variable_label = c(
      "Fracture: ever",
      "# of fractures (max 3)",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: Year",
      "Fracture 2: Year",
      "Fracture 3: Year",
      "Fracture 1 hip: cause",
      "Fracture 2 hip: cause",
      "Fracture 3 hip: cause",
      "Fractures family",
      "Fractures family history: mother",
      "Fractures family history: father",
      "Fractures family history: brother",
      "Fractures family history: sister",
      "Left hipprosthesis",
      "not processed",
      "Year left hipprosthesis",
      "Right hipprosthesis",
      "not processed",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "fracture: since last interview",
      "number of fractures since (max 3)",
      "fracture 1: side",
      "fracture 2: side",
      "fracture 3: side",
      "fracture 4: side",
      "fracture 5: side",
      "fracture 1: type",
      "fracture 2: type",
      "fracture 3: type",
      "fracture 4: type",
      "fracture 5: type",
      "fracture 1: day",
      "fracture 1: month",
      "fracture 1: year",
      "fracture 2: day",
      "fracture 2: month",
      "fracture 2: year",
      "fracture 3: day",
      "fracture 3: month",
      "fracture 3: year",
      "fracture 4: day",
      "fracture 4: month",
      "fracture 4: year",
      "fracture 5: day",
      "fracture 5: month",
      "fracture 5: year",
      "fracture 1: cause",
      "fracture 2: cause",
      "fracture 3: cause",
      "fracture 4: cause",
      "fracture 5: cause",
      "hip fractures family history",
      "hip fractures family history: mother",
      "hip fractures family history: father",
      "hip fractures family history: brother",
      "hip fractures family history: sister",
      "hip prosthesis left: month",
      "hip prosthesis left: year",
      "hip prosthesis right: month",
      "hip prosthesis",
      "hip prosthesis right: year",
      "Fracture: since last interview",
      "# of fractures since (max 5)",
      "Fracture before 1: age",
      "Fracture before 2: age",
      "Fracture before 3: age",
      "Fracture before 4: age",
      "Fracture before 5: age",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 4: type",
      "Fracture 5: type",
      "Fracture 1: month",
      "Fracture 2: month",
      "Fracture 3: month",
      "Fracture 4: month",
      "Fracture 5: month",
      "Fracture 1: year",
      "Fracture 2: year",
      "Fracture 3: year",
      "Fracture 4: year",
      "Fracture 5: year",
      "Fracture 1 hip: cause",
      "Fracture 2 hip; cause",
      "Fracture 3 hip: cause",
      "Fracture 4 hip: cause",
      "Fracture 5 hip: cause",
      "Fractures Family",
      "Fractures Family History: mother",
      "Fractures Family History: father",
      "Fractures Family History: brother",
      "Fractures Family History: sister",
      "Fractures before last interview (max 5)",
      "# of fractures before (max 5)",
      "Fracture before 1: type",
      "Fracture before 2: type",
      "Fracture before 3: type",
      "Fracture before 4: type",
      "Fracture before 5: type",
      "Fracture: since last interview",
      "# of fractures since (max 3)",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Hip fractures family members",
      "Hip fractures history: mother",
      "Hip fractures history: father",
      "Hip fractures history: brother",
      "Hip fractures history: sister",
      "Month left hip prosthesis",
      "Year left hip prosthesis",
      "Month right hip prosthesis",
      "Hip prosthesis",
      "Year right hip prosthesis",
      "Fracture: since last interview",
      "# of fractures since (max 3)",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Year left hip prosthesis",
      "Hip prosthesis",
      "Year right hip prosthesis",
      "Fracture: since last interview",
      "# of fractures since (max 3)",
      "Fracture 1: side",
      "Fracture 2: side",
      "Fracture 3: side",
      "Fracture 1: x-ray",
      "Fracture 2: x-ray",
      "Fracture 3: x-ray",
      "Fracture 1: consent",
      "Fracture 2: consent",
      "Fracture 3: consent",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: day",
      "Fracture 1: month",
      "Fracture 1: year",
      "Fracture 2: day",
      "Fracture 2: month",
      "Fracture 2: year",
      "Fracture 3: day",
      "Fracture 3: month",
      "Fracture 3: year",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Year left hip prosthesis",
      "Hip prosthesis",
      "Year right hip prosthesis",
      "fracture: since last interview",
      "number of fractures since (max 3)",
      "fracture 1: side",
      "fracture 2: side",
      "fracture 3: side",
      "fracture 1: x-ray",
      "fracture 2: x-ray",
      "fracture 3: x-ray",
      "fracture 1: consent",
      "fracture 2: consent",
      "fracture 3: consent",
      "fracture 1: type",
      "fracture 2: type",
      "fracture 3: type",
      "fracture 1: day",
      "fracture 1: month",
      "fracture 1: year",
      "fracture 2: day",
      "fracture 2: month",
      "fracture 2: year",
      "fracture 3: day",
      "fracture 3: month",
      "fracture 3: year",
      "fracture 1: cause",
      "fracture 2: cause",
      "fracture 3: cause",
      "hip prosthesis left: year",
      "hip prosthesis",
      "hip prosthesis right: year",
      "fracture: since last interview",
      "number of fractures since (max 3)",
      "fracture 1: side",
      "fracture 2: side",
      "fracture 3: side",
      "fracture 1: x-ray",
      "fracture 2: x-ray",
      "fracture 3: x-ray",
      "fracture 1: consent",
      "fracture 2: consent",
      "fracture 3: consent",
      "fracture 1: type",
      "fracture 2: type",
      "fracture 3: type",
      "fracture 1: day",
      "fracture 1: month",
      "fracture 1: year",
      "fracture 2: day",
      "fracture 2: month",
      "fracture 2: year",
      "fracture 3: day",
      "fracture 3: month",
      "fracture 3: year",
      "fracture 1: cause",
      "fracture 2: cause",
      "fracture 3: cause",
      "hip prosthesis left: year",
      "hip prosthesis",
      "hip prosthesis right: year",
      "knee prosthesis left: year",
      "knee prosthesis",
      "knee prosthesis right: year",
      "fracture: since last interview",
      "number of fractures since (max 3)",
      "fracture 1: side",
      "fracture 2: side",
      "fracture 3: side",
      "fracture 1: x-ray",
      "fracture 2: x-ray",
      "fracture 3: x-ray",
      "fracture 2: consent",
      "fracture 3: consent",
      "fracture 1: type",
      "fracture 2: type",
      "fracture 3: type",
      "fracture 1: day",
      "fracture 1: month",
      "fracture 1: year",
      "fracture 2: day",
      "fracture 2: month",
      "fracture 2: year",
      "fracture 3: day",
      "fracture 3: month",
      "fracture 3: year",
      "fracture 1: cause",
      "fracture 2: cause",
      "fracture 3: cause",
      "hip prosthesis left: year",
      "hip prosthesis",
      "hip prosthesis right: year",
      "knee prosthesis left: year",
      "knee prosthesis",
      "knee prosthesis right: year",
      "fracture: since last interview",
      "number of fractures since last interview (max 3)",
      "fracture 1: side",
      "fracture 2: side",
      "fracture 3: side",
      "fracture 1: x-ray",
      "fracture 2: x-ray",
      "fracture 3: x-ray",
      "fracture 1: consent for report",
      "fracture 2: consent for report",
      "fracture 3: consent for report",
      "fracture 1: type",
      "fracture 2: type",
      "fracture 3: type",
      "fracture 1: day",
      "fracture 1: month",
      "fracture 1: year",
      "fracture 2: day",
      "fracture 2: month",
      "fracture 2: year",
      "fracture 3: day",
      "fracture 3: month",
      "fracture 3: year",
      "fracture 1: cause",
      "fracture 2: cause",
      "fracture 3: cause",
      "fracture 1: consent for x-ray and report",
      "fracture 2: consent for x-ray and report",
      "fracture 3: consent for x-ray and report",
      "fracture due to",
      "fracture due to fall: day",
      "fracture due to fall: month",
      "fracture due to fall: year",
      "hip prosthesis left: year",
      "hip prosthesis",
      "hip prosthesis right: year",
      "knee prosthesis left: year",
      "knee prosthesis",
      "knee prosthesis right: year",
      "other fracture since last interview",
      "number of fractures since last interview (max 3)",
      "fracture 1: side",
      "fracture 2: side",
      "fracture 3: side",
      "fracture 1: photo",
      "fracture 2: photo",
      "fracture 3: photo",
      "second fracture",
      "fracture 1: type",
      "fracture 2: type",
      "fracture 3: type",
      "Third fracture",
      "fracture 1: day",
      "fracture 1: month",
      "fracture 1: year",
      "fracture 2: day",
      "fracture 2: month",
      "fracture 2: year",
      "fracture 3: day",
      "fracture 3: month",
      "fracture 3: year",
      "fracture 1: cause",
      "fracture 2: cause",
      "fracture 3: cause",
      "fracture 1: consent for photo and report",
      "fracture 2: consent for photo and report",
      "toestemming verslag botbreuk 1",
      "fracture due to",
      "fracture due to fall: day",
      "fracture due to fall: month",
      "fracture due to fall: year",
      "hip prosthesis left: year",
      "hip prosthesis",
      "hip prosthesis right: year",
      "knee prosthesis left: year",
      "knee prosthesis",
      "knee prosthesis right: year",
      "fracture: ever",
      "number of fractures (max 3)",
      "fracture 1: type",
      "fracture 2: type",
      "fracture 3: type",
      "fracture 1: day",
      "fracture 1: month",
      "fracture 1: year",
      "fracture 2: day",
      "fracture 2: month",
      "fracture 2: year",
      "fracture 3: day",
      "fracture 3: month",
      "fracture 3: year"
    ),
    harmonized_var_label = c(
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: year",
      "Fracture 2: year",
      "Fracture 3: year",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Fractures Family",
      "Fractures Family History: mother",
      "Fractures Family History: father",
      "Fractures Family History: brother",
      "Fractures Family History: sister",
      "Left hipprosthesis",
      "Month left hip prosthesis",
      "Year left hipprosthesis",
      "Right hipprosthesis",
      "Month right hip prosthesis",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: side",
      "Fracture 2: side",
      "Fracture 3: side",
      "fracture 4: side",
      "fracture 5: side",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 4: type",
      "Fracture 5: type",
      "Fracture 1: day",
      "Fracture 1: month",
      "Fracture 1: year",
      "Fracture 2: day",
      "Fracture 2: month",
      "Fracture 2: year",
      "Fracture 3: day",
      "Fracture 3: month",
      "Fracture 3: year",
      "fracture 4: day",
      "fracture 4: month",
      "fracture 4: year",
      "fracture 5: day",
      "fracture 5: month",
      "fracture 5: year",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Fracture 4 hip: cause",
      "Fracture 5 hip: cause",
      "Fractures Family",
      "Fractures Family History: mother",
      "Fractures Family History: father",
      "Fractures Family History: brother",
      "Fractures Family History: sister",
      "Month left hip prosthesis",
      "Year left hipprosthesis",
      "Month right hip prosthesis",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture before 1: age",
      "Fracture before 2: age",
      "Fracture before 3: age",
      "Fracture before 4: age",
      "Fracture before 5: age",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 4: type",
      "Fracture 5: type",
      "Fracture 1: month",
      "Fracture 2: month",
      "Fracture 3: month",
      "Fracture 4: month",
      "Fracture 5: month",
      "Fracture 1: year",
      "Fracture 2: year",
      "Fracture 3: year",
      "Fracture 4: year",
      "Fracture 5: year",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Fracture 4 hip: cause",
      "Fracture 5 hip: cause",
      "Fractures Family",
      "Fractures Family History: mother",
      "Fractures Family History: father",
      "Fractures Family History: brother",
      "Fractures Family History: sister",
      "Fractures before last interview (max 5)",
      "# of fractures before (max 5)",
      "Fracture before 1: type",
      "Fracture before 2: type",
      "Fracture before 3: type",
      "Fracture before 4: type",
      "Fracture before 5: type",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Fractures Family",
      "Fractures Family History: mother",
      "Fractures Family History: father",
      "Fractures Family History: brother",
      "Fractures Family History: sister",
      "Month left hip prosthesis",
      "Year left hipprosthesis",
      "Month right hip prosthesis",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Year left hipprosthesis",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: side",
      "Fracture 2: side",
      "Fracture 3: side",
      "Fracture 1: x-ray",
      "Fracture 2: x-ray",
      "Fracture 3: x-ray",
      "Fracture 1: consent",
      "Fracture 2: consent",
      "Fracture 3: consent",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: day",
      "Fracture 1: month",
      "Fracture 1: year",
      "Fracture 2: day",
      "Fracture 2: month",
      "Fracture 2: year",
      "Fracture 3: day",
      "Fracture 3: month",
      "Fracture 3: year",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Year left hipprosthesis",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: side",
      "Fracture 2: side",
      "Fracture 3: side",
      "Fracture 1: x-ray",
      "Fracture 2: x-ray",
      "Fracture 3: x-ray",
      "Fracture 1: consent",
      "Fracture 2: consent",
      "Fracture 3: consent",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: day",
      "Fracture 1: month",
      "Fracture 1: year",
      "Fracture 2: day",
      "Fracture 2: month",
      "Fracture 2: year",
      "Fracture 3: day",
      "Fracture 3: month",
      "Fracture 3: year",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Year left hipprosthesis",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: side",
      "Fracture 2: side",
      "Fracture 3: side",
      "Fracture 1: x-ray",
      "Fracture 2: x-ray",
      "Fracture 3: x-ray",
      "Fracture 1: consent",
      "Fracture 2: consent",
      "Fracture 3: consent",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: day",
      "Fracture 1: month",
      "Fracture 1: year",
      "Fracture 2: day",
      "Fracture 2: month",
      "Fracture 2: year",
      "Fracture 3: day",
      "Fracture 3: month",
      "Fracture 3: year",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Year left hipprosthesis",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "knee prosthesis left: year",
      "knee prosthesis",
      "knee prosthesis right: year",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: side",
      "Fracture 2: side",
      "Fracture 3: side",
      "Fracture 1: x-ray",
      "Fracture 2: x-ray",
      "Fracture 3: x-ray",
      "Fracture 2: consent",
      "Fracture 3: consent",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: day",
      "Fracture 1: month",
      "Fracture 1: year",
      "Fracture 2: day",
      "Fracture 2: month",
      "Fracture 2: year",
      "Fracture 3: day",
      "Fracture 3: month",
      "Fracture 3: year",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "Year left hipprosthesis",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "knee prosthesis left: year",
      "knee prosthesis",
      "knee prosthesis right: year",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: side",
      "Fracture 2: side",
      "Fracture 3: side",
      "Fracture 1: x-ray",
      "Fracture 2: x-ray",
      "Fracture 3: x-ray",
      "Fracture 1: consent",
      "Fracture 2: consent",
      "Fracture 3: consent",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: day",
      "Fracture 1: month",
      "Fracture 1: year",
      "Fracture 2: day",
      "Fracture 2: month",
      "Fracture 2: year",
      "Fracture 3: day",
      "Fracture 3: month",
      "Fracture 3: year",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "fracture 1: consent for x-ray and report",
      "fracture 2: consent for x-ray and report",
      "fracture 3: consent for x-ray and report",
      "fracture due to",
      "fracture due to fall: day",
      "fracture due to fall: month",
      "fracture due to fall: year",
      "Year left hipprosthesis",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "knee prosthesis left: year",
      "knee prosthesis",
      "knee prosthesis right: year",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: side",
      "Fracture 2: side",
      "Fracture 3: side",
      "Fracture 1: x-ray",
      "Fracture 2: x-ray",
      "Fracture 3: x-ray",
      "second fracture",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Third fracture",
      "Fracture 1: day",
      "Fracture 1: month",
      "Fracture 1: year",
      "Fracture 2: day",
      "Fracture 2: month",
      "Fracture 2: year",
      "Fracture 3: day",
      "Fracture 3: month",
      "Fracture 3: year",
      "Fracture 1: cause",
      "Fracture 2: cause",
      "Fracture 3: cause",
      "fracture 1: consent for x-ray and report",
      "fracture 2: consent for x-ray and report",
      "fracture 3: consent for x-ray and report",
      "fracture due to",
      "fracture due to fall: day",
      "fracture due to fall: month",
      "fracture due to fall: year",
      "Year left hipprosthesis",
      "Hipprosthesis",
      "Year right hipprosthesis",
      "knee prosthesis left: year",
      "knee prosthesis",
      "knee prosthesis right: year",
      "Fracture occurrence",
      "Number of fractures",
      "Fracture 1: type",
      "Fracture 2: type",
      "Fracture 3: type",
      "Fracture 1: day",
      "Fracture 1: month",
      "Fracture 1: year",
      "Fracture 2: day",
      "Fracture 2: month",
      "Fracture 2: year",
      "Fracture 3: day",
      "Fracture 3: month",
      "Fracture 3: year"
    ),
    var_type = c(
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mbot1 = list(
      `2B` = no_yes_5,
      `3B` = no_yes,
      C = no_yes_5,
      D = no_yes_5,
      E = no_yes_5,
      F = no_yes,
      G = no_yes,
      H = no_yes,
      I = no_yes,
      J = c(`-2` = "na, see JMFALLFRAC", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      K = no_yes_145,
      MB = no_yes
    ),
    `mbot1#` = list(
      `2B` = c(`-2` = "na, see BMBOT1", `-1` = "na, asked"),
      `3B` = na_see_h_b_imbot1,
      C = c(`-3` = "na, wrong skip", `-2` = "na, see CMBOT1"),
      D = na_see_d_embot1,
      E = na_see_d_embot1,
      F = c(`-2` = "na, see FMBOT1"),
      G = c(`-2` = "na, see GMBOT1"),
      H = na_see_h_b_imbot1,
      I = na_see_h_b_imbot1,
      J = c(`-2` = "na, see JMBOT1"),
      K = c(`-2` = "na, see KMBOT1"),
      MB = c(`-2` = "na, see BMBOT1")
    ),
    mbot2_1 = list(
      `2B` = pulse_wrist_colles_forearm_humerus_hand_fingers_4,
      `3B` = wrist_colles_humerus_hand_fingers,
      C = pulse_wrist_colles_forearm_humerus_hand_fingers_3,
      D = pulse_wrist_colles_forearm_humerus_hand_fingers_2,
      E = pulse_wrist_colles_forearm_humerus_hand_fingers_2,
      F = wrist_colles_humerus_hand_fingers_3,
      G = wrist_colles_humerus_hand_fingers_4,
      H = wrist_colles_humerus_hand_fingers,
      I = wrist_colles_humerus_hand_fingers,
      J = wrist_colles_humerus_hand_fingers_6,
      K = wrist_colles_humerus_hand_fingers_5,
      MB = wrist_colles_humerus_hand_fingers_2
    ),
    mbot2_2 = list(
      `2B` = pulse_wrist_colles_forearm_humerus_hand_fingers_4,
      `3B` = wrist_colles_humerus_hand_fingers,
      C = pulse_wrist_colles_forearm_humerus_hand_fingers_3,
      D = pulse_wrist_colles_forearm_humerus_hand_fingers_2,
      E = pulse_wrist_colles_forearm_humerus_hand_fingers_2,
      F = wrist_colles_humerus_hand_fingers_3,
      G = wrist_colles_humerus_hand_fingers_4,
      H = wrist_colles_humerus_hand_fingers,
      I = wrist_colles_humerus_hand_fingers,
      J = c(
        `-2` = "na, see JMBOT1#",
        `-1` = "na, asked",
        `1` = "wrist, colles",
        `2` = "humerus",
        `3` = "hand, fingers",
        `4` = "other upper extremities",
        `5` = "rib",
        `6` = "pelvis",
        `7` = "ankle",
        `8` = "feet, toes",
        `9` = "hip",
        `10` = "other lower extremities",
        `11` = "head (skull, nose, jaw)",
        `12` = "vertebra (back, neck)",
        `13` = "unknown"
      ),
      K = wrist_colles_humerus_hand_fingers_5,
      MB = wrist_colles_humerus_hand_fingers_2
    ),
    mbot2_3 = list(
      `2B` = pulse_wrist_colles_forearm_humerus_hand_fingers_4,
      `3B` = wrist_colles_humerus_hand_fingers,
      C = pulse_wrist_colles_forearm_humerus_hand_fingers_3,
      D = pulse_wrist_colles_forearm_humerus_hand_fingers_2,
      E = pulse_wrist_colles_forearm_humerus_hand_fingers_2,
      F = wrist_colles_humerus_hand_fingers_3,
      G = wrist_colles_humerus_hand_fingers_4,
      H = wrist_colles_humerus_hand_fingers,
      I = wrist_colles_humerus_hand_fingers,
      J = wrist_colles_humerus_hand_fingers_6,
      K = wrist_colles_humerus_hand_fingers_5,
      MB = wrist_colles_humerus_hand_fingers_2
    ),
    mbot41 = list(
      `2B` = na_wrong_skip_na_see_bmbot1_na_asked,
      C = na_wrong_skip_na_see_cmbot1_na_asked
    ),
    mbot42 = list(
      `2B` = na_wrong_skip_na_see_bmbot1_na_asked,
      C = na_wrong_skip_na_see_cmbot1_na_asked
    ),
    mbot43 = list(
      `2B` = na_wrong_skip_na_see_bmbot1_na_asked,
      C = na_wrong_skip_na_see_cmbot1_na_asked
    ),
    mbot51 = list(
      `2B` = fall_standing_height_fall_standing_height_3,
      `3B` = fall_from_standing_height_or_fall_from_standing_height,
      C = fall_standing_height_fall_standing_height_2,
      D = fall_standing_height_fall_standing_height,
      E = fall_standing_height_fall_standing_height,
      F = fall_standing_height_fall_standing_height_4,
      G = fall_standing_height_fall_standing_height_5,
      H = fall_from_standing_height_fall_from_standing_height_or,
      I = fall_from_standing_height_fall_from_standing_height_or,
      J = fall_from_standing_height_fall_from_standing_height_or_2,
      K = fall_from_standing_height_fall_from_standing_height_or_3
    ),
    mbot52 = list(
      `2B` = fall_standing_height_fall_standing_height_3,
      `3B` = fall_from_standing_height_or_fall_from_standing_height,
      C = fall_standing_height_fall_standing_height_2,
      D = fall_standing_height_fall_standing_height,
      E = fall_standing_height_fall_standing_height,
      F = fall_standing_height_fall_standing_height_4,
      G = c(
        `-2` = "na, see GMBOT1#",
        `-1` = "na, asked",
        `1` = "fall > standing height",
        `2` = "fall < =standing height",
        `3` = "traffic accident",
        `4` = "other"
      ),
      H = fall_from_standing_height_fall_from_standing_height_or,
      I = fall_from_standing_height_fall_from_standing_height_or,
      J = fall_from_standing_height_fall_from_standing_height_or_2,
      K = fall_from_standing_height_fall_from_standing_height_or_3
    ),
    mbot53 = list(
      `2B` = fall_standing_height_fall_standing_height_3,
      `3B` = fall_from_standing_height_or_fall_from_standing_height,
      C = fall_standing_height_fall_standing_height_2,
      D = fall_standing_height_fall_standing_height,
      E = fall_standing_height_fall_standing_height,
      F = fall_standing_height_fall_standing_height_4,
      G = fall_standing_height_fall_standing_height_5,
      H = fall_from_standing_height_fall_from_standing_height_or,
      I = fall_from_standing_height_fall_from_standing_height_or,
      J = fall_from_standing_height_fall_from_standing_height_or_2,
      K = fall_from_standing_height_fall_from_standing_height_or_3
    ),
    mbot6 = list(
      `2B` = yes_no_8,
      `3B` = yes_no_8,
      C = no_yes_5,
      D = no_yes
    ),
    mbot62 = list(
      `2B` = no_yes,
      `3B` = no_yes_179,
      C = not_mentioned_mentioned_260,
      D = not_mentioned_mentioned_261
    ),
    mbot63 = list(
      `2B` = no_yes,
      `3B` = no_yes_179,
      C = not_mentioned_mentioned_260,
      D = not_mentioned_mentioned_261
    ),
    mbot64 = list(
      `2B` = no_yes,
      `3B` = no_yes_179,
      C = not_mentioned_mentioned_260,
      D = not_mentioned_mentioned_261
    ),
    mbot65 = list(
      `2B` = no_yes,
      `3B` = no_yes_179,
      C = not_mentioned_mentioned_260,
      D = not_mentioned_mentioned_261
    ),
    mhippl = list(
      `2B` = no_yes_left
    ),
    mhipply = list(
      `2B` = na_see_bmhippl_na_asked,
      `3B` = na_see_h_b_imhippro_na_asked,
      D = na_see_d_emhippro_na_asked,
      E = na_see_d_emhippro_na_asked,
      F = na_see_fmhippro_na_asked,
      G = na_see_gmhippro_na_asked,
      H = na_see_h_b_imhippro_na_asked,
      I = na_see_h_b_imhippro_na_asked,
      J = na_see_jmhippro_na_asked,
      K = na_see_kmhippro_na_asked
    ),
    mhippr = list(
      `2B` = no_yes_right
    ),
    mhippro = list(
      `2B` = yes_no_8,
      `3B` = no_left_right_left_and_right,
      D = no_left_right_left_and_right,
      E = no_left_right_left_and_right,
      F = no_left_right_left_and_right,
      G = no_left_right_left_and_right,
      H = no_left_right_left_and_right,
      I = no_left_right_left_and_right,
      J = no_left_right_left_and_right,
      K = no_left_right_left_and_right
    ),
    mhippry = list(
      `2B` = na_see_bmhippr_na_asked,
      `3B` = na_see_h_b_imhippro_na_asked,
      D = na_see_d_emhippro_na_asked,
      E = na_see_d_emhippro_na_asked,
      F = na_see_fmhippro_na_asked,
      G = na_see_gmhippro_na_asked,
      H = na_see_h_b_imhippro_na_asked,
      I = na_see_h_b_imhippro_na_asked,
      J = na_see_jmhippro_na_asked,
      K = na_see_kmhippro_na_asked
    ),
    mbot111 = list(
      `3B` = right_side_left_side_not_applicable,
      F = right_side_left_side_not_applicable_4,
      G = right_side_left_side_not_applicable_5,
      H = right_side_left_side_not_applicable,
      I = right_side_left_side_not_applicable,
      J = right_side_left_side_not_applicable_2,
      K = right_side_left_side_not_applicable_6
    ),
    mbot112 = list(
      `3B` = right_side_left_side_not_applicable,
      F = right_side_left_side_not_applicable_4,
      G = right_side_left_side_not_applicable_5,
      H = right_side_left_side_not_applicable,
      I = right_side_left_side_not_applicable,
      J = right_side_left_side_not_applicable_2,
      K = right_side_left_side_not_applicable_6
    ),
    mbot113 = list(
      `3B` = right_side_left_side_not_applicable,
      F = right_side_left_side_not_applicable_4,
      G = right_side_left_side_not_applicable_5,
      H = right_side_left_side_not_applicable,
      I = right_side_left_side_not_applicable,
      J = right_side_left_side_not_applicable_2,
      K = right_side_left_side_not_applicable_6
    ),
    mbot114 = list(
      `3B` = right_side_left_side_not_applicable_3
    ),
    mbot115 = list(
      `3B` = right_side_left_side_not_applicable_3
    ),
    mbot2_4 = list(
      `3B` = wrist_colles_humerus_hand_fingers_2,
      C = pulse_wrist_colles_forearm_humerus_hand_fingers_3
    ),
    mbot2_5 = list(
      `3B` = wrist_colles_humerus_hand_fingers_2,
      C = pulse_wrist_colles_forearm_humerus_hand_fingers_3
    ),
    mbot41d = list(
      `3B` = na_asked,
      F = na_see_fmbot1_na_asked,
      G = na_see_gmbot_na_asked,
      H = na_asked,
      I = na_asked,
      J = na_asked,
      K = c(`-3` = "na, see KMFALLFRACD", `-2` = "na, see KMBOT#", `-1` = "na, asked"),
      MB = na_see_bmbot_na_asked
    ),
    mbot41m = list(
      `3B` = january_february_march_april_may_june_july_august_8,
      F = january_february_march_april_may_june_july_august_17,
      G = january_february_march_april_may_june_july_august_18,
      H = january_february_march_april_may_june_july_august_47,
      I = january_february_march_april_may_june_july_august_47,
      J = january_february_march_april_may_june_july_august_48,
      K = c(
        `-3` = "na, see KMFALLFRACM",
        `-2` = "na, see KMBOT#",
        `-1` = "na, asked",
        `1` = "January",
        `2` = "February",
        `3` = "March",
        `4` = "April",
        `5` = "May",
        `6` = "June",
        `7` = "July",
        `8` = "August",
        `9` = "September",
        `10` = "October",
        `11` = "November",
        `12` = "December"
      ),
      MB = january_february_march_april_may_june_july_august_19
    ),
    mbot41y = list(
      `3B` = na_see_h_b_imbot1_na_asked,
      F = na_see_fmbot1_na_asked,
      G = na_see_gmbot_na_asked,
      H = na_see_h_b_imbot1_na_asked,
      I = na_see_h_b_imbot1_na_asked,
      J = na_see_jmbot_na_asked,
      K = c(`-3` = "na, see KMFALLFRACY", `-2` = "na, see KMBOT#", `-1` = "na, asked"),
      MB = na_see_bmbot_na_asked
    ),
    mbot42d = list(
      `3B` = na_see_h_b_imbot1_na_asked,
      F = na_see_fmbot1_na_asked,
      G = na_see_gmbot_na_asked,
      H = na_see_h_b_imbot1_na_asked,
      I = na_see_h_b_imbot1_na_asked,
      J = na_see_jmbot_na_asked,
      K = na_see_kmbot_na_asked,
      MB = na_see_bmbot_na_asked
    ),
    mbot42m = list(
      `3B` = january_february_march_april_may_june_july_august_8,
      F = january_february_march_april_may_june_july_august_17,
      G = january_february_march_april_may_june_july_august_18,
      H = january_february_march_april_may_june_july_august_8,
      I = january_february_march_april_may_june_july_august_8,
      J = january_february_march_april_may_june_july_august_48,
      K = january_february_march_april_may_june_july_august_49,
      MB = january_february_march_april_may_june_july_august_19
    ),
    mbot42y = list(
      `3B` = na_see_h_b_imbot1_na_asked,
      F = na_see_fmbot1_na_asked,
      G = na_see_gmbot_na_asked,
      H = na_see_h_b_imbot1_na_asked,
      I = na_see_h_b_imbot1_na_asked,
      J = c(`-2` = "na, see JMBOT1#", `-1` = "na, asked"),
      K = na_see_kmbot_na_asked,
      MB = na_see_bmbot_na_asked
    ),
    mbot43d = list(
      `3B` = na_see_h_b_imbot1_na_asked,
      F = na_see_fmbot1_na_asked,
      G = na_see_gmbot_na_asked,
      H = na_see_h_b_imbot1_na_asked,
      I = na_see_h_b_imbot1_na_asked,
      J = na_see_jmbot_na_asked,
      K = na_see_kmbot_na_asked,
      MB = na_see_bmbot_na_asked
    ),
    mbot43m = list(
      `3B` = january_february_march_april_may_june_july_august_8,
      F = january_february_march_april_may_june_july_august_17,
      G = january_february_march_april_may_june_july_august_18,
      H = january_february_march_april_may_june_july_august_8,
      I = january_february_march_april_may_june_july_august_8,
      J = c(
        `-2` = "na, see JMBOT1#",
        `-1` = "na, asked",
        `1` = "January",
        `2` = "February",
        `3` = "March",
        `4` = "April",
        `5` = "May",
        `6` = "June",
        `7` = "July",
        `8` = "August",
        `9` = "September",
        `10` = "October",
        `11` = "November",
        `12` = "December"
      ),
      K = january_february_march_april_may_june_july_august_49,
      MB = january_february_march_april_may_june_july_august_19
    ),
    mbot43y = list(
      `3B` = na_see_h_b_imbot1_na_asked,
      F = na_see_fmbot1_na_asked,
      G = na_see_gmbot_na_asked,
      H = na_see_h_b_imbot1_na_asked,
      I = na_see_h_b_imbot1_na_asked,
      J = na_see_jmbot_na_asked,
      K = na_see_kmbot_na_asked,
      MB = na_see_bmbot_na_asked
    ),
    mbot44d = list(
      `3B` = na_see_bmbot1_na_asked
    ),
    mbot44m = list(
      `3B` = january_february_march_april_may_june_july_august_13
    ),
    mbot44y = list(
      `3B` = na_see_bmbot1_na_asked
    ),
    mbot45d = list(
      `3B` = na_see_bmbot1_na_asked
    ),
    mbot45m = list(
      `3B` = january_february_march_april_may_june_july_august_13
    ),
    mbot45y = list(
      `3B` = na_see_bmbot1_na_asked
    ),
    mbot54 = list(
      `3B` = fall_from_standing_height_or_fall_from_standing_height_2,
      C = fall_standing_height_fall_standing_height_2
    ),
    mbot55 = list(
      `3B` = fall_from_standing_height_or_fall_from_standing_height_2,
      C = fall_standing_height_fall_standing_height_2
    ),
    mhipplm = list(
      `3B` = january_february_march_april_may_june_july_august_50,
      D = january_february_march_april_may_june_july_august_14
    ),
    mhipprm = list(
      `3B` = january_february_march_april_may_june_july_august_50,
      D = january_february_march_april_may_june_july_august_14
    ),
    mbot101 = list(
      C = na_wrong_skip_na_see_cmbot8
    ),
    mbot102 = list(
      C = na_wrong_skip_na_see_cmbot8
    ),
    mbot103 = list(
      C = na_wrong_skip_na_see_cmbot8
    ),
    mbot104 = list(
      C = na_wrong_skip_na_see_cmbot8
    ),
    mbot105 = list(
      C = na_wrong_skip_na_see_cmbot8
    ),
    mbot31 = list(
      C = january_february_march_april_may_june_july_august_4
    ),
    mbot32 = list(
      C = january_february_march_april_may_june_july_august_4
    ),
    mbot33 = list(
      C = january_february_march_april_may_june_july_august_4
    ),
    mbot34 = list(
      C = january_february_march_april_may_june_july_august_4
    ),
    mbot35 = list(
      C = january_february_march_april_may_june_july_august_4
    ),
    mbot44 = list(
      C = na_wrong_skip_na_see_cmbot1_na_asked
    ),
    mbot45 = list(
      C = na_wrong_skip_na_see_cmbot1_na_asked
    ),
    mbot8 = list(
      C = no_yes_5
    ),
    `mbot8#` = list(
      C = na_wrong_skip_na_see_cmbot8_2
    ),
    mbot91 = list(
      C = pulse_wrist_colles_forearm_humerus_hand_fingers
    ),
    mbot92 = list(
      C = pulse_wrist_colles_forearm_humerus_hand_fingers
    ),
    mbot93 = list(
      C = pulse_wrist_colles_forearm_humerus_hand_fingers
    ),
    mbot94 = list(
      C = pulse_wrist_colles_forearm_humerus_hand_fingers
    ),
    mbot95 = list(
      C = pulse_wrist_colles_forearm_humerus_hand_fingers
    ),
    mbot121 = list(
      F = no_yes_109,
      G = no_yes_110,
      H = no_yes_51,
      I = no_yes_51,
      J = no_yes_26,
      K = no_yes_83
    ),
    mbot122 = list(
      F = no_yes_109,
      G = no_yes_110,
      H = no_yes_51,
      I = no_yes_51,
      J = c(`-2` = "na, see H/IMBOT#", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      K = no_yes_83
    ),
    mbot123 = list(
      F = no_yes_109,
      G = no_yes_110,
      H = no_yes_51,
      I = no_yes_51,
      J = no_yes_26,
      K = no_yes_83
    ),
    mbot131 = list(
      F = no_yes_109,
      G = no_yes_110,
      H = no_yes_51,
      J = no_yes_26
    ),
    mbot132 = list(
      F = no_yes_109,
      G = no_yes_110,
      H = no_yes_51,
      I = no_yes_51,
      J = no_yes_26
    ),
    mbot133 = list(
      F = no_yes_109,
      G = no_yes_110,
      H = no_yes_51,
      I = no_yes_51,
      J = no_yes_26
    ),
    mkneply = list(
      H = na_see_h_imknepro_na_asked,
      I = na_see_h_imknepro_na_asked,
      J = na_see_jmknepro_na_asked,
      K = na_see_kmknepro_na_asked
    ),
    mknepro = list(
      H = no_left_right_left_and_right,
      I = no_left_right_left_and_right,
      J = no_left_right_left_and_right,
      K = no_left_right_left_and_right
    ),
    mknepry = list(
      H = na_see_h_imknepro_na_asked,
      I = na_see_h_imknepro_na_asked,
      J = na_see_jmknepro_na_asked,
      K = na_see_kmknepro_na_asked
    ),
    mconsx1 = list(
      J = no_yes_26,
      K = no_yes_83
    ),
    mconsx2 = list(
      J = no_yes_26,
      K = no_yes_83
    ),
    mconsx3 = list(
      J = no_yes_26,
      K = no_yes_83
    ),
    mfallfrac = list(
      J = fall_no_yes,
      K = fall_no_yes
    ),
    mfallfracd = list(
      J = na_see_jmfallfrac_na_asked,
      K = na_see_kmfallfrac_na_asked
    ),
    mfallfracm = list(
      J = january_february_march_april_may_june_july_august_51,
      K = c(
        `-2` = "na, see KMFALLFRAC",
        `-1` = "na, asked",
        `1` = "January",
        `2` = "February",
        `3` = "March",
        `4` = "April",
        `5` = "May",
        `6` = "June",
        `7` = "July",
        `8` = "August",
        `9` = "September",
        `10` = "October",
        `11` = "November",
        `12` = "December"
      )
    ),
    mfallfracy = list(
      J = na_see_jmfallfrac_na_asked,
      K = na_see_kmfallfrac_na_asked
    ),
    mbot2 = list(
      K = no_yes_145
    ),
    mbot3 = list(
      K = no_yes_145
    )
  ),

  value_labels_harmonized = list(
    mbot1 = c(
      `-5` = "na, interview terminated",
      `-2` = "na, see JMFALLFRAC",
      `-1` = "na, asked",
      `1` = "no",
      `2` = "yes"
    ),
    `mbot1#` = c(`-3` = "na, wrong skip", `-2` = "na, see CMBOT1", `-1` = "na, asked"),
    mbot101 = na_wrong_skip_na_see_cmbot8,
    mbot102 = na_wrong_skip_na_see_cmbot8,
    mbot103 = na_wrong_skip_na_see_cmbot8,
    mbot104 = na_wrong_skip_na_see_cmbot8,
    mbot105 = na_wrong_skip_na_see_cmbot8,
    mbot111 = right_side_left_side_not_applicable_2,
    mbot112 = right_side_left_side_not_applicable_2,
    mbot113 = right_side_left_side_not_applicable_2,
    mbot114 = right_side_left_side_not_applicable_3,
    mbot115 = right_side_left_side_not_applicable_3,
    mbot121 = no_yes_26,
    mbot122 = no_yes_83,
    mbot123 = no_yes_26,
    mbot131 = no_yes_26,
    mbot132 = no_yes_26,
    mbot133 = no_yes_26,
    mbot2 = no_yes_145,
    mbot2_1 = wrist_colles_humerus_hand_fingers_7,
    mbot2_2 = c(
      `-3` = "na, wrong skip",
      `-2` = "na, see KMBOT#",
      `-1` = "na, asked",
      `1` = "wrist, colles",
      `2` = "humerus",
      `3` = "hand, fingers",
      `4` = "other upper extremities",
      `5` = "rib",
      `6` = "pelvis",
      `7` = "ankle",
      `8` = "feet, toes",
      `9` = "hip",
      `10` = "other lower extremities",
      `11` = "head, neck",
      `12` = "vertebra",
      `13` = "unknown"
    ),
    mbot2_3 = wrist_colles_humerus_hand_fingers_7,
    mbot2_4 = wrist_colles_humerus_hand_fingers_8,
    mbot2_5 = wrist_colles_humerus_hand_fingers_8,
    mbot3 = no_yes_145,
    mbot31 = january_february_march_april_may_june_july_august_4,
    mbot32 = january_february_march_april_may_june_july_august_4,
    mbot33 = january_february_march_april_may_june_july_august_4,
    mbot34 = january_february_march_april_may_june_july_august_4,
    mbot35 = january_february_march_april_may_june_july_august_4,
    mbot41 = na_wrong_skip_na_see_cmbot1_na_asked,
    mbot41d = c(`-3` = "na, see KMFALLFRACD", `-2` = "na, see FMBOT1", `-1` = "na, asked"),
    mbot41m = c(
      `-3` = "missing / source-specific",
      `-2` = "na, see FMBOT1",
      `-1` = "na, asked",
      `1` = "January",
      `2` = "February",
      `3` = "March",
      `4` = "April",
      `5` = "May",
      `6` = "June",
      `7` = "July",
      `8` = "August",
      `9` = "September",
      `10` = "October",
      `11` = "November",
      `12` = "December"
    ),
    mbot41y = c(`-3` = "na, see KMFALLFRACY", `-2` = "na, see FMBOT1", `-1` = "na, asked"),
    mbot42 = na_wrong_skip_na_see_cmbot1_na_asked,
    mbot42d = na_see_fmbot1_na_asked,
    mbot42m = january_february_march_april_may_june_july_august_52,
    mbot42y = na_see_fmbot1_na_asked,
    mbot43 = na_wrong_skip_na_see_cmbot1_na_asked,
    mbot43d = na_see_fmbot1_na_asked,
    mbot43m = january_february_march_april_may_june_july_august_52,
    mbot43y = na_see_fmbot1_na_asked,
    mbot44 = na_wrong_skip_na_see_cmbot1_na_asked,
    mbot44d = na_see_bmbot1_na_asked,
    mbot44m = january_february_march_april_may_june_july_august_13,
    mbot44y = na_see_bmbot1_na_asked,
    mbot45 = na_wrong_skip_na_see_cmbot1_na_asked,
    mbot45d = na_see_bmbot1_na_asked,
    mbot45m = january_february_march_april_may_june_july_august_13,
    mbot45y = na_see_bmbot1_na_asked,
    mbot51 = fall_standing_height_fall_standing_height_6,
    mbot52 = c(
      `-3` = "na, wrong skip",
      `-2` = "na, see JMBOT#",
      `-1` = "na, asked",
      `1` = "fall>standing height",
      `2` = "fall<standing height",
      `3` = "fall from bike",
      `4` = "other",
      `5` = "other"
    ),
    mbot53 = fall_standing_height_fall_standing_height_6,
    mbot54 = fall_standing_height_fall_standing_height_7,
    mbot55 = fall_standing_height_fall_standing_height_7,
    mbot6 = c(`-5` = "na, interview terminated", `-1` = "na, asked", `1` = "no", `2` = "no"),
    mbot62 = not_mentioned_no_yes,
    mbot63 = not_mentioned_no_yes,
    mbot64 = not_mentioned_no_yes,
    mbot65 = not_mentioned_no_yes,
    mbot8 = no_yes_5,
    `mbot8#` = na_wrong_skip_na_see_cmbot8_2,
    mbot91 = pulse_wrist_colles_forearm_humerus_hand_fingers,
    mbot92 = pulse_wrist_colles_forearm_humerus_hand_fingers,
    mbot93 = pulse_wrist_colles_forearm_humerus_hand_fingers,
    mbot94 = pulse_wrist_colles_forearm_humerus_hand_fingers,
    mbot95 = pulse_wrist_colles_forearm_humerus_hand_fingers,
    mconsx1 = no_yes_26,
    mconsx2 = no_yes_26,
    mconsx3 = no_yes_26,
    mfallfrac = fall_no_yes,
    mfallfracd = na_see_jmfallfrac_na_asked,
    mfallfracm = january_february_march_april_may_june_july_august_51,
    mfallfracy = na_see_jmfallfrac_na_asked,
    mhippl = no_yes_left,
    mhipplm = january_february_march_april_may_june_july_august_14,
    mhipply = na_see_bmhippl_na_asked,
    mhippr = no_yes_right,
    mhipprm = january_february_march_april_may_june_july_august_14,
    mhippro = c(`-1` = "na, asked", `1` = "no", `2` = "no", `3` = "right", `4` = "left and right"),
    mhippry = na_see_bmhippr_na_asked,
    mkneply = na_see_jmknepro_na_asked,
    mknepro = no_left_right_left_and_right,
    mknepry = na_see_jmknepro_na_asked
  )
)
