## LASA filecode 110 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_110 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bqimpor1",
      "bqimpor2",
      "bqimpor3",
      "bqimpor4",
      "bqimpor5",
      "bqimpor6",
      "bqimpor7",
      "bqimpor8",
      "bqimpor9",
      "bqnansw",
      "bqsatis1",
      "bqsatis2",
      "bqimpor1",
      "bqimpor2",
      "bqimpor3",
      "bqimpor4",
      "bqimpor5",
      "bqimpor6",
      "bqimpor7",
      "bqimpor8",
      "bqimpor9",
      "bqnansw",
      "bqsatis1",
      "bqsatis2",
      "bqimpor1",
      "bqimpor2",
      "bqimpor3",
      "bqimpor4",
      "bqimpor5",
      "bqimpor6",
      "bqimpor7",
      "bqimpor8",
      "bqimpor9",
      "bqnansw",
      "bqsatis1",
      "bqsatis2",
      "cqimpor1",
      "cqimpor2",
      "cqimpor3",
      "cqimpor4",
      "cqimpor5",
      "cqimpor6",
      "cqimpor7",
      "cqimpor8",
      "cqimpor9",
      "cqnansw",
      "cqsatis1",
      "cqsatis2",
      "dqimpor1",
      "dqimpor2",
      "dqimpor3",
      "dqimpor4",
      "dqimpor5",
      "dqimpor6",
      "dqimpor7",
      "dqimpor8",
      "dqimpor9",
      "dqnansw",
      "dqsatis1",
      "dqsatis2",
      "eqimpor1",
      "eqimpor2",
      "eqimpor3",
      "eqimpor4",
      "eqimpor5",
      "eqimpor6",
      "eqimpor7",
      "eqimpor8",
      "eqimpor9",
      "eqnansw",
      "eqsatis1",
      "eqsatis2",
      "fqimpor1",
      "fqimpor2",
      "fqimpor3",
      "fqimpor4",
      "fqimpor5",
      "fqimpor6",
      "fqimpor7",
      "fqimpor8",
      "fqimpor9",
      "fqnansw",
      "fqsatis1",
      "fqsatis2",
      "gqimpor1",
      "gqimpor2",
      "gqimpor3",
      "gqimpor4",
      "gqimpor5",
      "gqimpor6",
      "gqimpor7",
      "gqimpor8",
      "gqimpor9",
      "gqnansw",
      "gqsatis1",
      "gqsatis2",
      "hqimpor1",
      "hqimpor2",
      "hqimpor3",
      "hqimpor4",
      "hqimpor5",
      "hqimpor6",
      "hqimpor7",
      "hqimpor8",
      "hqimpor9",
      "hqnansw",
      "hqsatis1",
      "hqsatis2",
      "hqsatis3",
      "hqsatis4",
      "iqimpor1",
      "iqimpor2",
      "iqimpor3",
      "iqimpor4",
      "iqimpor5",
      "iqimpor6",
      "iqimpor7",
      "iqimpor8",
      "iqimpor9",
      "iqnansw",
      "iqsatis1",
      "iqsatis2",
      "iqsatis3",
      "iqsatis4",
      "jqimpor1",
      "jqimpor2",
      "jqimpor3",
      "jqimpor4",
      "jqimpor5",
      "jqimpor6",
      "jqimpor7",
      "jqimpor8",
      "jqimpor9",
      "jqnansw",
      "jqsatis1",
      "jqsatis2",
      "jqsatis3",
      "jqsatis4",
      "kqimpor1",
      "kqimpor2",
      "kqimpor3",
      "kqimpor4",
      "kqimpor5",
      "kqimpor6",
      "kqimpor7",
      "kqimpor8",
      "kqimpor9",
      "kqnansw",
      "kqsatis1",
      "kqsatis2"
    ),
    canonical_name = c(
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qsatis3",
      "qsatis4",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qsatis3",
      "qsatis4",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2",
      "qsatis3",
      "qsatis4",
      "qimpor1",
      "qimpor2",
      "qimpor3",
      "qimpor4",
      "qimpor5",
      "qimpor6",
      "qimpor7",
      "qimpor8",
      "qimpor9",
      "qnansw",
      "qsatis1",
      "qsatis2"
    ),
    variable_label = c(
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "satisfied with life: now score from 0 to 10",
      "satisfied with life: now compared to year ago",
      "good income",
      "nice family",
      "good physical health",
      "meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "satisfied with life: now score from 0 to 10",
      "satisfied with life: now compared to year ago",
      "good income",
      "nice family",
      "good physical health",
      "meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "satisfied with life: now score from 0 to 10",
      "satisfied with life: now compared to year ago",
      "good income",
      "nice family",
      "good physical health",
      "meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now"
    ),
    harmonized_var_label = c(
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "satisfied with life: now score from 0 to 10",
      "satisfied with life: now compared to year ago",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "satisfied with life: now score from 0 to 10",
      "satisfied with life: now compared to year ago",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now",
      "satisfied with life: now score from 0 to 10",
      "satisfied with life: now compared to year ago",
      "good income",
      "nice family",
      "good physical health",
      "sensible spending of time / meaningful pastime",
      "good marital life",
      "strong faith",
      "good mental health",
      "many friends and acquaintances",
      "good housing",
      "number of answers given on 9 items",
      "satisfied with life: lately",
      "satisfied with life: until now"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qimpor1 = list(
      `2B` = mentioned_not_mentioned,
      `3B` = mentioned_not_mentioned,
      B = mentioned_not_mentioned,
      C = mentioned_not_mentioned,
      D = mentioned_not_mentioned,
      E = mentioned_not_mentioned,
      F = mentioned_not_mentioned,
      G = mentioned_not_mentioned,
      H = mentioned_not_mentioned,
      I = mentioned_not_mentioned,
      J = mentioned_not_mentioned,
      K = mentioned_not_mentioned
    ),
    qimpor2 = list(
      `2B` = mentioned_not_mentioned,
      `3B` = mentioned_not_mentioned,
      B = mentioned_not_mentioned,
      C = mentioned_not_mentioned,
      D = mentioned_not_mentioned,
      E = mentioned_not_mentioned,
      F = mentioned_not_mentioned,
      G = mentioned_not_mentioned,
      H = mentioned_not_mentioned,
      I = mentioned_not_mentioned,
      J = mentioned_not_mentioned,
      K = mentioned_not_mentioned
    ),
    qimpor3 = list(
      `2B` = mentioned_not_mentioned,
      `3B` = mentioned_not_mentioned,
      B = mentioned_not_mentioned,
      C = mentioned_not_mentioned,
      D = mentioned_not_mentioned,
      E = mentioned_not_mentioned,
      F = mentioned_not_mentioned,
      G = mentioned_not_mentioned,
      H = mentioned_not_mentioned,
      I = mentioned_not_mentioned,
      J = mentioned_not_mentioned,
      K = mentioned_not_mentioned
    ),
    qimpor4 = list(
      `2B` = mentioned_not_mentioned,
      `3B` = mentioned_not_mentioned,
      B = mentioned_not_mentioned,
      C = mentioned_not_mentioned,
      D = mentioned_not_mentioned,
      E = mentioned_not_mentioned,
      F = mentioned_not_mentioned,
      G = mentioned_not_mentioned,
      H = mentioned_not_mentioned,
      I = mentioned_not_mentioned,
      J = mentioned_not_mentioned,
      K = mentioned_not_mentioned
    ),
    qimpor5 = list(
      `2B` = mentioned_not_mentioned,
      `3B` = mentioned_not_mentioned,
      B = mentioned_not_mentioned,
      C = mentioned_not_mentioned,
      D = mentioned_not_mentioned,
      E = mentioned_not_mentioned,
      F = mentioned_not_mentioned,
      G = mentioned_not_mentioned,
      H = mentioned_not_mentioned,
      I = mentioned_not_mentioned,
      J = mentioned_not_mentioned,
      K = mentioned_not_mentioned
    ),
    qimpor6 = list(
      `2B` = mentioned_not_mentioned,
      `3B` = mentioned_not_mentioned,
      B = mentioned_not_mentioned,
      C = mentioned_not_mentioned,
      D = mentioned_not_mentioned,
      E = mentioned_not_mentioned,
      F = mentioned_not_mentioned,
      G = mentioned_not_mentioned,
      H = mentioned_not_mentioned,
      I = mentioned_not_mentioned,
      J = mentioned_not_mentioned,
      K = mentioned_not_mentioned
    ),
    qimpor7 = list(
      `2B` = mentioned_not_mentioned,
      `3B` = mentioned_not_mentioned,
      B = mentioned_not_mentioned,
      C = mentioned_not_mentioned,
      D = mentioned_not_mentioned,
      E = mentioned_not_mentioned,
      F = mentioned_not_mentioned,
      G = mentioned_not_mentioned,
      H = mentioned_not_mentioned,
      I = mentioned_not_mentioned,
      J = mentioned_not_mentioned,
      K = mentioned_not_mentioned
    ),
    qimpor8 = list(
      `2B` = mentioned_not_mentioned,
      `3B` = mentioned_not_mentioned,
      B = mentioned_not_mentioned,
      C = mentioned_not_mentioned,
      D = mentioned_not_mentioned,
      E = mentioned_not_mentioned,
      F = mentioned_not_mentioned,
      G = mentioned_not_mentioned,
      H = mentioned_not_mentioned,
      I = mentioned_not_mentioned,
      J = mentioned_not_mentioned,
      K = mentioned_not_mentioned
    ),
    qimpor9 = list(
      `2B` = mentioned_not_mentioned,
      `3B` = mentioned_not_mentioned,
      B = mentioned_not_mentioned,
      C = mentioned_not_mentioned,
      D = mentioned_not_mentioned,
      E = mentioned_not_mentioned,
      F = mentioned_not_mentioned,
      G = mentioned_not_mentioned,
      H = mentioned_not_mentioned,
      I = mentioned_not_mentioned,
      J = mentioned_not_mentioned,
      K = mentioned_not_mentioned
    ),
    qnansw = list(
      `2B` = none_mentioned_1_mentioned_9_mentioned,
      `3B` = none_mentioned_1_mentioned_9_mentioned,
      B = none_mentioned_1_mentioned_9_mentioned,
      C = none_mentioned_1_mentioned_9_mentioned,
      D = none_mentioned_1_mentioned_9_mentioned,
      E = none_mentioned_1_mentioned_9_mentioned,
      F = none_mentioned_1_mentioned_9_mentioned,
      G = none_mentioned_1_mentioned_9_mentioned,
      H = none_mentioned_1_mentioned_9_mentioned,
      I = none_mentioned_1_mentioned_9_mentioned,
      J = none_mentioned_1_mentioned_9_mentioned,
      K = none_mentioned_1_mentioned_9_mentioned
    ),
    qsatis1 = list(
      `2B` = very_dissatisfied_dissatisfied,
      `3B` = very_dissatisfied_dissatisfied,
      B = very_dissatisfied_dissatisfied,
      C = very_dissatisfied_dissatisfied,
      D = very_dissatisfied_dissatisfied,
      E = very_dissatisfied_dissatisfied,
      F = very_dissatisfied_dissatisfied,
      G = very_dissatisfied_dissatisfied,
      H = very_dissatisfied_dissatisfied,
      I = very_dissatisfied_dissatisfied,
      J = very_dissatisfied_dissatisfied,
      K = very_dissatisfied_dissatisfied
    ),
    qsatis2 = list(
      `2B` = very_dissatisfied_dissatisfied,
      `3B` = very_dissatisfied_dissatisfied,
      B = very_dissatisfied_dissatisfied,
      C = very_dissatisfied_dissatisfied,
      D = very_dissatisfied_dissatisfied,
      E = very_dissatisfied_dissatisfied,
      F = very_dissatisfied_dissatisfied,
      G = very_dissatisfied_dissatisfied,
      H = very_dissatisfied_dissatisfied,
      I = very_dissatisfied_dissatisfied,
      J = very_dissatisfied_dissatisfied,
      K = very_dissatisfied_dissatisfied
    ),
    qsatis3 = list(
      H = no_answer_3,
      I = no_answer_3,
      J = no_answer_3
    ),
    qsatis4 = list(
      H = much_more_satisfied_more_satisfied_equally_satisfied,
      I = much_more_satisfied_more_satisfied_equally_satisfied,
      J = much_more_satisfied_more_satisfied_equally_satisfied
    )
  ),

  value_labels_harmonized = list(
    qimpor1 = mentioned_not_mentioned_2,
    qimpor2 = mentioned_not_mentioned_2,
    qimpor3 = mentioned_not_mentioned_2,
    qimpor4 = mentioned_not_mentioned_2,
    qimpor5 = mentioned_not_mentioned_2,
    qimpor6 = mentioned_not_mentioned_2,
    qimpor7 = mentioned_not_mentioned_2,
    qimpor8 = mentioned_not_mentioned_2,
    qimpor9 = mentioned_not_mentioned_2,
    qnansw = none_mentioned_1_mentioned_9_mentioned,
    qsatis1 = very_dissatisfied_dissatisfied_2,
    qsatis2 = very_dissatisfied_dissatisfied_2,
    qsatis3 = c(`-1` = "not available", `0` = NA_character_, `10` = NA_character_),
    qsatis4 = c(
      `-1` = "not available",
      `1` = "much more satisfied",
      `2` = "more satisfied",
      `3` = "equally satisfied",
      `4` = "less dissatisfied",
      `5` = "much less satisfied"
    )
  )
)
