## LASA filecode 157 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_157 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F"
    ),
    variable_name = c(
      "bmdasig1",
      "bmdasig2",
      "bmdasig3",
      "bmdasig4",
      "bmdasig5",
      "bmdasig6",
      "bmcontra",
      "bmctinch",
      "bmctley1",
      "bmctley2",
      "bmctley3",
      "bmctley4",
      "bmctley5",
      "bmctpart",
      "bmctrey1",
      "bmctrey2",
      "bmctrey3",
      "bmctrey4",
      "bmctrey5",
      "bmctunde",
      "bmdasig1",
      "bmdasig2",
      "bmdasig3",
      "bmlecont",
      "bmricont",
      "cmctglas",
      "cmctinch",
      "cmctley1",
      "cmctley2",
      "cmctley3",
      "cmctley4",
      "cmctley5",
      "cmctpart",
      "cmctrey1",
      "cmctrey2",
      "cmctrey3",
      "cmctrey4",
      "cmctrey5",
      "cmctrm",
      "cmctunde",
      "cmdasig1",
      "cmdasig2",
      "cmdasig3",
      "cmeyetes",
      "dmctglcl",
      "dmctinch",
      "dmctley1",
      "dmctley2",
      "dmctley3",
      "dmctley4",
      "dmctley5",
      "dmctpart",
      "dmctrey1",
      "dmctrey2",
      "dmctrey3",
      "dmctrey4",
      "dmctrey5",
      "dmctunde",
      "dmdasig1",
      "dmdasig2",
      "dmdasig3",
      "dmdasig4",
      "dmdasig5",
      "dmdasig6",
      "emdasig1",
      "emdasig2",
      "emdasig3",
      "emdasig4",
      "emdasig5",
      "emdasig6",
      "fmdasig1",
      "fmdasig2",
      "fmdasig3",
      "fmdasig4",
      "fmdasig5",
      "fmdasig6"
    ),
    canonical_name = c(
      "mdasig1",
      "mdasig2",
      "mdasig3",
      "mdasig4",
      "mdasig5",
      "mdasig6",
      "mcontra",
      "mctinch",
      "mctley1",
      "mctley2",
      "mctley3",
      "mctley4",
      "mctley5",
      "mctpart",
      "mctrey1",
      "mctrey2",
      "mctrey3",
      "mctrey4",
      "mctrey5",
      "mctunde",
      "mdasig1",
      "mdasig2",
      "mdasig3",
      "mlecont",
      "mricont",
      "mctglas",
      "mctinch",
      "mctley1",
      "mctley2",
      "mctley3",
      "mctley4",
      "mctley5",
      "mctpart",
      "mctrey1",
      "mctrey2",
      "mctrey3",
      "mctrey4",
      "mctrey5",
      "mctrm",
      "mctunde",
      "mdasig1",
      "mdasig2",
      "mdasig3",
      "meyetes",
      "mctglcl",
      "mctinch",
      "mctley1",
      "mctley2",
      "mctley3",
      "mctley4",
      "mctley5",
      "mctpart",
      "mctrey1",
      "mctrey2",
      "mctrey3",
      "mctrey4",
      "mctrey5",
      "mctunde",
      "mdasig1",
      "mdasig2",
      "mdasig3",
      "mdasig4",
      "mdasig5",
      "mdasig6",
      "mdasig1",
      "mdasig2",
      "mdasig3",
      "mdasig4",
      "mdasig5",
      "mdasig6",
      "mdasig1",
      "mdasig2",
      "mdasig3",
      "mdasig4",
      "mdasig5",
      "mdasig6"
    ),
    variable_label = c(
      "Daily sight: see better cloudy vs sunny weather",
      "Daily sight: blinded on clear day",
      "Daily sight: blinded when indoor/outdoor",
      "Daily sight: see bicycles and cars approaching",
      "Daily sight: regularly do not see doors and chairs",
      "Daily sight: regularly do not see floor related objects",
      "contrast: total score low-high",
      "contrast: inch",
      "contrast: left eye A",
      "contrast: left eye B",
      "contrast: left eye C",
      "contrast: left eye D",
      "contrast: left eye E",
      "participation with contrast test",
      "contrast: right eye A",
      "contrast: right eye B",
      "contrast: right eye C",
      "contrast: right eye D",
      "contrast: right eye E",
      "understanding of contrast test",
      "weather: cloudy",
      "weather: clear sky",
      "sight: blinded by indoor/outdoor",
      "left eye: total score low-high",
      "right eye: total score low-high",
      "during test: glasses or contact lenses",
      "contrast: inch",
      "contrast: left eye A",
      "contrast: left eye B",
      "contrast: left eye C",
      "contrast: left eye D",
      "contrast: left eye E",
      "participation with contrast test",
      "contrast: right eye A",
      "contrast: right eye B",
      "contrast: right eye C",
      "contrast: right eye D",
      "contrast: right eye E",
      "reason contrast test not done",
      "understanding of contrast test",
      "weather: cloudy",
      "weather: clear sky",
      "weather: blinded by indoor/outdoor",
      "Eye contrast test done: constructed",
      "contrast test: with glasses or contact lenses",
      "contast test: inch",
      "contrast test: left eye A",
      "contrast test: left eye B",
      "contrast test: left eye C",
      "contrast test: left eye D",
      "contrast test: left eye E",
      "participation with contrast test",
      "contrast test: right eye A",
      "contrast test: right eye B",
      "contrast test: right eye C",
      "contrast test: right eye D",
      "contrast test: right eye E",
      "understanding of contrast test",
      "Daily sight: see better cloudy vs sunny weather",
      "Daily sight: blinded on clear day",
      "Daily sight: blinded when indoor/outdoor",
      "Daily sight: see bicycles and cars approaching",
      "Daily sight: regularly do not see doors and chairs",
      "Daily sight: regularly do not see floor related objects",
      "Daily sight: see better cloudy vs sunny weather",
      "Daily sight: blinded on clear day",
      "Daily sight: blinded when indoor/outdoor",
      "Daily sight: see bicycles and cars approaching",
      "Daily sight: regularly do not see doors and chairs",
      "Daily sight: regularly do not see floor related objects",
      "Daily sight: see better cloudy vs sunny weather",
      "Daily sight: blinded on clear day",
      "Daily sight: blinded when indoor/outdoor",
      "Daily sight: see bicycles and cars approaching",
      "Daily sight: regularly do not see doors and chairs",
      "Daily sight: regularly do not see floor related objects"
    ),
    harmonized_var_label = c(
      "Daily sight: see better cloudy vs sunny weather",
      "Daily sight: blinded on clear day",
      "Daily sight: blinded by indoor/outdoor",
      "Daily sight: see bicycles and cars approaching",
      "Daily sight: regularly do not see doors and chairs",
      "Daily sight: regularly do not see floor related objects",
      "contrast: total score low-high",
      "contrast: inch",
      "contrast: left eye A",
      "contrast: left eye B",
      "contrast: left eye C",
      "contrast: left eye D",
      "contrast: left eye E",
      "participation with contrast test",
      "contrast: right eye A",
      "contrast: right eye B",
      "contrast: right eye C",
      "contrast: right eye D",
      "contrast: right eye E",
      "understanding of contrast test",
      "Daily sight: see better cloudy vs sunny weather",
      "Daily sight: blinded on clear day",
      "Daily sight: blinded by indoor/outdoor",
      "left eye: total score low-high",
      "right eye: total score low-high",
      "during test: glasses or contact lenses",
      "contrast: inch",
      "contrast: left eye A",
      "contrast: left eye B",
      "contrast: left eye C",
      "contrast: left eye D",
      "contrast: left eye E",
      "participation with contrast test",
      "contrast: right eye A",
      "contrast: right eye B",
      "contrast: right eye C",
      "contrast: right eye D",
      "contrast: right eye E",
      "reason contrast test not done",
      "understanding of contrast test",
      "Daily sight: see better cloudy vs sunny weather",
      "Daily sight: blinded on clear day",
      "Daily sight: blinded by indoor/outdoor",
      "Eye contrast test done: constructed",
      "contrast test: with glasses or contact lenses",
      "contrast: inch",
      "contrast: left eye A",
      "contrast: left eye B",
      "contrast: left eye C",
      "contrast: left eye D",
      "contrast: left eye E",
      "participation with contrast test",
      "contrast: right eye A",
      "contrast: right eye B",
      "contrast: right eye C",
      "contrast: right eye D",
      "contrast: right eye E",
      "understanding of contrast test",
      "Daily sight: see better cloudy vs sunny weather",
      "Daily sight: blinded on clear day",
      "Daily sight: blinded by indoor/outdoor",
      "Daily sight: see bicycles and cars approaching",
      "Daily sight: regularly do not see doors and chairs",
      "Daily sight: regularly do not see floor related objects",
      "Daily sight: see better cloudy vs sunny weather",
      "Daily sight: blinded on clear day",
      "Daily sight: blinded by indoor/outdoor",
      "Daily sight: see bicycles and cars approaching",
      "Daily sight: regularly do not see doors and chairs",
      "Daily sight: regularly do not see floor related objects",
      "Daily sight: see better cloudy vs sunny weather",
      "Daily sight: blinded on clear day",
      "Daily sight: blinded by indoor/outdoor",
      "Daily sight: see bicycles and cars approaching",
      "Daily sight: regularly do not see doors and chairs",
      "Daily sight: regularly do not see floor related objects"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "text",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "text",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "text",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mdasig1 = list(
      `2B` = rarely_sometimes_often_almost_always,
      B = rarely_sometimes_often_almost_always_2,
      C = rarely_sometimes_often_almost_always_3,
      D = rarely_sometimes_often_almost_always,
      E = rarely_sometimes_often_almost_always,
      F = rarely_sometimes_often_almost_always
    ),
    mdasig2 = list(
      `2B` = rarely_sometimes_often_almost_always,
      B = rarely_sometimes_often_almost_always_2,
      C = rarely_sometimes_often_almost_always_3,
      D = rarely_sometimes_often_almost_always,
      E = rarely_sometimes_often_almost_always,
      F = rarely_sometimes_often_almost_always
    ),
    mdasig3 = list(
      `2B` = rarely_sometimes_often_almost_always,
      B = rarely_sometimes_often_almost_always_2,
      C = rarely_sometimes_often_almost_always_3,
      D = rarely_sometimes_often_almost_always,
      E = rarely_sometimes_often_almost_always,
      F = rarely_sometimes_often_almost_always
    ),
    mdasig4 = list(
      `2B` = rarely_sometimes_often_almost_always,
      D = rarely_sometimes_often_almost_always,
      E = rarely_sometimes_often_almost_always,
      F = rarely_sometimes_often_almost_always
    ),
    mdasig5 = list(
      `2B` = rarely_sometimes_often_almost_always,
      D = rarely_sometimes_often_almost_always,
      E = rarely_sometimes_often_almost_always,
      F = rarely_sometimes_often_almost_always
    ),
    mdasig6 = list(
      `2B` = rarely_sometimes_often_almost_always,
      D = rarely_sometimes_often_almost_always,
      E = rarely_sometimes_often_almost_always,
      F = rarely_sometimes_often_almost_always
    ),
    mcontra = list(
      B = no_valid_data_2
    ),
    mctinch = list(
      B = c(`-3` = "no valid data", `-2` = "no measurement done", `-1` = "no answer, asked"),
      C = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see CMEYETES",
        `1` = "30cm",
        `2` = "32cm",
        `3` = "40cm",
        `4` = "18inch [ca 46 cm]"
      ),
      D = no_measurement
    ),
    mctunde = list(
      B = c(
        `-3` = "no valid data",
        `-2` = "no measurement done",
        `-1` = "no answer, asked",
        `1` = "excellent",
        `2` = "good",
        `3` = "moderate",
        `4` = "bad",
        `5` = "refused",
        `6` = "other reason"
      ),
      C = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see CMEYETES",
        `-1` = "na, asked",
        `1` = "excellent",
        `2` = "good",
        `3` = "moderate",
        `4` = "bad",
        `10` = "other: not done",
        `20` = "other: not able to: phys",
        `30` = "other: not able to: cogn",
        `40` = "other: not done: technical"
      ),
      D = c(
        `-2` = "no measurement done",
        `-1` = "no answer, asked",
        `1` = "excellent",
        `2` = "good",
        `3` = "moderate",
        `4` = "bad",
        `5` = "refused",
        `6` = "other reason"
      )
    ),
    mlecont = list(
      B = no_valid_data_2
    ),
    mricont = list(
      B = no_valid_data_2
    ),
    mctglas = list(
      C = none_glasses_contact_lenses
    ),
    mctley1 = list(
      C = na_wrong_skip_na_see_cmeyetes_na_asked,
      D = no_measurement
    ),
    mctley2 = list(
      C = na_wrong_skip_na_see_cmeyetes_na_asked,
      D = no_measurement
    ),
    mctley3 = list(
      C = na_wrong_skip_na_see_cmeyetes_na_asked,
      D = no_measurement
    ),
    mctley4 = list(
      C = na_wrong_skip_na_see_cmeyetes_na_asked,
      D = no_measurement
    ),
    mctley5 = list(
      C = na_wrong_skip_na_see_cmeyetes_na_asked,
      D = no_measurement
    ),
    mctrey1 = list(
      C = na_wrong_skip_na_see_cmeyetes_na_asked,
      D = no_measurement
    ),
    mctrey2 = list(
      C = na_wrong_skip_na_see_cmeyetes_na_asked,
      D = no_measurement
    ),
    mctrey3 = list(
      C = na_wrong_skip_na_see_cmeyetes_na_asked,
      D = no_measurement
    ),
    mctrey4 = list(
      C = na_wrong_skip_na_see_cmeyetes_na_asked,
      D = no_measurement
    ),
    mctrey5 = list(
      C = na_wrong_skip_na_see_cmeyetes_na_asked,
      D = no_measurement
    ),
    mctrm = list(
      C = refused_not_able_to_cognitive_not_able_to_physical
    ),
    meyetes = list(
      C = done_not_done_no_right_eye_no_left_eye_terminated
    ),
    mctglcl = list(
      D = none_glasses_contact_lenses_2
    )
  ),

  value_labels_harmonized = list(
    mcontra = no_valid_data_2,
    mctglas = none_glasses_contact_lenses,
    mctglcl = none_glasses_contact_lenses_2,
    mctinch = c(
      `-3` = "no valid data / na, wrong skip",
      `-2` = "no measurement done / na, see CMEYETES",
      `-1` = "no answer, asked / no measurement",
      `1` = "30cm",
      `2` = "32cm",
      `3` = "40cm",
      `4` = "18inch [ca 46 cm]"
    ),
    mctley1 = na_wrong_skip_na_see_cmeyetes_na_asked_no_measurement,
    mctley2 = na_wrong_skip_na_see_cmeyetes_na_asked_no_measurement,
    mctley3 = na_wrong_skip_na_see_cmeyetes_na_asked_no_measurement,
    mctley4 = na_wrong_skip_na_see_cmeyetes_na_asked_no_measurement,
    mctley5 = na_wrong_skip_na_see_cmeyetes_na_asked_no_measurement,
    mctrey1 = na_wrong_skip_na_see_cmeyetes_na_asked_no_measurement,
    mctrey2 = na_wrong_skip_na_see_cmeyetes_na_asked_no_measurement,
    mctrey3 = na_wrong_skip_na_see_cmeyetes_na_asked_no_measurement,
    mctrey4 = na_wrong_skip_na_see_cmeyetes_na_asked_no_measurement,
    mctrey5 = na_wrong_skip_na_see_cmeyetes_na_asked_no_measurement,
    mctrm = refused_not_able_to_cognitive_not_able_to_physical,
    mctunde = c(
      `-3` = "no valid data / na, wrong skip",
      `-2` = "no measurement done / na, see CMEYETES",
      `-1` = "no answer, asked",
      `1` = "excellent",
      `2` = "good",
      `3` = "moderate",
      `4` = "bad",
      `5` = "refused",
      `6` = "other reason",
      `10` = "other: not done",
      `20` = "other: not able to: phys",
      `30` = "other: not able to: cogn",
      `40` = "other: not done: technical"
    ),
    mdasig1 = rarely_sometimes_often_almost_always_2,
    mdasig2 = rarely_sometimes_often_almost_always_2,
    mdasig3 = rarely_sometimes_often_almost_always_2,
    mdasig4 = rarely_sometimes_often_almost_always,
    mdasig5 = rarely_sometimes_often_almost_always,
    mdasig6 = rarely_sometimes_often_almost_always,
    meyetes = done_not_done_no_right_eye_no_left_eye_terminated,
    mlecont = no_valid_data_2,
    mricont = no_valid_data_2
  )
)
