## LASA filecode 012 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_012 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bbird",
      "bcat",
      "bdog",
      "bnspecie",
      "bpetothe",
      "bpets",
      "bbird",
      "bcat",
      "bdog",
      "bnspecie",
      "bpetothe",
      "bpets",
      "bbird",
      "bcat",
      "bdog",
      "bnspecie",
      "bpets",
      "bpetsoth",
      "cbird",
      "ccat",
      "cdog",
      "cnspecie",
      "cpetothe",
      "cpets",
      "dbird",
      "dcat",
      "ddog",
      "dnspecie",
      "dpetothe",
      "dpets",
      "ebird",
      "ecat",
      "edog",
      "enspecie",
      "epetothe",
      "epets",
      "fbird",
      "fcat",
      "fdog",
      "fnspecie",
      "fpetothe",
      "fpets",
      "gbird",
      "gcat",
      "gdog",
      "gnspecie",
      "gpetothe",
      "gpets",
      "hbird",
      "hcat",
      "hdog",
      "hnspecie",
      "hpetothe",
      "hpets",
      "ibird",
      "icat",
      "idog",
      "inspecie",
      "ipetothe",
      "ipets",
      "jbird",
      "jcat",
      "jdog",
      "jnspecie",
      "jpetothe",
      "jpets",
      "kbird",
      "kcat",
      "kdog",
      "knspecie",
      "kpetothe",
      "kpets"
    ),
    canonical_name = c(
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "pets",
      "petsoth",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets",
      "bird",
      "cat",
      "dog",
      "nspecie",
      "petothe",
      "pets"
    ),
    variable_label = c(
      "pets: bird (s)",
      "pets: cat (s)",
      "pets: dog(s)",
      "pets: number of species",
      "pets: other",
      "do you have pets?",
      "pets: bird (s)",
      "pets: cat (s)",
      "pets: dog(s)",
      "pets: number of species",
      "pets: other",
      "do you have pets?",
      "pets: Bird(s)",
      "pets: Cat(s)",
      "pets: Dog(s)",
      "pets: Number of species",
      "Do you have pets?",
      "pets: Other",
      "pets: Bird(s)",
      "pets: Cat(s)",
      "pets: Dog(s)",
      "pets: Number of species",
      "pets: Other",
      "Do you have pets?",
      "pets: Bird(s)",
      "pets: Cat(s)",
      "pets: Dog(s)",
      "pets: Number of species",
      "pets: Other",
      "Do you have pets?",
      "pets: Bird(s)",
      "pets: Cat(s)",
      "pets: Dog(s)",
      "pets: Number of species",
      "pets: Other",
      "Do you have pets?",
      "pets: bird (s)",
      "pets: cat (s)",
      "pets: dog(s)",
      "pets: number of species",
      "pets: other",
      "do you have pets?",
      "pets: bird (s)",
      "pets: cat (s)",
      "pets: dog(s)",
      "pets: number of species",
      "pets: other",
      "do you have pets?",
      "pets: bird (s)",
      "pets: cat (s)",
      "pets: dog(s)",
      "pets: number of species",
      "pets: other",
      "do you have pets?",
      "pets: bird (s)",
      "pets: cat (s)",
      "pets: dog(s)",
      "pets: number of species",
      "pets: other",
      "do you have pets?",
      "pets: bird (s)",
      "pets: cat (s)",
      "pets: dog(s)",
      "pets: number of species",
      "pets: other",
      "do you have pets?",
      "pets: bird (s)",
      "pets: cat (s)",
      "pets: dog(s)",
      "pets: number of species",
      "pets: other",
      "do you have pets?"
    ),
    harmonized_var_label = c(
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Do you have pets",
      "Pets: Other",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets",
      "Pets: bird (s)",
      "Pets: cat (s)",
      "Pets: dog(s)",
      "Pets: number of species",
      "Pets: other",
      "Do you have pets"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    bird = list(
      `2B` = not_mentioned_mentioned_188,
      `3B` = not_mentioned_mentioned_50,
      B = not_mentioned_mentioned_188,
      C = not_mentioned_mentioned_246,
      D = not_mentioned_mentioned_189,
      E = not_mentioned_mentioned_189,
      F = not_mentioned_mentioned_50,
      G = not_mentioned_mentioned_50,
      H = not_mentioned_mentioned_50,
      I = not_mentioned_mentioned_50,
      J = not_mentioned_mentioned_50,
      K = not_mentioned_mentioned_50
    ),
    cat = list(
      `2B` = not_mentioned_mentioned_188,
      `3B` = not_mentioned_mentioned_50,
      B = not_mentioned_mentioned_188,
      C = not_mentioned_mentioned_246,
      D = not_mentioned_mentioned_189,
      E = not_mentioned_mentioned_189,
      F = not_mentioned_mentioned_50,
      G = not_mentioned_mentioned_50,
      H = not_mentioned_mentioned_50,
      I = not_mentioned_mentioned_50,
      J = not_mentioned_mentioned_50,
      K = not_mentioned_mentioned_50
    ),
    dog = list(
      `2B` = not_mentioned_mentioned_188,
      `3B` = not_mentioned_mentioned_50,
      B = not_mentioned_mentioned_188,
      C = not_mentioned_mentioned_246,
      D = not_mentioned_mentioned_189,
      E = not_mentioned_mentioned_189,
      F = not_mentioned_mentioned_50,
      G = not_mentioned_mentioned_50,
      H = not_mentioned_mentioned_50,
      I = not_mentioned_mentioned_50,
      J = not_mentioned_mentioned_50,
      K = not_mentioned_mentioned_50
    ),
    nspecie = list(
      `2B` = na_see_bpets,
      `3B` = na_see_f_g_h_b_i_jpts,
      B = na_see_bpets,
      C = c(`-2` = "na, see CPETS"),
      D = na_see_d_epets,
      E = na_see_d_epets,
      F = na_see_f_g_h_b_i_jpts,
      G = na_see_f_g_h_b_i_jpts,
      H = na_see_f_g_h_b_i_jpts,
      I = na_see_f_g_h_b_i_jpts,
      J = na_see_f_g_h_b_i_jpts,
      K = na_see_f_g_h_b_i_jpts
    ),
    petothe = list(
      `2B` = not_mentioned_mentioned_188,
      `3B` = not_mentioned_mentioned_50,
      C = not_mentioned_mentioned_246,
      D = not_mentioned_mentioned_189,
      E = not_mentioned_mentioned_189,
      F = not_mentioned_mentioned_50,
      G = not_mentioned_mentioned_50,
      H = not_mentioned_mentioned_50,
      I = not_mentioned_mentioned_50,
      J = not_mentioned_mentioned_50,
      K = not_mentioned_mentioned_50
    ),
    pets = list(
      `2B` = c(`-2` = "na, interview terminated", `-1` = "na, asked", `0` = "no", `1` = "yes"),
      `3B` = no_yes_15,
      B = c(`-4` = "na, short version", `0` = "no", `1` = "yes"),
      C = c(`0` = "no", `1` = "yes"),
      D = no_yes_15,
      E = no_yes_15,
      F = no_yes_15,
      G = no_yes_15,
      H = no_yes_15,
      I = no_yes_15,
      J = no_yes_15,
      K = no_yes_15
    ),
    petsoth = list(
      B = not_mentioned_mentioned_188
    )
  ),

  value_labels_harmonized = list(
    bird = not_mentioned_mentioned_6,
    cat = not_mentioned_mentioned_6,
    dog = not_mentioned_mentioned_6,
    nspecie = not_available_routing,
    petothe = not_mentioned_mentioned_6,
    pets = c(
      `-4` = "not available, short version",
      `-2` = "not available, interview terminated",
      `-1` = "not available, asked",
      `0` = "no",
      `1` = "yes"
    ),
    petsoth = not_mentioned_mentioned_6
  )
)
