## LASA filecode 192 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_192 <- list(
  variables = data.frame(
    wave = c(
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H"
    ),
    variable_name = c(
      "emvcm101",
      "emvcm102",
      "emvcm103",
      "emvcm104",
      "emvcm105",
      "emvcm106",
      "emvcm107",
      "emvcm108",
      "emvcm109",
      "emvcm110",
      "emvq1",
      "emvq2",
      "fmvcm101",
      "fmvcm102",
      "fmvcm103",
      "fmvcm104",
      "fmvcm105",
      "fmvcm106",
      "fmvcm107",
      "fmvcm108",
      "fmvcm109",
      "fmvcm110",
      "fmvq1",
      "fmvq2",
      "gmvcm101",
      "gmvcm102",
      "gmvcm103",
      "gmvcm104",
      "gmvcm105",
      "gmvcm106",
      "gmvcm107",
      "gmvcm108",
      "gmvcm109",
      "gmvcm110",
      "gmvq1",
      "gmvq2",
      "hmvcm101",
      "hmvcm102",
      "hmvcm103",
      "hmvcm104",
      "hmvcm105",
      "hmvcm106",
      "hmvcm107",
      "hmvcm108",
      "hmvcm109",
      "hmvcm110",
      "hmvq1",
      "hmvq2"
    ),
    canonical_name = c(
      "mvcm101",
      "mvcm102",
      "mvcm103",
      "mvcm104",
      "mvcm105",
      "mvcm106",
      "mvcm107",
      "mvcm108",
      "mvcm109",
      "mvcm110",
      "mvq1",
      "mvq2",
      "mvcm101",
      "mvcm102",
      "mvcm103",
      "mvcm104",
      "mvcm105",
      "mvcm106",
      "mvcm107",
      "mvcm108",
      "mvcm109",
      "mvcm110",
      "mvq1",
      "mvq2",
      "mvcm101",
      "mvcm102",
      "mvcm103",
      "mvcm104",
      "mvcm105",
      "mvcm106",
      "mvcm107",
      "mvcm108",
      "mvcm109",
      "mvcm110",
      "mvq1",
      "mvq2",
      "mvcm101",
      "mvcm102",
      "mvcm103",
      "mvcm104",
      "mvcm105",
      "mvcm106",
      "mvcm107",
      "mvcm108",
      "mvcm109",
      "mvcm110",
      "mvq1",
      "mvq2"
    ),
    variable_label = c(
      "VCM1: feeling ashamed",
      "VCM1: feeling frustrated or annoyed",
      "VCM1: feeling lonely or abandoned",
      "VCM1: feeling sad or unhappy",
      "VCM1: worried about decline of eyesight",
      "VCM1: worried about general safety at home",
      "VCM1: worried about general safety outdoors",
      "VCM1: worried about dealing with daily life",
      "VCM1: eyesight an obstacle for things you wanted to do",
      "VCM1: eyesight an obstacle for life in general",
      "eye surgery or eye/vision measurement in past month",
      "different glasses/contacts or change of eyesight in past month",
      "VCM1: feeling ashamed",
      "VCM1: feeling frustrated or annoyed",
      "VCM1: feeling lonely or abandoned",
      "VCM1: feeling sad or unhappy",
      "VCM1: worried about decline of eyesight",
      "VCM1: worried about general safety at home",
      "VCM1: worried about general safety outdoors",
      "VCM1: worried about dealing with daily life",
      "VCM1: eyesight an obstacle for things you wanted to do",
      "VCM1: eyesight an obstacle for life in general",
      "eye surgery or eye/vision measurement in past month",
      "different glasses/contacts or change of eyesight in past month",
      "VCM1: feeling ashamed",
      "VCM1: feeling frustrated or annoyed",
      "VCM1: feeling lonely or abandoned",
      "VCM1: feeling sad or unhappy",
      "VCM1: worried about decline of eyesight",
      "VCM1: worried about general safety at home",
      "VCM1: worried about general safety outdoors",
      "VCM1: worried about dealing with daily life",
      "VCM1: eyesight an obstacle for things you wanted to do",
      "VCM1: eyesight an obstacle for life in general",
      "eye surgery or eye/vision measurement in past month",
      "different glasses/contacts or change of eyesight in past month",
      "VCM1: feeling ashamed",
      "VCM1: feeling frustrated or annoyed",
      "VCM1: feeling lonely or abandoned",
      "VCM1: feeling sad or unhappy",
      "VCM1: worried about decline of eyesight",
      "VCM1: worried about general safety at home",
      "VCM1: worried about general safety outdoors",
      "VCM1: worried about dealing with daily life",
      "VCM1: eyesight an obstacle for things you wanted to do",
      "VCM1: eyesight an obstacle for life in general",
      "eye surgery or eye/vision measurement in past month",
      "different glasses/contacts or change of eyesight in past month"
    ),
    harmonized_var_label = c(
      "VCM1: feeling ashamed",
      "VCM1: feeling frustrated or annoyed",
      "VCM1: feeling lonely or abandoned",
      "VCM1: feeling sad or unhappy",
      "VCM1: worried about decline of eyesight",
      "VCM1: worried about general safety at home",
      "VCM1: worried about general safety outdoors",
      "VCM1: worried about dealing with daily life",
      "VCM1: eyesight an obstacle for things you wanted to do",
      "VCM1: eyesight an obstacle for life in general",
      "eye surgery or eye/vision measurement in past month",
      "different glasses/contacts or change of eyesight in past month",
      "VCM1: feeling ashamed",
      "VCM1: feeling frustrated or annoyed",
      "VCM1: feeling lonely or abandoned",
      "VCM1: feeling sad or unhappy",
      "VCM1: worried about decline of eyesight",
      "VCM1: worried about general safety at home",
      "VCM1: worried about general safety outdoors",
      "VCM1: worried about dealing with daily life",
      "VCM1: eyesight an obstacle for things you wanted to do",
      "VCM1: eyesight an obstacle for life in general",
      "eye surgery or eye/vision measurement in past month",
      "different glasses/contacts or change of eyesight in past month",
      "VCM1: feeling ashamed",
      "VCM1: feeling frustrated or annoyed",
      "VCM1: feeling lonely or abandoned",
      "VCM1: feeling sad or unhappy",
      "VCM1: worried about decline of eyesight",
      "VCM1: worried about general safety at home",
      "VCM1: worried about general safety outdoors",
      "VCM1: worried about dealing with daily life",
      "VCM1: eyesight an obstacle for things you wanted to do",
      "VCM1: eyesight an obstacle for life in general",
      "eye surgery or eye/vision measurement in past month",
      "different glasses/contacts or change of eyesight in past month",
      "VCM1: feeling ashamed",
      "VCM1: feeling frustrated or annoyed",
      "VCM1: feeling lonely or abandoned",
      "VCM1: feeling sad or unhappy",
      "VCM1: worried about decline of eyesight",
      "VCM1: worried about general safety at home",
      "VCM1: worried about general safety outdoors",
      "VCM1: worried about dealing with daily life",
      "VCM1: eyesight an obstacle for things you wanted to do",
      "VCM1: eyesight an obstacle for life in general",
      "eye surgery or eye/vision measurement in past month",
      "different glasses/contacts or change of eyesight in past month"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mvcm101 = list(
      E = never_seldom_sometimes_reasonably_often_often,
      F = never_seldom_sometimes_reasonably_often_often,
      G = never_seldom_sometimes_reasonably_often_often,
      H = never_seldom_sometimes_reasonably_often_often
    ),
    mvcm102 = list(
      E = never_seldom_sometimes_reasonably_often_often,
      F = never_seldom_sometimes_reasonably_often_often,
      G = never_seldom_sometimes_reasonably_often_often,
      H = never_seldom_sometimes_reasonably_often_often
    ),
    mvcm103 = list(
      E = never_seldom_sometimes_reasonably_often_often,
      F = never_seldom_sometimes_reasonably_often_often,
      G = never_seldom_sometimes_reasonably_often_often,
      H = never_seldom_sometimes_reasonably_often_often
    ),
    mvcm104 = list(
      E = never_seldom_sometimes_reasonably_often_often,
      F = never_seldom_sometimes_reasonably_often_often,
      G = never_seldom_sometimes_reasonably_often_often,
      H = never_seldom_sometimes_reasonably_often_often
    ),
    mvcm105 = list(
      E = never_seldom_sometimes_reasonably_often_often,
      F = never_seldom_sometimes_reasonably_often_often,
      G = never_seldom_sometimes_reasonably_often_often,
      H = never_seldom_sometimes_reasonably_often_often
    ),
    mvcm106 = list(
      E = never_seldom_sometimes_reasonably_often_often,
      F = never_seldom_sometimes_reasonably_often_often,
      G = never_seldom_sometimes_reasonably_often_often,
      H = never_seldom_sometimes_reasonably_often_often
    ),
    mvcm107 = list(
      E = never_seldom_sometimes_reasonably_often_often,
      F = never_seldom_sometimes_reasonably_often_often,
      G = never_seldom_sometimes_reasonably_often_often,
      H = never_seldom_sometimes_reasonably_often_often
    ),
    mvcm108 = list(
      E = never_seldom_sometimes_reasonably_often_often,
      F = never_seldom_sometimes_reasonably_often_often,
      G = never_seldom_sometimes_reasonably_often_often,
      H = never_seldom_sometimes_reasonably_often_often
    ),
    mvcm109 = list(
      E = never_seldom_sometimes_reasonably_often_often,
      F = never_seldom_sometimes_reasonably_often_often,
      G = never_seldom_sometimes_reasonably_often_often,
      H = never_seldom_sometimes_reasonably_often_often
    ),
    mvcm110 = list(
      E = never_seldom_sometimes_reasonably_often_often,
      F = never_seldom_sometimes_reasonably_often_often,
      G = never_seldom_sometimes_reasonably_often_often,
      H = never_seldom_sometimes_reasonably_often_often
    ),
    mvq1 = list(
      E = no_yes,
      F = no_yes,
      G = no_yes,
      H = no_yes
    ),
    mvq2 = list(
      E = no_yes,
      F = no_yes,
      G = no_yes,
      H = no_yes
    )
  ),

  value_labels_harmonized = list(
    mvcm101 = never_seldom_sometimes_reasonably_often_often,
    mvcm102 = never_seldom_sometimes_reasonably_often_often,
    mvcm103 = never_seldom_sometimes_reasonably_often_often,
    mvcm104 = never_seldom_sometimes_reasonably_often_often,
    mvcm105 = never_seldom_sometimes_reasonably_often_often,
    mvcm106 = never_seldom_sometimes_reasonably_often_often,
    mvcm107 = never_seldom_sometimes_reasonably_often_often,
    mvcm108 = never_seldom_sometimes_reasonably_often_often,
    mvcm109 = never_seldom_sometimes_reasonably_often_often,
    mvcm110 = never_seldom_sometimes_reasonably_often_often,
    mvq1 = no_yes,
    mvq2 = no_yes
  )
)
