## LASA filecode 195 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_195 <- list(
  variables = data.frame(
    wave = c(
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "fmeol01",
      "fmeol02",
      "fmeol03",
      "fmeol04",
      "fmeol05",
      "fmeol06",
      "fmeol07",
      "fmeol08",
      "fmeol09",
      "fmeol10",
      "fmeol11",
      "fmeol12",
      "fmeol13",
      "fmeol14",
      "fmeol141",
      "fmeol142",
      "fmeol143",
      "fmeol144",
      "fmeol145",
      "fmeol15",
      "fmeol41",
      "fmeol42",
      "fmeol43",
      "fmeol44",
      "fmeol45",
      "fmrmeol",
      "gmeol01",
      "gmeol02",
      "gmeol03",
      "gmeol04",
      "gmeol05",
      "gmeol06",
      "gmeol41",
      "gmeol42",
      "gmeol43",
      "gmeol44",
      "gmeol45",
      "gmrmeol",
      "hmeol01",
      "hmeol02",
      "hmeol03",
      "hmeol04",
      "hmeol05",
      "hmeol06",
      "hmeol41",
      "hmeol42",
      "hmeol43",
      "hmeol44",
      "hmeol45",
      "hmeol601",
      "hmeol602",
      "hmeol603",
      "hmeol604",
      "hmeol605",
      "hmeol606",
      "hmeol607",
      "hmeol608",
      "hmeol609",
      "hmeol610",
      "hmeol611",
      "hmrmeol",
      "imeol01",
      "imeol02",
      "imeol03",
      "imeol04",
      "imeol05",
      "imeol06",
      "imeol41",
      "imeol42",
      "imeol43",
      "imeol44",
      "imeol45",
      "imeol601",
      "imeol602",
      "imeol603",
      "imeol604",
      "imeol605",
      "imeol606",
      "imeol607",
      "imeol608",
      "imeol609",
      "imeol610",
      "imeol611",
      "imeol612",
      "imrmeol",
      "jmeol01",
      "jmeol02",
      "jmeol03",
      "jmeol04",
      "jmeol05",
      "jmeol06",
      "jmeol41",
      "jmeol42",
      "jmeol43",
      "jmeol44",
      "jmeol45",
      "jmeol601",
      "jmeol602",
      "jmeol603",
      "jmeol604",
      "jmeol605",
      "jmeol606",
      "jmeol607",
      "jmeol608",
      "jmeol609",
      "jmeol610",
      "jmeol611",
      "jmeol612",
      "jmrmeol",
      "kmeol01",
      "kmeol02",
      "kmeol03",
      "kmeol04",
      "kmeol05",
      "kmeol06",
      "kmeol41",
      "kmeol42",
      "kmeol43",
      "kmeol44",
      "kmeol45",
      "kmeol601",
      "kmeol602",
      "kmeol603",
      "kmeol604",
      "kmeol605",
      "kmeol606",
      "kmeol607",
      "kmrmeol"
    ),
    canonical_name = c(
      "meol01",
      "meol02",
      "meol03",
      "meol04",
      "meol05",
      "meol06",
      "meol07",
      "meol08",
      "meol09",
      "meol10",
      "meol11",
      "meol12",
      "meol13",
      "meol14",
      "meol141",
      "meol142",
      "meol143",
      "meol144",
      "meol145",
      "meol15",
      "meol41",
      "meol42",
      "meol43",
      "meol44",
      "meol45",
      "mrmeol",
      "meol01",
      "meol02",
      "meol03",
      "meol04",
      "meol05",
      "meol06",
      "meol41",
      "meol42",
      "meol43",
      "meol44",
      "meol45",
      "mrmeol",
      "meol01",
      "meol02",
      "meol03",
      "meol04",
      "meol05",
      "meol06",
      "meol41",
      "meol42",
      "meol43",
      "meol44",
      "meol45",
      "meol601",
      "meol602",
      "meol603",
      "meol604",
      "meol605",
      "meol606",
      "meol607",
      "meol608",
      "meol609",
      "meol610",
      "meol611",
      "mrmeol",
      "meol01",
      "meol02",
      "meol03",
      "meol04",
      "meol05",
      "meol06",
      "meol41",
      "meol42",
      "meol43",
      "meol44",
      "meol45",
      "meol601",
      "meol602",
      "meol603",
      "meol604",
      "meol605",
      "meol606",
      "meol607",
      "meol608",
      "meol609",
      "meol610",
      "meol611",
      "meol612",
      "mrmeol",
      "meol01",
      "meol02",
      "meol03",
      "meol04",
      "meol05",
      "meol06",
      "meol41",
      "meol42",
      "meol43",
      "meol44",
      "meol45",
      "meol601",
      "meol602",
      "meol603",
      "meol604",
      "meol605",
      "meol606",
      "meol607",
      "meol608",
      "meol609",
      "meol610",
      "meol611",
      "meol612",
      "mrmeol",
      "meol01",
      "meol02",
      "meol03",
      "meol04",
      "meol05",
      "meol06",
      "meol41",
      "meol42",
      "meol43",
      "meol44",
      "meol45",
      "meol601",
      "meol602",
      "meol603",
      "meol604",
      "meol605",
      "meol606",
      "meol607",
      "mrmeol"
    ),
    variable_label = c(
      "Trust in doctors for good care in EOL",
      "Trust in doctors for EOL-wishes",
      "Discussed EOL-wishes with doctor",
      "# persons talked to about EOL-wishes",
      "Indication (verbal/written)",
      "(standard) End-of-life declaration",
      "ever death thoughts",
      "ever death wishes",
      "feelings towards living past week",
      "feelings towards dying past week",
      "feelings towards reasons for living/dying",
      "suicide medication must be available",
      "imagine suicide medication in possession",
      "# circumstances taking suicide medication",
      "circumstance: higher age",
      "circumstance: severe illness",
      "circumstance: dementia",
      "circumstance: dependence",
      "circumstance: other",
      "usage suicide medication within few months",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "reason missing eol-answers",
      "Trust in doctors for good care in EOL",
      "Trust in doctors for EOL-wishes",
      "Discussed EOL-wishes with doctor",
      "# persons talked to about EOL-wishes",
      "Indication (verbal/written)",
      "(standard) End-of-life declaration",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "reason missing eol-answers",
      "Trust in doctors for good care in EOL",
      "Trust in doctors for EOL-wishes",
      "Discussed EOL-wishes with doctor",
      "number of persons talked to about EOL-wishes",
      "Indication (verbal/written)",
      "number of End-of-life declarations",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "standard: NVVE advance euthanasia directive",
      "standard: NVVE durable power of attorney",
      "standard: NVVE do not treat",
      "standard: NVVE do not resuscitate",
      "standard: NPV wish to live",
      "standard: notary: advance euthanasia directive",
      "standard: MAIA advance care directive",
      "standard: other standard living will",
      "personal: advance euthanasia directive",
      "personal: other personal living will -coded",
      "other EOL-declaration: not specified",
      "reason missing EOL-answers",
      "Trust in doctors for good care in EOL",
      "Trust in doctors for EOL-wishes",
      "Discussed EOL-wishes with doctor",
      "number of persons talked to about EOL-wishes",
      "Indication (verbal/written)",
      "number of End-of-life declarations",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "standard: NVVE advance euthanasia directive",
      "standard: NVVE durable power of attorney",
      "standard: NVVE do not treat",
      "standard: NVVE do not resuscitate",
      "standard: NPV wish to live",
      "standard: notary: advance euthanasia directive",
      "standard: MAIA advance care directive",
      "standard: other standard living will",
      "personal: advance euthanasia directive",
      "personal: other personal living will -coded",
      "other EOL-declaration: not specified",
      "living will",
      "reason missing EOL-answers",
      "Trust in doctors for good care in EOL",
      "Trust in doctors for EOL-wishes",
      "Discussed EOL-wishes with doctor",
      "number of persons talked to about EOL-wishes",
      "Indication (verbal/written)",
      "number of End-of-life declarations",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "standard: NVVE advance euthanasia directive",
      "standard: NVVE durable power of attorney",
      "standard: NVVE do not treat",
      "standard: NVVE do not resuscitate",
      "standard: NPV wish to live",
      "standard: notary: advance euthanasia directive",
      "standard: MAIA advance care directive",
      "standard: other standard living will",
      "personal: advance euthanasia directive",
      "personal: other personal living will -coded",
      "other EOL-declaration: not specified",
      "living will",
      "reason missing EOL-answers",
      "trust in doctors for good care in EOL",
      "trust in doctors for EOL-wishes",
      "discussed EOL-wishes with doctor",
      "number of persons talked to about EOL-wishes",
      "someone appointed to make medical treatment decisions",
      "number of End-of-life declarations",
      "talked with partner",
      "talked to children",
      "talked to other family members",
      "talked to friends",
      "talked to other persons",
      "advance directive: euthanasia",
      "advance directive: durable power of attorney",
      "advance directive: do not treat",
      "advance directive: do not resuscitate",
      "wish to live statement",
      "living will",
      "other EOL-declaration: not specified",
      "reason missing EOL-answers"
    ),
    harmonized_var_label = c(
      "Trust in doctors for good care in end-of-life",
      "Trust in doctors for end-of-life-wishes",
      "Discussed end-of-life-wishes with doctor",
      "Number of persons talked to about end-of-life wishes",
      "End-of-life decision arrangement",
      "End-of-life declaration information",
      "ever death thoughts",
      "ever death wishes",
      "feelings towards living past week",
      "feelings towards dying past week",
      "feelings towards reasons for living/dying",
      "suicide medication must be available",
      "imagine suicide medication in possession",
      "Number of circumstances taking suicide medication",
      "circumstance: higher age",
      "circumstance: severe illness",
      "circumstance: dementia",
      "circumstance: dependence",
      "circumstance: other",
      "usage suicide medication within few months",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "Reason for missing end-of-life answers",
      "Trust in doctors for good care in end-of-life",
      "Trust in doctors for end-of-life-wishes",
      "Discussed end-of-life-wishes with doctor",
      "Number of persons talked to about end-of-life wishes",
      "End-of-life decision arrangement",
      "End-of-life declaration information",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "Reason for missing end-of-life answers",
      "Trust in doctors for good care in end-of-life",
      "Trust in doctors for end-of-life-wishes",
      "Discussed end-of-life-wishes with doctor",
      "Number of persons talked to about end-of-life wishes",
      "End-of-life decision arrangement",
      "End-of-life declaration information",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "standard: NVVE advance euthanasia directive",
      "standard: NVVE durable power of attorney",
      "standard: NVVE do not treat",
      "standard: NVVE do not resuscitate",
      "standard: NPV wish to live",
      "End-of-life declaration item 6",
      "End-of-life declaration item 7",
      "standard: other standard living will",
      "personal: advance euthanasia directive",
      "personal: other personal living will -coded",
      "other end-of-life-declaration: not specified",
      "Reason for missing end-of-life answers",
      "Trust in doctors for good care in end-of-life",
      "Trust in doctors for end-of-life-wishes",
      "Discussed end-of-life-wishes with doctor",
      "Number of persons talked to about end-of-life wishes",
      "End-of-life decision arrangement",
      "End-of-life declaration information",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "standard: NVVE advance euthanasia directive",
      "standard: NVVE durable power of attorney",
      "standard: NVVE do not treat",
      "standard: NVVE do not resuscitate",
      "standard: NPV wish to live",
      "End-of-life declaration item 6",
      "End-of-life declaration item 7",
      "standard: other standard living will",
      "personal: advance euthanasia directive",
      "personal: other personal living will -coded",
      "other end-of-life-declaration: not specified",
      "living will",
      "Reason for missing end-of-life answers",
      "Trust in doctors for good care in end-of-life",
      "Trust in doctors for end-of-life-wishes",
      "Discussed end-of-life-wishes with doctor",
      "Number of persons talked to about end-of-life wishes",
      "End-of-life decision arrangement",
      "End-of-life declaration information",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "standard: NVVE advance euthanasia directive",
      "standard: NVVE durable power of attorney",
      "standard: NVVE do not treat",
      "standard: NVVE do not resuscitate",
      "standard: NPV wish to live",
      "End-of-life declaration item 6",
      "End-of-life declaration item 7",
      "standard: other standard living will",
      "personal: advance euthanasia directive",
      "personal: other personal living will -coded",
      "other end-of-life-declaration: not specified",
      "living will",
      "Reason for missing end-of-life answers",
      "Trust in doctors for good care in end-of-life",
      "Trust in doctors for end-of-life-wishes",
      "Discussed end-of-life-wishes with doctor",
      "Number of persons talked to about end-of-life wishes",
      "End-of-life decision arrangement",
      "End-of-life declaration information",
      "Talked to partner",
      "Talked to children",
      "Talked to other family members",
      "Talked to friends",
      "Talked to other persons",
      "standard: NVVE advance euthanasia directive",
      "standard: NVVE durable power of attorney",
      "standard: NVVE do not treat",
      "standard: NVVE do not resuscitate",
      "standard: NPV wish to live",
      "End-of-life declaration item 6",
      "End-of-life declaration item 7",
      "Reason for missing end-of-life answers"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    meol01 = list(
      F = trust_very_strong_quite_strong_not_much_not_at_all,
      G = trust_very_strong_quite_strong_not_much_not_at_all_2,
      H = trust_very_strong_quite_strong_not_much_not_at_all_3,
      I = trust_very_strong_quite_strong_not_much_not_at_all_4,
      J = trust_very_strong_quite_strong_not_much_not_at_all_5,
      K = trust_very_strong_trust_quite_strong_trust_not_much
    ),
    meol02 = list(
      F = trust_very_strong_quite_strong_not_much_not_at_all,
      G = trust_very_strong_quite_strong_not_much_not_at_all_2,
      H = trust_very_strong_quite_strong_not_much_not_at_all_3,
      I = trust_very_strong_quite_strong_not_much_not_at_all_4,
      J = trust_very_strong_quite_strong_not_much_not_at_all_5,
      K = trust_very_strong_trust_quite_strong_trust_not_much
    ),
    meol03 = list(
      F = yes_no_r_does_not_know_2,
      G = c(
        `-2` = "na, see GMRMEOL",
        `-1` = "na, asked",
        `1` = "yes",
        `2` = "no",
        `3` = "R does not know"
      ),
      H = c(
        `-2` = "na, see HMRMEOL",
        `-1` = "na, asked",
        `1` = "yes",
        `2` = "no",
        `3` = "R does not know"
      ),
      I = c(
        `-2` = "na, see IMRMEOL",
        `-1` = "na, asked",
        `1` = "yes",
        `2` = "no",
        `3` = "R does not know"
      ),
      J = c(
        `-2` = "na, see JMRMEOL",
        `-1` = "na, asked",
        `1` = "yes",
        `2` = "no",
        `3` = "R does not know"
      ),
      K = c(
        `-2` = "na, see KMRMEOL",
        `-1` = "na, asked",
        `1` = "yes",
        `2` = "no",
        `3` = "R does not know"
      )
    ),
    meol04 = list(
      F = c(`-2` = "na, see FMRMEOL", `-1` = "na, asked/R does not know"),
      G = c(`-2` = "na, see GMRMEOL", `-1` = "na, asked/R does not know"),
      H = c(`-2` = "na, see HMRMEOL", `-1` = "na, asked/R does not know"),
      I = c(`-2` = "na, see IMRMEOL", `-1` = "R does not know", `0` = "R did not talk to anyone"),
      J = c(`-2` = "na, see JMRMEOL", `-1` = "R does not know", `0` = "R did not talk to anyone"),
      K = c(`-2` = "na, see KMRMEOL", `-1` = "R does not know", `0` = "R did not talk to anyone")
    ),
    meol05 = list(
      F = c(
        `-2` = "na, see FMRMEOL",
        `-1` = "na, asked",
        `1` = "yes, exclusively written",
        `2` = "yes, excl. verbal",
        `3` = "yes, written and verbal",
        `4` = "yes, not specified",
        `5` = "no",
        `6` = "R does not know"
      ),
      G = c(
        `-2` = "na, see GMRMEOL",
        `-1` = "na, asked",
        `1` = "yes, exclusively written",
        `2` = "yes, excl. verbal",
        `3` = "yes, written and verbal",
        `4` = "yes, not specified",
        `5` = "no",
        `6` = "R does not know"
      ),
      H = c(
        `-2` = "na, see HMRMEOL",
        `-1` = "na, asked",
        `1` = "yes, exclusively written",
        `2` = "yes, exclusively verbal",
        `3` = "yes, written and verbal",
        `4` = "yes, not specified",
        `5` = "no",
        `6` = "R does not know"
      ),
      I = c(
        `-2` = "na, see IMRMEOL",
        `-1` = "na, asked",
        `1` = "yes, exclusively written",
        `2` = "yes, exclusively verbal",
        `3` = "yes, written and verbal",
        `4` = "yes, not specified",
        `5` = "no",
        `6` = "R does not know"
      ),
      J = c(
        `-2` = "na, see JMRMEOL",
        `-1` = "na, asked",
        `1` = "yes, exclusively written",
        `2` = "yes, exclusively verbal",
        `3` = "yes, written and verbal",
        `4` = "yes, not specified",
        `5` = "no",
        `6` = "R does not know"
      ),
      K = c(
        `-2` = "na, see KMRMEOL",
        `-1` = "na, asked",
        `1` = "yes, exclusively written",
        `2` = "yes, exclusively verbal",
        `3` = "yes, written and verbal",
        `4` = "yes, not specified",
        `5` = "no",
        `6` = "R does not know"
      )
    ),
    meol06 = list(
      F = c(
        `-2` = "na, see FMRMEOL",
        `-1` = "na, asked",
        `1` = "standard: NVVE advance euthanasia directive",
        `2` = "standard: NVVE durable power of attorney",
        `3` = "standard: NVVE do not treat",
        `4` = "standard: NVVE do not resuscitate",
        `5` = "standard: NPV wish to live",
        `6` = "standard: notary: advance euthanasia directive",
        `7` = "standard: MAIA advance care directive",
        `8` = "standard: other standard living will",
        `9` = "personal: advance euthanasia directive",
        `10` = "personal: other personal living will",
        `11` = "other not specified",
        `12` = "no",
        `13` = "R does not know"
      ),
      G = c(
        `-2` = "na, see GMRMEOL",
        `-1` = "na, asked",
        `1` = "standard: NVVE advance euthanasia directive",
        `2` = "standard: NVVE durable power of attorney",
        `3` = "standard: NVVE do not treat",
        `4` = "standard: NVVE do not resuscitate",
        `5` = "standard: NPV wish to live",
        `6` = "standard: notary: advance euthanasia directive",
        `7` = "standard: MAIA advance care directive",
        `8` = "standard: other standard living will",
        `9` = "personal: advance euthanasia directive",
        `10` = "personal: other personal living will",
        `11` = "other not specified",
        `12` = "no",
        `13` = "R does not know"
      ),
      H = c(`-2` = "na, see HMRMEOL", `-1` = "na, asked/ R does not know"),
      I = c(`-2` = "na, see IMRMEOL", `-1` = "R does not know", `0` = "R does not have anything on paper"),
      J = c(`-2` = "na, see JMRMEOL", `-1` = "R does not know", `0` = "R does not have anything on paper"),
      K = c(`-2` = "na, see KMRMEOL", `-1` = "R does not know", `0` = "R does not have anything on paper")
    ),
    meol07 = list(
      F = yes_no_r_does_not_know_2
    ),
    meol08 = list(
      F = yes_no_r_does_not_know_2
    ),
    meol09 = list(
      F = c(
        `-2` = "na, see FMRMEOL",
        `-1` = "na, asked",
        `1` = "a moderate to strong wish to live",
        `2` = "a weak wish to live",
        `3` = "no wish to live"
      )
    ),
    meol10 = list(
      F = c(
        `-2` = "na, see FMRMEOL",
        `-1` = "na, asked",
        `1` = "no wish to die",
        `2` = "a weak wish to die",
        `3` = "a moderate to strong wish to die"
      )
    ),
    meol11 = list(
      F = c(
        `-2` = "na, see FMRMEOL",
        `-1` = "na, asked",
        `1` = "for living outweigh those for dying",
        `2` = "about equal",
        `3` = "for dying outweigh those for living"
      )
    ),
    meol12 = list(
      F = yes_maybe_no_r_does_not_know
    ),
    meol13 = list(
      F = yes_maybe_no_r_does_not_know
    ),
    meol14 = list(
      F = c(`-2` = "na, see FMEOL13", `-1` = "na, asked")
    ),
    meol141 = list(
      F = not_mentioned_mentioned_239
    ),
    meol142 = list(
      F = not_mentioned_mentioned_239
    ),
    meol143 = list(
      F = not_mentioned_mentioned_239
    ),
    meol144 = list(
      F = not_mentioned_mentioned_239
    ),
    meol145 = list(
      F = not_mentioned_mentioned_239
    ),
    meol15 = list(
      F = c(`-2` = "na, see FMEOL13", `-1` = "na, asked", `1` = "yes, because…", `2` = "no")
    ),
    meol41 = list(
      F = not_mentioned_mentioned_240,
      G = not_mentioned_mentioned_241,
      H = not_mentioned_mentioned_242,
      I = not_mentioned_mentioned_243,
      J = not_mentioned_mentioned_244,
      K = not_mentioned_mentioned_245
    ),
    meol42 = list(
      F = not_mentioned_mentioned_240,
      G = not_mentioned_mentioned_241,
      H = not_mentioned_mentioned_242,
      I = not_mentioned_mentioned_243,
      J = not_mentioned_mentioned_244,
      K = not_mentioned_mentioned_245
    ),
    meol43 = list(
      F = not_mentioned_mentioned_240,
      G = not_mentioned_mentioned_241,
      H = not_mentioned_mentioned_242,
      I = not_mentioned_mentioned_243,
      J = not_mentioned_mentioned_244,
      K = not_mentioned_mentioned_245
    ),
    meol44 = list(
      F = not_mentioned_mentioned_240,
      G = not_mentioned_mentioned_241,
      H = not_mentioned_mentioned_242,
      I = not_mentioned_mentioned_243,
      J = not_mentioned_mentioned_244,
      K = not_mentioned_mentioned_245
    ),
    meol45 = list(
      F = not_mentioned_mentioned_240,
      G = not_mentioned_mentioned_241,
      H = not_mentioned_mentioned_242,
      I = not_mentioned_mentioned_243,
      J = not_mentioned_mentioned_244,
      K = not_mentioned_mentioned_245
    ),
    mrmeol = list(
      F = short_version_interview_terminated_too_many_missings_3,
      G = short_version_interview_terminated_too_many_missings_3,
      H = short_version_interview_terminated_too_many_missings,
      I = short_version_interview_terminated_too_many_missings,
      J = short_version_interview_terminated_too_many_missings,
      K = short_version_interview_terminated_too_many_missings
    ),
    meol601 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159,
      K = not_mentioned_mentioned_204
    ),
    meol602 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159,
      K = not_mentioned_mentioned_204
    ),
    meol603 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159,
      K = not_mentioned_mentioned_204
    ),
    meol604 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159,
      K = not_mentioned_mentioned_204
    ),
    meol605 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159,
      K = not_mentioned_mentioned_204
    ),
    meol606 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159,
      K = not_mentioned_mentioned_204
    ),
    meol607 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159,
      K = not_mentioned_mentioned_204
    ),
    meol608 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159
    ),
    meol609 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159
    ),
    meol610 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159
    ),
    meol611 = list(
      H = not_mentioned_mentioned_158,
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_159
    ),
    meol612 = list(
      I = not_mentioned_mentioned_128,
      J = not_mentioned_mentioned_128
    )
  ),

  value_labels_harmonized = list(
    meol01 = trust_very_strong_quite_strong_not_much_not_at_all_6,
    meol02 = trust_very_strong_quite_strong_not_much_not_at_all_6,
    meol03 = yes_no_r_does_not_know_3,
    meol04 = c(
      `-2` = "no valid data",
      `-1` = "does not know / no valid count",
      `0` = "R did not talk to anyone"
    ),
    meol05 = c(
      `-2` = "no valid data",
      `-1` = "na, asked",
      `1` = "yes, exclusively written",
      `2` = "yes, excl. verbal",
      `3` = "yes, written and verbal",
      `4` = "yes, not specified",
      `5` = "no",
      `6` = "R does not know"
    ),
    meol06 = c(
      `-2` = "no valid data",
      `-1` = "does not know / no valid response",
      `0` = "R does not have anything on paper",
      `1` = "recorded value 1",
      `2` = "recorded value 2",
      `3` = "recorded value 3",
      `4` = "recorded value 4",
      `5` = "recorded value 5",
      `6` = "recorded value 6",
      `7` = "recorded value 7",
      `8` = "recorded value 8",
      `9` = "recorded value 9",
      `10` = "recorded value 10",
      `11` = "recorded value 11",
      `12` = "recorded value 12",
      `13` = "recorded value 13"
    ),
    meol07 = yes_no_r_does_not_know_3,
    meol08 = yes_no_r_does_not_know_3,
    meol09 = c(
      `-2` = "no valid data",
      `-1` = "na, asked",
      `1` = "a moderate to strong wish to live",
      `2` = "a weak wish to live",
      `3` = "no wish to live"
    ),
    meol10 = c(
      `-2` = "no valid data",
      `-1` = "na, asked",
      `1` = "no wish to die",
      `2` = "a weak wish to die",
      `3` = "a moderate to strong wish to die"
    ),
    meol11 = c(
      `-2` = "no valid data",
      `-1` = "na, asked",
      `1` = "for living outweigh those for dying",
      `2` = "about equal",
      `3` = "for dying outweigh those for living"
    ),
    meol12 = yes_maybe_no_r_does_not_know_2,
    meol13 = yes_maybe_no_r_does_not_know_2,
    meol14 = no_valid_data_na_asked,
    meol141 = not_mentioned_mentioned_36,
    meol142 = not_mentioned_mentioned_36,
    meol143 = not_mentioned_mentioned_36,
    meol144 = not_mentioned_mentioned_36,
    meol145 = not_mentioned_mentioned_36,
    meol15 = c(`-2` = "no valid data", `-1` = "na, asked", `1` = "yes, because…", `2` = "no"),
    meol41 = not_mentioned_mentioned_36,
    meol42 = not_mentioned_mentioned_36,
    meol43 = not_mentioned_mentioned_36,
    meol44 = not_mentioned_mentioned_36,
    meol45 = not_mentioned_mentioned_36,
    meol601 = not_mentioned_mentioned_36,
    meol602 = not_mentioned_mentioned_36,
    meol603 = not_mentioned_mentioned_36,
    meol604 = not_mentioned_mentioned_36,
    meol605 = not_mentioned_mentioned_36,
    meol606 = not_mentioned_mentioned_36,
    meol607 = not_mentioned_mentioned_36,
    meol608 = not_mentioned_mentioned_36,
    meol609 = not_mentioned_mentioned_36,
    meol610 = not_mentioned_mentioned_36,
    meol611 = not_mentioned_mentioned_36,
    meol612 = not_mentioned_mentioned_36,
    mrmeol = c(
      `-2` = "valid score",
      `1` = "short version",
      `2` = "interview terminated",
      `3` = "too many missings",
      `4` = "refused test",
      `5` = "not able to [cognitive]",
      `6` = "not able to (physical)",
      `7` = "emotional reasons",
      `8` = "unknown"
    )
  )
)
