## LASA filecode 272 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_272 <- list(
  variables = data.frame(
    wave = c(
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "cbrodied",
      "cconflic",
      "ccrime",
      "cdaudied",
      "cfadied",
      "cfinanc",
      "cgcdied",
      "cilloth",
      "cillpart",
      "cmodied",
      "csisdied",
      "csondied",
      "dbrodied",
      "dconflic",
      "dcrime",
      "ddaudied",
      "dfadied",
      "dfinanc",
      "dgcdied",
      "dilloth",
      "dillpart",
      "dmodied",
      "dsisdied",
      "dsondied",
      "ebrodied",
      "econflic",
      "ecrime",
      "edaudied",
      "efadied",
      "efinanc",
      "egcdied",
      "eilloth",
      "eillpart",
      "emodied",
      "esisdied",
      "esondied",
      "fbrodied",
      "fconflic",
      "fcrime",
      "fdaudied",
      "ffadied",
      "ffinanc",
      "fgcdied",
      "filloth",
      "fillpart",
      "fmodied",
      "fsisdied",
      "fsondied",
      "gbrodied",
      "gconflic",
      "gcrime",
      "gdaudied",
      "gfadied",
      "gfinanc",
      "ggcdied",
      "gilloth",
      "gillpart",
      "gmodied",
      "gsisdied",
      "gsondied",
      "hbrodied",
      "hconflic",
      "hcrime",
      "hdaudied",
      "hfadied",
      "hfinanc",
      "hgcdied",
      "hilloth",
      "hillpart",
      "hmodied",
      "hsisdied",
      "hsondied",
      "ibrodied",
      "iconflic",
      "icrime",
      "idaudied",
      "ifadied",
      "ifinanc",
      "igcdied",
      "iilloth",
      "iillpart",
      "imodied",
      "isisdied",
      "isondied",
      "jbrodied",
      "jconflic",
      "jcrime",
      "jdaudied",
      "jfadied",
      "jfinanc",
      "jgcdied",
      "jilloth",
      "jillpart",
      "jmodied",
      "jsisdied",
      "jsondied",
      "kbrodied",
      "kconflic",
      "kcrime",
      "kdaudied",
      "kfadied",
      "kfinanc",
      "kgcdied",
      "killoth",
      "killpart",
      "kmodied",
      "ksisdied",
      "ksondied"
    ),
    canonical_name = c(
      "brodied",
      "conflic",
      "crime",
      "daudied",
      "fadied",
      "financ",
      "gcdied",
      "illoth",
      "illpart",
      "modied",
      "sisdied",
      "sondied",
      "brodied",
      "conflic",
      "crime",
      "daudied",
      "fadied",
      "financ",
      "gcdied",
      "illoth",
      "illpart",
      "modied",
      "sisdied",
      "sondied",
      "brodied",
      "conflic",
      "crime",
      "daudied",
      "fadied",
      "financ",
      "gcdied",
      "illoth",
      "illpart",
      "modied",
      "sisdied",
      "sondied",
      "brodied",
      "conflic",
      "crime",
      "daudied",
      "fadied",
      "financ",
      "gcdied",
      "illoth",
      "illpart",
      "modied",
      "sisdied",
      "sondied",
      "brodied",
      "conflic",
      "crime",
      "daudied",
      "fadied",
      "financ",
      "gcdied",
      "illoth",
      "illpart",
      "modied",
      "sisdied",
      "sondied",
      "brodied",
      "conflic",
      "crime",
      "daudied",
      "fadied",
      "financ",
      "gcdied",
      "illoth",
      "illpart",
      "modied",
      "sisdied",
      "sondied",
      "brodied",
      "conflic",
      "crime",
      "daudied",
      "fadied",
      "financ",
      "gcdied",
      "illoth",
      "illpart",
      "modied",
      "sisdied",
      "sondied",
      "brodied",
      "conflic",
      "crime",
      "daudied",
      "fadied",
      "financ",
      "gcdied",
      "illoth",
      "illpart",
      "modied",
      "sisdied",
      "sondied",
      "brodied",
      "conflic",
      "crime",
      "daudied",
      "fadied",
      "financ",
      "gcdied",
      "illoth",
      "illpart",
      "modied",
      "sisdied",
      "sondied"
    ),
    variable_label = c(
      "brothers died",
      "conflict /w other persons",
      "victim of crime",
      "daughters died",
      "father died",
      "financial problems",
      "grandchildren died",
      "illness relative(s)",
      "illness partner/spouse",
      "mother died",
      "sisters died",
      "sons died",
      "brothers died",
      "conflict /w other persons",
      "victim of crime",
      "daughters died",
      "father died",
      "financial problems",
      "grandchildren died",
      "illness relative(s)",
      "illness partner/spouse",
      "mother died",
      "sisters died",
      "sons died",
      "brothers died",
      "conflict /w other persons",
      "victim of crime",
      "daughters died",
      "father died",
      "financial problems",
      "grandchildren died",
      "illness relative(s)",
      "illness partner/spouse",
      "mother died",
      "sisters died",
      "sons died",
      "brothers died",
      "conflict /w other persons",
      "victim of crime",
      "daughters died",
      "father died",
      "financial problems",
      "grandchildren died",
      "illness relative(s)",
      "illness partner/spouse",
      "mother died",
      "sisters died",
      "sons died",
      "brothers died",
      "conflict /w other persons",
      "victim of crime",
      "daughters died",
      "father died",
      "financial problems",
      "grandchildren died",
      "illness relative(s)",
      "illness partner/spouse",
      "mother died",
      "sisters died",
      "sons died",
      "brothers died",
      "conflict /w other persons",
      "victim of crime",
      "daughters died",
      "father died",
      "financial problems",
      "grandchildren died",
      "illness relative(s)",
      "illness partner/spouse",
      "mother died",
      "sisters died",
      "sons died",
      "brothers died",
      "conflict /w other persons",
      "victim of crime",
      "daughters died",
      "father died",
      "financial problems",
      "grandchildren died",
      "illness relative(s)",
      "illness partner/spouse",
      "mother died",
      "sisters died",
      "sons died",
      "brothers died",
      "conflict /w other persons",
      "victim of crime",
      "daughters died",
      "father died",
      "financial problems",
      "grandchildren died",
      "illness relative(s)",
      "illness partner/spouse",
      "mother died",
      "sisters died",
      "sons died",
      "Did any of your brothers die after previous interview / Is één van uw broers na Maand Jaar overleden",
      "After Month Year, have you had a serious argument or conflict with someone important to you / Heeft u na Maand Jaar een ernstige ruzie of een conflict gehad met iemand die voor u belangrijk is",
      "Have you been a victim of a serious crime after previous interview / Bent u na Maand Jaar slachtoffer geworden van een ernstig misdrijf",
      "Did any of your daughters die after previous interview / Is één van uw dochters na Maand Jaar overleden",
      "Did your father pass away after previous interview / Is uw vader na Maand Jaar overleden",
      "Have you had any serious financial problems after previous interview / Heeft u na Maand Jaar ernstige financiële problemen gehad",
      "Did any of your grandchildren pass away after previous interview / Is een van uw kleinkinderen na Maand Jaar overleden",
      "After Month Year, has any of your family members been seriously ill or had a serious accident / Is één van uw familieleden na Maand Jaar ernstig ziek geweest of heeft een familielid een ernstig ongeluk gehad",
      "Has your partner been seriously ill or had a serious accident after previous interview / Is uw partner na Maand Jaar ernstig ziek geweest of heeft hij/zij een ernstig ongeluk gehad",
      "Did your mother pass away after previous interview / Is uw moeder na Maand Jaar overleden",
      "Did any of your sisters die after previous interview / Is één van uw zussen na Maand Jaar overleden",
      "Did any of your sons die after previous interview / Is één van uw zonen na Maand Jaar overleden"
    ),
    harmonized_var_label = c(
      "Brother(s) died",
      "Serious conflict with an important person",
      "Victim of serious crime",
      "Daughter(s) died",
      "Father died",
      "Serious financial problems",
      "Grandchild(ren) died",
      "Serious illness or accident of relative(s)",
      "Serious illness or accident of partner/spouse",
      "Mother died",
      "Sister(s) died",
      "Son(s) died",
      "Brother(s) died",
      "Serious conflict with an important person",
      "Victim of serious crime",
      "Daughter(s) died",
      "Father died",
      "Serious financial problems",
      "Grandchild(ren) died",
      "Serious illness or accident of relative(s)",
      "Serious illness or accident of partner/spouse",
      "Mother died",
      "Sister(s) died",
      "Son(s) died",
      "Brother(s) died",
      "Serious conflict with an important person",
      "Victim of serious crime",
      "Daughter(s) died",
      "Father died",
      "Serious financial problems",
      "Grandchild(ren) died",
      "Serious illness or accident of relative(s)",
      "Serious illness or accident of partner/spouse",
      "Mother died",
      "Sister(s) died",
      "Son(s) died",
      "Brother(s) died",
      "Serious conflict with an important person",
      "Victim of serious crime",
      "Daughter(s) died",
      "Father died",
      "Serious financial problems",
      "Grandchild(ren) died",
      "Serious illness or accident of relative(s)",
      "Serious illness or accident of partner/spouse",
      "Mother died",
      "Sister(s) died",
      "Son(s) died",
      "Brother(s) died",
      "Serious conflict with an important person",
      "Victim of serious crime",
      "Daughter(s) died",
      "Father died",
      "Serious financial problems",
      "Grandchild(ren) died",
      "Serious illness or accident of relative(s)",
      "Serious illness or accident of partner/spouse",
      "Mother died",
      "Sister(s) died",
      "Son(s) died",
      "Brother(s) died",
      "Serious conflict with an important person",
      "Victim of serious crime",
      "Daughter(s) died",
      "Father died",
      "Serious financial problems",
      "Grandchild(ren) died",
      "Serious illness or accident of relative(s)",
      "Serious illness or accident of partner/spouse",
      "Mother died",
      "Sister(s) died",
      "Son(s) died",
      "Brother(s) died",
      "Serious conflict with an important person",
      "Victim of serious crime",
      "Daughter(s) died",
      "Father died",
      "Serious financial problems",
      "Grandchild(ren) died",
      "Serious illness or accident of relative(s)",
      "Serious illness or accident of partner/spouse",
      "Mother died",
      "Sister(s) died",
      "Son(s) died",
      "Brother(s) died",
      "Serious conflict with an important person",
      "Victim of serious crime",
      "Daughter(s) died",
      "Father died",
      "Serious financial problems",
      "Grandchild(ren) died",
      "Serious illness or accident of relative(s)",
      "Serious illness or accident of partner/spouse",
      "Mother died",
      "Sister(s) died",
      "Son(s) died",
      "Brother(s) died",
      "Serious conflict with an important person",
      "Victim of serious crime",
      "Daughter(s) died",
      "Father died",
      "Serious financial problems",
      "Grandchild(ren) died",
      "Serious illness or accident of relative(s)",
      "Serious illness or accident of partner/spouse",
      "Mother died",
      "Sister(s) died",
      "Son(s) died"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    brodied = list(
      C = c(
        `-6` = "refusal/skip by interviewer",
        `-5` = "terminated interview",
        `-4` = "short version",
        `-3` = "na: no brothers",
        `-2` = "answer: no brothers",
        `-1` = "no answer",
        `1` = "no",
        `2` = "yes"
      ),
      D = no_yes_146,
      E = no_yes_146,
      F = no_yes_146,
      G = no_yes_146,
      H = no_yes_146,
      I = not_died_died_4,
      J = not_died_died_4,
      K = c(
        `-11` = "not asked: routing error",
        `-10` = "not asked: no data available",
        `-8` = "technical problems",
        `-7` = "refusal/skip by interviewer",
        `-6` = "terminated interview",
        `-5` = "short version interview",
        `-4` = "do not know",
        `-3` = "not asked: no brothers alive",
        `-2` = "answer: no brothers",
        `-1` = "no answer",
        `1` = "not died",
        `2` = "died"
      )
    ),
    conflic = list(
      C = no_yes_147,
      D = no_yes_19,
      E = no_yes_19,
      F = no_yes_19,
      G = no_yes_19,
      H = no_yes_19,
      I = no_yes_31,
      J = no_yes_31,
      K = no_yes_31
    ),
    crime = list(
      C = no_yes_147,
      D = no_yes_19,
      E = no_yes_19,
      F = no_yes_19,
      G = no_yes_19,
      H = no_yes_19,
      I = no_yes_31,
      J = no_yes_31,
      K = no_yes_31
    ),
    daudied = list(
      C = c(
        `-6` = "refusal/skip by interviewer",
        `-5` = "terminated interview",
        `-4` = "short version",
        `-3` = "na: no daughters",
        `-2` = "answer: no daughters",
        `-1` = "no answer",
        `1` = "no",
        `2` = "yes"
      ),
      D = no_yes_148,
      E = no_yes_148,
      F = no_yes_148,
      G = no_yes_148,
      H = no_yes_148,
      I = not_died_died_5,
      J = not_died_died_5,
      K = c(
        `-11` = "not asked: routing error",
        `-10` = "not asked: no data available",
        `-8` = "technical problems",
        `-7` = "refusal/skip by interviewer",
        `-6` = "terminated interview",
        `-5` = "short version interview",
        `-4` = "do not know",
        `-3` = "not asked: no daughters alive",
        `-2` = "answer: no daughters",
        `-1` = "no answer",
        `1` = "not died",
        `2` = "died"
      )
    ),
    fadied = list(
      C = not_died_died_6,
      D = not_died_died_7,
      E = not_died_died,
      F = not_died_died,
      G = not_died_died,
      H = not_died_died,
      I = not_died_died_2,
      J = not_died_died_2,
      K = not_died_died_8
    ),
    financ = list(
      C = no_yes_147,
      D = no_yes_19,
      E = no_yes_19,
      F = no_yes_19,
      G = no_yes_19,
      H = no_yes_19,
      I = no_yes_31,
      J = no_yes_31,
      K = no_yes_31
    ),
    gcdied = list(
      C = no_yes_147,
      D = no_yes_19,
      E = no_yes_19,
      F = no_yes_19,
      G = no_yes_19,
      H = no_yes_19,
      I = no_yes_31,
      J = no_yes_31,
      K = no_yes_31
    ),
    illoth = list(
      C = no_yes_147,
      D = no_yes_19,
      E = no_yes_19,
      F = no_yes_19,
      G = no_yes_19,
      H = no_yes_19,
      I = no_yes_31,
      J = no_yes_31,
      K = no_yes_31
    ),
    illpart = list(
      C = c(
        `-6` = "refusal/skip by interviewer",
        `-5` = "terminated interview",
        `-4` = "short version",
        `-2` = "not asked",
        `-1` = "no answer",
        `1` = "no",
        `2` = "yes"
      ),
      D = c(
        `-7` = "refusal/skip by interviewer",
        `-6` = "terminated interview",
        `-5` = "short version",
        `-2` = "not asked",
        `-1` = "no answer",
        `1` = "no",
        `2` = "yes"
      ),
      E = no_yes_181,
      F = no_yes_181,
      G = no_yes_181,
      H = no_yes_181,
      I = no_yes_243,
      J = no_yes_243,
      K = no_yes_243
    ),
    modied = list(
      C = not_died_died_6,
      D = not_died_died_7,
      E = not_died_died,
      F = not_died_died,
      G = not_died_died,
      H = not_died_died,
      I = not_died_died_2,
      J = not_died_died_2,
      K = not_died_died_8
    ),
    sisdied = list(
      C = c(
        `-6` = "refusal/skip by interviewer",
        `-5` = "terminated interview",
        `-4` = "short version",
        `-3` = "na: no sisters",
        `-2` = "answer: no sisters",
        `-1` = "no answer",
        `1` = "no",
        `2` = "yes"
      ),
      D = no_yes_149,
      E = no_yes_149,
      F = no_yes_149,
      G = no_yes_149,
      H = no_yes_149,
      I = not_died_died_9,
      J = not_died_died_9,
      K = c(
        `-11` = "not asked: routing error",
        `-10` = "not asked: no data available",
        `-8` = "technical problems",
        `-7` = "refusal/skip by interviewer",
        `-6` = "terminated interview",
        `-5` = "short version interview",
        `-4` = "do not know",
        `-3` = "not asked: no sisters alive",
        `-2` = "answer: no sisters",
        `-1` = "no answer",
        `1` = "not died",
        `2` = "died"
      )
    ),
    sondied = list(
      C = c(
        `-6` = "refusal/skip by interviewer",
        `-5` = "terminated interview",
        `-4` = "short version",
        `-3` = "na: no sons",
        `-2` = "answer: no sons",
        `-1` = "no answer",
        `1` = "no",
        `2` = "yes"
      ),
      D = no_yes_150,
      E = no_yes_150,
      F = no_yes_150,
      G = no_yes_150,
      H = no_yes_150,
      I = not_died_died_10,
      J = not_died_died_10,
      K = c(
        `-11` = "not asked: routing error",
        `-10` = "not asked: no data available",
        `-8` = "technical problems",
        `-7` = "refusal/skip by interviewer",
        `-6` = "terminated interview",
        `-5` = "short version interview",
        `-4` = "do not know",
        `-3` = "not asked: no sons alive",
        `-2` = "answer: no sons",
        `-1` = "no answer",
        `1` = "not died",
        `2` = "died"
      )
    )
  ),

  value_labels_harmonized = list(
    brodied = not_died_died_3,
    conflic = no_yes_151,
    crime = no_yes_151,
    daudied = not_died_died_3,
    fadied = not_died_died_11,
    financ = no_yes_151,
    gcdied = no_yes_151,
    illoth = no_yes_151,
    illpart = c(
      `-8` = "technical problems",
      `-7` = "refusal/skip by interviewer",
      `-6` = "interview nonresponse",
      `-5` = "interview nonresponse",
      `-4` = "short version",
      `-3` = "partner not identified in demographic part",
      `-2` = "not asked / no partner",
      `-1` = "no answer",
      `1` = "no",
      `2` = "yes"
    ),
    modied = not_died_died_11,
    sisdied = not_died_died_3,
    sondied = not_died_died_3
  )
)
