## LASA filecode 235 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_235 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "E",
      "E",
      "F",
      "F",
      "G",
      "G",
      "H",
      "H",
      "I",
      "I",
      "J",
      "J",
      "K",
      "K",
      "MB"
    ),
    variable_name = c(
      "bnochrom",
      "bnochrot",
      "bnochrom",
      "bnochrot",
      "bnochrom",
      "bnochrot",
      "xnochrom",
      "xnochrot",
      "cnochrom",
      "cnochrot",
      "xnochrom",
      "xnochrot",
      "dnochrom",
      "dnochrot",
      "enochrom",
      "enochrot",
      "fnochrom",
      "fnochrot",
      "gnochrom",
      "gnochrot",
      "hnochrom",
      "hnochrot",
      "inochrom",
      "inochrot",
      "jnochrom",
      "jnochrot",
      "knochrom",
      "knochrot",
      "bnochrom"
    ),
    canonical_name = c(
      "nochrom",
      "nochrot",
      "nochrom",
      "nochrot",
      "nochrom",
      "nochrot",
      "xnochrom",
      "xnochrot",
      "nochrom",
      "nochrot",
      "xnochrom",
      "xnochrot",
      "nochrom",
      "nochrot",
      "nochrom",
      "nochrot",
      "nochrom",
      "nochrot",
      "nochrom",
      "nochrot",
      "nochrom",
      "nochrot",
      "nochrom",
      "nochrot",
      "nochrom",
      "nochrot",
      "nochrom",
      "nochrot",
      "nochrom"
    ),
    variable_label = c(
      "Number chronic diseases from 7 majors",
      "Number chronic diseases incl. others",
      "Number chronic diseases from 7 majors",
      "Number chronic diseases incl. others",
      "# chronic diseases from 7 Majors",
      "# chronic diseases incl Others",
      "(longitudinal) # chronic diseases from 7 Majors",
      "(longitudinal) # chronic diseases incl Others",
      "# chronic diseases from 7 Majors",
      "# chronic diseases incl Others",
      "(longitudinal) # chronic diseases from 7 Majors",
      "(longitudinal) # chronic diseases incl Others",
      "Number chronic diseases from 7 majors",
      "Number chronic diseases incl. others",
      "Number chronic diseases from 7 majors",
      "Number chronic diseases incl. others",
      "Number chronic diseases from 7 majors",
      "Number chronic diseases incl. others",
      "Number chronic diseases from 7 majors",
      "Number chronic diseases incl. others",
      "Number chronic diseases from 7 majors",
      "Number chronic diseases incl. others",
      "Number chronic diseases from 7 majors",
      "Number chronic diseases incl. others",
      "Number chronic diseases from 7 majors",
      "Number chronic diseases incl. others",
      "Number chronic diseases from 7 majors",
      "Number chronic diseases incl. others",
      "Number chronic diseases from 7 majors"
    ),
    harmonized_var_label = c(
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Longitudinal number of chronic diseases from 7 major diseases",
      "Longitudinal number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Longitudinal number of chronic diseases from 7 major diseases",
      "Longitudinal number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases",
      "Number of chronic diseases including others",
      "Number of chronic diseases from 7 major diseases"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    nochrom = list(
      `2B` = no_valid_data_2,
      `3B` = no_valid_data_2,
      B = no_valid_data_2,
      C = no_valid_data_2,
      D = no_valid_data_2,
      E = no_valid_data_2,
      F = no_valid_data_2,
      G = no_valid_data_2,
      H = no_valid_data_2,
      I = no_valid_data_2,
      J = no_valid_data_2,
      K = no_valid_data_2,
      MB = no_valid_data_2
    ),
    nochrot = list(
      `2B` = no_valid_data_2,
      `3B` = no_valid_data_2,
      B = no_valid_data_2,
      C = no_valid_data_2,
      D = no_valid_data_2,
      E = no_valid_data_2,
      F = no_valid_data_2,
      G = no_valid_data_2,
      H = no_valid_data_2,
      I = no_valid_data_2,
      J = no_valid_data_2,
      K = no_valid_data_2
    ),
    xnochrom = list(
      B = no_valid_data_2,
      C = no_valid_data_2
    ),
    xnochrot = list(
      B = no_valid_data_2,
      C = no_valid_data_2
    )
  ),

  value_labels_harmonized = list(
    nochrom = no_valid_data_2,
    nochrot = no_valid_data_2,
    xnochrom = no_valid_data_2,
    xnochrot = no_valid_data_2
  )
)
