## LASA filecode 135 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_135 <- list(
  variables = data.frame(
    wave = c(
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I"
    ),
    variable_name = c(
      "bqeq5d1",
      "bqeq5d2",
      "bqeq5d3",
      "bqeq5d4",
      "bqeq5d5",
      "bqeqvas",
      "eqeq5d1",
      "eqeq5d2",
      "eqeq5d3",
      "eqeq5d4",
      "eqeq5d5",
      "eqeqvas",
      "fqeq5d1",
      "fqeq5d2",
      "fqeq5d3",
      "fqeq5d4",
      "fqeq5d5",
      "fqeqvas",
      "gqeq5d1",
      "gqeq5d2",
      "gqeq5d3",
      "gqeq5d4",
      "gqeq5d5",
      "gqeqvas",
      "hqeq5d1",
      "hqeq5d2",
      "hqeq5d3",
      "hqeq5d4",
      "hqeq5d5",
      "hqeqvas",
      "iqeq5d1",
      "iqeq5d2",
      "iqeq5d3",
      "iqeq5d4",
      "iqeq5d5",
      "iqeqvas"
    ),
    canonical_name = c(
      "qeq5d1",
      "qeq5d2",
      "qeq5d3",
      "qeq5d4",
      "qeq5d5",
      "qeqvas",
      "qeq5d1",
      "qeq5d2",
      "qeq5d3",
      "qeq5d4",
      "qeq5d5",
      "qeqvas",
      "qeq5d1",
      "qeq5d2",
      "qeq5d3",
      "qeq5d4",
      "qeq5d5",
      "qeqvas",
      "qeq5d1",
      "qeq5d2",
      "qeq5d3",
      "qeq5d4",
      "qeq5d5",
      "qeqvas",
      "qeq5d1",
      "qeq5d2",
      "qeq5d3",
      "qeq5d4",
      "qeq5d5",
      "qeqvas",
      "qeq5d1",
      "qeq5d2",
      "qeq5d3",
      "qeq5d4",
      "qeq5d5",
      "qeqvas"
    ),
    variable_label = c(
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)",
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)",
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)",
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)",
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)",
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)"
    ),
    harmonized_var_label = c(
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)",
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)",
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)",
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)",
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)",
      "EQ5D1: Mobility",
      "EQ5D2: Self-care",
      "EQ5D3: Usual activities",
      "EQ5D4: Pain/discomfort",
      "EQ5D5: Anxiety/depression",
      "EQVAS: Self-rated health (scale)"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qeq5d1 = list(
      `3B` = no_problems_walking_some_problems_walking,
      E = no_problems_walking_some_problems_walking,
      F = no_problems_walking_some_problems_walking,
      G = no_problems_walking_some_problems_walking,
      H = no_problems_walking_some_problems_walking,
      I = no_problems_walking_some_problems_walking
    ),
    qeq5d2 = list(
      `3B` = no_problems_washing_dressing,
      E = no_problems_washing_dressing,
      F = no_problems_washing_dressing,
      G = no_problems_washing_dressing,
      H = no_problems_washing_dressing,
      I = no_problems_washing_dressing
    ),
    qeq5d3 = list(
      `3B` = no_problems_usual_activities,
      E = no_problems_usual_activities,
      F = no_problems_usual_activities,
      G = no_problems_usual_activities,
      H = no_problems_usual_activities,
      I = no_problems_usual_activities
    ),
    qeq5d4 = list(
      `3B` = no_pain_discomfort_moderate_pain_discomfort,
      E = no_pain_discomfort_moderate_pain_discomfort,
      F = no_pain_discomfort_moderate_pain_discomfort,
      G = no_pain_discomfort_moderate_pain_discomfort,
      H = no_pain_discomfort_moderate_pain_discomfort,
      I = no_pain_discomfort_moderate_pain_discomfort
    ),
    qeq5d5 = list(
      `3B` = not_anxious_depressed_moderately_anxious_depressed,
      E = not_anxious_depressed_moderately_anxious_depressed,
      F = not_anxious_depressed_moderately_anxious_depressed,
      G = not_anxious_depressed_moderately_anxious_depressed,
      H = not_anxious_depressed_moderately_anxious_depressed,
      I = not_anxious_depressed_moderately_anxious_depressed
    ),
    qeqvas = list(
      `3B` = no_answer_2,
      E = no_answer_2,
      F = no_answer_2,
      G = no_answer_2,
      H = no_answer_2,
      I = no_answer_2
    )
  ),

  value_labels_harmonized = list(
    qeq5d1 = c(
      `-1` = "not available",
      `1` = "no problems walking",
      `2` = "some problems walking",
      `3` = "confined to bed"
    ),
    qeq5d2 = c(
      `-1` = "not available",
      `1` = "no problems washing/dressing",
      `2` = "some problems washing/dressing",
      `3` = "unable to wash/dress"
    ),
    qeq5d3 = c(
      `-1` = "not available",
      `1` = "no problems usual activities",
      `2` = "some problems usual activities",
      `3` = "unable to perform usual activities"
    ),
    qeq5d4 = c(
      `-1` = "not available",
      `1` = "no pain/discomfort",
      `2` = "moderate pain/discomfort",
      `3` = "extreme pain/discomfort"
    ),
    qeq5d5 = c(
      `-1` = "not available",
      `1` = "not anxious/depressed",
      `2` = "moderately anxious/depressed",
      `3` = "extreme anxious/depressed"
    ),
    qeqvas = c(`-1` = "not available", `0` = NA_character_, `100` = NA_character_)
  )
)
