## LASA filecode 124 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_124 <- list(
  variables = data.frame(
    wave = c(
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D"
    ),
    variable_name = c(
      "bqmemo01",
      "bqmemo02",
      "bqmemo03",
      "bqmemo04",
      "bqmemo05",
      "bqmemo06",
      "bqmemo07",
      "bqmemo08",
      "bqmemo09",
      "bqmemo10",
      "bqmemo11",
      "bqmemo12",
      "bqmemo13",
      "bqmemo14",
      "bqmemo15",
      "bqmemo16",
      "bqmemo17",
      "bqmemo18",
      "bqmemo19",
      "bqmemo20",
      "bqmemo21",
      "bqmemo22",
      "bqmemo23",
      "bqmemo24",
      "bqmemo25",
      "bqmemo26",
      "bqmemo27",
      "bqmemo28",
      "bqmemo29",
      "bqmemo30",
      "cqmemo01",
      "cqmemo02",
      "cqmemo03",
      "cqmemo04",
      "cqmemo05",
      "cqmemo06",
      "cqmemo07",
      "cqmemo08",
      "cqmemo09",
      "cqmemo10",
      "cqmemo11",
      "cqmemo12",
      "cqmemo13",
      "cqmemo14",
      "cqmemo15",
      "cqmemo16",
      "cqmemo17",
      "cqmemo18",
      "cqmemo19",
      "cqmemo20",
      "cqmemo21",
      "cqmemo22",
      "cqmemo23",
      "cqmemo24",
      "cqmemo25",
      "cqmemo26",
      "cqmemo27",
      "cqmemo28",
      "cqmemo29",
      "cqmemo30",
      "cqmemo31",
      "cqmemo32",
      "cqmemo33",
      "cqmemo34",
      "cqmemo35",
      "cqmemo36",
      "cqmemo37",
      "cqmemo38",
      "cqmemo39",
      "cqmemo40",
      "cqmemo41",
      "dqmemo01",
      "dqmemo02",
      "dqmemo03",
      "dqmemo04",
      "dqmemo05",
      "dqmemo06",
      "dqmemo07",
      "dqmemo08",
      "dqmemo09",
      "dqmemo10",
      "dqmemo11",
      "dqmemo12",
      "dqmemo13",
      "dqmemo14",
      "dqmemo15",
      "dqmemo16",
      "dqmemo17",
      "dqmemo18",
      "dqmemo19",
      "dqmemo20",
      "dqmemo21",
      "dqmemo22",
      "dqmemo23",
      "dqmemo24",
      "dqmemo25",
      "dqmemo26",
      "dqmemo27",
      "dqmemo28",
      "dqmemo29",
      "dqmemo30",
      "dqmemo31",
      "dqmemo32",
      "dqmemo33",
      "dqmemo34",
      "dqmemo35",
      "dqmemo36",
      "dqmemo37",
      "dqmemo38",
      "dqmemo39",
      "dqmemo40",
      "dqmemo41"
    ),
    canonical_name = c(
      "qmemo01",
      "qmemo02",
      "qmemo03",
      "qmemo04",
      "qmemo05",
      "qmemo06",
      "qmemo07",
      "qmemo08",
      "qmemo09",
      "qmemo10",
      "qmemo11",
      "qmemo12",
      "qmemo13",
      "qmemo14",
      "qmemo15",
      "qmemo16",
      "qmemo17",
      "qmemo18",
      "qmemo19",
      "qmemo20",
      "qmemo21",
      "qmemo22",
      "qmemo23",
      "qmemo24",
      "qmemo25",
      "qmemo26",
      "qmemo27",
      "qmemo28",
      "qmemo29",
      "qmemo30",
      "qmemo01",
      "qmemo02",
      "qmemo03",
      "qmemo04",
      "qmemo05",
      "qmemo06",
      "qmemo07",
      "qmemo08",
      "qmemo09",
      "qmemo10",
      "qmemo11",
      "qmemo12",
      "qmemo13",
      "qmemo14",
      "qmemo15",
      "qmemo16",
      "qmemo17",
      "qmemo18",
      "qmemo19",
      "qmemo20",
      "qmemo21",
      "qmemo22",
      "qmemo23",
      "qmemo24",
      "qmemo25",
      "qmemo26",
      "qmemo27",
      "qmemo28",
      "qmemo29",
      "qmemo30",
      "qmemo31",
      "qmemo32",
      "qmemo33",
      "qmemo34",
      "qmemo35",
      "qmemo36",
      "qmemo37",
      "qmemo38",
      "qmemo39",
      "qmemo40",
      "qmemo41",
      "qmemo01",
      "qmemo02",
      "qmemo03",
      "qmemo04",
      "qmemo05",
      "qmemo06",
      "qmemo07",
      "qmemo08",
      "qmemo09",
      "qmemo10",
      "qmemo11",
      "qmemo12",
      "qmemo13",
      "qmemo14",
      "qmemo15",
      "qmemo16",
      "qmemo17",
      "qmemo18",
      "qmemo19",
      "qmemo20",
      "qmemo21",
      "qmemo22",
      "qmemo23",
      "qmemo24",
      "qmemo25",
      "qmemo26",
      "qmemo27",
      "qmemo28",
      "qmemo29",
      "qmemo30",
      "qmemo31",
      "qmemo32",
      "qmemo33",
      "qmemo34",
      "qmemo35",
      "qmemo36",
      "qmemo37",
      "qmemo38",
      "qmemo39",
      "qmemo40",
      "qmemo41"
    ),
    variable_label = c(
      "memory 01: important dates",
      "memory 02: beginning of the day",
      "memory 03: suitcase",
      "memory 04: names and faces",
      "memory 05: difficulties",
      "memory 06: conscious",
      "memory 07: other relation",
      "memory 08: mental images",
      "memory 09: mentally repeat",
      "memory 10: reminders",
      "memory 11: nervous",
      "memory 12: remember names",
      "memory 13: difficult if nervous",
      "memory 14: 10 years",
      "memory 15: problems",
      "memory 16: introduce",
      "memory 17: improve",
      "memory 18: memory test",
      "memory 19: practice",
      "memory 20: questions",
      "memory 21: use",
      "memory 22: accurate",
      "memory 23: tense",
      "memory 24: declines",
      "memory 25: did not do",
      "memory 26: appointment",
      "memory 27: exercise",
      "memory 28: not as good",
      "memory 29: decline when elder",
      "memory 30: improve when practice",
      "memory 01: important dates",
      "memory 02: beginning of the day",
      "memory 03: suitcase",
      "memory 04: names and faces",
      "memory 05: difficulties",
      "memory 06: conscious",
      "memory 07: other relation",
      "memory 08: mental images",
      "memory 09: mentally repeat",
      "memory 10: reminders",
      "memory 11: nervous",
      "memory 12: remember names",
      "memory 13: difficult if nervous",
      "memory 14: 10 years",
      "memory 15: problems",
      "memory 16: introduce",
      "memory 17: improve",
      "memory 18: memory test",
      "memory 19: practice",
      "memory 20: questions",
      "memory 21: use",
      "memory 22: accurate",
      "memory 23: tense",
      "memory 24: declines",
      "memory 25: did not do",
      "memory 26: appointment",
      "memory 27: exercise",
      "memory 28: not as good",
      "memory 29: decline when elder",
      "memory 30: improve when practice",
      "memory 31: always declines",
      "memory 32: no improvement",
      "memory 33: upset",
      "memory 34: difficult when upset",
      "memory 35: nervous new place",
      "memory 36: proud",
      "memory 37: admire others",
      "memory 38: important to be precise",
      "memory 39: self without help",
      "memory 40: pleasant",
      "memory 41: well",
      "memory 01: important dates",
      "memory 02: beginning of the day",
      "memory 03: suitcase",
      "memory 04: names and faces",
      "memory 05: difficulties",
      "memory 06: conscious",
      "memory 07: other relation",
      "memory 08: mental images",
      "memory 09: mentally repeat",
      "memory 10: reminders",
      "memory 11: nervous",
      "memory 12: remember names",
      "memory 13: difficult if nervous",
      "memory 14: 10 years",
      "memory 15: problems",
      "memory 16: introduce",
      "memory 17: improve",
      "memory 18: memory test",
      "memory 19: practice",
      "memory 20: questions",
      "memory 21: use",
      "memory 22: accurate",
      "memory 23: tense",
      "memory 24: declines",
      "memory 25: did not do",
      "memory 26: appointment",
      "memory 27: exercise",
      "memory 28: not as good",
      "memory 29: decline when elder",
      "memory 30: improve when practice",
      "memory 31: always declines",
      "memory 32: no improvement",
      "memory 33: upset",
      "memory 34: difficult when upset",
      "memory 35: nervous new place",
      "memory 36: proud",
      "memory 37: admire others",
      "memory 38: important to be precise",
      "memory 39: self without help",
      "memory 40: pleasant",
      "memory 41: well"
    ),
    harmonized_var_label = c(
      "memory 01: important dates",
      "memory 02: beginning of the day",
      "memory 03: suitcase",
      "memory 04: names and faces",
      "memory 05: difficulties",
      "memory 06: conscious",
      "memory 07: other relation",
      "memory 08: mental images",
      "memory 09: mentally repeat",
      "memory 10: reminders",
      "memory 11: nervous",
      "memory 12: remember names",
      "memory 13: difficult if nervous",
      "memory 14: 10 years",
      "memory 15: problems",
      "memory 16: introduce",
      "memory 17: improve",
      "memory 18: memory test",
      "memory 19: practice",
      "memory 20: questions",
      "memory 21: use",
      "memory 22: accurate",
      "memory 23: tense",
      "memory 24: declines",
      "memory 25: did not do",
      "memory 26: appointment",
      "memory 27: exercise",
      "memory 28: not as good",
      "memory 29: decline when elder",
      "memory 30: improve when practice",
      "memory 01: important dates",
      "memory 02: beginning of the day",
      "memory 03: suitcase",
      "memory 04: names and faces",
      "memory 05: difficulties",
      "memory 06: conscious",
      "memory 07: other relation",
      "memory 08: mental images",
      "memory 09: mentally repeat",
      "memory 10: reminders",
      "memory 11: nervous",
      "memory 12: remember names",
      "memory 13: difficult if nervous",
      "memory 14: 10 years",
      "memory 15: problems",
      "memory 16: introduce",
      "memory 17: improve",
      "memory 18: memory test",
      "memory 19: practice",
      "memory 20: questions",
      "memory 21: use",
      "memory 22: accurate",
      "memory 23: tense",
      "memory 24: declines",
      "memory 25: did not do",
      "memory 26: appointment",
      "memory 27: exercise",
      "memory 28: not as good",
      "memory 29: decline when elder",
      "memory 30: improve when practice",
      "memory 31: always declines",
      "memory 32: no improvement",
      "memory 33: upset",
      "memory 34: difficult when upset",
      "memory 35: nervous new place",
      "memory 36: proud",
      "memory 37: admire others",
      "memory 38: important to be precise",
      "memory 39: self without help",
      "memory 40: pleasant",
      "memory 41: well",
      "memory 01: important dates",
      "memory 02: beginning of the day",
      "memory 03: suitcase",
      "memory 04: names and faces",
      "memory 05: difficulties",
      "memory 06: conscious",
      "memory 07: other relation",
      "memory 08: mental images",
      "memory 09: mentally repeat",
      "memory 10: reminders",
      "memory 11: nervous",
      "memory 12: remember names",
      "memory 13: difficult if nervous",
      "memory 14: 10 years",
      "memory 15: problems",
      "memory 16: introduce",
      "memory 17: improve",
      "memory 18: memory test",
      "memory 19: practice",
      "memory 20: questions",
      "memory 21: use",
      "memory 22: accurate",
      "memory 23: tense",
      "memory 24: declines",
      "memory 25: did not do",
      "memory 26: appointment",
      "memory 27: exercise",
      "memory 28: not as good",
      "memory 29: decline when elder",
      "memory 30: improve when practice",
      "memory 31: always declines",
      "memory 32: no improvement",
      "memory 33: upset",
      "memory 34: difficult when upset",
      "memory 35: nervous new place",
      "memory 36: proud",
      "memory 37: admire others",
      "memory 38: important to be precise",
      "memory 39: self without help",
      "memory 40: pleasant",
      "memory 41: well"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qmemo01 = list(
      B = never_seldom_some_of_the_time_often_always,
      C = never_seldom_some_of_the_time_often_always,
      D = never_seldom_some_of_the_time_often_always
    ),
    qmemo02 = list(
      B = never_seldom_some_of_the_time_often_always,
      C = never_seldom_some_of_the_time_often_always,
      D = never_seldom_some_of_the_time_often_always
    ),
    qmemo03 = list(
      B = never_seldom_some_of_the_time_often_always,
      C = never_seldom_some_of_the_time_often_always,
      D = never_seldom_some_of_the_time_often_always
    ),
    qmemo04 = list(
      B = never_seldom_some_of_the_time_often_always,
      C = never_seldom_some_of_the_time_often_always,
      D = never_seldom_some_of_the_time_often_always
    ),
    qmemo05 = list(
      B = never_seldom_some_of_the_time_often_always,
      C = never_seldom_some_of_the_time_often_always,
      D = never_seldom_some_of_the_time_often_always
    ),
    qmemo06 = list(
      B = never_seldom_some_of_the_time_often_always,
      C = never_seldom_some_of_the_time_often_always,
      D = never_seldom_some_of_the_time_often_always
    ),
    qmemo07 = list(
      B = never_seldom_some_of_the_time_often_always,
      C = never_seldom_some_of_the_time_often_always,
      D = never_seldom_some_of_the_time_often_always
    ),
    qmemo08 = list(
      B = never_seldom_some_of_the_time_often_always,
      C = never_seldom_some_of_the_time_often_always,
      D = never_seldom_some_of_the_time_often_always
    ),
    qmemo09 = list(
      B = never_seldom_some_of_the_time_often_always,
      C = never_seldom_some_of_the_time_often_always,
      D = never_seldom_some_of_the_time_often_always
    ),
    qmemo10 = list(
      B = never_seldom_some_of_the_time_often_always,
      C = never_seldom_some_of_the_time_often_always,
      D = never_seldom_some_of_the_time_often_always
    ),
    qmemo11 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo12 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo13 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo14 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo15 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo16 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo17 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo18 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo19 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo20 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo21 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo22 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo23 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo24 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo25 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo26 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo27 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo28 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo29 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo30 = list(
      B = strongly_disagree_disagree_no_agreement_agreement_agree,
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo31 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo32 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo33 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo34 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo35 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo36 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo37 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo38 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo39 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo40 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    ),
    qmemo41 = list(
      C = strongly_disagree_disagree_no_agreement_agreement_agree,
      D = strongly_disagree_disagree_no_agreement_agreement_agree
    )
  ),

  value_labels_harmonized = list(
    qmemo01 = never_seldom_some_of_the_time_often_always_2,
    qmemo02 = never_seldom_some_of_the_time_often_always_2,
    qmemo03 = never_seldom_some_of_the_time_often_always_2,
    qmemo04 = never_seldom_some_of_the_time_often_always_2,
    qmemo05 = never_seldom_some_of_the_time_often_always_2,
    qmemo06 = never_seldom_some_of_the_time_often_always_2,
    qmemo07 = never_seldom_some_of_the_time_often_always_2,
    qmemo08 = never_seldom_some_of_the_time_often_always_2,
    qmemo09 = never_seldom_some_of_the_time_often_always_2,
    qmemo10 = never_seldom_some_of_the_time_often_always_2,
    qmemo11 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo12 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo13 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo14 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo15 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo16 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo17 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo18 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo19 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo20 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo21 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo22 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo23 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo24 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo25 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo26 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo27 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo28 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo29 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo30 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo31 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo32 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo33 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo34 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo35 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo36 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo37 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo38 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo39 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo40 = strongly_disagree_disagree_no_agreement_agreement_agree_2,
    qmemo41 = strongly_disagree_disagree_no_agreement_agreement_agree_2
  )
)
