## LASA filecode 108 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_108 <- list(
  variables = data.frame(
    wave = c(
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "iqacp10a",
      "iqacp10b",
      "iqacp10c",
      "iqacp10d",
      "iqacp10e",
      "iqacp1a",
      "iqacp1b",
      "iqacp1c",
      "iqacp1d",
      "iqacp2a",
      "iqacp2b",
      "iqacp2c",
      "iqacp2d",
      "iqacp3a",
      "iqacp3b",
      "iqacp3c",
      "iqacp3d",
      "iqacp3e",
      "iqacp4a",
      "iqacp4b",
      "iqacp4c",
      "iqacp4d",
      "iqacp4e",
      "iqacp5a",
      "iqacp5b",
      "iqacp5c",
      "iqacp5d",
      "iqacp5e",
      "iqacp6a",
      "iqacp6b",
      "iqacp6c",
      "iqacp6d",
      "iqacp6e",
      "iqacp7a",
      "iqacp7b",
      "iqacp7c",
      "iqacp7d",
      "iqacp7e",
      "iqacp8a",
      "iqacp8b",
      "iqacp8c",
      "iqacp8d",
      "iqacp8e",
      "iqacp9a",
      "iqacp9b",
      "iqacp9c",
      "iqacp9d",
      "iqacp9e",
      "kqacp1a",
      "kqacp1b",
      "kqacp1c",
      "kqacp1d",
      "kqacp1e",
      "kqacp2a",
      "kqacp2b",
      "kqacp2c",
      "kqacp2d",
      "kqacp2e",
      "kqacp3a",
      "kqacp3b",
      "kqacp3c",
      "kqacp3d",
      "kqacp3e",
      "kqacp4a",
      "kqacp4b",
      "kqacp4c",
      "kqacp4d",
      "kqacp4e",
      "kqacp5a",
      "kqacp5b",
      "kqacp5c",
      "kqacp5d",
      "kqacp5e",
      "kqacp6a",
      "kqacp6b",
      "kqacp6c",
      "kqacp6d",
      "kqacp6e",
      "kqacp7a",
      "kqacp7b",
      "kqacp7c",
      "kqacp7d",
      "kqacp7e"
    ),
    canonical_name = c(
      "qacp10a",
      "qacp10b",
      "qacp10c",
      "qacp10d",
      "qacp10e",
      "qacp1a",
      "qacp1b",
      "qacp1c",
      "qacp1d",
      "qacp2a",
      "qacp2b",
      "qacp2c",
      "qacp2d",
      "qacp3a",
      "qacp3b",
      "qacp3c",
      "qacp3d",
      "qacp3e",
      "qacp4a",
      "qacp4b",
      "qacp4c",
      "qacp4d",
      "qacp4e",
      "qacp5a",
      "qacp5b",
      "qacp5c",
      "qacp5d",
      "qacp5e",
      "qacp6a",
      "qacp6b",
      "qacp6c",
      "qacp6d",
      "qacp6e",
      "qacp7a",
      "qacp7b",
      "qacp7c",
      "qacp7d",
      "qacp7e",
      "qacp8a",
      "qacp8b",
      "qacp8c",
      "qacp8d",
      "qacp8e",
      "qacp9a",
      "qacp9b",
      "qacp9c",
      "qacp9d",
      "qacp9e",
      "qacp1a",
      "qacp1b",
      "qacp1c",
      "qacp1d",
      "qacp1e",
      "qacp2a",
      "qacp2b",
      "qacp2c",
      "qacp2d",
      "qacp2e",
      "qacp3a",
      "qacp3b",
      "qacp3c",
      "qacp3d",
      "qacp3e",
      "qacp4a",
      "qacp4b",
      "qacp4c",
      "qacp4d",
      "qacp4e",
      "qacp5a",
      "qacp5b",
      "qacp5c",
      "qacp5d",
      "qacp5e",
      "qacp6a",
      "qacp6b",
      "qacp6c",
      "qacp6d",
      "qacp6e",
      "qacp7a",
      "qacp7b",
      "qacp7c",
      "qacp7d",
      "qacp7e"
    ),
    variable_label = c(
      "acp 10a: sometimes think about wishes for my deathbed",
      "acp 10b: talk to people close to me about wishes for my deathbed",
      "acp 10c: talk to my general physician about wishes for my deathbed",
      "acp 10d: would like to talk to my general physician about wishes for my deathbed",
      "acp 10e: put something on paper about wishes for my deathbed",
      "acp 1a: sometimes think about future health",
      "acp 1b: talk to people close to me about future health",
      "acp 1c: talk to my general physician about future health",
      "acp 1d: would like to talk to my general physician about future health",
      "acp 2a: sometimes think about future health partner",
      "acp 2b: talk to people close to me about future health partner",
      "acp 2c: talk to my general physician about future health partner",
      "acp 2d: would like to talk to my general physician about future health partner",
      "acp 3a: sometimes think about future medical care and guidance",
      "acp 3b: talk to people close to me about future medical care and guidance",
      "acp 3c: talk to my general physician about future medical care and guidance",
      "acp 3d: would like to talk to my general physician about future medical care and guidance",
      "acp 3e: put something on paper about future medical care and guidance",
      "acp 4a: sometimes think about who to take care of me not being able to care for myself",
      "acp 4b: talk to people close to me about who to take care of me not being able to care for myself",
      "acp 4c: talk to my general physician about who to take care of me not being able to care for myself",
      "acp 4d: would like to talk to my general physician who to take care of me not being able to care for myself",
      "acp 4e: put something on paper about who to take care of me not being able to care for myself",
      "acp 5a: sometimes think about who to take medical decisions for me not being able doing it myself",
      "acp 5b: talk to people close to me about who to take medical decisions for me not being able doing it myself",
      "acp 5c: talk to my general physician about who to take medical decisions for me not being able doing it myself",
      "acp 5d: would like to talk to my general physician about who to take medical decisions for me not being able doing it myself",
      "acp 5e: put something on paper about who to take medical decisions for me not being able doing it myself",
      "acp 6a: sometimes think about whether a nursing home is an option for me when not being able to stay at home",
      "acp 6b: talk to people close to me about whether a nursing home is an option for me when not being able to stay at home",
      "acp 6c: talk to my general physician about whether a nursing home is an option for me when not being able to stay at home",
      "acp 6d: would like to talk to my general physician about whether a nursing home is an option for me when not being able to stay at home",
      "acp 6e: put something on paper about whether a nursing home is an option for me when not being able to stay at home",
      "acp 7a: sometimes think about situations where I no longer want to have a life-extending treatment",
      "acp 7b: talk to people close to me about situations where I no longer want to have a life-extending treatment",
      "acp 7c: talk to my general physician about situations where I no longer want to have a life-extending treatment",
      "acp 7d: would like to talk to my general physician about situations where I no longer want to have a life-extending treatment",
      "acp 7e: put something on paper about situations where I no longer want to have a life-extending treatment",
      "acp 8a: sometimes think about I would like to be resuscitated if I had a cardiac arrest",
      "acp 8b: talk to people close to me about I would like to be resuscitated if I had a cardiac arrest",
      "acp 8c: talk to my general physician about I would like to be resuscitated if I had a cardiac arrest",
      "acp 8d: would like to talk to my general physician about I would like to be resuscitated if I had a cardiac arrest",
      "acp 8e: put something on paper about I would like to be resuscitated if I had a cardiac arrest",
      "acp 9a: sometimes think about euthanasia as an option for me if life has become unbearable",
      "acp 9b: talk to people close to me about euthanasia as an option for me if life has become unbearable",
      "acp 9c: talk to my general physician about euthanasia as an option for me if life has become unbearable",
      "acp 9d: would like to talk to my general physician about euthanasia as an option for me if life has become unbearable",
      "acp 9e: put something on paper about future euthanasia as an option for me if life has become unbearable",
      "Advanced care planning, staying at home: no, not thought about (past months)",
      "Advanced care planning, staying at home: yes, thought about (past months)",
      "Advanced care planning, staying at home: yes, spoken about with doctor/healthcare provider (past months)",
      "Advanced care planning, staying at home: yes, spoken about with relatives (past months)",
      "Advanced care planning, staying at home: yes, living will (past months)",
      "Advanced care planning: going to hospital: no, not thought about (past months)",
      "Advanced care planning: going to hospital: yes, thought about (past months)",
      "Advanced care planning: going to hospital: yes, spoken about with doctor/healthcare provider (past months)",
      "Advanced care planning: going to hospital: yes, spoken about with relatives (past months)",
      "Advanced care planning: going to hospital: yes, living will (past months)",
      "Advanced care planning: admitted to nursing home: no, not thought about (past months)",
      "Advanced care planning: admitted to nursing home: yes, thought about (past months)",
      "Advanced care planning: admitted to nursing home: yes, spoken about with doctor/healthcare provider (past months)",
      "Advanced care planning: admitted to nursing home: yes, spoken about with relatives (past months)",
      "Advanced care planning: admitted to nursing home: yes, living will (past months)",
      "Advanced care planning: desired treatments: no, not thought about (past months)",
      "Advanced care planning: desired treatments: yes, thought about (past months)",
      "Advanced care planning: desired treatments: yes, spoken about with doctor/healthcare provider (past months)",
      "Advanced care planning: desired treatments: yes, spoken about with relatives (past months)",
      "Advanced care planning: desired treatments: yes, living will (past months)",
      "Advanced care planning: who should make medical decisions: no, not thought about (past months)",
      "Advanced care planning: who should make medical decisions: yes, thought about (past months)",
      "Advanced care planning: who should make medical decisions: yes, spoken about with doctor/healthcare provider (past months)",
      "Advanced care planning: who should make medical decisions: yes, spoken about with relatives (past months)",
      "Advanced care planning: who should make medical decisions: yes, living will (past months)",
      "Advanced care planning: be resuscitated: no, not thought about (past months)",
      "Advanced care planning: be resuscitated: yes, thought about (past months)",
      "Advanced care planning: be resuscitated: yes, spoken about with doctor/healthcare provider (past months)",
      "Advanced care planning: be resuscitated: yes, spoken about with relatives (past months)",
      "Advanced care planning: be resuscitated: yes, living will (past months)",
      "Advanced care planning: euthanasia: no, not thought about (past months)",
      "Advanced care planning: euthanasia: yes, thought about (past months)",
      "Advanced care planning: euthanasia: yes, spoken about with doctor/healthcare provider (past months)",
      "Advanced care planning: euthanasia: yes, spoken about with relatives (past months)",
      "Advanced care planning: euthanasia: yes, living will (past months)"
    ),
    harmonized_var_label = c(
      "acp 10a: sometimes think about wishes for my deathbed",
      "acp 10b: talk to people close to me about wishes for my deathbed",
      "acp 10c: talk to my general physician about wishes for my deathbed",
      "acp 10d: would like to talk to my general physician about wishes for my deathbed",
      "acp 10e: put something on paper about wishes for my deathbed",
      "Advance care planning item 1a",
      "Advance care planning item 1b",
      "Advance care planning item 1c",
      "Advance care planning item 1d",
      "Advance care planning item 2a",
      "Advance care planning item 2b",
      "Advance care planning item 2c",
      "Advance care planning item 2d",
      "Advance care planning item 3a",
      "Advance care planning item 3b",
      "Advance care planning item 3c",
      "Advance care planning item 3d",
      "Advance care planning item 3e",
      "Advance care planning item 4a",
      "Advance care planning item 4b",
      "Advance care planning item 4c",
      "Advance care planning item 4d",
      "Advance care planning item 4e",
      "Advance care planning item 5a",
      "Advance care planning item 5b",
      "Advance care planning item 5c",
      "Advance care planning item 5d",
      "Advance care planning item 5e",
      "Advance care planning item 6a",
      "Advance care planning item 6b",
      "Advance care planning item 6c",
      "Advance care planning item 6d",
      "Advance care planning item 6e",
      "Advance care planning item 7a",
      "Advance care planning item 7b",
      "Advance care planning item 7c",
      "Advance care planning item 7d",
      "Advance care planning item 7e",
      "acp 8a: sometimes think about I would like to be resuscitated if I had a cardiac arrest",
      "acp 8b: talk to people close to me about I would like to be resuscitated if I had a cardiac arrest",
      "acp 8c: talk to my general physician about I would like to be resuscitated if I had a cardiac arrest",
      "acp 8d: would like to talk to my general physician about I would like to be resuscitated if I had a cardiac arrest",
      "acp 8e: put something on paper about I would like to be resuscitated if I had a cardiac arrest",
      "acp 9a: sometimes think about euthanasia as an option for me if life has become unbearable",
      "acp 9b: talk to people close to me about euthanasia as an option for me if life has become unbearable",
      "acp 9c: talk to my general physician about euthanasia as an option for me if life has become unbearable",
      "acp 9d: would like to talk to my general physician about euthanasia as an option for me if life has become unbearable",
      "acp 9e: put something on paper about future euthanasia as an option for me if life has become unbearable",
      "Advance care planning item 1a",
      "Advance care planning item 1b",
      "Advance care planning item 1c",
      "Advance care planning item 1d",
      "Advanced care planning, staying at home: yes, living will (past months)",
      "Advance care planning item 2a",
      "Advance care planning item 2b",
      "Advance care planning item 2c",
      "Advance care planning item 2d",
      "Advanced care planning: going to hospital: yes, living will (past months)",
      "Advance care planning item 3a",
      "Advance care planning item 3b",
      "Advance care planning item 3c",
      "Advance care planning item 3d",
      "Advance care planning item 3e",
      "Advance care planning item 4a",
      "Advance care planning item 4b",
      "Advance care planning item 4c",
      "Advance care planning item 4d",
      "Advance care planning item 4e",
      "Advance care planning item 5a",
      "Advance care planning item 5b",
      "Advance care planning item 5c",
      "Advance care planning item 5d",
      "Advance care planning item 5e",
      "Advance care planning item 6a",
      "Advance care planning item 6b",
      "Advance care planning item 6c",
      "Advance care planning item 6d",
      "Advance care planning item 6e",
      "Advance care planning item 7a",
      "Advance care planning item 7b",
      "Advance care planning item 7c",
      "Advance care planning item 7d",
      "Advance care planning item 7e"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qacp10a = list(
      I = yes_no
    ),
    qacp10b = list(
      I = yes_no
    ),
    qacp10c = list(
      I = yes_no
    ),
    qacp10d = list(
      I = yes_no
    ),
    qacp10e = list(
      I = yes_no
    ),
    qacp1a = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp1b = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp1c = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp1d = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp2a = list(
      I = yes_no_10,
      K = not_mentioned_mentioned_31
    ),
    qacp2b = list(
      I = yes_no_10,
      K = not_mentioned_mentioned_31
    ),
    qacp2c = list(
      I = yes_no_10,
      K = not_mentioned_mentioned_31
    ),
    qacp2d = list(
      I = yes_no_10,
      K = not_mentioned_mentioned_31
    ),
    qacp3a = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp3b = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp3c = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp3d = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp3e = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp4a = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp4b = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp4c = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp4d = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp4e = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp5a = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp5b = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp5c = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp5d = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp5e = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp6a = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp6b = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp6c = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp6d = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp6e = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp7a = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp7b = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp7c = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp7d = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp7e = list(
      I = yes_no,
      K = not_mentioned_mentioned_31
    ),
    qacp8a = list(
      I = yes_no
    ),
    qacp8b = list(
      I = yes_no
    ),
    qacp8c = list(
      I = yes_no
    ),
    qacp8d = list(
      I = yes_no
    ),
    qacp8e = list(
      I = yes_no
    ),
    qacp9a = list(
      I = yes_no
    ),
    qacp9b = list(
      I = yes_no
    ),
    qacp9c = list(
      I = yes_no
    ),
    qacp9d = list(
      I = yes_no
    ),
    qacp9e = list(
      I = yes_no
    ),
    qacp1e = list(
      K = not_mentioned_mentioned_31
    ),
    qacp2e = list(
      K = not_mentioned_mentioned_31
    )
  ),

  value_labels_harmonized = list(
    qacp10a = yes_no,
    qacp10b = yes_no,
    qacp10c = yes_no,
    qacp10d = yes_no,
    qacp10e = yes_no,
    qacp1a = not_mentioned_coding_category_1_no,
    qacp1b = not_mentioned_coding_category_1_no,
    qacp1c = not_mentioned_coding_category_1_no,
    qacp1d = not_mentioned_coding_category_1_no,
    qacp1e = not_mentioned_mentioned_31,
    qacp2a = not_mentioned_coding_category_1_no_2,
    qacp2b = not_mentioned_coding_category_1_no_2,
    qacp2c = not_mentioned_coding_category_1_no_2,
    qacp2d = not_mentioned_coding_category_1_no_2,
    qacp2e = not_mentioned_mentioned_31,
    qacp3a = not_mentioned_coding_category_1_no,
    qacp3b = not_mentioned_coding_category_1_no,
    qacp3c = not_mentioned_coding_category_1_no,
    qacp3d = not_mentioned_coding_category_1_no,
    qacp3e = not_mentioned_coding_category_1_no,
    qacp4a = not_mentioned_coding_category_1_no,
    qacp4b = not_mentioned_coding_category_1_no,
    qacp4c = not_mentioned_coding_category_1_no,
    qacp4d = not_mentioned_coding_category_1_no,
    qacp4e = not_mentioned_coding_category_1_no,
    qacp5a = not_mentioned_coding_category_1_no,
    qacp5b = not_mentioned_coding_category_1_no,
    qacp5c = not_mentioned_coding_category_1_no,
    qacp5d = not_mentioned_coding_category_1_no,
    qacp5e = not_mentioned_coding_category_1_no,
    qacp6a = not_mentioned_coding_category_1_no,
    qacp6b = not_mentioned_coding_category_1_no,
    qacp6c = not_mentioned_coding_category_1_no,
    qacp6d = not_mentioned_coding_category_1_no,
    qacp6e = not_mentioned_coding_category_1_no,
    qacp7a = not_mentioned_coding_category_1_no,
    qacp7b = not_mentioned_coding_category_1_no,
    qacp7c = not_mentioned_coding_category_1_no,
    qacp7d = not_mentioned_coding_category_1_no,
    qacp7e = not_mentioned_coding_category_1_no,
    qacp8a = yes_no,
    qacp8b = yes_no,
    qacp8c = yes_no,
    qacp8d = yes_no,
    qacp8e = yes_no,
    qacp9a = yes_no,
    qacp9b = yes_no,
    qacp9c = yes_no,
    qacp9d = yes_no,
    qacp9e = yes_no
  )
)
