## LASA filecode 118 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_118 <- list(
  variables = data.frame(
    wave = c(
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "D",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bqfood01",
      "bqfood02",
      "bqfood03",
      "bqfood04",
      "bqfood05",
      "bqfood06",
      "bqfood07",
      "bqfood08",
      "bqfood09",
      "bqfood10",
      "bqfood11",
      "bqfood12",
      "bqfood13",
      "bqfood14",
      "bqfood15",
      "bqfood16",
      "bqfood17",
      "bqfood18",
      "bqfood19",
      "bqfood20",
      "cqfood01",
      "dqfood01",
      "hqfood21",
      "hqfood22",
      "hqfood23",
      "hqfood24",
      "hqfood25",
      "hqfood26",
      "hqfood27",
      "iqfood21",
      "iqfood22",
      "iqfood23",
      "iqfood24",
      "iqfood25",
      "iqfood26",
      "iqfood27",
      "jqfood21",
      "jqfood22",
      "jqfood23",
      "jqfood24",
      "jqfood25",
      "jqfood26",
      "jqfood27",
      "kqapp1",
      "kqapp2",
      "kqapp3",
      "kqapp4",
      "kqfood21",
      "kqfood22",
      "kqfood23",
      "kqfood24",
      "kqfood25",
      "kqfood26",
      "kqfood27"
    ),
    canonical_name = c(
      "qfood01",
      "qfood02",
      "qfood03",
      "qfood04",
      "qfood05",
      "qfood06",
      "qfood07",
      "qfood08",
      "qfood09",
      "qfood10",
      "qfood11",
      "qfood12",
      "qfood13",
      "qfood14",
      "qfood15",
      "qfood16",
      "qfood17",
      "qfood18",
      "qfood19",
      "qfood20",
      "qfood01",
      "qfood01",
      "qfood21",
      "qfood22",
      "qfood23",
      "qfood24",
      "qfood25",
      "qfood26",
      "qfood27",
      "qfood21",
      "qfood22",
      "qfood23",
      "qfood24",
      "qfood25",
      "qfood26",
      "qfood27",
      "qfood21",
      "qfood22",
      "qfood23",
      "qfood24",
      "qfood25",
      "qfood26",
      "qfood27",
      "qapp1",
      "qapp2",
      "qapp3",
      "qapp4",
      "qfood21",
      "qfood22",
      "qfood23",
      "qfood24",
      "qfood25",
      "qfood26",
      "qfood27"
    ),
    variable_label = c(
      "bite and chew",
      "#times eaten: morning",
      "#times eaten: afternoon",
      "#times eaten: evening",
      "#times eaten: night",
      "diet: low-calorie-poor",
      "diet: low-cholesterol",
      "diet: low-salt",
      "diet: sugar-free",
      "diet: high-calorie",
      "diet: vegetarian",
      "diet: other",
      "fruit spring summer:#days a week",
      "fruit spring summer:#times a day",
      "fruit autumn winter:#days a week",
      "fruit autumn winter:#times a day",
      "vegetables spring summer:#days a week",
      "vegetables spring summer:#times a day",
      "vegetables autums winter:#days a week",
      "vegetables autums winter:#times a day",
      "bite and chew",
      "bite and chew",
      "eat less: disease",
      "less than 2 meals a day",
      "few vegetables, fruit, dairy",
      "eat less: bite and chew problems",
      "eat less: money problems",
      "eat alone mostly",
      "phys. cond. limit shopping and cooking",
      "eat less: disease",
      "less than 2 meals a day",
      "few vegetables, fruit, dairy",
      "eat less: bite and chew problems",
      "eat less: money problems",
      "eat alone mostly",
      "phys. cond. limit shopping and cooking",
      "eat less: disease",
      "less than 2 meals a day",
      "few vegetables, fruit, dairy",
      "eat less: bite and chew problems",
      "eat less: money problems",
      "eat alone mostly",
      "phys. cond. limit shopping and cooking",
      "Appetite: eating a meal",
      "Appetite: general appetite",
      "Appetite: general liking of food",
      "Appetite: number of meals per day",
      "eat less: disease",
      "less than 2 meals a day",
      "few vegetables, fruit, dairy",
      "eat less: bite and chew problems",
      "eat less: money problems",
      "eat alone mostly",
      "phys. cond. limit shopping and cooking"
    ),
    harmonized_var_label = c(
      "bite and chew",
      "#times eaten: morning",
      "#times eaten: afternoon",
      "#times eaten: evening",
      "#times eaten: night",
      "diet: low-calorie-poor",
      "diet: low-cholesterol",
      "diet: low-salt",
      "diet: sugar-free",
      "diet: high-calorie",
      "diet: vegetarian",
      "diet: other",
      "fruit spring summer:#days a week",
      "fruit spring summer:#times a day",
      "fruit autumn winter:#days a week",
      "fruit autumn winter:#times a day",
      "vegetables spring summer:#days a week",
      "vegetables spring summer:#times a day",
      "vegetables autums winter:#days a week",
      "vegetables autums winter:#times a day",
      "bite and chew",
      "bite and chew",
      "eat less: disease",
      "less than 2 meals a day",
      "few vegetables, fruit, dairy",
      "eat less: bite and chew problems",
      "eat less: money problems",
      "eat alone mostly",
      "phys. cond. limit shopping and cooking",
      "eat less: disease",
      "less than 2 meals a day",
      "few vegetables, fruit, dairy",
      "eat less: bite and chew problems",
      "eat less: money problems",
      "eat alone mostly",
      "phys. cond. limit shopping and cooking",
      "eat less: disease",
      "less than 2 meals a day",
      "few vegetables, fruit, dairy",
      "eat less: bite and chew problems",
      "eat less: money problems",
      "eat alone mostly",
      "phys. cond. limit shopping and cooking",
      "Appetite: eating a meal",
      "Appetite: general appetite",
      "Appetite: general liking of food",
      "Appetite: number of meals per day",
      "eat less: disease",
      "less than 2 meals a day",
      "few vegetables, fruit, dairy",
      "eat less: bite and chew problems",
      "eat less: money problems",
      "eat alone mostly",
      "phys. cond. limit shopping and cooking"
    ),
    var_type = c(
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qfood01 = list(
      B = c(
        `-1` = "no answer",
        `1` = "almost never",
        `2` = "some of the day",
        `3` = "often",
        `4` = "most of the time"
      ),
      C = yes_without_trouble_yes_with_some_trouble,
      D = yes_without_trouble_yes_with_some_trouble
    ),
    qfood02 = list(
      B = no_answer
    ),
    qfood03 = list(
      B = no_answer
    ),
    qfood04 = list(
      B = no_answer
    ),
    qfood05 = list(
      B = no_answer
    ),
    qfood06 = list(
      B = no_yes_3
    ),
    qfood07 = list(
      B = no_yes_3
    ),
    qfood08 = list(
      B = no_yes_3
    ),
    qfood09 = list(
      B = no_yes_3
    ),
    qfood10 = list(
      B = no_yes_3
    ),
    qfood11 = list(
      B = no_yes_3
    ),
    qfood12 = list(
      B = no_yes_3
    ),
    qfood13 = list(
      B = no_answer
    ),
    qfood14 = list(
      B = no_answer
    ),
    qfood15 = list(
      B = no_answer
    ),
    qfood16 = list(
      B = no_answer
    ),
    qfood17 = list(
      B = no_answer
    ),
    qfood18 = list(
      B = no_answer
    ),
    qfood19 = list(
      B = no_answer
    ),
    qfood20 = list(
      B = no_answer
    ),
    qfood21 = list(
      H = yes_no,
      I = yes_no,
      J = yes_no,
      K = yes_no
    ),
    qfood22 = list(
      H = yes_no,
      I = yes_no,
      J = yes_no,
      K = yes_no
    ),
    qfood23 = list(
      H = yes_no,
      I = yes_no,
      J = yes_no,
      K = yes_no
    ),
    qfood24 = list(
      H = yes_no,
      I = yes_no,
      J = yes_no,
      K = yes_no
    ),
    qfood25 = list(
      H = yes_no,
      I = yes_no,
      J = yes_no,
      K = yes_no
    ),
    qfood26 = list(
      H = yes_no,
      I = yes_no,
      J = yes_no,
      K = yes_no
    ),
    qfood27 = list(
      H = yes_no,
      I = yes_no,
      J = yes_no,
      K = yes_no
    ),
    qapp1 = list(
      K = c(
        `-1` = "no answer",
        `1` = "satiated after a few bites",
        `2` = "satiated after 1/3 the meal",
        `3` = "satiated after 1/2 the meal",
        `4` = "satiated after most of the meal",
        `5` = "never satiated"
      )
    ),
    qapp2 = list(
      K = very_bad_bad_moderate_good_very_good
    ),
    qapp3 = list(
      K = very_bad_bad_moderate_good_very_good
    ),
    qapp4 = list(
      K = c(
        `-1` = "no answer",
        `1` = "< 1 meal per day",
        `2` = "1 meals per day",
        `3` = "2 meals per day",
        `4` = "3 meals per day",
        `5` = "> 3 meals per day"
      )
    )
  ),

  value_labels_harmonized = list(
    qapp1 = c(
      `-1` = "not available",
      `1` = "satiated after a few bites",
      `2` = "satiated after 1/3 the meal",
      `3` = "satiated after 1/2 the meal",
      `4` = "satiated after most of the meal",
      `5` = "never satiated"
    ),
    qapp2 = very_bad_bad_moderate_good_very_good_2,
    qapp3 = very_bad_bad_moderate_good_very_good_2,
    qapp4 = c(
      `-1` = "not available",
      `1` = "< 1 meal per day",
      `2` = "1 meals per day",
      `3` = "2 meals per day",
      `4` = "3 meals per day",
      `5` = "> 3 meals per day"
    ),
    qfood01 = c(
      `-1` = "not available",
      `1` = "coding category 1",
      `2` = "coding category 2",
      `3` = "coding category 3",
      `4` = "coding category 4"
    ),
    qfood02 = not_available,
    qfood03 = not_available,
    qfood04 = not_available,
    qfood05 = not_available,
    qfood06 = no_yes_33,
    qfood07 = no_yes_33,
    qfood08 = no_yes_33,
    qfood09 = no_yes_33,
    qfood10 = no_yes_33,
    qfood11 = no_yes_33,
    qfood12 = no_yes_33,
    qfood13 = not_available,
    qfood14 = not_available,
    qfood15 = not_available,
    qfood16 = not_available,
    qfood17 = not_available,
    qfood18 = not_available,
    qfood19 = not_available,
    qfood20 = not_available,
    qfood21 = yes_no_2,
    qfood22 = yes_no_2,
    qfood23 = yes_no_2,
    qfood24 = yes_no_2,
    qfood25 = yes_no_2,
    qfood26 = yes_no_2,
    qfood27 = yes_no_2
  )
)
