## LASA filecode 154 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_154 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bmsmokbef",
      "bmsmokebef",
      "bmsmokecig",
      "bmsmokeciga",
      "bmsmokeciganw",
      "bmsmokecignw",
      "bmsmokecigp",
      "bmsmokecigpnw",
      "bmsmokeqage",
      "bmsmokesage",
      "bmsmokeyn",
      "bmsmokebef",
      "bmsmokecig",
      "bmsmokeciga",
      "bmsmokeciganw",
      "bmsmokecignw",
      "bmsmokepipe",
      "bmsmokepm",
      "bmsmokeqage",
      "bmsmokesage",
      "bmsmokesh",
      "bmsmokeshnw",
      "bmsmokeyn",
      "cmsmokebef",
      "cmsmokeciga",
      "cmsmokeciganw",
      "cmsmokecignw",
      "cmsmokepipe",
      "cmsmokepm",
      "cmsmokeqage",
      "cmsmokesage",
      "cmsmokesh",
      "cmsmokeyn",
      "dmsmokebef",
      "dmsmokecig",
      "dmsmokeciga",
      "dmsmokeciganw",
      "dmsmokecignw",
      "dmsmokepipe",
      "dmsmokepm",
      "dmsmokeqage",
      "dmsmokesage",
      "dmsmokesh",
      "dmsmokeshnw",
      "dmsmokeyn",
      "emsmokbef",
      "emsmokebef",
      "emsmokecig",
      "emsmokeciga",
      "emsmokeciganw",
      "emsmokecignw",
      "emsmokecigp",
      "emsmokecigpnw",
      "emsmokeqage",
      "emsmokesage",
      "emsmokeyn",
      "fmsmokbef",
      "fmsmokebef",
      "fmsmokecig",
      "fmsmokeciga",
      "fmsmokeciganw",
      "fmsmokecignw",
      "fmsmokecigp",
      "fmsmokecigpnw",
      "fmsmokeqage",
      "fmsmokesage",
      "fmsmokeyn",
      "gmsmokbef",
      "gmsmokebef",
      "gmsmokecig",
      "gmsmokeciga",
      "gmsmokeciganw",
      "gmsmokecignw",
      "gmsmokecigp",
      "gmsmokecigpnw",
      "gmsmokeqage",
      "gmsmokesage",
      "gmsmokeyn",
      "hmsmokbef",
      "hmsmokebef",
      "hmsmokecig",
      "hmsmokeciga",
      "hmsmokeciganw",
      "hmsmokecigp",
      "hmsmokecigpnw",
      "hmsmokeqage",
      "hmsmokesage",
      "hmsmokeyn",
      "imsmokebef",
      "imsmokecig",
      "imsmokeciga",
      "imsmokeciganw",
      "imsmokecignw",
      "imsmokecignwp",
      "imsmokecigp",
      "imsmokeecig",
      "imsmokeecigd",
      "imsmokeecigf",
      "imsmokeecigp",
      "imsmokeecigpf",
      "imsmokeqage",
      "imsmokesage",
      "imsmokeyn",
      "jmsmokebef",
      "jmsmokecig",
      "jmsmokeciga",
      "jmsmokeciganw",
      "jmsmokecignw",
      "jmsmokecignwp",
      "jmsmokecigp",
      "jmsmokeecig",
      "jmsmokeecigd",
      "jmsmokeecigf",
      "jmsmokeecigp",
      "jmsmokeecigpf",
      "jmsmokeqage",
      "jmsmokesage",
      "jmsmokeyn",
      "kmsmokebef",
      "kmsmokecig",
      "kmsmokeciga",
      "kmsmokeciganw",
      "kmsmokecignw",
      "kmsmokecignwp",
      "kmsmokecigp",
      "kmsmokeecig",
      "kmsmokeecigd",
      "kmsmokeecigf",
      "kmsmokeecigp",
      "kmsmokeecigpf",
      "kmsmokeqage",
      "kmsmokesage",
      "kmsmokeyn",
      "bmsmokebef",
      "bmsmokecignw",
      "bmsmokeqage",
      "bmsmokeyn"
    ),
    canonical_name = c(
      "msmokbef",
      "msmokebef",
      "msmokecig",
      "msmokeciga",
      "msmokeciganw",
      "msmokecignw",
      "msmokecigp",
      "msmokecigpnw",
      "msmokeqage",
      "msmokesage",
      "msmokeyn",
      "msmokebef",
      "msmokecig",
      "msmokeciga",
      "msmokeciganw",
      "msmokecignw",
      "msmokepipe",
      "msmokepm",
      "msmokeqage",
      "msmokesage",
      "msmokesh",
      "msmokeshnw",
      "msmokeyn",
      "msmokebef",
      "msmokeciga",
      "msmokeciganw",
      "msmokecignw",
      "msmokepipe",
      "msmokepm",
      "msmokeqage",
      "msmokesage",
      "msmokesh",
      "msmokeyn",
      "msmokebef",
      "msmokecig",
      "msmokeciga",
      "msmokeciganw",
      "msmokecignw",
      "msmokepipe",
      "msmokepm",
      "msmokeqage",
      "msmokesage",
      "msmokesh",
      "msmokeshnw",
      "msmokeyn",
      "msmokbef",
      "msmokebef",
      "msmokecig",
      "msmokeciga",
      "msmokeciganw",
      "msmokecignw",
      "msmokecigp",
      "msmokecigpnw",
      "msmokeqage",
      "msmokesage",
      "msmokeyn",
      "msmokbef",
      "msmokebef",
      "msmokecig",
      "msmokeciga",
      "msmokeciganw",
      "msmokecignw",
      "msmokecigp",
      "msmokecigpnw",
      "msmokeqage",
      "msmokesage",
      "msmokeyn",
      "msmokbef",
      "msmokebef",
      "msmokecig",
      "msmokeciga",
      "msmokeciganw",
      "msmokecignw",
      "msmokecigp",
      "msmokecigpnw",
      "msmokeqage",
      "msmokesage",
      "msmokeyn",
      "msmokbef",
      "msmokebef",
      "msmokecig",
      "msmokeciga",
      "msmokeciganw",
      "msmokecigp",
      "msmokecigpnw",
      "msmokeqage",
      "msmokesage",
      "msmokeyn",
      "msmokebef",
      "msmokecig",
      "msmokeciga",
      "msmokeciganw",
      "msmokecignw",
      "msmokecignwp",
      "msmokecigp",
      "msmokeecig",
      "msmokeecigd",
      "msmokeecigf",
      "msmokeecigp",
      "msmokeecigpf",
      "msmokeqage",
      "msmokesage",
      "msmokeyn",
      "msmokebef",
      "msmokecig",
      "msmokeciga",
      "msmokeciganw",
      "msmokecignw",
      "msmokecignwp",
      "msmokecigp",
      "msmokeecig",
      "msmokeecigd",
      "msmokeecigf",
      "msmokeecigp",
      "msmokeecigpf",
      "msmokeqage",
      "msmokesage",
      "msmokeyn",
      "msmokebef",
      "msmokecig",
      "msmokeciga",
      "msmokeciganw",
      "msmokecignw",
      "msmokecignwp",
      "msmokecigp",
      "msmokeecig",
      "msmokeecigd",
      "msmokeecigf",
      "msmokeecigp",
      "msmokeecigpf",
      "msmokeqage",
      "msmokesage",
      "msmokeyn",
      "msmokebef",
      "msmokecignw",
      "msmokeqage",
      "msmokeyn"
    ),
    variable_label = c(
      NA_character_,
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "(past) number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      "Did you smoke before",
      "Do you smoke cigarettes",
      "Do you smoke cigars",
      "Number of cigars a week",
      "Number of cigarettes a week",
      "Do you smoke pipe",
      "Number of packets a month",
      "When did you stop smoking: age",
      "When did you start smoking: age",
      "Do you smoke shag",
      "Number of shags a week",
      "Do you smoke",
      "Did you smoke before",
      "smoking: cigars",
      "Number of cigars a week",
      "Number of cigarettes or self-rolled a week",
      "Do you smoke pipe",
      "Number of packs (50 gr.) of pipe tobacco a month",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "smoking: cigarettes or shag",
      "Do you smoke",
      "Did you smoke before",
      "do you smoke cigarettes",
      "do you smoke cigars",
      "Number of cigars a week",
      "Number of cigarettes a week",
      "do you smoke pipe",
      "Number of packs (50 gr.) of pipe tobacco a month",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "do you smoke self-rolled cigarettes",
      "Number of self-rolled cigarettes a week",
      "Do you smoke",
      NA_character_,
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "(past) number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      NA_character_,
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "(past) number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      NA_character_,
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "(past) number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      NA_character_,
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "(past) number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      "Did you smoke before",
      "Do you smoke (self-rolled) cigarettes",
      "Do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) number of (self-rolled) cigarettes a week",
      "(past) Did you smoke (self-rolled) cigarettes",
      "Do you ever use an electronic cigarette",
      "Dosage electronic cigarette",
      "How often do you use the electronic cigarette",
      "(past) did you ever use an electronic cigarette",
      "(past) how often did you use the electronic cigarette",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      "Did you smoke before",
      "Do you smoke (self-rolled) cigarettes",
      "Do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) number of (self-rolled) cigarettes a week",
      "(past) Did you smoke (self-rolled) cigarettes",
      "Do you ever use an electronic cigarette",
      "Dosage electronic cigarette",
      "How often do you use the electronic cigarette",
      "(past) did you ever use an electronic cigarette",
      "(past) how often did you use the electronic cigarette",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      "Did you smoke before",
      "Do you smoke (self-rolled) cigarettes",
      "Do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) number of (self-rolled) cigarettes a week",
      "(past) Did you smoke (self-rolled) cigarettes",
      "Do you ever use an electronic cigarette",
      "Dosage electronic cigarette",
      "How often do you use the electronic cigarette",
      "(past) did you ever use an electronic cigarette",
      "(past) how often did you use the electronic cigarette",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      "Did you smoke before",
      "Number of cigarettes a day",
      "at what age did you stop smoking",
      "Do you smoke"
    ),
    harmonized_var_label = c(
      NA_character_,
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "(past) number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "Do you smoke pipe",
      "Number of packs (50 gr.) of pipe tobacco a month",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "do you smoke self-rolled cigarettes",
      "Number of self-rolled cigarettes a week",
      "Do you smoke",
      "Did you smoke before",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "Do you smoke pipe",
      "Number of packs (50 gr.) of pipe tobacco a month",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "do you smoke self-rolled cigarettes",
      "Do you smoke",
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "Do you smoke pipe",
      "Number of packs (50 gr.) of pipe tobacco a month",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "do you smoke self-rolled cigarettes",
      "Number of self-rolled cigarettes a week",
      "Do you smoke",
      NA_character_,
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "(past) number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      NA_character_,
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "(past) number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      NA_character_,
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "(past) number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      NA_character_,
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "(past) number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "Do you ever use an electronic cigarette",
      "Dosage electronic cigarette",
      "How often do you use the electronic cigarette",
      "(past) did you ever use an electronic cigarette",
      "(past) how often did you use the electronic cigarette",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "Do you ever use an electronic cigarette",
      "Dosage electronic cigarette",
      "How often do you use the electronic cigarette",
      "(past) did you ever use an electronic cigarette",
      "(past) how often did you use the electronic cigarette",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      "Did you smoke before",
      "do you smoke (self-rolled) cigarettes",
      "do you smoke pipe/cigars",
      "Number of pipes/cigars a week",
      "Number of (self-rolled) cigarettes a week",
      "(past) number of (self-rolled) cigarettes a week",
      "(past) did you smoke (self\002rolled) cigarettes",
      "Do you ever use an electronic cigarette",
      "Dosage electronic cigarette",
      "How often do you use the electronic cigarette",
      "(past) did you ever use an electronic cigarette",
      "(past) how often did you use the electronic cigarette",
      "At what age did you stop smoking",
      "At what age did you start smoking",
      "Do you smoke",
      "Did you smoke before",
      "Number of (self-rolled) cigarettes a week",
      "At what age did you stop smoking",
      "Do you smoke"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    msmokbef = list(
      `2B` = na_asked,
      E = na_asked,
      F = na_asked,
      G = na_asked,
      H = na_asked
    ),
    msmokebef = list(
      `2B` = no_yes_141,
      B = c(`-4` = "no valid data", `-2` = "R smokes", `-1` = "no answer, asked", `1` = "no", `2` = "yes"),
      C = c(`-3` = "na, wrong skip", `-2` = "na, see CMSMOKEYN", `1` = "no", `2` = "yes"),
      D = no_yes_142,
      E = no_yes_141,
      F = no_yes_141,
      G = no_yes_141,
      H = no_yes_141,
      I = no_yes_236,
      J = no_yes_236,
      K = no_yes_236,
      MB = c(`-2` = "na, see BMSMOKEYN /")
    ),
    msmokecig = list(
      `2B` = no_yes_5,
      B = no_yes_176,
      D = no_yes_142,
      E = no_yes_5,
      F = no_yes_5,
      G = no_yes_5,
      H = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see E/B/F/GSMOKEYN",
        `-1` = "na, asked",
        `1` = "yes",
        `2` = "no"
      ),
      I = no_yes_63,
      J = no_yes_63,
      K = no_yes_63
    ),
    msmokeciga = list(
      `2B` = yes_no_6,
      B = no_yes_176,
      C = no_yes_5,
      D = no_yes_142,
      E = yes_no_6,
      F = yes_no_6,
      G = yes_no_6,
      H = yes_no_6,
      I = no_yes_63,
      J = no_yes_63,
      K = no_yes_63
    ),
    msmokeciganw = list(
      `2B` = na_see,
      B = c(
        `-4` = "no valid data",
        `-3` = "R does not smoke",
        `-2` = "R smokes, but not cigars",
        `-1` = "no answer, asked"
      ),
      C = c(`-3` = "na, wrong skip", `-2` = "na, see CMSMOKECIGA", `-1` = "na, asked"),
      D = c(`-2` = "na, see DMSMOKECIGA", `-1` = "na, asked"),
      E = na_see,
      F = na_see,
      G = na_see,
      H = na_see,
      I = vs_1_a_week_2,
      J = vs_1_a_week_2,
      K = vs_1_a_week_2
    ),
    msmokecignw = list(
      `2B` = less_than_1_a_week_1_or_less_a_week,
      B = c(
        `-4` = "no valid data",
        `-3` = "R does not smoke",
        `-2` = "R smokes, but not cig",
        `-1` = "no answer, asked"
      ),
      C = c(`-3` = "na, wrong skip", `-2` = "na, see CMSMOKESH", `-1` = "na, asked"),
      D = c(`-2` = "na, see DMSMOKECIG", `-1` = "na, asked"),
      E = less_than_1_a_week_1_or_less_a_week,
      F = na_see_e_b_f_gmsmokecig_na_asked,
      G = na_see_e_b_f_gmsmokecig_na_asked,
      I = vs_1_a_week_3,
      J = vs_1_a_week_3,
      K = vs_1_a_week_3,
      MB = c(
        `-2` = "na, see BMSMOKEYN",
        `-1` = "na, asked",
        `1` = "1-20 cigarettes a day",
        `2` = "more than 20 cigarettes a day"
      )
    ),
    msmokecigp = list(
      `2B` = no_yes_5,
      E = no_yes_5,
      F = no_yes_5,
      G = no_yes_5,
      H = yes_no_6,
      I = na_see_i_j_kmsmokebef_na_asked,
      J = na_see_i_j_kmsmokebef_na_asked,
      K = na_see_i_j_kmsmokebef_na_asked
    ),
    msmokecigpnw = list(
      `2B` = no_yes_5,
      E = no_yes_5,
      F = no_yes_5,
      G = no_yes_5,
      H = c(`-3` = "na, wrong skip", `-2` = "na, see")
    ),
    msmokeqage = list(
      `2B` = na_see,
      B = no_valid_data_r_smokes_r_never_smoked_no_answer_asked,
      C = c(`-3` = "na, wrong skip", `-2` = "na ,see CMSMOKEBEF", `-1` = "na, asked"),
      D = c(`-2` = "na, see DMSMOKEBEF", `-1` = "na, asked"),
      E = na_see,
      F = na_see,
      G = na_see,
      H = na_see,
      I = na_wrong_skip_na_see_i_j_kmsmokebef_na_asked,
      J = na_wrong_skip_na_see_i_j_kmsmokebef_na_asked,
      K = na_wrong_skip_na_see_i_j_kmsmokebef_na_asked,
      MB = c(`-2` = "na, see BMSMOKEBEF", `-1` = "na, asked")
    ),
    msmokesage = list(
      `2B` = na_see_e_b_f_g_hsmokeyn_smokebef_na_asked,
      B = no_valid_data_r_smokes_r_never_smoked_no_answer_asked,
      C = na_wrong_skip_na_see_cmsmokeyn,
      D = c(`-2` = "na, see DMSMOKEYN /"),
      E = na_see_e_b_f_g_hsmokeyn_smokebef_na_asked,
      F = na_see_e_b_f_g_hsmokeyn_smokebef_na_asked,
      G = na_see_e_b_f_g_hsmokeyn_smokebef_na_asked,
      H = na_see_e_b_f_g_hsmokeyn_smokebef_na_asked,
      I = na_see_i_j_kmsmokeyn_na_asked,
      J = na_see_i_j_kmsmokeyn_na_asked,
      K = na_see_i_j_kmsmokeyn_na_asked
    ),
    msmokeyn = list(
      `2B` = no_yes_5,
      B = no_yes_341,
      C = no_yes_5,
      D = no_yes_5,
      E = no_yes_5,
      F = no_yes_5,
      G = no_yes_5,
      H = no_yes_5,
      I = no_yes_237,
      J = no_yes_237,
      K = no_yes_237,
      MB = no_yes
    ),
    msmokepipe = list(
      B = no_yes_176,
      C = no_yes_5,
      D = no_yes_142
    ),
    msmokepm = list(
      B = c(
        `-4` = "no valid data",
        `-3` = "R does not smoke",
        `-2` = "R smokes, but not pipe",
        `-1` = "no answer, asked"
      ),
      C = c(`-3` = "na, wrong skip", `-2` = "na, see CMSMOKEPIPE", `-1` = "na, asked"),
      D = c(`-2` = "na, see DMSMOKEPIPE", `-1` = "na, asked")
    ),
    msmokesh = list(
      B = no_yes_176,
      C = na_wrong_skip_na_see_cmsmokeyn,
      D = no_yes_142
    ),
    msmokeshnw = list(
      B = c(
        `-4` = "no valid data",
        `-3` = "R does not smoke",
        `-2` = "R smokes, but not shag",
        `-1` = "no answer, asked"
      ),
      D = c(`-2` = "na, see DMSMOKESH", `-1` = "na, asked")
    ),
    msmokecignwp = list(
      I = vs_1_a_week,
      J = vs_1_a_week,
      K = vs_1_a_week
    ),
    msmokeecig = list(
      I = no_yes_63,
      J = no_yes_63,
      K = no_yes_63
    ),
    msmokeecigd = list(
      I = no_nicotine_1_10_mg_nicotine_11_20_mg_nicotine,
      J = no_nicotine_1_10_mg_nicotine_11_20_mg_nicotine,
      K = no_nicotine_1_10_mg_nicotine_11_20_mg_nicotine
    ),
    msmokeecigf = list(
      I = most_of_the_day_a_few_times_a_day_a_few_times_a_week,
      J = most_of_the_day_a_few_times_a_day_a_few_times_a_week,
      K = most_of_the_day_a_few_times_a_day_a_few_times_a_week
    ),
    msmokeecigp = list(
      I = no_yes_177,
      J = no_yes_177,
      K = no_yes_177
    ),
    msmokeecigpf = list(
      I = most_of_the_day_a_few_times_a_day_a_few_times_a_week_2,
      J = most_of_the_day_a_few_times_a_day_a_few_times_a_week_2,
      K = most_of_the_day_a_few_times_a_day_a_few_times_a_week_2
    )
  ),

  value_labels_harmonized = list(
    msmokbef = na_asked,
    msmokebef = c(
      `-4` = "no valid data",
      `-3` = "na, wrong skip",
      `-2` = "R smokes / na, see CMSMOKEYN",
      `-1` = "no answer, asked / na, short interview",
      `1` = "no",
      `2` = "yes"
    ),
    msmokecig = no_yes_yes_no_3,
    msmokeciga = no_yes_yes_no_3,
    msmokeciganw = c(
      `-4` = "no valid data",
      `-3` = "R does not smoke / na, wrong skip",
      `-2` = "R smokes, but not cigars / na, see CMSMOKECIGA / na, see",
      `-1` = "no answer, asked",
      `0` = "< 1 a week"
    ),
    msmokecignw = c(
      `-4` = "no valid data",
      `-3` = "R does not smoke / na, wrong skip",
      `-2` = "R smokes, but not cig / na, see CMSMOKESH",
      `-1` = "no answer, asked",
      `0` = "less than 1 a week",
      `1` = "1 or less a week / 1-20 cigarettes a day",
      `2` = "more than 20 cigarettes a day"
    ),
    msmokecignwp = vs_1_a_week,
    msmokecigp = c(
      `-5` = "na, interview terminated",
      `-3` = "na, wrong skip",
      `-2` = "na, see E/B/F/G/HMSMOKEYN",
      `-1` = "na, asked",
      `1` = "no / yes",
      `2` = "yes / no"
    ),
    msmokecigpnw = c(
      `-5` = "na, interview terminated",
      `-3` = "na, wrong skip",
      `-2` = "na, see",
      `-1` = "na, asked",
      `1` = "no",
      `2` = "yes"
    ),
    msmokeecig = no_yes_63,
    msmokeecigd = no_nicotine_1_10_mg_nicotine_11_20_mg_nicotine,
    msmokeecigf = most_of_the_day_a_few_times_a_day_a_few_times_a_week,
    msmokeecigp = no_yes_177,
    msmokeecigpf = most_of_the_day_a_few_times_a_day_a_few_times_a_week_2,
    msmokepipe = c(
      `-5` = "na, interview terminated",
      `-4` = "no valid data",
      `-2` = "R does not smoke / na, see DMSMOKEYN",
      `-1` = "no answer, asked",
      `1` = "no",
      `2` = "yes"
    ),
    msmokepm = c(
      `-4` = "no valid data",
      `-3` = "R does not smoke / na, wrong skip",
      `-2` = "R smokes, but not pipe / na, see CMSMOKEPIPE",
      `-1` = "no answer, asked"
    ),
    msmokeqage = c(
      `-4` = "no valid data",
      `-3` = "R smokes / na, wrong skip",
      `-2` = "R never smoked / na ,see CMSMOKEBEF / na, see DMSMOKEBEF / na, see",
      `-1` = "no answer, asked"
    ),
    msmokesage = c(
      `-4` = "no valid data",
      `-3` = "R smokes / na, wrong skip",
      `-2` = "R never smoked / na, see CMSMOKEYN /",
      `-1` = "no answer, asked"
    ),
    msmokesh = c(
      `-4` = "no valid data",
      `-3` = "na, wrong skip",
      `-2` = "R does not smoke / na, see CMSMOKEYN /",
      `-1` = "no answer, asked",
      `1` = "no",
      `2` = "yes"
    ),
    msmokeshnw = c(
      `-4` = "no valid data",
      `-3` = "R does not smoke",
      `-2` = "R smokes, but not shag / na, see DMSMOKESH",
      `-1` = "no answer, asked"
    ),
    msmokeyn = c(
      `-5` = "na, interview terminated",
      `-4` = "no valid data",
      `-2` = "no answer, skipped",
      `-1` = "no answer, asked / na, short interview",
      `1` = "no",
      `2` = "yes"
    )
  )
)
