## LASA filecode 226 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_226 <- list(
  variables = data.frame(
    wave = c(
      "3B",
      "3B",
      "B",
      "B",
      "C",
      "C",
      "D",
      "D",
      "E",
      "E",
      "F",
      "F",
      "G",
      "G",
      "H",
      "H",
      "I",
      "I",
      "J",
      "J",
      "MB",
      "MB"
    ),
    variable_name = c(
      "banxint",
      "brmanx",
      "banxint",
      "brmanx",
      "canxint",
      "crmanx",
      "danxint",
      "drmanx",
      "eanxint",
      "ermanx",
      "fanxint",
      "frmanx",
      "ganxint",
      "grmanx",
      "hanxint",
      "hrmanx",
      "ianxint",
      "irmanx",
      "janxint",
      "jrmanx",
      "bmanxint",
      "bmrmanx"
    ),
    canonical_name = c(
      "anxint",
      "rmanx",
      "anxint",
      "rmanx",
      "anxint",
      "rmanx",
      "anxint",
      "rmanx",
      "anxint",
      "rmanx",
      "anxint",
      "rmanx",
      "anxint",
      "rmanx",
      "anxint",
      "rmanx",
      "anxint",
      "rmanx",
      "anxint",
      "rmanx",
      "anxint",
      "rmanx"
    ),
    variable_label = c(
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score",
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score",
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score",
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score",
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score",
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score",
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score",
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score",
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score",
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score",
      "ANXIETY SCALE TOTAL SCORE INTEGER",
      "Reason no anxiety scale score"
    ),
    harmonized_var_label = c(
      "Anxiety scale total score",
      "Reason for missing anxiety scale score",
      "Anxiety scale total score",
      "Reason for missing anxiety scale score",
      "Anxiety scale total score",
      "Reason for missing anxiety scale score",
      "Anxiety scale total score",
      "Reason for missing anxiety scale score",
      "Anxiety scale total score",
      "Reason for missing anxiety scale score",
      "Anxiety scale total score",
      "Reason for missing anxiety scale score",
      "Anxiety scale total score",
      "Reason for missing anxiety scale score",
      "Anxiety scale total score",
      "Reason for missing anxiety scale score",
      "Anxiety scale total score",
      "Reason for missing anxiety scale score",
      "Anxiety scale total score",
      "Reason for missing anxiety scale score",
      "Anxiety scale total score",
      "Reason for missing anxiety scale score"
    ),
    var_type = c(
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    anxint = list(
      `3B` = no_valid_data_5,
      B = c(`-2` = "na, see BRMANX", `0` = NA_character_, `21` = NA_character_),
      C = no_valid_data_5,
      D = no_valid_data_5,
      E = no_valid_data_5,
      F = no_valid_data_5,
      G = no_valid_data_5,
      H = no_valid_data_5,
      I = no_valid_data_5,
      J = no_valid_data_5,
      MB = no_valid_data_5
    ),
    rmanx = list(
      `3B` = short_interview_interview_terminated_too_many_missings,
      B = short_interview_interview_terminated_too_many_missings_3,
      C = short_interview_interview_terminated_too_many_missings,
      D = short_interview_interview_terminated_too_many_missings,
      E = short_interview_interview_terminated_too_many_missings,
      F = short_interview_interview_terminated_too_many_missings,
      G = short_interview_interview_terminated_too_many_missings,
      H = short_interview_interview_terminated_too_many_missings,
      I = short_interview_interview_terminated_too_many_missings,
      J = short_interview_interview_terminated_too_many_missings,
      MB = short_interview_interview_terminated_too_many_missings
    )
  ),

  value_labels_harmonized = list(
    anxint = no_valid_data_5,
    rmanx = short_interview_interview_terminated_too_many_missings_3
  )
)
