## LASA filecode 139 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_139 <- list(
  variables = data.frame(
    wave = c(
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bqpadl1",
      "bqpadl2",
      "bqpadl3",
      "bqpadl4",
      "bqpadl5",
      "bqpadl6",
      "bqpdeme",
      "bqpdis1",
      "bqpdis2",
      "bqpdis3",
      "bqpdis4",
      "bqpmemo",
      "bqprel1",
      "bqprel2",
      "bqprel3",
      "bqprel4",
      "bqprel5",
      "bqprel6",
      "bqprel7",
      "bqprel8",
      "bqptalk",
      "eqpadl1",
      "eqpadl2",
      "eqpadl3",
      "eqpadl4",
      "eqpadl5",
      "eqpadl6",
      "eqpdeme",
      "eqpdis1",
      "eqpdis2",
      "eqpdis3",
      "eqpdis4",
      "eqpmemo",
      "eqprel1",
      "eqprel2",
      "eqprel3",
      "eqprel4",
      "eqprel5",
      "eqprel6",
      "eqprel7",
      "eqprel8",
      "eqptalk",
      "fqpadl1",
      "fqpadl2",
      "fqpadl3",
      "fqpadl4",
      "fqpadl5",
      "fqpadl6",
      "fqpdeme",
      "fqpdis1",
      "fqpdis2",
      "fqpdis3",
      "fqpdis4",
      "fqpmemo",
      "fqprel1",
      "fqprel2",
      "fqprel3",
      "fqprel4",
      "fqprel5",
      "fqprel6",
      "fqprel7",
      "fqprel8",
      "fqptalk",
      "gqpadl1",
      "gqpadl2",
      "gqpadl3",
      "gqpadl4",
      "gqpadl5",
      "gqpadl6",
      "gqpdeme",
      "gqpdis1",
      "gqpdis2",
      "gqpdis3",
      "gqpdis4",
      "gqpmemo",
      "gqprel1",
      "gqprel2",
      "gqprel3",
      "gqprel4",
      "gqprel5",
      "gqprel6",
      "gqprel7",
      "gqprel8",
      "gqptalk",
      "hqpadl1",
      "hqpadl2",
      "hqpadl3",
      "hqpadl4",
      "hqpadl5",
      "hqpadl6",
      "hqpdeme",
      "hqpdis1",
      "hqpdis2",
      "hqpdis3",
      "hqpdis4",
      "hqpmemo",
      "hqprel1",
      "hqprel2",
      "hqprel3",
      "hqprel4",
      "hqprel5",
      "hqprel6",
      "hqprel7",
      "hqprel8",
      "hqptalk",
      "iqpadl1",
      "iqpadl2",
      "iqpadl3",
      "iqpadl4",
      "iqpadl5",
      "iqpadl6",
      "iqpdeme",
      "iqpdis1",
      "iqpdis2",
      "iqpdis3",
      "iqpdis4",
      "iqpmemo",
      "iqprel1",
      "iqprel2",
      "iqprel3",
      "iqprel4",
      "iqprel5",
      "iqprel6",
      "iqprel7",
      "iqprel8",
      "iqprespc1",
      "iqprespc2",
      "iqprespc3",
      "iqprespc4",
      "iqptalk",
      "jqpadl1",
      "jqpadl2",
      "jqpadl3",
      "jqpadl4",
      "jqpadl5",
      "jqpadl6",
      "jqpdeme",
      "jqpdis1",
      "jqpdis2",
      "jqpdis3",
      "jqpdis4",
      "jqpmemo",
      "jqprel1",
      "jqprel2",
      "jqprel3",
      "jqprel4",
      "jqprel5",
      "jqprel6",
      "jqprel7",
      "jqprel8",
      "jqprespc1",
      "jqprespc2",
      "jqprespc3",
      "jqprespc4",
      "jqptalk",
      "kqpadl1",
      "kqpadl2",
      "kqpadl3",
      "kqpadl4",
      "kqpadl5",
      "kqpdeme",
      "kqpmemo",
      "kqprel1",
      "kqprel2",
      "kqprel3",
      "kqprel4",
      "kqprel5",
      "kqprel6",
      "kqprespc1",
      "kqprespc2",
      "kqprespc3",
      "kqprespc4",
      "kqptalk"
    ),
    canonical_name = c(
      "qpadl1",
      "qpadl2",
      "qpadl3",
      "qpadl4",
      "qpadl5",
      "qpadl6",
      "qpdeme",
      "qpdis1",
      "qpdis2",
      "qpdis3",
      "qpdis4",
      "qpmemo",
      "qprel1",
      "qprel2",
      "qprel3",
      "qprel4",
      "qprel5",
      "qprel6",
      "qprel7",
      "qprel8",
      "qptalk",
      "qpadl1",
      "qpadl2",
      "qpadl3",
      "qpadl4",
      "qpadl5",
      "qpadl6",
      "qpdeme",
      "qpdis1",
      "qpdis2",
      "qpdis3",
      "qpdis4",
      "qpmemo",
      "qprel1",
      "qprel2",
      "qprel3",
      "qprel4",
      "qprel5",
      "qprel6",
      "qprel7",
      "qprel8",
      "qptalk",
      "qpadl1",
      "qpadl2",
      "qpadl3",
      "qpadl4",
      "qpadl5",
      "qpadl6",
      "qpdeme",
      "qpdis1",
      "qpdis2",
      "qpdis3",
      "qpdis4",
      "qpmemo",
      "qprel1",
      "qprel2",
      "qprel3",
      "qprel4",
      "qprel5",
      "qprel6",
      "qprel7",
      "qprel8",
      "qptalk",
      "qpadl1",
      "qpadl2",
      "qpadl3",
      "qpadl4",
      "qpadl5",
      "qpadl6",
      "qpdeme",
      "qpdis1",
      "qpdis2",
      "qpdis3",
      "qpdis4",
      "qpmemo",
      "qprel1",
      "qprel2",
      "qprel3",
      "qprel4",
      "qprel5",
      "qprel6",
      "qprel7",
      "qprel8",
      "qptalk",
      "qpadl1",
      "qpadl2",
      "qpadl3",
      "qpadl4",
      "qpadl5",
      "qpadl6",
      "qpdeme",
      "qpdis1",
      "qpdis2",
      "qpdis3",
      "qpdis4",
      "qpmemo",
      "qprel1",
      "qprel2",
      "qprel3",
      "qprel4",
      "qprel5",
      "qprel6",
      "qprel7",
      "qprel8",
      "qptalk",
      "qpadl1",
      "qpadl2",
      "qpadl3",
      "qpadl4",
      "qpadl5",
      "qpadl6",
      "qpdeme",
      "qpdis1",
      "qpdis2",
      "qpdis3",
      "qpdis4",
      "qpmemo",
      "qprel1",
      "qprel2",
      "qprel3",
      "qprel4",
      "qprel5",
      "qprel6",
      "qprel7",
      "qprel8",
      "qprespc1",
      "qprespc2",
      "qprespc3",
      "qprespc4",
      "qptalk",
      "qpadl1",
      "qpadl2",
      "qpadl3",
      "qpadl4",
      "qpadl5",
      "qpadl6",
      "qpdeme",
      "qpdis1",
      "qpdis2",
      "qpdis3",
      "qpdis4",
      "qpmemo",
      "qprel1",
      "qprel2",
      "qprel3",
      "qprel4",
      "qprel5",
      "qprel6",
      "qprel7",
      "qprel8",
      "qprespc1",
      "qprespc2",
      "qprespc3",
      "qprespc4",
      "qptalk",
      "qpadl1",
      "qpadl2",
      "qpadl3",
      "qpadl4",
      "qpadl5",
      "qpdeme",
      "qpmemo",
      "qprel1",
      "qprel2",
      "qprel3",
      "qprel4",
      "qprel5",
      "qprel6",
      "qprespc1",
      "qprespc2",
      "qprespc3",
      "qprespc4",
      "qptalk"
    ),
    variable_label = c(
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner respite care: daytime activities",
      "Partner respite care: overnight stay in care institution",
      "Partner respite care: lodging facility for a few days",
      "Partner respite care: minder, so R can go away part of the day",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner respite care: daytime activities",
      "Partner respite care: overnight stay in care institution",
      "Partner respite care: lodging facility for a few days",
      "Partner respite care: minder, so R can go away part of the day",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner diagnosed with dementia",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner respite care: daytime activities",
      "Partner respite care: overnight stay in care institution",
      "Partner respite care: lodging facility for a few days",
      "Partner respite care: minder, so R can go away part of the day",
      "Partner important conversation"
    ),
    harmonized_var_label = c(
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner respite care: daytime activities",
      "Partner respite care: overnight stay in care institution",
      "Partner respite care: lodging facility for a few days",
      "Partner respite care: minder, so R can go away part of the day",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner func. lim. 6: public transportation",
      "Partner diagnosed with dementia",
      "Partner dispute 1: financial affairs",
      "Partner dispute 2: domestic affairs",
      "Partner dispute 3: spare time",
      "Partner dispute 4: consideration",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner rel. 7: evaluation now",
      "Partner rel. 8: evaluation 10 years ago",
      "Partner respite care: daytime activities",
      "Partner respite care: overnight stay in care institution",
      "Partner respite care: lodging facility for a few days",
      "Partner respite care: minder, so R can go away part of the day",
      "Partner important conversation",
      "Partner func. lim. 1: stairs",
      "Partner func. lim. 2: dress",
      "Partner func. lim. 3: chair",
      "Partner func. lim. 4: toenails",
      "Partner func. lim. 5: walk",
      "Partner diagnosed with dementia",
      "Partner problem with memory",
      "Partner rel. 1: daily support",
      "Partner rel. 2: motivated",
      "Partner rel. 3: personality",
      "Partner rel. 4: consideration",
      "Partner rel. 5: disputes",
      "Partner rel. 6: decision making",
      "Partner respite care: daytime activities",
      "Partner respite care: overnight stay in care institution",
      "Partner respite care: lodging facility for a few days",
      "Partner respite care: minder, so R can go away part of the day",
      "Partner important conversation"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qpadl1 = list(
      `3B` = no_partner_cannot_only_with_help,
      E = no_partner_cannot_only_with_help,
      F = no_partner_cannot_only_with_help,
      G = no_partner_cannot_only_with_help,
      H = no_partner_cannot_only_with_help,
      I = no_partner_cannot_only_with_help,
      J = no_partner_cannot_only_with_help,
      K = no_partner_cannot_only_with_help
    ),
    qpadl2 = list(
      `3B` = no_partner_cannot_only_with_help,
      E = no_partner_cannot_only_with_help,
      F = no_partner_cannot_only_with_help,
      G = no_partner_cannot_only_with_help,
      H = no_partner_cannot_only_with_help,
      I = no_partner_cannot_only_with_help,
      J = no_partner_cannot_only_with_help,
      K = no_partner_cannot_only_with_help
    ),
    qpadl3 = list(
      `3B` = no_partner_cannot_only_with_help,
      E = no_partner_cannot_only_with_help,
      F = no_partner_cannot_only_with_help,
      G = no_partner_cannot_only_with_help,
      H = no_partner_cannot_only_with_help,
      I = no_partner_cannot_only_with_help,
      J = no_partner_cannot_only_with_help,
      K = no_partner_cannot_only_with_help
    ),
    qpadl4 = list(
      `3B` = no_partner_cannot_only_with_help,
      E = no_partner_cannot_only_with_help,
      F = no_partner_cannot_only_with_help,
      G = no_partner_cannot_only_with_help,
      H = no_partner_cannot_only_with_help,
      I = no_partner_cannot_only_with_help,
      J = no_partner_cannot_only_with_help,
      K = no_partner_cannot_only_with_help
    ),
    qpadl5 = list(
      `3B` = no_partner_cannot_only_with_help,
      E = no_partner_cannot_only_with_help,
      F = no_partner_cannot_only_with_help,
      G = no_partner_cannot_only_with_help,
      H = no_partner_cannot_only_with_help,
      I = no_partner_cannot_only_with_help,
      J = no_partner_cannot_only_with_help,
      K = no_partner_cannot_only_with_help
    ),
    qpadl6 = list(
      `3B` = no_partner_cannot_only_with_help,
      E = no_partner_cannot_only_with_help,
      F = no_partner_cannot_only_with_help,
      G = no_partner_cannot_only_with_help,
      H = no_partner_cannot_only_with_help,
      I = no_partner_cannot_only_with_help,
      J = no_partner_cannot_only_with_help
    ),
    qpdeme = list(
      `3B` = no_yes_38,
      E = no_yes_38,
      F = no_yes_38,
      G = no_yes_38,
      H = no_yes_38,
      I = no_yes_214,
      J = no_yes_214,
      K = no_yes_214
    ),
    qpdis1 = list(
      `3B` = strongly_in_disagreement_reasonably_in_disagreement,
      E = strongly_in_disagreement_reasonably_in_disagreement,
      F = strongly_in_disagreement_reasonably_in_disagreement,
      G = strongly_in_disagreement_reasonably_in_disagreement,
      H = strongly_in_disagreement_reasonably_in_disagreement,
      I = strongly_in_disagreement_reasonably_in_disagreement,
      J = strongly_in_disagreement_reasonably_in_disagreement
    ),
    qpdis2 = list(
      `3B` = strongly_in_disagreement_reasonably_in_disagreement,
      E = strongly_in_disagreement_reasonably_in_disagreement,
      F = strongly_in_disagreement_reasonably_in_disagreement,
      G = strongly_in_disagreement_reasonably_in_disagreement,
      H = strongly_in_disagreement_reasonably_in_disagreement,
      I = strongly_in_disagreement_reasonably_in_disagreement,
      J = strongly_in_disagreement_reasonably_in_disagreement
    ),
    qpdis3 = list(
      `3B` = strongly_in_disagreement_reasonably_in_disagreement,
      E = strongly_in_disagreement_reasonably_in_disagreement,
      F = strongly_in_disagreement_reasonably_in_disagreement,
      G = strongly_in_disagreement_reasonably_in_disagreement,
      H = strongly_in_disagreement_reasonably_in_disagreement,
      I = strongly_in_disagreement_reasonably_in_disagreement,
      J = strongly_in_disagreement_reasonably_in_disagreement
    ),
    qpdis4 = list(
      `3B` = strongly_in_disagreement_reasonably_in_disagreement,
      E = strongly_in_disagreement_reasonably_in_disagreement,
      F = strongly_in_disagreement_reasonably_in_disagreement,
      G = strongly_in_disagreement_reasonably_in_disagreement,
      H = strongly_in_disagreement_reasonably_in_disagreement,
      I = strongly_in_disagreement_reasonably_in_disagreement,
      J = strongly_in_disagreement_reasonably_in_disagreement
    ),
    qpmemo = list(
      `3B` = no_yes_38,
      E = no_yes_38,
      F = no_yes_38,
      G = no_yes_38,
      H = no_yes_38,
      I = no_yes_38,
      J = no_yes_38,
      K = no_yes_38
    ),
    qprel1 = list(
      `3B` = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      E = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      F = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      G = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      H = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      I = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      J = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      K = very_dissatisfied_dissatisfied_a_little_dissatisfied
    ),
    qprel2 = list(
      `3B` = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      E = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      F = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      G = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      H = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      I = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      J = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      K = very_dissatisfied_dissatisfied_a_little_dissatisfied
    ),
    qprel3 = list(
      `3B` = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      E = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      F = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      G = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      H = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      I = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      J = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      K = very_dissatisfied_dissatisfied_a_little_dissatisfied
    ),
    qprel4 = list(
      `3B` = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      E = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      F = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      G = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      H = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      I = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      J = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      K = very_dissatisfied_dissatisfied_a_little_dissatisfied
    ),
    qprel5 = list(
      `3B` = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      E = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      F = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      G = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      H = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      I = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      J = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      K = very_dissatisfied_dissatisfied_a_little_dissatisfied
    ),
    qprel6 = list(
      `3B` = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      E = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      F = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      G = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      H = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      I = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      J = very_dissatisfied_dissatisfied_a_little_dissatisfied,
      K = very_dissatisfied_dissatisfied_a_little_dissatisfied
    ),
    qprel7 = list(
      `3B` = no_partner_no_answer,
      E = no_partner_no_answer,
      F = no_partner_no_answer,
      G = no_partner_no_answer,
      H = no_partner_no_answer,
      I = no_partner_no_answer,
      J = no_partner_no_answer
    ),
    qprel8 = list(
      `3B` = no_partner_no_answer,
      E = no_partner_no_answer,
      F = no_partner_no_answer,
      G = no_partner_no_answer,
      H = no_partner_no_answer,
      I = no_partner_no_answer,
      J = no_partner_no_answer
    ),
    qptalk = list(
      `3B` = at_least_once_a_day_a_few_times_a_week_once_a_week,
      E = at_least_once_a_day_a_few_times_a_week_once_a_week,
      F = at_least_once_a_day_a_few_times_a_week_once_a_week,
      G = at_least_once_a_day_a_few_times_a_week_once_a_week,
      H = at_least_once_a_day_a_few_times_a_week_once_a_week,
      I = at_least_once_a_day_a_few_times_a_week_once_a_week,
      J = at_least_once_a_day_a_few_times_a_week_once_a_week,
      K = at_least_once_a_day_a_few_times_a_week_once_a_week
    ),
    qprespc1 = list(
      I = no_yes_41,
      J = no_yes_41,
      K = no_yes_41
    ),
    qprespc2 = list(
      I = no_yes_41,
      J = no_yes_41,
      K = no_yes_41
    ),
    qprespc3 = list(
      I = no_yes_41,
      J = no_yes_41,
      K = no_yes_41
    ),
    qprespc4 = list(
      I = no_yes_41,
      J = no_yes_41,
      K = no_yes_41
    )
  ),

  value_labels_harmonized = list(
    qpadl1 = no_partner_cannot_only_with_help_2,
    qpadl2 = no_partner_cannot_only_with_help_2,
    qpadl3 = no_partner_cannot_only_with_help_2,
    qpadl4 = no_partner_cannot_only_with_help_2,
    qpadl5 = no_partner_cannot_only_with_help_2,
    qpadl6 = no_partner_cannot_only_with_help_2,
    qpdeme = no_yes_20,
    qpdis1 = strongly_in_disagreement_reasonably_in_disagreement_2,
    qpdis2 = strongly_in_disagreement_reasonably_in_disagreement_2,
    qpdis3 = strongly_in_disagreement_reasonably_in_disagreement_2,
    qpdis4 = strongly_in_disagreement_reasonably_in_disagreement_2,
    qpmemo = no_yes_20,
    qprel1 = very_dissatisfied_dissatisfied_a_little_dissatisfied_2,
    qprel2 = very_dissatisfied_dissatisfied_a_little_dissatisfied_2,
    qprel3 = very_dissatisfied_dissatisfied_a_little_dissatisfied_2,
    qprel4 = very_dissatisfied_dissatisfied_a_little_dissatisfied_2,
    qprel5 = very_dissatisfied_dissatisfied_a_little_dissatisfied_2,
    qprel6 = very_dissatisfied_dissatisfied_a_little_dissatisfied_2,
    qprel7 = not_available_not_available_4,
    qprel8 = not_available_not_available_4,
    qprespc1 = no_yes_43,
    qprespc2 = no_yes_43,
    qprespc3 = no_yes_43,
    qprespc4 = no_yes_43,
    qptalk = c(
      `-2` = "not available",
      `-1` = "not available",
      `1` = "at least once a day",
      `2` = "a few times a week",
      `3` = "once a week",
      `4` = "once a month",
      `5` = "less than once a month"
    )
  )
)
