## LASA filecode 047 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_047 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bdomain",
      "bdomtyp",
      "bemo_giv",
      "bemo_rec",
      "bfreqran",
      "bins_giv",
      "bins_rec",
      "bnwconf",
      "bnwfreq",
      "bnwinhh",
      "bnwmem",
      "bnwsex",
      "bnwtrav",
      "bnwtype",
      "brandom",
      "bsequenc",
      "bdomain",
      "bdomtyp",
      "bemo_giv",
      "bemo_rec",
      "bfreqran",
      "bins_giv",
      "bins_rec",
      "bnwconf",
      "bnwfreq",
      "bnwinhh",
      "bnwmem",
      "bnwsex",
      "bnwtrav",
      "bnwtype",
      "bsequenc",
      "bdomain",
      "bdomtyp",
      "bemo_giv",
      "bemo_rec",
      "bfreqran",
      "bins_giv",
      "bins_rec",
      "bnwfreq",
      "bnwinhh",
      "bnwmem",
      "bnwmsupp",
      "bnwpart",
      "bnwsex",
      "bnwtrav",
      "bnwtype",
      "brandom",
      "bsequenc",
      "cdomain",
      "cdomtyp",
      "cemo_giv",
      "cemo_rec",
      "cfreqran",
      "cins_giv",
      "cins_rec",
      "cnwconf",
      "cnwfreq",
      "cnwinhh",
      "cnwmem",
      "cnwsex",
      "cnwtrav",
      "cnwtype",
      "crandom",
      "csequenc",
      "ddomain",
      "ddomtyp",
      "demo_giv",
      "demo_rec",
      "dfreqran",
      "dins_giv",
      "dins_rec",
      "dnwconf",
      "dnwfreq",
      "dnwinhh",
      "dnwmem",
      "dnwsex",
      "dnwtrav",
      "dnwtype",
      "drandom",
      "dsequenc",
      "edomain",
      "edomtyp",
      "eemo_giv",
      "eemo_rec",
      "efreqran",
      "eins_giv",
      "eins_rec",
      "enwconf",
      "enwfreq",
      "enwinhh",
      "enwmem",
      "enwsex",
      "enwtrav",
      "enwtype",
      "erandom",
      "esequenc",
      "fdomain",
      "fdomtyp",
      "femo_giv",
      "femo_rec",
      "ffreqran",
      "fins_giv",
      "fins_rec",
      "fnwconf",
      "fnwfreq",
      "fnwinhh",
      "fnwmem",
      "fnwsex",
      "fnwtrav",
      "fnwtype",
      "frandom",
      "fsequenc",
      "gdomain",
      "gdomtyp",
      "gemo_giv",
      "gemo_rec",
      "gfreqran",
      "gins_giv",
      "gins_rec",
      "gnwconf",
      "gnwfreq",
      "gnwinhh",
      "gnwmem",
      "gnwsex",
      "gnwtrav",
      "gnwtype",
      "grandom",
      "gsequenc",
      "hdomain",
      "hdomtyp",
      "hemo_giv",
      "hemo_rec",
      "hfreqran",
      "hins_giv",
      "hins_rec",
      "hnwconf",
      "hnwfreq",
      "hnwinhh",
      "hnwmem",
      "hnwsex",
      "hnwtrav",
      "hnwtype",
      "hsequenc",
      "idomain",
      "idomtyp",
      "iemo_giv",
      "iemo_rec",
      "ifreqran",
      "iins_giv",
      "iins_rec",
      "inwconf",
      "inwfreq",
      "inwinhh",
      "inwmem",
      "inwsex",
      "inwtrav",
      "inwtype",
      "isequenc",
      "jdomain",
      "jdomtyp",
      "jemo_giv",
      "jemo_rec",
      "jfreqran",
      "jins_giv",
      "jins_rec",
      "jnwconf",
      "jnwfreq",
      "jnwinhh",
      "jnwmem",
      "jnwsex",
      "jnwtrav",
      "jnwtype",
      "jsequenc",
      "kdomain",
      "kdomtyp",
      "kemo_giv",
      "kemo_rec",
      "kfreqran",
      "kins_giv",
      "kins_rec",
      "knwconf",
      "knwfreq",
      "knwinhh",
      "knwmem",
      "knwsex",
      "knwtrav",
      "knwtype",
      "ksequenc"
    ),
    canonical_name = c(
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "random",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwmsupp",
      "nwpart",
      "nwsex",
      "nwtrav",
      "nwtype",
      "random",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "random",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "random",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "random",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "random",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "random",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "sequenc",
      "domain",
      "domtyp",
      "emo_giv",
      "emo_rec",
      "freqran",
      "ins_giv",
      "ins_rec",
      "nwconf",
      "nwfreq",
      "nwinhh",
      "nwmem",
      "nwsex",
      "nwtrav",
      "nwtype",
      "sequenc"
    ),
    variable_label = c(
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "most supportive network member support Q's:",
      "marital/partner status network member",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)"
    ),
    harmonized_var_label = c(
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "most supportive network member support Q's:",
      "marital/partner status network member",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "used in ranking ties frequency",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)",
      "domain in which nominated",
      "domain type (variable is recoded in Xnwinhh en Xnwtype)",
      "emotional support given (\"... told you about his/her personal experiences and feelings\")",
      "emotional support received (\"you told ... about your personal experiences and feelings\")",
      "ranking # frequency",
      "instrumental support given (\"you helped ... with daily chores in and around the house\")",
      "instrumental support received (\"... helped you with daily chores in and around the house\")",
      "confidant identification (Which of all the",
      "frequency of contact <1- 8> (\"How",
      "sharing the household with R",
      "network member id = respondent id followed by 2 digits 01..99(max). Each occurrence describes a network relation with R",
      "sex network member",
      "travelling time to network member (minutes)",
      "relationship type (What relationship do you have with ...? / In welke relatie staat ... tot u?)",
      "sequence questions on support (e=emotional i=instrumental r=received g=given)"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    domain = list(
      `2B` = household_children_in_law_other_kin_neighborhood,
      `3B` = household_children_in_law_other_kin_neighborhood,
      B = household_children_in_law_other_kin_neighborhood,
      C = household_children_in_law_other_kin_neighborhood,
      D = household_children_in_law_other_kin_neighborhood,
      E = household_children_in_law_other_kin_neighborhood,
      F = household_children_in_law_other_kin_neighborhood,
      G = household_children_in_law_other_kin_neighborhood,
      H = household_children_in_law_other_kin_neighborhood,
      I = household_children_in_law_other_kin_neighborhood,
      J = household_children_in_law_other_kin_neighborhood,
      K = household_children_in_law_other_kin_neighborhood
    ),
    domtyp = list(
      `2B` = housekeeper_in_household_acquaintance_in_household,
      `3B` = housekeeper_in_household_acquaintance_in_household,
      B = housekeeper_in_household_acquaintance_in_household,
      C = housekeeper_in_household_acquaintance_in_household,
      D = housekeeper_in_household_acquaintance_in_household,
      E = housekeeper_in_household_acquaintance_in_household,
      F = housekeeper_in_household_acquaintance_in_household,
      G = housekeeper_in_household_acquaintance_in_household,
      H = housekeeper_in_household_acquaintance_in_household,
      I = housekeeper_in_household_acquaintance_in_household,
      J = housekeeper_in_household_acquaintance_in_household,
      K = housekeeper_in_household_acquaintance_in_household
    ),
    emo_giv = list(
      `2B` = never_seldom_sometimes_often,
      `3B` = never_seldom_sometimes_often,
      B = never_seldom_sometimes_often,
      C = never_seldom_sometimes_often,
      D = never_seldom_sometimes_often,
      E = never_seldom_sometimes_often,
      F = never_seldom_sometimes_often,
      G = never_seldom_sometimes_often,
      H = never_seldom_sometimes_often,
      I = never_seldom_sometimes_often,
      J = never_seldom_sometimes_often,
      K = never_seldom_sometimes_often
    ),
    emo_rec = list(
      `2B` = never_seldom_sometimes_often,
      `3B` = never_seldom_sometimes_often,
      B = never_seldom_sometimes_often,
      C = never_seldom_sometimes_often,
      D = never_seldom_sometimes_often,
      E = never_seldom_sometimes_often,
      F = never_seldom_sometimes_often,
      G = never_seldom_sometimes_often,
      H = never_seldom_sometimes_often,
      I = never_seldom_sometimes_often,
      J = never_seldom_sometimes_often,
      K = never_seldom_sometimes_often
    ),
    freqran = list(
      `2B` = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      `3B` = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      B = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      C = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      D = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      E = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      F = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      G = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      H = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      I = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      J = na_see_247_rcf_sys_addition_deleted_by_interviewer,
      K = na_see_247_rcf_sys_addition_deleted_by_interviewer
    ),
    ins_giv = list(
      `2B` = never_seldom_sometimes_often,
      `3B` = never_seldom_sometimes_often,
      B = never_seldom_sometimes_often,
      C = never_seldom_sometimes_often,
      D = never_seldom_sometimes_often,
      E = never_seldom_sometimes_often,
      F = never_seldom_sometimes_often,
      G = never_seldom_sometimes_often,
      H = never_seldom_sometimes_often,
      I = never_seldom_sometimes_often,
      J = never_seldom_sometimes_often,
      K = never_seldom_sometimes_often
    ),
    ins_rec = list(
      `2B` = never_seldom_sometimes_often,
      `3B` = never_seldom_sometimes_often,
      B = never_seldom_sometimes_often,
      C = never_seldom_sometimes_often,
      D = never_seldom_sometimes_often,
      E = never_seldom_sometimes_often,
      F = never_seldom_sometimes_often,
      G = never_seldom_sometimes_often,
      H = never_seldom_sometimes_often,
      I = never_seldom_sometimes_often,
      J = never_seldom_sometimes_often,
      K = never_seldom_sometimes_often
    ),
    nwconf = list(
      `2B` = not_the_a_confidant_1st_confidant_2nd_confidant,
      `3B` = not_the_a_confidant_1st_confidant_2nd_confidant,
      C = not_the_a_confidant_1st_confidant_2nd_confidant,
      D = not_the_a_confidant_1st_confidant_2nd_confidant,
      E = not_the_a_confidant_1st_confidant_2nd_confidant,
      F = not_the_a_confidant_1st_confidant_2nd_confidant,
      G = not_the_a_confidant_1st_confidant_2nd_confidant,
      H = not_the_a_confidant_1st_confidant_2nd_confidant,
      I = not_the_a_confidant_1st_confidant_2nd_confidant,
      J = not_the_a_confidant_1st_confidant_2nd_confidant,
      K = not_the_a_confidant_1st_confidant_2nd_confidant
    ),
    nwfreq = list(
      `2B` = never_yearly_or_less_often_few_times_year_monthly,
      `3B` = never_yearly_or_less_often_few_times_year_monthly,
      B = never_yearly_or_less_often_few_times_year_monthly,
      C = never_yearly_or_less_often_few_times_year_monthly,
      D = never_yearly_or_less_often_few_times_year_monthly,
      E = never_yearly_or_less_often_few_times_year_monthly,
      F = never_yearly_or_less_often_few_times_year_monthly,
      G = never_yearly_or_less_often_few_times_year_monthly,
      H = never_yearly_or_less_often_few_times_year_monthly,
      I = never_yearly_or_less_often_few_times_year_monthly,
      J = never_yearly_or_less_often_few_times_year_monthly,
      K = never_yearly_or_less_often_few_times_year_monthly
    ),
    nwinhh = list(
      `2B` = not_sharing_sharing_household,
      `3B` = not_sharing_sharing_household,
      B = not_sharing_sharing_household,
      C = not_sharing_sharing_household,
      D = not_sharing_sharing_household,
      E = not_sharing_sharing_household,
      F = not_sharing_sharing_household,
      G = not_sharing_sharing_household,
      H = not_sharing_sharing_household,
      I = not_sharing_sharing_household,
      J = not_sharing_sharing_household,
      K = not_sharing_sharing_household
    ),
    nwsex = list(
      `2B` = male_female,
      `3B` = male_female,
      B = male_female,
      C = male_female,
      D = male_female,
      E = male_female,
      F = male_female,
      G = male_female,
      H = male_female,
      I = male_female,
      J = male_female,
      K = male_female
    ),
    nwtrav = list(
      `2B` = no_time_1_hour_24_hours,
      `3B` = no_time_1_hour_24_hours,
      B = no_time_1_hour_24_hours,
      C = no_time_1_hour_24_hours,
      D = no_time_1_hour_24_hours,
      E = no_time_1_hour_24_hours,
      F = no_time_1_hour_24_hours,
      G = no_time_1_hour_24_hours,
      H = no_time_1_hour_24_hours,
      I = no_time_1_hour_24_hours,
      J = no_time_1_hour_24_hours,
      K = no_time_1_hour_24_hours
    ),
    nwtype = list(
      `2B` = spouse_or_partner_biological_son_or_daughter,
      `3B` = spouse_or_partner_biological_son_or_daughter,
      B = spouse_or_partner_biological_son_or_daughter,
      C = spouse_or_partner_biological_son_or_daughter,
      D = spouse_or_partner_biological_son_or_daughter,
      E = spouse_or_partner_biological_son_or_daughter,
      F = spouse_or_partner_biological_son_or_daughter,
      G = spouse_or_partner_biological_son_or_daughter,
      H = spouse_or_partner_biological_son_or_daughter,
      I = spouse_or_partner_biological_son_or_daughter,
      J = spouse_or_partner_biological_son_or_daughter,
      K = spouse_or_partner_biological_son_or_daughter
    ),
    random = list(
      `2B` = na_see_247_rcf_sys_addition_missing,
      B = na_see_247_rcf_sys_addition_missing,
      C = na_see_247_rcf_sys_addition_missing,
      D = na_see_247_rcf_sys_addition_missing,
      E = na_see_247_rcf_sys_addition_missing,
      F = na_see_247_rcf_sys_addition_missing,
      G = na_see_247_rcf_sys_addition_missing
    ),
    sequenc = list(
      `2B` = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      `3B` = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      B = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      C = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      D = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      E = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      F = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      G = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      H = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      I = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      J = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir,
      K = er_ir_eg_ig_er_ir_ig_eg_er_eg_ir_ig_er_eg_ig_ir
    ),
    nwmsupp = list(
      B = c(
        `-8` = "no answer",
        `-7` = "NA:rank>10",
        `-6` = "NA:see 247",
        `-4` = "NA:only 1 network member",
        `-3` = "RCF/SYS addition",
        `-2` = "as -1,partner not listed",
        `-1` = "nobody/refusal/all",
        `0` = "<>partner,<>most supportive, no partner in network",
        `1` = "<>partner,<>most supportive, partner in network",
        `2` = ">partner,<>most supportive, partner not on list in Q",
        `3` = "partner, but not most supportive",
        `4` = "most supportive=partner",
        `5` = "most supportive, no partner in network",
        `6` = "most supportive<>partner, partner on list in Q",
        `7` = "most supportive<>partner, partner not on list in Q"
      )
    ),
    nwpart = list(
      B = c(
        `-7` = "NA:rank>10/12",
        `-6` = "NA:see 247",
        `-4` = "NA:miss techn",
        `-3` = "RCF/SYS addition",
        `-1` = "no answer",
        `1` = "w/partner",
        `5` = "no partner"
      )
    )
  ),

  value_labels_harmonized = list(
    domain = c(
      `1` = "household",
      `2` = "children/-in-law",
      `3` = "other kin",
      `4` = "neighborhood",
      `5` = "work/school",
      `6` = "organizations",
      `7` = "other non-kin",
      `8` = "forgotten",
      `9` = "rcf/sys addition"
    ),
    domtyp = c(
      `1` = "housekeeper (in household)",
      `2` = "acquaintance (in household)",
      `3` = "catholic sister (in household)",
      `4` = "parent (in household)",
      `5` = "parent inlaw (in household)",
      `6` = "niece/nephew (in household)",
      `7` = "son/daughter-in-law (in household)",
      `8` = "brother/sister-in-law (in household)",
      `9` = "former partner (in household)",
      `10` = "boarder/landlord (in household)",
      `11` = "partner/spouse (in household)",
      `12` = "biological son/daughter (in household)",
      `13` = "brother/sister (in household)",
      `14` = "grandson/daughter (in household)",
      `15` = "friend (in household)",
      `16` = "other, not specified (in household)",
      `17` = "other nonkin, not specified (in household)",
      `18` = "other kin, not specified (in household)",
      `19` = "son/daughter of partner, step, adoptive, foster (in household)",
      `21` = "biological son/daughter",
      `22` = "son/daughter-in-law",
      `23` = "son/daughter of partner, step, adoptive, foster (specification in xnwtype)",
      `24` = "former son/daughter-in-law, other specific cases",
      `25` = "stepchild",
      `26` = "adoptive child",
      `27` = "foster child",
      `31` = "parent",
      `32` = "brother/sister (including half or step)",
      `33` = "brother/sister-in-law",
      `34` = "grandson/daughter",
      `35` = "cousin/niece/nephew",
      `36` = "uncle/aunt",
      `37` = "other family; specification unknown",
      `38` = "father/mother-in-law",
      `39` = "partner/spouse of grandchild",
      `40` = "neighbor",
      `41` = "former neighbor",
      `42` = "living in neighborhood",
      `51` = "(former) colleague or his/her spouse",
      `52` = "known through volunteer work",
      `53` = "known through school, course, education",
      `60` = "known through voluntary organization (e.g. church, sports, political)",
      `70` = "other nonkin; specification unknown",
      `71` = "friend",
      `72` = "acquaintance",
      `73` = "(former) colleague or his/her spouse ->51",
      `74` = "known through voluntary organization (e.g. church, sports, political) ->60",
      `75` = "known through contact at street",
      `76` = "professional helper",
      `77` = "professional, e.g. pastor, reverend, general practitioner",
      `78` = "other kin or nonkin; specification unknown",
      `79` = "professional helper (frequent contact)",
      `80` = "partner/spouse outside household",
      `81` = "former spouse/partner",
      `82` = "parent of child-in-law",
      `83` = "former parent-in-law",
      `84` = "landlord",
      `85` = "catholic sister",
      `86` = "other kin or nonkin; specification unknown"
    ),
    emo_giv = never_seldom_sometimes_often_2,
    emo_rec = never_seldom_sometimes_often_2,
    freqran = c(`-6` = "not available, routing", `-3` = "rcf/sys addition", `-1` = "deleted by interviewer"),
    ins_giv = never_seldom_sometimes_often_2,
    ins_rec = never_seldom_sometimes_often_2,
    nwconf = c(
      `-6` = "identified persons is your confidant?/welke van alle hiervoor genoemde personen beschouwt u als uw vertrouwenspersoon?) see 247",
      `-3` = "rcf/sys addition",
      `0` = "not the/a confidant",
      `1` = "(1st) confidant",
      `2` = "2nd confidant",
      `3` = "3rd confidant",
      `4` = "4th confidant",
      `5` = "5th confidant",
      `6` = "6th confidant",
      `7` = "7th confidant",
      `8` = "8th confidant",
      `9` = "9th/last confidant"
    ),
    nwfreq = c(
      `-6` = "often are you in touch with ...?\"/\"hoe vaak heeft u contact met not available, routing",
      `-3` = "rcf/sys addition",
      `-1` = "no answer",
      `1` = "never",
      `2` = "...\") yearly or less often",
      `3` = "few times year",
      `4` = "monthly",
      `5` = "once every 2 weeks",
      `6` = "weekly",
      `7` = "few times week",
      `8` = "daily or household member"
    ),
    nwinhh = not_sharing_sharing_household,
    nwmsupp = c(
      `-8` = "no answer",
      `-7` = "not available,rank>10",
      `-6` = "not available, routing",
      `-4` = "not available,only 1 network member",
      `-3` = "rcf/sys addition",
      `-2` = "as -1,partner not listed",
      `-1` = "nobody/refusal/all",
      `0` = "<>partner,<>most supportive, no partner in network",
      `1` = "<>partner,<>most supportive, partner in network",
      `2` = ">partner,<>most supportive, partner not on list in q",
      `3` = "partner, but not most supportive",
      `4` = "most supportive=partner",
      `5` = "most supportive, no partner in network",
      `6` = "most supportive<>partner, partner on list in q",
      `7` = "most supportive<>partner, partner not on list in q"
    ),
    nwpart = c(
      `-7` = "not available,rank>10/12",
      `-6` = "not available, routing",
      `-4` = "not available,miss techn",
      `-3` = "rcf/sys addition",
      `-1` = "no answer",
      `1` = "w/partner",
      `5` = "no partner"
    ),
    nwsex = male_female,
    nwtrav = c(
      `-7` = "not available,rank>10/12",
      `-6` = "not available, routing",
      `-4` = "not available,miss techn",
      `-3` = "rcf/sys addition",
      `-1` = "no answer",
      `0` = "no time",
      `60` = "1 hour",
      `1440` = ">24 hours"
    ),
    nwtype = spouse_or_partner_biological_son_or_daughter,
    random = c(
      `-6` = "not available, routing",
      `-3` = "rcf/sys addition",
      `-1` = "missing",
      `0` = NA_character_,
      `59` = NA_character_,
      `99` = NA_character_
    ),
    sequenc = c(
      `-7` = "not available,rank>10/12",
      `-6` = "not available, routing",
      `-3` = "rcf/sys addition",
      `-1` = "only missings",
      `1234` = "er ir eg ig",
      `1243` = "er ir ig eg",
      `1324` = "er eg ir ig",
      `1342` = "er eg ig ir",
      `1423` = "er ig ir eg",
      `1432` = "er ig eg ir",
      `2134` = "ir er eg ig",
      `2143` = "ir er ig eg",
      `2314` = "ir eg er ig",
      `2341` = "ir eg ig er",
      `2413` = "ir ig er eg",
      `2431` = "ir ig eg er",
      `3124` = "eg er ir ig",
      `3142` = "eg er ig ir",
      `3214` = "eg ir er ig",
      `3241` = "eg ir ig er",
      `3412` = "eg ig er ir",
      `3421` = "eg ig ir er",
      `4123` = "ig er ir eg",
      `4132` = "ig er eg ir",
      `4213` = "ig ir er eg",
      `4231` = "ig ir eg er",
      `4312` = "ig eg er ir",
      `4321` = "ig eg ir er"
    )
  )
)
