## LASA filecode 153 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_153 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bmalcage",
      "bmalcbeer",
      "bmalcd",
      "bmalcgin",
      "bmalclig",
      "bmalcliq",
      "bmalcmix",
      "bmalcnr",
      "bmalcnr6",
      "bmalcuse",
      "bmalcwine",
      "bmalcyn",
      "bmalcage",
      "bmalcbeer",
      "bmalcd",
      "bmalcgin",
      "bmalclig",
      "bmalcliq",
      "bmalcmix",
      "bmalcnr",
      "bmalcnr6",
      "bmalcuse",
      "bmalcw",
      "bmalcwine",
      "bmalcyn",
      "bmalcagestop",
      "bmalcbeer",
      "bmalcbefore",
      "bmalcd",
      "bmalcgin",
      "bmalclig",
      "bmalcliq",
      "bmalcmix",
      "bmalcnr",
      "bmalcnr6",
      "bmalctod",
      "bmalcwine",
      "bmalcyn",
      "cmalcnr",
      "cmalcnr6",
      "cmalcupy",
      "cmalcyn",
      "dmalcd",
      "dmalcnr",
      "dmalcnr6",
      "dmalcyn",
      "emalcd",
      "emalcnr",
      "emalcnr6",
      "emalcyn",
      "fmalcd",
      "fmalcnr",
      "fmalcnr6",
      "fmalcyn",
      "gmalcd",
      "gmalcnr",
      "gmalcnr6",
      "gmalcyn",
      "hmalcd",
      "hmalcnr",
      "hmalcnr6",
      "hmalcw",
      "hmalcyn",
      "imalcd",
      "imalcnr",
      "imalcnr6",
      "imalcw",
      "imalcyn",
      "jmalcd",
      "jmalcnr",
      "jmalcnr6",
      "jmalcw",
      "jmalcyn",
      "kmalcd",
      "kmalcnr",
      "kmalcnr6",
      "kmalcw",
      "kmalcyn",
      "bmalcd",
      "bmalcnr",
      "bmalcyn"
    ),
    canonical_name = c(
      "malcage",
      "malcbeer",
      "malcd",
      "malcgin",
      "malclig",
      "malcliq",
      "malcmix",
      "malcnr",
      "malcnr6",
      "malcuse",
      "malcwine",
      "malcyn",
      "malcage",
      "malcbeer",
      "malcd",
      "malcgin",
      "malclig",
      "malcliq",
      "malcmix",
      "malcnr",
      "malcnr6",
      "malcuse",
      "malcw",
      "malcwine",
      "malcyn",
      "malcagestop",
      "malcbeer",
      "malcbefore",
      "malcd",
      "malcgin",
      "malclig",
      "malcliq",
      "malcmix",
      "malcnr",
      "malcnr6",
      "malctod",
      "malcwine",
      "malcyn",
      "malcnr",
      "malcnr6",
      "malcupy",
      "malcyn",
      "malcd",
      "malcnr",
      "malcnr6",
      "malcyn",
      "malcd",
      "malcnr",
      "malcnr6",
      "malcyn",
      "malcd",
      "malcnr",
      "malcnr6",
      "malcyn",
      "malcd",
      "malcnr",
      "malcnr6",
      "malcyn",
      "malcd",
      "malcnr",
      "malcnr6",
      "malcw",
      "malcyn",
      "malcd",
      "malcnr",
      "malcnr6",
      "malcw",
      "malcyn",
      "malcd",
      "malcnr",
      "malcnr6",
      "malcw",
      "malcyn",
      "malcd",
      "malcnr",
      "malcnr6",
      "malcw",
      "malcyn",
      "malcd",
      "malcnr",
      "malcyn"
    ),
    variable_label = c(
      "Age stopped drinking",
      "Beer",
      "Days a week usage",
      "Gin",
      "Light",
      "Liqueur",
      "Cocktail",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Use in past",
      "Wine",
      "Do you drink alcohol",
      "Age stopped drinking",
      "Beer",
      "Days a week usage",
      "Gin",
      "Light",
      "Liqueur",
      "Cocktail",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Use in past",
      "Alcohol: other people worried about alcohol use",
      "Wine",
      "Do you drink alcohol",
      "Age stopped",
      "Beer",
      "Drank before",
      "Number of days a week",
      "Gin",
      "Light",
      "Liqueur",
      "Cocktail",
      "Number of glasses at one time",
      "Number of times six glasses or more",
      "Which time of day",
      "Wine",
      "Do you drink alcohol",
      "number of glasses each time",
      "number of times R 6 glasses a day past half year",
      "Alcohol use for the past year",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Other people worried about alcohol use",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Other people worried about alcohol use",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Other people worried about alcohol use",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Other people worried about alcohol use",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Do you drink alcohol"
    ),
    harmonized_var_label = c(
      "Age stopped drinking",
      "Beer",
      "Number of days a week/month usage",
      "Gin",
      "Light",
      "Liqueur",
      "Cocktail",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Use in past",
      "Wine",
      "Do you drink alcohol",
      "Age stopped drinking",
      "Beer",
      "Number of days a week/month usage",
      "Gin",
      "Light",
      "Liqueur",
      "Cocktail",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Use in past",
      "Other people worried about alcohol use",
      "Wine",
      "Do you drink alcohol",
      "Age stopped",
      "Beer",
      "Drank before",
      "Number of days a week/month usage",
      "Gin",
      "Light",
      "Liqueur",
      "Cocktail",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Which time of day",
      "Wine",
      "Do you drink alcohol",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Alcohol use for the past year",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Other people worried about alcohol use",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Other people worried about alcohol use",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Other people worried about alcohol use",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Number of time six glasses or more",
      "Other people worried about alcohol use",
      "Do you drink alcohol",
      "Number of days a week/month usage",
      "Number of glasses at one time",
      "Do you drink alcohol"
    ),
    var_type = c(
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    malcage = list(
      `2B` = na_see_bmalcuse_no_answer_asked,
      `3B` = na_see_bmalcuse_no_answer_asked
    ),
    malcbeer = list(
      `2B` = no_yes_140,
      `3B` = no_yes_140,
      B = no_yes_50
    ),
    malcd = list(
      `2B` = every_day_5_6_days_a_week_3_4_days_a_week,
      `3B` = every_day_5_6_days_a_week_3_4_days_a_week,
      B = every_day_5_6_days_a_week_3_4_days_a_week_2,
      D = every_day_5_6_days_a_week_3_4_days_a_week,
      E = every_day_5_6_days_a_week_3_4_days_a_week,
      F = every_day_5_6_days_a_week_3_4_days_a_week,
      G = every_day_5_6_days_a_week_3_4_days_a_week,
      H = every_day_5_6_days_a_week_3_4_days_a_week,
      I = every_day_5_6_days_a_week_3_4_days_a_week,
      J = every_day_5_6_days_a_week_3_4_days_a_week,
      K = every_day_5_6_days_a_week_3_4_days_a_week,
      MB = every_day_5_6_days_a_week_3_4_days_a_week
    ),
    malcgin = list(
      `2B` = no_yes_23,
      `3B` = no_yes_23,
      B = no_yes_50
    ),
    malclig = list(
      `2B` = no_yes_23,
      `3B` = no_yes_23,
      B = no_yes_50
    ),
    malcliq = list(
      `2B` = no_yes_23,
      `3B` = no_yes_23,
      B = no_yes_50
    ),
    malcmix = list(
      `2B` = no_yes_23,
      `3B` = no_yes_23,
      B = no_yes_50
    ),
    malcnr = list(
      `2B` = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses,
      `3B` = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses,
      B = c(
        `-4` = "no valid data",
        `-3` = "R never drank",
        `-2` = "R drinks at present",
        `-1` = "no answer, asked",
        `1` = "11 glasses or more",
        `2` = "8-10 glasses",
        `3` = "6-7 glasses",
        `4` = "4-5 glasses",
        `5` = "2-3 glasses",
        `6` = "1 glass"
      ),
      C = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see CMALCYN",
        `-1` = "na, asked",
        `1` = "11 glasses or more",
        `2` = "8-10 glasses",
        `3` = "6-7 glasses",
        `4` = "4-5 glasses",
        `5` = "2-3 glasses",
        `6` = "1 glass"
      ),
      D = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses,
      E = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses,
      F = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses,
      G = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses,
      H = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses,
      I = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses,
      J = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses,
      K = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses,
      MB = vs_11_glasses_or_more_8_10_glasses_6_7_glasses_4_5_glasses
    ),
    malcnr6 = list(
      `2B` = every_day_5_6_days_a_week_3_4_days_a_week,
      `3B` = every_day_5_6_days_a_week_3_4_days_a_week,
      B = c(
        `-5` = "no valid data",
        `-4` = "R never drank",
        `-3` = "R drink/drank > 6 glasses",
        `-2` = "R drink/drank < 2 glasses",
        `-1` = "no answer, asked",
        `1` = "every day",
        `2` = "5-6 days a week",
        `3` = "3-4 days a week",
        `4` = "1-2 days a week",
        `5` = "1-3 days a month",
        `6` = "less than 1 day a month"
      ),
      C = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see CMACLNR",
        `-1` = "na, asked",
        `1` = "daily",
        `2` = "5-6 days a week",
        `3` = "3-4 days a week",
        `4` = "1-2 days a week",
        `5` = "1-3 days a month",
        `6` = "< 1 glass a month"
      ),
      D = every_day_5_6_days_a_week_3_4_days_a_week,
      E = every_day_5_6_days_a_week_3_4_days_a_week,
      F = every_day_5_6_days_a_week_3_4_days_a_week,
      G = every_day_5_6_days_a_week_3_4_days_a_week,
      H = every_day_5_6_days_a_week_3_4_days_a_week,
      I = every_day_5_6_days_a_week_3_4_days_a_week,
      J = every_day_5_6_days_a_week_3_4_days_a_week,
      K = every_day_5_6_days_a_week_3_4_days_a_week
    ),
    malcuse = list(
      `2B` = no_yes_140,
      `3B` = no_yes_140
    ),
    malcwine = list(
      `2B` = no_yes_23,
      `3B` = no_yes_23,
      B = no_yes_50
    ),
    malcyn = list(
      `2B` = no_yes_23,
      `3B` = no_yes_23,
      B = no_yes_341,
      C = no_yes_5,
      D = no_yes_23,
      E = no_yes_23,
      F = no_yes_23,
      G = no_yes_23,
      H = no_yes_23,
      I = no_yes_23,
      J = no_yes_23,
      K = no_yes_23,
      MB = no_yes_23
    ),
    malcw = list(
      `3B` = c(
        `-2` = "R does not drink 6 or more glasses at one time",
        `-1` = "no answer, asked",
        `1` = "no",
        `2` = "yes, but not in past year",
        `3` = "yes, in past year"
      ),
      H = no_yes_but_not_in_past_year_yes_in_past_year,
      I = no_yes_but_not_in_past_year_yes_in_past_year,
      J = no_yes_but_not_in_past_year_yes_in_past_year,
      K = no_yes_but_not_in_past_year_yes_in_past_year
    ),
    malcagestop = list(
      B = no_valid_data_r_never_drank_r_drinks_at_present
    ),
    malcbefore = list(
      B = no_yes_342
    ),
    malctod = list(
      B = morning_7_12_hour_afternoon_12_18_hour
    ),
    malcupy = list(
      C = daily_5_6_days_a_week_3_4_days_a_week_1_2_days_a_week
    )
  ),

  value_labels_harmonized = list(
    malcage = na_see_bmalcuse_no_answer_asked,
    malcagestop = no_valid_data_r_never_drank_r_drinks_at_present,
    malcbeer = c(
      `-4` = "no valid data",
      `-2` = "R does not drink / na, see BMALCYN",
      `-1` = "no answer, asked",
      `1` = "no",
      `2` = "yes"
    ),
    malcbefore = no_yes_342,
    malcd = every_day_5_6_days_a_week_3_4_days_a_week_2,
    malcgin = no_yes_50,
    malclig = no_yes_50,
    malcliq = no_yes_50,
    malcmix = no_yes_50,
    malcnr = c(
      `-4` = "no valid data",
      `-3` = "R never drank / na, wrong skip",
      `-2` = "R drinks at present / na, see CMALCYN / R does not drink",
      `-1` = "no answer, asked",
      `1` = "11 glasses or more",
      `2` = "8-10 glasses",
      `3` = "6-7 glasses",
      `4` = "4-5 glasses",
      `5` = "2-3 glasses",
      `6` = "1 glass"
    ),
    malcnr6 = c(
      `-5` = "no valid data",
      `-4` = "R never drank",
      `-3` = "R drink/drank > 6 glasses / na, wrong skip",
      `-2` = "R drink/drank < 2 glasses / na, see CMACLNR / R does not drink",
      `-1` = "no answer, asked",
      `1` = "every day / daily",
      `2` = "5-6 days a week",
      `3` = "3-4 days a week",
      `4` = "1-2 days a week",
      `5` = "1-3 days a month",
      `6` = "less than 1 day a month / < 1 glass a month"
    ),
    malctod = morning_7_12_hour_afternoon_12_18_hour,
    malcupy = daily_5_6_days_a_week_3_4_days_a_week_1_2_days_a_week,
    malcuse = no_yes_140,
    malcw = c(
      `-2` = "R does not drink / R does not drink 6 or more glasses at one time",
      `-1` = "no answer, asked",
      `1` = "no",
      `2` = "yes, but not in past year",
      `3` = "yes, in past year"
    ),
    malcwine = no_yes_50,
    malcyn = c(
      `-5` = "na, interview terminated",
      `-4` = "no valid data",
      `-2` = "no answer, skipped",
      `-1` = "no answer, asked",
      `1` = "no",
      `2` = "yes"
    )
  )
)
