## LASA filecode 117 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_117 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bqsleep1",
      "bqsleep2",
      "bqsleep3",
      "bqsleep4",
      "bqsleep1",
      "bqsleep2",
      "bqsleep3",
      "bqsleep4",
      "bqsleep5",
      "bqsleeph",
      "bqsleepm",
      "bqsleep1",
      "bqsleep2",
      "bqsleep3",
      "bqsleep4",
      "cqsleep1",
      "cqsleep2",
      "cqsleep3",
      "cqsleep4",
      "dqsleep1",
      "dqsleep2",
      "dqsleep3",
      "dqsleep4",
      "eqsleep1",
      "eqsleep2",
      "eqsleep3",
      "eqsleep4",
      "fqsleep1",
      "fqsleep2",
      "fqsleep3",
      "fqsleep4",
      "gqsleep1",
      "gqsleep2",
      "gqsleep3",
      "gqsleep4",
      "gqsleep5",
      "gqsleeph",
      "gqsleepm",
      "hqsleep1",
      "hqsleep2",
      "hqsleep3",
      "hqsleep4",
      "hqsleep5",
      "hqsleeph",
      "hqsleepm",
      "iqsleep1",
      "iqsleep2",
      "iqsleep3",
      "iqsleep4",
      "iqsleep5",
      "iqsleeph",
      "iqsleepm",
      "jqsleep1",
      "jqsleep2",
      "jqsleep3",
      "jqsleep4",
      "jqsleep5",
      "jqsleeph",
      "jqsleepm",
      "kqsleep1",
      "kqsleep2",
      "kqsleep3",
      "kqsleep4",
      "kqsleep5",
      "kqsleeph",
      "kqsleepm"
    ),
    canonical_name = c(
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep5",
      "qsleeph",
      "qsleepm",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep5",
      "qsleeph",
      "qsleepm",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep5",
      "qsleeph",
      "qsleepm",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep5",
      "qsleeph",
      "qsleepm",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep5",
      "qsleeph",
      "qsleepm",
      "qsleep1",
      "qsleep2",
      "qsleep3",
      "qsleep4",
      "qsleep5",
      "qsleeph",
      "qsleepm"
    ),
    variable_label = c(
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake to early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake to early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake to early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake to early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake to early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake to early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute"
    ),
    harmonized_var_label = c(
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute",
      "Sleep 1: hours sleep in 24 hours",
      "Sleep 2: falling a sleep",
      "Sleep 3: continue sleeping",
      "Sleep 4: awake too early",
      "Sleep 5: sleep quality past month",
      "going to sleep: hour of the day",
      "going to sleep: minute"
    ),
    var_type = c(
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qsleep1 = list(
      `2B` = no_answer,
      `3B` = no_answer,
      B = no_answer,
      C = no_answer,
      D = no_answer,
      E = no_answer,
      F = no_answer,
      G = no_answer,
      H = no_answer,
      I = no_answer,
      J = no_answer,
      K = no_answer
    ),
    qsleep2 = list(
      `2B` = almost_never_some_of_the_time_often_most_of_the_time,
      `3B` = almost_never_some_of_the_time_often_most_of_the_time,
      B = almost_never_some_of_the_time_often_most_of_the_time,
      C = almost_never_some_of_the_time_often_most_of_the_time,
      D = almost_never_some_of_the_time_often_most_of_the_time,
      E = almost_never_some_of_the_time_often_most_of_the_time,
      F = almost_never_some_of_the_time_often_most_of_the_time,
      G = almost_never_some_of_the_time_often_most_of_the_time,
      H = almost_never_some_of_the_time_often_most_of_the_time,
      I = almost_never_some_of_the_time_often_most_of_the_time,
      J = almost_never_some_of_the_time_often_most_of_the_time,
      K = almost_never_some_of_the_time_often_most_of_the_time
    ),
    qsleep3 = list(
      `2B` = almost_never_some_of_the_time_often_most_of_the_time,
      `3B` = almost_never_some_of_the_time_often_most_of_the_time,
      B = almost_never_some_of_the_time_often_most_of_the_time,
      C = almost_never_some_of_the_time_often_most_of_the_time,
      D = almost_never_some_of_the_time_often_most_of_the_time,
      E = almost_never_some_of_the_time_often_most_of_the_time,
      F = almost_never_some_of_the_time_often_most_of_the_time,
      G = almost_never_some_of_the_time_often_most_of_the_time,
      H = almost_never_some_of_the_time_often_most_of_the_time,
      I = almost_never_some_of_the_time_often_most_of_the_time,
      J = almost_never_some_of_the_time_often_most_of_the_time,
      K = almost_never_some_of_the_time_often_most_of_the_time
    ),
    qsleep4 = list(
      `2B` = almost_never_some_of_the_time_often_most_of_the_time,
      `3B` = almost_never_some_of_the_time_often_most_of_the_time,
      B = almost_never_some_of_the_time_often_most_of_the_time,
      C = almost_never_some_of_the_time_often_most_of_the_time,
      D = almost_never_some_of_the_time_often_most_of_the_time,
      E = almost_never_some_of_the_time_often_most_of_the_time,
      F = almost_never_some_of_the_time_often_most_of_the_time,
      G = almost_never_some_of_the_time_often_most_of_the_time,
      H = almost_never_some_of_the_time_often_most_of_the_time,
      I = almost_never_some_of_the_time_often_most_of_the_time,
      J = almost_never_some_of_the_time_often_most_of_the_time,
      K = almost_never_some_of_the_time_often_most_of_the_time
    ),
    qsleep5 = list(
      `3B` = very_good_somewhat_good_somewhat_bad_very_bad,
      G = very_good_somewhat_good_somewhat_bad_very_bad,
      H = very_good_somewhat_good_somewhat_bad_very_bad,
      I = very_good_somewhat_good_somewhat_bad_very_bad,
      J = very_good_somewhat_good_somewhat_bad_very_bad,
      K = very_good_somewhat_good_somewhat_bad_very_bad
    ),
    qsleeph = list(
      `3B` = no_answer,
      H = no_answer,
      I = no_answer,
      J = no_answer,
      K = no_answer
    ),
    qsleepm = list(
      `3B` = no_answer,
      H = no_answer,
      I = no_answer,
      J = no_answer
    )
  ),

  value_labels_harmonized = list(
    qsleep1 = not_available,
    qsleep2 = almost_never_some_of_the_time_often_most_of_the_time_2,
    qsleep3 = almost_never_some_of_the_time_often_most_of_the_time_2,
    qsleep4 = almost_never_some_of_the_time_often_most_of_the_time_2,
    qsleep5 = c(
      `-1` = "not available",
      `1` = "very good",
      `2` = "somewhat good",
      `3` = "somewhat bad",
      `4` = "very bad"
    ),
    qsleeph = not_available,
    qsleepm = not_available
  )
)
