## LASA filecode 189 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_189 <- list(
  variables = data.frame(
    wave = c(
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "emadapt",
      "emappli",
      "emdistr",
      "emdistrh",
      "emdomeca",
      "emdomech",
      "emeldedn",
      "emelderh",
      "emelderl",
      "emhomeca",
      "emmeal",
      "emmealn",
      "emnurdep",
      "emnursdn",
      "emnursh",
      "emnursin",
      "empersca",
      "empersch",
      "emriooth",
      "emrioyn",
      "emurgyn",
      "fmadapt",
      "fmappli",
      "fmdistr",
      "fmdistrh",
      "fmdomeca",
      "fmdomech",
      "fmedntyp",
      "fmeldedn",
      "fmelderl",
      "fmidn",
      "fmioag",
      "fmioagh",
      "fmiose",
      "fmioseh",
      "fmiosg",
      "fmiosgh",
      "fmiotr",
      "fmiotrh",
      "fmistay",
      "fmitypc",
      "fmmeal",
      "fmmealn",
      "fmndndep",
      "fmndntyp",
      "fmnurdep",
      "fmnursdn",
      "fmnursin",
      "fmpersca",
      "fmpersch",
      "fmpgbadm",
      "fmpgbca",
      "fmpgbcat",
      "fmpgbf",
      "fmpgbfa",
      "fmpgbfat",
      "fmpgbft",
      "fmpgbhc",
      "fmpgbhct",
      "fmpgbhf",
      "fmpgbhft",
      "fmpgbn",
      "fmpgbnt",
      "fmpgbo",
      "fmpgbot",
      "fmpgbp",
      "fmpgbpc",
      "fmpgbpct",
      "fmpgbpt",
      "fmriooth",
      "fmrioyn",
      "fmurgyn",
      "gmdistr",
      "gmdistrh",
      "gmdtreat",
      "gmitypc",
      "gmlstay",
      "gmntreat",
      "gmother",
      "gmotherh",
      "gmpersca",
      "gmpersch",
      "gmpgbadm",
      "gmpgbchc",
      "gmpgbchg",
      "gmpgbchh",
      "gmpgbdev",
      "gmpgbfrc",
      "gmpgbfrg",
      "gmpgbfrh",
      "gmpgbhcc",
      "gmpgbhcg",
      "gmpgbhch",
      "gmpgbhmc",
      "gmpgbhmg",
      "gmpgbhmh",
      "gmpgbnbc",
      "gmpgbnbg",
      "gmpgbnbh",
      "gmpgbotc",
      "gmpgbotg",
      "gmpgboth",
      "gmpgbpc",
      "gmpgbpg",
      "gmpgbph",
      "gmpgbphc",
      "gmpgbphg",
      "gmpgbphh",
      "gmpgbrcc",
      "gmpgbrcg",
      "gmpgbrch",
      "gmpgbrlc",
      "gmpgbrlg",
      "gmpgbrlh",
      "gmrioyn",
      "gmshstay",
      "gmurgyn",
      "hmcizna",
      "hmcizrd",
      "hmcizyn",
      "hmdistr",
      "hmdistrh",
      "hmdtreat",
      "hmitypc",
      "hmlstay",
      "hmntreat",
      "hmother",
      "hmotherh",
      "hmpersca",
      "hmpersch",
      "hmpgbac",
      "hmpgbao",
      "hmpgbap",
      "hmpgbaph",
      "hmpgbas",
      "hmpgbchc",
      "hmpgbchg",
      "hmpgbchh",
      "hmpgbdev",
      "hmpgbfrc",
      "hmpgbfrg",
      "hmpgbfrh",
      "hmpgbhcc",
      "hmpgbhcg",
      "hmpgbhch",
      "hmpgbhmc",
      "hmpgbhmg",
      "hmpgbhmh",
      "hmpgbnbc",
      "hmpgbnbg",
      "hmpgbnbh",
      "hmpgbotc",
      "hmpgbotg",
      "hmpgboth",
      "hmpgbpc",
      "hmpgbpg",
      "hmpgbph",
      "hmpgbphc",
      "hmpgbphg",
      "hmpgbphh",
      "hmpgbrcc",
      "hmpgbrcg",
      "hmpgbrch",
      "hmpgbrlc",
      "hmpgbrlg",
      "hmpgbrlh",
      "hmshstay",
      "hmurgyn",
      "imi24ca",
      "imi24cg",
      "imi24cm",
      "imi24crd",
      "imidaca",
      "imidacg",
      "imidacm",
      "imidacrd",
      "imiguia",
      "imiguig",
      "imiguim",
      "imiguird",
      "imihada",
      "imihadg",
      "imihadrd",
      "imihhaa",
      "imihhag",
      "imihham",
      "imihhard",
      "imindnat",
      "imindpgb",
      "imintca",
      "imintcg",
      "imintcm",
      "imintcrd",
      "iminura",
      "iminurg",
      "iminurm",
      "iminurrd",
      "imiotha",
      "imiothg",
      "imiothm",
      "imiothrd",
      "imipca",
      "imipcg",
      "imipcm",
      "imipcrd",
      "imissca",
      "imisscg",
      "imisscm",
      "imisscrd",
      "imitraa",
      "imitrag",
      "imitrard",
      "impgbac",
      "impgbao",
      "impgbap",
      "impgbaph",
      "impgbas",
      "imppgbdn",
      "imppgbfo",
      "imppgbnf",
      "imppgbot",
      "imppgbpa",
      "imppgbpc",
      "imppgbph",
      "imppgbrc",
      "imppgbro",
      "imppgbvo",
      "jmi24ca",
      "jmi24cg",
      "jmi24ch",
      "jmi24cm",
      "jmi24crd",
      "jmi24crw",
      "jmidaca",
      "jmidacg",
      "jmidach",
      "jmidacm",
      "jmidacrd",
      "jmidacrw",
      "jmiguia",
      "jmiguig",
      "jmiguih",
      "jmiguim",
      "jmiguird",
      "jmiguirw",
      "jmihada",
      "jmihadg",
      "jmihadrd",
      "jmihadrw",
      "jmihhaa",
      "jmihhag",
      "jmihhah",
      "jmihham",
      "jmihhard",
      "jmihharw",
      "jmindtype",
      "jmintca",
      "jmintcg",
      "jmintch",
      "jmintcm",
      "jmintcrd",
      "jmintcrw",
      "jminura",
      "jminurg",
      "jminurh",
      "jminurm",
      "jminurrd",
      "jminurrw",
      "jmiotha",
      "jmiothg",
      "jmiothh",
      "jmiothm",
      "jmiothrd",
      "jmiothrw",
      "jmipca",
      "jmipcg",
      "jmipch",
      "jmipcm",
      "jmipcrd",
      "jmipcrw",
      "jmissca",
      "jmisscd",
      "jmisscg",
      "jmisscrd",
      "jmisscrw",
      "jmitraa",
      "jmitrag",
      "jmitrard",
      "jmitrarw",
      "jmpgbac",
      "jmpgbao",
      "jmpgbap",
      "jmpgbaph",
      "jmpgbas",
      "jmppgbdn",
      "jmppgbfo",
      "jmppgbnf",
      "jmppgbot",
      "jmppgbpa",
      "jmppgbpc",
      "jmppgbph",
      "jmppgbrc",
      "jmppgbro",
      "jmppgbvo",
      "kmi24ca",
      "kmi24cg",
      "kmi24crd",
      "kmi24crw",
      "kmidaca",
      "kmidacg",
      "kmidach",
      "kmidacm",
      "kmidacrd",
      "kmidacrw",
      "kmiguia",
      "kmiguig",
      "kmiguih",
      "kmiguim",
      "kmiguird",
      "kmiguirw",
      "kmihada",
      "kmihadg",
      "kmihadrd",
      "kmihadrw",
      "kmihhaa",
      "kmihhag",
      "kmihhah",
      "kmihham",
      "kmihhard",
      "kmihharw",
      "kmindtype",
      "kmintca",
      "kmintcc",
      "kmintcg",
      "kmintcn",
      "kmintcrd",
      "kmintcrw",
      "kminura",
      "kminurg",
      "kminurh",
      "kminurm",
      "kminurrd",
      "kminurrw",
      "kmiotha",
      "kmiothg",
      "kmiothrd",
      "kmiothrw",
      "kmipca",
      "kmipcg",
      "kmipch",
      "kmipcm",
      "kmipcrd",
      "kmipcrw",
      "kmissca",
      "kmisscg",
      "kmisscrd",
      "kmisscrw",
      "kmisshd",
      "kmissn",
      "kmitraa",
      "kmitrag",
      "kmitrard",
      "kmitrarw",
      "kmpgbac",
      "kmpgbao",
      "kmpgbap",
      "kmpgbaph",
      "kmpgbas",
      "kmppgbdn",
      "kmppgbfo",
      "kmppgbnf",
      "kmppgbot",
      "kmppgbpa",
      "kmppgbpc",
      "kmppgbph",
      "kmppgbrc",
      "kmppgbro",
      "kmppgbvo"
    ),
    canonical_name = c(
      "madapt",
      "mappli",
      "mdistr",
      "mdistrh",
      "mdomeca",
      "mdomech",
      "meldedn",
      "melderh",
      "melderl",
      "mhomeca",
      "mmeal",
      "mmealn",
      "mnurdep",
      "mnursdn",
      "mnursh",
      "mnursin",
      "mpersca",
      "mpersch",
      "mriooth",
      "mrioyn",
      "murgyn",
      "madapt",
      "mappli",
      "mdistr",
      "mdistrh",
      "mdomeca",
      "mdomech",
      "medntyp",
      "meldedn",
      "melderl",
      "midn",
      "mioag",
      "mioagh",
      "miose",
      "mioseh",
      "miosg",
      "miosgh",
      "miotr",
      "miotrh",
      "mistay",
      "mitypc",
      "mmeal",
      "mmealn",
      "mndndep",
      "mndntyp",
      "mnurdep",
      "mnursdn",
      "mnursin",
      "mpersca",
      "mpersch",
      "mpgbadm",
      "mpgbca",
      "mpgbcat",
      "mpgbf",
      "mpgbfa",
      "mpgbfat",
      "mpgbft",
      "mpgbhc",
      "mpgbhct",
      "mpgbhf",
      "mpgbhft",
      "mpgbn",
      "mpgbnt",
      "mpgbo",
      "mpgbot",
      "mpgbp",
      "mpgbpc",
      "mpgbpct",
      "mpgbpt",
      "mriooth",
      "mrioyn",
      "murgyn",
      "mdistr",
      "mdistrh",
      "mdtreat",
      "mitypc",
      "mlstay",
      "mntreat",
      "mother",
      "motherh",
      "mpersca",
      "mpersch",
      "mpgbadm",
      "mpgbchc",
      "mpgbchg",
      "mpgbchh",
      "mpgbdev",
      "mpgbfrc",
      "mpgbfrg",
      "mpgbfrh",
      "mpgbhcc",
      "mpgbhcg",
      "mpgbhch",
      "mpgbhmc",
      "mpgbhmg",
      "mpgbhmh",
      "mpgbnbc",
      "mpgbnbg",
      "mpgbnbh",
      "mpgbotc",
      "mpgbotg",
      "mpgboth",
      "mpgbpc",
      "mpgbpg",
      "mpgbph",
      "mpgbphc",
      "mpgbphg",
      "mpgbphh",
      "mpgbrcc",
      "mpgbrcg",
      "mpgbrch",
      "mpgbrlc",
      "mpgbrlg",
      "mpgbrlh",
      "mrioyn",
      "mshstay",
      "murgyn",
      "mcizna",
      "mcizrd",
      "mcizyn",
      "mdistr",
      "mdistrh",
      "mdtreat",
      "mitypc",
      "mlstay",
      "mntreat",
      "mother",
      "motherh",
      "mpersca",
      "mpersch",
      "mpgbac",
      "mpgbao",
      "mpgbap",
      "mpgbaph",
      "mpgbas",
      "mpgbchc",
      "mpgbchg",
      "mpgbchh",
      "mpgbdev",
      "mpgbfrc",
      "mpgbfrg",
      "mpgbfrh",
      "mpgbhcc",
      "mpgbhcg",
      "mpgbhch",
      "mpgbhmc",
      "mpgbhmg",
      "mpgbhmh",
      "mpgbnbc",
      "mpgbnbg",
      "mpgbnbh",
      "mpgbotc",
      "mpgbotg",
      "mpgboth",
      "mpgbpc",
      "mpgbpg",
      "mpgbph",
      "mpgbphc",
      "mpgbphg",
      "mpgbphh",
      "mpgbrcc",
      "mpgbrcg",
      "mpgbrch",
      "mpgbrlc",
      "mpgbrlg",
      "mpgbrlh",
      "mshstay",
      "murgyn",
      "mi24ca",
      "mi24cg",
      "mi24cm",
      "mi24crd",
      "midaca",
      "midacg",
      "midacm",
      "midacrd",
      "miguia",
      "miguig",
      "miguim",
      "miguird",
      "mihada",
      "mihadg",
      "mihadrd",
      "mihhaa",
      "mihhag",
      "mihham",
      "mihhard",
      "mindnat",
      "mindpgb",
      "mintca",
      "mintcg",
      "mintcm",
      "mintcrd",
      "minura",
      "minurg",
      "minurm",
      "minurrd",
      "miotha",
      "miothg",
      "miothm",
      "miothrd",
      "mipca",
      "mipcg",
      "mipcm",
      "mipcrd",
      "missca",
      "misscg",
      "misscd",
      "misscrd",
      "mitraa",
      "mitrag",
      "mitrard",
      "mpgbac",
      "mpgbao",
      "mpgbap",
      "mpgbaph",
      "mpgbas",
      "mppgbdn",
      "mppgbfo",
      "mppgbnf",
      "mppgbot",
      "mppgbpa",
      "mppgbpc",
      "mppgbph",
      "mppgbrc",
      "mppgbro",
      "mppgbvo",
      "mi24ca",
      "mi24cg",
      "mi24ch",
      "mi24cm",
      "mi24crd",
      "mi24crw",
      "midaca",
      "midacg",
      "midach",
      "midacm",
      "midacrd",
      "midacrw",
      "miguia",
      "miguig",
      "miguih",
      "miguim",
      "miguird",
      "miguirw",
      "mihada",
      "mihadg",
      "mihadrd",
      "mihadrw",
      "mihhaa",
      "mihhag",
      "mihhah",
      "mihham",
      "mihhard",
      "mihharw",
      "mindtype",
      "mintca",
      "mintcg",
      "mintch",
      "mintcm",
      "mintcrd",
      "mintcrw",
      "minura",
      "minurg",
      "minurh",
      "minurm",
      "minurrd",
      "minurrw",
      "miotha",
      "miothg",
      "miothh",
      "miothm",
      "miothrd",
      "miothrw",
      "mipca",
      "mipcg",
      "mipch",
      "mipcm",
      "mipcrd",
      "mipcrw",
      "missca",
      "misscd",
      "misscg",
      "misscrd",
      "misscrw",
      "mitraa",
      "mitrag",
      "mitrard",
      "mitrarw",
      "mpgbac",
      "mpgbao",
      "mpgbap",
      "mpgbaph",
      "mpgbas",
      "mppgbdn",
      "mppgbfo",
      "mppgbnf",
      "mppgbot",
      "mppgbpa",
      "mppgbpc",
      "mppgbph",
      "mppgbrc",
      "mppgbro",
      "mppgbvo",
      "mi24ca",
      "mi24cg",
      "mi24crd",
      "mi24crw",
      "midaca",
      "midacg",
      "midach",
      "midacm",
      "midacrd",
      "midacrw",
      "miguia",
      "miguig",
      "miguih",
      "miguim",
      "miguird",
      "miguirw",
      "mihada",
      "mihadg",
      "mihadrd",
      "mihadrw",
      "mihhaa",
      "mihhag",
      "mihhah",
      "mihham",
      "mihhard",
      "mihharw",
      "mindtype",
      "mintca",
      "mintcc",
      "mintcg",
      "mintcn",
      "mintcrd",
      "mintcrw",
      "minura",
      "minurg",
      "minurh",
      "minurm",
      "minurrd",
      "minurrw",
      "miotha",
      "miothg",
      "miothrd",
      "miothrw",
      "mipca",
      "mipcg",
      "mipch",
      "mipcm",
      "mipcrd",
      "mipcrw",
      "missca",
      "misscg",
      "misscrd",
      "misscrw",
      "misshd",
      "missn",
      "mitraa",
      "mitrag",
      "mitrard",
      "mitrarw",
      "mpgbac",
      "mpgbao",
      "mpgbap",
      "mpgbaph",
      "mpgbas",
      "mppgbdn",
      "mppgbfo",
      "mppgbnf",
      "mppgbot",
      "mppgbpa",
      "mppgbpc",
      "mppgbph",
      "mppgbrc",
      "mppgbro",
      "mppgbvo"
    ),
    variable_label = c(
      "Indication for adaptations",
      "Indication for an appliance",
      "Indication for district nurse",
      "District nurse: # hours/week",
      "Home care: domestic tasks",
      "Domestic tasks: # hours/week",
      "Day/night treatment in home for the elderly",
      "Home for the elderly: # hours/week",
      "Stay in home for the elderly",
      "Indication for home care",
      "Indication for meals",
      "# meals per week",
      "Nursing home: department",
      "Day/night treatment in nursing home",
      "Nursing home: # hours/week",
      "Stay in nursing home",
      "Home care: personal care",
      "Personal care: # hours/week",
      "Other indication",
      "Indication (on medical grounds)",
      "Urgent indication",
      "Indication for adaptations",
      "Indication for an appliance",
      "Indication for nursing",
      "nursing: # hours/week",
      "Indication for domestic care",
      "Domestic care: # hours/week",
      "Type of day/night treatment in home for the elderly",
      "Day/night treatment in home for the elderly",
      "Stay in home for the elderly",
      "Indication for day/night treatment",
      "Other ind.: activating guidance",
      "Other ind.: activating guidance: # hours/week",
      "Other ind.: something else",
      "Other ind.: something else: # hours/week",
      "Other ind.: supporting guidance",
      "Other ind.: supporting guidance: # hours/week",
      "Other ind.: treatment",
      "Other ind.: treatment: # hours/week",
      "Indication for stay in (nursing) home",
      "Indication: type of care",
      "Indication for meals",
      "# meals per week",
      "Day/night treatment in nursing home: department",
      "Type of day/night treatment in nursing home",
      "Nursing home: department",
      "Day/night treatment in nursing home",
      "Stay in nursing home",
      "Indication for personal care",
      "Personal care: # hours/week",
      "PGB: administration",
      "PGB: care by children living away from home",
      "PGB: type of care by children living away from home",
      "PGB: care by friends",
      "PGB: care by family living away from home",
      "PGB: type of care by family living away from home",
      "PGB: type of care by friends",
      "PGB: care by personnel home care",
      "PGB: type of care by personnel home care",
      "PGB: care by household family/friend",
      "PGB: type of care by household family/friend",
      "PGB: care by neighbours",
      "PGB: type of care by neighbours",
      "PGB: care by others",
      "PGB: type of care by others",
      "PGB: care by partner",
      "PGB: care by private care",
      "PGB: type of care by private care",
      "PGB: type of care by partner",
      "Other indication",
      "Indication (on medical grounds)",
      "Urgent indication",
      "indication for nursing",
      "nursing: # hrs per week",
      "day treatment res care",
      "home care services or PGB",
      "long stay residential care",
      "night treatment res care",
      "other indication",
      "other care: # hrs per week",
      "indication personal care",
      "personal care: # hrs per week",
      "PGB: administration",
      "PGB: outside hh child personal care",
      "PGB: outside hh child guidance",
      "PGB: outside hh child household care",
      "PGB: devices or transport",
      "PGB: friend personal care",
      "PGB: friend guidance",
      "PGB: friend household care",
      "PGB: home care personal care",
      "PGB: home care guidance",
      "PGB: home care household care",
      "PGB: hh member personal care",
      "PGB: hh member guidance",
      "PGB: hh member household care",
      "PGB: neighbor personal care",
      "PGB: neighbor guidance",
      "PGB: neighbor household care",
      "PGB: other personal care",
      "PGB: other guidance",
      "PGB: other household care",
      "PGB: partner personal care",
      "PGB: partner guidance",
      "PGB: partner household care",
      "PGB: private help personal care",
      "PGB: private help guidance",
      "PGB: private help household care",
      "PGB: res care personal care",
      "PGB: res care guidance",
      "PGB: res care household care",
      "PGB: relative personal care",
      "PGB: relative guidance",
      "PGB: relative household care",
      "Applied for Indication",
      "short stay residential care",
      "urgent indication",
      "reason not applied for indication",
      "reason application declined",
      "Applied for Indication",
      "indication for nursing",
      "nursing: # hrs per week",
      "day treatment res care",
      "home care services or PGB",
      "long stay residential care",
      "night treatment res care",
      "other indication",
      "other care: # hrs per week",
      "indication personal care",
      "personal care: # hrs per week",
      "PGB administration: child(ren)",
      "PGB administration: other",
      "PGB administration: partner",
      "PGB administration: private help",
      "PGB administration: self",
      "PGB: outside hh child personal care",
      "PGB: outside hh child guidance",
      "PGB: outside hh child household care",
      "PGB: devices or transport",
      "PGB: friend personal care",
      "PGB: friend guidance",
      "PGB: friend household care",
      "PGB: home care personal care",
      "PGB: home care guidance",
      "PGB: home care household care",
      "PGB: hh member personal care",
      "PGB: hh member guidance",
      "PGB: hh member household care",
      "PGB: neighbor personal care",
      "PGB: neighbor guidance",
      "PGB: neighbor household care",
      "PGB: other personal care",
      "PGB: other guidance",
      "PGB: other household care",
      "PGB: partner personal care",
      "PGB: partner guidance",
      "PGB: partner household care",
      "PGB: private help personal care",
      "PGB: private help guidance",
      "PGB: private help household care",
      "PGB: res care personal care",
      "PGB: res care guidance",
      "PGB: res care household care",
      "PGB: relative personal care",
      "PGB: relative guidance",
      "PGB: relative household care",
      "short stay residential care",
      "urgent indication",
      "indication 24 hours care (at home or residential): applied",
      "indication 24 hours care (at home or residential): granted",
      "indication 24 hours care (at home or residential): minutes granted",
      "indication 24 hours care (at home or residential): reason declined",
      "indication daytime activities (group): applied",
      "indication daytime activities (group): granted",
      "indication daytime activities (group): minutes granted",
      "indication daytime activities (group): reason declined",
      "indication guidance (one on one): applied",
      "indication guidance (one on one): granted",
      "indication guidance (one on one): minutes granted",
      "indication guidance (one on one): reason declined",
      "indication house adaptation: applied",
      "indication house adaptation: granted",
      "indication house adaptation: reason declined",
      "indication household assistance at home: applied",
      "indication household assistance at home: granted",
      "indication household assistance at home: minutes granted",
      "indication household assistance at home: reason declined",
      "indication granted: care in kind",
      "indication granted: PGB",
      "indication night treatment residential care: applied",
      "indication night treatment residential care: granted",
      "indication night treatment residential care: minutes granted",
      "indication night treatment residential care: reason declined",
      "indication nursing at home: applied",
      "indication nursing at home: granted",
      "indication nursing at home: minutes granted",
      "indication nursing at home: reason declined",
      "other indication: applied",
      "other indication: granted",
      "other indication: minutes granted",
      "other indication: reason declined",
      "indication personal care at home: applied",
      "indication personal care at home: granted",
      "indication personal care at home: minutes granted",
      "indication personal care at home: reason declined",
      "indication short stay residential care: applied",
      "indication short stay residential care: granted",
      "indication short stay residential care: days granted",
      "indication short stay residential care: reason declined",
      "indication transport: applied",
      "indication transport: granted",
      "indication transport: reason declined",
      "PGB: administration: child(ren)",
      "PGB: administration: other",
      "PGB: administration: partner",
      "PGB: administration: private help",
      "PGB: administration: self",
      "PGB: paying for care to: district nurse",
      "PGB: paying for care to: other family (non-resident)",
      "PGB: paying for care to: neighbours/friends/acquaintances",
      "PGB: paying for care to: other",
      "PGB: paying for care to: partner",
      "PGB: paying for care to: professional home care",
      "PGB: paying for care to: private help",
      "PGB: paying for care to: resident child",
      "PGB: paying for care to: other resident",
      "PGB: paying for care to: volunteers",
      "indication 24 hours care (at home or residential): applied",
      "indication 24 hours care (at home or residential): granted",
      "indication 24 hours care (at home or residential): hours granted",
      "indication 24 hours care (at home or residential): minutes granted",
      "indication 24 hours care (at home or residential): reason declined",
      "indication 24 hours care (at home or residential): reason withdrawn",
      "indication daytime activities (group): applied",
      "indication daytime activities (group): granted",
      "indication daytime activities (group): hours granted",
      "indication daytime activities (group): minutes granted",
      "indication daytime activities (group): reason declined",
      "indication daytime activities (group): reason withdrawn",
      "indication guidance (one on one): applied",
      "indication guidance (one on one): granted",
      "indication guidance (one on one): hours granted",
      "indication guidance (one on one): minutes granted",
      "indication guidance (one on one): reason declined",
      "indication guidance (one on one): reason withdrawn",
      "indication house adaptation: applied",
      "indication house adaptation: granted",
      "indication house adaptation: reason declined",
      "indication house adaptation: reason withdrawn",
      "indication household assistance at home: applied",
      "indication household assistance at home: granted",
      "indication household assistance at home: hours granted",
      "indication household assistance at home: minutes granted",
      "indication household assistance at home: reason declined",
      "indication household assistance at home: reason withdrawn",
      "type of indication granted",
      "indication night treatment residential care: applied",
      "indication night treatment residential care: granted",
      "indication night treatment residential care: hours granted",
      "indication night treatment residential care: minutes granted",
      "indication night treatment residential care: reason declined",
      "indication night treatment residential care: reason withdrawn",
      "indication nursing at home: applied",
      "indication nursing at home: granted",
      "indication nursing at home: hours granted",
      "indication nursing at home: minutes granted",
      "indication nursing at home: reason declined",
      "indication nursing at home: reason withdrawn",
      "other indication: applied",
      "other indication: granted",
      "other indication: hours granted",
      "other indication: minutes granted",
      "other indication: reason declined",
      "other indication: reason withdrawn",
      "indication personal care at home: applied",
      "indication personal care at home: granted",
      "indication personal care at home: hours granted",
      "indication personal care at home: minutes granted",
      "indication personal care at home: reason declined",
      "indication personal care at home: reason withdrawn",
      "indication short stay residential care: applied",
      "indication short stay residential care: days granted",
      "indication short stay residential care: granted",
      "indication short stay residential care: reason declined",
      "indication short stay residential care: reason withdrawn",
      "indication transport: applied",
      "indication transport: granted",
      "indication transport: reason declined",
      "indication transport: reason withdrawn",
      "PGB: administration: child(ren)",
      "PGB: administration: other",
      "PGB: administration: partner",
      "PGB: administration: private help",
      "PGB: administration: self",
      "PGB: paying for care to: district nurse",
      "PGB: paying for care to: other family (non-resident)",
      "PGB: paying for care to: neighbours/friends/acquaintances",
      "PGB: paying for care to: other",
      "PGB: paying for care to: partner",
      "PGB: paying for care to: professional home care",
      "PGB: paying for care to: private help",
      "PGB: paying for care to: resident child",
      "PGB: paying for care to: other resident",
      "PGB: paying for care to: volunteers",
      "indication 24 hours care (at home or residential): applied",
      "indication 24 hours care (at home or residential): granted",
      "indication 24 hours care (at home or residential): reason declined",
      "indication 24 hours care (at home or residential): reason withdrawn",
      "indication daytime activities (group): applied",
      "indication daytime activities (group): granted",
      "indication daytime activities (group): hours granted",
      "indication daytime activities (group): minutes granted",
      "indication daytime activities (group): reason declined",
      "indication daytime activities (group): reason withdrawn",
      "indication guidance (one on one): applied",
      "indication guidance (one on one): granted",
      "indication guidance (one on one): hours granted",
      "indication guidance (one on one): minutes granted",
      "indication guidance (one on one): reason declined",
      "indication guidance (one on one): reason withdrawn",
      "indication house adaptation: applied",
      "indication house adaptation: granted",
      "indication house adaptation: reason declined",
      "indication house adaptation: reason withdrawn",
      "indication household assistance at home: applied",
      "indication household assistance at home: granted",
      "indication household assistance at home: hours granted",
      "indication household assistance at home: minutes granted",
      "indication household assistance at home: reason declined",
      "indication household assistance at home: reason withdrawn",
      "type of indication granted",
      "indication night treatment residential care: applied",
      "indication night treatment residential care: comment",
      "indication night treatment residential care: granted",
      "indication night treatment residential care: number nights granted",
      "indication night treatment residential care: reason declined",
      "indication night treatment residential care: reason withdrawn",
      "indication nursing at home: applied",
      "indication nursing at home: granted",
      "indication nursing at home: hours granted",
      "indication nursing at home: minutes granted",
      "indication nursing at home: reason declined",
      "indication nursing at home: reason withdrawn",
      "other indication: applied",
      "other indication: granted",
      "other indication: reason declined",
      "other indication: reason withdrawn",
      "indication personal care at home: applied",
      "indication personal care at home: granted",
      "indication personal care at home: hours granted",
      "indication personal care at home: minutes granted",
      "indication personal care at home: reason declined",
      "indication personal care at home: reason withdrawn",
      "indication short stay residential care: applied",
      "indication short stay residential care: granted",
      "indication short stay residential care: reason declined",
      "indication short stay residential care: reason withdrawn",
      "indication short stay residential care: number days, weeks, months granted",
      "indication short stay residential care: how many days/weeks/months for short stay",
      "indication transport: applied",
      "indication transport: granted",
      "indication transport: reason declined",
      "indication transport: reason withdrawn",
      "PGB: administration: child(ren)",
      "PGB: administration: other",
      "PGB: administration: partner",
      "PGB: administration: private help",
      "PGB: administration: self",
      "PGB: paying for care to: district nurse",
      "PGB: paying for care to: other family (non-resident)",
      "PGB: paying for care to: neighbours/friends/acquaintances",
      "PGB: paying for care to: other",
      "PGB: paying for care to: partner",
      "PGB: paying for care to: professional home care",
      "PGB: paying for care to: private help",
      "PGB: paying for care to: resident child",
      "PGB: paying for care to: other resident",
      "PGB: paying for care to: volunteers"
    ),
    harmonized_var_label = c(
      "Indication for adaptations",
      "Indication for an appliance",
      "Indication for nursing care",
      "Nursing care: hours per week",
      "Home care: domestic tasks",
      "Domestic tasks: Number of hours/week",
      "Day/night treatment in home for the elderly",
      "Home for the elderly: Number of hours/week",
      "Stay in home for the elderly",
      "Indication for home care",
      "Indication for meals",
      "Number of meals per week",
      "Nursing home: department",
      "Day/night treatment in nursing home",
      "Nursing home: Number of hours/week",
      "Stay in nursing home",
      "Indication for personal care",
      "Personal care: hours per week",
      "Other indication",
      "Medical care indication/application status",
      "Urgent indication",
      "Indication for adaptations",
      "Indication for an appliance",
      "Indication for nursing care",
      "Nursing care: hours per week",
      "Home care: domestic tasks",
      "Domestic tasks: Number of hours/week",
      "Type of day/night treatment in home for the elderly",
      "Day/night treatment in home for the elderly",
      "Stay in home for the elderly",
      "Indication for day/night treatment",
      "Other ind.: activating guidance",
      "Other ind.: activating guidance: Number of hours/week",
      "Other ind.: something else",
      "Other ind.: something else: Number of hours/week",
      "Other ind.: supporting guidance",
      "Other ind.: supporting guidance: Number of hours/week",
      "Other ind.: treatment",
      "Other ind.: treatment: Number of hours/week",
      "Indication for stay in (nursing) home",
      "Indicated care funding/delivery type",
      "Indication for meals",
      "Number of meals per week",
      "Day/night treatment in nursing home: department",
      "Type of day/night treatment in nursing home",
      "Nursing home: department",
      "Day/night treatment in nursing home",
      "Stay in nursing home",
      "Indication for personal care",
      "Personal care: hours per week",
      "PGB administration by person",
      "PGB: care by children living away from home",
      "PGB: type of care by children living away from home",
      "PGB: care by friends",
      "PGB: care by family living away from home",
      "PGB: type of care by family living away from home",
      "PGB: type of care by friends",
      "PGB: care by personnel home care",
      "PGB: type of care by personnel home care",
      "PGB: care by household family/friend",
      "PGB: type of care by household family/friend",
      "PGB: care by neighbours",
      "PGB: type of care by neighbours",
      "PGB: care by others",
      "PGB: type of care by others",
      "PGB: care by partner",
      "PGB: care by private care",
      "PGB: type of care by private care",
      "PGB: type of care by partner",
      "Other indication",
      "Medical care indication/application status",
      "Urgent indication",
      "Indication for nursing care",
      "Nursing care: hours per week",
      "day treatment res care",
      "Indicated care funding/delivery type",
      "long stay residential care",
      "night treatment res care",
      "other indication",
      "other care: Number of hours per week",
      "Indication for personal care",
      "Personal care: hours per week",
      "PGB administration by person",
      "PGB: outside hh child personal care",
      "PGB: outside hh child guidance",
      "PGB: outside hh child household care",
      "PGB: devices or transport",
      "PGB: friend personal care",
      "PGB: friend guidance",
      "PGB: friend household care",
      "PGB: home care personal care",
      "PGB: home care guidance",
      "PGB: home care household care",
      "PGB: hh member personal care",
      "PGB: hh member guidance",
      "PGB: hh member household care",
      "PGB: neighbor personal care",
      "PGB: neighbor guidance",
      "PGB: neighbor household care",
      "PGB: other personal care",
      "PGB: other guidance",
      "PGB: other household care",
      "PGB: care by private care",
      "PGB: partner guidance",
      "PGB: partner household care",
      "PGB: private help personal care",
      "PGB: private help guidance",
      "PGB: private help household care",
      "PGB: res care personal care",
      "PGB: res care guidance",
      "PGB: res care household care",
      "PGB: relative personal care",
      "PGB: relative guidance",
      "PGB: relative household care",
      "Medical care indication/application status",
      "short stay residential care",
      "Urgent indication",
      "reason not applied for indication",
      "reason application declined",
      "Applied for Indication",
      "Indication for nursing care",
      "Nursing care: hours per week",
      "day treatment res care",
      "Indicated care funding/delivery type",
      "long stay residential care",
      "night treatment res care",
      "other indication",
      "other care: Number of hours per week",
      "Indication for personal care",
      "Personal care: hours per week",
      "PGB administration: child(ren)",
      "PGB administration: other",
      "PGB administration: partner",
      "PGB administration: private help",
      "PGB administration: self",
      "PGB: outside hh child personal care",
      "PGB: outside hh child guidance",
      "PGB: outside hh child household care",
      "PGB: devices or transport",
      "PGB: friend personal care",
      "PGB: friend guidance",
      "PGB: friend household care",
      "PGB: home care personal care",
      "PGB: home care guidance",
      "PGB: home care household care",
      "PGB: hh member personal care",
      "PGB: hh member guidance",
      "PGB: hh member household care",
      "PGB: neighbor personal care",
      "PGB: neighbor guidance",
      "PGB: neighbor household care",
      "PGB: other personal care",
      "PGB: other guidance",
      "PGB: other household care",
      "PGB: care by private care",
      "PGB: partner guidance",
      "PGB: partner household care",
      "PGB: private help personal care",
      "PGB: private help guidance",
      "PGB: private help household care",
      "PGB: res care personal care",
      "PGB: res care guidance",
      "PGB: res care household care",
      "PGB: relative personal care",
      "PGB: relative guidance",
      "PGB: relative household care",
      "short stay residential care",
      "Urgent indication",
      "indication 24 hours care (at home or residential): applied",
      "indication 24 hours care (at home or residential): granted",
      "indication 24 hours care (at home or residential): minutes granted",
      "indication 24 hours care (at home or residential): reason declined",
      "indication daytime activities (group): applied",
      "indication daytime activities (group): granted",
      "indication daytime activities (group): minutes granted",
      "indication daytime activities (group): reason declined",
      "indication guidance (one on one): applied",
      "indication guidance (one on one): granted",
      "indication guidance (one on one): minutes granted",
      "indication guidance (one on one): reason declined",
      "indication house adaptation: applied",
      "indication house adaptation: granted",
      "indication house adaptation: reason declined",
      "indication household assistance at home: applied",
      "indication household assistance at home: granted",
      "indication household assistance at home: minutes granted",
      "indication household assistance at home: reason declined",
      "indication granted: care in kind",
      "indication granted: PGB",
      "indication night treatment residential care: applied",
      "indication night treatment residential care: granted",
      "indication night treatment residential care: minutes granted",
      "indication night treatment residential care: reason declined",
      "indication nursing at home: applied",
      "indication nursing at home: granted",
      "indication nursing at home: minutes granted",
      "indication nursing at home: reason declined",
      "other indication: applied",
      "other indication: granted",
      "other indication: minutes granted",
      "other indication: reason declined",
      "indication personal care at home: applied",
      "indication personal care at home: granted",
      "indication personal care at home: minutes granted",
      "indication personal care at home: reason declined",
      "indication short stay residential care: applied",
      "indication short stay residential care: granted",
      "indication short stay residential care: days granted",
      "indication short stay residential care: reason declined",
      "indication transport: applied",
      "indication transport: granted",
      "indication transport: reason declined",
      "PGB administration: child(ren)",
      "PGB administration: other",
      "PGB administration: partner",
      "PGB administration: private help",
      "PGB administration: self",
      "PGB: paying for care to: district nurse",
      "PGB: paying for care to: other family (non-resident)",
      "PGB: paying for care to: neighbours/friends/acquaintances",
      "PGB: paying for care to: other",
      "PGB: paying for care to: partner",
      "PGB: paying for care to: professional home care",
      "PGB: paying for care to: private help",
      "PGB: paying for care to: resident child",
      "PGB: paying for care to: other resident",
      "PGB: paying for care to: volunteers",
      "indication 24 hours care (at home or residential): applied",
      "indication 24 hours care (at home or residential): granted",
      "indication 24 hours care (at home or residential): hours granted",
      "indication 24 hours care (at home or residential): minutes granted",
      "indication 24 hours care (at home or residential): reason declined",
      "indication 24 hours care (at home or residential): reason withdrawn",
      "indication daytime activities (group): applied",
      "indication daytime activities (group): granted",
      "indication daytime activities (group): hours granted",
      "indication daytime activities (group): minutes granted",
      "indication daytime activities (group): reason declined",
      "indication daytime activities (group): reason withdrawn",
      "indication guidance (one on one): applied",
      "indication guidance (one on one): granted",
      "indication guidance (one on one): hours granted",
      "indication guidance (one on one): minutes granted",
      "indication guidance (one on one): reason declined",
      "indication guidance (one on one): reason withdrawn",
      "indication house adaptation: applied",
      "indication house adaptation: granted",
      "indication house adaptation: reason declined",
      "indication house adaptation: reason withdrawn",
      "indication household assistance at home: applied",
      "indication household assistance at home: granted",
      "indication household assistance at home: hours granted",
      "indication household assistance at home: minutes granted",
      "indication household assistance at home: reason declined",
      "indication household assistance at home: reason withdrawn",
      "type of indication granted",
      "indication night treatment residential care: applied",
      "indication night treatment residential care: granted",
      "indication night treatment residential care: hours granted",
      "indication night treatment residential care: minutes granted",
      "indication night treatment residential care: reason declined",
      "indication night treatment residential care: reason withdrawn",
      "indication nursing at home: applied",
      "indication nursing at home: granted",
      "indication nursing at home: hours granted",
      "indication nursing at home: minutes granted",
      "indication nursing at home: reason declined",
      "indication nursing at home: reason withdrawn",
      "other indication: applied",
      "other indication: granted",
      "other indication: hours granted",
      "other indication: minutes granted",
      "other indication: reason declined",
      "other indication: reason withdrawn",
      "indication personal care at home: applied",
      "indication personal care at home: granted",
      "indication personal care at home: hours granted",
      "indication personal care at home: minutes granted",
      "indication personal care at home: reason declined",
      "indication personal care at home: reason withdrawn",
      "indication short stay residential care: applied",
      "indication short stay residential care: days granted",
      "indication short stay residential care: granted",
      "indication short stay residential care: reason declined",
      "indication short stay residential care: reason withdrawn",
      "indication transport: applied",
      "indication transport: granted",
      "indication transport: reason declined",
      "indication transport: reason withdrawn",
      "PGB administration: child(ren)",
      "PGB administration: other",
      "PGB administration: partner",
      "PGB administration: private help",
      "PGB administration: self",
      "PGB: paying for care to: district nurse",
      "PGB: paying for care to: other family (non-resident)",
      "PGB: paying for care to: neighbours/friends/acquaintances",
      "PGB: paying for care to: other",
      "PGB: paying for care to: partner",
      "PGB: paying for care to: professional home care",
      "PGB: paying for care to: private help",
      "PGB: paying for care to: resident child",
      "PGB: paying for care to: other resident",
      "PGB: paying for care to: volunteers",
      "indication 24 hours care (at home or residential): applied",
      "indication 24 hours care (at home or residential): granted",
      "indication 24 hours care (at home or residential): reason declined",
      "indication 24 hours care (at home or residential): reason withdrawn",
      "indication daytime activities (group): applied",
      "indication daytime activities (group): granted",
      "indication daytime activities (group): hours granted",
      "indication daytime activities (group): minutes granted",
      "indication daytime activities (group): reason declined",
      "indication daytime activities (group): reason withdrawn",
      "indication guidance (one on one): applied",
      "indication guidance (one on one): granted",
      "indication guidance (one on one): hours granted",
      "indication guidance (one on one): minutes granted",
      "indication guidance (one on one): reason declined",
      "indication guidance (one on one): reason withdrawn",
      "indication house adaptation: applied",
      "indication house adaptation: granted",
      "indication house adaptation: reason declined",
      "indication house adaptation: reason withdrawn",
      "indication household assistance at home: applied",
      "indication household assistance at home: granted",
      "indication household assistance at home: hours granted",
      "indication household assistance at home: minutes granted",
      "indication household assistance at home: reason declined",
      "indication household assistance at home: reason withdrawn",
      "type of indication granted",
      "indication night treatment residential care: applied",
      "indication night treatment residential care: comment",
      "indication night treatment residential care: granted",
      "indication night treatment residential care: number nights granted",
      "indication night treatment residential care: reason declined",
      "indication night treatment residential care: reason withdrawn",
      "indication nursing at home: applied",
      "indication nursing at home: granted",
      "indication nursing at home: hours granted",
      "indication nursing at home: minutes granted",
      "indication nursing at home: reason declined",
      "indication nursing at home: reason withdrawn",
      "other indication: applied",
      "other indication: granted",
      "other indication: reason declined",
      "other indication: reason withdrawn",
      "indication personal care at home: applied",
      "indication personal care at home: granted",
      "indication personal care at home: hours granted",
      "indication personal care at home: minutes granted",
      "indication personal care at home: reason declined",
      "indication personal care at home: reason withdrawn",
      "indication short stay residential care: applied",
      "indication short stay residential care: granted",
      "indication short stay residential care: reason declined",
      "indication short stay residential care: reason withdrawn",
      "indication short stay residential care: number days, weeks, months granted",
      "indication short stay residential care: how many days/weeks/months for short stay",
      "indication transport: applied",
      "indication transport: granted",
      "indication transport: reason declined",
      "indication transport: reason withdrawn",
      "PGB administration: child(ren)",
      "PGB administration: other",
      "PGB administration: partner",
      "PGB administration: private help",
      "PGB administration: self",
      "PGB: paying for care to: district nurse",
      "PGB: paying for care to: other family (non-resident)",
      "PGB: paying for care to: neighbours/friends/acquaintances",
      "PGB: paying for care to: other",
      "PGB: paying for care to: partner",
      "PGB: paying for care to: professional home care",
      "PGB: paying for care to: private help",
      "PGB: paying for care to: resident child",
      "PGB: paying for care to: other resident",
      "PGB: paying for care to: volunteers"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    madapt = list(
      E = no_yes_8,
      F = no_yes_8
    ),
    mappli = list(
      E = no_yes_8,
      F = no_yes_8
    ),
    mdistr = list(
      E = no_yes_8,
      F = no_yes_8,
      G = no_yes_8,
      H = no_yes_8
    ),
    mdistrh = list(
      E = na_routing_na_asked,
      F = na_routing_na_asked,
      G = na_routing_na_asked,
      H = na_routing_na_asked
    ),
    mdomeca = list(
      E = no_yes_8,
      F = no_yes_8
    ),
    mdomech = list(
      E = na_routing_na_asked,
      F = na_routing_na_asked
    ),
    meldedn = list(
      E = day_treatment_night_treatment_both,
      F = no_yes_8
    ),
    melderh = list(
      E = na_routing_na_asked
    ),
    melderl = list(
      E = no_yes_8,
      F = no_yes_8
    ),
    mhomeca = list(
      E = no_yes_8
    ),
    mmeal = list(
      E = no_yes_8,
      F = no_yes_8
    ),
    mmealn = list(
      E = na_routing_na_asked,
      F = na_routing_na_asked
    ),
    mnurdep = list(
      E = somatic_psychogeriatric,
      F = somatic_psychogeriatric
    ),
    mnursdn = list(
      E = day_treatment_night_treatment_both,
      F = no_yes_8
    ),
    mnursh = list(
      E = na_routing_na_asked
    ),
    mnursin = list(
      E = no_yes_8,
      F = no_yes_8
    ),
    mpersca = list(
      E = no_yes_8,
      F = no_yes_8,
      G = no_yes_8,
      H = no_yes_8
    ),
    mpersch = list(
      E = na_routing_na_asked,
      F = na_routing_na_asked,
      G = na_routing_na_asked,
      H = na_routing_na_asked
    ),
    mriooth = list(
      E = no_yes_8,
      F = no_yes_8
    ),
    mrioyn = list(
      E = c(
        `-1` = "na, asked",
        `1` = "no",
        `2` = "no, but expect one soon",
        `3` = "yes",
        `4` = "answer 2 + 3"
      ),
      F = c(`-1` = "na, asked", `1` = "no", `2` = "no, but expect one soon", `3` = "yes"),
      G = c(`-1` = "na, asked", `1` = "no", `2` = "yes, not approved yet", `3` = "yes, approved")
    ),
    murgyn = list(
      E = c(
        `-2` = "na, routing",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes, urgent",
        `3` = "yes, very urgent"
      ),
      F = no_yes_8,
      G = no_yes_8,
      H = no_yes_8
    ),
    medntyp = list(
      F = day_treatment_night_treatment_both
    ),
    midn = list(
      F = no_yes_8
    ),
    mioag = list(
      F = no_yes_8
    ),
    mioagh = list(
      F = na_routing_na_asked
    ),
    miose = list(
      F = no_yes_8
    ),
    mioseh = list(
      F = na_routing_na_asked
    ),
    miosg = list(
      F = no_yes_8
    ),
    miosgh = list(
      F = na_routing_na_asked
    ),
    miotr = list(
      F = no_yes_8
    ),
    miotrh = list(
      F = na_routing_na_asked
    ),
    mistay = list(
      F = no_yes_8
    ),
    mitypc = list(
      F = c(
        `-2` = "na, routing",
        `-1` = "na, asked",
        `1` = "care paid by org",
        `2` = "care paid with pgb"
      ),
      G = home_care_service_pgb,
      H = home_care_service_pgb
    ),
    mndndep = list(
      F = somatic_psychogeriatric
    ),
    mndntyp = list(
      F = day_treatment_night_treatment_both
    ),
    mpgbadm = list(
      F = c(
        `-2` = "na, routing",
        `-1` = "na, asked",
        `1` = "R self",
        `2` = "spouse",
        `3` = "child(ren)",
        `4` = "private help",
        `5` = "other"
      ),
      G = respondent_spouse_child_ren_private_help_other
    ),
    mpgbca = list(
      F = not_mentioned_mentioned_4
    ),
    mpgbcat = list(
      F = domestic_care_personal_care_both
    ),
    mpgbf = list(
      F = not_mentioned_mentioned_4
    ),
    mpgbfa = list(
      F = not_mentioned_mentioned_4
    ),
    mpgbfat = list(
      F = domestic_care_personal_care_both
    ),
    mpgbft = list(
      F = domestic_care_personal_care_both
    ),
    mpgbhc = list(
      F = not_mentioned_mentioned_4
    ),
    mpgbhct = list(
      F = domestic_care_personal_care_both
    ),
    mpgbhf = list(
      F = not_mentioned_mentioned_4
    ),
    mpgbhft = list(
      F = domestic_care_personal_care_both
    ),
    mpgbn = list(
      F = not_mentioned_mentioned_4
    ),
    mpgbnt = list(
      F = domestic_care_personal_care_both
    ),
    mpgbo = list(
      F = not_mentioned_mentioned_4
    ),
    mpgbot = list(
      F = domestic_care_personal_care_both
    ),
    mpgbp = list(
      F = not_mentioned_mentioned_4
    ),
    mpgbpc = list(
      F = not_mentioned_mentioned_4,
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbpct = list(
      F = domestic_care_personal_care_both
    ),
    mpgbpt = list(
      F = domestic_care_personal_care_both
    ),
    mdtreat = list(
      G = no_yes_elderly_home_yes_nursing_home_somatic,
      H = no_yes_elderly_home_yes_nursing_home_somatic
    ),
    mlstay = list(
      G = no_yes_elderly_home_yes_nursing_home_somatic,
      H = no_yes_elderly_home_yes_nursing_home_somatic
    ),
    mntreat = list(
      G = no_yes_elderly_home_yes_nursing_home_somatic,
      H = no_yes_elderly_home_yes_nursing_home_somatic
    ),
    mother = list(
      G = no_yes_8,
      H = no_yes_8
    ),
    motherh = list(
      G = na_routing_na_asked,
      H = na_routing_na_asked
    ),
    mpgbchc = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbchg = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbchh = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbdev = list(
      G = no_yes_8,
      H = no_yes_8
    ),
    mpgbfrc = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbfrg = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbfrh = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbhcc = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbhcg = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbhch = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbhmc = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbhmg = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbhmh = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbnbc = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbnbg = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbnbh = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbotc = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbotg = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgboth = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbpg = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbph = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbphc = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbphg = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbphh = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbrcc = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbrcg = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbrch = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbrlc = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbrlg = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mpgbrlh = list(
      G = not_mentioned_mentioned_4,
      H = not_mentioned_mentioned_4
    ),
    mshstay = list(
      G = no_yes_elderly_home_yes_nursing_home_somatic,
      H = no_yes_elderly_home_yes_nursing_home_somatic
    ),
    mcizna = list(
      H = not_needed_prefer_self_regulation_did_not_know
    ),
    mcizrd = list(
      H = must_rely_on_informal_network
    ),
    mcizyn = list(
      H = c(
        `-5` = "section not done",
        `1` = "no",
        `2` = "yes, declined",
        `3` = "yes, not approved yet",
        `4` = "yes, approved"
      )
    ),
    mpgbac = list(
      H = not_mentioned_mentioned_4,
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mpgbao = list(
      H = not_mentioned_mentioned_4,
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mpgbap = list(
      H = not_mentioned_mentioned_4,
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mpgbaph = list(
      H = not_mentioned_mentioned_4,
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mpgbas = list(
      H = not_mentioned_mentioned_4,
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mi24ca = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    mi24cg = list(
      I = c(
        `-2` = "na, see IMI24CA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMI24CA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMI24CA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    mi24cm = list(
      I = c(`-2` = "na, see IMI24CA", `-1` = "na, asked"),
      J = na_see_jmi24ca_na_asked
    ),
    mi24crd = list(
      I = c(
        `-2` = "na, see IMI24CG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_2,
      K = informal_network_should_help_3
    ),
    midaca = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    midacg = list(
      I = c(
        `-2` = "na, see IMIDACA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMIDACA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMIDACA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    midacm = list(
      I = c(`-2` = "na, see IMIDACA", `-1` = "na, asked"),
      J = na_see_jmidaca_na_asked,
      K = na_see_kmidaca_na_asked
    ),
    midacrd = list(
      I = c(
        `-2` = "na, see IMIDACG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_4,
      K = informal_network_should_help_5
    ),
    miguia = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    miguig = list(
      I = c(
        `-2` = "na, see IMIGUIA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMIGUIA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMIGUIA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    miguim = list(
      I = c(`-2` = "na, see IMIGUIA", `-1` = "na, asked"),
      J = na_see_jmiguia_na_asked,
      K = na_see_kmiguia_na_asked
    ),
    miguird = list(
      I = c(
        `-2` = "na, see IMIGUIG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_6,
      K = informal_network_should_help_7
    ),
    mihada = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    mihadg = list(
      I = c(
        `-2` = "na, see IMIHADA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMIHADA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMIHADA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    mihadrd = list(
      I = c(
        `-2` = "na, see IMIHADG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_8,
      K = informal_network_should_help_9
    ),
    mihhaa = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    mihhag = list(
      I = c(
        `-2` = "na, see IMIHHAA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMIHHAA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMIHHAA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    mihham = list(
      I = c(`-2` = "na, see IMIHHAA", `-1` = "na, asked"),
      J = na_see_jmihhaa_na_asked,
      K = na_see_kmihhaa_na_asked
    ),
    mihhard = list(
      I = c(
        `-2` = "na, see IMIHHAG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_10,
      K = informal_network_should_help_11
    ),
    mindnat = list(
      I = not_mentioned_mentioned_263
    ),
    mindpgb = list(
      I = not_mentioned_mentioned_263
    ),
    mintca = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    mintcg = list(
      I = c(
        `-2` = "na, see IMINTCA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMINTCA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMINTCA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    mintcm = list(
      I = c(`-2` = "na, see IMINTCA", `-1` = "na, asked"),
      J = na_see_jmintca_na_asked
    ),
    mintcrd = list(
      I = c(
        `-2` = "na, see IMINTCG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_12,
      K = informal_network_should_help_13
    ),
    minura = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    minurg = list(
      I = c(
        `-2` = "na, see IMINURA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMINURA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMINURA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    minurm = list(
      I = c(`-2` = "na, see IMINURA", `-1` = "na, asked"),
      J = na_see_jminura_na_asked,
      K = na_see_kminura_na_asked
    ),
    minurrd = list(
      I = c(
        `-2` = "na, see IMINURG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_14,
      K = informal_network_should_help_15
    ),
    miotha = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    miothg = list(
      I = c(
        `-2` = "na, see IMIOTHA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMIOTHA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMIOTHA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    miothm = list(
      I = c(`-2` = "na, see IMIOTHA", `-1` = "na, asked"),
      J = na_see_jmiotha_na_asked
    ),
    miothrd = list(
      I = c(
        `-2` = "na, see IMIOTHG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_16,
      K = informal_network_should_help_17
    ),
    mipca = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    mipcg = list(
      I = c(
        `-2` = "na, see IMIPCA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMIPCA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMIPCA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    mipcm = list(
      I = c(`-2` = "na, see IMIPCA", `-1` = "na, asked"),
      J = na_see_jmipca_na_asked,
      K = na_see_kmipca_na_asked
    ),
    mipcrd = list(
      I = c(
        `-2` = "na, see IMIPCG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_18,
      K = informal_network_should_help_19
    ),
    missca = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    misscd = list(
      I = c(`-2` = "na, see IMISSCA", `-1` = "na, asked"),
      J = c(`-2` = "na, see JMISSCA", `-1` = "na, asked")
    ),
    misscg = list(
      I = c(
        `-2` = "na, see IMISSCA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMISSCA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMISSCA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    misscrd = list(
      I = c(
        `-2` = "na, see IMISSCG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_20,
      K = informal_network_should_help_21
    ),
    mitraa = list(
      I = no_yes_52,
      J = no_yes_12,
      K = no_yes_12
    ),
    mitrag = list(
      I = c(
        `-2` = "na, see IMITRAA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      J = c(
        `-2` = "na, see JMITRAA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      ),
      K = c(
        `-2` = "na, see KMITRAA",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes",
        `3` = "under consideration",
        `4` = "withdrawn"
      )
    ),
    mitrard = list(
      I = c(
        `-2` = "na, see IMITRAG",
        `-1` = "na, asked",
        `1` = "informal network should help",
        `2` = "need for care is not serious enough",
        `3` = "other"
      ),
      J = informal_network_should_help_22,
      K = informal_network_should_help_23
    ),
    mppgbdn = list(
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mppgbfo = list(
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mppgbnf = list(
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mppgbot = list(
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mppgbpa = list(
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mppgbpc = list(
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mppgbph = list(
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mppgbrc = list(
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mppgbro = list(
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mppgbvo = list(
      I = not_mentioned_mentioned_106,
      J = not_mentioned_mentioned_49,
      K = not_mentioned_mentioned_49
    ),
    mi24ch = list(
      J = na_see_jmi24ca_na_asked
    ),
    mi24crw = list(
      J = informal_network_should_help_2,
      K = informal_network_should_help_3
    ),
    midach = list(
      J = na_see_jmidaca_na_asked,
      K = na_see_kmidaca_na_asked
    ),
    midacrw = list(
      J = informal_network_should_help_4,
      K = informal_network_should_help_5
    ),
    miguih = list(
      J = na_see_jmiguia_na_asked,
      K = na_see_kmiguia_na_asked
    ),
    miguirw = list(
      J = informal_network_should_help_6,
      K = informal_network_should_help_7
    ),
    mihadrw = list(
      J = informal_network_should_help_8,
      K = informal_network_should_help_9
    ),
    mihhah = list(
      J = na_see_jmihhaa_na_asked,
      K = na_see_kmihhaa_na_asked
    ),
    mihharw = list(
      J = informal_network_should_help_10,
      K = informal_network_should_help_11
    ),
    mindtype = list(
      J = in_kind_personal_budget_pgb_both,
      K = in_kind_personal_budget_pgb_both
    ),
    mintch = list(
      J = na_see_jmintca_na_asked
    ),
    mintcrw = list(
      J = informal_network_should_help_12,
      K = informal_network_should_help_13
    ),
    minurh = list(
      J = na_see_jminura_na_asked,
      K = na_see_kminura_na_asked
    ),
    minurrw = list(
      J = informal_network_should_help_14,
      K = informal_network_should_help_15
    ),
    miothh = list(
      J = na_see_jmiotha_na_asked
    ),
    miothrw = list(
      J = informal_network_should_help_16,
      K = informal_network_should_help_17
    ),
    mipch = list(
      J = na_see_jmipca_na_asked,
      K = na_see_kmipca_na_asked
    ),
    mipcrw = list(
      J = informal_network_should_help_18,
      K = informal_network_should_help_19
    ),
    misscrw = list(
      J = informal_network_should_help_20,
      K = informal_network_should_help_21
    ),
    mitrarw = list(
      J = informal_network_should_help_22,
      K = informal_network_should_help_23
    ),
    mintcn = list(
      K = c(`-2` = "na, see KMINTCA", `-1` = "na, asked")
    ),
    misshd = list(
      K = na_see_kmissca_na_asked
    ),
    missn = list(
      K = na_see_kmissca_na_asked
    )
  ),

  value_labels_harmonized = list(
    madapt = no_yes_8,
    mappli = no_yes_8,
    mcizna = not_needed_prefer_self_regulation_did_not_know,
    mcizrd = must_rely_on_informal_network,
    mcizyn = c(
      `-5` = "section not done",
      `1` = "no",
      `2` = "yes, declined",
      `3` = "yes, not approved yet",
      `4` = "yes"
    ),
    mdistr = no_yes_8,
    mdistrh = na_routing_na_asked,
    mdomeca = no_yes_8,
    mdomech = na_routing_na_asked,
    mdtreat = no_yes_elderly_home_yes_nursing_home_somatic,
    medntyp = day_treatment_night_treatment_both,
    meldedn = no_yes_both,
    melderh = na_routing_na_asked,
    melderl = no_yes_8,
    mhomeca = no_yes_8,
    mi24ca = no_yes_12,
    mi24cg = no_yes_under_consideration_withdrawn,
    mi24ch = no_valid_data_na_asked,
    mi24cm = no_valid_data_na_asked,
    mi24crd = informal_network_should_help,
    mi24crw = informal_network_should_help,
    midaca = no_yes_12,
    midacg = no_yes_under_consideration_withdrawn,
    midach = no_valid_data_na_asked,
    midacm = no_valid_data_na_asked,
    midacrd = informal_network_should_help,
    midacrw = informal_network_should_help,
    midn = no_yes_8,
    miguia = no_yes_12,
    miguig = no_yes_under_consideration_withdrawn,
    miguih = no_valid_data_na_asked,
    miguim = no_valid_data_na_asked,
    miguird = informal_network_should_help,
    miguirw = informal_network_should_help,
    mihada = no_yes_12,
    mihadg = no_yes_under_consideration_withdrawn,
    mihadrd = informal_network_should_help,
    mihadrw = informal_network_should_help,
    mihhaa = no_yes_12,
    mihhag = no_yes_under_consideration_withdrawn,
    mihhah = no_valid_data_na_asked,
    mihham = no_valid_data_na_asked,
    mihhard = informal_network_should_help,
    mihharw = informal_network_should_help,
    mindnat = not_mentioned_mentioned_263,
    mindpgb = not_mentioned_mentioned_263,
    mindtype = in_kind_personal_budget_pgb_both,
    mintca = no_yes_12,
    mintcg = no_yes_under_consideration_withdrawn,
    mintch = no_valid_data_na_asked,
    mintcm = no_valid_data_na_asked,
    mintcn = no_valid_data_na_asked,
    mintcrd = informal_network_should_help,
    mintcrw = informal_network_should_help,
    minura = no_yes_12,
    minurg = no_yes_under_consideration_withdrawn,
    minurh = no_valid_data_na_asked,
    minurm = no_valid_data_na_asked,
    minurrd = informal_network_should_help,
    minurrw = informal_network_should_help,
    mioag = no_yes_8,
    mioagh = na_routing_na_asked,
    miose = no_yes_8,
    mioseh = na_routing_na_asked,
    miosg = no_yes_8,
    miosgh = na_routing_na_asked,
    miotha = no_yes_12,
    miothg = no_yes_under_consideration_withdrawn,
    miothh = no_valid_data_na_asked,
    miothm = no_valid_data_na_asked,
    miothrd = informal_network_should_help,
    miothrw = informal_network_should_help,
    miotr = no_yes_8,
    miotrh = na_routing_na_asked,
    mipca = no_yes_12,
    mipcg = no_yes_under_consideration_withdrawn,
    mipch = no_valid_data_na_asked,
    mipcm = no_valid_data_na_asked,
    mipcrd = informal_network_should_help,
    mipcrw = informal_network_should_help,
    missca = no_yes_12,
    misscd = no_valid_data_na_asked,
    misscg = no_yes_under_consideration_withdrawn,
    misscrd = informal_network_should_help,
    misscrw = informal_network_should_help,
    misshd = no_valid_data_na_asked,
    missn = no_valid_data_na_asked,
    mistay = no_yes_8,
    mitraa = no_yes_12,
    mitrag = no_yes_under_consideration_withdrawn,
    mitrard = informal_network_should_help,
    mitrarw = informal_network_should_help,
    mitypc = c(`-2` = "na, routing", `-1` = "na, asked", `1` = "care paid by org", `2` = "PGB"),
    mlstay = no_yes_elderly_home_yes_nursing_home_somatic,
    mmeal = no_yes_8,
    mmealn = na_routing_na_asked,
    mndndep = somatic_psychogeriatric,
    mndntyp = day_treatment_night_treatment_both,
    mntreat = no_yes_elderly_home_yes_nursing_home_somatic,
    mnurdep = somatic_psychogeriatric,
    mnursdn = no_yes_both,
    mnursh = na_routing_na_asked,
    mnursin = no_yes_8,
    mother = no_yes_8,
    motherh = na_routing_na_asked,
    mpersca = no_yes_8,
    mpersch = na_routing_na_asked,
    mpgbac = not_mentioned_mentioned_238,
    mpgbadm = respondent_spouse_child_ren_private_help_other,
    mpgbao = not_mentioned_mentioned_238,
    mpgbap = not_mentioned_mentioned_238,
    mpgbaph = not_mentioned_mentioned_238,
    mpgbas = not_mentioned_mentioned_238,
    mpgbca = not_mentioned_mentioned_4,
    mpgbcat = domestic_care_personal_care_both,
    mpgbchc = not_mentioned_mentioned_4,
    mpgbchg = not_mentioned_mentioned_4,
    mpgbchh = not_mentioned_mentioned_4,
    mpgbdev = no_yes_8,
    mpgbf = not_mentioned_mentioned_4,
    mpgbfa = not_mentioned_mentioned_4,
    mpgbfat = domestic_care_personal_care_both,
    mpgbfrc = not_mentioned_mentioned_4,
    mpgbfrg = not_mentioned_mentioned_4,
    mpgbfrh = not_mentioned_mentioned_4,
    mpgbft = domestic_care_personal_care_both,
    mpgbhc = not_mentioned_mentioned_4,
    mpgbhcc = not_mentioned_mentioned_4,
    mpgbhcg = not_mentioned_mentioned_4,
    mpgbhch = not_mentioned_mentioned_4,
    mpgbhct = domestic_care_personal_care_both,
    mpgbhf = not_mentioned_mentioned_4,
    mpgbhft = domestic_care_personal_care_both,
    mpgbhmc = not_mentioned_mentioned_4,
    mpgbhmg = not_mentioned_mentioned_4,
    mpgbhmh = not_mentioned_mentioned_4,
    mpgbn = not_mentioned_mentioned_4,
    mpgbnbc = not_mentioned_mentioned_4,
    mpgbnbg = not_mentioned_mentioned_4,
    mpgbnbh = not_mentioned_mentioned_4,
    mpgbnt = domestic_care_personal_care_both,
    mpgbo = not_mentioned_mentioned_4,
    mpgbot = domestic_care_personal_care_both,
    mpgbotc = not_mentioned_mentioned_4,
    mpgbotg = not_mentioned_mentioned_4,
    mpgboth = not_mentioned_mentioned_4,
    mpgbp = not_mentioned_mentioned_4,
    mpgbpc = not_mentioned_mentioned_4,
    mpgbpct = domestic_care_personal_care_both,
    mpgbpg = not_mentioned_mentioned_4,
    mpgbph = not_mentioned_mentioned_4,
    mpgbphc = not_mentioned_mentioned_4,
    mpgbphg = not_mentioned_mentioned_4,
    mpgbphh = not_mentioned_mentioned_4,
    mpgbpt = domestic_care_personal_care_both,
    mpgbrcc = not_mentioned_mentioned_4,
    mpgbrcg = not_mentioned_mentioned_4,
    mpgbrch = not_mentioned_mentioned_4,
    mpgbrlc = not_mentioned_mentioned_4,
    mpgbrlg = not_mentioned_mentioned_4,
    mpgbrlh = not_mentioned_mentioned_4,
    mppgbdn = not_mentioned_mentioned_36,
    mppgbfo = not_mentioned_mentioned_36,
    mppgbnf = not_mentioned_mentioned_36,
    mppgbot = not_mentioned_mentioned_36,
    mppgbpa = not_mentioned_mentioned_36,
    mppgbpc = not_mentioned_mentioned_36,
    mppgbph = not_mentioned_mentioned_36,
    mppgbrc = not_mentioned_mentioned_36,
    mppgbro = not_mentioned_mentioned_36,
    mppgbvo = not_mentioned_mentioned_36,
    mriooth = no_yes_8,
    mrioyn = c(
      `-1` = "na, asked",
      `1` = "no",
      `2` = "indication/application not yet finalized",
      `3` = "yes",
      `4` = "answer 2 + 3"
    ),
    mshstay = no_yes_elderly_home_yes_nursing_home_somatic,
    murgyn = c(`-2` = "na, routing", `-1` = "na, asked", `1` = "no", `2` = "yes", `3` = "yes, very urgent")
  )
)
