## LASA filecode 109 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_109 <- list(
  variables = data.frame(
    wave = c(
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "iqpchc05",
      "iqpchc06",
      "iqpchc07",
      "iqpchc08",
      "iqpchc09",
      "iqpchc10",
      "iqpchc11",
      "iqpchc12",
      "iqpchc13",
      "iqpchc14",
      "iqpchc15",
      "iqpchc17",
      "iqpchc18",
      "jqpchc05",
      "jqpchc06",
      "jqpchc07",
      "jqpchc08",
      "jqpchc09",
      "jqpchc10",
      "jqpchc11",
      "jqpchc12",
      "jqpchc13",
      "jqpchc14",
      "jqpchc15",
      "jqpchc17",
      "jqpchc18",
      "kqpchc05",
      "kqpchc06",
      "kqpchc07",
      "kqpchc08",
      "kqpchc09",
      "kqpchc10",
      "kqpchc11",
      "kqpchc12",
      "kqpchc13",
      "kqpchc14",
      "kqpchc15",
      "kqpchc17",
      "kqpchc18"
    ),
    canonical_name = c(
      "qpchc05",
      "qpchc06",
      "qpchc07",
      "qpchc08",
      "qpchc09",
      "qpchc10",
      "qpchc11",
      "qpchc12",
      "qpchc13",
      "qpchc14",
      "qpchc15",
      "qpchc17",
      "qpchc18",
      "qpchc05",
      "qpchc06",
      "qpchc07",
      "qpchc08",
      "qpchc09",
      "qpchc10",
      "qpchc11",
      "qpchc12",
      "qpchc13",
      "qpchc14",
      "qpchc15",
      "qpchc17",
      "qpchc18",
      "qpchc05",
      "qpchc06",
      "qpchc07",
      "qpchc08",
      "qpchc09",
      "qpchc10",
      "qpchc11",
      "qpchc12",
      "qpchc13",
      "qpchc14",
      "qpchc15",
      "qpchc17",
      "qpchc18"
    ),
    variable_label = c(
      "Perceived control in health care: I know when it is time to call in care",
      "Perceived control in health care: I can find information about health or care when I need it",
      "Perceived control in health care: I will find out if there are any aids or services I could really use",
      "Perceived control in health care: I know where to apply for care, aids or services",
      "Perceived control in health care: I am able to arrange any care, aids or services I need",
      "Perceived control in health care: I understand the regulations of care organisations that are relevant for me",
      "Perceived control in health care: I can manage to get to my healthcare professional(s) when I need to",
      "Perceived control in health care: I can keep track of all appointments with my healthcare professional(s)",
      "Perceived control in health care: I explain what is going on to my healthcare professional(s)",
      "Perceived control in health care: I ask any questions I have about my health or treatment",
      "Perceived control in health care: I indicate any wishes I have",
      "Perceived control in health care: I can deal with the medication I am prescribed by my healthcare professional(s)",
      "Perceived control in health care: I am able to carry out the recommendations I am prescribed by my healthcare professional(s)",
      "Perceived control in health care: I know when it is time to call in care",
      "Perceived control in health care: I can find information about health or care when I need it",
      "Perceived control in health care: I will find out if there are any aids or services I could really use",
      "Perceived control in health care: I know where to apply for care, aids or services",
      "Perceived control in health care: I am able to arrange any care, aids or services I need",
      "Perceived control in health care: I understand the regulations of care organisations that are relevant for me",
      "Perceived control in health care: I can manage to get to my healthcare professional(s) when I need to",
      "Perceived control in health care: I can keep track of all appointments with my healthcare professional(s)",
      "Perceived control in health care: I explain what is going on to my healthcare professional(s)",
      "Perceived control in health care: I ask any questions I have about my health or treatment",
      "Perceived control in health care: I indicate any wishes I have",
      "Perceived control in health care: I can deal with the medication I am prescribed by my healthcare professional(s)",
      "Perceived control in health care: I am able to carry out the recommendations I am prescribed by my healthcare professional(s)",
      "Perceived control in health care: I know when it is time to call in care",
      "Perceived control in health care: I can find information about health or care when I need it",
      "Perceived control in health care: I will find out if there are any aids or services I could really use",
      "Perceived control in health care: I know where to apply for care, aids or services",
      "Perceived control in health care: I am able to arrange any care, aids or services I need",
      "Perceived control in health care: I understand the regulations of care organisations that are relevant for me",
      "Perceived control in health care: I can manage to get to my healthcare professional(s) when I need to",
      "Perceived control in health care: I can keep track of all appointments with my healthcare professional(s)",
      "Perceived control in health care: I explain what is going on to my healthcare professional(s)",
      "Perceived control in health care: I ask any questions I have about my health or treatment",
      "Perceived control in health care: I indicate any wishes I have",
      "Perceived control in health care: I can deal with the medication I am prescribed by my healthcare professional(s)",
      "Perceived control in health care: I am able to carry out the recommendations I am prescribed by my healthcare professional(s)"
    ),
    harmonized_var_label = c(
      "Perceived control in health care: I know when it is time to call in care",
      "Perceived control in health care: I can find information about health or care when I need it",
      "Perceived control in health care: I will find out if there are any aids or services I could really use",
      "Perceived control in health care: I know where to apply for care, aids or services",
      "Perceived control in health care: I am able to arrange any care, aids or services I need",
      "Perceived control in health care: I understand the regulations of care organisations that are relevant for me",
      "Perceived control in health care: I can manage to get to my healthcare professional(s) when I need to",
      "Perceived control in health care: I can keep track of all appointments with my healthcare professional(s)",
      "Perceived control in health care: I explain what is going on to my healthcare professional(s)",
      "Perceived control in health care: I ask any questions I have about my health or treatment",
      "Perceived control in health care: I indicate any wishes I have",
      "Perceived control in health care: I can deal with the medication I am prescribed by my healthcare professional(s)",
      "Perceived control in health care: I am able to carry out the recommendations I am prescribed by my healthcare professional(s)",
      "Perceived control in health care: I know when it is time to call in care",
      "Perceived control in health care: I can find information about health or care when I need it",
      "Perceived control in health care: I will find out if there are any aids or services I could really use",
      "Perceived control in health care: I know where to apply for care, aids or services",
      "Perceived control in health care: I am able to arrange any care, aids or services I need",
      "Perceived control in health care: I understand the regulations of care organisations that are relevant for me",
      "Perceived control in health care: I can manage to get to my healthcare professional(s) when I need to",
      "Perceived control in health care: I can keep track of all appointments with my healthcare professional(s)",
      "Perceived control in health care: I explain what is going on to my healthcare professional(s)",
      "Perceived control in health care: I ask any questions I have about my health or treatment",
      "Perceived control in health care: I indicate any wishes I have",
      "Perceived control in health care: I can deal with the medication I am prescribed by my healthcare professional(s)",
      "Perceived control in health care: I am able to carry out the recommendations I am prescribed by my healthcare professional(s)",
      "Perceived control in health care: I know when it is time to call in care",
      "Perceived control in health care: I can find information about health or care when I need it",
      "Perceived control in health care: I will find out if there are any aids or services I could really use",
      "Perceived control in health care: I know where to apply for care, aids or services",
      "Perceived control in health care: I am able to arrange any care, aids or services I need",
      "Perceived control in health care: I understand the regulations of care organisations that are relevant for me",
      "Perceived control in health care: I can manage to get to my healthcare professional(s) when I need to",
      "Perceived control in health care: I can keep track of all appointments with my healthcare professional(s)",
      "Perceived control in health care: I explain what is going on to my healthcare professional(s)",
      "Perceived control in health care: I ask any questions I have about my health or treatment",
      "Perceived control in health care: I indicate any wishes I have",
      "Perceived control in health care: I can deal with the medication I am prescribed by my healthcare professional(s)",
      "Perceived control in health care: I am able to carry out the recommendations I am prescribed by my healthcare professional(s)"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qpchc05 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc06 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc07 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc08 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc09 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc10 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc11 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc12 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc13 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc14 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc15 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree,
      J = strongly_disagree_disagree_no_dis_agreement_agree,
      K = strongly_disagree_disagree_no_dis_agreement_agree
    ),
    qpchc17 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree_2,
      J = strongly_disagree_disagree_no_dis_agreement_agree_2,
      K = strongly_disagree_disagree_no_dis_agreement_agree_2
    ),
    qpchc18 = list(
      I = strongly_disagree_disagree_no_dis_agreement_agree_2,
      J = strongly_disagree_disagree_no_dis_agreement_agree_2,
      K = strongly_disagree_disagree_no_dis_agreement_agree_2
    )
  ),

  value_labels_harmonized = list(
    qpchc05 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc06 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc07 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc08 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc09 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc10 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc11 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc12 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc13 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc14 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc15 = strongly_disagree_disagree_no_dis_agreement_agree,
    qpchc17 = strongly_disagree_disagree_no_dis_agreement_agree_2,
    qpchc18 = strongly_disagree_disagree_no_dis_agreement_agree_2
  )
)
