## LASA filecode 178 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_178 <- list(
  variables = data.frame(
    wave = c(
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "gmwmoapp",
      "gmwmomun",
      "gmwmonc1",
      "gmwmonc2",
      "gmwmonc3",
      "gmwmonc4",
      "gmwmonc5",
      "gmwmonc6",
      "gmwmorc",
      "gmwmota1",
      "gmwmota2",
      "gmwmota3",
      "gmwmota4",
      "gmwmota5",
      "gmwmota6",
      "gmwmota7",
      "hmwmoapp",
      "hmwmomun",
      "hmwmonc1",
      "hmwmonc2",
      "hmwmonc3",
      "hmwmonc4",
      "hmwmonc5",
      "hmwmonc6",
      "hmwmorc1",
      "hmwmorc2",
      "hmwmorc3",
      "hmwmorc4",
      "hmwmorc5",
      "hmwmorc6",
      "hmwmota1",
      "hmwmota2",
      "hmwmota3",
      "hmwmota4",
      "hmwmota5",
      "hmwmota6",
      "hmwmota7",
      "imcizctc",
      "imciznc1",
      "imciznc2",
      "imciznc3",
      "imciznc4",
      "imciznc5",
      "imciznc6",
      "imcizrc1",
      "imcizrc2",
      "imcizrc3",
      "imcizrc4",
      "imcizrc5",
      "imcizrc6",
      "imcizrc7",
      "imhwwctc",
      "imhwwnc1",
      "imhwwnc2",
      "imhwwnc3",
      "imhwwnc4",
      "imhwwnc5",
      "imhwwnc6",
      "imhwwrc1",
      "imhwwrc2",
      "imhwwrc3",
      "imhwwrc4",
      "imhwwrc5",
      "imhwwrc6",
      "imhwwrc7",
      "imwmoctc",
      "imwmonc1",
      "imwmonc2",
      "imwmonc3",
      "imwmonc4",
      "imwmonc5",
      "imwmonc6",
      "imwmorc1",
      "imwmorc2",
      "imwmorc3",
      "imwmorc4",
      "imwmorc5",
      "imwmorc6",
      "imwmorc7",
      "jmcizctc",
      "jmciznc1",
      "jmciznc2",
      "jmciznc3",
      "jmciznc4",
      "jmciznc5",
      "jmciznc6",
      "jmcizpc1",
      "jmcizpc10",
      "jmcizpc11",
      "jmcizpc2",
      "jmcizpc3",
      "jmcizpc4",
      "jmcizpc5",
      "jmcizpc6",
      "jmcizpc7",
      "jmcizpc8",
      "jmcizpc9",
      "jmcizrc1",
      "jmcizrc2",
      "jmcizrc3",
      "jmcizrc4",
      "jmcizrc5",
      "jmcizrc6",
      "jmcizrc7",
      "jmhwwctc",
      "jmhwwnc1",
      "jmhwwnc2",
      "jmhwwnc3",
      "jmhwwnc4",
      "jmhwwnc5",
      "jmhwwnc6",
      "jmhwwpc1",
      "jmhwwpc10",
      "jmhwwpc11",
      "jmhwwpc2",
      "jmhwwpc3",
      "jmhwwpc4",
      "jmhwwpc5",
      "jmhwwpc6",
      "jmhwwpc7",
      "jmhwwpc8",
      "jmhwwpc9",
      "jmhwwrc1",
      "jmhwwrc2",
      "jmhwwrc3",
      "jmhwwrc4",
      "jmhwwrc5",
      "jmhwwrc6",
      "jmhwwrc7",
      "jmwmoctc",
      "jmwmonc1",
      "jmwmonc2",
      "jmwmonc3",
      "jmwmonc4",
      "jmwmonc5",
      "jmwmonc6",
      "jmwmopc1",
      "jmwmopc10",
      "jmwmopc11",
      "jmwmopc2",
      "jmwmopc3",
      "jmwmopc4",
      "jmwmopc5",
      "jmwmopc6",
      "jmwmopc7",
      "jmwmopc8",
      "jmwmopc9",
      "jmwmorc1",
      "jmwmorc2",
      "jmwmorc3",
      "jmwmorc4",
      "jmwmorc5",
      "jmwmorc6",
      "jmwmorc7",
      "kmcizctc",
      "kmciznc1",
      "kmciznc2",
      "kmciznc3",
      "kmciznc4",
      "kmciznc5",
      "kmciznc6",
      "kmcizpc1",
      "kmcizpc10",
      "kmcizpc11",
      "kmcizpc2",
      "kmcizpc3",
      "kmcizpc4",
      "kmcizpc5",
      "kmcizpc6",
      "kmcizpc7",
      "kmcizpc8",
      "kmcizpc9",
      "kmcizrc1",
      "kmcizrc2",
      "kmcizrc3",
      "kmcizrc4",
      "kmcizrc5",
      "kmcizrc6",
      "kmcizrc7",
      "kmhwwctc",
      "kmhwwnc1",
      "kmhwwnc2",
      "kmhwwnc3",
      "kmhwwnc4",
      "kmhwwnc5",
      "kmhwwnc6",
      "kmhwwpc1",
      "kmhwwpc10",
      "kmhwwpc11",
      "kmhwwpc2",
      "kmhwwpc3",
      "kmhwwpc4",
      "kmhwwpc5",
      "kmhwwpc6",
      "kmhwwpc7",
      "kmhwwpc8",
      "kmhwwpc9",
      "kmhwwrc1",
      "kmhwwrc2",
      "kmhwwrc3",
      "kmhwwrc4",
      "kmhwwrc5",
      "kmhwwrc6",
      "kmhwwrc7",
      "kmwmoctc",
      "kmwmonc1",
      "kmwmonc2",
      "kmwmonc3",
      "kmwmonc4",
      "kmwmonc5",
      "kmwmonc6",
      "kmwmopc1",
      "kmwmopc10",
      "kmwmopc11",
      "kmwmopc2",
      "kmwmopc3",
      "kmwmopc4",
      "kmwmopc5",
      "kmwmopc6",
      "kmwmopc7",
      "kmwmopc8",
      "kmwmopc9",
      "kmwmorc1",
      "kmwmorc2",
      "kmwmorc3",
      "kmwmorc4",
      "kmwmorc5",
      "kmwmorc6",
      "kmwmorc7"
    ),
    canonical_name = c(
      "mwmoapp",
      "mwmoctc",
      "mwmonc1",
      "mwmonc2",
      "mwmonc3",
      "mwmonc4",
      "mwmonc5",
      "mwmonc6",
      "mwmorc",
      "mwmota1",
      "mwmota2",
      "mwmota3",
      "mwmota4",
      "mwmota5",
      "mwmota6",
      "mwmota7",
      "mwmoapp",
      "mwmoctc",
      "mwmonc1",
      "mwmonc2",
      "mwmonc3",
      "mwmonc4",
      "mwmonc5",
      "mwmonc6",
      "mwmorc1",
      "mwmorc2",
      "mwmorc3",
      "mwmorc4",
      "mwmorc5",
      "mwmorc6",
      "mwmota1",
      "mwmota2",
      "mwmota3",
      "mwmota4",
      "mwmota5",
      "mwmota6",
      "mwmota7",
      "mcizctc",
      "mciznc1",
      "mciznc2",
      "mciznc3",
      "mciznc4",
      "mciznc5",
      "mciznc6",
      "mcizrc1",
      "mcizrc2",
      "mcizrc3",
      "mcizrc4",
      "mcizrc5",
      "mcizrc6",
      "mcizrc7",
      "mhwwctc",
      "mhwwnc1",
      "mhwwnc2",
      "mhwwnc3",
      "mhwwnc4",
      "mhwwnc5",
      "mhwwnc6",
      "mhwwrc1",
      "mhwwrc2",
      "mhwwrc3",
      "mhwwrc4",
      "mhwwrc5",
      "mhwwrc6",
      "mhwwrc7",
      "mwmoctc",
      "mwmonc1",
      "mwmonc2",
      "mwmonc3",
      "mwmonc4",
      "mwmonc5",
      "mwmonc6",
      "mwmorc1",
      "mwmorc2",
      "mwmorc3",
      "mwmorc4",
      "mwmorc5",
      "mwmorc6",
      "mwmorc7",
      "mcizctc",
      "mciznc1",
      "mciznc2",
      "mciznc3",
      "mciznc4",
      "mciznc5",
      "mciznc6",
      "mcizpc1",
      "mcizpc10",
      "mcizpc11",
      "mcizpc2",
      "mcizpc3",
      "mcizpc4",
      "mcizpc5",
      "mcizpc6",
      "mcizpc7",
      "mcizpc8",
      "mcizpc9",
      "mcizrc1",
      "mcizrc2",
      "mcizrc3",
      "mcizrc4",
      "mcizrc5",
      "mcizrc6",
      "mcizrc7",
      "mhwwctc",
      "mhwwnc1",
      "mhwwnc2",
      "mhwwnc3",
      "mhwwnc4",
      "mhwwnc5",
      "mhwwnc6",
      "mhwwpc1",
      "mhwwpc10",
      "mhwwpc11",
      "mhwwpc2",
      "mhwwpc3",
      "mhwwpc4",
      "mhwwpc5",
      "mhwwpc6",
      "mhwwpc7",
      "mhwwpc8",
      "mhwwpc9",
      "mhwwrc1",
      "mhwwrc2",
      "mhwwrc3",
      "mhwwrc4",
      "mhwwrc5",
      "mhwwrc6",
      "mhwwrc7",
      "mwmoctc",
      "mwmonc1",
      "mwmonc2",
      "mwmonc3",
      "mwmonc4",
      "mwmonc5",
      "mwmonc6",
      "mwmopc1",
      "mwmopc10",
      "mwmopc11",
      "mwmopc2",
      "mwmopc3",
      "mwmopc4",
      "mwmopc5",
      "mwmopc6",
      "mwmopc7",
      "mwmopc8",
      "mwmopc9",
      "mwmorc1",
      "mwmorc2",
      "mwmorc3",
      "mwmorc4",
      "mwmorc5",
      "mwmorc6",
      "mwmorc7",
      "mcizctc",
      "mciznc1",
      "mciznc2",
      "mciznc3",
      "mciznc4",
      "mciznc5",
      "mciznc6",
      "mcizpc1",
      "mcizpc10",
      "mcizpc11",
      "mcizpc2",
      "mcizpc3",
      "mcizpc4",
      "mcizpc5",
      "mcizpc6",
      "mcizpc7",
      "mcizpc8",
      "mcizpc9",
      "mcizrc1",
      "mcizrc2",
      "mcizrc3",
      "mcizrc4",
      "mcizrc5",
      "mcizrc6",
      "mcizrc7",
      "mhwwctc",
      "mhwwnc1",
      "mhwwnc2",
      "mhwwnc3",
      "mhwwnc4",
      "mhwwnc5",
      "mhwwnc6",
      "mhwwpc1",
      "mhwwpc10",
      "mhwwpc11",
      "mhwwpc2",
      "mhwwpc3",
      "mhwwpc4",
      "mhwwpc5",
      "mhwwpc6",
      "mhwwpc7",
      "mhwwpc8",
      "mhwwpc9",
      "mhwwrc1",
      "mhwwrc2",
      "mhwwrc3",
      "mhwwrc4",
      "mhwwrc5",
      "mhwwrc6",
      "mhwwrc7",
      "mwmoctc",
      "mwmonc1",
      "mwmonc2",
      "mwmonc3",
      "mwmonc4",
      "mwmonc5",
      "mwmonc6",
      "mwmopc1",
      "mwmopc10",
      "mwmopc11",
      "mwmopc2",
      "mwmopc3",
      "mwmopc4",
      "mwmopc5",
      "mwmopc6",
      "mwmopc7",
      "mwmopc8",
      "mwmopc9",
      "mwmorc1",
      "mwmorc2",
      "mwmorc3",
      "mwmorc4",
      "mwmorc5",
      "mwmorc6",
      "mwmorc7"
    ),
    variable_label = c(
      "application approved",
      "contact with municipality about WMO since Jan 1, 2007",
      "reason no contact: no need",
      "reason no contact: take care of it myself",
      "reason no contact: no knowledge",
      "reason no contact: do not dare, cannot do it",
      "reason no contact: service unreachable",
      "reason no contact: other",
      "reason contact with municipality about WMO",
      "type of application: domestic care",
      "type of application: housing facility",
      "type of application: transportation facility",
      "type of application: wheelchair",
      "type of application: PGB",
      "type of application: support volunteer aid",
      "type of application: other",
      "application approved",
      "contact with municipality about WMO since Jan 1, 2007",
      "reason no contact: no need",
      "reason no contact: take care of it myself",
      "reason no contact: no knowledge",
      "reason no contact: do not dare, cannot do it",
      "reason no contact: service unreachable",
      "reason no contact: other",
      "reason contact information",
      "reason contact application new facility",
      "reason contact re-evaluation dom. care",
      "reason contact extension indication",
      "reason contact complaint",
      "reason contact other",
      "type of application: domestic care",
      "type of application: housing facility",
      "type of application: transportation facility",
      "type of application: wheelchair",
      "type of application: PGB",
      "type of application: support volunteer aid",
      "type of application: other",
      "contact since 2012 with CIZ or social district team about 24 hours care",
      "reason no contact: no need",
      "reason no contact: take care of it myself",
      "reason no contact: no knowledge",
      "reason no contact: do not dare, cannot do it",
      "reason no contact: service unreachable",
      "reason no contact: other",
      "reason contact: information",
      "reason contact: application new facility",
      "reason contact: re-evaluation existing facility",
      "reason contact: extension indication",
      "reason contact: complaint",
      "reason contact: to know where I stand with all the changes in care",
      "reason contact: other",
      "contact since 2012 with general practitioner, district nurse or team about home care or nursing",
      "reason no contact: no need",
      "reason no contact: take care of it myself",
      "reason no contact: no knowledge",
      "reason no contact: do not dare, cannot do it",
      "reason no contact: organisation unreachable",
      "reason no contact: other",
      "reason contact: information",
      "reason contact: application new facility",
      "reason contact: re-evaluation existing facility",
      "reason contact: extension indication",
      "reason contact: complaint",
      "reason contact: to know where I stand with all the changes in care",
      "reason contact: other",
      "contact since 2012 with municipality or WMO about support or facilities",
      "reason no contact: no need",
      "reason no contact: take care of it myself",
      "reason no contact: no knowledge",
      "reason no contact: do not dare, cannot do it",
      "reason no contact: service unreachable",
      "reason no contact: other",
      "reason contact WMO: information",
      "reason contact: application new facility",
      "reason contact: re-evaluation existing facility",
      "reason contact: extension indication",
      "reason contact: complaint",
      "reason contact: to know where I stand with all the changes in care",
      "reason contact: other",
      "contact since 2015 (in K: 2018) with CIZ or social district team about 24 hours care",
      "reason no contact CIZ: no need",
      "reason no contact CIZ: take care of it myself",
      "reason no contact CIZ: no knowledge",
      "reason no contact CIZ: do not dare, cannot do it",
      "reason no contact CIZ: service unreachable",
      "reason no contact CIZ: other",
      "person who contacted CIZ: respondent",
      "person who contacted CIZ: volunteer",
      "person who contacted CIZ: other",
      "person who contacted CIZ: partner of respondent",
      "person who contacted CIZ: child (in law)",
      "person who contacted CIZ: other family",
      "person who contacted CIZ: neighbour",
      "person who contacted CIZ: friend/acquaintance",
      "person who contacted CIZ: general practitioner",
      "person who contacted CIZ: district nurse",
      "person who contacted CIZ: household assistant",
      "reason contact CIZ: information",
      "reason contact CIZ: application new facility",
      "reason contact CIZ: re-evaluation existing facility",
      "reason contact CIZ: extension indication",
      "reason contact CIZ: complaint",
      "reason contact CIZ: to know where I stand with all the changes in care",
      "reason contact CIZ: other",
      "contact since 2015 (in K: 2018) with general practitioner, district nurse or team about home care or nursing",
      "reason no contact GP/nurse: no need",
      "reason no contact GP/nurse: take care of it myself",
      "reason no contact GP/nurse: no knowledge",
      "reason no contact GP/nurse: do not dare, cannot do it",
      "reason no contact GP/nurse: organisation unreachable",
      "reason no contact GP/nurse: other",
      "person who contacted GP/nurse: respondent",
      "person who contacted GP/nurse: volunteer",
      "person who contacted GP/nurse: other",
      "person who contacted GP/nurse: partner of respondent",
      "person who contacted GP/nurse: child (in law)",
      "person who contacted GP/nurse: other family",
      "person who contacted GP/nurse: neighbour",
      "person who contacted GP/nurse: friend/acquaintance",
      "person who contacted GP/nurse: general practitioner",
      "person who contacted GP/nurse: district nurse",
      "person who contacted GP/nurse: household assistant",
      "reason contact GP/nurse: information",
      "reason contact GP/nurse: application new facility",
      "reason contact GP/nurse: re-evaluation existing facility",
      "reason contact GP/nurse: extension indication",
      "reason contact GP/nurse: complaint",
      "reason contact GP/nurse: to know where I stand with all the changes in care",
      "reason contact GP/nurse: other",
      "contact since 2015 (in K: 2018) with municipality or WMO about support or facilities",
      "reason no contact WMO: no need",
      "reason no contact WMO: take care of it myself",
      "reason no contact WMO: no knowledge",
      "reason no contact WMO: do not dare, cannot do it",
      "reason no contact WMO : service unreachable",
      "reason no contact WMO: other",
      "person who contacted WMO: respondent",
      "person who contacted WMO: volunteer",
      "person who contacted WMO: other",
      "person who contacted WMO: partner of respondent",
      "person who contacted WMO: child (in law)",
      "person who contacted WMO: other family",
      "person who contacted WMO: neighbour",
      "person who contacted WMO: friend/acquaintance",
      "person who contacted WMO: general practitioner",
      "person who contacted WMO: district nurse",
      "person who contacted WMO: household assistant",
      "reason contact WMO: information",
      "reason contact WMO: application new facility",
      "reason contact WMO: re-evaluation existing facility",
      "reason contact WMO: extension indication",
      "reason contact WMO: complaint",
      "reason contact WMO: to know where I stand with all the changes in care",
      "reason contact WMO: other",
      "contact since 2015 (in K: 2018) with CIZ or social district team about 24 hours care",
      "reason no contact CIZ: no need",
      "reason no contact CIZ: take care of it myself",
      "reason no contact CIZ: no knowledge",
      "reason no contact CIZ: do not dare, cannot do it",
      "reason no contact CIZ: service unreachable",
      "reason no contact CIZ: other",
      "person who contacted CIZ: respondent",
      "person who contacted CIZ: volunteer",
      "person who contacted CIZ: other",
      "person who contacted CIZ: partner of respondent",
      "person who contacted CIZ: child (in law)",
      "person who contacted CIZ: other family",
      "person who contacted CIZ: neighbour",
      "person who contacted CIZ: friend/acquaintance",
      "person who contacted CIZ: general practitioner",
      "person who contacted CIZ: district nurse",
      "person who contacted CIZ: household assistant",
      "reason contact CIZ: information",
      "reason contact CIZ: application new facility",
      "reason contact CIZ: re-evaluation existing facility",
      "reason contact CIZ: extension indication",
      "reason contact CIZ: complaint",
      "reason contact CIZ: to know where I stand with all the changes in care",
      "reason contact CIZ: other",
      "contact since 2015 (in K: 2018) with general practitioner, district nurse or team about home care or nursing",
      "reason no contact GP/nurse: no need",
      "reason no contact GP/nurse: take care of it myself",
      "reason no contact GP/nurse: no knowledge",
      "reason no contact GP/nurse: do not dare, cannot do it",
      "reason no contact GP/nurse: organisation unreachable",
      "reason no contact GP/nurse: other",
      "person who contacted GP/nurse: respondent",
      "person who contacted GP/nurse: volunteer",
      "person who contacted GP/nurse: other",
      "person who contacted GP/nurse: partner of respondent",
      "person who contacted GP/nurse: child (in law)",
      "person who contacted GP/nurse: other family",
      "person who contacted GP/nurse: neighbour",
      "person who contacted GP/nurse: friend/acquaintance",
      "person who contacted GP/nurse: general practitioner",
      "person who contacted GP/nurse: district nurse",
      "person who contacted GP/nurse: household assistant",
      "reason contact GP/nurse: information",
      "reason contact GP/nurse: application new facility",
      "reason contact GP/nurse: re-evaluation existing facility",
      "reason contact GP/nurse: extension indication",
      "reason contact GP/nurse: complaint",
      "reason contact GP/nurse: to know where I stand with all the changes in care",
      "reason contact GP/nurse: other",
      "contact since 2015 (in K: 2018) with municipality or WMO about support or facilities",
      "reason no contact WMO: no need",
      "reason no contact WMO: take care of it myself",
      "reason no contact WMO: no knowledge",
      "reason no contact WMO: do not dare, cannot do it",
      "reason no contact WMO : service unreachable",
      "reason no contact WMO: other",
      "person who contacted WMO: respondent",
      "person who contacted WMO: volunteer",
      "person who contacted WMO: other",
      "person who contacted WMO: partner of respondent",
      "person who contacted WMO: child (in law)",
      "person who contacted WMO: other family",
      "person who contacted WMO: neighbour",
      "person who contacted WMO: friend/acquaintance",
      "person who contacted WMO: general practitioner",
      "person who contacted WMO: district nurse",
      "person who contacted WMO: household assistant",
      "reason contact WMO: information",
      "reason contact WMO: application new facility",
      "reason contact WMO: re-evaluation existing facility",
      "reason contact WMO: extension indication",
      "reason contact WMO: complaint",
      "reason contact WMO: to know where I stand with all the changes in care",
      "reason contact WMO: other"
    ),
    harmonized_var_label = c(
      "application approved",
      "Contact with municipality/WMO about support or facilities",
      "reason no contact: no need",
      "reason no contact: take care of it myself",
      "reason no contact: no knowledge",
      "reason no contact: do not dare, cannot do it",
      "reason no contact: service unreachable",
      "reason no contact: other",
      "reason contact with municipality about WMO",
      "type of application: domestic care",
      "type of application: housing facility",
      "type of application: transportation facility",
      "type of application: wheelchair",
      "type of application: PGB",
      "type of application: support volunteer aid",
      "type of application: other",
      "application approved",
      "Contact with municipality/WMO about support or facilities",
      "reason no contact: no need",
      "reason no contact: take care of it myself",
      "reason no contact: no knowledge",
      "reason no contact: do not dare, cannot do it",
      "reason no contact: service unreachable",
      "reason no contact: other",
      "reason contact WMO: information",
      "reason contact WMO: application new facility",
      "reason contact WMO: re-evaluation existing facility",
      "reason contact WMO: extension indication",
      "reason contact WMO: complaint",
      "reason contact WMO: to know where I stand with all the changes in care",
      "type of application: domestic care",
      "type of application: housing facility",
      "type of application: transportation facility",
      "type of application: wheelchair",
      "type of application: PGB",
      "type of application: support volunteer aid",
      "type of application: other",
      "contact since 2015 (in K: 2018) with CIZ or social district team about 24 hours care",
      "reason no contact CIZ: no need",
      "reason no contact CIZ: take care of it myself",
      "reason no contact CIZ: no knowledge",
      "reason no contact CIZ: do not dare, cannot do it",
      "reason no contact CIZ: service unreachable",
      "reason no contact CIZ: other",
      "reason contact CIZ: information",
      "reason contact CIZ: application new facility",
      "reason contact CIZ: re-evaluation existing facility",
      "reason contact CIZ: extension indication",
      "reason contact CIZ: complaint",
      "reason contact CIZ: to know where I stand with all the changes in care",
      "reason contact CIZ: other",
      "contact since 2015 (in K: 2018) with general practitioner, district nurse or team about home care or nursing",
      "reason no contact GP/nurse: no need",
      "reason no contact GP/nurse: take care of it myself",
      "reason no contact GP/nurse: no knowledge",
      "reason no contact GP/nurse: do not dare, cannot do it",
      "reason no contact GP/nurse: organisation unreachable",
      "reason no contact GP/nurse: other",
      "reason contact: information",
      "reason contact: application new facility",
      "reason contact: re-evaluation existing facility",
      "reason contact: extension indication",
      "reason contact: complaint",
      "reason contact: to know where I stand with all the changes in care",
      "reason contact: other",
      "Contact with municipality/WMO about support or facilities",
      "reason no contact: no need",
      "reason no contact: take care of it myself",
      "reason no contact: no knowledge",
      "reason no contact: do not dare, cannot do it",
      "reason no contact: service unreachable",
      "reason no contact: other",
      "reason contact WMO: information",
      "reason contact WMO: application new facility",
      "reason contact WMO: re-evaluation existing facility",
      "reason contact WMO: extension indication",
      "reason contact WMO: complaint",
      "reason contact WMO: to know where I stand with all the changes in care",
      "reason contact WMO: other",
      "contact since 2015 (in K: 2018) with CIZ or social district team about 24 hours care",
      "reason no contact CIZ: no need",
      "reason no contact CIZ: take care of it myself",
      "reason no contact CIZ: no knowledge",
      "reason no contact CIZ: do not dare, cannot do it",
      "reason no contact CIZ: service unreachable",
      "reason no contact CIZ: other",
      "person who contacted CIZ: respondent",
      "person who contacted CIZ: volunteer",
      "person who contacted CIZ: other",
      "person who contacted CIZ: partner of respondent",
      "person who contacted CIZ: child (in law)",
      "person who contacted CIZ: other family",
      "person who contacted CIZ: neighbour",
      "person who contacted CIZ: friend/acquaintance",
      "person who contacted CIZ: general practitioner",
      "person who contacted CIZ: district nurse",
      "person who contacted CIZ: household assistant",
      "reason contact CIZ: information",
      "reason contact CIZ: application new facility",
      "reason contact CIZ: re-evaluation existing facility",
      "reason contact CIZ: extension indication",
      "reason contact CIZ: complaint",
      "reason contact CIZ: to know where I stand with all the changes in care",
      "reason contact CIZ: other",
      "contact since 2015 (in K: 2018) with general practitioner, district nurse or team about home care or nursing",
      "reason no contact GP/nurse: no need",
      "reason no contact GP/nurse: take care of it myself",
      "reason no contact GP/nurse: no knowledge",
      "reason no contact GP/nurse: do not dare, cannot do it",
      "reason no contact GP/nurse: organisation unreachable",
      "reason no contact GP/nurse: other",
      "person who contacted GP/nurse: respondent",
      "person who contacted GP/nurse: volunteer",
      "person who contacted GP/nurse: other",
      "person who contacted GP/nurse: partner of respondent",
      "person who contacted GP/nurse: child (in law)",
      "person who contacted GP/nurse: other family",
      "person who contacted GP/nurse: neighbour",
      "person who contacted GP/nurse: friend/acquaintance",
      "person who contacted GP/nurse: general practitioner",
      "person who contacted GP/nurse: district nurse",
      "person who contacted GP/nurse: household assistant",
      "reason contact: information",
      "reason contact: application new facility",
      "reason contact: re-evaluation existing facility",
      "reason contact: extension indication",
      "reason contact: complaint",
      "reason contact: to know where I stand with all the changes in care",
      "reason contact: other",
      "Contact with municipality/WMO about support or facilities",
      "reason no contact: no need",
      "reason no contact: take care of it myself",
      "reason no contact: no knowledge",
      "reason no contact: do not dare, cannot do it",
      "reason no contact: service unreachable",
      "reason no contact: other",
      "person who contacted WMO: respondent",
      "person who contacted WMO: volunteer",
      "person who contacted WMO: other",
      "person who contacted WMO: partner of respondent",
      "person who contacted WMO: child (in law)",
      "person who contacted WMO: other family",
      "person who contacted WMO: neighbour",
      "person who contacted WMO: friend/acquaintance",
      "person who contacted WMO: general practitioner",
      "person who contacted WMO: district nurse",
      "person who contacted WMO: household assistant",
      "reason contact WMO: information",
      "reason contact WMO: application new facility",
      "reason contact WMO: re-evaluation existing facility",
      "reason contact WMO: extension indication",
      "reason contact WMO: complaint",
      "reason contact WMO: to know where I stand with all the changes in care",
      "reason contact WMO: other",
      "contact since 2015 (in K: 2018) with CIZ or social district team about 24 hours care",
      "reason no contact CIZ: no need",
      "reason no contact CIZ: take care of it myself",
      "reason no contact CIZ: no knowledge",
      "reason no contact CIZ: do not dare, cannot do it",
      "reason no contact CIZ: service unreachable",
      "reason no contact CIZ: other",
      "person who contacted CIZ: respondent",
      "person who contacted CIZ: volunteer",
      "person who contacted CIZ: other",
      "person who contacted CIZ: partner of respondent",
      "person who contacted CIZ: child (in law)",
      "person who contacted CIZ: other family",
      "person who contacted CIZ: neighbour",
      "person who contacted CIZ: friend/acquaintance",
      "person who contacted CIZ: general practitioner",
      "person who contacted CIZ: district nurse",
      "person who contacted CIZ: household assistant",
      "reason contact CIZ: information",
      "reason contact CIZ: application new facility",
      "reason contact CIZ: re-evaluation existing facility",
      "reason contact CIZ: extension indication",
      "reason contact CIZ: complaint",
      "reason contact CIZ: to know where I stand with all the changes in care",
      "reason contact CIZ: other",
      "contact since 2015 (in K: 2018) with general practitioner, district nurse or team about home care or nursing",
      "reason no contact GP/nurse: no need",
      "reason no contact GP/nurse: take care of it myself",
      "reason no contact GP/nurse: no knowledge",
      "reason no contact GP/nurse: do not dare, cannot do it",
      "reason no contact GP/nurse: organisation unreachable",
      "reason no contact GP/nurse: other",
      "person who contacted GP/nurse: respondent",
      "person who contacted GP/nurse: volunteer",
      "person who contacted GP/nurse: other",
      "person who contacted GP/nurse: partner of respondent",
      "person who contacted GP/nurse: child (in law)",
      "person who contacted GP/nurse: other family",
      "person who contacted GP/nurse: neighbour",
      "person who contacted GP/nurse: friend/acquaintance",
      "person who contacted GP/nurse: general practitioner",
      "person who contacted GP/nurse: district nurse",
      "person who contacted GP/nurse: household assistant",
      "reason contact: information",
      "reason contact: application new facility",
      "reason contact: re-evaluation existing facility",
      "reason contact: extension indication",
      "reason contact: complaint",
      "reason contact: to know where I stand with all the changes in care",
      "reason contact: other",
      "Contact with municipality/WMO about support or facilities",
      "reason no contact: no need",
      "reason no contact: take care of it myself",
      "reason no contact: no knowledge",
      "reason no contact: do not dare, cannot do it",
      "reason no contact: service unreachable",
      "reason no contact: other",
      "person who contacted WMO: respondent",
      "person who contacted WMO: volunteer",
      "person who contacted WMO: other",
      "person who contacted WMO: partner of respondent",
      "person who contacted WMO: child (in law)",
      "person who contacted WMO: other family",
      "person who contacted WMO: neighbour",
      "person who contacted WMO: friend/acquaintance",
      "person who contacted WMO: general practitioner",
      "person who contacted WMO: district nurse",
      "person who contacted WMO: household assistant",
      "reason contact WMO: information",
      "reason contact WMO: application new facility",
      "reason contact WMO: re-evaluation existing facility",
      "reason contact WMO: extension indication",
      "reason contact WMO: complaint",
      "reason contact WMO: to know where I stand with all the changes in care",
      "reason contact WMO: other"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mwmoapp = list(
      G = yes_approved_no_denied_informal_network,
      H = yes_approved_no_denied_informal_network
    ),
    mwmoctc = list(
      G = no_yes_143,
      H = no_yes_143,
      I = no_yes_143,
      J = no_yes_68,
      K = no_yes_68
    ),
    mwmonc1 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmonc2 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmonc3 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmonc4 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmonc5 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmonc6 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmorc = list(
      G = obtain_information_application_for_a_new_facility
    ),
    mwmota1 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35
    ),
    mwmota2 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35
    ),
    mwmota3 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35
    ),
    mwmota4 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35
    ),
    mwmota5 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35
    ),
    mwmota6 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35
    ),
    mwmota7 = list(
      G = not_mentioned_mentioned_35,
      H = not_mentioned_mentioned_35
    ),
    mwmorc1 = list(
      H = not_mentioned_mentioned_219,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmorc2 = list(
      H = not_mentioned_mentioned_219,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmorc3 = list(
      H = not_mentioned_mentioned_219,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmorc4 = list(
      H = not_mentioned_mentioned_219,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmorc5 = list(
      H = not_mentioned_mentioned_219,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmorc6 = list(
      H = not_mentioned_mentioned_219,
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mcizctc = list(
      I = no_yes_143,
      J = no_yes_68,
      K = no_yes_68
    ),
    mciznc1 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mciznc2 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mciznc3 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mciznc4 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mciznc5 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mciznc6 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizrc1 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizrc2 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizrc3 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizrc4 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizrc5 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizrc6 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizrc7 = list(
      I = not_mentioned_mentioned_58,
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mhwwctc = list(
      I = no_yes_143,
      J = no_yes_68,
      K = no_yes_68
    ),
    mhwwnc1 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwnc2 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwnc3 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwnc4 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwnc5 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwnc6 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwrc1 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwrc2 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwrc3 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwrc4 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwrc5 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwrc6 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwrc7 = list(
      I = not_mentioned_mentioned_59,
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mwmorc7 = list(
      I = not_mentioned_mentioned_82,
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mcizpc1 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizpc10 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizpc11 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizpc2 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizpc3 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizpc4 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizpc5 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizpc6 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizpc7 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizpc8 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mcizpc9 = list(
      J = not_mentioned_mentioned_11,
      K = not_mentioned_mentioned_11
    ),
    mhwwpc1 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwpc10 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwpc11 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwpc2 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwpc3 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwpc4 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwpc5 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwpc6 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwpc7 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwpc8 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mhwwpc9 = list(
      J = not_mentioned_mentioned_12,
      K = not_mentioned_mentioned_12
    ),
    mwmopc1 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmopc10 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmopc11 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmopc2 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmopc3 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmopc4 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmopc5 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmopc6 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmopc7 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmopc8 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    ),
    mwmopc9 = list(
      J = not_mentioned_mentioned_10,
      K = not_mentioned_mentioned_10
    )
  ),

  value_labels_harmonized = list(
    mcizctc = no_yes_68,
    mciznc1 = not_mentioned_mentioned_58,
    mciznc2 = not_mentioned_mentioned_58,
    mciznc3 = not_mentioned_mentioned_58,
    mciznc4 = not_mentioned_mentioned_58,
    mciznc5 = not_mentioned_mentioned_58,
    mciznc6 = not_mentioned_mentioned_58,
    mcizpc1 = not_mentioned_mentioned_11,
    mcizpc10 = not_mentioned_mentioned_11,
    mcizpc11 = not_mentioned_mentioned_11,
    mcizpc2 = not_mentioned_mentioned_11,
    mcizpc3 = not_mentioned_mentioned_11,
    mcizpc4 = not_mentioned_mentioned_11,
    mcizpc5 = not_mentioned_mentioned_11,
    mcizpc6 = not_mentioned_mentioned_11,
    mcizpc7 = not_mentioned_mentioned_11,
    mcizpc8 = not_mentioned_mentioned_11,
    mcizpc9 = not_mentioned_mentioned_11,
    mcizrc1 = not_mentioned_mentioned_58,
    mcizrc2 = not_mentioned_mentioned_58,
    mcizrc3 = not_mentioned_mentioned_58,
    mcizrc4 = not_mentioned_mentioned_58,
    mcizrc5 = not_mentioned_mentioned_58,
    mcizrc6 = not_mentioned_mentioned_58,
    mcizrc7 = not_mentioned_mentioned_58,
    mhwwctc = no_yes_68,
    mhwwnc1 = not_mentioned_mentioned_59,
    mhwwnc2 = not_mentioned_mentioned_59,
    mhwwnc3 = not_mentioned_mentioned_59,
    mhwwnc4 = not_mentioned_mentioned_59,
    mhwwnc5 = not_mentioned_mentioned_59,
    mhwwnc6 = not_mentioned_mentioned_59,
    mhwwpc1 = not_mentioned_mentioned_12,
    mhwwpc10 = not_mentioned_mentioned_12,
    mhwwpc11 = not_mentioned_mentioned_12,
    mhwwpc2 = not_mentioned_mentioned_12,
    mhwwpc3 = not_mentioned_mentioned_12,
    mhwwpc4 = not_mentioned_mentioned_12,
    mhwwpc5 = not_mentioned_mentioned_12,
    mhwwpc6 = not_mentioned_mentioned_12,
    mhwwpc7 = not_mentioned_mentioned_12,
    mhwwpc8 = not_mentioned_mentioned_12,
    mhwwpc9 = not_mentioned_mentioned_12,
    mhwwrc1 = not_mentioned_mentioned_59,
    mhwwrc2 = not_mentioned_mentioned_59,
    mhwwrc3 = not_mentioned_mentioned_59,
    mhwwrc4 = not_mentioned_mentioned_59,
    mhwwrc5 = not_mentioned_mentioned_59,
    mhwwrc6 = not_mentioned_mentioned_59,
    mhwwrc7 = not_mentioned_mentioned_59,
    mwmoapp = yes_approved_no_denied_informal_network,
    mwmoctc = no_yes_68,
    mwmonc1 = not_mentioned_mentioned_82,
    mwmonc2 = not_mentioned_mentioned_82,
    mwmonc3 = not_mentioned_mentioned_82,
    mwmonc4 = not_mentioned_mentioned_82,
    mwmonc5 = not_mentioned_mentioned_82,
    mwmonc6 = not_mentioned_mentioned_82,
    mwmopc1 = not_mentioned_mentioned_10,
    mwmopc10 = not_mentioned_mentioned_10,
    mwmopc11 = not_mentioned_mentioned_10,
    mwmopc2 = not_mentioned_mentioned_10,
    mwmopc3 = not_mentioned_mentioned_10,
    mwmopc4 = not_mentioned_mentioned_10,
    mwmopc5 = not_mentioned_mentioned_10,
    mwmopc6 = not_mentioned_mentioned_10,
    mwmopc7 = not_mentioned_mentioned_10,
    mwmopc8 = not_mentioned_mentioned_10,
    mwmopc9 = not_mentioned_mentioned_10,
    mwmorc = obtain_information_application_for_a_new_facility,
    mwmorc1 = not_mentioned_mentioned_220,
    mwmorc2 = not_mentioned_mentioned_220,
    mwmorc3 = not_mentioned_mentioned_220,
    mwmorc4 = not_mentioned_mentioned_220,
    mwmorc5 = not_mentioned_mentioned_220,
    mwmorc6 = not_mentioned_mentioned_220,
    mwmorc7 = not_mentioned_mentioned_82,
    mwmota1 = not_mentioned_mentioned_35,
    mwmota2 = not_mentioned_mentioned_35,
    mwmota3 = not_mentioned_mentioned_35,
    mwmota4 = not_mentioned_mentioned_35,
    mwmota5 = not_mentioned_mentioned_35,
    mwmota6 = not_mentioned_mentioned_35,
    mwmota7 = not_mentioned_mentioned_35
  )
)
