## LASA filecode 125 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_125 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G"
    ),
    variable_name = c(
      "bqsocp04",
      "bqsocp05",
      "bqsocp06",
      "bqsocp07",
      "bqsocp08",
      "bqsocp09",
      "bqsocp10",
      "bqsocp11",
      "bqsocp12",
      "bqsocp13",
      "bqsocp14",
      "bqsocp15",
      "bqsocp16",
      "bqsocp17",
      "bqsocp18",
      "bqsocp19",
      "bqsocp20",
      "bqsocp21",
      "bqsocp04",
      "bqsocp05",
      "bqsocp06",
      "bqsocp07",
      "bqsocp08",
      "bqsocp09",
      "bqsocp10",
      "bqsocp11",
      "bqsocp12",
      "bqsocp13",
      "bqsocp14",
      "bqsocp15",
      "bqsocp16",
      "bqsocp17",
      "bqsocp18",
      "bqsocp19",
      "bqsocp20",
      "bqsocp21",
      "bqsocp22",
      "bqsocp23",
      "bqsocp24",
      "bqsocp25",
      "bqsocp26",
      "bqsocp27",
      "cqsocp07",
      "cqsocp08",
      "cqsocp09",
      "cqsocp10",
      "cqsocp11",
      "cqsocp12",
      "cqsocp14",
      "cqsocp15",
      "cqsocp16",
      "cqsocp17",
      "cqsocp18",
      "cqsocp19",
      "cqsocp21",
      "dqsocp07",
      "dqsocp08",
      "dqsocp09",
      "dqsocp10",
      "dqsocp11",
      "dqsocp12",
      "dqsocp14",
      "dqsocp15",
      "dqsocp16",
      "dqsocp17",
      "dqsocp18",
      "dqsocp19",
      "dqsocp20",
      "dqsocp21",
      "eqsocp07",
      "eqsocp08",
      "eqsocp09",
      "eqsocp10",
      "eqsocp11",
      "eqsocp12",
      "eqsocp14",
      "eqsocp15",
      "eqsocp16",
      "eqsocp17",
      "eqsocp18",
      "eqsocp19",
      "eqsocp20",
      "eqsocp21",
      "fqsocp07",
      "fqsocp08",
      "fqsocp09",
      "fqsocp10",
      "fqsocp11",
      "fqsocp12",
      "fqsocp14",
      "fqsocp15",
      "fqsocp16",
      "fqsocp17",
      "fqsocp18",
      "fqsocp19",
      "fqsocp20",
      "fqsocp21",
      "gqsocp07",
      "gqsocp08",
      "gqsocp09",
      "gqsocp10",
      "gqsocp11",
      "gqsocp12",
      "gqsocp14",
      "gqsocp15",
      "gqsocp16",
      "gqsocp17",
      "gqsocp18",
      "gqsocp19",
      "gqsocp20",
      "gqsocp20b",
      "gqsocp21"
    ),
    canonical_name = c(
      "qsocp04",
      "qsocp05",
      "qsocp06",
      "qsocp07",
      "qsocp08",
      "qsocp09",
      "qsocp10",
      "qsocp11",
      "qsocp12",
      "qsocp13",
      "qsocp14",
      "qsocp15",
      "qsocp16",
      "qsocp17",
      "qsocp18",
      "qsocp19",
      "qsocp20",
      "qsocp21",
      "qsocp04",
      "qsocp05",
      "qsocp06",
      "qsocp07",
      "qsocp08",
      "qsocp09",
      "qsocp10",
      "qsocp11",
      "qsocp12",
      "qsocp13",
      "qsocp14",
      "qsocp15",
      "qsocp16",
      "qsocp17",
      "qsocp18",
      "qsocp19",
      "qsocp20",
      "qsocp21",
      "qsocp22",
      "qsocp23",
      "qsocp24",
      "qsocp25",
      "qsocp26",
      "qsocp27",
      "qsocp07",
      "qsocp08",
      "qsocp09",
      "qsocp10",
      "qsocp11",
      "qsocp12",
      "qsocp14",
      "qsocp15",
      "qsocp16",
      "qsocp17",
      "qsocp18",
      "qsocp19",
      "qsocp21",
      "qsocp07",
      "qsocp08",
      "qsocp09",
      "qsocp10",
      "qsocp11",
      "qsocp12",
      "qsocp14",
      "qsocp15",
      "qsocp16",
      "qsocp17",
      "qsocp18",
      "qsocp19",
      "qsocp20",
      "qsocp21",
      "qsocp07",
      "qsocp08",
      "qsocp09",
      "qsocp10",
      "qsocp11",
      "qsocp12",
      "qsocp14",
      "qsocp15",
      "qsocp16",
      "qsocp17",
      "qsocp18",
      "qsocp19",
      "qsocp20",
      "qsocp21",
      "qsocp07",
      "qsocp08",
      "qsocp09",
      "qsocp10",
      "qsocp11",
      "qsocp12",
      "qsocp14",
      "qsocp15",
      "qsocp16",
      "qsocp17",
      "qsocp18",
      "qsocp19",
      "qsocp20",
      "qsocp21",
      "qsocp07",
      "qsocp08",
      "qsocp09",
      "qsocp10",
      "qsocp11",
      "qsocp12",
      "qsocp14",
      "qsocp15",
      "qsocp16",
      "qsocp17",
      "qsocp18",
      "qsocp19",
      "qsocp20",
      "qsocp20b",
      "qsocp21"
    ),
    variable_label = c(
      "possession senior card (65+/60+)",
      "usage senior card",
      "listening to the radio: hours a day",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "watching television: hours a day",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/soaps",
      "reading newspapers",
      "possession senior card (65+/60+)",
      "usage senior card",
      "listening to the radio: hours a day",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "watching television: hours a day",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/soaps",
      "reading newspapers",
      "involved: world",
      "involved: europe",
      "involved: dutch society",
      "involved: province",
      "involved: municipality",
      "involved: neighborhood",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "reading newspapers",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/soaps",
      "reading newspapers",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/soaps",
      "reading newspapers",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/tv series",
      "reading newspapers",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/tv series",
      "tv: reality programmes",
      "reading newspapers"
    ),
    harmonized_var_label = c(
      "possession senior card (65+/60+)",
      "usage senior card",
      "listening to the radio: hours a day",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "watching television: hours a day",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/soaps",
      "reading newspapers",
      "possession senior card (65+/60+)",
      "usage senior card",
      "listening to the radio: hours a day",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "watching television: hours a day",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/soaps",
      "reading newspapers",
      "involved: world",
      "involved: europe",
      "involved: dutch society",
      "involved: province",
      "involved: municipality",
      "involved: neighborhood",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "reading newspapers",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/soaps",
      "reading newspapers",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/soaps",
      "reading newspapers",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/soaps",
      "reading newspapers",
      "radio: news",
      "radio: commentaries",
      "radio: religious services",
      "radio: music",
      "radio: sport",
      "radio: quiz/games",
      "tv: news",
      "tv: commentaries",
      "tv: religious services",
      "tv: music",
      "tv: sport",
      "tv: quiz/games",
      "tv: films/soaps",
      "tv: reality programmes",
      "reading newspapers"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qsocp04 = list(
      `2B` = yes_no_r_thinks_not_yet_applicable,
      B = yes_no_r_thinks_not_yet_applicable
    ),
    qsocp05 = list(
      `2B` = almost_never_a_few_times_a_year_once_a_month,
      B = almost_never_a_few_times_a_year_once_a_month
    ),
    qsocp06 = list(
      `2B` = no_answer,
      B = no_answer
    ),
    qsocp07 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp08 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp09 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp10 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp11 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp12 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp13 = list(
      `2B` = no_answer,
      B = no_answer
    ),
    qsocp14 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp15 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp16 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp17 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp18 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp19 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      C = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp20 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = very_often_often_some_of_the_time_never,
      D = very_often_often_some_of_the_time_never,
      E = very_often_often_some_of_the_time_never,
      F = very_often_often_some_of_the_time_never,
      G = very_often_often_some_of_the_time_never
    ),
    qsocp21 = list(
      `2B` = very_often_often_some_of_the_time_never,
      B = every_day_4_5_times_a_week_2_3_times_a_week,
      C = every_day_4_5_times_a_week_2_3_times_a_week,
      D = every_day_4_5_times_a_week_2_3_times_a_week,
      E = every_day_4_5_times_a_week_2_3_times_a_week,
      F = every_day_4_5_times_a_week_2_3_times_a_week,
      G = every_day_4_5_times_a_week_2_3_times_a_week
    ),
    qsocp22 = list(
      B = not_at_all_involved_not_involved_involved
    ),
    qsocp23 = list(
      B = not_at_all_involved_not_involved_involved
    ),
    qsocp24 = list(
      B = not_at_all_involved_not_involved_involved
    ),
    qsocp25 = list(
      B = not_at_all_involved_not_involved_involved
    ),
    qsocp26 = list(
      B = not_at_all_involved_not_involved_involved
    ),
    qsocp27 = list(
      B = not_at_all_involved_not_involved_involved
    ),
    qsocp20b = list(
      G = very_often_often_some_of_the_time_never
    )
  ),

  value_labels_harmonized = list(
    qsocp04 = c(
      `-2` = "not available, routing",
      `-1` = "not available",
      `1` = "yes",
      `2` = "no",
      `3` = "R thinks not yet applicable"
    ),
    qsocp05 = c(
      `-2` = "not available, routing",
      `-1` = "not available",
      `1` = "almost never",
      `2` = "a few times a year",
      `3` = "once a month",
      `4` = "a few times a month",
      `5` = "once a week",
      `6` = "a few times a week",
      `7` = "every day"
    ),
    qsocp06 = not_available,
    qsocp07 = very_often_often_some_of_the_time_never_2,
    qsocp08 = very_often_often_some_of_the_time_never_2,
    qsocp09 = very_often_often_some_of_the_time_never_2,
    qsocp10 = very_often_often_some_of_the_time_never_2,
    qsocp11 = very_often_often_some_of_the_time_never_2,
    qsocp12 = very_often_often_some_of_the_time_never_2,
    qsocp13 = not_available,
    qsocp14 = very_often_often_some_of_the_time_never_2,
    qsocp15 = very_often_often_some_of_the_time_never_2,
    qsocp16 = very_often_often_some_of_the_time_never_2,
    qsocp17 = very_often_often_some_of_the_time_never_2,
    qsocp18 = very_often_often_some_of_the_time_never_2,
    qsocp19 = very_often_often_some_of_the_time_never_2,
    qsocp20 = very_often_often_some_of_the_time_never_2,
    qsocp20b = very_often_often_some_of_the_time_never_2,
    qsocp21 = c(
      `-1` = "not available",
      `1` = "coding category 1",
      `2` = "coding category 2",
      `3` = "coding category 3",
      `4` = "coding category 4",
      `5` = "never"
    ),
    qsocp22 = not_at_all_involved_not_involved_involved_2,
    qsocp23 = not_at_all_involved_not_involved_involved_2,
    qsocp24 = not_at_all_involved_not_involved_involved_2,
    qsocp25 = not_at_all_involved_not_involved_involved_2,
    qsocp26 = not_at_all_involved_not_involved_involved_2,
    qsocp27 = not_at_all_involved_not_involved_involved_2
  )
)
