## LASA filecode 133 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_133 <- list(
  variables = data.frame(
    wave = c(
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bquli01",
      "bquli02",
      "bquli03",
      "bquli04",
      "bquli05",
      "bquli06",
      "bquli07",
      "bquli08",
      "bquli09",
      "bquli10",
      "bquli11",
      "bquli12",
      "dquli01",
      "dquli02",
      "dquli03",
      "dquli04",
      "dquli05",
      "dquli06",
      "dquli07",
      "dquli08",
      "dquli09",
      "dquli10",
      "dquli11",
      "dquli12",
      "equli01",
      "equli02",
      "equli03",
      "equli04",
      "equli05",
      "equli06",
      "equli07",
      "equli08",
      "equli09",
      "equli10",
      "equli11",
      "equli12",
      "fquli01",
      "fquli02",
      "fquli03",
      "fquli04",
      "fquli05",
      "fquli06",
      "fquli07",
      "fquli08",
      "fquli09",
      "fquli10",
      "fquli11",
      "fquli12",
      "gquli01",
      "gquli02",
      "gquli03",
      "gquli04",
      "gquli05",
      "gquli06",
      "gquli07",
      "gquli08",
      "gquli09",
      "gquli10",
      "gquli11",
      "gquli12",
      "hquli01",
      "hquli02",
      "hquli03",
      "hquli04",
      "hquli05",
      "hquli06",
      "hquli07",
      "hquli08",
      "hquli09",
      "hquli10",
      "hquli11",
      "hquli12",
      "iquli01",
      "iquli02",
      "iquli03",
      "iquli04",
      "iquli05",
      "iquli06",
      "iquli07",
      "iquli08",
      "iquli09",
      "iquli10",
      "iquli11",
      "iquli12",
      "iquli13",
      "iquli14",
      "jquli01",
      "jquli02",
      "jquli03",
      "jquli04",
      "jquli05",
      "jquli06",
      "jquli07",
      "jquli08",
      "jquli09",
      "jquli10",
      "jquli11",
      "jquli12",
      "jquli13",
      "jquli14",
      "kquli01",
      "kquli02",
      "kquli03",
      "kquli04",
      "kquli05",
      "kquli06",
      "kquli07",
      "kquli08",
      "kquli09",
      "kquli10",
      "kquli11",
      "kquli12",
      "kquli13",
      "kquli14"
    ),
    canonical_name = c(
      "quli01",
      "quli02",
      "quli03",
      "quli04",
      "quli05",
      "quli06",
      "quli07",
      "quli08",
      "quli09",
      "quli10",
      "quli11",
      "quli12",
      "quli01",
      "quli02",
      "quli03",
      "quli04",
      "quli05",
      "quli06",
      "quli07",
      "quli08",
      "quli09",
      "quli10",
      "quli11",
      "quli12",
      "quli01",
      "quli02",
      "quli03",
      "quli04",
      "quli05",
      "quli06",
      "quli07",
      "quli08",
      "quli09",
      "quli10",
      "quli11",
      "quli12",
      "quli01",
      "quli02",
      "quli03",
      "quli04",
      "quli05",
      "quli06",
      "quli07",
      "quli08",
      "quli09",
      "quli10",
      "quli11",
      "quli12",
      "quli01",
      "quli02",
      "quli03",
      "quli04",
      "quli05",
      "quli06",
      "quli07",
      "quli08",
      "quli09",
      "quli10",
      "quli11",
      "quli12",
      "quli01",
      "quli02",
      "quli03",
      "quli04",
      "quli05",
      "quli06",
      "quli07",
      "quli08",
      "quli09",
      "quli10",
      "quli11",
      "quli12",
      "quli01",
      "quli02",
      "quli03",
      "quli04",
      "quli05",
      "quli06",
      "quli07",
      "quli08",
      "quli09",
      "quli10",
      "quli11",
      "quli12",
      "quli13",
      "quli14",
      "quli01",
      "quli02",
      "quli03",
      "quli04",
      "quli05",
      "quli06",
      "quli07",
      "quli08",
      "quli09",
      "quli10",
      "quli11",
      "quli12",
      "quli13",
      "quli14",
      "quli01",
      "quli02",
      "quli03",
      "quli04",
      "quli05",
      "quli06",
      "quli07",
      "quli08",
      "quli09",
      "quli10",
      "quli11",
      "quli12",
      "quli13",
      "quli14"
    ),
    variable_label = c(
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "WHOQOL: rating quality of life",
      "WHOQOL: feeling life is meaningful",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "WHOQOL: rating quality of life",
      "WHOQOL: feeling life is meaningful",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "WHOQOL: rating quality of life",
      "WHOQOL: feeling life is meaningful"
    ),
    harmonized_var_label = c(
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "WHOQOL: rating quality of life",
      "WHOQOL: feeling life is meaningful",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "WHOQOL: rating quality of life",
      "WHOQOL: feeling life is meaningful",
      "SF12-01: GH, general health",
      "SF12-02: PF, moderate activities",
      "SF12-03: PF, climbing stairs",
      "SF12-04: RP, physical accomplished less",
      "SF12-05: RP, limited in activities",
      "SF12-06: RE, mental accomplished less",
      "SF12-07: RE, work not careful",
      "SF12-08: BP, pain",
      "SF12-09: MH, calm",
      "SF12-10: VT, energy",
      "SF12-11: MH, blue",
      "SF12-12: SF, social activities",
      "WHOQOL: rating quality of life",
      "WHOQOL: feeling life is meaningful"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    quli01 = list(
      `3B` = excellent_very_good_good_fair_poor,
      D = excellent_very_good_good_fair_poor,
      E = excellent_very_good_good_fair_poor,
      F = excellent_very_good_good_fair_poor,
      G = excellent_very_good_good_fair_poor,
      H = excellent_very_good_good_fair_poor,
      I = excellent_very_good_good_fair_poor,
      J = excellent_very_good_good_fair_poor,
      K = excellent_very_good_good_fair_poor
    ),
    quli02 = list(
      `3B` = yes_limited_a_lot_yes_limited_a_little,
      D = yes_limited_a_lot_yes_limited_a_little,
      E = yes_limited_a_lot_yes_limited_a_little,
      F = yes_limited_a_lot_yes_limited_a_little,
      G = yes_limited_a_lot_yes_limited_a_little,
      H = yes_limited_a_lot_yes_limited_a_little,
      I = yes_limited_a_lot_yes_limited_a_little,
      J = yes_limited_a_lot_yes_limited_a_little,
      K = yes_limited_a_lot_yes_limited_a_little
    ),
    quli03 = list(
      `3B` = yes_limited_a_lot_yes_limited_a_little,
      D = yes_limited_a_lot_yes_limited_a_little,
      E = yes_limited_a_lot_yes_limited_a_little,
      F = yes_limited_a_lot_yes_limited_a_little,
      G = yes_limited_a_lot_yes_limited_a_little,
      H = yes_limited_a_lot_yes_limited_a_little,
      I = yes_limited_a_lot_yes_limited_a_little,
      J = yes_limited_a_lot_yes_limited_a_little,
      K = yes_limited_a_lot_yes_limited_a_little
    ),
    quli04 = list(
      `3B` = yes_no_3,
      D = yes_no_3,
      E = yes_no_3,
      F = yes_no_3,
      G = yes_no_3,
      H = yes_no_3,
      I = yes_no_3,
      J = yes_no_3,
      K = yes_no_3
    ),
    quli05 = list(
      `3B` = yes_no_3,
      D = yes_no_3,
      E = yes_no_3,
      F = yes_no_3,
      G = yes_no_3,
      H = yes_no_3,
      I = yes_no_3,
      J = yes_no_3,
      K = yes_no_3
    ),
    quli06 = list(
      `3B` = yes_no_3,
      D = yes_no_3,
      E = yes_no_3,
      F = yes_no_3,
      G = yes_no_3,
      H = yes_no_3,
      I = yes_no_3,
      J = yes_no_3,
      K = yes_no_3
    ),
    quli07 = list(
      `3B` = yes_no_3,
      D = yes_no_3,
      E = yes_no_3,
      F = yes_no_3,
      G = yes_no_3,
      H = yes_no_3,
      I = yes_no_3,
      J = yes_no_3,
      K = yes_no_3
    ),
    quli08 = list(
      `3B` = not_at_all_a_little_bit_moderately_quite_a_bit,
      D = not_at_all_a_little_bit_moderately_quite_a_bit,
      E = not_at_all_a_little_bit_moderately_quite_a_bit,
      F = not_at_all_a_little_bit_moderately_quite_a_bit,
      G = not_at_all_a_little_bit_moderately_quite_a_bit,
      H = not_at_all_a_little_bit_moderately_quite_a_bit,
      I = not_at_all_a_little_bit_moderately_quite_a_bit,
      J = not_at_all_a_little_bit_moderately_quite_a_bit,
      K = not_at_all_a_little_bit_moderately_quite_a_bit
    ),
    quli09 = list(
      `3B` = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      D = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      E = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      F = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      G = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      H = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      I = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      J = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      K = all_of_the_time_most_of_the_time_a_good_bit_of_the_time
    ),
    quli10 = list(
      `3B` = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      D = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      E = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      F = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      G = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      H = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      I = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      J = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      K = all_of_the_time_most_of_the_time_a_good_bit_of_the_time
    ),
    quli11 = list(
      `3B` = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      D = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      E = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      F = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      G = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      H = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      I = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      J = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      K = all_of_the_time_most_of_the_time_a_good_bit_of_the_time
    ),
    quli12 = list(
      `3B` = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      D = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      E = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      F = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      G = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      H = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      I = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      J = all_of_the_time_most_of_the_time_a_good_bit_of_the_time,
      K = all_of_the_time_most_of_the_time_a_good_bit_of_the_time
    ),
    quli13 = list(
      I = very_poor_rather_poor_neither_poor_nor_good_rather_good,
      J = very_poor_rather_poor_neither_poor_nor_good_rather_good,
      K = very_poor_rather_poor_neither_poor_nor_good_rather_good
    ),
    quli14 = list(
      I = not_at_all_a_little_a_moderate_amount_very_much,
      J = not_at_all_a_little_a_moderate_amount_very_much,
      K = not_at_all_a_little_a_moderate_amount_very_much
    )
  ),

  value_labels_harmonized = list(
    quli01 = c(
      `-1` = "not available",
      `1` = "excellent",
      `2` = "very good",
      `3` = "good",
      `4` = "fair",
      `5` = "poor"
    ),
    quli02 = yes_limited_a_lot_yes_limited_a_little_2,
    quli03 = yes_limited_a_lot_yes_limited_a_little_2,
    quli04 = yes_no_2,
    quli05 = yes_no_2,
    quli06 = yes_no_2,
    quli07 = yes_no_2,
    quli08 = c(
      `-1` = "not available",
      `1` = "not at all",
      `2` = "a little bit",
      `3` = "moderately",
      `4` = "quite a bit",
      `5` = "extremely"
    ),
    quli09 = all_of_the_time_most_of_the_time_a_good_bit_of_the_time_2,
    quli10 = all_of_the_time_most_of_the_time_a_good_bit_of_the_time_2,
    quli11 = all_of_the_time_most_of_the_time_a_good_bit_of_the_time_2,
    quli12 = all_of_the_time_most_of_the_time_a_good_bit_of_the_time_2,
    quli13 = c(
      `-1` = "not available",
      `1` = "very poor",
      `2` = "rather poor",
      `3` = "neither poor nor good",
      `4` = "rather good",
      `5` = "very good"
    ),
    quli14 = c(
      `-1` = "not available",
      `1` = "not at all",
      `2` = "a little",
      `3` = "a moderate amount",
      `4` = "very much",
      `5` = "an extreme amount"
    )
  )
)
