## LASA filecode 015 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_015 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "bhowner",
      "bmortga",
      "bmovefut",
      "bmovrea",
      "bmovreas",
      "bmovtyph",
      "bmovtypi",
      "bmovtyps",
      "bpleas",
      "bsafe",
      "byneigh",
      "bhowner",
      "bmortga",
      "bpleas",
      "bsafe",
      "byneigh",
      "bhowner",
      "bmortga",
      "bmovefut",
      "bpleas",
      "bsafe",
      "byneigh",
      "chowner",
      "cmortga",
      "cmovefut",
      "cpleas",
      "csafe",
      "cyneigh",
      "dhowner",
      "dmortga",
      "dmovefut",
      "dpleas",
      "dsafe",
      "dyneigh",
      "ehowner",
      "emortga",
      "emovefut",
      "epleas",
      "esafe",
      "eyneigh",
      "fhowner",
      "fmortga",
      "fpleas",
      "fsafe",
      "fyneigh",
      "gh21own",
      "gh21owns",
      "gh22own",
      "gh22owns",
      "gh2dura",
      "gh2loc",
      "gh2locsp",
      "ghouse2",
      "ghowner",
      "ghs21",
      "ghs22",
      "ghs23",
      "ghs24",
      "ghs25",
      "ghs26",
      "ghs26s",
      "gmortga",
      "gpleas",
      "gsafe",
      "gyneigh",
      "hhowner",
      "hmortga",
      "hpleas",
      "hsafe",
      "hyneigh",
      "ihowner",
      "imortga",
      "ipleas",
      "isafe",
      "iyneigh",
      "jhowner",
      "jmortga",
      "jpleas",
      "jsafe",
      "jyneigh",
      "khowner",
      "kmortga",
      "kpleas",
      "ksafe",
      "kyneigh"
    ),
    canonical_name = c(
      "howner",
      "mortga",
      "movefut",
      "movrea",
      "movreas",
      "movtyph",
      "movtypi",
      "movtyps",
      "pleas",
      "safe",
      "yneigh",
      "howner",
      "mortga",
      "pleas",
      "safe",
      "yneigh",
      "howner",
      "mortga",
      "movefut",
      "pleas",
      "safe",
      "yneigh",
      "howner",
      "mortga",
      "movefut",
      "pleas",
      "safe",
      "yneigh",
      "howner",
      "mortga",
      "movefut",
      "pleas",
      "safe",
      "yneigh",
      "howner",
      "mortga",
      "movefut",
      "pleas",
      "safe",
      "yneigh",
      "howner",
      "mortga",
      "pleas",
      "safe",
      "yneigh",
      "h21own",
      "h21owns",
      "h22own",
      "h22owns",
      "h2dura",
      "h2loc",
      "h2locsp",
      "house2",
      "howner",
      "hs21",
      "hs22",
      "hs23",
      "hs24",
      "hs25",
      "hs26",
      "hs26s",
      "mortga",
      "pleas",
      "safe",
      "yneigh",
      "howner",
      "mortga",
      "pleas",
      "safe",
      "yneigh",
      "howner",
      "mortga",
      "pleas",
      "safe",
      "yneigh",
      "howner",
      "mortga",
      "pleas",
      "safe",
      "yneigh",
      "howner",
      "mortga",
      "pleas",
      "safe",
      "yneigh"
    ),
    variable_label = c(
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Want to move the next years",
      "Most important reason for moving",
      "Other reason for moving",
      "Kind of home R wants to move to",
      "Type of independent home R wants to move to",
      "Other kind of home R wants to move to",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Want to move the next years",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Want to move the next years",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Want to move the next years",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Want to move the next years",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership second home, apartment",
      "Ownership second home, apartment: other specified",
      "Ownership caravan, tent (fixed)",
      "Ownership caravan, tent (fixed): other specified",
      "Duration of stay in second home (total per year)",
      "Location of second home, place of stay",
      "Location of second home, place of stay, specified",
      "Stay in second home more than a month a year",
      "Ownership of house: owner/rented/free",
      "Second home type: second house, apartment",
      "Second home type: caravan, tent on a fixed place",
      "Second home type: mobile home, camper (not fixed)",
      "Second home type: boat",
      "Second home type: home of family or friends",
      "Second home type: something else",
      "Second home type: something else, specified",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood"
    ),
    harmonized_var_label = c(
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Want to move the next years",
      "Most important reason for moving",
      "Other reason for moving",
      "Kind of home R wants to move to",
      "Type of independent home R wants to move to",
      "Other kind of home R wants to move to",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Want to move the next years",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Want to move the next years",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Want to move the next years",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Want to move the next years",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership second home, apartment",
      "Ownership second home, apartment: other specified",
      "Ownership caravan, tent (fixed)",
      "Ownership caravan, tent (fixed): other specified",
      "Duration of stay in second home (total per year)",
      "Location of second home, place of stay",
      "Location of second home, place of stay, specified",
      "Stay in second home more than a month a year",
      "Ownership of house: owner/rented/free",
      "Second home type: second house, apartment",
      "Second home type: caravan, tent on a fixed place",
      "Second home type: mobile home, camper (not fixed)",
      "Second home type: boat",
      "Second home type: home of family or friends",
      "Second home type: something else",
      "Second home type: something else, specified",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood",
      "Ownership of house: owner/rented/free",
      "House is mortgage free",
      "Pleasant living in neighbourhood",
      "Feeling safe in evening in neighbourhood",
      "How many years in neighbourhood"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    howner = list(
      `2B` = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BHINDEP in LAS2B014",
        `-1` = "na, asked",
        `1` = "owner",
        `2` = "tenant",
        `3` = "subtenant",
        `4` = "resident",
        `5` = "free"
      ),
      `3B` = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BHINDEP in LAS3B014",
        `-1` = "na, asked",
        `1` = "owner",
        `2` = "tenant",
        `3` = "subtenant",
        `4` = "resident",
        `5` = "free"
      ),
      B = c(
        `-4` = "na, short version",
        `-3` = "na, wrong skip",
        `-2` = "na, routing",
        `-1` = "no answer, asked",
        `1` = "owner",
        `2` = "tenant",
        `3` = "subtenant",
        `4` = "resident",
        `5` = "free"
      ),
      C = owner_tenant_subtenant_resident_free,
      D = owner_tenant_subtenant_resident_free,
      E = owner_tenant_subtenant_resident_free,
      F = owner_tenant_subtenant_resident_free,
      G = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see GHINDEP in LASAG014",
        `-1` = "na, asked",
        `1` = "owner",
        `2` = "tenant",
        `3` = "subtenant",
        `4` = "resident",
        `5` = "free"
      ),
      H = owner_tenant_subtenant_resident_free,
      I = owner_tenant_subtenant_resident_free,
      J = owner_tenant_subtenant_resident_free,
      K = owner_tenant_subtenant_resident_free
    ),
    mortga = list(
      `2B` = no_mortgage_mortgage_2,
      `3B` = no_mortgage_mortgage_2,
      B = c(
        `-4` = "na, short version",
        `-3` = "na, wrong skip",
        `-2` = "na, routing",
        `-1` = "no answer, asked",
        `1` = "no mortgage",
        `2` = "mortgage"
      ),
      C = no_mortgage_mortgage,
      D = no_mortgage_mortgage,
      E = no_mortgage_mortgage,
      F = no_mortgage_mortgage,
      G = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see GHOWNER",
        `-1` = "na, asked",
        `1` = "no mortgage",
        `2` = "mortgage"
      ),
      H = no_mortgage_mortgage,
      I = no_mortgage_mortgage,
      J = no_mortgage_mortgage,
      K = no_mortgage_mortgage
    ),
    movefut = list(
      `2B` = no_yes_184,
      B = no_yes_185,
      C = no_yes_22,
      D = no_yes_22,
      E = no_yes_22
    ),
    movrea = list(
      `2B` = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BMOVTYPH",
        `-1` = "na, asked",
        `1` = "poor health R",
        `2` = "poor health partner",
        `3` = "marriage/cohabitation",
        `4` = "divorce",
        `5` = "more privacy",
        `6` = "more companionship",
        `7` = "no burden to others",
        `8` = "closer to (non)kin",
        `9` = "job",
        `10` = "house now too big",
        `11` = "house now too small",
        `12` = "house now too expensive",
        `13` = "house now inadequate",
        `14` = "dislike neighbourhood",
        `15` = "closer to facilities",
        `16` = "demolition house",
        `17` = "other"
      )
    ),
    movreas = list(
      `2B` = c(`-3` = "na, wrong skip", `-2` = "na, see BMOVREA", `-1` = "na, asked", `0` = "<to be coded>")
    ),
    movtyph = list(
      `2B` = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BMOVEFUT",
        `-1` = "na, asked",
        `1` = "co-residence with children",
        `2` = "share home with family",
        `3` = "share home with friends",
        `4` = "commune",
        `5` = "service-flat",
        `6` = "apartment building elderly (elevator)",
        `7` = "home elderly (street level)",
        `8` = "home elderly (service provision)",
        `9` = "semi-independent",
        `10` = "old peoples home",
        `11` = "nursing home",
        `12` = "independent",
        `13` = "other"
      )
    ),
    movtypi = list(
      `2B` = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BMOVTYPH",
        `-1` = "na, asked",
        `1` = "attached row",
        `2` = "semi-detached",
        `3` = "detached",
        `4` = "high rise (elevator)",
        `5` = "high rise (no elevator)",
        `6` = "farm",
        `7` = "low-level apt building"
      )
    ),
    movtyps = list(
      `2B` = c(`-3` = "na, wrong skip", `-2` = "na, see BMOVTYPH", `-1` = "na, asked", `0` = "<to be coded>")
    ),
    pleas = list(
      `2B` = no_yes_184,
      `3B` = no_yes_186,
      B = no_yes_185,
      C = no_yes_22,
      D = no_yes_22,
      E = no_yes_22,
      F = no_yes_22,
      G = no_yes_22,
      H = no_yes_22,
      I = no_yes_22,
      J = no_yes_22,
      K = no_yes_22
    ),
    safe = list(
      `2B` = no_yes_184,
      `3B` = no_yes_186,
      B = no_yes_185,
      C = no_yes_22,
      D = no_yes_22,
      E = no_yes_22,
      F = no_yes_22,
      G = no_yes_22,
      H = no_yes_22,
      I = no_yes_22,
      J = no_yes_22,
      K = no_yes_22
    ),
    yneigh = list(
      `2B` = c(`-2` = "na, interview terminated", `-1` = "na, asked"),
      `3B` = na_asked,
      B = c(`-4` = "na, short version"),
      C = na_asked,
      D = na_asked,
      E = na_asked,
      F = na_asked,
      G = na_asked,
      H = na_asked,
      I = na_asked,
      J = na_asked,
      K = na_asked
    ),
    h21own = list(
      G = c(
        `-2` = "na, see GHS21",
        `-1` = "na, asked",
        `1` = "owner without mortgage",
        `2` = "owner, with mortgage",
        `3` = "rented or paid residence",
        `4` = "other"
      )
    ),
    h21owns = list(
      G = to_be_coded_7
    ),
    h22own = list(
      G = c(
        `-2` = "na, see GHS22",
        `-1` = "na, asked",
        `1` = "owner, without mortgage",
        `2` = "owner, with mortgage",
        `3` = "rented or paid residence",
        `4` = "other"
      )
    ),
    h22owns = list(
      G = to_be_coded_7
    ),
    h2dura = list(
      G = c(
        `-2` = "na, see GHOUSE2",
        `-1` = "na, asked",
        `1` = "1 or 2 months",
        `2` = "3 or 4 months",
        `3` = "about half a year",
        `4` = "the larger part of the year"
      )
    ),
    h2loc = list(
      G = c(
        `-2` = "na, see GHOUSE2",
        `-1` = "na, asked",
        `1` = "own region, province",
        `2` = "somewhere else in the Netherlands",
        `3` = "in Europe",
        `4` = "outside Europe"
      )
    ),
    h2locsp = list(
      G = c(`-2` = "na, see GH2LOC", `0` = "- to be coded-")
    ),
    house2 = list(
      G = no_yes
    ),
    hs21 = list(
      G = not_mentioned_mentioned_205
    ),
    hs22 = list(
      G = not_mentioned_mentioned_205
    ),
    hs23 = list(
      G = not_mentioned_mentioned_205
    ),
    hs24 = list(
      G = not_mentioned_mentioned_205
    ),
    hs25 = list(
      G = not_mentioned_mentioned_205
    ),
    hs26 = list(
      G = not_mentioned_mentioned_205
    ),
    hs26s = list(
      G = c(`-2` = "na, see GHS26", `0` = "-to be coded-")
    )
  ),

  value_labels_harmonized = list(
    h21own = c(
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "owner without mortgage",
      `2` = "owner, with mortgage",
      `3` = "rented or paid residence",
      `4` = "other"
    ),
    h21owns = to_be_coded_3,
    h22own = c(
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "owner, without mortgage",
      `2` = "owner, with mortgage",
      `3` = "rented or paid residence",
      `4` = "other"
    ),
    h22owns = to_be_coded_3,
    h2dura = c(
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "1 or 2 months",
      `2` = "3 or 4 months",
      `3` = "about half a year",
      `4` = "the larger part of the year"
    ),
    h2loc = c(
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "own region, province",
      `2` = "somewhere else in the netherlands",
      `3` = "in europe",
      `4` = "outside europe"
    ),
    h2locsp = to_be_coded_3,
    house2 = no_yes_244,
    howner = c(
      `-4` = "not available, short version",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "owner",
      `2` = "tenant",
      `3` = "subtenant",
      `4` = "resident",
      `5` = "free"
    ),
    hs21 = not_mentioned_mentioned_6,
    hs22 = not_mentioned_mentioned_6,
    hs23 = not_mentioned_mentioned_6,
    hs24 = not_mentioned_mentioned_6,
    hs25 = not_mentioned_mentioned_6,
    hs26 = not_mentioned_mentioned_6,
    hs26s = to_be_coded_3,
    mortga = c(
      `-4` = "not available, short version",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "no mortgage",
      `2` = "mortgage"
    ),
    movefut = no_binary_category_1_yes,
    movrea = c(
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "poor health r",
      `2` = "poor health partner",
      `3` = "marriage/cohabitation",
      `4` = "divorce",
      `5` = "more privacy",
      `6` = "more companionship",
      `7` = "no burden to others",
      `8` = "closer to (non)kin",
      `9` = "job",
      `10` = "house now too big",
      `11` = "house now too small",
      `12` = "house now too expensive",
      `13` = "house now inadequate",
      `14` = "dislike neighbourhood",
      `15` = "closer to facilities",
      `16` = "demolition house",
      `17` = "other"
    ),
    movreas = to_be_coded_8,
    movtyph = c(
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "co-residence with children",
      `2` = "share home with family",
      `3` = "share home with friends",
      `4` = "commune",
      `5` = "service-flat",
      `6` = "apartment building elderly (elevator)",
      `7` = "home elderly (street level)",
      `8` = "home elderly (service provision)",
      `9` = "semi-independent",
      `10` = "old peoples home",
      `11` = "nursing home",
      `12` = "independent",
      `13` = "other"
    ),
    movtypi = c(
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "attached row",
      `2` = "semi-detached",
      `3` = "detached",
      `4` = "high rise (elevator)",
      `5` = "high rise (no elevator)",
      `6` = "farm",
      `7` = "low-level apt building"
    ),
    movtyps = to_be_coded_8,
    pleas = no_binary_category_1_yes,
    safe = no_binary_category_1_yes,
    yneigh = c(
      `-4` = "not available, short version",
      `-2` = "not available, interview terminated",
      `-1` = "not available, asked"
    )
  )
)
