## LASA filecode 144 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_144 <- list(
  variables = data.frame(
    wave = c(
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "fqindf01",
      "fqindf02",
      "fqindf03",
      "fqindf04",
      "fqindf05",
      "fqindf06",
      "fqindf07",
      "fqindf08",
      "fqindf09",
      "fqindf10",
      "fqindf11",
      "fqindf12",
      "fqindf13",
      "fqindf14",
      "fqindf15",
      "fqindf16",
      "gqindf01",
      "gqindf02",
      "gqindf03",
      "gqindf04",
      "gqindf05",
      "gqindf06",
      "gqindf07",
      "gqindf08",
      "gqindf09",
      "gqindf10",
      "gqindf11",
      "gqindf12",
      "gqindf13",
      "gqindf14",
      "gqindf15",
      "gqindf16",
      "hqindf01",
      "hqindf02",
      "hqindf03",
      "hqindf04",
      "hqindf05",
      "hqindf06",
      "hqindf07",
      "hqindf08",
      "hqindf09",
      "hqindf10",
      "hqindf11",
      "hqindf12",
      "hqindf13",
      "hqindf14",
      "hqindf15",
      "hqindf16",
      "iqindf01",
      "iqindf02",
      "iqindf03",
      "iqindf04",
      "iqindf05",
      "iqindf06",
      "iqindf07",
      "iqindf08",
      "iqindf09",
      "iqindf10",
      "iqindf11",
      "iqindf12",
      "iqindf13",
      "iqindf14",
      "iqindf15",
      "iqindf16",
      "iqindf17",
      "jqindf01",
      "jqindf02",
      "jqindf03",
      "jqindf04",
      "jqindf05",
      "jqindf06",
      "jqindf07",
      "jqindf08",
      "jqindf09",
      "jqindf10",
      "jqindf11",
      "jqindf12",
      "jqindf13",
      "jqindf14",
      "jqindf15",
      "jqindf16",
      "kqindf01",
      "kqindf02",
      "kqindf03",
      "kqindf04",
      "kqindf05",
      "kqindf06",
      "kqindf07",
      "kqindf08",
      "kqindf09",
      "kqindf10",
      "kqindf11",
      "kqindf12",
      "kqindf13",
      "kqindf14",
      "kqindf15",
      "kqindf16"
    ),
    canonical_name = c(
      "qindf01",
      "qindf02",
      "qindf03",
      "qindf04",
      "qindf05",
      "qindf06",
      "qindf07",
      "qindf08",
      "qindf09",
      "qindf10",
      "qindf11",
      "qindf12",
      "qindf13",
      "qindf14",
      "qindf15",
      "qindf16",
      "qindf01",
      "qindf02",
      "qindf03",
      "qindf04",
      "qindf05",
      "qindf06",
      "qindf07",
      "qindf08",
      "qindf09",
      "qindf10",
      "qindf11",
      "qindf12",
      "qindf13",
      "qindf14",
      "qindf15",
      "qindf16",
      "qindf01",
      "qindf02",
      "qindf03",
      "qindf04",
      "qindf05",
      "qindf06",
      "qindf07",
      "qindf08",
      "qindf09",
      "qindf10",
      "qindf11",
      "qindf12",
      "qindf13",
      "qindf14",
      "qindf15",
      "qindf16",
      "qindf01",
      "qindf02",
      "qindf03",
      "qindf04",
      "qindf05",
      "qindf06",
      "qindf07",
      "qindf08",
      "qindf09",
      "qindf10",
      "qindf11",
      "qindf12",
      "qindf13",
      "qindf14",
      "qindf15",
      "qindf16",
      "qindf17",
      "qindf01",
      "qindf02",
      "qindf03",
      "qindf04",
      "qindf05",
      "qindf06",
      "qindf07",
      "qindf08",
      "qindf09",
      "qindf10",
      "qindf11",
      "qindf12",
      "qindf13",
      "qindf14",
      "qindf15",
      "qindf16",
      "qindf01",
      "qindf02",
      "qindf03",
      "qindf04",
      "qindf05",
      "qindf06",
      "qindf07",
      "qindf08",
      "qindf09",
      "qindf10",
      "qindf11",
      "qindf12",
      "qindf13",
      "qindf14",
      "qindf15",
      "qindf16"
    ),
    variable_label = c(
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently",
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently",
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently",
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently",
      "ability to cope, independently or with help from others (score from 1 to 10)",
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently",
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently"
    ),
    harmonized_var_label = c(
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently",
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently",
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently",
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently",
      "ability to cope, independently or with help from others (score from 1 to 10)",
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently",
      "able to do things for myself",
      "proud to take care of myself",
      "bothers me when others notice",
      "live independently not very important",
      "does not bother me when unable to do a task",
      "important to work at sustaining my independence",
      "trying to improve my ability to function on my own",
      "admire people who live on their own",
      "friends often notice my self-sufficiency",
      "often notice my friends self-sufficiency",
      "be very accurate when remembering appointments",
      "be very accurate when taking my medications",
      "bothers me when unable to run errands on my own",
      "do things on my own, without relying on other people",
      "highly motivated to do things on my own",
      "great satisfaction to accomplish tasks independently"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qindf01 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf02 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf03 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf04 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf05 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf06 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf07 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf08 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf09 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf10 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf11 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf12 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf13 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf14 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf15 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf16 = list(
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement,
      H = strongly_disagree_disagree_no_agreement_disagreement,
      I = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement,
      K = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qindf17 = list(
      I = no_answer
    )
  ),

  value_labels_harmonized = list(
    qindf01 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf02 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf03 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf04 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf05 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf06 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf07 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf08 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf09 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf10 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf11 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf12 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf13 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf14 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf15 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf16 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qindf17 = not_available
  )
)
