## LASA filecode 181 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_181 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bmmenno61",
      "bmmeno01",
      "bmmeno02",
      "bmmeno03",
      "bmmeno04",
      "bmmeno05",
      "bmmeno07",
      "bmmeno08",
      "bmmeno09",
      "bmmeno10",
      "bmmeno11",
      "bmmeno12",
      "bmmeno13",
      "bmmeno14",
      "bmmeno15",
      "bmmeno16",
      "bmmeno62",
      "bmmeno63",
      "bmmeno64",
      "bmmeno81",
      "bmmeno82",
      "bmmeno83",
      "bmmeno84",
      "bmmeno85",
      "bmmenno61",
      "bmmeno01",
      "bmmeno02",
      "bmmeno03",
      "bmmeno04",
      "bmmeno05",
      "bmmeno07",
      "bmmeno08",
      "bmmeno09",
      "bmmeno10",
      "bmmeno11",
      "bmmeno12",
      "bmmeno13",
      "bmmeno14",
      "bmmeno15",
      "bmmeno16",
      "bmmeno62",
      "bmmeno63",
      "bmmeno64",
      "bmmeno65",
      "bmmeno66",
      "bmmeno81",
      "bmmeno82",
      "bmmeno83",
      "bmmeno84",
      "bmmeno85",
      "cmenno18",
      "cmmeno05",
      "cmmeno09",
      "cmmeno17",
      "cmmeno61",
      "cmmeno62",
      "cmmeno63",
      "cmmeno66",
      "cmmeno82",
      "cmmeno83",
      "bmmeno01",
      "bmmeno05",
      "bmmeno09",
      "bmmeno10",
      "bmmeno14",
      "bmmeno61",
      "bmmeno62",
      "bmmeno63",
      "bmmeno64",
      "bmmeno65",
      "bmmeno66",
      "bmmeno82",
      "bmmeno84",
      "bmmeno85"
    ),
    canonical_name = c(
      "mmenno61",
      "mmeno01",
      "mmeno02",
      "mmeno03",
      "mmeno04",
      "mmeno05",
      "mmeno07",
      "mmeno08",
      "mmeno09",
      "mmeno10",
      "mmeno11",
      "mmeno12",
      "mmeno13",
      "mmeno14",
      "mmeno15",
      "mmeno16",
      "mmeno62",
      "mmeno63",
      "mmeno64",
      "mmeno81",
      "mmeno82",
      "mmeno83",
      "mmeno84",
      "mmeno85",
      "mmenno61",
      "mmeno01",
      "mmeno02",
      "mmeno03",
      "mmeno04",
      "mmeno05",
      "mmeno07",
      "mmeno08",
      "mmeno09",
      "mmeno10",
      "mmeno11",
      "mmeno12",
      "mmeno13",
      "mmeno14",
      "mmeno15",
      "mmeno16",
      "mmeno62",
      "mmeno63",
      "mmeno64",
      "mmeno65",
      "mmeno66",
      "mmeno81",
      "mmeno82",
      "mmeno83",
      "mmeno84",
      "mmeno85",
      "menno18",
      "mmeno05",
      "mmeno09",
      "mmeno17",
      "mmeno61",
      "mmeno62",
      "mmeno63",
      "mmeno66",
      "mmeno82",
      "mmeno83",
      "mmeno01",
      "mmeno05",
      "mmeno09",
      "mmeno10",
      "mmeno14",
      "mmeno61",
      "mmeno62",
      "mmeno63",
      "mmeno64",
      "mmeno65",
      "mmeno66",
      "mmeno82",
      "mmeno84",
      "mmeno85"
    ),
    variable_label = c(
      "Menopause: hysterectomy",
      "Menopause: age start period",
      "Menopause: number of children",
      "Menopause: age first child born",
      "Menopause: ever pregnant",
      "Menopause: age last period",
      "Menopause: used contraceptive pill",
      "Menopause: # years contraceptive pill",
      "Menopause: hot flushes",
      "Menopause: excessive transpiration",
      "Menopause: pain in muscles",
      "Menopause: dry vagina",
      "Menopause: pain during intercourse",
      "Menopause: hot flushes in the past",
      "Menopause: age first hot flushes",
      "Menopause: age last hot flushes",
      "Menopause: age hysterectomy",
      "Menopause: ovary removed",
      "Menopause: age first ovary removed",
      "Menopause: age start use contraceptive pill",
      "Menopause: females sex hormones",
      "Menopause: hormones type",
      "Menopause: hormones start age",
      "Menopause: hormones # months",
      "Menopause: hysterectomy",
      "Menopause: age start period",
      "Menopause: number of children",
      "Menopause: age first child born",
      "Menopause: ever pregnant",
      "Menopause: age last period",
      "Menopause: used contraceptive pill",
      "Menopause: # years contraceptive pill",
      "Menopause: hot flushes",
      "Menopause: excessive transpiration",
      "Menopause: pain in muscles",
      "Menopause: dry vagina",
      "Menopause: pain during intercourse",
      "Menopause: hot flushes in the past",
      "Menopause: age first hot flushes",
      "Menopause: age last hot flushes",
      "Menopause: age hysterectomy",
      "Menopause: ovary removed",
      "Menopause: age first ovary removed",
      "Menopause: age second ovary removed",
      "Menopause: age one ovary removed",
      "Menopause: age start use contraceptive pill",
      "Menopause: females sex hormones",
      "Menopause: hormones type",
      "Menopause: hormones start age",
      "Menopause: hormones # months",
      "Menopause 10: number of months",
      "Menopause 01: age period stopped",
      "Menopause 06: hot flushes",
      "Menopause 07: age first time",
      "Menopause 02: had a hysterectomy",
      "Menopause 03: hysterectomy age",
      "Menopause 04: ovary removed",
      "Menopause 05: ovary age (last operation)",
      "Menopause 08: female sex hormones",
      "Menopause 09: hormones type",
      "Menopause: age start period",
      "Menopause: age last period",
      "Menopause: hot flushes",
      "Menopause: excessive transpiration",
      "Menopause: hot flushes in the past",
      "Menopause: hysterectomy",
      "Menopause: age hysterectomy",
      "Menopause: ovary removed",
      "Menopause: age first ovary removed",
      "Menopause: age second ovary removed",
      "Menopause: age one ovary removed",
      "Menopause: females sex hormones",
      "Menopause: hormones start age",
      "Menopause: hormones # months"
    ),
    harmonized_var_label = c(
      "Menopause: hysterectomy",
      "Menopause: age start period",
      "Menopause: number of children",
      "Menopause: age first child born",
      "Menopause: ever pregnant",
      "Menopause: age last period",
      "Menopause: used contraceptive pill",
      "Menopause: # years contraceptive pill",
      "Menopause: hot flushes",
      "Menopause: excessive transpiration",
      "Menopause: pain in muscles",
      "Menopause: dry vagina",
      "Menopause: pain during intercourse",
      "Menopause: hot flushes in the past",
      "Menopause: age first hot flushes",
      "Menopause: age last hot flushes",
      "Menopause: age hysterectomy",
      "Menopause: ovary removed",
      "Menopause: age first ovary removed",
      "Menopause: age start use contraceptive pill",
      "Menopause: females sex hormones",
      "Menopause: hormones type",
      "Menopause: hormones start age",
      "Menopause: hormones # months",
      "Menopause: hysterectomy",
      "Menopause: age start period",
      "Menopause: number of children",
      "Menopause: age first child born",
      "Menopause: ever pregnant",
      "Menopause: age last period",
      "Menopause: used contraceptive pill",
      "Menopause: # years contraceptive pill",
      "Menopause: hot flushes",
      "Menopause: excessive transpiration",
      "Menopause: pain in muscles",
      "Menopause: dry vagina",
      "Menopause: pain during intercourse",
      "Menopause: hot flushes in the past",
      "Menopause: age first hot flushes",
      "Menopause: age last hot flushes",
      "Menopause: age hysterectomy",
      "Menopause: ovary removed",
      "Menopause: age first ovary removed",
      "Menopause: age second ovary removed",
      "Menopause: age one ovary removed",
      "Menopause: age start use contraceptive pill",
      "Menopause: females sex hormones",
      "Menopause: hormones type",
      "Menopause: hormones start age",
      "Menopause: hormones # months",
      "Menopause 10: number of months",
      "Menopause: age last period",
      "Menopause: hot flushes",
      "Menopause 07: age first time",
      "Menopause 02: had a hysterectomy",
      "Menopause: age hysterectomy",
      "Menopause: ovary removed",
      "Menopause: age one ovary removed",
      "Menopause: females sex hormones",
      "Menopause: hormones type",
      "Menopause: age start period",
      "Menopause: age last period",
      "Menopause: hot flushes",
      "Menopause: excessive transpiration",
      "Menopause: hot flushes in the past",
      "Menopause 02: had a hysterectomy",
      "Menopause: age hysterectomy",
      "Menopause: ovary removed",
      "Menopause: age first ovary removed",
      "Menopause: age second ovary removed",
      "Menopause: age one ovary removed",
      "Menopause: females sex hormones",
      "Menopause: hormones start age",
      "Menopause: hormones # months"
    ),
    var_type = c(
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mmenno61 = list(
      `2B` = no_yes_144,
      `3B` = no_yes_144
    ),
    mmeno01 = list(
      `2B` = male_respondent_na_asked,
      `3B` = male_respondent_na_asked,
      MB = na_wrong_skip_male_respondent_na_asked
    ),
    mmeno02 = list(
      `2B` = see_bmmeno03_na_asked,
      `3B` = see_bmmeno03_na_asked
    ),
    mmeno03 = list(
      `2B` = did_not_bear_children_see_bmmeno04_na_asked,
      `3B` = did_not_bear_children_see_bmmeno04_na_asked
    ),
    mmeno04 = list(
      `2B` = yes_no_7,
      `3B` = yes_no_7
    ),
    mmeno05 = list(
      `2B` = male_respondent_na_asked,
      `3B` = male_respondent_na_asked,
      C = c(`-5` = "na, interview terminated", `-2` = "male respondent", `-1` = "R does not know age"),
      MB = na_wrong_skip_male_respondent_na_asked
    ),
    mmeno07 = list(
      `2B` = yes_no_7,
      `3B` = yes_no_7
    ),
    mmeno08 = list(
      `2B` = na_asked,
      `3B` = na_asked
    ),
    mmeno09 = list(
      `2B` = yes_no_5,
      `3B` = yes_no_5,
      C = no_yes_240,
      MB = no_yes_r_refused_to_answer_r_does_not_know
    ),
    mmeno10 = list(
      `2B` = yes_no_5,
      `3B` = yes_no_5,
      MB = no_yes_r_refused_to_answer_r_does_not_know
    ),
    mmeno11 = list(
      `2B` = yes_no_5,
      `3B` = yes_no_5
    ),
    mmeno12 = list(
      `2B` = yes_no_5,
      `3B` = yes_no_5
    ),
    mmeno13 = list(
      `2B` = yes_no_5,
      `3B` = yes_no_5
    ),
    mmeno14 = list(
      `2B` = no_yes_348,
      `3B` = no_yes_348,
      MB = no_yes_r_refused_to_answer_r_does_not_know
    ),
    mmeno15 = list(
      `2B` = see_bmmeno14,
      `3B` = see_bmmeno14
    ),
    mmeno16 = list(
      `2B` = na_asked,
      `3B` = na_asked
    ),
    mmeno62 = list(
      `2B` = see_bmmeno61_na_asked,
      `3B` = see_bmmeno61_na_asked,
      C = c(`-3` = "na, wrong skip", `-2` = "na, see CMMENO61", `-1` = "R does not know age"),
      MB = c(`-2` = "na, see BMMENO61", `-1` = "na, asked")
    ),
    mmeno63 = list(
      `2B` = no_yes_one_removed_yes_both_removed,
      `3B` = no_yes_one_removed_yes_both_removed,
      C = c(
        `-5` = "na, interview terminated",
        `-2` = "male respondent",
        `-1` = "R does not know age",
        `1` = "no",
        `2` = "yes, one taken",
        `3` = "yes, both taken"
      ),
      MB = c(
        `-3` = "na, wrong skip",
        `-2` = "male respondent",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes, one removed",
        `3` = "yes, both removed"
      )
    ),
    mmeno64 = list(
      `2B` = see_bmmeno63_na_asked,
      `3B` = see_bmmeno63_na_asked,
      MB = c(`-2` = "na, see BMMENO63")
    ),
    mmeno81 = list(
      `2B` = see_bmmeno07,
      `3B` = see_bmmeno07
    ),
    mmeno82 = list(
      `2B` = no_yes_144,
      `3B` = no_yes_144,
      C = no_yes_240,
      MB = c(
        `-3` = "na, wrong skip",
        `-2` = "male respondent",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes, during menopause",
        `3` = "yes, after menopause",
        `4` = "yes, during and after menopause"
      )
    ),
    mmeno83 = list(
      `2B` = to_be_coded_16,
      `3B` = to_be_coded_16,
      C = c(`-3` = "na, wrong skip", `-2` = "na, see CMMENO82", `0` = "to be coded")
    ),
    mmeno84 = list(
      `2B` = see_bmmeno82,
      `3B` = see_bmmeno82,
      MB = c(`-2` = "na, see BMMENO82")
    ),
    mmeno85 = list(
      `2B` = na_asked,
      `3B` = na_asked,
      MB = na_asked
    ),
    mmeno65 = list(
      `3B` = na_see_bmmeno63_na_asked,
      MB = na_asked
    ),
    mmeno66 = list(
      `3B` = na_see_bmmeno63_na_asked,
      C = c(`-3` = "na, wrong skip", `-2` = "na, see CMMENO63", `-1` = "R does not know age"),
      MB = na_asked
    ),
    menno18 = list(
      C = na_wrong_skip_na_see_cmmeno82_r_does_not_know_age
    ),
    mmeno17 = list(
      C = na_wrong_skip_na_see_cmmeno09_r_does_not_know_age
    ),
    mmeno61 = list(
      C = no_yes_240,
      MB = c(
        `-3` = "na, wrong skip",
        `-2` = "male respondent",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes"
      )
    )
  ),

  value_labels_harmonized = list(
    menno18 = na_wrong_skip_na_see_cmmeno82_r_does_not_know_age,
    mmenno61 = no_yes_144,
    mmeno01 = na_wrong_skip_male_respondent_na_asked,
    mmeno02 = see_bmmeno03_na_asked,
    mmeno03 = did_not_bear_children_see_bmmeno04_na_asked,
    mmeno04 = yes_no_7,
    mmeno05 = c(
      `-5` = "na, interview terminated",
      `-3` = "na, wrong skip",
      `-2` = "male respondent",
      `-1` = "missing / source-specific"
    ),
    mmeno07 = yes_no_7,
    mmeno08 = na_asked,
    mmeno09 = c(
      `-5` = "na, interview terminated",
      `-3` = "missing / source-specific",
      `-2` = "male respondent",
      `-1` = "na, asked",
      `1` = "no",
      `2` = "no",
      `3` = "R refused to answer",
      `4` = "R does not know"
    ),
    mmeno10 = c(
      `-3` = "missing / source-specific",
      `-2` = "male respondent",
      `-1` = "na, asked",
      `1` = "no",
      `2` = "no",
      `3` = "R refused to answer",
      `4` = "R does not know"
    ),
    mmeno11 = yes_no_5,
    mmeno12 = yes_no_5,
    mmeno13 = yes_no_5,
    mmeno14 = c(
      `-3` = "missing / source-specific",
      `-2` = "male respondent",
      `-1` = "na, asked",
      `1` = "no",
      `2` = "yes",
      `3` = "R refused to answer",
      `4` = "R does not know"
    ),
    mmeno15 = see_bmmeno14,
    mmeno16 = na_asked,
    mmeno17 = na_wrong_skip_na_see_cmmeno09_r_does_not_know_age,
    mmeno61 = c(
      `-5` = "na, interview terminated",
      `-3` = "na, wrong skip",
      `-2` = "male respondent",
      `-1` = "na, asked",
      `1` = "no",
      `2` = "yes"
    ),
    mmeno62 = c(`-3` = "na, wrong skip", `-2` = "see BMMENO61", `-1` = "missing / source-specific"),
    mmeno63 = c(
      `-5` = "na, interview terminated",
      `-3` = "na, wrong skip",
      `-2` = "male respondent",
      `-1` = "missing / source-specific",
      `1` = "no",
      `2` = "yes, one taken",
      `3` = "yes, both taken"
    ),
    mmeno64 = see_bmmeno63_na_asked,
    mmeno65 = na_see_bmmeno63_na_asked,
    mmeno66 = c(`-3` = "na, wrong skip", `-2` = "na, see CMMENO63", `-1` = "missing / source-specific"),
    mmeno81 = see_bmmeno07,
    mmeno82 = c(
      `-5` = "na, interview terminated",
      `-3` = "na, wrong skip",
      `-2` = "male respondent",
      `-1` = "na, asked",
      `1` = "no",
      `2` = "yes",
      `3` = "yes, after menopause",
      `4` = "yes, during and after menopause"
    ),
    mmeno83 = c(`-3` = "na, wrong skip", `-2` = "see BMMENO82", `-1` = "na, asked", `0` = "to be coded"),
    mmeno84 = see_bmmeno82,
    mmeno85 = na_asked
  )
)
