## LASA filecode 028 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_028 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "badvemv",
      "balcmv",
      "balcos01",
      "balcos02",
      "balcos03",
      "balcos04",
      "balcos05",
      "balcos06",
      "balcos07",
      "balcos08",
      "balcos09",
      "balcos10",
      "balcos11",
      "balcos12",
      "bcompmv",
      "binitmv",
      "badvemv",
      "balcmv",
      "balcos01",
      "balcos02",
      "balcos03",
      "balcos04",
      "balcos05",
      "balcos06",
      "balcos07",
      "balcos08",
      "balcos09",
      "balcos10",
      "balcos11",
      "balcos12",
      "bcompmv",
      "binitmv",
      "badvemv",
      "balcmv",
      "balcos01",
      "balcos02",
      "balcos03",
      "balcos04",
      "balcos05",
      "balcos06",
      "balcos07",
      "balcos08",
      "balcos09",
      "balcos10",
      "balcos11",
      "balcos12",
      "bcompmv",
      "binitmv",
      "cadvemv",
      "calcmv",
      "calcos01",
      "calcos02",
      "calcos03",
      "calcos04",
      "calcos05",
      "calcos06",
      "calcos07",
      "calcos08",
      "calcos09",
      "calcos10",
      "calcos11",
      "calcos12",
      "ccompmv",
      "cinitmv",
      "dadvemv",
      "dalcmv",
      "dalcos01",
      "dalcos02",
      "dalcos03",
      "dalcos04",
      "dalcos05",
      "dalcos06",
      "dalcos07",
      "dalcos08",
      "dalcos09",
      "dalcos10",
      "dalcos11",
      "dalcos12",
      "dcompmv",
      "dinitmv",
      "eadvemv",
      "ealcmv",
      "ealcos01",
      "ealcos02",
      "ealcos03",
      "ealcos04",
      "ealcos05",
      "ealcos06",
      "ealcos07",
      "ealcos08",
      "ealcos09",
      "ealcos10",
      "ealcos11",
      "ealcos12",
      "ecompmv",
      "einitmv",
      "fadvemv",
      "falcmv",
      "falcos01",
      "falcos02",
      "falcos03",
      "falcos04",
      "falcos05",
      "falcos06",
      "falcos07",
      "falcos08",
      "falcos09",
      "falcos10",
      "falcos11",
      "falcos12",
      "fcompmv",
      "finitmv",
      "gadvemv",
      "galcmv",
      "galcos01",
      "galcos02",
      "galcos03",
      "galcos04",
      "galcos05",
      "galcos06",
      "galcos07",
      "galcos08",
      "galcos09",
      "galcos10",
      "galcos11",
      "galcos12",
      "gcompmv",
      "ginitmv",
      "hadvemv",
      "halcmv",
      "halcos01",
      "halcos02",
      "halcos03",
      "halcos04",
      "halcos05",
      "halcos06",
      "halcos07",
      "halcos08",
      "halcos09",
      "halcos10",
      "halcos11",
      "halcos12",
      "hcompmv",
      "hinitmv",
      "iadvemv",
      "ialcmv",
      "ialcos01",
      "ialcos02",
      "ialcos03",
      "ialcos04",
      "ialcos05",
      "ialcos06",
      "ialcos07",
      "ialcos08",
      "ialcos09",
      "ialcos10",
      "ialcos11",
      "ialcos12",
      "icompmv",
      "iinitmv",
      "jadvemv",
      "jalcmv",
      "jalcos01",
      "jalcos02",
      "jalcos03",
      "jalcos04",
      "jalcos05",
      "jalcos06",
      "jalcos07",
      "jalcos08",
      "jalcos09",
      "jalcos10",
      "jalcos11",
      "jalcos12",
      "jcompmv",
      "jinitmv",
      "kadvemv",
      "kalcmv",
      "kalcos01",
      "kalcos02",
      "kalcos03",
      "kalcos04",
      "kalcos05",
      "kalcos06",
      "kalcos07",
      "kalcos08",
      "kalcos09",
      "kalcos10",
      "kalcos11",
      "kalcos12",
      "kcompmv",
      "kinitmv"
    ),
    canonical_name = c(
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv",
      "advemv",
      "alcmv",
      "alcos01",
      "alcos02",
      "alcos03",
      "alcos04",
      "alcos05",
      "alcos06",
      "alcos07",
      "alcos08",
      "alcos09",
      "alcos10",
      "alcos11",
      "alcos12",
      "compmv",
      "initmv"
    ),
    variable_label = c(
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items"
    ),
    harmonized_var_label = c(
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items",
      "# missing values adver-alcos items",
      "# missing values alcos items",
      "Alcos item 01: plans",
      "Alcos item 02: failure",
      "Alcos item 03: wrong",
      "Alcos item 04: complicated",
      "Alcos item 05: unpleasant",
      "Alcos item 06: problem solving",
      "Alcos item 07: decision",
      "Alcos item 08: quickly",
      "Alcos item 09: unexpected",
      "Alcos item 10: mistake",
      "Alcos item 11: new things",
      "Alcos item 12: doubt",
      "# missing values comp-alcos items",
      "# missing values init-alcos items"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    advemv = list(
      `2B` = no_valid_data,
      `3B` = no_valid_data,
      B = na_see_brmalc_in_lasab228,
      C = no_valid_data,
      D = no_valid_data,
      E = no_valid_data,
      F = no_valid_data,
      G = no_valid_data,
      H = no_valid_data,
      I = no_valid_data,
      J = no_valid_data,
      K = no_valid_data
    ),
    alcmv = list(
      `2B` = no_valid_data,
      `3B` = no_valid_data,
      B = na_see_brmalc_in_lasab228,
      C = no_valid_data,
      D = no_valid_data,
      E = no_valid_data,
      F = no_valid_data,
      G = no_valid_data,
      H = no_valid_data,
      I = no_valid_data,
      J = no_valid_data,
      K = no_valid_data
    ),
    alcos01 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos02 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos03 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos04 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos05 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos06 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos07 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos08 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos09 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos10 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos11 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    alcos12 = list(
      `2B` = strongly_disagree_disagree_no_disagreement_agreement,
      `3B` = strongly_disagree_disagree_no_disagreement_agreement,
      B = strongly_disagree_disagree_no_disagreement_agreement_2,
      C = strongly_disagree_disagree_no_disagreement_agreement,
      D = strongly_disagree_disagree_no_disagreement_agreement,
      E = strongly_disagree_disagree_no_disagreement_agreement,
      F = strongly_disagree_disagree_no_disagreement_agreement,
      G = strongly_disagree_disagree_no_disagreement_agreement,
      H = strongly_disagree_disagree_no_disagreement_agreement,
      I = strongly_disagree_disagree_no_disagreement_agreement,
      J = strongly_disagree_disagree_no_disagreement_agreement,
      K = strongly_disagree_disagree_no_disagreement_agreement
    ),
    compmv = list(
      `2B` = no_valid_data,
      `3B` = no_valid_data,
      B = na_see_brmalc_in_lasab228,
      C = no_valid_data,
      D = no_valid_data,
      E = no_valid_data,
      F = no_valid_data,
      G = no_valid_data,
      H = no_valid_data,
      I = no_valid_data,
      J = no_valid_data,
      K = no_valid_data
    ),
    initmv = list(
      `2B` = no_valid_data,
      `3B` = no_valid_data,
      B = na_see_brmalc_in_lasab228,
      C = no_valid_data,
      D = no_valid_data,
      E = no_valid_data,
      F = no_valid_data,
      G = no_valid_data,
      H = no_valid_data,
      I = no_valid_data,
      J = no_valid_data,
      K = no_valid_data
    )
  ),

  value_labels_harmonized = list(
    advemv = not_available_2,
    alcmv = not_available_2,
    alcos01 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos02 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos03 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos04 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos05 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos06 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos07 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos08 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos09 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos10 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos11 = strongly_disagree_disagree_no_disagreement_agreement_3,
    alcos12 = strongly_disagree_disagree_no_disagreement_agreement_3,
    compmv = not_available_2,
    initmv = not_available_2
  )
)
