## LASA filecode 112 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_112 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bqaid1",
      "bqaid2",
      "bqaid3",
      "bqaid4",
      "bqaid5",
      "bqaid6",
      "bqaid7",
      "bqaid8",
      "bqaid1",
      "bqaid2",
      "bqaid4",
      "bqaid6",
      "bqaid7",
      "bqaid9",
      "bqaid1",
      "bqaid2",
      "bqaid3",
      "bqaid4",
      "bqaid5",
      "bqaid6",
      "bqaid7",
      "bqaid8",
      "fqaid1",
      "fqaid2",
      "fqaid3",
      "fqaid4",
      "fqaid5",
      "fqaid6",
      "fqaid7",
      "fqaid8",
      "gqaid1",
      "gqaid2",
      "gqaid4",
      "gqaid6",
      "gqaid7",
      "gqaid9",
      "hqaid1",
      "hqaid2",
      "hqaid4",
      "hqaid6",
      "hqaid7",
      "hqaid9",
      "iqaid1",
      "iqaid2",
      "iqaid4",
      "iqaid6",
      "iqaid7",
      "iqaid9",
      "jqaid1",
      "jqaid2",
      "jqaid4",
      "jqaid6",
      "jqaid7",
      "jqaid9",
      "kqaid1",
      "kqaid2",
      "kqaid4",
      "kqaid6",
      "kqaid7",
      "kqaid9",
      "bmaid1",
      "bmaid2",
      "bmaid4",
      "bmaid6",
      "bmaid7",
      "bmaid9"
    ),
    canonical_name = c(
      "qaid1",
      "qaid2",
      "qaid3",
      "qaid4",
      "qaid5",
      "qaid6",
      "qaid7",
      "qaid8",
      "qaid1",
      "qaid2",
      "qaid4",
      "qaid6",
      "qaid7",
      "qaid9",
      "qaid1",
      "qaid2",
      "qaid3",
      "qaid4",
      "qaid5",
      "qaid6",
      "qaid7",
      "qaid8",
      "qaid1",
      "qaid2",
      "qaid3",
      "qaid4",
      "qaid5",
      "qaid6",
      "qaid7",
      "qaid8",
      "qaid1",
      "qaid2",
      "qaid4",
      "qaid6",
      "qaid7",
      "qaid9",
      "qaid1",
      "qaid2",
      "qaid4",
      "qaid6",
      "qaid7",
      "qaid9",
      "qaid1",
      "qaid2",
      "qaid4",
      "qaid6",
      "qaid7",
      "qaid9",
      "qaid1",
      "qaid2",
      "qaid4",
      "qaid6",
      "qaid7",
      "qaid9",
      "qaid1",
      "qaid2",
      "qaid4",
      "qaid6",
      "qaid7",
      "qaid9",
      "maid1",
      "maid2",
      "maid4",
      "maid6",
      "maid7",
      "maid9"
    ),
    variable_label = c(
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 3: do not pay",
      "Assistance 4: independent",
      "Assistance 5: burden",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 8: long waiting",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 3: do not pay",
      "Assistance 4: independent",
      "Assistance 5: burden",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 8: long waiting",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 3: do not pay",
      "Assistance 4: independent",
      "Assistance 5: burden",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 8: long waiting",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal"
    ),
    harmonized_var_label = c(
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 3: do not pay",
      "Assistance 4: independent",
      "Assistance 5: burden",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 8: long waiting",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 3: do not pay",
      "Assistance 4: independent",
      "Assistance 5: burden",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 8: long waiting",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 3: do not pay",
      "Assistance 4: independent",
      "Assistance 5: burden",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 8: long waiting",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal",
      "Assistance 1: professional",
      "Assistance 2: children",
      "Assistance 4: independent",
      "Assistance 6: personal",
      "Assistance 7: official services",
      "Assistance 9: too often appeal"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qaid1 = list(
      `2B` = strongly_disagree_disagree_no_agreement_disagreement,
      `3B` = strongly_disagree_disagree_no_agreement_disagreement_3,
      B = strongly_disagree_disagree_no_agreement_disagreement,
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement_3,
      H = strongly_disagree_disagree_no_agreement_disagreement_3,
      I = strongly_disagree_disagree_no_agreement_disagreement_3,
      J = strongly_disagree_disagree_no_agreement_disagreement_3,
      K = strongly_disagree_disagree_no_agreement_disagreement_3
    ),
    qaid2 = list(
      `2B` = strongly_disagree_disagree_no_agreement_disagreement,
      `3B` = strongly_disagree_disagree_no_agreement_disagreement_3,
      B = strongly_disagree_disagree_no_agreement_disagreement,
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement_3,
      H = strongly_disagree_disagree_no_agreement_disagreement_3,
      I = strongly_disagree_disagree_no_agreement_disagreement_3,
      J = strongly_disagree_disagree_no_agreement_disagreement_3,
      K = strongly_disagree_disagree_no_agreement_disagreement_3
    ),
    qaid3 = list(
      `2B` = strongly_disagree_disagree_no_agreement_disagreement,
      B = strongly_disagree_disagree_no_agreement_disagreement,
      F = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qaid4 = list(
      `2B` = strongly_disagree_disagree_no_agreement_disagreement,
      `3B` = strongly_disagree_disagree_no_agreement_disagreement_3,
      B = strongly_disagree_disagree_no_agreement_disagreement,
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement_3,
      H = strongly_disagree_disagree_no_agreement_disagreement_3,
      I = strongly_disagree_disagree_no_agreement_disagreement_3,
      J = strongly_disagree_disagree_no_agreement_disagreement_3,
      K = strongly_disagree_disagree_no_agreement_disagreement_3
    ),
    qaid5 = list(
      `2B` = strongly_disagree_disagree_no_agreement_disagreement,
      B = strongly_disagree_disagree_no_agreement_disagreement,
      F = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qaid6 = list(
      `2B` = strongly_disagree_disagree_no_agreement_disagreement,
      `3B` = strongly_disagree_disagree_no_agreement_disagreement_3,
      B = strongly_disagree_disagree_no_agreement_disagreement,
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement_3,
      H = strongly_disagree_disagree_no_agreement_disagreement_3,
      I = strongly_disagree_disagree_no_agreement_disagreement_3,
      J = strongly_disagree_disagree_no_agreement_disagreement_3,
      K = strongly_disagree_disagree_no_agreement_disagreement_3
    ),
    qaid7 = list(
      `2B` = strongly_disagree_disagree_no_agreement_disagreement,
      `3B` = strongly_disagree_disagree_no_agreement_disagreement_3,
      B = strongly_disagree_disagree_no_agreement_disagreement,
      F = strongly_disagree_disagree_no_agreement_disagreement,
      G = strongly_disagree_disagree_no_agreement_disagreement_3,
      H = strongly_disagree_disagree_no_agreement_disagreement_3,
      I = strongly_disagree_disagree_no_agreement_disagreement_3,
      J = strongly_disagree_disagree_no_agreement_disagreement_3,
      K = strongly_disagree_disagree_no_agreement_disagreement_3
    ),
    qaid8 = list(
      `2B` = strongly_disagree_disagree_no_agreement_disagreement,
      B = strongly_disagree_disagree_no_agreement_disagreement,
      F = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qaid9 = list(
      `3B` = strongly_disagree_disagree_no_agreement_disagreement_3,
      G = strongly_disagree_disagree_no_agreement_disagreement_3,
      H = strongly_disagree_disagree_no_agreement_disagreement_3,
      I = strongly_disagree_disagree_no_agreement_disagreement_3,
      J = strongly_disagree_disagree_no_agreement_disagreement_3,
      K = strongly_disagree_disagree_no_agreement_disagreement_3
    ),
    maid1 = list(
      MB = strongly_disagree_disagree_no_agreement_disagreement_4
    ),
    maid2 = list(
      MB = strongly_disagree_disagree_no_agreement_disagreement_4
    ),
    maid4 = list(
      MB = strongly_disagree_disagree_no_agreement_disagreement_4
    ),
    maid6 = list(
      MB = strongly_disagree_disagree_no_agreement_disagreement_4
    ),
    maid7 = list(
      MB = strongly_disagree_disagree_no_agreement_disagreement_4
    ),
    maid9 = list(
      MB = strongly_disagree_disagree_no_agreement_disagreement_4
    )
  ),

  value_labels_harmonized = list(
    maid1 = strongly_disagree_disagree_neither_agree_nor_disagree_2,
    maid2 = strongly_disagree_disagree_neither_agree_nor_disagree_2,
    maid4 = strongly_disagree_disagree_neither_agree_nor_disagree_2,
    maid6 = strongly_disagree_disagree_neither_agree_nor_disagree_2,
    maid7 = strongly_disagree_disagree_neither_agree_nor_disagree_2,
    maid9 = strongly_disagree_disagree_neither_agree_nor_disagree_2,
    qaid1 = strongly_disagree_disagree_neither_agree_nor_disagree,
    qaid2 = strongly_disagree_disagree_neither_agree_nor_disagree,
    qaid3 = strongly_disagree_disagree_neither_agree_nor_disagree,
    qaid4 = strongly_disagree_disagree_neither_agree_nor_disagree,
    qaid5 = strongly_disagree_disagree_neither_agree_nor_disagree,
    qaid6 = strongly_disagree_disagree_neither_agree_nor_disagree,
    qaid7 = strongly_disagree_disagree_neither_agree_nor_disagree,
    qaid8 = strongly_disagree_disagree_neither_agree_nor_disagree,
    qaid9 = strongly_disagree_disagree_neither_agree_nor_disagree
  )
)
