## LASA filecode 158 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_158 <- list(
  variables = data.frame(
    wave = c(
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H"
    ),
    variable_name = c(
      "bmpeakf1",
      "bmpeakf2",
      "bmpeakf3",
      "bmpeakfc",
      "bmpeakfp",
      "bmpeakfu",
      "bmpeamax",
      "cmpeakf1",
      "cmpeakf2",
      "cmpeakf3",
      "cmpeakfc",
      "cmpeakfl",
      "cmpeakfp",
      "cmpeakfu",
      "cmpeamax",
      "cmrmpf",
      "dmpeakf1",
      "dmpeakf2",
      "dmpeakf3",
      "dmpeakfp",
      "dmpeakfu",
      "dpeakfc",
      "empeakf1",
      "empeakf2",
      "empeakf3",
      "empeakfm",
      "empeakfp",
      "empeakfu",
      "epeakfc",
      "gmpeakf1",
      "gmpeakf2",
      "gmpeakf3",
      "gmpeakfm",
      "gmpeakfp",
      "gmpeakfu",
      "gpeakfc",
      "hmpeakf1",
      "hmpeakf2",
      "hmpeakf3",
      "hmpeakfm",
      "hmpeakfp",
      "hmpeakfu",
      "hpeakfc"
    ),
    canonical_name = c(
      "mpeakf1",
      "mpeakf2",
      "mpeakf3",
      "mpeakfc",
      "mpeakfp",
      "mpeakfu",
      "mpeamax",
      "mpeakf1",
      "mpeakf2",
      "mpeakf3",
      "mpeakfc",
      "mpeakfl",
      "mpeakfp",
      "mpeakfu",
      "mpeamax",
      "mrmpf",
      "mpeakf1",
      "mpeakf2",
      "mpeakf3",
      "mpeakfp",
      "mpeakfu",
      "peakfc",
      "mpeakf1",
      "mpeakf2",
      "mpeakf3",
      "mpeakfm",
      "mpeakfp",
      "mpeakfu",
      "peakfc",
      "mpeakf1",
      "mpeakf2",
      "mpeakf3",
      "mpeakfm",
      "mpeakfp",
      "mpeakfu",
      "peakfc",
      "mpeakf1",
      "mpeakf2",
      "mpeakf3",
      "mpeakfm",
      "mpeakfp",
      "mpeakfu",
      "peakfc"
    ),
    variable_label = c(
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "participation in peakflow test",
      "position of peakflow test",
      "understanding of peakflow test",
      "peakflow: maximum score 3 trials",
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Participation with peakflow test",
      "Peakflow done: constructed",
      "position of peakflow test",
      "Understanding of peakflow test",
      "peakflow: maximum score three trials",
      "reason peakflow not done",
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Peakflow: position during test",
      "Peakflow: understanding of test",
      "Peakflow: cooperation with test",
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Peakflow: maximum score three trials",
      "Peakflow: position during test",
      "Peakflow: understanding of test",
      "Peakflow: cooperation with test",
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Peakflow: maximum score three trials",
      "Peakflow: position during test",
      "Peakflow: understanding of test",
      "Peakflow: cooperation with test",
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Peakflow: maximum score three trials",
      "Peakflow: position during test",
      "Peakflow: understanding of test",
      "Peakflow: cooperation with test"
    ),
    harmonized_var_label = c(
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Participation with peakflow test",
      "Peakflow: position during test",
      "Peakflow: understanding of test",
      "peakflow: maximum score three trials",
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Participation with peakflow test",
      "Peakflow done: constructed",
      "Peakflow: position during test",
      "Peakflow: understanding of test",
      "peakflow: maximum score three trials",
      "reason peakflow not done",
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Peakflow: position during test",
      "Peakflow: understanding of test",
      "Peakflow: cooperation with test",
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Peakflow: maximum score three trials",
      "Peakflow: position during test",
      "Peakflow: understanding of test",
      "Peakflow: cooperation with test",
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Peakflow: maximum score three trials",
      "Peakflow: position during test",
      "Peakflow: understanding of test",
      "Peakflow: cooperation with test",
      "Peakflow 1",
      "Peakflow 2",
      "Peakflow 3",
      "Peakflow: maximum score three trials",
      "Peakflow: position during test",
      "Peakflow: understanding of test",
      "Peakflow: cooperation with test"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mpeakf1 = list(
      B = c(`-2` = "R refused"),
      C = c(`-3` = "na, wrong skip", `-2` = "na, see CMPEAKFL", `-1` = "na, asked"),
      D = r_refused_no_valid_measurement,
      E = attempted_score_60,
      G = attempted_score_60,
      H = attempted_score_60
    ),
    mpeakf2 = list(
      B = no_valid_data_2,
      D = r_refused_no_valid_measurement,
      E = attempted_score_60,
      G = attempted_score_60,
      H = attempted_score_60
    ),
    mpeakfc = list(
      B = excellent_good_fair_bad_refused_other_reason
    ),
    mpeakfp = list(
      B = c(
        `-1` = "no answer, asked",
        `1` = "standing",
        `2` = "sitting",
        `3` = "lying down",
        `4` = "other"
      ),
      C = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see CMPEAKFL",
        `-1` = "na, asked",
        `1` = "standing",
        `2` = "sitting",
        `3` = "lying down",
        `10` = "other: not done",
        `20` = "other : not able to: physical",
        `30` = "other: not able to: cognitive",
        `40` = "other: not done: technical"
      ),
      D = standing_sitting_lying,
      E = standing_sitting_lying,
      G = standing_sitting_lying,
      H = c(
        `-2` = "no valid measurement",
        `-1` = "na, asked",
        `1` = "standing",
        `2` = "sitting",
        `3` = "lying"
      )
    ),
    mpeakfu = list(
      B = c(
        `-2` = "no answer, skipped",
        `-1` = "no answer, asked",
        `1` = "excellent",
        `2` = "good",
        `3` = "fair",
        `4` = "bad",
        `5` = "refused"
      ),
      C = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see CMPEAKFL",
        `-1` = "na, asked",
        `1` = "excellent",
        `2` = "good",
        `3` = "fair",
        `4` = "bad",
        `5` = "refused",
        `10` = "other: not done",
        `20` = "other : not able to: physical",
        `30` = "other: not able to: cognitive",
        `40` = "other: not done: technical"
      ),
      D = excellent_good_fair_bad_refused_other,
      E = excellent_good_fair_bad_refused_other,
      G = excellent_good_fair_bad_refused_other,
      H = excellent_good_fair_bad_refused_other
    ),
    mpeamax = list(
      B = c(`-2` = "R refused", `-1` = "no valid data"),
      C = c(`-2` = "na, see CMPEAKFL")
    ),
    mpeakfl = list(
      C = done_not_done_terminated_not_able_physical
    ),
    mrmpf = list(
      C = refused_not_able_cognitive_not_able_physical
    ),
    mpeakf3 = list(
      D = r_refused_no_valid_measurement,
      E = attempted_score_60,
      G = attempted_score_60,
      H = attempted_score_60
    )
  ),

  value_labels_harmonized = list(
    mpeakf1 = c(
      `-3` = "na, wrong skip",
      `-2` = "R refused / na, see CMPEAKFL / test not done",
      `-1` = "na, asked / no valid measurement",
      `30` = "attempted score < 60"
    ),
    mpeakf2 = c(
      `-2` = "R refused / test not done",
      `-1` = "no valid data / no valid measurement",
      `30` = "attempted score < 60"
    ),
    mpeakf3 = c(
      `-2` = "R refused / test not done",
      `-1` = "no valid measurement",
      `30` = "attempted score < 60"
    ),
    mpeakfc = excellent_good_fair_bad_refused_other_reason,
    mpeakfl = done_not_done_terminated_not_able_physical,
    mpeakfp = c(
      `-3` = "na, wrong skip",
      `-2` = "na, see CMPEAKFL / no valid measurement",
      `-1` = "no answer, asked",
      `1` = "standing",
      `2` = "sitting",
      `3` = "lying down",
      `4` = "other",
      `10` = "other: not done",
      `20` = "other : not able to: physical",
      `30` = "other: not able to: cognitive",
      `40` = "other: not done: technical"
    ),
    mpeakfu = c(
      `-3` = "na, wrong skip",
      `-2` = "no answer, skipped / na, see CMPEAKFL / no valid measurement",
      `-1` = "no answer, asked",
      `1` = "excellent",
      `2` = "good",
      `3` = "fair",
      `4` = "bad",
      `5` = "refused",
      `6` = "other",
      `10` = "other: not done",
      `20` = "other : not able to: physical",
      `30` = "other: not able to: cognitive",
      `40` = "other: not done: technical"
    ),
    mpeamax = c(`-2` = "R refused / na, see CMPEAKFL", `-1` = "no valid data"),
    mrmpf = refused_not_able_cognitive_not_able_physical
  )
)
