## LASA filecode 160 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_160 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bmagewmx",
      "bmhage25",
      "bmwage25",
      "bmwage40",
      "bmweightch",
      "bmweightchkg",
      "bmweightchr",
      "bmweightchrc",
      "bmweightgr",
      "bmweightlr",
      "bmwmax",
      "bmagemxw",
      "bmapp6m",
      "bmapp7d",
      "bmattw",
      "bmealt6m",
      "bmestw",
      "bmhage25",
      "bmmaxw",
      "bmprob6m",
      "bmsatw",
      "bmwage25",
      "bmwage40",
      "bmweightch",
      "bmweightchkg",
      "bmweightchrc",
      "bmweightgr",
      "bmweightlr",
      "bmweightlr2",
      "bmweightr2",
      "bmheight40y",
      "bmweightage",
      "bmweightch",
      "bmweightchcr",
      "bmweightchkg",
      "bmweightchr",
      "bmweightgr",
      "bmweighthigh",
      "bmweightk40y",
      "bmweightlr",
      "cmheight25y",
      "cmweightch",
      "cmweightchkg",
      "cmweightchr",
      "cmweightchrc",
      "cmweightgr",
      "cmweightlow",
      "cmweightlr",
      "dmweightch",
      "dmweightchkg",
      "dmweightchr",
      "dmweightchrc",
      "dmweightgr",
      "dmweightlr",
      "emweightch",
      "emweightchkg",
      "emweightchr",
      "emweightchrc",
      "emweightgr",
      "emweightlr",
      "fmattw",
      "fmestw",
      "fmlwm01",
      "fmlwm02",
      "fmlwm03",
      "fmlwm04",
      "fmlwm05",
      "fmlwm06",
      "fmlwm07",
      "fmlwm08",
      "fmlwm09",
      "fmlwm10",
      "fmlwm11",
      "fmlwm12",
      "fmlwm13",
      "fmlwm14",
      "fmlwm15",
      "fmsatw",
      "fmweightch",
      "fmweightchkg",
      "fmweightchr",
      "fmweightchrc",
      "fmweightgr",
      "fmweightlr",
      "gmattw",
      "gmestw",
      "gmlwm01",
      "gmlwm02",
      "gmlwm03",
      "gmlwm04",
      "gmlwm05",
      "gmlwm06",
      "gmlwm07",
      "gmlwm08",
      "gmlwm09",
      "gmlwm10",
      "gmlwm11",
      "gmlwm12",
      "gmlwm13",
      "gmlwm14",
      "gmlwm15",
      "gmsatw",
      "gmweightch",
      "gmweightchkg",
      "gmweightchr",
      "gmweightchrc",
      "gmweightgr",
      "gmweightlr",
      "hmapp6m",
      "hmapp7d",
      "hmattw",
      "hmealt6m",
      "hmestw",
      "hmprob6m",
      "hmsatw",
      "hmwage25",
      "hmweightch",
      "hmweightchkg",
      "hmweightchrc",
      "hmweightgr",
      "hmweightlr",
      "hmweightlr2",
      "hmweightr2",
      "imapp7d",
      "imeatl6m",
      "imestw",
      "imhage25",
      "improb6m",
      "imwage25",
      "imwage40",
      "imweightch",
      "imweightchkgg",
      "imweightchkgl",
      "imweightchrc",
      "imweightgr",
      "imweightgr2",
      "imweightlr",
      "imweightlr2",
      "jmapp7d",
      "jmeatl6m",
      "jmestw",
      "jmprob6m",
      "jmweightch",
      "jmweightchkgg",
      "jmweightchkgl",
      "jmweightgr2",
      "jmweightlr2",
      "bmwlbelt",
      "bmwlclot",
      "bmwloss",
      "bmwlwatc"
    ),
    canonical_name = c(
      "magewmx",
      "mhage25",
      "mwage25",
      "mwage40",
      "mweightch",
      "mweightchkg",
      "mweightchr",
      "mweightchrc",
      "mweightgr",
      "mweightlr",
      "mwmax",
      "magemxw",
      "mapp6m",
      "mapp7d",
      "mattw",
      "mealt6m",
      "mestw",
      "mhage25",
      "mmaxw",
      "mprob6m",
      "msatw",
      "mwage25",
      "mwage40",
      "mweightch",
      "mweightchkg",
      "mweightchrc",
      "mweightgr",
      "mweightlr",
      "mweightlr2",
      "mweightgr2",
      "mheight40y",
      "mweightage",
      "mweightch",
      "mweightchrc",
      "mweightchkg",
      "mweightchr",
      "mweightgr",
      "mweighthigh",
      "mweightk40y",
      "mweightlr",
      "mheight25y",
      "mweightch",
      "mweightchkg",
      "mweightchr",
      "mweightchrc",
      "mweightgr",
      "mweightlow",
      "mweightlr",
      "mweightch",
      "mweightchkg",
      "mweightchr",
      "mweightchrc",
      "mweightgr",
      "mweightlr",
      "mweightch",
      "mweightchkg",
      "mweightchr",
      "mweightchrc",
      "mweightgr",
      "mweightlr",
      "mattw",
      "mestw",
      "mlwm01",
      "mlwm02",
      "mlwm03",
      "mlwm04",
      "mlwm05",
      "mlwm06",
      "mlwm07",
      "mlwm08",
      "mlwm09",
      "mlwm10",
      "mlwm11",
      "mlwm12",
      "mlwm13",
      "mlwm14",
      "mlwm15",
      "msatw",
      "mweightch",
      "mweightchkg",
      "mweightchr",
      "mweightchrc",
      "mweightgr",
      "mweightlr",
      "mattw",
      "mestw",
      "mlwm01",
      "mlwm02",
      "mlwm03",
      "mlwm04",
      "mlwm05",
      "mlwm06",
      "mlwm07",
      "mlwm08",
      "mlwm09",
      "mlwm10",
      "mlwm11",
      "mlwm12",
      "mlwm13",
      "mlwm14",
      "mlwm15",
      "msatw",
      "mweightch",
      "mweightchkg",
      "mweightchr",
      "mweightchrc",
      "mweightgr",
      "mweightlr",
      "mapp6m",
      "mapp7d",
      "mattw",
      "mealt6m",
      "mestw",
      "mprob6m",
      "msatw",
      "mwage25",
      "mweightch",
      "mweightchkg",
      "mweightchrc",
      "mweightgr",
      "mweightlr",
      "mweightlr2",
      "mweightgr2",
      "mapp7d",
      "meatl6m",
      "mestw",
      "mhage25",
      "mprob6m",
      "mwage25",
      "mwage40",
      "mweightch",
      "mweightchkgg",
      "mweightchkgl",
      "mweightchrc",
      "mweightgr",
      "mweightgr2",
      "mweightlr",
      "mweightlr2",
      "mapp7d",
      "meatl6m",
      "mestw",
      "mprob6m",
      "mweightch",
      "mweightchkgg",
      "mweightchkgl",
      "mweightgr2",
      "mweightlr2",
      "mwlbelt",
      "mwlclot",
      "mwloss",
      "mwlwatc"
    ),
    variable_label = c(
      "Weight: age at maximum weight",
      "Height: height at age 25",
      "Weight: weight at age 25",
      "Weight: weight at age 40",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Weight: maximum in lifetime",
      "Age at maximum weight",
      "Appetite last 6 months (average)",
      "Appetite last 7 days",
      "Pay attention to body weight",
      "Eating less last 6 months (problems)",
      "Estimation body weight",
      "Height at age 25",
      "Maximum weight in lifetime",
      "psychological stress or severe sickness last 6 months",
      "Satisfaction with body weight",
      "Weight at age 25",
      "Weight at age 40",
      "Weight: change last 6 months",
      "Weight change kilogram",
      "Weight change other reason: coded",
      "Reason weight gain: coded",
      "Reason weight loss: coded",
      "Weight loss reason",
      "Weight gain reason",
      "Length: at 40 in centimeters",
      "Weight: highest in life age",
      "Weight: change",
      "Weight: change reason: coded",
      "Weight: change kilograms",
      "Weight: change reason",
      "Reason weight gain",
      "Weight: highest in life kilogram",
      "Weight: at 40 in kilogram",
      "Reason weight loss",
      "Height: at age 25 in centimeters",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Weight: lowest after age 25",
      "Reason weight loss",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Pay attention to body weight",
      "Estimation body weight",
      "LW method 1: eat less",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "Satisfied with body weight",
      "Weight: change last 6 months",
      "Weight: change kilogram",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Pay attention to body weight",
      "Estimation body weight",
      "LW method 1: eat less",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "Satisfied with body weight",
      "Weight: change last 6 months",
      "Weight: change kilogram",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Appetite last 6 months (average)",
      "Appetite last 7 days",
      "Pay attention to body weight",
      "Eating less last 6 months (problems)",
      "Estimation body weight",
      "psychological stress or severe sickness last 6 months",
      "Satisfaction with body weight",
      "Weight at age 25",
      "Weight: change last 6 months",
      "Weight change kilogram",
      "Weight change other reason: coded",
      "Reason weight gain: coded",
      "Reason weight loss: coded",
      "Weight loss reason",
      "Weight gain reason",
      "Appetite last 7 days",
      "Eating less last 6 months (problems)",
      "Estimation body weight",
      "Height at age 25",
      "Psychological stress or severe sickness last 6 months",
      "Weight at age 25",
      "Weight at age 40",
      "Weight: change last 6 months",
      "Weight gain kilogram",
      "Weight loss kilogram",
      "Weight change other: coded",
      "Reason weight gain: coded",
      "Weight gain reason",
      "Reason weight loss: coded",
      "Weight loss reason",
      "Appetite last 7 days",
      "Eating less last 6 months (problems)",
      "Estimation body weight",
      "Psychological stress or severe sickness last 6 months",
      "Weight: change last 6 months",
      "Weight gain kilogram",
      "Weight loss kilogram",
      "Weight gain reason",
      "Weight loss reason",
      "Unintentional weight loss in past 6 months: tightened belt",
      "Unintentional weight loss in past 6 months: looser fitting clothing",
      "Unintentional weight loss in past 6 months: lost 4 kg or more",
      "Unintentional weight loss in past 6 months: looser fitting watch"
    ),
    harmonized_var_label = c(
      "Weight: age at maximum weight",
      "Height at age 25",
      "Weight at age 25",
      "Weight at age 40",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Weight: maximum in lifetime",
      "Age at maximum weight",
      "Appetite last 6 months (average)",
      "Appetite last 7 days",
      "Pay attention to body weight",
      "Eating less last 6 months (problems)",
      "Estimation body weight",
      "Height at age 25",
      "Maximum weight in lifetime",
      "Psychological stress or severe sickness last 6 months",
      "Satisfaction with body weight",
      "Weight at age 25",
      "Weight at age 40",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Weight loss reason",
      "Weight gain reason",
      "Length: at 40 in centimeters",
      "Weight: highest in life age",
      "Weight: change last 6 months",
      "Weight: change reason: coded",
      "Weight: change kilograms",
      "Weight: change reason",
      "Reason weight gain",
      "Weight: highest in life kilogram",
      "Weight: at 40 in kilogram",
      "Reason weight loss",
      "Height: at age 25 in centimeters",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Weight: lowest after age 25",
      "Reason weight loss",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Pay attention to body weight",
      "Estimation body weight",
      "LW method 1: eat less",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "Satisfaction with body weight",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Pay attention to body weight",
      "Estimation body weight",
      "LW method 1: eat less",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "LW method",
      "Satisfaction with body weight",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Appetite last 6 months (average)",
      "Appetite last 7 days",
      "Pay attention to body weight",
      "Eating less last 6 months (problems)",
      "Estimation body weight",
      "Psychological stress or severe sickness last 6 months",
      "Satisfaction with body weight",
      "Weight at age 25",
      "Weight: change last 6 months",
      "Weight: change kilograms",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Reason weight loss",
      "Weight loss reason",
      "Weight gain reason",
      "Appetite last 7 days",
      "Eating less last 6 months (problems)",
      "Estimation body weight",
      "Height at age 25",
      "Psychological stress or severe sickness last 6 months",
      "Weight at age 25",
      "Weight at age 40",
      "Weight: change last 6 months",
      "Weight gain kilogram",
      "Weight loss kilogram",
      "Weight: change reason: coded",
      "Reason weight gain",
      "Weight gain reason",
      "Reason weight loss",
      "Weight loss reason",
      "Appetite last 7 days",
      "Eating less last 6 months (problems)",
      "Estimation body weight",
      "Psychological stress or severe sickness last 6 months",
      "Weight: change last 6 months",
      "Weight gain kilogram",
      "Weight loss kilogram",
      "Weight gain reason",
      "Weight loss reason",
      "Unintentional weight loss in past 6 months: tightened belt",
      "Unintentional weight loss in past 6 months: looser fitting clothing",
      "Unintentional weight loss in past 6 months: lost 4 kg or more",
      "Unintentional weight loss in past 6 months: looser fitting watch"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "categorical",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mweightch = list(
      `2B` = not_changed_gained_weight_lost_weight,
      `3B` = not_changed_gained_weight_lost_weight,
      B = c(
        `-3` = "no valid data",
        `-2` = "no answer, routing",
        `-1` = "no answer, asked",
        `1` = "not changed",
        `2` = "gained weight",
        `3` = "lost weight"
      ),
      C = not_changed_gained_weight_lost_weight_2,
      D = not_changed_gained_weight_lost_weight_2,
      E = not_changed_gained_weight_lost_weight_2,
      F = not_changed_gained_weight_lost_weight,
      G = not_changed_gained_weight_lost_weight,
      H = not_changed_gained_weight_lost_weight,
      I = not_changed_gained_weight_lost_weight_3,
      J = not_changed_gained_weight_lost_weight_3
    ),
    mweightchkg = list(
      `2B` = na_see_c_d_e_bmweightch_na_asked,
      `3B` = na_see_h_bmweightch_na_asked,
      B = no_valid_data_no_answer_routing_no_answer_asked,
      C = na_see_c_d_e_bmweightch_na_asked,
      D = na_see_c_d_e_bmweightch_na_asked,
      E = na_see_c_d_e_bmweightch_na_asked,
      F = na_see_f_gmweightch_na_asked,
      G = na_see_f_gmweightch_na_asked,
      H = na_see_h_bmweightch_na_asked
    ),
    mweightchr = list(
      `2B` = sickness_diet_social_factors,
      B = c(
        `-2` = "na, see BMWEIGHTCH",
        `-1` = "na, asked",
        `1` = "sickness",
        `2` = "diet",
        `3` = "social factors",
        `4` = "other, see WEIGHTCHCR"
      ),
      C = sickness_diet_social_factors,
      D = sickness_diet_social_factors,
      E = sickness_diet_social_factors,
      F = sickness_diet_social_factors_other_see_f_gmweightchrc,
      G = sickness_diet_social_factors_other_see_f_gmweightchrc
    ),
    mweightchrc = list(
      `2B` = sickness_unintentional_medication_unintentional,
      `3B` = sickness_unintentional_medication_unintentional_2,
      B = sickness_unintentional_medication_unintentional,
      C = sickness_unintentional_medication_unintentional,
      D = sickness_unintentional_medication_unintentional,
      E = sickness_unintentional_medication_unintentional,
      F = sickness_unintentional_medication_unintentional,
      G = c(
        `-3` = "no valid data",
        `-2` = "no weight change",
        `-1` = "no answer, asked see *Table reason",
        `1` = "sickness (unintentional)",
        `1.1` = "medication (unintentional)",
        `1.2` = "physical inactive due to sickness (unintentional)",
        `2` = "diet (intentional)",
        `2.1` = "eating less or different (unknown)",
        `2.2` = "eating more or different (unintentional)",
        `2.3` = "eating more and physical inactive (unintentional)",
        `2.4` = "quit smoking (unknown)",
        `2.5` = "smoking (unknown)",
        `2.6` = "eating less and physical active (intentional)",
        `2.7` = "eating less or different (unintentional)",
        `3` = "social factors (unintentional)",
        `3.1` = "social factors recoded (unintentional)",
        `5` = "do not know (unintentional)",
        `5.1` = "other reason (implausible reason) (unknown)",
        `6` = "physical activities (intentional)",
        `6.1` = "physical activity (unknown)",
        `6.2` = "physical inactivity (unintentional)",
        `6.3` = "working harder (unintentional)",
        `6.4` = "physical activity (unintentional)",
        `7` = "older age (unintentional)",
        `8` = "loss of appetite (unintentional)",
        `9` = "diuretics or dehydration",
        `9.1` = "oedeme/ascites",
        `9.2` = "quit prednison"
      ),
      H = sickness_unintentional_medication_unintentional_2,
      I = c(
        `-3` = "no valid data",
        `-2` = "na, see IMWEIGHTLR2/GR2",
        `-1` = "na, asked see *Table Reason",
        `1` = "sickness (unintentional)",
        `1.1` = "medication (unintentional)",
        `1.2` = "physical inactive due to sickness (unintentional)",
        `2` = "diet (intentional)",
        `2.1` = "eating less or different (unknown)",
        `2.2` = "eating more or different (unintentional)",
        `2.3` = "eating more and physical inactive (unintentional)",
        `2.4` = "quit smoking (unknown)",
        `2.5` = "smoking (unknown)",
        `2.6` = "eating less and physical active (intentional)",
        `2.7` = "eating less or different (unintentional)",
        `3` = "social factors (unintentional)",
        `3.1` = "social factors recoded (unintentional)",
        `5` = "do not know (unintentional)",
        `5.1` = "other reason (implausible reason) (unknown)",
        `6` = "physical activities (intentional)",
        `6.1` = "physical activity (unknown)",
        `6.2` = "physical inactivity (unintentional)",
        `6.3` = "working harder (unintentional)",
        `6.4` = "physical activity (unintentional)",
        `7` = "older age (unintentional)",
        `8` = "loss of appetite (unintentional)",
        `9` = "diuretics or dehydration",
        `9.1` = "oedeme/ascites",
        `9.2` = "quit prednison"
      )
    ),
    mweightgr = list(
      `2B` = related_to_eating_physical_inactivity,
      `3B` = sickness_related_to_eating_physical_inactivity,
      B = c(
        `-3` = "no valid data",
        `-2` = "no weight gain",
        `-1` = "no answer, asked",
        `1` = "related to eating",
        `2` = "physical inactivity",
        `3` = "eating and physical inactivity",
        `4` = "medical reason",
        `5` = "other"
      ),
      C = related_to_eating_physical_inactivity,
      D = related_to_eating_physical_inactivity,
      E = related_to_eating_physical_inactivity,
      F = related_to_eating_physical_inactivity,
      G = related_to_eating_physical_inactivity,
      H = sickness_related_to_eating_physical_inactivity,
      I = c(
        `-3` = "no valid data",
        `-2` = "na, see IMWEIGHTGR2",
        `-1` = "na, asked",
        `1` = "sickness",
        `2` = "related to eating",
        `3` = "physical inactivity",
        `4` = "eating and physical inactivity",
        `5` = "reason unknown",
        `6` = "other reason",
        `7` = "aging",
        `8` = "social factors"
      )
    ),
    mweightlr = list(
      `2B` = voluntary_involuntary_eating_less_or_different,
      `3B` = sickness_unintentional_diet_intentional_2,
      B = voluntary_involuntary_eating_less_or_different,
      C = voluntary_involuntary_eating_less_or_different,
      D = voluntary_involuntary_eating_less_or_different,
      E = voluntary_involuntary_eating_less_or_different,
      F = voluntary_involuntary_eating_less_or_different,
      G = voluntary_involuntary_eating_less_or_different,
      H = sickness_unintentional_diet_intentional_2,
      I = c(
        `-3` = "no valid data",
        `-2` = "na, see IMWEIGHTLR2",
        `-1` = "na, asked",
        `1` = "sickness (unintentional)",
        `2` = "diet (intentional)",
        `3` = "different diet (unintentional)",
        `4` = "physical activity (intentional)",
        `5` = "reason unknown (unintentional)",
        `6` = "social factors (unintentional)",
        `7` = "other reason (7)",
        `8` = "eating less or different (unknown)",
        `9` = "eating less and physical active (intentional)",
        `10` = "physical activity (unintentional)",
        `11` = "physical activity (unknown)",
        `12` = "aging (unintentional)"
      )
    ),
    mwmax = list(
      `2B` = na_asked
    ),
    magemxw = list(
      `3B` = na_asked
    ),
    mapp6m = list(
      `3B` = good_moderate_poor,
      H = good_moderate_poor
    ),
    mapp7d = list(
      `3B` = good_moderate_poor,
      H = good_moderate_poor,
      I = good_moderate_poor_2,
      J = good_moderate_poor_2
    ),
    mattw = list(
      `3B` = yes_trying_to_lose_weight_yes_trying_not_gain_weight,
      F = yes_trying_to_lose_weight_yes_trying_not_to_gain_weight,
      G = yes_trying_to_lose_weight_yes_trying_not_to_gain_weight,
      H = yes_trying_to_lose_weight_yes_trying_not_gain_weight
    ),
    mealt6m = list(
      `3B` = did_not_eat_less_did_eat_somewhat_less,
      H = did_not_eat_less_did_eat_somewhat_less
    ),
    mestw = list(
      `3B` = severe_underweight_underweight_approx_normal_weight,
      F = c(`-1` = "na, asked", `1` = "underweight", `2` = "normal weight", `3` = "overweight"),
      G = c(
        `-1` = "na, asked",
        `1` = "severe underweight",
        `2` = "underweight",
        `3` = "normal weight",
        `4` = "overweight",
        `5` = "severe overweight"
      ),
      H = severe_underweight_underweight_approx_normal_weight,
      I = severe_underweight_underweight_approx_normal_weight_2,
      J = severe_underweight_underweight_approx_normal_weight_2
    ),
    mmaxw = list(
      `3B` = na_section_not_done
    ),
    mprob6m = list(
      `3B` = no_yes,
      H = no_yes,
      I = no_yes_238,
      J = no_yes_238
    ),
    msatw = list(
      `3B` = very_dissatisfied_dissatisfied_3,
      F = c(`-1` = "na, asked", `1` = "very", `2` = "reasonably", `3` = "a little", `4` = "not at all"),
      G = c(
        `-1` = "na, asked",
        `1` = "very dissatisfied",
        `2` = "dissatisfied",
        `3` = "neither dissatisfied nor satisfied",
        `4` = "satisfied",
        `5` = "very satisfied"
      ),
      H = very_dissatisfied_dissatisfied_3
    ),
    mweightgr2 = list(
      `3B` = sickness_eating_more_or_different,
      H = sickness_eating_more_or_different,
      I = sickness_eating_more_or_different_2,
      J = sickness_eating_more_or_different_2
    ),
    mweightlr2 = list(
      `3B` = sickness_unintentional_diet_intentional,
      H = sickness_unintentional_diet_intentional,
      I = sickness_unintentional_diet_intentional_3,
      J = sickness_unintentional_diet_intentional_3
    ),
    mweighthigh = list(
      B = no_valid_data_no_answer_routing_no_answer_asked
    ),
    mheight25y = list(
      C = na_interview_terminated
    ),
    mweightlow = list(
      C = no_valid_data_2
    ),
    mlwm01 = list(
      F = not_mentioned_mentioned_274,
      G = not_mentioned_mentioned_274
    ),
    mlwm02 = list(
      F = less_snacks,
      G = less_snacks
    ),
    mlwm03 = list(
      F = eat_less_fat,
      G = eat_less_fat
    ),
    mlwm04 = list(
      F = drink_less_alcohol,
      G = drink_less_alcohol
    ),
    mlwm05 = list(
      F = limit_types_of_food,
      G = limit_types_of_food
    ),
    mlwm06 = list(
      F = light_products,
      G = light_products
    ),
    mlwm07 = list(
      F = replacements_slim_fast,
      G = replacements_slim_fast
    ),
    mlwm08 = list(
      F = slimming_program_ww,
      G = slimming_program_ww
    ),
    mlwm09 = list(
      F = more_exercise_sports,
      G = more_exercise_sports
    ),
    mlwm10 = list(
      F = more_daily_exercise_stairs,
      G = more_daily_exercise_stairs
    ),
    mlwm11 = list(
      F = more_smoking,
      G = more_smoking
    ),
    mlwm12 = list(
      F = slimming_pills,
      G = slimming_pills
    ),
    mlwm13 = list(
      F = stomach_reduction,
      G = stomach_reduction
    ),
    mlwm14 = list(
      F = guidance_dietician,
      G = guidance_dietician
    ),
    mlwm15 = list(
      F = other_method,
      G = other_method
    ),
    mwage25 = list(
      H = na_asked,
      I = na_section_not_done_na_asked
    ),
    meatl6m = list(
      I = did_not_eat_less_did_eat_somewhat_less_2,
      J = did_not_eat_less_did_eat_somewhat_less_2
    ),
    mweightchkgg = list(
      I = na_see_i_jmweightch_na_asked,
      J = na_see_i_jmweightch_na_asked
    ),
    mweightchkgl = list(
      I = na_see_i_jmweightch_na_asked,
      J = na_see_i_jmweightch_na_asked
    ),
    mwlclot = list(
      MB = no_yes_343
    ),
    mwloss = list(
      MB = no_yes_unknown
    )
  ),

  value_labels_harmonized = list(
    magemxw = na_asked,
    mapp6m = good_moderate_poor,
    mapp7d = good_moderate_poor_2,
    mattw = c(
      `-1` = "na, asked / do not know / na, asked",
      `1` = "yes, trying to lose weight",
      `2` = "yes, trying not to gain weight",
      `3` = "yes, trying not to lose weight",
      `4` = "yes, trying to gain weight",
      `5` = "no",
      `6` = "do not know"
    ),
    mealt6m = did_not_eat_less_did_eat_somewhat_less,
    meatl6m = did_not_eat_less_did_eat_somewhat_less_2,
    mestw = c(
      `-3` = "na, section not done",
      `-1` = "na, asked",
      `1` = "underweight / severe underweight",
      `2` = "normal weight / underweight",
      `3` = "overweight / normal weight / approx.. normal weight",
      `4` = "overweight",
      `5` = "severe overweight",
      `6` = "do not know"
    ),
    mheight25y = na_interview_terminated,
    mlwm01 = not_mentioned_mentioned_274,
    mlwm02 = less_snacks,
    mlwm03 = eat_less_fat,
    mlwm04 = drink_less_alcohol,
    mlwm05 = limit_types_of_food,
    mlwm06 = light_products,
    mlwm07 = replacements_slim_fast,
    mlwm08 = slimming_program_ww,
    mlwm09 = more_exercise_sports,
    mlwm10 = more_daily_exercise_stairs,
    mlwm11 = more_smoking,
    mlwm12 = slimming_pills,
    mlwm13 = stomach_reduction,
    mlwm14 = guidance_dietician,
    mlwm15 = other_method,
    mmaxw = na_section_not_done,
    mprob6m = no_yes_238,
    msatw = c(
      `-1` = "na, asked",
      `1` = "very / very dissatisfied",
      `2` = "reasonably / dissatisfied",
      `3` = "a little / neither dissatisfied nor satisfied / not satisfied/dissatisfied",
      `4` = "not at all / satisfied",
      `5` = "very satisfied",
      `6` = "do not know"
    ),
    mwage25 = na_section_not_done_na_asked,
    mweightch = c(
      `-5` = "na, interview terminated",
      `-3` = "no valid data / na, section not done",
      `-2` = "no answer, routing",
      `-1` = "no answer, asked",
      `1` = "not changed",
      `2` = "gained weight",
      `3` = "lost weight"
    ),
    mweightchkg = no_valid_data_no_answer_routing_no_answer_asked,
    mweightchkgg = na_see_i_jmweightch_na_asked,
    mweightchkgl = na_see_i_jmweightch_na_asked,
    mweightchr = c(
      `-2` = "na, see BMWEIGHTCH",
      `-1` = "na, asked",
      `1` = "sickness",
      `2` = "diet",
      `3` = "social factors",
      `4` = "other, see WEIGHTCHCR / other, see C/D/E/BMWEIGHTCHRC / other, see F/GMWEIGHTCHRC",
      `5` = "do not know"
    ),
    mweightchrc = c(
      `-3` = "no valid data",
      `-2` = "no weight change / na, see H/BMWEIGHTLR2/GR2",
      `-1` = "no answer, asked see *Table reason",
      `1` = "sickness (unintentional)",
      `1.1` = "medication (unintentional)",
      `1.2` = "physical inactive due to sickness (unintentional)",
      `1.3` = "lost weight due to sickness; now gained weight (unintentional)",
      `2` = "diet (intentional)",
      `2.1` = "eating less or different (unknown)",
      `2.2` = "eating more or different (unintentional)",
      `2.3` = "eating more and physical inactive (unintentional)",
      `2.4` = "quit smoking (unknown)",
      `2.5` = "smoking (unknown)",
      `2.6` = "eating less and physical active (intentional)",
      `2.7` = "eating less or different (unintentional)",
      `3` = "social factors (unintentional)",
      `3.1` = "social factors recoded (unintentional)",
      `5` = "do not know (unintentional)",
      `5.1` = "other reason (implausible reason) (unknown)",
      `6` = "physical activities (intentional)",
      `6.1` = "physical activity (unknown)",
      `6.2` = "physical inactivity (unintentional)",
      `6.3` = "working harder (unintentional)",
      `6.4` = "physical activity (unintentional)",
      `7` = "older age (unintentional)",
      `8` = "loss of appetite (unintentional)",
      `9` = "diuretics or dehydration",
      `9.1` = "oedeme/ascites",
      `9.2` = "quit prednison"
    ),
    mweightgr = c(
      `-3` = "no valid data",
      `-2` = "no weight gain / na, see HMWEIGHTGR2",
      `-1` = "no answer, asked",
      `1` = "related to eating / sickness",
      `2` = "physical inactivity / related to eating",
      `3` = "eating and physical inactivity / physical inactivity",
      `4` = "medical reason / medical reasons / eating and physical inactivity",
      `5` = "other / reason unknown",
      `6` = "other reason",
      `7` = "aging",
      `8` = "social factors"
    ),
    mweightgr2 = sickness_eating_more_or_different,
    mweighthigh = no_valid_data_no_answer_routing_no_answer_asked,
    mweightlow = no_valid_data_2,
    mweightlr = c(
      `-3` = "no valid data",
      `-2` = "no weight loss / na, see HMWEIGHTLR2",
      `-1` = "no answer, asked",
      `1` = "voluntary / sickness (unintentional)",
      `2` = "involuntary / diet (intentional)",
      `3` = "eating less or different / different diet (unintentional)",
      `4` = "physical activity (intentional)",
      `5` = "reason unknown (unintentional)",
      `6` = "social factors (unintentional)",
      `7` = "other reason (7)",
      `8` = "eating less or different (unknown)",
      `9` = "eating less and physical active (intentional)",
      `10` = "physical activity (unintentional)",
      `11` = "physical activity (unknown)",
      `12` = "aging (unintentional)"
    ),
    mweightlr2 = sickness_unintentional_diet_intentional,
    mwlclot = no_yes_343,
    mwloss = no_yes_unknown,
    mwmax = na_asked
  )
)
