## LASA filecode 045 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_045 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bhosp",
      "bmedspec",
      "bpsych",
      "bpsyhosp",
      "bhosp",
      "bmedspec",
      "ziekan",
      "bhosp",
      "bmedspec",
      "bpsych",
      "bpsyhosp",
      "chosp",
      "cmedspec",
      "cpsych",
      "cpsyhosp",
      "dhosp",
      "dmedspec",
      "dpsych",
      "dpsyhosp",
      "ehosp",
      "emedspec",
      "epsych",
      "epsyhosp",
      "fhosp",
      "fmedspec",
      "fpsych",
      "fpsyhosp",
      "ghosp",
      "gmedspec",
      "gpsych",
      "gpsyhosp",
      "hhosp",
      "hmedspec",
      "hpsych",
      "hpsyhosp",
      "ziekan",
      "ihosp",
      "imedspec",
      "ipsych",
      "ipsyhosp",
      "ziekan",
      "jerh",
      "jerhn",
      "jhosp",
      "jmedspec",
      "jpsyhosp",
      "jsych",
      "seh_reden",
      "ziekan",
      "bhosp",
      "bmedspec",
      "ziekan"
    ),
    canonical_name = c(
      "hosp",
      "medspec",
      "psych",
      "psyhosp",
      "hosp",
      "medspec",
      "ziekan",
      "hosp",
      "medspec",
      "psych",
      "psyhosp",
      "hosp",
      "medspec",
      "psych",
      "psyhosp",
      "hosp",
      "medspec",
      "psych",
      "psyhosp",
      "hosp",
      "medspec",
      "psych",
      "psyhosp",
      "hosp",
      "medspec",
      "psych",
      "psyhosp",
      "hosp",
      "medspec",
      "psych",
      "psyhosp",
      "hosp",
      "medspec",
      "psych",
      "psyhosp",
      "ziekan",
      "hosp",
      "medspec",
      "psych",
      "psyhosp",
      "ziekan",
      "erh",
      "erhn",
      "hosp",
      "medspec",
      "psyhosp",
      "sych",
      "seh_reden",
      "ziekan",
      "hosp",
      "medspec",
      "ziekan"
    ),
    variable_label = c(
      "Hospitalization p 6 mo.",
      "Contacted medical specialist p 6 mo.",
      "Contacted psychiatrist p 6 mo.",
      "Psychiatric hospitalization p 6 mo.",
      "Hospitalization p 6 mo.",
      "Contacted medical specialist p 6 mo.",
      "‡ Wat was de reden voor deze opname? (what was the reason for this admission?)",
      "Hospitalization past 6 months",
      "Contacted medical specialist past 6 months",
      "Contacted psychiatrist past 6 months",
      "Psychiatric hospitalization past 6 months",
      "Hospitalization p 6 mo.",
      "Contacted medical specialist p 6 mo.",
      "Contacted psychiatrist p 6 mo.",
      "Psychiatric hospitalization p 6 mo.",
      "Hospitalization p 6 mo.",
      "Contacted medical specialist p 6 mo.",
      "Contacted psychiatrist p 6 mo.",
      "Psychiatric hospitalization p 6 mo.",
      "Hospitalization p 6 mo.",
      "Contacted medical specialist p 6 mo.",
      "Contacted psychiatrist p 6 mo.",
      "Psychiatric hospitalization p 6 mo.",
      "Hospitalization p 6 mo.",
      "Contacted medical specialist p 6 mo.",
      "Contacted psychiatrist p 6 mo.",
      "Psychiatric hospitalization p 6 mo.",
      "Hospitalization p 6 mo.",
      "Contacted medical specialist p 6 mo.",
      "Contacted psychiatrist p 6 mo.",
      "Psychiatric hospitalization p 6 mo.",
      "Hospitalization p 6 mo.",
      "Contacted medical specialist p 6 mo.",
      "Contacted psychiatrist p 6 mo.",
      "Psychiatric hospitalization p 6 mo.",
      "‡ Wat was de reden voor deze opname? (what was the reason for this admission?)",
      "Hospitalization p 6 mo.",
      "Contacted medical specialist p 6 mo.",
      "Contacted psychiatrist p 6 mo.",
      "Psychiatric hospitalization p 6 mo.",
      "‡ Wat was de reden voor deze opname? (what was the reason for this admission?)",
      "Visited emergency room hospital past 6 months",
      "Visited emergency room hospital: number of times",
      "Hospitalization past 6 months",
      "Contacted medical specialist past 6 months",
      "Psychiatric hospitalization past 6 months",
      "Contacted psychiatrist past 6 months",
      "‡ Wat was/waren de reden(en) voor het bezoeken van de SEH? (what was/were the reason(s) for visiting the emergency room?)",
      "‡ Wat was de reden voor deze opname? (what was the reason for this admission?)",
      "Hospitalization p 6 mo. (Including psych hosp.)",
      "Contacted medical specialist p 6 mo.",
      "‡ Wat was de reden voor deze opname? (what was the reason for this admission?)"
    ),
    harmonized_var_label = c(
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "Contacted psychiatrist past 6 monthsnths",
      "Psychiatric hospitalization past 6 monthsnths",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "‡ Wat was de reden voor deze opname? (what was the reason for this admission?)",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "Contacted psychiatrist past 6 monthsnths",
      "Psychiatric hospitalization past 6 monthsnths",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "Contacted psychiatrist past 6 monthsnths",
      "Psychiatric hospitalization past 6 monthsnths",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "Contacted psychiatrist past 6 monthsnths",
      "Psychiatric hospitalization past 6 monthsnths",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "Contacted psychiatrist past 6 monthsnths",
      "Psychiatric hospitalization past 6 monthsnths",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "Contacted psychiatrist past 6 monthsnths",
      "Psychiatric hospitalization past 6 monthsnths",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "Contacted psychiatrist past 6 monthsnths",
      "Psychiatric hospitalization past 6 monthsnths",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "Contacted psychiatrist past 6 monthsnths",
      "Psychiatric hospitalization past 6 monthsnths",
      "‡ Wat was de reden voor deze opname? (what was the reason for this admission?)",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "Contacted psychiatrist past 6 monthsnths",
      "Psychiatric hospitalization past 6 monthsnths",
      "‡ Wat was de reden voor deze opname? (what was the reason for this admission?)",
      "Visited emergency room hospital past 6 monthsnths",
      "Visited emergency room hospital: number of times",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "Psychiatric hospitalization past 6 monthsnths",
      "Contacted psychiatrist past 6 monthsnths",
      "‡ Wat was/waren de reden(en) voor het bezoeken van de SEH? (what was/were the reason(s) for visiting the emergency room?)",
      "‡ Wat was de reden voor deze opname? (what was the reason for this admission?)",
      "Hospitalization past 6 monthsnths",
      "Contacted medical specialist past 6 monthsnths",
      "‡ Wat was de reden voor deze opname? (what was the reason for this admission?)"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "text",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "text",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "text",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "text",
      "text",
      "numeric",
      "numeric",
      "text"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    hosp = list(
      `2B` = no_yes_r_does_not_know_refused,
      `3B` = no_yes_r_does_not_know_refused_2,
      B = no_yes_307,
      C = no_yes_r_does_not_know_refused,
      D = no_yes_r_does_not_know_refused,
      E = no_yes_r_does_not_know_refused,
      F = no_yes_r_does_not_know_refused,
      G = no_yes_r_does_not_know_refused,
      H = no_yes_r_does_not_know_refused_2,
      I = no_yes_r_does_not_know_refused_2,
      J = no_yes_r_does_not_know_refused_2,
      MB = no_yes_r_does_not_know_refused
    ),
    medspec = list(
      `2B` = no_yes_r_does_not_know_refused,
      `3B` = no_yes_r_does_not_know_refused_2,
      B = no_yes_44,
      C = no_yes_r_does_not_know_refused,
      D = no_yes_r_does_not_know_refused,
      E = no_yes_r_does_not_know_refused,
      F = no_yes_r_does_not_know_refused,
      G = no_yes_r_does_not_know_refused,
      H = no_yes_r_does_not_know_refused_2,
      I = no_yes_r_does_not_know_refused_2,
      J = no_yes_r_does_not_know_refused_2,
      MB = no_yes_r_does_not_know_refused
    ),
    psych = list(
      `2B` = no_yes_r_does_not_know_refused,
      B = no_yes_307,
      C = no_yes_r_does_not_know_refused,
      D = no_yes_r_does_not_know_refused,
      E = no_yes_r_does_not_know_refused,
      F = no_yes_r_does_not_know_refused,
      G = no_yes_r_does_not_know_refused,
      H = no_yes_r_does_not_know_refused_2,
      I = no_yes_r_does_not_know_refused_2
    ),
    psyhosp = list(
      `2B` = no_yes_r_does_not_know_refused_3,
      B = c(`-2` = "na, see BPSYCH", `-1` = "na, asked", `0` = "no", `1` = "yes"),
      C = no_yes_r_does_not_know_refused_3,
      D = no_yes_r_does_not_know_refused_3,
      E = no_yes_r_does_not_know_refused_3,
      F = no_yes_r_does_not_know_refused_3,
      G = no_yes_r_does_not_know_refused_3,
      H = no_yes_r_does_not_know_refused_4,
      I = no_yes_r_does_not_know_refused_4,
      J = no_yes_r_does_not_know_refused_2
    ),
    erh = list(
      J = no_yes_r_does_not_know_refused_2
    ),
    erhn = list(
      J = c(`-2` = "na, see JER", `-1` = "na, asked / R does not know")
    ),
    sych = list(
      J = no_yes_r_does_not_know_refused_2
    )
  ),

  value_labels_harmonized = list(
    erh = no_yes_respondent_does_not_know_refused,
    erhn = c(`-2` = "not available, routing", `-1` = "not available, asked / respondent does not know"),
    hosp = no_numeric_coding_category_1_yes_3,
    medspec = c(
      `-5` = "not available, interview terminated",
      `-4` = "not available, interview terminated",
      `-1` = "not available, asked",
      `0` = "no",
      `1` = "numeric coding category 1",
      `2` = "yes",
      `3` = "respondent does not know",
      `4` = "refused"
    ),
    psych = no_numeric_coding_category_1_yes_3,
    psyhosp = c(
      `-4` = "not available, interview terminated",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `0` = "no",
      `1` = "numeric coding category 1",
      `2` = "yes",
      `3` = "respondent does not know",
      `4` = "refused"
    ),
    sych = no_yes_respondent_does_not_know_refused
  )
)
