## LASA filecode 103 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_103 <- list(
  variables = data.frame(
    wave = c(
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J"
    ),
    variable_name = c(
      "hqmus1",
      "hqmus2",
      "hqmus3",
      "hqmus4",
      "hqmus5",
      "hqmusk6s",
      "hqsmus1",
      "hqsmus2",
      "hqsmus3",
      "hqsmus4",
      "hqsmus5",
      "hqsmus6",
      "iqmus1",
      "iqmus2",
      "iqmus3",
      "iqmus4",
      "iqmus5",
      "iqmusk6s",
      "iqsmus1",
      "iqsmus2",
      "iqsmus3",
      "iqsmus4",
      "iqsmus5",
      "iqsmus6",
      "jqmus1",
      "jqmus2",
      "jqmus4",
      "jqmus5",
      "jqmusat",
      "jqmusl",
      "jqmuslc",
      "jqmuslm",
      "jqmuslnt",
      "jqmussl",
      "jqmussl_a1",
      "jqmussl_a2",
      "jqmussl_a3",
      "jqmussl_a4",
      "jqmussl_a5",
      "jqmussl_a6",
      "jqmussl_i1",
      "jqmussl_i2",
      "jqmussl_i3",
      "jqmussl_i4",
      "jqmussl_i5",
      "jqmussl_i6",
      "jqmussl_y1",
      "jqmussl_y2",
      "jqmussl_y3",
      "jqmussl_y4",
      "jqmussl_y5",
      "jqmussl_y6",
      "jqmussln"
    ),
    canonical_name = c(
      "qmus1",
      "qmus2",
      "qmus3",
      "qmus4",
      "qmus5",
      "qmusk6s",
      "qsmus1",
      "qsmus2",
      "qsmus3",
      "qsmus4",
      "qsmus5",
      "qsmus6",
      "qmus1",
      "qmus2",
      "qmus3",
      "qmus4",
      "qmus5",
      "qmusk6s",
      "qsmus1",
      "qsmus2",
      "qsmus3",
      "qsmus4",
      "qsmus5",
      "qsmus6",
      "qmus1",
      "qmus2",
      "qmus4",
      "qmus5",
      "qmusat",
      "qmusl",
      "qmuslc",
      "qmuslm",
      "qmuslnt",
      "qmussl",
      "qmussl_a1",
      "qmussl_a2",
      "qmussl_a3",
      "qmussl_a4",
      "qmussl_a5",
      "qmussl_a6",
      "qmussl_i1",
      "qmussl_i2",
      "qmussl_i3",
      "qmussl_i4",
      "qmussl_i5",
      "qmussl_i6",
      "qmussl_y1",
      "qmussl_y2",
      "qmussl_y3",
      "qmussl_y4",
      "qmussl_y5",
      "qmussl_y6",
      "qmussln"
    ),
    variable_label = c(
      "make music",
      "type of instrument",
      "singing as a hobby",
      "number of times per 2 weeks making music or singing",
      "minutes per time",
      "kind of music: other, specified",
      "kind of music: classic",
      "kind of music: jazz",
      "kind of music: Dutch",
      "kind of music: pop",
      "kind of music: rock",
      "kind of music: other",
      "make music",
      "type of instrument",
      "singing as a hobby",
      "number of times per 2 weeks making music or singing",
      "minutes per time",
      "kind of music: other, specified",
      "kind of music: classic",
      "kind of music: jazz",
      "kind of music: Dutch",
      "kind of music: pop",
      "kind of music: rock",
      "kind of music: other",
      "making music or singing momentarily",
      "making music or singing: instrument",
      "making music or singing: number of times per 2 weeks",
      "making music or singing: minutes per time",
      "making music or singing: alone or together",
      "listening to music",
      "listening to music: number of concerts attending per year",
      "listening to music: minutes per time",
      "listening to music: number of times per 2 weeks",
      "music or singing lessons",
      "lessons 1: age at start",
      "lessons 2: age at start",
      "lessons 3: age at start",
      "lessons 4: age at start",
      "lessons 5: age at start",
      "lessons 6: age at start",
      "lessons 1: instrument",
      "lessons 2: instrument",
      "lessons 3: instrument",
      "lessons 4: instrument",
      "lessons 5: instrument",
      "lessons 6: instrument",
      "lessons 1: number of years",
      "lessons 2: number of years",
      "lessons 3: number of years",
      "lessons 4: number of years",
      "lessons 5: number of years",
      "lessons 6: number of years",
      "lessons: number of instruments (including voice)"
    ),
    harmonized_var_label = c(
      "Making music or singing",
      "Making music or singing: instrument",
      "singing as a hobby",
      "Making music or singing: number of times per 2 weeks",
      "Making music or singing: minutes per time",
      "kind of music: other, specified",
      "kind of music: classic",
      "kind of music: jazz",
      "kind of music: Dutch",
      "kind of music: pop",
      "kind of music: rock",
      "kind of music: other",
      "Making music or singing",
      "Making music or singing: instrument",
      "singing as a hobby",
      "Making music or singing: number of times per 2 weeks",
      "Making music or singing: minutes per time",
      "kind of music: other, specified",
      "kind of music: classic",
      "kind of music: jazz",
      "kind of music: Dutch",
      "kind of music: pop",
      "kind of music: rock",
      "kind of music: other",
      "Making music or singing",
      "Making music or singing: instrument",
      "Making music or singing: number of times per 2 weeks",
      "Making music or singing: minutes per time",
      "making music or singing: alone or together",
      "listening to music",
      "listening to music: number of concerts attending per year",
      "listening to music: minutes per time",
      "listening to music: number of times per 2 weeks",
      "music or singing lessons",
      "lessons 1: age at start",
      "lessons 2: age at start",
      "lessons 3: age at start",
      "lessons 4: age at start",
      "lessons 5: age at start",
      "lessons 6: age at start",
      "lessons 1: instrument",
      "lessons 2: instrument",
      "lessons 3: instrument",
      "lessons 4: instrument",
      "lessons 5: instrument",
      "lessons 6: instrument",
      "lessons 1: number of years",
      "lessons 2: number of years",
      "lessons 3: number of years",
      "lessons 4: number of years",
      "lessons 5: number of years",
      "lessons 6: number of years",
      "lessons: number of instruments (including voice)"
    ),
    var_type = c(
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "text",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "categorical",
      "numeric",
      "numeric",
      "text",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "text",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qmus1 = list(
      H = no_yes_3,
      I = no_yes_3,
      J = no_yes_339
    ),
    qmus2 = list(
      H = no_answer,
      I = no_answer,
      J = no_answer
    ),
    qmus3 = list(
      H = no_yes_3,
      I = no_yes_3
    ),
    qmus4 = list(
      H = na_see_h_iqmus1_h_iqmus3_no_answer,
      I = na_see_h_iqmus1_h_iqmus3_no_answer,
      J = c(`-2` = "na, see JQMUS1", `-1` = "no answer")
    ),
    qmus5 = list(
      H = na_see_h_iqmus1_h_iqmus3_no_answer,
      I = na_see_h_iqmus1_h_iqmus3_no_answer,
      J = c(`-2` = "na, see JQMUS4", `-1` = "no answer")
    ),
    qsmus1 = list(
      H = not_mentioned_mentioned_154,
      I = not_mentioned_mentioned_154
    ),
    qsmus2 = list(
      H = not_mentioned_mentioned_154,
      I = not_mentioned_mentioned_154
    ),
    qsmus3 = list(
      H = not_mentioned_mentioned_154,
      I = not_mentioned_mentioned_154
    ),
    qsmus4 = list(
      H = not_mentioned_mentioned_154,
      I = not_mentioned_mentioned_154
    ),
    qsmus5 = list(
      H = not_mentioned_mentioned_154,
      I = not_mentioned_mentioned_154
    ),
    qsmus6 = list(
      H = not_mentioned_mentioned_154,
      I = not_mentioned_mentioned_154
    ),
    qmusat = list(
      J = c(
        `-2` = "na, see JQMUS1",
        `-1` = "no answer",
        `1` = "always alone",
        `2` = "mostly alone",
        `3` = "changes, as often alone as together",
        `4` = "mostly together with others",
        `5` = "always together with others"
      )
    ),
    qmusl = list(
      J = no_yes_339
    ),
    qmuslc = list(
      J = na_see_jqmusl_no_answer
    ),
    qmuslm = list(
      J = c(`-2` = "na, see JQMUSLNT", `-1` = "no answer")
    ),
    qmuslnt = list(
      J = na_see_jqmusl_no_answer
    ),
    qmussl = list(
      J = no_yes_3
    ),
    qmussl_a1 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_a2 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_a3 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_a4 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_a5 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_a6 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_y1 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_y2 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_y3 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_y4 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_y5 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussl_y6 = list(
      J = na_see_jqmussln_no_answer
    ),
    qmussln = list(
      J = c(`-2` = "na, see JQMUSSL")
    )
  ),

  value_labels_harmonized = list(
    qmus1 = no_yes_3,
    qmus2 = no_answer,
    qmus3 = no_yes_3,
    qmus4 = not_available_routing_no_answer,
    qmus5 = not_available_routing_no_answer,
    qmusat = c(
      `-2` = "not available, routing",
      `-1` = "no answer",
      `1` = "always alone",
      `2` = "mostly alone",
      `3` = "changes, as often alone as together",
      `4` = "mostly together with others",
      `5` = "always together with others"
    ),
    qmusl = no_yes_244,
    qmuslc = not_available_routing_no_answer,
    qmuslm = not_available_routing_no_answer,
    qmuslnt = not_available_routing_no_answer,
    qmussl = no_yes_3,
    qmussl_a1 = not_available_routing_no_answer,
    qmussl_a2 = not_available_routing_no_answer,
    qmussl_a3 = not_available_routing_no_answer,
    qmussl_a4 = not_available_routing_no_answer,
    qmussl_a5 = not_available_routing_no_answer,
    qmussl_a6 = not_available_routing_no_answer,
    qmussl_y1 = not_available_routing_no_answer,
    qmussl_y2 = not_available_routing_no_answer,
    qmussl_y3 = not_available_routing_no_answer,
    qmussl_y4 = not_available_routing_no_answer,
    qmussl_y5 = not_available_routing_no_answer,
    qmussl_y6 = not_available_routing_no_answer,
    qmussln = not_available_routing,
    qsmus1 = not_mentioned_mentioned_6,
    qsmus2 = not_mentioned_mentioned_6,
    qsmus3 = not_mentioned_mentioned_6,
    qsmus4 = not_mentioned_mentioned_6,
    qsmus5 = not_mentioned_mentioned_6,
    qsmus6 = not_mentioned_mentioned_6
  )
)
