## LASA filecode 030 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_030 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "badl1a",
      "badl1b",
      "badl1c",
      "badl1d",
      "badl1e",
      "badl2a",
      "badl2b",
      "badl2c",
      "badl2d",
      "badl2e",
      "badl3a",
      "badl3b",
      "badl3c",
      "badl3d",
      "badl3e",
      "badl4a",
      "badl4b",
      "badl4c",
      "badl4d",
      "badl4e",
      "badl5a",
      "badl5b",
      "badl5c",
      "badl5d",
      "badl5e",
      "badl6a",
      "badl6b",
      "badl6c",
      "badl6d",
      "badl6e",
      "badl7a",
      "badl7b",
      "badl7c",
      "badl7d",
      "badl7e",
      "badl1a",
      "badl1b",
      "badl1c",
      "badl1d",
      "badl2a",
      "badl2b",
      "badl2c",
      "badl2d",
      "badl3a",
      "badl3b",
      "badl3c",
      "badl3d",
      "badl4a",
      "badl4b",
      "badl4c",
      "badl4d",
      "badl5a",
      "badl5b",
      "badl5c",
      "badl5d",
      "badl6a",
      "badl6b",
      "badl6c",
      "badl6d",
      "badl7a",
      "badl7b",
      "badl7c",
      "badl7d",
      "badl1a",
      "badl1b",
      "badl1c",
      "badl1d",
      "badl4a",
      "badl4b",
      "badl4c",
      "badl4d",
      "badl6a",
      "badl6b",
      "badl6c",
      "badl6d",
      "cadl1a",
      "cadl1b",
      "cadl1c",
      "cadl1d",
      "cadl1e",
      "cadl2a",
      "cadl2b",
      "cadl2c",
      "cadl2d",
      "cadl2e",
      "cadl3a",
      "cadl3b",
      "cadl3c",
      "cadl3d",
      "cadl3e",
      "cadl4a",
      "cadl4b",
      "cadl4c",
      "cadl4d",
      "cadl4e",
      "cadl5a",
      "cadl5b",
      "cadl5c",
      "cadl5d",
      "cadl5e",
      "cadl6a",
      "cadl6b",
      "cadl6c",
      "cadl6d",
      "cadl6e",
      "dadl1a",
      "dadl1b",
      "dadl1c",
      "dadl1d",
      "dadl1e",
      "dadl2a",
      "dadl2b",
      "dadl2c",
      "dadl2d",
      "dadl2e",
      "dadl3a",
      "dadl3b",
      "dadl3c",
      "dadl3d",
      "dadl3e",
      "dadl4a",
      "dadl4b",
      "dadl4c",
      "dadl4d",
      "dadl4e",
      "dadl5a",
      "dadl5b",
      "dadl5c",
      "dadl5d",
      "dadl5e",
      "dadl6a",
      "dadl6b",
      "dadl6c",
      "dadl6d",
      "dadl6e",
      "eadl1a",
      "eadl1b",
      "eadl1c",
      "eadl1d",
      "eadl1e",
      "eadl2a",
      "eadl2b",
      "eadl2c",
      "eadl2d",
      "eadl2e",
      "eadl3a",
      "eadl3b",
      "eadl3c",
      "eadl3d",
      "eadl3e",
      "eadl4a",
      "eadl4b",
      "eadl4c",
      "eadl4d",
      "eadl4e",
      "eadl5a",
      "eadl5b",
      "eadl5c",
      "eadl5d",
      "eadl5e",
      "eadl6a",
      "eadl6b",
      "eadl6c",
      "eadl6d",
      "eadl6e",
      "fadl1a",
      "fadl1b",
      "fadl1c",
      "fadl1d",
      "fadl1e",
      "fadl2a",
      "fadl2b",
      "fadl2c",
      "fadl2d",
      "fadl2e",
      "fadl3a",
      "fadl3b",
      "fadl3c",
      "fadl3d",
      "fadl3e",
      "fadl4a",
      "fadl4b",
      "fadl4c",
      "fadl4d",
      "fadl4e",
      "fadl5a",
      "fadl5b",
      "fadl5c",
      "fadl5d",
      "fadl5e",
      "fadl6a",
      "fadl6b",
      "fadl6c",
      "fadl6d",
      "fadl6e",
      "fadl7a",
      "fadl7b",
      "fadl7c",
      "fadl7d",
      "fadl7e",
      "gadl1a",
      "gadl1b",
      "gadl1c",
      "gadl1d",
      "gadl1e",
      "gadl2a",
      "gadl2b",
      "gadl2c",
      "gadl2d",
      "gadl2e",
      "gadl3a",
      "gadl3b",
      "gadl3c",
      "gadl3d",
      "gadl3e",
      "gadl4a",
      "gadl4b",
      "gadl4c",
      "gadl4d",
      "gadl4e",
      "gadl5a",
      "gadl5b",
      "gadl5c",
      "gadl5d",
      "gadl5e",
      "gadl6a",
      "gadl6b",
      "gadl6c",
      "gadl6d",
      "gadl6e",
      "gadl7a",
      "gadl7b",
      "gadl7c",
      "gadl7d",
      "gadl7e",
      "hadl1a",
      "hadl1b",
      "hadl1c",
      "hadl1d",
      "hadl2a",
      "hadl2b",
      "hadl2c",
      "hadl2d",
      "hadl3a",
      "hadl3b",
      "hadl3c",
      "hadl3d",
      "hadl4a",
      "hadl4b",
      "hadl4c",
      "hadl4d",
      "hadl5a",
      "hadl5b",
      "hadl5c",
      "hadl5d",
      "hadl6a",
      "hadl6b",
      "hadl6c",
      "hadl6d",
      "hadl7a",
      "hadl7b",
      "hadl7c",
      "hadl7d",
      "iadl1a",
      "iadl1b",
      "iadl1c",
      "iadl1d",
      "iadl2a",
      "iadl2b",
      "iadl2c",
      "iadl2d",
      "iadl3a",
      "iadl3b",
      "iadl3c",
      "iadl3d",
      "iadl4a",
      "iadl4b",
      "iadl4c",
      "iadl4d",
      "iadl5a",
      "iadl5b",
      "iadl5c",
      "iadl5d",
      "iadl6a",
      "iadl6b",
      "iadl6c",
      "iadl6d",
      "iadl7a",
      "iadl7b",
      "iadl7c",
      "iadl7d",
      "jadl1a",
      "jadl1b",
      "jadl1c",
      "jadl1d",
      "jadl2a",
      "jadl2b",
      "jadl2c",
      "jadl2d",
      "jadl3a",
      "jadl3b",
      "jadl3c",
      "jadl3d",
      "jadl4a",
      "jadl4b",
      "jadl4c",
      "jadl4d",
      "jadl5a",
      "jadl5b",
      "jadl5c",
      "jadl5d",
      "jadl6a",
      "jadl6b",
      "jadl6c",
      "jadl6d",
      "jadl7a",
      "jadl7b",
      "jadl7c",
      "jadl7d",
      "kadl1a",
      "kadl1b",
      "kadl1c",
      "kadl1d",
      "kadl2a",
      "kadl2b",
      "kadl2c",
      "kadl2d",
      "kadl3a",
      "kadl3b",
      "kadl3c",
      "kadl3d",
      "kadl4a",
      "kadl4b",
      "kadl4c",
      "kadl4d",
      "kadl5a",
      "kadl5b",
      "kadl5c",
      "kadl5d",
      "kadl6a",
      "kadl6b",
      "kadl6c",
      "kadl6d",
      "kadl7a",
      "kadl7b",
      "kadl7c",
      "kadl7d",
      "badl1a",
      "badl1b",
      "badl2a",
      "badl2b",
      "badl3a",
      "badl3b",
      "badl4a",
      "badl4b",
      "badl5a",
      "badl5b",
      "badl6a",
      "badl6b",
      "badl7a",
      "badl7b"
    ),
    canonical_name = c(
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl1e",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl2e",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl3e",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl4e",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl5e",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl6e",
      "adl7a",
      "adl7b",
      "adl7c",
      "adl7d",
      "adl7e",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl7a",
      "adl7b",
      "adl7c",
      "adl7d",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl1e",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl2e",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl3e",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl4e",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl5e",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl6e",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl1e",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl2e",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl3e",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl4e",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl5e",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl6e",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl1e",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl2e",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl3e",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl4e",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl5e",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl6e",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl1e",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl2e",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl3e",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl4e",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl5e",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl6e",
      "adl7a",
      "adl7b",
      "adl7c",
      "adl7d",
      "adl7e",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl1e",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl2e",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl3e",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl4e",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl5e",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl6e",
      "adl7a",
      "adl7b",
      "adl7c",
      "adl7d",
      "adl7e",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl7a",
      "adl7b",
      "adl7c",
      "adl7d",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl7a",
      "adl7b",
      "adl7c",
      "adl7d",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl7a",
      "adl7b",
      "adl7c",
      "adl7d",
      "adl1a",
      "adl1b",
      "adl1c",
      "adl1d",
      "adl2a",
      "adl2b",
      "adl2c",
      "adl2d",
      "adl3a",
      "adl3b",
      "adl3c",
      "adl3d",
      "adl4a",
      "adl4b",
      "adl4c",
      "adl4d",
      "adl5a",
      "adl5b",
      "adl5c",
      "adl5d",
      "adl6a",
      "adl6b",
      "adl6c",
      "adl6d",
      "adl7a",
      "adl7b",
      "adl7c",
      "adl7d",
      "adl1a",
      "adl1b",
      "adl2a",
      "adl2b",
      "adl3a",
      "adl3b",
      "adl4a",
      "adl4b",
      "adl5a",
      "adl5b",
      "adl6a",
      "adl6b",
      "adl7a",
      "adl7b"
    ),
    variable_label = c(
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (B/F/GADL1A > 1)",
      "Stairs: help from someone (B/F/GADL1A > 2)",
      "Stairs: R receive help (B/F/GADL1A = 2)",
      "Stairs: less than wanted (B/F/GADL1A > 1)",
      "(Un)dress: self",
      "(Un)dress: using aid (B/F/GADL2A > 1)",
      "(Un)dress: help from someone (B/F/GADL2A > 2)",
      "(Un)dress: R receive help (B/F/GADL2A = 2)",
      "(Un)dress: less than wanted (B/F/GADL2A > 1)",
      "Chair: sit and rise from",
      "Chair: using aid (B/F/GADL3A > 1)",
      "Chair: help from someone (B/F/GADL3A > 2)",
      "Chair: R receive help (B/F/GADL3A = 2)",
      "Chair: less than wanted (B/F/GADL3A > 1)",
      "Toenails: cutting own",
      "Toenails: using aid (C/DADL4A > 1)",
      "Toenails: help from someone (B/F/GADL4A > 2)",
      "Toenails: R receive help (B/F/GADL4A = 2)",
      "Toenails: less than wanted (B/F/GADL4A > 1)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (B/F/GADL5A > 1)",
      "Walking: help from someone (B/F/GADL5A > 2)",
      "Walking: R receive help (B/F/GADL5A = 2)",
      "Walking: less than wanted (B/F/GADL5A > 1)",
      "Transport: use of own or public",
      "Transport: using aid (B/F/GADL6A > 1)",
      "Transport: help from someone (B/F/GADL6A > 2)",
      "Transport: R receive help (B/F/GADL6A = 2)",
      "Transport: less than wanted (B/F/GADL6A > 1)",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid (B/F/GADL7A > 1)",
      "Take a bath/shower: help from someone (B/F/GADL7A > 2)",
      "Take a bath/shower: R receive help (B/F/GADL7A = 2)",
      "Take a bath/shower: less than wanted (B/F/GADL7A > 1)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (B/I/J/KADL1A > 1)",
      "Stairs: help from someone (B/I/J/KADL1A > 2)",
      "Stairs: R receive help (B/I/J/KADL1A = 2)",
      "(Un)dress: self",
      "(Un)dress: using aid (B/I/J/KADL2A > 1)",
      "(Un)dress: help from someone (B/I/J/KADL2A > 2)",
      "(Un)dress: R receive help (B/I/J/KADL2A = 2)",
      "Chair: sit and rise from",
      "Chair: using aid (B/I/J/KADL3A > 1)",
      "Chair: help from someone (B/I/J/KADL3A > 2)",
      "Chair: R receive help (B/I/J/KADL3A = 2)",
      "Toenails: cutting own",
      "Toenails: using aid (B/I/J/KADL4A > 1)",
      "Toenails: help from someone (B/I/J/KADL4A > 2)",
      "Toenails: R receive help (B/I/J/KADL4A = 2)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (B/I/J/KADL5A > 1)",
      "Walking: help from someone (B/I/J/KADL5A > 2)",
      "Walking: R receive help (B/I/J/KADL5A = 2)",
      "Transport: use of own or public",
      "Transport: using aid (B/I/J/KADL6A > 1)",
      "Transport: help from someone (B/I/J/KADL6A > 2)",
      "Transport: R receive help (B/I/J/KADL6A = 2)",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid (B/I/J/KADL7A > 1)",
      "Take a bath/shower: help from someone (B/I/J/KADL7A > 2)",
      "Take a bath/shower: R receive help (B/I/J/KADL7A = 2)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (BADL1A > 1)",
      "Stairs: help from someone (BADL1A = 3)",
      "Stairs: R receive help (BADL1A = 2)",
      "Toenails: cutting own",
      "Toenails: using aid (BADL4A > 1)",
      "Toenails: help from someone (BADL4A = 3)",
      "Toenails: R receive help (BADL4A = 2)",
      "Transport: use of own or public",
      "Transport: using aid (BADL6A > 1)",
      "Transport: help from someone (BADL6A = 3)",
      "Transport: R receive help (BADL6A = 2)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (C/D/EADL1A > 1)",
      "Stairs: help from someone (C/D/EADL1A > 2)",
      "Stairs: R receive help (C/D/EADL1A = 2)",
      "Stairs: less than wanted (C/D/EADL1A > 1)",
      "(Un)dress: self",
      "(Un)dress: using aid (C/D/EADL2A > 1)",
      "(Un)dress: help from someone (C/D/EADL2A > 2)",
      "(Un)dress: R receive help (C/D/EADL2A = 2)",
      "(Un)dress: less than wanted (C/D/EADL2A > 1)",
      "Chair: sit and rise from",
      "Chair: using aid (C/D/EADL3A > 1)",
      "Chair: help from someone (C/D/EADL3A > 2)",
      "Chair: R receive help (C/D/EADL3A = 2)",
      "Chair: less than wanted (C/D/EADL3A > 1)",
      "Toenails: cutting own",
      "Toenails: using aid (C/DADL4A > 1)",
      "Toenails: help from someone (C/D/EADL4A > 2)",
      "Toenails: R receive help (C/D/EADL4A = 2)",
      "Toenails: less than wanted (C/D/EADL4A > 1)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (C/D/EADL5A > 1)",
      "Walking: help from someone (C/D/EADL5A > 2)",
      "Walking: R receive help (C/D/EADL5A = 2)",
      "Walking: less than wanted (C/D/EADL5A > 1)",
      "Transport: use of own or public",
      "Transport: using aid (C/D/EADL6A > 1)",
      "Transport: help from someone (C/D/EADL6A > 2)",
      "Transport: R receive help (C/D/EADL6A = 2)",
      "Transport: less than wanted (C/D/EADL6A > 1)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (C/D/EADL1A > 1)",
      "Stairs: help from someone (C/D/EADL1A > 2)",
      "Stairs: R receive help (C/D/EADL1A = 2)",
      "Stairs: less than wanted (C/D/EADL1A > 1)",
      "(Un)dress: self",
      "(Un)dress: using aid (C/D/EADL2A > 1)",
      "(Un)dress: help from someone (C/D/EADL2A > 2)",
      "(Un)dress: R receive help (C/D/EADL2A = 2)",
      "(Un)dress: less than wanted (C/D/EADL2A > 1)",
      "Chair: sit and rise from",
      "Chair: using aid (C/D/EADL3A > 1)",
      "Chair: help from someone (C/D/EADL3A > 2)",
      "Chair: R receive help (C/D/EADL3A = 2)",
      "Chair: less than wanted (C/D/EADL3A > 1)",
      "Toenails: cutting own",
      "Toenails: using aid (C/DADL4A > 1)",
      "Toenails: help from someone (C/D/EADL4A > 2)",
      "Toenails: R receive help (C/D/EADL4A = 2)",
      "Toenails: less than wanted (C/D/EADL4A > 1)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (C/D/EADL5A > 1)",
      "Walking: help from someone (C/D/EADL5A > 2)",
      "Walking: R receive help (C/D/EADL5A = 2)",
      "Walking: less than wanted (C/D/EADL5A > 1)",
      "Transport: use of own or public",
      "Transport: using aid (C/D/EADL6A > 1)",
      "Transport: help from someone (C/D/EADL6A > 2)",
      "Transport: R receive help (C/D/EADL6A = 2)",
      "Transport: less than wanted (C/D/EADL6A > 1)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (C/D/EADL1A > 1)",
      "Stairs: help from someone (C/D/EADL1A > 2)",
      "Stairs: R receive help (C/D/EADL1A = 2)",
      "Stairs: less than wanted (C/D/EADL1A > 1)",
      "(Un)dress: self",
      "(Un)dress: using aid (C/D/EADL2A > 1)",
      "(Un)dress: help from someone (C/D/EADL2A > 2)",
      "(Un)dress: R receive help (C/D/EADL2A = 2)",
      "(Un)dress: less than wanted (C/D/EADL2A > 1)",
      "Chair: sit and rise from",
      "Chair: using aid (C/D/EADL3A > 1)",
      "Chair: help from someone (C/D/EADL3A > 2)",
      "Chair: R receive help (C/D/EADL3A = 2)",
      "Chair: less than wanted (C/D/EADL3A > 1)",
      "Toenails: cutting own",
      "Toenails: using aid (C/DADL4A > 1)",
      "Toenails: help from someone (C/D/EADL4A > 2)",
      "Toenails: R receive help (C/D/EADL4A = 2)",
      "Toenails: less than wanted (C/D/EADL4A > 1)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (C/D/EADL5A > 1)",
      "Walking: help from someone (C/D/EADL5A > 2)",
      "Walking: R receive help (C/D/EADL5A = 2)",
      "Walking: less than wanted (C/D/EADL5A > 1)",
      "Transport: use of own or public",
      "Transport: using aid (C/D/EADL6A > 1)",
      "Transport: help from someone (C/D/EADL6A > 2)",
      "Transport: R receive help (C/D/EADL6A = 2)",
      "Transport: less than wanted (C/D/EADL6A > 1)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (B/F/GADL1A > 1)",
      "Stairs: help from someone (B/F/GADL1A > 2)",
      "Stairs: R receive help (B/F/GADL1A = 2)",
      "Stairs: less than wanted (B/F/GADL1A > 1)",
      "(Un)dress: self",
      "(Un)dress: using aid (B/F/GADL2A > 1)",
      "(Un)dress: help from someone (B/F/GADL2A > 2)",
      "(Un)dress: R receive help (B/F/GADL2A = 2)",
      "(Un)dress: less than wanted (B/F/GADL2A > 1)",
      "Chair: sit and rise from",
      "Chair: using aid (B/F/GADL3A > 1)",
      "Chair: help from someone (B/F/GADL3A > 2)",
      "Chair: R receive help (B/F/GADL3A = 2)",
      "Chair: less than wanted (B/F/GADL3A > 1)",
      "Toenails: cutting own",
      "Toenails: using aid (C/DADL4A > 1)",
      "Toenails: help from someone (B/F/GADL4A > 2)",
      "Toenails: R receive help (B/F/GADL4A = 2)",
      "Toenails: less than wanted (B/F/GADL4A > 1)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (B/F/GADL5A > 1)",
      "Walking: help from someone (B/F/GADL5A > 2)",
      "Walking: R receive help (B/F/GADL5A = 2)",
      "Walking: less than wanted (B/F/GADL5A > 1)",
      "Transport: use of own or public",
      "Transport: using aid (B/F/GADL6A > 1)",
      "Transport: help from someone (B/F/GADL6A > 2)",
      "Transport: R receive help (B/F/GADL6A = 2)",
      "Transport: less than wanted (B/F/GADL6A > 1)",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid (B/F/GADL7A > 1)",
      "Take a bath/shower: help from someone (B/F/GADL7A > 2)",
      "Take a bath/shower: R receive help (B/F/GADL7A = 2)",
      "Take a bath/shower: less than wanted (B/F/GADL7A > 1)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (B/F/GADL1A > 1)",
      "Stairs: help from someone (B/F/GADL1A > 2)",
      "Stairs: R receive help (B/F/GADL1A = 2)",
      "Stairs: less than wanted (B/F/GADL1A > 1)",
      "(Un)dress: self",
      "(Un)dress: using aid (B/F/GADL2A > 1)",
      "(Un)dress: help from someone (B/F/GADL2A > 2)",
      "(Un)dress: R receive help (B/F/GADL2A = 2)",
      "(Un)dress: less than wanted (B/F/GADL2A > 1)",
      "Chair: sit and rise from",
      "Chair: using aid (B/F/GADL3A > 1)",
      "Chair: help from someone (B/F/GADL3A > 2)",
      "Chair: R receive help (B/F/GADL3A = 2)",
      "Chair: less than wanted (B/F/GADL3A > 1)",
      "Toenails: cutting own",
      "Toenails: using aid (C/DADL4A > 1)",
      "Toenails: help from someone (B/F/GADL4A > 2)",
      "Toenails: R receive help (B/F/GADL4A = 2)",
      "Toenails: less than wanted (B/F/GADL4A > 1)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (B/F/GADL5A > 1)",
      "Walking: help from someone (B/F/GADL5A > 2)",
      "Walking: R receive help (B/F/GADL5A = 2)",
      "Walking: less than wanted (B/F/GADL5A > 1)",
      "Transport: use of own or public",
      "Transport: using aid (B/F/GADL6A > 1)",
      "Transport: help from someone (B/F/GADL6A > 2)",
      "Transport: R receive help (B/F/GADL6A = 2)",
      "Transport: less than wanted (B/F/GADL6A > 1)",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid (B/F/GADL7A > 1)",
      "Take a bath/shower: help from someone (B/F/GADL7A > 2)",
      "Take a bath/shower: R receive help (B/F/GADL7A = 2)",
      "Take a bath/shower: less than wanted (B/F/GADL7A > 1)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (HADL1A > 1)",
      "Stairs: help from someone (HADL1A > 2)",
      "Stairs: R receive help (HADL1A = 2)",
      "(Un)dress: self",
      "(Un)dress: using aid (HADL2A > 1)",
      "(Un)dress: help from someone (HADL2A > 2)",
      "(Un)dress: R receive help (HADL2A = 2)",
      "Chair: sit and rise from",
      "Chair: using aid (HADL3A > 1)",
      "Chair: help from someone (HADL3A > 2)",
      "Chair: R receive help (HADL3A = 2)",
      "Toenails: cutting own",
      "Toenails: using aid (C/DADL4A > 1)",
      "Toenails: help from someone (HADL4A > 2)",
      "Toenails: R receive help (HADL4A = 2)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (HADL5A > 1)",
      "Walking: help from someone (HADL5A > 2)",
      "Walking: R receive help (HADL5A = 2)",
      "Transport: use of own or public",
      "Transport: using aid (HADL6A > 1)",
      "Transport: help from someone (HADL6A > 2)",
      "Transport: R receive help (HADL6A = 2)",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid (HADL7A > 1)",
      "Take a bath/shower: help from someone (HADL7A > 2)",
      "Take a bath/shower: R receive help (HADL7A = 2)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (B/I/J/KADL1A > 1)",
      "Stairs: help from someone (B/I/J/KADL1A > 2)",
      "Stairs: R receive help (B/I/J/KADL1A = 2)",
      "(Un)dress: self",
      "(Un)dress: using aid (B/I/J/KADL2A > 1)",
      "(Un)dress: help from someone (B/I/J/KADL2A > 2)",
      "(Un)dress: R receive help (B/I/J/KADL2A = 2)",
      "Chair: sit and rise from",
      "Chair: using aid (B/I/J/KADL3A > 1)",
      "Chair: help from someone (B/I/J/KADL3A > 2)",
      "Chair: R receive help (B/I/J/KADL3A = 2)",
      "Toenails: cutting own",
      "Toenails: using aid (B/I/J/KADL4A > 1)",
      "Toenails: help from someone (B/I/J/KADL4A > 2)",
      "Toenails: R receive help (B/I/J/KADL4A = 2)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (B/I/J/KADL5A > 1)",
      "Walking: help from someone (B/I/J/KADL5A > 2)",
      "Walking: R receive help (B/I/J/KADL5A = 2)",
      "Transport: use of own or public",
      "Transport: using aid (B/I/J/KADL6A > 1)",
      "Transport: help from someone (B/I/J/KADL6A > 2)",
      "Transport: R receive help (B/I/J/KADL6A = 2)",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid (B/I/J/KADL7A > 1)",
      "Take a bath/shower: help from someone (B/I/J/KADL7A > 2)",
      "Take a bath/shower: R receive help (B/I/J/KADL7A = 2)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (B/I/J/KADL1A > 1)",
      "Stairs: help from someone (B/I/J/KADL1A > 2)",
      "Stairs: R receive help (B/I/J/KADL1A = 2)",
      "(Un)dress: self",
      "(Un)dress: using aid (B/I/J/KADL2A > 1)",
      "(Un)dress: help from someone (B/I/J/KADL2A > 2)",
      "(Un)dress: R receive help (B/I/J/KADL2A = 2)",
      "Chair: sit and rise from",
      "Chair: using aid (B/I/J/KADL3A > 1)",
      "Chair: help from someone (B/I/J/KADL3A > 2)",
      "Chair: R receive help (B/I/J/KADL3A = 2)",
      "Toenails: cutting own",
      "Toenails: using aid (B/I/J/KADL4A > 1)",
      "Toenails: help from someone (B/I/J/KADL4A > 2)",
      "Toenails: R receive help (B/I/J/KADL4A = 2)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (B/I/J/KADL5A > 1)",
      "Walking: help from someone (B/I/J/KADL5A > 2)",
      "Walking: R receive help (B/I/J/KADL5A = 2)",
      "Transport: use of own or public",
      "Transport: using aid (B/I/J/KADL6A > 1)",
      "Transport: help from someone (B/I/J/KADL6A > 2)",
      "Transport: R receive help (B/I/J/KADL6A = 2)",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid (B/I/J/KADL7A > 1)",
      "Take a bath/shower: help from someone (B/I/J/KADL7A > 2)",
      "Take a bath/shower: R receive help (B/I/J/KADL7A = 2)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (B/I/J/KADL1A > 1)",
      "Stairs: help from someone (B/I/J/KADL1A > 2)",
      "Stairs: R receive help (B/I/J/KADL1A = 2)",
      "(Un)dress: self",
      "(Un)dress: using aid (B/I/J/KADL2A > 1)",
      "(Un)dress: help from someone (B/I/J/KADL2A > 2)",
      "(Un)dress: R receive help (B/I/J/KADL2A = 2)",
      "Chair: sit and rise from",
      "Chair: using aid (B/I/J/KADL3A > 1)",
      "Chair: help from someone (B/I/J/KADL3A > 2)",
      "Chair: R receive help (B/I/J/KADL3A = 2)",
      "Toenails: cutting own",
      "Toenails: using aid (B/I/J/KADL4A > 1)",
      "Toenails: help from someone (B/I/J/KADL4A > 2)",
      "Toenails: R receive help (B/I/J/KADL4A = 2)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (B/I/J/KADL5A > 1)",
      "Walking: help from someone (B/I/J/KADL5A > 2)",
      "Walking: R receive help (B/I/J/KADL5A = 2)",
      "Transport: use of own or public",
      "Transport: using aid (B/I/J/KADL6A > 1)",
      "Transport: help from someone (B/I/J/KADL6A > 2)",
      "Transport: R receive help (B/I/J/KADL6A = 2)",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid (B/I/J/KADL7A > 1)",
      "Take a bath/shower: help from someone (B/I/J/KADL7A > 2)",
      "Take a bath/shower: R receive help (B/I/J/KADL7A = 2)",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid (BADL1A > 1)",
      "(Un)dress: self",
      "(Un)dress: using aid (BADL2A > 1)",
      "Chair: sit and rise from",
      "Chair: using aid (BADL3A > 1)",
      "Toenails: cutting own",
      "Toenails: using aid (BADL4A > 1)",
      "Walking: 5 min. outside the house",
      "Walking: using aid (BADL5A > 1)",
      "Transport: use of own or public",
      "Transport: using aid (BADL6A > 1)",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid (BADL7A > 1)"
    ),
    harmonized_var_label = c(
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "Stairs: less than wanted",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "(Un)dress: less than wanted",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Chair: less than wanted",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Toenails: less than wanted",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Walking: less than wanted",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Transport: less than wanted",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid",
      "Take a bath/shower: help from someone",
      "Take a bath/shower: R receive help",
      "Take a bath/shower: less than wanted",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid",
      "Take a bath/shower: help from someone",
      "Take a bath/shower: R receive help",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "Stairs: less than wanted",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "(Un)dress: less than wanted",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Chair: less than wanted",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Toenails: less than wanted",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Walking: less than wanted",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Transport: less than wanted",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "Stairs: less than wanted",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "(Un)dress: less than wanted",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Chair: less than wanted",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Toenails: less than wanted",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Walking: less than wanted",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Transport: less than wanted",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "Stairs: less than wanted",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "(Un)dress: less than wanted",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Chair: less than wanted",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Toenails: less than wanted",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Walking: less than wanted",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Transport: less than wanted",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "Stairs: less than wanted",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "(Un)dress: less than wanted",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Chair: less than wanted",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Toenails: less than wanted",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Walking: less than wanted",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Transport: less than wanted",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid",
      "Take a bath/shower: help from someone",
      "Take a bath/shower: R receive help",
      "Take a bath/shower: less than wanted",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "Stairs: less than wanted",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "(Un)dress: less than wanted",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Chair: less than wanted",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Toenails: less than wanted",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Walking: less than wanted",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Transport: less than wanted",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid",
      "Take a bath/shower: help from someone",
      "Take a bath/shower: R receive help",
      "Take a bath/shower: less than wanted",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid",
      "Take a bath/shower: help from someone",
      "Take a bath/shower: R receive help",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid",
      "Take a bath/shower: help from someone",
      "Take a bath/shower: R receive help",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid",
      "Take a bath/shower: help from someone",
      "Take a bath/shower: R receive help",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "Stairs: help from someone",
      "Stairs: R receive help",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "(Un)dress: help from someone",
      "(Un)dress: R receive help",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Chair: help from someone",
      "Chair: R receive help",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Toenails: help from someone",
      "Toenails: R receive help",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Walking: help from someone",
      "Walking: R receive help",
      "Transport: use of own or public",
      "Transport: using aid",
      "Transport: help from someone",
      "Transport: R receive help",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid",
      "Take a bath/shower: help from someone",
      "Take a bath/shower: R receive help",
      "Stairs: 15 steps without stopping",
      "Stairs: using aid",
      "(Un)dress: self",
      "(Un)dress: using aid",
      "Chair: sit and rise from",
      "Chair: using aid",
      "Toenails: cutting own",
      "Toenails: using aid",
      "Walking: 5 min. outside the house",
      "Walking: using aid",
      "Transport: use of own or public",
      "Transport: using aid",
      "Take a bath/shower: self",
      "Take a bath/shower: using aid"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    adl1a = list(
      `2B` = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      `3B` = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      B = c(
        `-5` = "na, interview terminated",
        `-1` = "na, asked",
        `1` = "no, I cannot",
        `2` = "only with help",
        `3` = "yes, with difficulty",
        `4` = "yes, without help"
      ),
      C = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      D = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      E = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      F = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      G = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      H = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      I = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      J = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      K = no_i_cannot_only_with_help_yes_with_much_difficulty_4,
      MB = no_i_cannot_only_with_help_yes_with_much_difficulty_4
    ),
    adl1b = list(
      `2B` = no_yes_86,
      `3B` = no_yes_153,
      B = no_yes_265,
      C = no_yes_87,
      D = no_yes_87,
      E = no_yes_87,
      F = no_yes_86,
      G = no_yes_86,
      H = c(`-3` = "na, wrong skip", `-2` = "na, see HADL1A", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      I = no_yes_153,
      J = no_yes_153,
      K = no_yes_153,
      MB = no_yes_265
    ),
    adl1c = list(
      `2B` = never_seldom_occasionally_often_or_always_9,
      `3B` = never_seldom_occasionally_often_or_always_2,
      B = never_seldom_occasionally_often_or_always_22,
      C = never_seldom_occasionally_often_or_always_10,
      D = never_seldom_occasionally_often_or_always_10,
      E = never_seldom_occasionally_often_or_always_10,
      F = never_seldom_occasionally_often_or_always_9,
      G = never_seldom_occasionally_often_or_always_9,
      H = never_seldom_occasionally_often_or_always_23,
      I = never_seldom_occasionally_often_or_always_2,
      J = never_seldom_occasionally_often_or_always_2,
      K = never_seldom_occasionally_often_or_always_2
    ),
    adl1d = list(
      `2B` = never_seldom_occasionally_often_or_always_9,
      `3B` = never_seldom_occasionally_often_or_always_2,
      B = never_seldom_occasionally_often_or_always_22,
      C = never_seldom_occasionally_often_or_always_10,
      D = never_seldom_occasionally_often_or_always_10,
      E = never_seldom_occasionally_often_or_always_10,
      F = never_seldom_occasionally_often_or_always_9,
      G = never_seldom_occasionally_often_or_always_9,
      H = never_seldom_occasionally_often_or_always_23,
      I = never_seldom_occasionally_often_or_always_2,
      J = never_seldom_occasionally_often_or_always_2,
      K = never_seldom_occasionally_often_or_always_2
    ),
    adl1e = list(
      `2B` = no_yes_86,
      C = no_yes_87,
      D = no_yes_87,
      E = no_yes_87,
      F = no_yes_86,
      G = no_yes_86
    ),
    adl2a = list(
      `2B` = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      `3B` = no_i_cannot_only_with_help_yes_with_much_difficulty,
      C = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      D = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      E = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      F = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      G = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      H = no_i_cannot_only_with_help_yes_with_much_difficulty_5,
      I = no_i_cannot_only_with_help_yes_with_much_difficulty,
      J = no_i_cannot_only_with_help_yes_with_much_difficulty,
      K = no_i_cannot_only_with_help_yes_with_much_difficulty,
      MB = no_i_cannot_only_with_help_yes_with_much_difficulty_6
    ),
    adl2b = list(
      `2B` = no_yes_88,
      `3B` = no_yes_154,
      C = no_yes_89,
      D = no_yes_89,
      E = no_yes_89,
      F = no_yes_88,
      G = no_yes_88,
      H = c(`-3` = "na, wrong skip", `-2` = "na, see HADL2A", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      I = no_yes_154,
      J = no_yes_154,
      K = no_yes_154,
      MB = c(`-3` = "na, wrong skip", `-2` = "na, see BADL2A", `-1` = "na, asked", `1` = "no", `2` = "yes")
    ),
    adl2c = list(
      `2B` = never_seldom_occasionally_often_or_always_11,
      `3B` = never_seldom_occasionally_often_or_always_3,
      C = never_seldom_occasionally_often_or_always_12,
      D = never_seldom_occasionally_often_or_always_12,
      E = never_seldom_occasionally_often_or_always_12,
      F = never_seldom_occasionally_often_or_always_11,
      G = never_seldom_occasionally_often_or_always_11,
      H = never_seldom_occasionally_often_or_always_24,
      I = never_seldom_occasionally_often_or_always_3,
      J = never_seldom_occasionally_often_or_always_3,
      K = never_seldom_occasionally_often_or_always_3
    ),
    adl2d = list(
      `2B` = never_seldom_occasionally_often_or_always_11,
      `3B` = never_seldom_occasionally_often_or_always_3,
      C = never_seldom_occasionally_often_or_always_12,
      D = never_seldom_occasionally_often_or_always_12,
      E = never_seldom_occasionally_often_or_always_12,
      F = never_seldom_occasionally_often_or_always_11,
      G = never_seldom_occasionally_often_or_always_11,
      H = never_seldom_occasionally_often_or_always_24,
      I = never_seldom_occasionally_often_or_always_3,
      J = never_seldom_occasionally_often_or_always_3,
      K = never_seldom_occasionally_often_or_always_3
    ),
    adl2e = list(
      `2B` = no_yes_88,
      C = no_yes_89,
      D = no_yes_89,
      E = no_yes_89,
      F = no_yes_88,
      G = no_yes_88
    ),
    adl3a = list(
      `2B` = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      `3B` = no_i_cannot_only_with_help_yes_with_much_difficulty,
      C = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      D = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      E = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      F = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      G = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      H = no_i_cannot_only_with_help_yes_with_much_difficulty_5,
      I = no_i_cannot_only_with_help_yes_with_much_difficulty,
      J = no_i_cannot_only_with_help_yes_with_much_difficulty,
      K = no_i_cannot_only_with_help_yes_with_much_difficulty,
      MB = no_i_cannot_only_with_help_yes_with_much_difficulty_6
    ),
    adl3b = list(
      `2B` = no_yes_90,
      `3B` = no_yes_155,
      C = no_yes_91,
      D = no_yes_91,
      E = no_yes_91,
      F = no_yes_90,
      G = no_yes_90,
      H = c(`-3` = "na, wrong skip", `-2` = "na, see HADL3A", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      I = no_yes_155,
      J = no_yes_155,
      K = no_yes_155,
      MB = c(`-3` = "na, wrong skip", `-2` = "na, see BADL3A", `-1` = "na, asked", `1` = "no", `2` = "yes")
    ),
    adl3c = list(
      `2B` = never_seldom_occasionally_often_or_always_13,
      `3B` = never_seldom_occasionally_often_or_always_4,
      C = never_seldom_occasionally_often_or_always_14,
      D = never_seldom_occasionally_often_or_always_14,
      E = never_seldom_occasionally_often_or_always_14,
      F = never_seldom_occasionally_often_or_always_13,
      G = never_seldom_occasionally_often_or_always_13,
      H = never_seldom_occasionally_often_or_always_25,
      I = never_seldom_occasionally_often_or_always_4,
      J = never_seldom_occasionally_often_or_always_4,
      K = never_seldom_occasionally_often_or_always_4
    ),
    adl3d = list(
      `2B` = never_seldom_occasionally_often_or_always_13,
      `3B` = never_seldom_occasionally_often_or_always_4,
      C = never_seldom_occasionally_often_or_always_14,
      D = never_seldom_occasionally_often_or_always_14,
      E = never_seldom_occasionally_often_or_always_14,
      F = never_seldom_occasionally_often_or_always_13,
      G = never_seldom_occasionally_often_or_always_13,
      H = never_seldom_occasionally_often_or_always_25,
      I = never_seldom_occasionally_often_or_always_4,
      J = never_seldom_occasionally_often_or_always_4,
      K = never_seldom_occasionally_often_or_always_4
    ),
    adl3e = list(
      `2B` = no_yes_90,
      C = no_yes_91,
      D = no_yes_91,
      E = no_yes_91,
      F = no_yes_90,
      G = no_yes_90
    ),
    adl4a = list(
      `2B` = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      `3B` = no_i_cannot_only_with_help_yes_with_much_difficulty,
      B = no_i_cannot_only_with_help_yes_with_difficulty,
      C = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      D = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      E = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      F = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      G = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      H = no_i_cannot_only_with_help_yes_with_much_difficulty_5,
      I = no_i_cannot_only_with_help_yes_with_much_difficulty,
      J = no_i_cannot_only_with_help_yes_with_much_difficulty,
      K = no_i_cannot_only_with_help_yes_with_much_difficulty,
      MB = no_i_cannot_only_with_help_yes_with_much_difficulty_6
    ),
    adl4b = list(
      `2B` = no_yes_92,
      `3B` = no_yes_156,
      B = no_yes_266,
      C = no_yes_93,
      D = no_yes_93,
      E = no_yes_93,
      F = no_yes_92,
      G = no_yes_92,
      H = c(`-3` = "na, wrong skip", `-2` = "na, see HADL4A", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      I = no_yes_156,
      J = no_yes_156,
      K = no_yes_156,
      MB = no_yes_266
    ),
    adl4c = list(
      `2B` = never_seldom_occasionally_often_or_always_15,
      `3B` = never_seldom_occasionally_often_or_always_5,
      B = never_seldom_occasionally_often_or_always_26,
      C = never_seldom_occasionally_often_or_always_16,
      D = never_seldom_occasionally_often_or_always_16,
      E = never_seldom_occasionally_often_or_always_16,
      F = never_seldom_occasionally_often_or_always_15,
      G = never_seldom_occasionally_often_or_always_15,
      H = never_seldom_occasionally_often_or_always_27,
      I = never_seldom_occasionally_often_or_always_5,
      J = never_seldom_occasionally_often_or_always_5,
      K = never_seldom_occasionally_often_or_always_5
    ),
    adl4d = list(
      `2B` = never_seldom_occasionally_often_or_always_15,
      `3B` = never_seldom_occasionally_often_or_always_5,
      B = never_seldom_occasionally_often_or_always_26,
      C = never_seldom_occasionally_often_or_always_16,
      D = never_seldom_occasionally_often_or_always_16,
      E = never_seldom_occasionally_often_or_always_16,
      F = never_seldom_occasionally_often_or_always_15,
      G = never_seldom_occasionally_often_or_always_15,
      H = never_seldom_occasionally_often_or_always_27,
      I = never_seldom_occasionally_often_or_always_5,
      J = never_seldom_occasionally_often_or_always_5,
      K = never_seldom_occasionally_often_or_always_5
    ),
    adl4e = list(
      `2B` = no_yes_92,
      C = no_yes_93,
      D = no_yes_93,
      E = no_yes_93,
      F = no_yes_92,
      G = no_yes_92
    ),
    adl5a = list(
      `2B` = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      `3B` = no_i_cannot_only_with_help_yes_with_much_difficulty,
      C = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      D = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      E = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      F = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      G = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      H = no_i_cannot_only_with_help_yes_with_much_difficulty_5,
      I = no_i_cannot_only_with_help_yes_with_much_difficulty,
      J = no_i_cannot_only_with_help_yes_with_much_difficulty,
      K = no_i_cannot_only_with_help_yes_with_much_difficulty,
      MB = no_i_cannot_only_with_help_yes_with_much_difficulty_6
    ),
    adl5b = list(
      `2B` = no_yes_94,
      `3B` = no_yes_157,
      C = no_yes_95,
      D = no_yes_95,
      E = no_yes_95,
      F = no_yes_94,
      G = no_yes_94,
      H = c(`-3` = "na, wrong skip", `-2` = "na, see HADL5A", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      I = no_yes_157,
      J = no_yes_157,
      K = no_yes_157,
      MB = c(`-3` = "na, wrong skip", `-2` = "na, see BADL5A", `-1` = "na, asked", `1` = "no", `2` = "yes")
    ),
    adl5c = list(
      `2B` = never_seldom_occasionally_often_or_always_17,
      `3B` = never_seldom_occasionally_often_or_always_6,
      C = never_seldom_occasionally_often_or_always_18,
      D = never_seldom_occasionally_often_or_always_18,
      E = never_seldom_occasionally_often_or_always_18,
      F = never_seldom_occasionally_often_or_always_17,
      G = never_seldom_occasionally_often_or_always_17,
      H = never_seldom_occasionally_often_or_always_28,
      I = never_seldom_occasionally_often_or_always_6,
      J = never_seldom_occasionally_often_or_always_6,
      K = never_seldom_occasionally_often_or_always_6
    ),
    adl5d = list(
      `2B` = never_seldom_occasionally_often_or_always_17,
      `3B` = never_seldom_occasionally_often_or_always_6,
      C = never_seldom_occasionally_often_or_always_18,
      D = never_seldom_occasionally_often_or_always_18,
      E = never_seldom_occasionally_often_or_always_18,
      F = never_seldom_occasionally_often_or_always_17,
      G = never_seldom_occasionally_often_or_always_17,
      H = never_seldom_occasionally_often_or_always_28,
      I = never_seldom_occasionally_often_or_always_6,
      J = never_seldom_occasionally_often_or_always_6,
      K = never_seldom_occasionally_often_or_always_6
    ),
    adl5e = list(
      `2B` = no_yes_94,
      C = no_yes_95,
      D = no_yes_95,
      E = no_yes_95,
      F = no_yes_94,
      G = no_yes_94
    ),
    adl6a = list(
      `2B` = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      `3B` = no_i_cannot_only_with_help_yes_with_much_difficulty,
      B = no_i_cannot_only_with_help_yes_with_difficulty,
      C = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      D = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      E = no_i_cannot_only_with_help_yes_with_much_difficulty_3,
      F = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      G = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      H = no_i_cannot_only_with_help_yes_with_much_difficulty_5,
      I = no_i_cannot_only_with_help_yes_with_much_difficulty,
      J = no_i_cannot_only_with_help_yes_with_much_difficulty,
      K = no_i_cannot_only_with_help_yes_with_much_difficulty,
      MB = no_i_cannot_only_with_help_yes_with_much_difficulty_6
    ),
    adl6b = list(
      `2B` = no_yes_96,
      `3B` = no_yes_158,
      B = no_yes_267,
      C = no_yes_97,
      D = no_yes_97,
      E = no_yes_97,
      F = no_yes_96,
      G = no_yes_96,
      H = c(`-3` = "na, wrong skip", `-2` = "na, see HADL6A", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      I = no_yes_158,
      J = no_yes_158,
      K = no_yes_158,
      MB = no_yes_267
    ),
    adl6c = list(
      `2B` = never_seldom_occasionally_often_or_always_19,
      `3B` = never_seldom_occasionally_often_or_always_7,
      B = never_seldom_occasionally_often_or_always_29,
      C = never_seldom_occasionally_often_or_always_20,
      D = never_seldom_occasionally_often_or_always_20,
      E = never_seldom_occasionally_often_or_always_20,
      F = never_seldom_occasionally_often_or_always_19,
      G = never_seldom_occasionally_often_or_always_19,
      H = never_seldom_occasionally_often_or_always_30,
      I = never_seldom_occasionally_often_or_always_7,
      J = never_seldom_occasionally_often_or_always_7,
      K = never_seldom_occasionally_often_or_always_7
    ),
    adl6d = list(
      `2B` = never_seldom_occasionally_often_or_always_19,
      `3B` = never_seldom_occasionally_often_or_always_7,
      B = never_seldom_occasionally_often_or_always_29,
      C = never_seldom_occasionally_often_or_always_20,
      D = never_seldom_occasionally_often_or_always_20,
      E = never_seldom_occasionally_often_or_always_20,
      F = never_seldom_occasionally_often_or_always_19,
      G = never_seldom_occasionally_often_or_always_19,
      H = never_seldom_occasionally_often_or_always_30,
      I = never_seldom_occasionally_often_or_always_7,
      J = never_seldom_occasionally_often_or_always_7,
      K = never_seldom_occasionally_often_or_always_7
    ),
    adl6e = list(
      `2B` = no_yes_96,
      C = no_yes_97,
      D = no_yes_97,
      E = no_yes_97,
      F = no_yes_96,
      G = no_yes_96
    ),
    adl7a = list(
      `2B` = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      `3B` = no_i_cannot_only_with_help_yes_with_much_difficulty,
      F = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      G = no_i_cannot_only_with_help_yes_with_much_difficulty_2,
      H = no_i_cannot_only_with_help_yes_with_much_difficulty_5,
      I = no_i_cannot_only_with_help_yes_with_much_difficulty,
      J = no_i_cannot_only_with_help_yes_with_much_difficulty,
      K = no_i_cannot_only_with_help_yes_with_much_difficulty,
      MB = no_i_cannot_only_with_help_yes_with_much_difficulty_6
    ),
    adl7b = list(
      `2B` = no_yes_98,
      `3B` = no_yes_159,
      F = no_yes_98,
      G = no_yes_98,
      H = c(`-3` = "na, wrong skip", `-2` = "na, see HADL7A", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      I = no_yes_159,
      J = no_yes_159,
      K = no_yes_159,
      MB = c(`-3` = "na, wrong skip", `-2` = "na, see BADL7A", `-1` = "na, asked", `1` = "no", `2` = "yes")
    ),
    adl7c = list(
      `2B` = never_seldom_occasionally_often_or_always_21,
      `3B` = never_seldom_occasionally_often_or_always_8,
      F = never_seldom_occasionally_often_or_always_21,
      G = never_seldom_occasionally_often_or_always_21,
      H = never_seldom_occasionally_often_or_always_31,
      I = never_seldom_occasionally_often_or_always_8,
      J = never_seldom_occasionally_often_or_always_8,
      K = never_seldom_occasionally_often_or_always_8
    ),
    adl7d = list(
      `2B` = never_seldom_occasionally_often_or_always_21,
      `3B` = never_seldom_occasionally_often_or_always_8,
      F = never_seldom_occasionally_often_or_always_21,
      G = never_seldom_occasionally_often_or_always_21,
      H = never_seldom_occasionally_often_or_always_31,
      I = never_seldom_occasionally_often_or_always_8,
      J = never_seldom_occasionally_often_or_always_8,
      K = never_seldom_occasionally_often_or_always_8
    ),
    adl7e = list(
      `2B` = no_yes_98,
      F = no_yes_98,
      G = no_yes_98
    )
  ),

  value_labels_harmonized = list(
    adl1a = c(
      `-5` = "not available, interview terminated",
      `-1` = "not available, asked",
      `1` = "no, I cannot",
      `2` = "only with help",
      `3` = "functional ability category 3",
      `4` = "functional ability category 4",
      `5` = "yes, without help"
    ),
    adl1b = no_yes_4,
    adl1c = never_seldom_occasionally_often_or_always,
    adl1d = never_seldom_occasionally_often_or_always,
    adl1e = no_yes_4,
    adl2a = no_i_cannot_only_with_help_yes_with_much_difficulty_7,
    adl2b = no_yes_4,
    adl2c = never_seldom_occasionally_often_or_always,
    adl2d = never_seldom_occasionally_often_or_always,
    adl2e = no_yes_4,
    adl3a = no_i_cannot_only_with_help_yes_with_much_difficulty_7,
    adl3b = no_yes_4,
    adl3c = never_seldom_occasionally_often_or_always,
    adl3d = never_seldom_occasionally_often_or_always,
    adl3e = no_yes_4,
    adl4a = no_i_cannot_only_with_help,
    adl4b = no_yes_4,
    adl4c = never_seldom_occasionally_often_or_always,
    adl4d = never_seldom_occasionally_often_or_always,
    adl4e = no_yes_4,
    adl5a = no_i_cannot_only_with_help_yes_with_much_difficulty_7,
    adl5b = no_yes_4,
    adl5c = never_seldom_occasionally_often_or_always,
    adl5d = never_seldom_occasionally_often_or_always,
    adl5e = no_yes_4,
    adl6a = no_i_cannot_only_with_help,
    adl6b = no_yes_4,
    adl6c = never_seldom_occasionally_often_or_always,
    adl6d = never_seldom_occasionally_often_or_always,
    adl6e = no_yes_4,
    adl7a = no_i_cannot_only_with_help_yes_with_much_difficulty_7,
    adl7b = no_yes_4,
    adl7c = never_seldom_occasionally_often_or_always,
    adl7d = never_seldom_occasionally_often_or_always,
    adl7e = no_yes_4
  )
)
