## LASA filecode 038 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_038 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bRMGL",
      "brelig01",
      "brelig08",
      "brelig09",
      "brelig10",
      "brelig11",
      "brelig12",
      "brelig13",
      "brelig14",
      "brelig15",
      "brelig16",
      "brelig17",
      "brelig18",
      "brelig19",
      "brelig1b",
      "brelig8a",
      "brelig08",
      "brelig8a",
      "crelig01",
      "crelig02",
      "crelig03",
      "crelig04",
      "crelig05",
      "crelig06",
      "crelig07",
      "crelig08",
      "crelig09",
      "crelig10",
      "crelig11",
      "crelig12",
      "crelig13",
      "crelig14",
      "crelig15",
      "crelig16",
      "crelig17",
      "crelig18",
      "crelig19",
      "crmgl",
      "dRMGL",
      "drelig01",
      "drelig08",
      "drelig09",
      "drelig10",
      "drelig11",
      "drelig12",
      "drelig13",
      "drelig14",
      "drelig15",
      "drelig16",
      "drelig17",
      "drelig18",
      "drelig19",
      "drelig1a",
      "drelig1b",
      "drelig8a",
      "eRMGL",
      "erelig01",
      "erelig08",
      "erelig09",
      "erelig10",
      "erelig11",
      "erelig12",
      "erelig13",
      "erelig14",
      "erelig15",
      "erelig16",
      "erelig17",
      "erelig18",
      "erelig19",
      "erelig1b",
      "erelig8a",
      "frelig08",
      "frelig14",
      "frelig15",
      "frelig16",
      "frelig17",
      "frelig18",
      "frelig19",
      "frelig1b",
      "frelig8a",
      "frmgl",
      "grelig08",
      "grelig1b",
      "grelig8a",
      "grmgl",
      "hrelig08",
      "hrelig1b",
      "hrelig8a",
      "hrmgl",
      "irelig08",
      "irelig1b",
      "irelig8a",
      "jrelig08",
      "jrelig1b",
      "jrelig8a",
      "krelig08",
      "krelig1b",
      "krelig8a",
      "brelig1a",
      "brelig1b"
    ),
    canonical_name = c(
      "rmgl",
      "relig01",
      "relig08",
      "relig09",
      "relig10",
      "relig11",
      "relig12",
      "relig13",
      "relig14",
      "relig15",
      "relig16",
      "relig17",
      "relig18",
      "relig19",
      "relig1b",
      "relig8a",
      "relig08",
      "relig8a",
      "relig01",
      "relig02",
      "relig03",
      "relig04",
      "relig05",
      "relig06",
      "relig07",
      "relig08",
      "relig09",
      "relig10",
      "relig11",
      "relig12",
      "relig13",
      "relig14",
      "relig15",
      "relig16",
      "relig17",
      "relig18",
      "relig19",
      "rmgl",
      "rmgl",
      "relig01",
      "relig08",
      "relig09",
      "relig10",
      "relig11",
      "relig12",
      "relig13",
      "relig14",
      "relig15",
      "relig16",
      "relig17",
      "relig18",
      "relig19",
      "relig1a",
      "relig1b",
      "relig8a",
      "rmgl",
      "relig01",
      "relig08",
      "relig09",
      "relig10",
      "relig11",
      "relig12",
      "relig13",
      "relig14",
      "relig15",
      "relig16",
      "relig17",
      "relig18",
      "relig19",
      "relig1b",
      "relig8a",
      "relig08",
      "relig14",
      "relig15",
      "relig16",
      "relig17",
      "relig18",
      "relig19",
      "relig1b",
      "relig8a",
      "rmgl",
      "relig08",
      "relig1b",
      "relig8a",
      "rmgl",
      "relig08",
      "relig1b",
      "relig8a",
      "rmgl",
      "relig08",
      "relig1b",
      "relig8a",
      "relig08",
      "relig1b",
      "relig8a",
      "relig08",
      "relig1b",
      "relig8a",
      "relig1a",
      "relig1b"
    ),
    variable_label = c(
      "Reason missing",
      "Member of a church or a particular ideological group?",
      "Praying: meaningful",
      "Influences my daily life",
      "Role in important decisions",
      "Influences my political opinion",
      "Life would look different without",
      "Faith: very interesting",
      "Border life/death less striking",
      "Unimportance individual life",
      "Mutual connection universe",
      "Close presence persons",
      "Distance past/present disappears",
      "Belonging with earlier/coming generation",
      "Church attendance frequency",
      "Praying: frequency",
      "Praying:",
      "Praying:",
      "Member of a church or a particular ideological group?",
      "Life after death",
      "Heaven",
      "Hell",
      "Devil",
      "Adam and Eve",
      "Bible as God",
      "Praying: meaningful",
      "Influences my daily life",
      "Role in important decisions",
      "Influences my political opinion",
      "Life would look different without",
      "Faith: very interesting",
      "Border life/death less striking",
      "Unimportance individual life",
      "Mutual connection universe",
      "Close presence persons",
      "Distance past/present disappears",
      "Belonging with earlier/coming generation",
      "Reason missing",
      "Reason missing",
      "Member of a church or a particular ideological group?",
      "Praying: meaningful",
      "Influences my daily life",
      "Role in important decisions",
      "Influences my political opinion",
      "Life would look different without",
      "Faith: very interesting",
      "Border life/death less striking",
      "Unimportance individual life",
      "Mutual connection universe",
      "Close presence persons",
      "Distance past/present disappears",
      "Belonging with earlier/coming generation",
      "Which church or particular ideological group?",
      "Church attendance frequency",
      "Praying: frequency",
      "Reason missing",
      "Member of a church or a particular ideological group?",
      "Praying: meaningful",
      "Influences my daily life",
      "Role in important decisions",
      "Influences my political opinion",
      "Life would look different without",
      "Faith: very interesting",
      "Border life/death less striking",
      "Unimportance individual life",
      "Mutual connection universe",
      "Close presence persons",
      "Distance past/present disappears",
      "Belonging with earlier/coming generation",
      "Church attendance frequency",
      "Praying: frequency",
      "Praying: meaningful",
      "Border life/death less striking",
      "Unimportance individual life",
      "Mutual connection universe",
      "Close presence persons",
      "Distance past/present disappears",
      "Belonging with earlier/coming generation",
      "Church attendance frequency",
      "Praying: frequency",
      "Reason missing",
      "Praying: meaningful",
      "Church attendance frequency",
      "Praying: frequency",
      "Reason missing",
      "Praying: meaningful",
      "Church attendance frequency",
      "Praying: frequency",
      "Reason missing",
      "Praying: meaningful",
      "Church attendance frequency",
      "Praying: frequency",
      "Praying: meaningful",
      "Church attendance frequency",
      "Praying: frequency",
      "Praying: meaningful",
      "Church attendance frequency",
      "Praying: frequency",
      "Member of a church or particular ideological group",
      "Church attendance frequency"
    ),
    harmonized_var_label = c(
      "Reason missing",
      "Member of a church or a particular ideological group?",
      "Praying: meaningful",
      "Influences my daily life",
      "Role in important decisions",
      "Influences my political opinion",
      "Life would look different without",
      "Faith: very interesting",
      "Border life/death less striking",
      "Unimportance individual life",
      "Mutual connection universe",
      "Close presence persons",
      "Distance past/present disappears",
      "Belonging with earlier/coming generation",
      "Church attendance frequency",
      "Praying: frequency",
      "Praying: meaningful",
      "Praying: frequency",
      "Member of a church or a particular ideological group?",
      "Life after death",
      "Heaven",
      "Hell",
      "Devil",
      "Adam and Eve",
      "Bible as God",
      "Praying: meaningful",
      "Influences my daily life",
      "Role in important decisions",
      "Influences my political opinion",
      "Life would look different without",
      "Faith: very interesting",
      "Border life/death less striking",
      "Unimportance individual life",
      "Mutual connection universe",
      "Close presence persons",
      "Distance past/present disappears",
      "Belonging with earlier/coming generation",
      "Reason missing",
      "Reason missing",
      "Member of a church or a particular ideological group?",
      "Praying: meaningful",
      "Influences my daily life",
      "Role in important decisions",
      "Influences my political opinion",
      "Life would look different without",
      "Faith: very interesting",
      "Border life/death less striking",
      "Unimportance individual life",
      "Mutual connection universe",
      "Close presence persons",
      "Distance past/present disappears",
      "Belonging with earlier/coming generation",
      "Which church or particular ideological group?",
      "Church attendance frequency",
      "Praying: frequency",
      "Reason missing",
      "Member of a church or a particular ideological group?",
      "Praying: meaningful",
      "Influences my daily life",
      "Role in important decisions",
      "Influences my political opinion",
      "Life would look different without",
      "Faith: very interesting",
      "Border life/death less striking",
      "Unimportance individual life",
      "Mutual connection universe",
      "Close presence persons",
      "Distance past/present disappears",
      "Belonging with earlier/coming generation",
      "Church attendance frequency",
      "Praying: frequency",
      "Praying: meaningful",
      "Border life/death less striking",
      "Unimportance individual life",
      "Mutual connection universe",
      "Close presence persons",
      "Distance past/present disappears",
      "Belonging with earlier/coming generation",
      "Church attendance frequency",
      "Praying: frequency",
      "Reason missing",
      "Praying: meaningful",
      "Church attendance frequency",
      "Praying: frequency",
      "Reason missing",
      "Praying: meaningful",
      "Church attendance frequency",
      "Praying: frequency",
      "Reason missing",
      "Praying: meaningful",
      "Church attendance frequency",
      "Praying: frequency",
      "Praying: meaningful",
      "Church attendance frequency",
      "Praying: frequency",
      "Praying: meaningful",
      "Church attendance frequency",
      "Praying: frequency",
      "Which church or particular ideological group?",
      "Church attendance frequency"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    relig01 = list(
      `2B` = no_yes_106,
      C = no_yes_74,
      D = no_yes_106,
      E = no_yes_106
    ),
    relig08 = list(
      `2B` = no_yes_106,
      `3B` = c(`-5` = "meaningful interview terminated", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      C = no_yes_74,
      D = no_yes_106,
      E = no_yes_106,
      F = c(`-2` = "na, see FRMGL", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      G = no_yes_304,
      H = no_yes_304,
      I = no_yes,
      J = no_yes,
      K = no_yes
    ),
    relig09 = list(
      `2B` = strongly_agree_agree_no_agreement_no_disagree_disagree,
      C = strongly_agree_agree_no_agreement_no_disagree_disagree_2,
      D = strongly_agree_agree_no_agreement_no_disagree_disagree,
      E = strongly_agree_agree_no_agreement_no_disagree_disagree
    ),
    relig10 = list(
      `2B` = strongly_agree_agree_no_agreement_no_disagree_disagree,
      C = strongly_agree_agree_no_agreement_no_disagree_disagree_2,
      D = strongly_agree_agree_no_agreement_no_disagree_disagree,
      E = strongly_agree_agree_no_agreement_no_disagree_disagree
    ),
    relig11 = list(
      `2B` = strongly_agree_agree_no_agreement_no_disagree_disagree,
      C = strongly_agree_agree_no_agreement_no_disagree_disagree_2,
      D = strongly_agree_agree_no_agreement_no_disagree_disagree,
      E = strongly_agree_agree_no_agreement_no_disagree_disagree
    ),
    relig12 = list(
      `2B` = strongly_agree_agree_no_agreement_no_disagree_disagree,
      C = strongly_agree_agree_no_agreement_no_disagree_disagree_2,
      D = strongly_agree_agree_no_agreement_no_disagree_disagree,
      E = strongly_agree_agree_no_agreement_no_disagree_disagree
    ),
    relig13 = list(
      `2B` = strongly_agree_agree_no_agreement_no_disagree_disagree,
      C = strongly_agree_agree_no_agreement_no_disagree_disagree_2,
      D = strongly_agree_agree_no_agreement_no_disagree_disagree,
      E = strongly_agree_agree_no_agreement_no_disagree_disagree
    ),
    relig14 = list(
      `2B` = not_recognizing_content_recognizing_content,
      C = not_recognizing_content_recognizing_content_2,
      D = not_recognizing_content_recognizing_content,
      E = not_recognizing_content_recognizing_content,
      F = not_recognizing_content_recognizing_content_3
    ),
    relig15 = list(
      `2B` = not_recognizing_content_recognizing_content,
      C = not_recognizing_content_recognizing_content_2,
      D = not_recognizing_content_recognizing_content,
      E = not_recognizing_content_recognizing_content,
      F = not_recognizing_content_recognizing_content_3
    ),
    relig16 = list(
      `2B` = not_recognizing_content_recognizing_content,
      C = not_recognizing_content_recognizing_content_2,
      D = not_recognizing_content_recognizing_content,
      E = not_recognizing_content_recognizing_content,
      F = not_recognizing_content_recognizing_content_3
    ),
    relig17 = list(
      `2B` = not_recognizing_content_recognizing_content,
      C = not_recognizing_content_recognizing_content_2,
      D = not_recognizing_content_recognizing_content,
      E = not_recognizing_content_recognizing_content,
      F = not_recognizing_content_recognizing_content_3
    ),
    relig18 = list(
      `2B` = not_recognizing_content_recognizing_content,
      C = not_recognizing_content_recognizing_content_2,
      D = not_recognizing_content_recognizing_content,
      E = not_recognizing_content_recognizing_content,
      F = not_recognizing_content_recognizing_content_3
    ),
    relig19 = list(
      `2B` = not_recognizing_content_recognizing_content,
      C = not_recognizing_content_recognizing_content_2,
      D = not_recognizing_content_recognizing_content,
      E = not_recognizing_content_recognizing_content,
      F = not_recognizing_content_recognizing_content_3
    ),
    relig1b = list(
      `2B` = never_once_a_year_or_less_a_few_times_a_year,
      D = never_once_a_year_or_less_a_few_times_a_year,
      E = never_once_a_year_or_less_a_few_times_a_year,
      F = c(
        `-2` = "na, see FRMGL",
        `-1` = "na, asked",
        `1` = "never",
        `2` = "once a year or less",
        `3` = "a few times a year",
        `4` = "approx. once a month",
        `5` = "2 or 3 times a month",
        `6` = "once a week or more"
      ),
      G = never_once_a_year_or_less_a_few_times_a_year_3,
      H = never_once_a_year_or_less_a_few_times_a_year_3,
      I = never_once_a_year_or_less_a_few_times_a_year_2,
      J = never_once_a_year_or_less_a_few_times_a_year_2,
      K = never_once_a_year_or_less_a_few_times_a_year_2,
      MB = never_less_than_once_a_month_once_a_month
    ),
    relig8a = list(
      `2B` = never_less_than_once_a_month_once_a_month_2,
      `3B` = c(
        `-5` = "frequency interview terminated",
        `-1` = "na, asked",
        `1` = "never",
        `2` = "less than once a month",
        `3` = "once a month",
        `4` = "a few times a month",
        `5` = "once a week",
        `6` = "a few times a week",
        `7` = "once a day",
        `8` = "more than once a day"
      ),
      D = never_less_than_once_a_month_once_a_month_2,
      E = never_less_than_once_a_month_once_a_month_2,
      F = c(
        `-2` = "na, see FRMGL",
        `-1` = "na, asked",
        `1` = "never",
        `2` = "less than once a month",
        `3` = "once a month",
        `4` = "a few times a month",
        `5` = "once a week",
        `6` = "a few times a week",
        `7` = "once a day",
        `8` = "more than once a day"
      ),
      G = never_less_than_once_a_month_once_a_month_3,
      H = never_less_than_once_a_month_once_a_month_3,
      I = never_less_than_once_a_month_once_a_month,
      J = never_less_than_once_a_month_once_a_month,
      K = never_less_than_once_a_month_once_a_month
    ),
    rmgl = list(
      `2B` = short_interview_interview_terminated,
      C = short_interview_interview_terminated,
      D = short_interview_interview_terminated,
      E = short_interview_interview_terminated,
      F = short_interview_interview_terminated,
      G = short_interview_interview_terminated,
      H = short_interview_interview_terminated
    ),
    relig02 = list(
      C = no_yes_74
    ),
    relig03 = list(
      C = no_yes_74
    ),
    relig04 = list(
      C = no_yes_74
    ),
    relig05 = list(
      C = no_yes_74
    ),
    relig06 = list(
      C = no_yes_74
    ),
    relig07 = list(
      C = no_yes_74
    ),
    relig1a = list(
      D = c(
        `-2` = "na, see DRELIG01",
        `-1` = "na, asked",
        `1` = "Dutch Reformed (without Ger. Bond)",
        `2` = "Ger. Bond (Dutch Reformed)",
        `3` = "Reformed Calvinist",
        `4` = "small Reformed denomination",
        `5` = "Roman-Catholic",
        `6` = "other protestant denomination",
        `7` = "Humanistic Society",
        `8` = "Jewish",
        `9` = "Muslim",
        `10` = "Hinduism",
        `11` = "other"
      ),
      MB = c(
        `-1` = "na, asked",
        `0` = "no member (not religious)",
        `1` = "Islam",
        `2` = "Roman-Catholic",
        `3` = "Protestant",
        `4` = "Jewish",
        `7` = "Orthodox",
        `8` = "Alevism",
        `9` = "Bahai"
      )
    )
  ),

  value_labels_harmonized = list(
    relig01 = no_yes_70,
    relig02 = no_yes_70,
    relig03 = no_yes_70,
    relig04 = no_yes_70,
    relig05 = no_yes_70,
    relig06 = no_yes_70,
    relig07 = no_yes_70,
    relig08 = c(
      `-5` = "meaningful interview terminated",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "no",
      `2` = "yes"
    ),
    relig09 = strongly_agree_agree_no_agreement_no_disagree_disagree_3,
    relig10 = strongly_agree_agree_no_agreement_no_disagree_disagree_3,
    relig11 = strongly_agree_agree_no_agreement_no_disagree_disagree_3,
    relig12 = strongly_agree_agree_no_agreement_no_disagree_disagree_3,
    relig13 = strongly_agree_agree_no_agreement_no_disagree_disagree_3,
    relig14 = not_recognizing_content_recognizing_content_4,
    relig15 = not_recognizing_content_recognizing_content_4,
    relig16 = not_recognizing_content_recognizing_content_4,
    relig17 = not_recognizing_content_recognizing_content_4,
    relig18 = not_recognizing_content_recognizing_content_4,
    relig19 = not_recognizing_content_recognizing_content_4,
    relig1a = c(
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `0` = "no member (not religious)",
      `1` = "coding category 1",
      `2` = "coding category 2",
      `3` = "coding category 3",
      `4` = "coding category 4",
      `5` = "Roman-Catholic",
      `6` = "other protestant denomination",
      `7` = "coding category 7",
      `8` = "coding category 8",
      `9` = "coding category 9",
      `10` = "Hinduism",
      `11` = "other"
    ),
    relig1b = c(
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "never",
      `2` = "ordinal category 2",
      `3` = "ordinal category 3",
      `4` = "ordinal category 4",
      `5` = "ordinal category 5",
      `6` = "ordinal category 6",
      `7` = "once a day",
      `8` = "more than once a day"
    ),
    relig8a = c(
      `-5` = "frequency interview terminated",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "never",
      `2` = "less than once a month",
      `3` = "once a month",
      `4` = "a few times a month",
      `5` = "once a week",
      `6` = "a few times a week",
      `7` = "once a day",
      `8` = "more than once a day"
    ),
    rmgl = short_interview_interview_terminated
  )
)
