## LASA filecode 123 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_123 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E"
    ),
    variable_name = c(
      "bqdpq01",
      "bqdpq02",
      "bqdpq03",
      "bqdpq04",
      "bqdpq05",
      "bqdpq06",
      "bqdpq07",
      "bqdpq08",
      "bqdpq09",
      "bqdpq10",
      "bqdpq11",
      "bqdpq12",
      "bqdpq13",
      "bqdpq14",
      "bqdpq15",
      "bqdpq16",
      "bqdpq17",
      "bqdpq18",
      "bqdpq19",
      "bqdpq20",
      "bqdpq21",
      "bqdpq22",
      "bqdpq23",
      "bqdpq24",
      "bqdpq25",
      "bqdpq01",
      "bqdpq02",
      "bqdpq03",
      "bqdpq04",
      "bqdpq05",
      "bqdpq06",
      "bqdpq07",
      "bqdpq08",
      "bqdpq09",
      "bqdpq10",
      "bqdpq11",
      "bqdpq12",
      "bqdpq13",
      "bqdpq14",
      "bqdpq15",
      "bqdpq16",
      "bqdpq17",
      "bqdpq18",
      "bqdpq19",
      "bqdpq20",
      "bqdpq21",
      "bqdpq22",
      "bqdpq23",
      "bqdpq24",
      "bqdpq25",
      "bqdpq01",
      "bqdpq02",
      "bqdpq03",
      "bqdpq04",
      "bqdpq05",
      "bqdpq06",
      "bqdpq07",
      "bqdpq08",
      "bqdpq09",
      "bqdpq10",
      "bqdpq11",
      "bqdpq12",
      "bqdpq13",
      "bqdpq14",
      "bqdpq15",
      "bqdpq16",
      "bqdpq17",
      "bqdpq18",
      "bqdpq19",
      "bqdpq20",
      "bqdpq21",
      "bqdpq22",
      "bqdpq23",
      "bqdpq24",
      "bqdpq25",
      "cqdpq01",
      "cqdpq02",
      "cqdpq03",
      "cqdpq04",
      "cqdpq05",
      "cqdpq06",
      "cqdpq07",
      "cqdpq08",
      "cqdpq09",
      "cqdpq10",
      "cqdpq11",
      "cqdpq12",
      "cqdpq13",
      "cqdpq14",
      "cqdpq15",
      "cqdpq16",
      "cqdpq17",
      "cqdpq18",
      "cqdpq19",
      "cqdpq20",
      "cqdpq21",
      "cqdpq22",
      "cqdpq23",
      "cqdpq24",
      "cqdpq25",
      "dqdpq01",
      "dqdpq02",
      "dqdpq03",
      "dqdpq04",
      "dqdpq05",
      "dqdpq06",
      "dqdpq07",
      "dqdpq08",
      "dqdpq09",
      "dqdpq10",
      "dqdpq11",
      "dqdpq12",
      "dqdpq13",
      "dqdpq14",
      "dqdpq15",
      "dqdpq16",
      "dqdpq17",
      "dqdpq18",
      "dqdpq19",
      "dqdpq20",
      "dqdpq21",
      "dqdpq22",
      "dqdpq23",
      "dqdpq24",
      "dqdpq25",
      "eqdpq01",
      "eqdpq02",
      "eqdpq03",
      "eqdpq04",
      "eqdpq05",
      "eqdpq06",
      "eqdpq07",
      "eqdpq08",
      "eqdpq09",
      "eqdpq10",
      "eqdpq11",
      "eqdpq12",
      "eqdpq13",
      "eqdpq14",
      "eqdpq15",
      "eqdpq16",
      "eqdpq17",
      "eqdpq18",
      "eqdpq19",
      "eqdpq20",
      "eqdpq21",
      "eqdpq22",
      "eqdpq23",
      "eqdpq24",
      "eqdpq25"
    ),
    canonical_name = c(
      "qdpq01",
      "qdpq02",
      "qdpq03",
      "qdpq04",
      "qdpq05",
      "qdpq06",
      "qdpq07",
      "qdpq08",
      "qdpq09",
      "qdpq10",
      "qdpq11",
      "qdpq12",
      "qdpq13",
      "qdpq14",
      "qdpq15",
      "qdpq16",
      "qdpq17",
      "qdpq18",
      "qdpq19",
      "qdpq20",
      "qdpq21",
      "qdpq22",
      "qdpq23",
      "qdpq24",
      "qdpq25",
      "qdpq01",
      "qdpq02",
      "qdpq03",
      "qdpq04",
      "qdpq05",
      "qdpq06",
      "qdpq07",
      "qdpq08",
      "qdpq09",
      "qdpq10",
      "qdpq11",
      "qdpq12",
      "qdpq13",
      "qdpq14",
      "qdpq15",
      "qdpq16",
      "qdpq17",
      "qdpq18",
      "qdpq19",
      "qdpq20",
      "qdpq21",
      "qdpq22",
      "qdpq23",
      "qdpq24",
      "qdpq25",
      "qdpq01",
      "qdpq02",
      "qdpq03",
      "qdpq04",
      "qdpq05",
      "qdpq06",
      "qdpq07",
      "qdpq08",
      "qdpq09",
      "qdpq10",
      "qdpq11",
      "qdpq12",
      "qdpq13",
      "qdpq14",
      "qdpq15",
      "qdpq16",
      "qdpq17",
      "qdpq18",
      "qdpq19",
      "qdpq20",
      "qdpq21",
      "qdpq22",
      "qdpq23",
      "qdpq24",
      "qdpq25",
      "qdpq01",
      "qdpq02",
      "qdpq03",
      "qdpq04",
      "qdpq05",
      "qdpq06",
      "qdpq07",
      "qdpq08",
      "qdpq09",
      "qdpq10",
      "qdpq11",
      "qdpq12",
      "qdpq13",
      "qdpq14",
      "qdpq15",
      "qdpq16",
      "qdpq17",
      "qdpq18",
      "qdpq19",
      "qdpq20",
      "qdpq21",
      "qdpq22",
      "qdpq23",
      "qdpq24",
      "qdpq25",
      "qdpq01",
      "qdpq02",
      "qdpq03",
      "qdpq04",
      "qdpq05",
      "qdpq06",
      "qdpq07",
      "qdpq08",
      "qdpq09",
      "qdpq10",
      "qdpq11",
      "qdpq12",
      "qdpq13",
      "qdpq14",
      "qdpq15",
      "qdpq16",
      "qdpq17",
      "qdpq18",
      "qdpq19",
      "qdpq20",
      "qdpq21",
      "qdpq22",
      "qdpq23",
      "qdpq24",
      "qdpq25",
      "qdpq01",
      "qdpq02",
      "qdpq03",
      "qdpq04",
      "qdpq05",
      "qdpq06",
      "qdpq07",
      "qdpq08",
      "qdpq09",
      "qdpq10",
      "qdpq11",
      "qdpq12",
      "qdpq13",
      "qdpq14",
      "qdpq15",
      "qdpq16",
      "qdpq17",
      "qdpq18",
      "qdpq19",
      "qdpq20",
      "qdpq21",
      "qdpq22",
      "qdpq23",
      "qdpq24",
      "qdpq25"
    ),
    variable_label = c(
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience",
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience",
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience",
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience",
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience",
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience"
    ),
    harmonized_var_label = c(
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience",
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience",
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience",
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience",
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience",
      "DPQ 01: bad temper",
      "DPQ 02: wander off",
      "DPQ 03: strangers",
      "DPQ 04: control",
      "DPQ 05: nervous",
      "DPQ 06: people",
      "DPQ 07: humour",
      "DPQ 08: contact",
      "DPQ 09: feeling down",
      "DPQ 10: receptions",
      "DPQ 11: small matters",
      "DPQ 12: shy",
      "DPQ 13: different",
      "DPQ 14: new friends",
      "DPQ 15: useless",
      "DPQ 16: background",
      "DPQ 17: tension",
      "DPQ 18: influence",
      "DPQ 19: regret",
      "DPQ 20: restlessness",
      "DPQ 21: surrounded",
      "DPQ 22: hate",
      "DPQ 23: shy 2",
      "DPQ 24: difficult",
      "DPQ 25: inconvenience"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qdpq01 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq02 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq03 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq04 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq05 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq06 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq07 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq08 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq09 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq10 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq11 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq12 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq13 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq14 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq15 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq16 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq17 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq18 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq19 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq20 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq21 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq22 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq23 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq24 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    ),
    qdpq25 = list(
      `2B` = applicable_not_applicable,
      `3B` = applicable_not_applicable,
      B = applicable_not_applicable,
      C = applicable_not_applicable,
      D = applicable_not_applicable,
      E = applicable_not_applicable
    )
  ),

  value_labels_harmonized = list(
    qdpq01 = applicable_not_applicable_2,
    qdpq02 = applicable_not_applicable_2,
    qdpq03 = applicable_not_applicable_2,
    qdpq04 = applicable_not_applicable_2,
    qdpq05 = applicable_not_applicable_2,
    qdpq06 = applicable_not_applicable_2,
    qdpq07 = applicable_not_applicable_2,
    qdpq08 = applicable_not_applicable_2,
    qdpq09 = applicable_not_applicable_2,
    qdpq10 = applicable_not_applicable_2,
    qdpq11 = applicable_not_applicable_2,
    qdpq12 = applicable_not_applicable_2,
    qdpq13 = applicable_not_applicable_2,
    qdpq14 = applicable_not_applicable_2,
    qdpq15 = applicable_not_applicable_2,
    qdpq16 = applicable_not_applicable_2,
    qdpq17 = applicable_not_applicable_2,
    qdpq18 = applicable_not_applicable_2,
    qdpq19 = applicable_not_applicable_2,
    qdpq20 = applicable_not_applicable_2,
    qdpq21 = applicable_not_applicable_2,
    qdpq22 = applicable_not_applicable_2,
    qdpq23 = applicable_not_applicable_2,
    qdpq24 = applicable_not_applicable_2,
    qdpq25 = applicable_not_applicable_2
  )
)
