## LASA filecode 151 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_151 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bmarmds1",
      "bmarmds2",
      "bmarmds3",
      "bmarmds4",
      "bmarmpa1",
      "bmarmpa2",
      "bmarmps1",
      "bmarmps2",
      "bmarmps3",
      "bmarmps4",
      "bmarmss1",
      "bmarmss2",
      "bmarmss3",
      "bmarmss4",
      "bmarmds01",
      "bmarmds02",
      "bmarmds1",
      "bmarmds2",
      "bmarmpa0",
      "bmarmpar",
      "bmarmps01",
      "bmarmps02",
      "bmarmps1",
      "bmarmps2",
      "bmarmss01",
      "bmarmss02",
      "bmarmss1",
      "bmarmss2",
      "bmfinps1",
      "bmfinps2",
      "bmfinps3",
      "cmarmds1",
      "cmarmlds1",
      "cmarmlps1",
      "cmarmlss1",
      "cmarmpa1",
      "cmarmpa2",
      "cmarmpa3",
      "cmarmpa4",
      "cmarmpa4o",
      "cmarmpar",
      "cmarmps1",
      "cmarmsds1",
      "cmarmsps1",
      "cmarmss1",
      "cmarmsss1",
      "cmfinds1",
      "cmfinpos1",
      "cmfinps1",
      "cmfinss1",
      "crm151",
      "dmarmds1",
      "dmarmlds1",
      "dmarmlps1",
      "dmarmlss1",
      "dmarmpa1",
      "dmarmpa2",
      "dmarmpa3",
      "dmarmpa4",
      "dmarmpar",
      "dmarmps1",
      "dmarmsds1",
      "dmarmsps1",
      "dmarmss1",
      "dmarmsss1",
      "dmfinds1",
      "dmfinpo1",
      "dmfinps1",
      "dmfinss1",
      "emarmds1",
      "emarmds2",
      "emarmds3",
      "emarmpar",
      "emarmps1",
      "emarmps2",
      "emarmps3",
      "emarmss1",
      "emarmss2",
      "emarmss3",
      "fmarmds1",
      "fmarmds2",
      "fmarmds3",
      "fmarmpar",
      "fmarmps1",
      "fmarmps2",
      "fmarmps3",
      "fmarmss1",
      "fmarmss2",
      "fmarmss3",
      "gmarmds0",
      "gmarmds1",
      "gmarmds2",
      "gmarmds3",
      "gmarmpa0",
      "gmarmpar",
      "gmarmps0",
      "gmarmps1",
      "gmarmps2",
      "gmarmps3",
      "gmarmss0",
      "gmarmss1",
      "gmarmss2",
      "gmarmss3",
      "hmarmds0",
      "hmarmds1",
      "hmarmpa0",
      "hmarmpar",
      "hmarmps0",
      "hmarmps1",
      "hmarmss0",
      "hmarmss1",
      "imarmds0",
      "imarmds1",
      "imarmpa0",
      "imarmpar",
      "imarmps0",
      "imarmps1",
      "imarmss0",
      "imarmss1",
      "jmarmds0",
      "jmarmds1",
      "jmarmpa0",
      "jmarmpar",
      "jmarmps0",
      "jmarmps1",
      "jmarmss0",
      "jmarmss1",
      "kmarmds0",
      "kmarmds1",
      "kmarmpa0",
      "kmarmpar",
      "kmarmps0",
      "kmarmps1",
      "kmarmss0",
      "kmarmss1",
      "bmarmds1",
      "bmarmds2",
      "bmarmpar",
      "bmarmps1",
      "bmarmps2",
      "bmarmss1",
      "bmarmss2"
    ),
    canonical_name = c(
      "marmds1",
      "marmds2",
      "marmds3",
      "marmds4",
      "marmpa1",
      "marmpa2",
      "marmps1",
      "marmps2",
      "marmps3",
      "marmps4",
      "marmss1",
      "marmss2",
      "marmss3",
      "marmss4",
      "marmds01",
      "marmds02",
      "marmds1",
      "marmds2",
      "marmpa0",
      "marmpar",
      "marmps01",
      "marmps02",
      "marmps1",
      "marmps2",
      "marmss01",
      "marmss02",
      "marmss1",
      "marmss2",
      "mfinps1",
      "mfinps2",
      "mfinps3",
      "marmds1",
      "marmlds1",
      "marmlps1",
      "marmlss1",
      "marmpa1",
      "marmpa2",
      "marmpa3",
      "marmpa4",
      "marmpa4o",
      "marmpar",
      "marmps1",
      "marmsds1",
      "marmsps1",
      "marmss1",
      "marmsss1",
      "mfinds1",
      "mfinpos1",
      "mfinps1",
      "mfinss1",
      "rm151",
      "marmds1",
      "marmlds1",
      "marmlps1",
      "marmlss1",
      "marmpa1",
      "marmpa2",
      "marmpa3",
      "marmpa4",
      "marmpar",
      "marmps1",
      "marmsds1",
      "marmsps1",
      "marmss1",
      "marmsss1",
      "mfinds1",
      "mfinpo1",
      "mfinps1",
      "mfinss1",
      "marmds1",
      "marmds2",
      "marmds3",
      "marmpar",
      "marmps1",
      "marmps2",
      "marmps3",
      "marmss1",
      "marmss2",
      "marmss3",
      "marmds1",
      "marmds2",
      "marmds3",
      "marmpar",
      "marmps1",
      "marmps2",
      "marmps3",
      "marmss1",
      "marmss2",
      "marmss3",
      "marmds0",
      "marmds1",
      "marmds2",
      "marmds3",
      "marmpa0",
      "marmpar",
      "marmps0",
      "marmps1",
      "marmps2",
      "marmps3",
      "marmss0",
      "marmss1",
      "marmss2",
      "marmss3",
      "marmds0",
      "marmds1",
      "marmpa0",
      "marmpar",
      "marmps0",
      "marmps1",
      "marmss0",
      "marmss1",
      "marmds0",
      "marmds1",
      "marmpa0",
      "marmpar",
      "marmps0",
      "marmps1",
      "marmss0",
      "marmss1",
      "marmds0",
      "marmds1",
      "marmpa0",
      "marmpar",
      "marmps0",
      "marmps1",
      "marmss0",
      "marmss1",
      "marmds0",
      "marmds1",
      "marmpa0",
      "marmpar",
      "marmps0",
      "marmps1",
      "marmss0",
      "marmss1",
      "marmds1",
      "marmds2",
      "marmpar",
      "marmps1",
      "marmps2",
      "marmss1",
      "marmss2"
    ),
    variable_label = c(
      "Bloodpr 1 sitting (arm) mmHg: diastolic",
      "Bloodpr 2 sitting (arm) mmHg: diastolic",
      "Retest Bloodpr 3 sitting (arm) mmHg: diastolic",
      "Retest Bloodpr 4 sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure",
      "Retest Particularities bloodpressure",
      "Pulse rate sitting (arm) 1",
      "Pulse rate sitting (arm) 2",
      "Retest Pulse rate 3 sitting (arm)",
      "Retest Pulse rate 4 sitting (arm)",
      "Bloodpr 1 sitting (arm) mmHg: systolic",
      "Bloodpr 2 sitting (arm) mmHg: systolic",
      "Retest Bloodpr 3 sitting (arm) mmHg: systolic",
      "Retest Bloodpr 4 sitting (arm) mmHg: systolic",
      "Pretest 1: bloodpr sit (arm) mmHg: diastolic",
      "Pretest 2: bloodpr sit (arm) mmHg: diastolic",
      "Bloodpr 1 sitting (arm) mmHg: diastolic",
      "Bloodpr 2 sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure Pretest",
      "Particularities bloodpressure",
      "Pretest 1: pulse rate sit (arm)",
      "Pretest 2: pulse rate sit (arm)",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Pretest 1: bloodpr sit (arm) mmHg: systolic",
      "Pretest 2: bloodpr sit (arm) mmHg: systolic",
      "Bloodpr 1 sitting (arm) mmHg: systolic",
      "Bloodpr 2 sitting (arm) mmHg: systolic",
      "Pulse rate (1)",
      "Pulse rate (2)",
      "Pulse rate (3)",
      "Bloodpr sitting (arm) mmHg: diastolic",
      "Bloodpr lying (arm) mmHg: diastolic",
      "Pulse rate lying (arm)",
      "Bloodpr lying (arm) mmHg: systolic",
      "Partic. bloodpressure: cannot stand",
      "Partic. bloodpressure: cannot sit",
      "Partic. bloodpressure: cannot lie down",
      "Partic. bloodpressure: other",
      "Partic other: specification",
      "Particularities bloodpressure",
      "Pulse rate sitting (arm)",
      "Bloodpr standing (arm) mmHg: diastolic",
      "Pulse rate standing (arm)",
      "Bloodpr sitting (arm) mmHg: systolic",
      "Bloodpr standing (arm) mmHg: systolic",
      "Bloodpressure (finger) mmHg: diastolic",
      "Blood pressure (finger): position",
      "Pulse rate (finger)",
      "Bloodpressure (finger) mmHg: systolic",
      "Reason missing: LASAC151",
      "Bloodpr sitting (arm) mmHg: diastolic",
      "Bloodpr lying (arm) mmHg: diastolic",
      "Pulse rate lying (arm)",
      "Bloodpr lying (arm) mmHg: systolic",
      "Partic. bloodpressure: cannot stand",
      "Partic. bloodpressure: cannot sit",
      "Partic. bloodpressure: cannot lie down",
      "Partic. bloodpressure: other",
      "Particularities bloodpressure",
      "Pulse rate sitting (arm)",
      "Bloodpr standing (arm) mmHg: diastolic",
      "Pulse rate standing (arm)",
      "Bloodpr sitting (arm) mmHg: systolic",
      "Bloodpr standing (arm) mmHg: systolic",
      "Bloodpressure (finger) mmHg: diastolic",
      "Blood pressure (finger): position",
      "Pulse rate (finger)",
      "Bloodpressure (finger) mmHg: systolic",
      "Bloodpr 1 sitting (arm) mmHg: diastolic",
      "Bloodpr 2 sitting (arm) mmHg: diastolic",
      "Bloodpr 3 sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Pulse rate 3 sitting (arm)",
      "Bloodpr 1 sitting (arm) mmHg: systolic",
      "Bloodpr 2 sitting (arm) mmHg: systolic",
      "Bloodpr 3 sitting (arm) mmHg: systolic",
      "Bloodpr 1 sitting (arm) mmHg: diastolic",
      "Bloodpr 2 sitting (arm) mmHg: diastolic",
      "Bloodpr 3 sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Pulse rate 3 sitting (arm)",
      "Bloodpr 1 sitting (arm) mmHg: systolic",
      "Bloodpr 2 sitting (arm) mmHg: systolic",
      "Bloodpr 3 sitting (arm) mmHg: systolic",
      "Pretest: bloodpr 0 sit (arm) mmHg: diastolic",
      "Bloodpr 1 sitting (arm) mmHg: diastolic",
      "Bloodpr 2 sitting (arm) mmHg: diastolic",
      "Bloodpr 3 sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure Pretest",
      "Particularities bloodpressure",
      "Pretest: pulse rate 0 sit (arm)",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Pulse rate 3 sitting (arm)",
      "Pretest: bloodpr 0 sit (arm) mmHg: systolic",
      "Bloodpr 1 sitting (arm) mmHg: systolic",
      "Bloodpr 2 sitting (arm) mmHg: systolic",
      "Bloodpr 3 sitting (arm) mmHg: systolic",
      "Pretest: bloodpressure (0) sitting (arm) mmHg: diastolic",
      "Bloodpressure (1) sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure Pretest",
      "Particularities bloodpressure",
      "Pretest: pulse rate (0) sitting (arm)",
      "Pulse rate (1) sitting (arm)",
      "Pretest: bloodpressure (0) sitting (arm) mmHg: systolic",
      "Bloodpressure (1) sitting (arm) mmHg: systolic",
      "Pretest: bloodpressure (0) sitting (arm) mmHg: diastolic",
      "Bloodpressure (1) sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure pretest",
      "Particularities bloodpressure",
      "Pretest: pulse rate (0) sitting (arm)",
      "Pulse rate (1) sitting (arm)",
      "Pretest: bloodpressure (0) sitting (arm) mmHg: systolic",
      "Bloodpressure (1) sitting (arm) mmHg: systolic",
      "Pretest: bloodpressure (0) sitting (arm) mmHg: diastolic",
      "Bloodpressure (1) sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure pretest",
      "Particularities bloodpressure",
      "Pretest: pulse rate (0) sitting (arm)",
      "Pulse rate (1) sitting (arm)",
      "Pretest: bloodpressure (0) sitting (arm) mmHg: systolic",
      "Bloodpressure (1) sitting (arm) mmHg: systolic",
      "Pretest: bloodpressure (0) sitting (arm) mmHg: diastolic",
      "Bloodpressure (1) sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure pretest",
      "Particularities bloodpressure",
      "Pretest: pulse rate (0) sitting (arm)",
      "Pulse rate (1) sitting (arm)",
      "Pretest: bloodpressure (0) sitting (arm) mmHg: systolic",
      "Bloodpressure (1) sitting (arm) mmHg: systolic",
      "Bloodpr 1 sitting (arm) mmHg: diastolic",
      "Bloodpr 2 sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Bloodpr 1 sitting (arm) mmHg: systolic",
      "Bloodpr 2 sitting (arm) mmHg: systolic"
    ),
    harmonized_var_label = c(
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Blood pressure 2 sitting (arm) mmHg: diastolic",
      "Blood pressure 3 sitting (arm) mmHg: diastolic",
      "Retest Bloodpr 4 sitting (arm) mmHg: diastolic",
      "Blood pressure particularities item 1",
      "Blood pressure particularities item 2",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Pulse rate 3 sitting (arm)",
      "Retest Pulse rate 4 sitting (arm)",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Blood pressure 2 sitting (arm) mmHg: systolic",
      "Blood pressure 3 sitting (arm) mmHg: systolic",
      "Retest Bloodpr 4 sitting (arm) mmHg: systolic",
      "Pretest 1: bloodpr sit (arm) mmHg: diastolic",
      "Pretest 2: bloodpr sit (arm) mmHg: diastolic",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Blood pressure 2 sitting (arm) mmHg: diastolic",
      "Pretest blood pressure particularities",
      "Particularities bloodpressure",
      "Pretest 1: pulse rate sit (arm)",
      "Pretest 2: pulse rate sit (arm)",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Pretest 1: bloodpr sit (arm) mmHg: systolic",
      "Pretest 2: bloodpr sit (arm) mmHg: systolic",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Blood pressure 2 sitting (arm) mmHg: systolic",
      "Pulse rate measurement 1",
      "Pulse rate (2)",
      "Pulse rate (3)",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Bloodpr lying (arm) mmHg: diastolic",
      "Pulse rate lying (arm)",
      "Bloodpr lying (arm) mmHg: systolic",
      "Blood pressure particularities item 1",
      "Blood pressure particularities item 2",
      "Partic. bloodpressure: cannot lie down",
      "Partic. bloodpressure: other",
      "Partic other: specification",
      "Particularities bloodpressure",
      "Pulse rate 1 sitting (arm)",
      "Bloodpr standing (arm) mmHg: diastolic",
      "Pulse rate standing (arm)",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Bloodpr standing (arm) mmHg: systolic",
      "Bloodpressure (finger) mmHg: diastolic",
      "Blood pressure (finger): position",
      "Pulse rate measurement 1",
      "Bloodpressure (finger) mmHg: systolic",
      "Reason missing: LASAC151",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Bloodpr lying (arm) mmHg: diastolic",
      "Pulse rate lying (arm)",
      "Bloodpr lying (arm) mmHg: systolic",
      "Blood pressure particularities item 1",
      "Blood pressure particularities item 2",
      "Partic. bloodpressure: cannot lie down",
      "Partic. bloodpressure: other",
      "Particularities bloodpressure",
      "Pulse rate 1 sitting (arm)",
      "Bloodpr standing (arm) mmHg: diastolic",
      "Pulse rate standing (arm)",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Bloodpr standing (arm) mmHg: systolic",
      "Bloodpressure (finger) mmHg: diastolic",
      "Blood pressure (finger): position",
      "Pulse rate measurement 1",
      "Bloodpressure (finger) mmHg: systolic",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Blood pressure 2 sitting (arm) mmHg: diastolic",
      "Blood pressure 3 sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Pulse rate 3 sitting (arm)",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Blood pressure 2 sitting (arm) mmHg: systolic",
      "Blood pressure 3 sitting (arm) mmHg: systolic",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Blood pressure 2 sitting (arm) mmHg: diastolic",
      "Blood pressure 3 sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Pulse rate 3 sitting (arm)",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Blood pressure 2 sitting (arm) mmHg: systolic",
      "Blood pressure 3 sitting (arm) mmHg: systolic",
      "Pretest blood pressure 0 sitting (arm) mmHg: diastolic",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Blood pressure 2 sitting (arm) mmHg: diastolic",
      "Blood pressure 3 sitting (arm) mmHg: diastolic",
      "Pretest blood pressure particularities",
      "Particularities bloodpressure",
      "Pretest pulse rate 0 sitting (arm)",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Pulse rate 3 sitting (arm)",
      "Pretest blood pressure 0 sitting (arm) mmHg: systolic",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Blood pressure 2 sitting (arm) mmHg: systolic",
      "Blood pressure 3 sitting (arm) mmHg: systolic",
      "Pretest blood pressure 0 sitting (arm) mmHg: diastolic",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Pretest blood pressure particularities",
      "Particularities bloodpressure",
      "Pretest pulse rate 0 sitting (arm)",
      "Pulse rate 1 sitting (arm)",
      "Pretest blood pressure 0 sitting (arm) mmHg: systolic",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Pretest blood pressure 0 sitting (arm) mmHg: diastolic",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Pretest blood pressure particularities",
      "Particularities bloodpressure",
      "Pretest pulse rate 0 sitting (arm)",
      "Pulse rate 1 sitting (arm)",
      "Pretest blood pressure 0 sitting (arm) mmHg: systolic",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Pretest blood pressure 0 sitting (arm) mmHg: diastolic",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Pretest blood pressure particularities",
      "Particularities bloodpressure",
      "Pretest pulse rate 0 sitting (arm)",
      "Pulse rate 1 sitting (arm)",
      "Pretest blood pressure 0 sitting (arm) mmHg: systolic",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Pretest blood pressure 0 sitting (arm) mmHg: diastolic",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Pretest blood pressure particularities",
      "Particularities bloodpressure",
      "Pretest pulse rate 0 sitting (arm)",
      "Pulse rate 1 sitting (arm)",
      "Pretest blood pressure 0 sitting (arm) mmHg: systolic",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Blood pressure 1 sitting (arm) mmHg: diastolic",
      "Blood pressure 2 sitting (arm) mmHg: diastolic",
      "Particularities bloodpressure",
      "Pulse rate 1 sitting (arm)",
      "Pulse rate 2 sitting (arm)",
      "Blood pressure 1 sitting (arm) mmHg: systolic",
      "Blood pressure 2 sitting (arm) mmHg: systolic"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    marmds1 = list(
      `2B` = no_valid_measurement,
      C = no_valid_measurement
    ),
    marmds3 = list(
      `2B` = no_valid_measurement
    ),
    marmpa1 = list(
      `2B` = normal_measurement_cannot_sit_other_to_be_coded,
      C = not_mentioned_mentioned_273,
      D = not_mentioned_mentioned_251
    ),
    marmpa2 = list(
      `2B` = normal_measurement_cannot_sit_other_to_be_coded,
      C = not_mentioned_mentioned_273,
      D = not_mentioned_mentioned_251
    ),
    marmss1 = list(
      `2B` = c(`-2` = "na, see BMARMPA1", `-1` = "no valid measurement"),
      C = na_see_crm151,
      E = no_valid_measurement,
      F = no_valid_measurement,
      G = no_valid_measurement,
      MB = no_valid_measurement
    ),
    marmss3 = list(
      `2B` = c(`-2` = "na, see BMARMPA2", `-1` = "no valid measurement")
    ),
    marmpa0 = list(
      `3B` = r_cannot_sit_measurement_error,
      G = r_cannot_sit_measurement_error,
      H = r_cannot_sit_measurement_error,
      I = r_cannot_sit_measurement_error,
      J = r_cannot_sit_measurement_error,
      K = r_cannot_sit_measurement_error
    ),
    marmps02 = list(
      `3B` = no_valid_measurement
    ),
    marmss01 = list(
      `3B` = no_valid_measurement
    ),
    mfinps1 = list(
      B = c(`-1` = NA_character_)
    ),
    marmpa3 = list(
      C = not_mentioned_mentioned_273,
      D = not_mentioned_mentioned_251
    ),
    marmpa4 = list(
      C = c(`-2` = "na, see CMARMPAR", `0` = "not mentioned", `1` = "mentioned --> CMARMPA4O"),
      D = not_mentioned_mentioned_251
    ),
    marmpa4o = list(
      C = c(
        `-2` = "na, see CMARMPA4",
        `1` = "measurement error",
        `2` = "refused",
        `3` = "problem with finger",
        `4` = "measurement on right arm",
        `5` = "miscellaneous",
        `6` = "no normal score",
        `7` = "no specification"
      )
    ),
    marmpar = list(
      C = c(`-2` = "na, see CRM151", `1` = "no", `2` = "yes"),
      D = no_yes,
      E = c(
        `-3` = "test not done",
        `-1` = "normal test",
        `1` = "R cannot sit",
        `2` = "measurement error",
        `3` = "painful arm, no measurement",
        `4` = "measurement on right arm",
        `5` = "(part of) test refused",
        `6` = "part of test wrongfully not done"
      ),
      F = r_cannot_sit_measurement_error,
      G = r_cannot_sit_measurement_error,
      MB = r_cannot_sit_measurement_error
    ),
    mfinds1 = list(
      C = no_valid_measurement
    ),
    mfinpos1 = list(
      C = c(
        `-2` = "na, see CRM151",
        `-1` = "no valid measurement",
        `1` = "standing",
        `2` = "sitting",
        `3` = "lying down"
      )
    ),
    mfinss1 = list(
      C = na_see_crm151,
      D = no_valid_measurement
    ),
    rm151 = list(
      C = interview_terminated
    ),
    marmps2 = list(
      G = no_valid_measurement
    ),
    marmss0 = list(
      G = no_valid_measurement,
      H = no_valid_measurement,
      I = no_valid_measurement,
      J = no_valid_measurement,
      K = no_valid_measurement
    ),
    marmps0 = list(
      I = no_valid_measurement,
      J = no_valid_measurement,
      K = no_valid_measurement
    )
  ),

  value_labels_harmonized = list(
    marmds1 = not_available,
    marmds3 = not_available,
    marmpa0 = r_cannot_sit_measurement_error_2,
    marmpa1 = not_mentioned_mentioned_other_to_be_coded,
    marmpa2 = not_mentioned_mentioned_other_to_be_coded,
    marmpa3 = c(`-2` = "not available", `0` = "not mentioned", `1` = "mentioned"),
    marmpa4 = c(`-2` = "not available", `0` = "not mentioned", `1` = "mentioned --> CMARMPA4O"),
    marmpa4o = c(
      `-2` = "not available",
      `1` = "measurement error",
      `2` = "refused",
      `3` = "problem with finger",
      `4` = "measurement on right arm",
      `5` = "miscellaneous",
      `6` = "no normal score",
      `7` = "no specification"
    ),
    marmpar = r_cannot_sit_measurement_error_2,
    marmps0 = not_available,
    marmps02 = not_available,
    marmps2 = not_available,
    marmss0 = not_available,
    marmss01 = not_available,
    marmss1 = not_available_not_available,
    marmss3 = not_available_not_available,
    mfinds1 = not_available,
    mfinpos1 = c(
      `-2` = "not available",
      `-1` = "not available",
      `1` = "standing",
      `2` = "sitting",
      `3` = "lying down"
    ),
    mfinps1 = not_available,
    mfinss1 = not_available_not_available,
    rm151 = c(`-2` = "not available", `2` = "interview terminated")
  )
)
