## LASA filecode 225 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_225 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "3B",
      "3B",
      "B",
      "B",
      "C",
      "C",
      "D",
      "D",
      "E",
      "E",
      "F",
      "F",
      "G",
      "G",
      "H",
      "H",
      "I",
      "I",
      "J",
      "J",
      "K",
      "K",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bcesdint",
      "brmcesd",
      "bcesdint",
      "brmcesd",
      "bcesdint",
      "brmcesd",
      "ccesdint",
      "crmcesd",
      "dcesdint",
      "drmcesd",
      "ecesdint",
      "ermcesd",
      "fcesdint",
      "frmcesd",
      "gcesdint",
      "grmcesd",
      "hcesdint",
      "hrmcesd",
      "icesdint",
      "irmcesd",
      "jcesdint",
      "jrmcesd",
      "kcesdint",
      "krmcesd",
      "bcesdint",
      "brmcesd"
    ),
    canonical_name = c(
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd",
      "cesdint",
      "rmcesd"
    ),
    variable_label = c(
      "2B CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "3B CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "B CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "C CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "D CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "E CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "F CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "G CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "H CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "I CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "J CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "K CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score",
      "MB CES-D SCALE TOTAL SCORE INTEGER",
      "reason missing ces-d score"
    ),
    harmonized_var_label = c(
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score",
      "CES-D total score",
      "Reason for missing CES-D score"
    ),
    var_type = c(
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    cesdint = list(
      `2B` = cut_off,
      `3B` = cut_off,
      B = c(`-2` = "na, see BRMCESD", `0` = NA_character_, `16` = "cut off", `60` = NA_character_),
      C = cut_off,
      D = cut_off,
      E = cut_off,
      F = cut_off,
      G = cut_off,
      H = cut_off,
      I = cut_off,
      J = cut_off,
      K = cut_off,
      MB = cut_off
    ),
    rmcesd = list(
      `2B` = c(`-2` = "valid score", `2` = "interview terminated", `3` = "too many missings"),
      `3B` = short_interview_interview_terminated_too_many_missings,
      B = short_interview_interview_terminated_too_many_missings_3,
      C = short_interview_interview_terminated_too_many_missings,
      D = short_interview_interview_terminated_too_many_missings,
      E = short_interview_interview_terminated_too_many_missings,
      F = short_interview_interview_terminated_too_many_missings,
      G = short_interview_interview_terminated_too_many_missings,
      H = short_interview_interview_terminated_too_many_missings,
      I = short_interview_interview_terminated_too_many_missings,
      J = short_interview_interview_terminated_too_many_missings,
      K = short_interview_interview_terminated_too_many_missings,
      MB = c(
        `-2` = "valid score",
        `1` = "short interview",
        `2` = "interview terminated",
        `3` = "too many missings",
        `4` = "no valid data"
      )
    )
  ),

  value_labels_harmonized = list(
    cesdint = cut_off,
    rmcesd = c(
      `-2` = "valid score",
      `1` = "short interview",
      `2` = "interview terminated",
      `3` = "too many missings",
      `4` = "refused test / no valid data"
    )
  )
)
