## LASA filecode 177 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_177 <- list(
  variables = data.frame(
    wave = c(
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "gmwvg01",
      "gmwvg02",
      "gmwvg03",
      "gmwvg04",
      "gmwvg05",
      "gmwvg06",
      "gmwvg07",
      "gmwvg08",
      "gmwvg09",
      "gmwvg10",
      "gmwvg11",
      "hmwvg01",
      "hmwvg02",
      "hmwvg03",
      "hmwvg04",
      "hmwvg05",
      "hmwvg06",
      "hmwvg07",
      "hmwvg08",
      "hmwvg09",
      "hmwvg10",
      "hmwvg11",
      "imwvg01",
      "imwvg02",
      "imwvg03",
      "imwvg05",
      "imwvg06",
      "imwvg07",
      "imwvg11",
      "jmwvg01",
      "jmwvg02",
      "jmwvg03",
      "jmwvg05",
      "jmwvg06",
      "jmwvg07",
      "kmwvg02",
      "kmwvg03",
      "kmwvg05",
      "kmwvg06",
      "kmwvg07"
    ),
    canonical_name = c(
      "mwvg01",
      "mwvg02",
      "mwvg03",
      "mwvg04",
      "mwvg05",
      "mwvg06",
      "mwvg07",
      "mwvg08",
      "mwvg09",
      "mwvg10",
      "mwvg11",
      "mwvg01",
      "mwvg02",
      "mwvg03",
      "mwvg04",
      "mwvg05",
      "mwvg06",
      "mwvg07",
      "mwvg08",
      "mwvg09",
      "mwvg10",
      "mwvg11",
      "mwvg01",
      "mwvg02",
      "mwvg03",
      "mwvg05",
      "mwvg06",
      "mwvg07",
      "mwvg11",
      "mwvg01",
      "mwvg02",
      "mwvg03",
      "mwvg05",
      "mwvg06",
      "mwvg07",
      "mwvg02",
      "mwvg03",
      "mwvg05",
      "mwvg06",
      "mwvg07"
    ),
    variable_label = c(
      "WVG 01: Walking frame",
      "WVG 02: Wheelchair",
      "WVG 03: Mobility scooter, adjusted bicycle",
      "WVG 04: Taxi pass",
      "WVG 05: Car adjustment",
      "WVG 06: Transport compensation",
      "WVG 07: Disabled parking permit",
      "WVG 08: Personal alarm",
      "WVG 09: Meals on wheels",
      "WVG 10: Handyman",
      "WVG 11: Grocery shopping service",
      "WVG 01: Walking frame",
      "WVG 02: Wheelchair",
      "WVG 03: Mobility scooter, adjusted bicycle",
      "WVG 04: Taxi pass",
      "WVG 05: Car adjustment",
      "WVG 06: Transport compensation",
      "WVG 07: Disabled parking permit",
      "WVG 08: Personal alarm",
      "WVG 09: Meals on wheels",
      "WVG 10: Handyman",
      "WVG 11: Grocery shopping service",
      "WVG 01: Walking frame",
      "WVG 02: Wheelchair",
      "WVG 03: Mobility scooter, adjusted bicycle",
      "WVG 05: Car adjustment",
      "WVG 06: Transport compensation",
      "WVG 07: Disabled parking permit",
      "WVG 11: Grocery shopping service",
      "WVG 01: Walking frame",
      "WVG 02: Wheelchair",
      "WVG 03: Mobility scooter, adjusted bicycle",
      "WVG 05: Car adjustment",
      "WVG 06: Transport compensation",
      "WVG 07: Disabled parking permit",
      "WVG 02: Wheelchair",
      "WVG 03: Mobility scooter, adjusted bicycle",
      "WVG 05: Car adjustment",
      "WVG 06: Transport compensation",
      "WVG 07: Disabled parking permit"
    ),
    harmonized_var_label = c(
      "WVG 01: Walking frame",
      "WVG 02: Wheelchair",
      "WVG 03: Mobility scooter, adjusted bicycle",
      "WVG 04: Taxi pass",
      "WVG 05: Car adjustment",
      "WVG 06: Transport compensation",
      "WVG 07: Disabled parking permit",
      "WVG 08: Personal alarm",
      "WVG 09: Meals on wheels",
      "WVG 10: Handyman",
      "WVG 11: Grocery shopping service",
      "WVG 01: Walking frame",
      "WVG 02: Wheelchair",
      "WVG 03: Mobility scooter, adjusted bicycle",
      "WVG 04: Taxi pass",
      "WVG 05: Car adjustment",
      "WVG 06: Transport compensation",
      "WVG 07: Disabled parking permit",
      "WVG 08: Personal alarm",
      "WVG 09: Meals on wheels",
      "WVG 10: Handyman",
      "WVG 11: Grocery shopping service",
      "WVG 01: Walking frame",
      "WVG 02: Wheelchair",
      "WVG 03: Mobility scooter, adjusted bicycle",
      "WVG 05: Car adjustment",
      "WVG 06: Transport compensation",
      "WVG 07: Disabled parking permit",
      "WVG 11: Grocery shopping service",
      "WVG 01: Walking frame",
      "WVG 02: Wheelchair",
      "WVG 03: Mobility scooter, adjusted bicycle",
      "WVG 05: Car adjustment",
      "WVG 06: Transport compensation",
      "WVG 07: Disabled parking permit",
      "WVG 02: Wheelchair",
      "WVG 03: Mobility scooter, adjusted bicycle",
      "WVG 05: Car adjustment",
      "WVG 06: Transport compensation",
      "WVG 07: Disabled parking permit"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    mwvg01 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no,
      I = own_and_use_own_no_use_no,
      J = own_and_use_own_no_use_no
    ),
    mwvg02 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no,
      I = own_and_use_own_no_use_no,
      J = own_and_use_own_no_use_no,
      K = own_and_use_own_no_use_no
    ),
    mwvg03 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no,
      I = own_and_use_own_no_use_no,
      J = own_and_use_own_no_use_no,
      K = own_and_use_own_no_use_no
    ),
    mwvg04 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no
    ),
    mwvg05 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no,
      I = own_and_use_own_no_use_no,
      J = own_and_use_own_no_use_no,
      K = own_and_use_own_no_use_no
    ),
    mwvg06 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no,
      I = own_and_use_own_no_use_no,
      J = own_and_use_own_no_use_no,
      K = own_and_use_own_no_use_no
    ),
    mwvg07 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no,
      I = own_and_use_own_no_use_no,
      J = own_and_use_own_no_use_no,
      K = own_and_use_own_no_use_no
    ),
    mwvg08 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no
    ),
    mwvg09 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no
    ),
    mwvg10 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no
    ),
    mwvg11 = list(
      G = no_yes,
      H = own_and_use_own_no_use_no,
      I = own_and_use_own_no_use_no
    )
  ),

  value_labels_harmonized = list(
    mwvg01 = no_yes_no,
    mwvg02 = no_yes_no,
    mwvg03 = no_yes_no,
    mwvg04 = no_yes_no,
    mwvg05 = no_yes_no,
    mwvg06 = no_yes_no,
    mwvg07 = no_yes_no,
    mwvg08 = no_yes_no,
    mwvg09 = no_yes_no,
    mwvg10 = no_yes_no,
    mwvg11 = no_yes_no
  )
)
