## LASA filecode 014 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_014 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB"
    ),
    variable_name = c(
      "bfdoor",
      "bhindep",
      "bhoustyp",
      "blrooms",
      "bmomonth",
      "bmoyear",
      "bnrooms",
      "bospec1",
      "bospec2",
      "bospec3",
      "bospec4",
      "bospec5",
      "bospec6",
      "brfdoor",
      "bsatis",
      "bspec01",
      "bspec02",
      "bspec03",
      "bspec04",
      "bspec05",
      "bspec06",
      "bspec07",
      "bspec08",
      "bspec09",
      "bspec10",
      "bspec11",
      "bspec12",
      "bspec13",
      "bspec14",
      "bspec15",
      "bspec16",
      "bspec17",
      "bspecadj",
      "bhindep",
      "bhoustyp",
      "bhwhacc",
      "bmomonth",
      "bmoyear",
      "bsatis",
      "bspec1",
      "bspec2",
      "bspec3",
      "bspec4",
      "bspec5",
      "bspec6",
      "bspec7",
      "bspec8",
      "bspec9",
      "bspecadj",
      "bspecwho",
      "bfdoor",
      "bfdoorc",
      "bhindep",
      "bhousem",
      "bhoustyp",
      "blrooms",
      "bmomonth",
      "bmoved",
      "bmoyear",
      "bnrooms",
      "bnroomsc",
      "brfdoor",
      "bsatis",
      "bsatis01",
      "bsatis02",
      "bsatis03",
      "bsatis04",
      "bsatis05",
      "bsatis06",
      "bsatis07",
      "bsatis08",
      "bsatis09",
      "bspec01",
      "bspec02",
      "bspec03",
      "bspec04",
      "bspec05",
      "bspec06",
      "bspec07",
      "bspec08",
      "bspec09",
      "bspec10",
      "bspec11",
      "bspec12",
      "bspec13",
      "bspec14",
      "bspec15",
      "bspec16",
      "bspec17",
      "bspecadj",
      "cfdoor",
      "cfdoorc",
      "chindep",
      "chousem",
      "choustyp",
      "clrooms",
      "cmomonth",
      "cmoved",
      "cmoyear",
      "cnrooms",
      "cnroomsc",
      "crfdoor",
      "csatis",
      "cspec01",
      "cspec02",
      "cspec03",
      "cspec04",
      "cspec05",
      "cspec06",
      "cspec07",
      "cspec08",
      "cspec09",
      "cspec10",
      "cspec11",
      "cspec12",
      "cspec13",
      "cspec14",
      "cspec15",
      "cspec16",
      "cspec17",
      "cspecadj",
      "dfdoor",
      "dfdoorc",
      "dhindep",
      "dhousem",
      "dhoustyp",
      "dlrooms",
      "dmomonth",
      "dmoved",
      "dmoyear",
      "dnrooms",
      "dnroomsc",
      "drfdoor",
      "dsatis",
      "dspec01",
      "dspec02",
      "dspec03",
      "dspec04",
      "dspec05",
      "dspec06",
      "dspec07",
      "dspec08",
      "dspec09",
      "dspec10",
      "dspec11",
      "dspec12",
      "dspec13",
      "dspec14",
      "dspec15",
      "dspec16",
      "dspec17",
      "dspecadj",
      "efdoor",
      "efdoorc",
      "ehindep",
      "ehousem",
      "ehoustyp",
      "elrooms",
      "emomonth",
      "emoved",
      "emoyear",
      "enrooms",
      "enroomsc",
      "erfdoor",
      "esatis",
      "espec01",
      "espec02",
      "espec03",
      "espec04",
      "espec05",
      "espec06",
      "espec07",
      "espec08",
      "espec09",
      "espec10",
      "espec11",
      "espec12",
      "espec13",
      "espec14",
      "espec15",
      "espec16",
      "espec17",
      "especadj",
      "ffdoor",
      "ffdoorc",
      "fhindep",
      "fhousem",
      "fhoustyp",
      "flrooms",
      "fmomonth",
      "fmoved",
      "fmoyear",
      "fnrooms",
      "fnroomsc",
      "frfdoor",
      "fsatis",
      "fspec01",
      "fspec02",
      "fspec03",
      "fspec04",
      "fspec05",
      "fspec06",
      "fspec07",
      "fspec08",
      "fspec09",
      "fspec10",
      "fspec11",
      "fspec12",
      "fspec13",
      "fspec14",
      "fspec15",
      "fspec16",
      "fspec17",
      "fspecadj",
      "gfdoor",
      "gfdoorc",
      "ghindep",
      "ghousem",
      "ghoustyp",
      "glrooms",
      "gmomonth",
      "gmoved",
      "gmoyear",
      "gnrooms",
      "gnroomsc",
      "grfdoor",
      "gsatis",
      "gspec01",
      "gspec02",
      "gspec03",
      "gspec04",
      "gspec05",
      "gspec06",
      "gspec07",
      "gspec08",
      "gspec09",
      "gspec10",
      "gspec11",
      "gspec12",
      "gspec13",
      "gspec14",
      "gspec15",
      "gspec16",
      "gspec17",
      "gspecadj",
      "hhindep",
      "hhousem",
      "hhoustyp",
      "hhwhacc",
      "hlrooms",
      "hmomonth",
      "hmoved",
      "hmoyear",
      "hnrooms",
      "hnroomsc",
      "hsatis",
      "hspec1",
      "hspec2",
      "hspec3",
      "hspec4",
      "hspec5",
      "hspec6",
      "hspec7",
      "hspec8",
      "hspec9",
      "hspecadj",
      "hspecwho",
      "ihindep",
      "ihousem",
      "ihoustyp",
      "ihwhacc",
      "ilrooms",
      "imomonth",
      "imoved",
      "imoyear",
      "inrooms",
      "isatis",
      "ispec1",
      "ispec2",
      "ispec3",
      "ispec4",
      "ispec5",
      "ispec6",
      "ispec7",
      "ispec8",
      "ispec9",
      "ispecadj",
      "ispecwho",
      "jhindep",
      "jhousem",
      "jhoustyp",
      "jhwhacc",
      "jmomonth",
      "jmoved",
      "jmoyear",
      "jsatis",
      "jspec1",
      "jspec2",
      "jspec3",
      "jspec4",
      "jspec5",
      "jspec6",
      "jspec7",
      "jspec8",
      "jspec9",
      "jspecadj",
      "jspecwho",
      "khindep",
      "khousem",
      "khoustyp",
      "khwhacc",
      "kmomonth",
      "kmoved",
      "kmoyear",
      "ksatis",
      "kspec1",
      "kspec10",
      "kspec2",
      "kspec3",
      "kspec4",
      "kspec5",
      "kspec6",
      "kspec7",
      "kspec8",
      "kspec9",
      "kspecadj",
      "kspecwho",
      "bhindep"
    ),
    canonical_name = c(
      "fdoor",
      "hindep",
      "houstyp",
      "lrooms",
      "momonth",
      "moyear",
      "nrooms",
      "ospec1",
      "ospec2",
      "ospec3",
      "ospec4",
      "ospec5",
      "ospec6",
      "rfdoor",
      "satis",
      "spec01",
      "spec02",
      "spec03",
      "spec04",
      "spec05",
      "spec06",
      "spec07",
      "spec08",
      "spec09",
      "spec10",
      "spec11",
      "spec12",
      "spec13",
      "spec14",
      "spec15",
      "spec16",
      "spec17",
      "specadj",
      "hindep",
      "houstyp",
      "hwhacc",
      "momonth",
      "moyear",
      "satis",
      "spec1",
      "spec2",
      "spec3",
      "spec4",
      "spec5",
      "spec6",
      "spec7",
      "spec8",
      "spec9",
      "specadj",
      "specwho",
      "fdoor",
      "fdoorc",
      "hindep",
      "housem",
      "houstyp",
      "lrooms",
      "momonth",
      "moved",
      "moyear",
      "nrooms",
      "nroomsc",
      "rfdoor",
      "satis",
      "satis01",
      "satis02",
      "satis03",
      "satis04",
      "satis05",
      "satis06",
      "satis07",
      "satis08",
      "satis09",
      "spec01",
      "spec02",
      "spec03",
      "spec04",
      "spec05",
      "spec06",
      "spec07",
      "spec08",
      "spec09",
      "spec10",
      "spec11",
      "spec12",
      "spec13",
      "spec14",
      "spec15",
      "spec16",
      "spec17",
      "specadj",
      "fdoor",
      "fdoorc",
      "hindep",
      "housem",
      "houstyp",
      "lrooms",
      "momonth",
      "moved",
      "moyear",
      "nrooms",
      "nroomsc",
      "rfdoor",
      "satis",
      "spec01",
      "spec02",
      "spec03",
      "spec04",
      "spec05",
      "spec06",
      "spec07",
      "spec08",
      "spec09",
      "spec10",
      "spec11",
      "spec12",
      "spec13",
      "spec14",
      "spec15",
      "spec16",
      "spec17",
      "specadj",
      "fdoor",
      "fdoorc",
      "hindep",
      "housem",
      "houstyp",
      "lrooms",
      "momonth",
      "moved",
      "moyear",
      "nrooms",
      "nroomsc",
      "rfdoor",
      "satis",
      "spec01",
      "spec02",
      "spec03",
      "spec04",
      "spec05",
      "spec06",
      "spec07",
      "spec08",
      "spec09",
      "spec10",
      "spec11",
      "spec12",
      "spec13",
      "spec14",
      "spec15",
      "spec16",
      "spec17",
      "specadj",
      "fdoor",
      "fdoorc",
      "hindep",
      "housem",
      "houstyp",
      "lrooms",
      "momonth",
      "moved",
      "moyear",
      "nrooms",
      "nroomsc",
      "rfdoor",
      "satis",
      "spec01",
      "spec02",
      "spec03",
      "spec04",
      "spec05",
      "spec06",
      "spec07",
      "spec08",
      "spec09",
      "spec10",
      "spec11",
      "spec12",
      "spec13",
      "spec14",
      "spec15",
      "spec16",
      "spec17",
      "specadj",
      "fdoor",
      "fdoorc",
      "hindep",
      "housem",
      "houstyp",
      "lrooms",
      "momonth",
      "moved",
      "moyear",
      "nrooms",
      "nroomsc",
      "rfdoor",
      "satis",
      "spec01",
      "spec02",
      "spec03",
      "spec04",
      "spec05",
      "spec06",
      "spec07",
      "spec08",
      "spec09",
      "spec10",
      "spec11",
      "spec12",
      "spec13",
      "spec14",
      "spec15",
      "spec16",
      "spec17",
      "specadj",
      "fdoor",
      "fdoorc",
      "hindep",
      "housem",
      "houstyp",
      "lrooms",
      "momonth",
      "moved",
      "moyear",
      "nrooms",
      "nroomsc",
      "rfdoor",
      "satis",
      "spec01",
      "spec02",
      "spec03",
      "spec04",
      "spec05",
      "spec06",
      "spec07",
      "spec08",
      "spec09",
      "spec10",
      "spec11",
      "spec12",
      "spec13",
      "spec14",
      "spec15",
      "spec16",
      "spec17",
      "specadj",
      "hindep",
      "housem",
      "houstyp",
      "hwhacc",
      "lrooms",
      "momonth",
      "moved",
      "moyear",
      "nrooms",
      "nroomsc",
      "satis",
      "spec1",
      "spec2",
      "spec3",
      "spec4",
      "spec5",
      "spec6",
      "spec7",
      "spec8",
      "spec9",
      "specadj",
      "specwho",
      "hindep",
      "housem",
      "houstyp",
      "hwhacc",
      "lrooms",
      "momonth",
      "moved",
      "moyear",
      "nrooms",
      "satis",
      "spec1",
      "spec2",
      "spec3",
      "spec4",
      "spec5",
      "spec6",
      "spec7",
      "spec8",
      "spec9",
      "specadj",
      "specwho",
      "hindep",
      "housem",
      "houstyp",
      "hwhacc",
      "momonth",
      "moved",
      "moyear",
      "satis",
      "spec1",
      "spec2",
      "spec3",
      "spec4",
      "spec5",
      "spec6",
      "spec7",
      "spec8",
      "spec9",
      "specadj",
      "specwho",
      "hindep",
      "housem",
      "houstyp",
      "hwhacc",
      "momonth",
      "moved",
      "moyear",
      "satis",
      "spec1",
      "spec10",
      "spec2",
      "spec3",
      "spec4",
      "spec5",
      "spec6",
      "spec7",
      "spec8",
      "spec9",
      "specadj",
      "specwho",
      "hindep"
    ),
    variable_label = c(
      "Floor of front door",
      "OBSERVATION: type of housing",
      "Type of housing",
      "All rooms on the same floor",
      "Moved to current residence: month",
      "Moved to current residence: year",
      "Number of rooms in house",
      "Other special adjustments: for wheel chair users",
      "Other special adjustments: for deaf people",
      "Other special adjustments: faucets",
      "Other special adjustments: chair lift",
      "Other special adjustments:chairs",
      "Other special adjustments: other, documented",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Specially adjusted: non-skid in bathroom",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "OBSERVATION: type of housing",
      "Type of housing",
      "House accessible by wheelchair",
      "Moved to current residence: month",
      "Moved to current residence: year",
      "How (dis)satisfied with housing condition",
      "Spec. adjust: lowered or no doorstep",
      "Spec. adjust: adjusted toilet, supports, handgrips",
      "Spec. adjust: non-skid in bathroom, seating equip",
      "Spec. adjust: bedroom on same floor",
      "Spec. adjust: sloping ramp to pavement",
      "Spec. adjust: adjusted sink cupboards kitchen",
      "Spec. adjust: fall alarm",
      "Spec. adjust: stair elevator",
      "Spec. adjust: other",
      "House has special adjustments/adaptation",
      "Spec. adjust: for who",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing: constructed",
      "All rooms on the same floor",
      "Moved since last interview: month",
      "Moved since last interview",
      "Moved since last interview: year",
      "# rooms in house",
      "# rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Dissatisfied: House is too big",
      "Dissatisfied: House is too small",
      "Dissatisfied: House is in bad condition",
      "Dissatisfied: Rooms in house not on the same floor",
      "Dissatisfied: House can only be reached by stairs",
      "Dissatisfied: Doorsteps in house too high",
      "Dissatisfied: House is too expensive",
      "Dissatisfied: House is vulnerable to burglar",
      "Dissatisfied: other reason",
      "Specially adjusted: telephone e.g. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Specially adjusted: non-skid in bathroom",
      "Specially adjusted: seating equipment in bathroom",
      "spec. adjust: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing: constructed",
      "All rooms on the same floor",
      "Moved since last int: month",
      "Moved since last interview",
      "Moved since last int: year",
      "# rooms in house",
      "# rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Specially adjusted: non-skid in bathroom",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing: constructed",
      "All rooms on the same floor",
      "Moved since last int: month",
      "Moved since last interview",
      "Moved since last int: year",
      "# rooms in house",
      "# rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Specially adjusted: non-skid in bathroom",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing: constructed",
      "All rooms on the same floor",
      "Moved since last int: month",
      "Moved since last interview",
      "Moved since last int: year",
      "# rooms in house",
      "# rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Specially adjusted: non-skid in bathroom",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing: constructed",
      "All rooms on the same floor",
      "Moved since last int: month",
      "Moved since last interview",
      "Moved since last int: year",
      "# rooms in house",
      "# rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Specially adjusted: non-skid in bathroom",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing: constructed",
      "All rooms on the same floor",
      "Moved since last int: month",
      "Moved since last interview",
      "Moved since last int: year",
      "# rooms in house",
      "# rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Specially adjusted: non-skid in bathroom",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing: constructed",
      "House accessible by wheelchair",
      "All rooms on the same floor",
      "Moved since last int: month",
      "Moved since last interview",
      "Moved since last int: year",
      "# rooms in house",
      "# rooms: constructed",
      "How (dis)satisfied with housing condition",
      "Spec. adjust: lowered or no doorstep",
      "Spec. adjust: adjusted toilet, supports, handgrips",
      "Spec. adjust: non-skid in bathroom, seating equip",
      "Spec. adjust: bedroom on same floor",
      "Spec. adjust: sloping ramp to pavement",
      "Spec. adjust: adjusted sink cupboards kitchen",
      "Spec. adjust: fall alarm",
      "Spec. adjust: stair elevator",
      "Spec. adjust: other",
      "House has special adjustments/adaptation",
      "Spec. adjust: for who",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing: constructed",
      "House accessible by wheelchair",
      "All rooms on the same floor",
      "Moved since last int: month",
      "Moved since last interview",
      "Moved since last int: year",
      "# rooms in house",
      "How (dis)satisfied with housing condition",
      "Spec. adjust: lowered or no doorstep",
      "Spec. adjust: adjusted toilet, supports, handgrips",
      "Spec. adjust: non-skid in bathroom, seating equipment",
      "Spec. adjust: bedroom on same floor",
      "Spec. adjust: sloping ramp to pavement",
      "Spec. adjust: adjusted sink cupboards kitchen",
      "Spec. adjust: fall alarm",
      "Spec. adjust: stair elevator",
      "Spec. adjust: other",
      "House has special adjustments / adaptation",
      "Spec. adjust: for who",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing: constructed",
      "House accessible by wheelchair",
      "Moved since last int: month",
      "Moved since last interview",
      "Moved since last int: year",
      "How (dis)satisfied with housing condition",
      "Spec. adjust: lowered or no doorstep",
      "Spec. adjust: adjusted toilet, supports, handgrips",
      "Spec. adjust: non-skid in bathroom, seating equipment",
      "Spec. adjust: bedroom on same floor",
      "Spec. adjust: sloping ramp to pavement",
      "Spec. adjust: adjusted sink cupboards kitchen",
      "Spec. adjust: fall alarm",
      "Spec. adjust: stair elevator",
      "Spec. adjust: other",
      "House has special adjustments / adaptation",
      "Spec. adjust: for who",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing: constructed",
      "House accessible by wheelchair",
      "Moved since last int: month",
      "Moved since last interview",
      "Moved since last int: year",
      "How (dis)satisfied with housing condition",
      "Spec. adjust: lowered or no doorstep",
      "Spec. adjust: other",
      "Spec. adjust: adjusted toilet, supports, handgrips",
      "Spec. adjust: non-skid in bathroom, seating equipment",
      "Spec. adjust: bedroom on same floor",
      "Spec. adjust: sloping ramp to pavement",
      "Spec. adjust: adjusted sink cupboards kitchen",
      "Spec. adjust: fall alarm",
      "Spec. adjust: stair elevator",
      "Spec. adjust: sensors to monitor movement",
      "House has special adjustments / adaptation",
      "Spec. adjust: for who",
      "OBSERVATION: type of housing"
    ),
    harmonized_var_label = c(
      "Floor of front door",
      "OBSERVATION: type of housing",
      "Type of housing",
      "All rooms on the same floor",
      "Month moved to current residence",
      "Year moved to current residence",
      "Number of rooms in house",
      "Other special adjustments: for wheel chair users",
      "Other special adjustments: for deaf people",
      "Other special adjustments: faucets",
      "Other special adjustments: chair lift",
      "Other special adjustments:chairs",
      "Other special adjustments: other, documented",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Special housing adjustment",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "OBSERVATION: type of housing",
      "Type of housing",
      "House accessible by wheelchair",
      "Month moved to current residence",
      "Year moved to current residence",
      "How (dis)satisfied with housing condition",
      "Special adjustment: lowered or no doorstep",
      "Special adjustment: adjusted toilet, supports, handgrips",
      "Special adjustment: non-skid in bathroom, seating equipment",
      "Special adjustment: bedroom on same floor",
      "Special adjustment: sloping ramp to pavement",
      "Special adjustment: adjusted sink cupboards kitchen",
      "Special adjustment: fall alarm",
      "Special adjustment: stair elevator",
      "Special housing adjustment",
      "House has special adjustments/adaptation",
      "Special adjustment: for who",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing",
      "All rooms on the same floor",
      "Month moved to current residence",
      "Moved since last interview",
      "Year moved to current residence",
      "Number of rooms in house",
      "Number of rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Dissatisfied: House is too big",
      "Dissatisfied: House is too small",
      "Dissatisfied: House is in bad condition",
      "Dissatisfied: Rooms in house not on the same floor",
      "Dissatisfied: House can only be reached by stairs",
      "Dissatisfied: Doorsteps in house too high",
      "Dissatisfied: House is too expensive",
      "Dissatisfied: House is vulnerable to burglar",
      "Dissatisfied: other reason",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Special housing adjustment",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing",
      "All rooms on the same floor",
      "Month moved to current residence",
      "Moved since last interview",
      "Year moved to current residence",
      "Number of rooms in house",
      "Number of rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Special housing adjustment",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing",
      "All rooms on the same floor",
      "Month moved to current residence",
      "Moved since last interview",
      "Year moved to current residence",
      "Number of rooms in house",
      "Number of rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Special housing adjustment",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing",
      "All rooms on the same floor",
      "Month moved to current residence",
      "Moved since last interview",
      "Year moved to current residence",
      "Number of rooms in house",
      "Number of rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Special housing adjustment",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing",
      "All rooms on the same floor",
      "Month moved to current residence",
      "Moved since last interview",
      "Year moved to current residence",
      "Number of rooms in house",
      "Number of rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Special housing adjustment",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "Floor of front door",
      "Floor of front door: constructed",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing",
      "All rooms on the same floor",
      "Month moved to current residence",
      "Moved since last interview",
      "Year moved to current residence",
      "Number of rooms in house",
      "Number of rooms: constructed",
      "How to reach front door",
      "How (dis)satisfied with housing condition",
      "Specially adjusted: telephone eg. amplified sound",
      "Specially adjusted: lowered doorstep",
      "Specially adjusted: alarm system",
      "Specially adjusted: handgrips/handrails or supports",
      "Specially adjusted: lowered/raised draining board",
      "Specially adjusted: stair elevator",
      "Specially adjusted: bedrooms same floor level",
      "Specially adjusted: adjusted or raised toilet",
      "Specially adjusted: lowered/raised washbasin",
      "Special housing adjustment",
      "Specially adjusted: seating equipment in bathroom",
      "Specially adjusted: raised bed",
      "Specially adjusted: handgrip above bed",
      "Specially adjusted: extra handrails inside the house",
      "Specially adjusted: extra handrails outside the house",
      "Specially adjusted: sloping ramp to pavement",
      "Specially adjusted: other",
      "House has special adjustments/adaptation",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing",
      "House accessible by wheelchair",
      "All rooms on the same floor",
      "Month moved to current residence",
      "Moved since last interview",
      "Year moved to current residence",
      "Number of rooms in house",
      "Number of rooms: constructed",
      "How (dis)satisfied with housing condition",
      "Special adjustment: lowered or no doorstep",
      "Special adjustment: adjusted toilet, supports, handgrips",
      "Special adjustment: non-skid in bathroom, seating equipment",
      "Special adjustment: bedroom on same floor",
      "Special adjustment: sloping ramp to pavement",
      "Special adjustment: adjusted sink cupboards kitchen",
      "Special adjustment: fall alarm",
      "Special adjustment: stair elevator",
      "Special housing adjustment",
      "House has special adjustments/adaptation",
      "Special adjustment: for who",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing",
      "House accessible by wheelchair",
      "All rooms on the same floor",
      "Month moved to current residence",
      "Moved since last interview",
      "Year moved to current residence",
      "Number of rooms in house",
      "How (dis)satisfied with housing condition",
      "Special adjustment: lowered or no doorstep",
      "Special adjustment: adjusted toilet, supports, handgrips",
      "Special adjustment: non-skid in bathroom, seating equipment",
      "Special adjustment: bedroom on same floor",
      "Special adjustment: sloping ramp to pavement",
      "Special adjustment: adjusted sink cupboards kitchen",
      "Special adjustment: fall alarm",
      "Special adjustment: stair elevator",
      "Special housing adjustment",
      "House has special adjustments/adaptation",
      "Special adjustment: for who",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing",
      "House accessible by wheelchair",
      "Month moved to current residence",
      "Moved since last interview",
      "Year moved to current residence",
      "How (dis)satisfied with housing condition",
      "Special adjustment: lowered or no doorstep",
      "Special adjustment: adjusted toilet, supports, handgrips",
      "Special adjustment: non-skid in bathroom, seating equipment",
      "Special adjustment: bedroom on same floor",
      "Special adjustment: sloping ramp to pavement",
      "Special adjustment: adjusted sink cupboards kitchen",
      "Special adjustment: fall alarm",
      "Special adjustment: stair elevator",
      "Special housing adjustment",
      "House has special adjustments/adaptation",
      "Special adjustment: for who",
      "OBSERVATION: type of housing",
      "Type of housing: moved since last interview",
      "Type of housing",
      "House accessible by wheelchair",
      "Month moved to current residence",
      "Moved since last interview",
      "Year moved to current residence",
      "How (dis)satisfied with housing condition",
      "Special adjustment: lowered or no doorstep",
      "Special housing adjustment",
      "Special adjustment: adjusted toilet, supports, handgrips",
      "Special adjustment: non-skid in bathroom, seating equipment",
      "Special adjustment: bedroom on same floor",
      "Special adjustment: sloping ramp to pavement",
      "Special adjustment: adjusted sink cupboards kitchen",
      "Special adjustment: fall alarm",
      "Special adjustment: stair elevator",
      "Special housing adjustment",
      "House has special adjustments/adaptation",
      "Special adjustment: for who",
      "OBSERVATION: type of housing"
    ),
    var_type = c(
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "date",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "date",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "categorical",
      "date",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "categorical",
      "date",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "categorical",
      "date",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "categorical",
      "date",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "categorical",
      "date",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "categorical",
      "date",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "categorical",
      "date",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "categorical",
      "date",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "categorical",
      "date",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "date",
      "categorical",
      "date",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    fdoor = list(
      `2B` = c(`-3` = "wrong skip", `-2` = "na, see BHINDEP", `-1` = "na, asked"),
      B = c(`-5` = "na, see BHINDEP", `-3` = "na, wrong skip", `-2` = "na, see BMOVED", `-1` = "na"),
      C = na_see_c_d_e_f_ghindep_na_wrong_skip,
      D = na_see_c_d_e_f_ghindep_na_wrong_skip,
      E = na_see_c_d_e_f_ghindep_na_wrong_skip,
      F = na_see_c_d_e_f_ghindep_na_wrong_skip,
      G = na_see_c_d_e_f_ghindep_na_wrong_skip
    ),
    hindep = list(
      `2B` = c(
        `-2` = "na, interview terminated",
        `-1` = "na, asked",
        `1` = "independent",
        `2` = "residential home",
        `3` = "nursing h- somatic",
        `4` = "nursing h-psych",
        `5` = "hospital",
        `6` = "psychiatric hospital",
        `8` = "monastery (added)"
      ),
      `3B` = c(
        `-3` = "na, wrong skip",
        `-1` = "na, asked",
        `1` = "independent",
        `2` = "residential home",
        `3` = "nursing h-somatic",
        `4` = "nursing h-psych",
        `5` = "hospital",
        `6` = "psychiatric hospital",
        `8` = "monastery"
      ),
      B = c(
        `1` = "independent",
        `2` = "residential home",
        `3` = "nursing h-somatic",
        `4` = "nursing h-psych",
        `5` = "hospital",
        `6` = "psychiatric hospital",
        `8` = "monastery (added)"
      ),
      C = independent_residential_home_nursing_h_somatic,
      D = independent_residential_home_nursing_h_somatic,
      E = independent_residential_home_nursing_h_somatic,
      F = independent_residential_home_nursing_h_somatic,
      G = independent_residential_home_nursing_h_somatic,
      H = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see HMOVED",
        `-1` = "na, asked",
        `1` = "independent",
        `2` = "residential home",
        `3` = "nursing h-somatic",
        `4` = "nursing h-psych",
        `5` = "hospital",
        `6` = "psychiatric hospital",
        `8` = "monastery"
      ),
      I = independent_residential_home_nursing_h_somatic_2,
      J = independent_residential_home_nursing_h_somatic_2,
      K = independent_residential_home_nursing_h_somatic_2,
      MB = c(
        `-3` = "na, wrong skip",
        `-1` = "na, asked",
        `1` = "independent",
        `2` = "residential home",
        `3` = "nursing h-somatic",
        `4` = "nursing h-psych",
        `5` = "hospital",
        `6` = "psychiatric hospital",
        `7` = "other"
      )
    ),
    houstyp = list(
      `2B` = c(
        `-2` = "na, see BHINDEP",
        `-1` = "unknown",
        `1` = "attached row",
        `2` = "semi-detached",
        `3` = "detached",
        `4` = "high rise (elevator)",
        `5` = "high rise (no elevator)",
        `6` = "low-level apt building",
        `7` = "ground floor apartment",
        `8` = "apt build elderly (elevator)",
        `9` = "home elderly (street level)",
        `10` = "service flat (home elderly)",
        `11` = "semi-independent",
        `12` = "farm",
        `13` = "houseboat",
        `14` = "commune",
        `15` = "other",
        `16` = "institution",
        `17` = "monastery"
      ),
      `3B` = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BHINDEP",
        `-1` = "unknown",
        `1` = "attached row or semi-detached",
        `2` = "detached",
        `3` = "high rise (elevator)",
        `4` = "high rise (no elevator)",
        `5` = "ground floor apartment",
        `6` = "apt build elderly (elevator)",
        `7` = "home elderly (street level)",
        `8` = "semi-independent",
        `9` = "farm / corporate housing",
        `10` = "houseboat",
        `11` = "housing with communal facilities",
        `12` = "other",
        `13` = "institution",
        `14` = "monastery"
      ),
      B = attached_row_semi_detached_detached_high_rise_elevator_2,
      C = attached_row_semi_detached_detached_high_rise_elevator_2,
      D = attached_row_semi_detached_detached_high_rise_elevator_2,
      E = attached_row_semi_detached_detached_high_rise_elevator_3,
      F = attached_row_semi_detached_detached_high_rise_elevator_3,
      G = attached_row_semi_detached_detached_high_rise_elevator_3,
      H = c(
        `-3` = "na, wrong skip",
        `-1` = "unknown",
        `1` = "attached row or semi-detached",
        `2` = "detached",
        `3` = "high rise (elevator)",
        `4` = "high rise (no elevator)",
        `5` = "ground floor apartment",
        `6` = "apt build elderly (elevator)",
        `7` = "home elderly (street level)",
        `8` = "semi-independent",
        `9` = "farm / corporate housing",
        `10` = "houseboat",
        `11` = "other",
        `12` = "institution",
        `13` = "monastery"
      ),
      I = attached_row_or_semi_detached_detached,
      J = attached_row_or_semi_detached_detached,
      K = attached_row_or_semi_detached_detached
    ),
    lrooms = list(
      `2B` = no_yes_182,
      B = c(
        `-5` = "na, see BHINDEP",
        `-4` = "na, short version",
        `-3` = "na, wrong skip",
        `-2` = "na, see BMOVED",
        `-1` = "na",
        `1` = "no",
        `2` = "yes"
      ),
      C = no_yes_111,
      D = no_yes_111,
      E = no_yes_111,
      F = no_yes_111,
      G = no_yes_111,
      H = c(
        `-5` = "na, see HHINDEP",
        `-3` = "na, wrong skip",
        `-2` = "na, see HMOVED",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes"
      ),
      I = c(
        `-5` = "na, see IHINDEP",
        `-3` = "na, wrong skip",
        `-2` = "na, see IMOVED",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes"
      )
    ),
    momonth = list(
      `2B` = na_wrong_skip_na_see_bhindep_na_asked,
      `3B` = na_wrong_skip_na_see_bhindep_na_asked,
      B = na_short_version_na_wrong_skip_na_see_bmoved_na_asked,
      C = na_wrong_skip_na_see_c_d_e_f_gmoved_na_asked,
      D = na_wrong_skip_na_see_c_d_e_f_gmoved_na_asked,
      E = na_wrong_skip_na_see_c_d_e_f_gmoved_na_asked,
      F = na_wrong_skip_na_see_c_d_e_f_gmoved_na_asked,
      G = na_wrong_skip_na_see_c_d_e_f_gmoved_na_asked,
      H = na_wrong_skip_na_see_hmoved_na_asked,
      I = na_wrong_skip_na_see_i_j_kmoved_na_asked,
      J = na_wrong_skip_na_see_i_j_kmoved_na_asked,
      K = na_wrong_skip_na_see_i_j_kmoved_na_asked
    ),
    moyear = list(
      `2B` = na_wrong_skip_na_see_bhindep_na_asked,
      `3B` = na_wrong_skip_na_see_bhindep_na_asked,
      B = na_short_version_na_wrong_skip_na_see_bmoved_na_asked,
      C = na_wrong_skip_na_see_c_d_e_f_gmoved_na_asked,
      D = na_wrong_skip_na_see_c_d_e_f_gmoved_na_asked,
      E = na_wrong_skip_na_see_c_d_e_f_gmoved_na_asked,
      F = na_wrong_skip_na_see_c_d_e_f_gmoved_na_asked,
      G = na_wrong_skip_na_see_c_d_e_f_gmoved_na_asked,
      H = na_wrong_skip_na_see_hmoved_na_asked,
      I = na_wrong_skip_na_see_i_j_kmoved_na_asked,
      J = na_wrong_skip_na_see_i_j_kmoved_na_asked,
      K = na_wrong_skip_na_see_i_j_kmoved_na_asked
    ),
    nrooms = list(
      `2B` = na_wrong_skip_na_see_bhindep_na_asked,
      B = c(
        `-5` = "na, see BHINDEP",
        `-4` = "na, short version",
        `-3` = "na, wrong skip",
        `-2` = "na, see BMOVED",
        `-1` = "na"
      ),
      C = na_see_c_d_e_f_ghindep_na_wrong_skip,
      D = na_see_c_d_e_f_ghindep_na_wrong_skip,
      E = na_see_c_d_e_f_ghindep_na_wrong_skip,
      F = na_see_c_d_e_f_ghindep_na_wrong_skip,
      G = na_see_c_d_e_f_ghindep_na_wrong_skip,
      H = c(
        `-5` = "na, see HHINDEP",
        `-3` = "na, wrong skip",
        `-2` = "na, see HMOVED",
        `-1` = "na, asked"
      ),
      I = c(
        `-5` = "na, see IHINDEP",
        `-3` = "na, wrong skip",
        `-2` = "na, see IMOVED",
        `-1` = "na, asked"
      )
    ),
    ospec1 = list(
      `2B` = no_yes_84
    ),
    ospec2 = list(
      `2B` = no_yes_84
    ),
    ospec3 = list(
      `2B` = no_yes_84
    ),
    ospec4 = list(
      `2B` = no_yes_84
    ),
    ospec5 = list(
      `2B` = no_yes_84
    ),
    ospec6 = list(
      `2B` = no_yes_84
    ),
    rfdoor = list(
      `2B` = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BFDOOR",
        `-1` = "na, asked",
        `1` = "only stairs",
        `2` = "elevator present",
        `3` = "other"
      ),
      B = c(
        `-4` = "na, short version",
        `-2` = "na, see BFDOOR",
        `-1` = "na",
        `1` = "only stairs",
        `2` = "elevator present",
        `3` = "other"
      ),
      C = only_stairs_elevator_present_other,
      D = only_stairs_elevator_present_other,
      E = only_stairs_elevator_present_other,
      F = only_stairs_elevator_present_other,
      G = only_stairs_elevator_present_other
    ),
    satis = list(
      `2B` = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BHINDEP",
        `-1` = "na, asked",
        `1` = "dissatisfied",
        `2` = "not satisfied/dissatisfied",
        `3` = "satisfied"
      ),
      `3B` = c(
        `-3` = "na, wrong skip",
        `-1` = "na, asked",
        `1` = "dissatisfied",
        `2` = "not satisfied/dissatisfied",
        `3` = "satisfied"
      ),
      B = c(
        `-4` = "na, short version",
        `-3` = "wrong skip",
        `-2` = "na, routing",
        `-1` = "na, asked",
        `1` = "dissatisfied",
        `2` = "no satisfied/dissatisfy",
        `3` = "satisfied"
      ),
      C = dissatisfied_not_satisfied_dissatisfied_satisfied,
      D = dissatisfied_not_satisfied_dissatisfied_satisfied,
      E = dissatisfied_not_satisfied_dissatisfied_satisfied,
      F = dissatisfied_not_satisfied_dissatisfied_satisfied,
      G = dissatisfied_not_satisfied_dissatisfied_satisfied,
      H = dissatisfied_not_satisfied_dissatisfied_satisfied,
      I = dissatisfied_not_satisfied_dissatisfied_satisfied,
      J = dissatisfied_not_satisfied_dissatisfied_satisfied,
      K = dissatisfied_not_satisfied_dissatisfied_satisfied
    ),
    spec01 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    spec02 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    spec03 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    spec04 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    spec05 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    spec06 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_190,
      C = not_mentioned_mentioned_60,
      D = not_mentioned_mentioned_60,
      E = not_mentioned_mentioned_60,
      F = not_mentioned_mentioned_60,
      G = not_mentioned_mentioned_60
    ),
    spec07 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_190,
      C = not_mentioned_mentioned_60,
      D = not_mentioned_mentioned_60,
      E = not_mentioned_mentioned_60,
      F = not_mentioned_mentioned_60,
      G = not_mentioned_mentioned_60
    ),
    spec08 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    spec09 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    spec10 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9,
      K = not_mentioned_mentioned_277
    ),
    spec11 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    spec12 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    spec13 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    spec14 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_190,
      C = not_mentioned_mentioned_60,
      D = not_mentioned_mentioned_60,
      E = not_mentioned_mentioned_60,
      F = not_mentioned_mentioned_60,
      G = not_mentioned_mentioned_60
    ),
    spec15 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_190,
      C = not_mentioned_mentioned_60,
      D = not_mentioned_mentioned_60,
      E = not_mentioned_mentioned_60,
      F = not_mentioned_mentioned_60,
      G = not_mentioned_mentioned_60
    ),
    spec16 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_190,
      C = not_mentioned_mentioned_60,
      D = not_mentioned_mentioned_60,
      E = not_mentioned_mentioned_60,
      F = not_mentioned_mentioned_60,
      G = not_mentioned_mentioned_60
    ),
    spec17 = list(
      `2B` = not_mentioned_mentioned_91,
      B = not_mentioned_mentioned_86,
      C = not_mentioned_mentioned_9,
      D = not_mentioned_mentioned_9,
      E = not_mentioned_mentioned_9,
      F = not_mentioned_mentioned_9,
      G = not_mentioned_mentioned_9
    ),
    specadj = list(
      `2B` = no_yes_182,
      `3B` = no_yes_182,
      B = c(`-3` = "na, wrong skip", `-1` = "na, asked", `0` = "no", `1` = "yes"),
      C = no_yes_112,
      D = no_yes_112,
      E = no_yes_112,
      F = no_yes_112,
      G = no_yes_112,
      H = c(`-3` = "na, wrong skip", `-2` = "na, see HMOVED", `-1` = "na, asked", `1` = "no", `2` = "yes"),
      I = no_yes_183,
      J = no_yes_183,
      K = no_yes_183
    ),
    hwhacc = list(
      `3B` = c(
        `-5` = "na, see BHINDEP",
        `-3` = "na, wrong skip",
        `-2` = "na, see BHINDEP",
        `-1` = "na, asked",
        `1` = "yes",
        `2` = "only with help",
        `3` = "no"
      ),
      H = c(
        `-5` = "na, see HHINDEP",
        `-2` = "na, see HMOVED",
        `-1` = "na, asked",
        `1` = "yes",
        `2` = "only with help",
        `3` = "no"
      ),
      I = yes_only_with_help_no,
      J = yes_only_with_help_no,
      K = yes_only_with_help_no
    ),
    spec1 = list(
      `3B` = not_mentioned_mentioned_86,
      H = not_mentioned_mentioned_222,
      I = not_mentioned_mentioned_96,
      J = not_mentioned_mentioned_96,
      K = not_mentioned_mentioned_96
    ),
    spec2 = list(
      `3B` = not_mentioned_mentioned_86,
      H = not_mentioned_mentioned_222,
      I = not_mentioned_mentioned_96,
      J = not_mentioned_mentioned_96,
      K = not_mentioned_mentioned_96
    ),
    spec3 = list(
      `3B` = not_mentioned_mentioned_86,
      H = not_mentioned_mentioned_222,
      I = not_mentioned_mentioned_96,
      J = not_mentioned_mentioned_96,
      K = not_mentioned_mentioned_96
    ),
    spec4 = list(
      `3B` = not_mentioned_mentioned_190,
      H = not_mentioned_mentioned_247,
      I = not_mentioned_mentioned_174,
      J = not_mentioned_mentioned_174,
      K = not_mentioned_mentioned_174
    ),
    spec5 = list(
      `3B` = not_mentioned_mentioned_190,
      H = not_mentioned_mentioned_247,
      I = not_mentioned_mentioned_174,
      J = not_mentioned_mentioned_174,
      K = not_mentioned_mentioned_174
    ),
    spec6 = list(
      `3B` = not_mentioned_mentioned_86,
      H = not_mentioned_mentioned_222,
      I = not_mentioned_mentioned_96,
      J = not_mentioned_mentioned_96,
      K = not_mentioned_mentioned_96
    ),
    spec7 = list(
      `3B` = not_mentioned_mentioned_86,
      H = not_mentioned_mentioned_247,
      I = not_mentioned_mentioned_96,
      J = not_mentioned_mentioned_96,
      K = not_mentioned_mentioned_96
    ),
    spec8 = list(
      `3B` = not_mentioned_mentioned_190,
      H = not_mentioned_mentioned_247,
      I = not_mentioned_mentioned_174,
      J = not_mentioned_mentioned_174,
      K = not_mentioned_mentioned_174
    ),
    spec9 = list(
      `3B` = not_mentioned_mentioned_86,
      H = not_mentioned_mentioned_222,
      I = not_mentioned_mentioned_278,
      J = not_mentioned_mentioned_278,
      K = not_mentioned_mentioned_277
    ),
    specwho = list(
      `3B` = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BSPECADJ",
        `-1` = "na, asked",
        `1` = "for respondent",
        `2` = "for (former) inmate",
        `3` = "for both",
        `4` = "for none, already present"
      ),
      H = c(
        `-2` = "na, see HSPECADJ",
        `-1` = "na, asked",
        `1` = "for respondent",
        `2` = "for (former) inmate",
        `3` = "for both",
        `4` = "for none, already present"
      ),
      I = for_respondent_for_former_inmate_for_both,
      J = for_respondent_for_former_inmate_for_both,
      K = for_respondent_for_former_inmate_for_both
    ),
    fdoorc = list(
      B = monastery_institution_unknown,
      C = monastery_institution_unknown,
      D = monastery_institution_unknown,
      E = monastery_institution_unknown,
      F = monastery_institution_unknown,
      G = monastery_institution_unknown
    ),
    housem = list(
      B = c(
        `-5` = "na, see BHINDEP",
        `-4` = "na, short version",
        `-3` = "na, wrong skip",
        `-2` = "na, see BMOVED",
        `-1` = "na, asked",
        `1` = "attached row",
        `2` = "semi-detached",
        `3` = "detached",
        `4` = "high rise (elevator)",
        `5` = "high rise (no elevator)",
        `6` = "low-level apt building",
        `7` = "ground floor apartment",
        `8` = "apt build elderly (elevator)",
        `9` = "home elderly (street level)",
        `10` = "service flat (home elderly)",
        `11` = "semi-independent",
        `12` = "farm",
        `13` = "houseboat",
        `14` = "commune",
        `15` = "other"
      ),
      C = attached_row_semi_detached_detached_high_rise_elevator,
      D = attached_row_semi_detached_detached_high_rise_elevator,
      E = attached_row_semi_detached_detached_high_rise_elevator,
      F = attached_row_semi_detached_detached_high_rise_elevator,
      G = attached_row_semi_detached_detached_high_rise_elevator,
      H = c(
        `-5` = "na, see HHINDEP",
        `-3` = "na, wrong skip",
        `-2` = "na, see HMOVED",
        `-1` = "na, asked",
        `1` = "attached row or semi-detached",
        `2` = "detached",
        `3` = "high rise (elevator)",
        `4` = "high rise (no elevator)",
        `5` = "ground floor apartment",
        `6` = "apt build elderly (elevator)",
        `7` = "home elderly (street level)",
        `8` = "semi-independent",
        `9` = "farm / corporate housing",
        `10` = "houseboat",
        `11` = "other (documented)"
      ),
      I = attached_row_or_semi_detached_detached_2,
      J = attached_row_or_semi_detached_detached_2,
      K = attached_row_or_semi_detached_detached_2
    ),
    moved = list(
      B = c(`1` = "no", `2` = "yes"),
      C = no_yes,
      D = no_yes,
      E = no_yes,
      F = no_yes_yes_temporarily_living_elsewhere,
      G = no_yes_yes_temporarily_living_elsewhere,
      H = no_yes_yes_temporarily_living_elsewhere,
      I = no_yes_yes_temporarily_living_elsewhere,
      J = no_yes_yes_temporarily_living_elsewhere,
      K = no_yes_yes_temporarily_living_elsewhere
    ),
    nroomsc = list(
      B = monastery_institution_unknown,
      C = monastery_institution_unknown,
      D = monastery_institution_unknown,
      E = monastery_institution_unknown,
      F = monastery_institution_unknown,
      G = monastery_institution_unknown,
      H = monastery_institution_unknown
    ),
    satis01 = list(
      B = not_mentioned_mentioned_175
    ),
    satis02 = list(
      B = not_mentioned_mentioned_175
    ),
    satis03 = list(
      B = not_mentioned_mentioned_175
    ),
    satis04 = list(
      B = not_mentioned_mentioned_175
    ),
    satis05 = list(
      B = not_mentioned_mentioned_175
    ),
    satis06 = list(
      B = not_mentioned_mentioned_175
    ),
    satis07 = list(
      B = not_mentioned_mentioned_175
    ),
    satis08 = list(
      B = not_mentioned_mentioned_175
    ),
    satis09 = list(
      B = not_mentioned_mentioned_175
    )
  ),

  value_labels_harmonized = list(
    fdoor = c(
      `-5` = "not available, routing",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available"
    ),
    fdoorc = monastery_institution_unknown,
    hindep = c(
      `-3` = "not available, wrong skip",
      `-2` = "not available",
      `-1` = "not available, asked",
      `1` = "independent",
      `2` = "residential home",
      `3` = "nursing h-somatic",
      `4` = "nursing h-psych",
      `5` = "hospital",
      `6` = "psychiatric hospital",
      `7` = "other",
      `8` = "monastery"
    ),
    housem = c(
      `-5` = "not available, routing",
      `-4` = "not available, short version",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "housing type category 1",
      `2` = "housing type category 2",
      `3` = "housing type category 3",
      `4` = "housing type category 4",
      `5` = "housing type category 5",
      `6` = "housing type category 6",
      `7` = "housing type category 7",
      `8` = "housing type category 8",
      `9` = "housing type category 9",
      `10` = "housing type category 10",
      `11` = "housing type category 11",
      `12` = "housing type category 12",
      `13` = "houseboat",
      `14` = "commune",
      `15` = "other"
    ),
    houstyp = c(
      `-4` = "not available",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "unknown",
      `1` = "housing type category 1",
      `2` = "housing type category 2",
      `3` = "housing type category 3",
      `4` = "housing type category 4",
      `5` = "housing type category 5",
      `6` = "housing type category 6",
      `7` = "housing type category 7",
      `8` = "housing type category 8",
      `9` = "housing type category 9",
      `10` = "housing type category 10",
      `11` = "housing type category 11",
      `12` = "housing type category 12",
      `13` = "housing type category 13",
      `14` = "housing type category 14",
      `15` = "other",
      `16` = "institution",
      `17` = "monastery"
    ),
    hwhacc = c(
      `-5` = "not available, routing",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "yes",
      `2` = "only with help",
      `3` = "no"
    ),
    lrooms = c(
      `-5` = "not available, routing",
      `-4` = "not available, short version",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available",
      `1` = "no",
      `2` = "yes"
    ),
    momonth = not_available_short_version_not_available_wrong_skip,
    moved = c(
      `-1` = "not available, asked",
      `1` = "no",
      `2` = "yes",
      `3` = "yes, temporarily living elsewhere",
      `4` = "lived temporarily elsewhere"
    ),
    moyear = not_available_short_version_not_available_wrong_skip,
    nrooms = c(
      `-5` = "not available, routing",
      `-4` = "not available, short version",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available"
    ),
    nroomsc = monastery_institution_unknown,
    ospec1 = no_yes_85,
    ospec2 = no_yes_85,
    ospec3 = no_yes_85,
    ospec4 = no_yes_85,
    ospec5 = no_yes_85,
    ospec6 = no_yes_85,
    rfdoor = c(
      `-4` = "not available, short version",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available",
      `1` = "only stairs",
      `2` = "elevator present",
      `3` = "other"
    ),
    satis = c(
      `-4` = "not available, short version",
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "dissatisfied",
      `2` = "not satisfied/dissatisfied",
      `3` = "satisfied"
    ),
    satis01 = not_mentioned_mentioned_21,
    satis02 = not_mentioned_mentioned_21,
    satis03 = not_mentioned_mentioned_21,
    satis04 = not_mentioned_mentioned_21,
    satis05 = not_mentioned_mentioned_21,
    satis06 = not_mentioned_mentioned_21,
    satis07 = not_mentioned_mentioned_21,
    satis08 = not_mentioned_mentioned_21,
    satis09 = not_mentioned_mentioned_21,
    spec01 = not_mentioned_binary_category_1_mentioned,
    spec02 = not_mentioned_binary_category_1_mentioned,
    spec03 = not_mentioned_binary_category_1_mentioned,
    spec04 = not_mentioned_binary_category_1_mentioned,
    spec05 = not_mentioned_binary_category_1_mentioned,
    spec06 = not_mentioned_binary_category_1_mentioned_2,
    spec07 = not_mentioned_binary_category_1_mentioned_2,
    spec08 = not_mentioned_binary_category_1_mentioned,
    spec09 = not_mentioned_binary_category_1_mentioned,
    spec1 = not_mentioned_mentioned,
    spec10 = c(
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `0` = "not mentioned",
      `1` = "special housing adjustment category 1",
      `2` = "mentioned"
    ),
    spec11 = not_mentioned_binary_category_1_mentioned,
    spec12 = not_mentioned_binary_category_1_mentioned,
    spec13 = not_mentioned_binary_category_1_mentioned,
    spec14 = not_mentioned_binary_category_1_mentioned_2,
    spec15 = not_mentioned_binary_category_1_mentioned_2,
    spec16 = not_mentioned_binary_category_1_mentioned_2,
    spec17 = not_mentioned_binary_category_1_mentioned,
    spec2 = not_mentioned_mentioned,
    spec3 = not_mentioned_mentioned,
    spec4 = not_mentioned_mentioned_248,
    spec5 = not_mentioned_mentioned_248,
    spec6 = not_mentioned_mentioned,
    spec7 = not_mentioned_mentioned_248,
    spec8 = not_mentioned_mentioned_248,
    spec9 = not_mentioned_mentioned,
    specadj = c(
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `0` = "no",
      `1` = "binary category 1",
      `2` = "yes"
    ),
    specwho = c(
      `-3` = "not available, wrong skip",
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `1` = "for respondent",
      `2` = "for (former) inmate",
      `3` = "for both",
      `4` = "for none, already present"
    )
  )
)
