## LASA filecode 132 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_132 <- list(
  variables = data.frame(
    wave = c(
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J"
    ),
    variable_name = c(
      "dqfioe01",
      "dqfioe02",
      "dqfioe03",
      "dqfioe04",
      "dqfioe05",
      "dqfioe06",
      "dqfioe07",
      "dqfioe08",
      "dqfioe09",
      "dqfioe10",
      "dqfioe11",
      "dqfioe12",
      "dqfioe13",
      "dqfioe14",
      "dqfioe15",
      "dqfioe16",
      "eqfioe01",
      "eqfioe02",
      "eqfioe03",
      "eqfioe04",
      "eqfioe05",
      "eqfioe06",
      "eqfioe07",
      "eqfioe08",
      "eqfioe09",
      "eqfioe10",
      "eqfioe11",
      "eqfioe12",
      "eqfioe13",
      "eqfioe14",
      "eqfioe15",
      "eqfioe16",
      "jqfioe01",
      "jqfioe02",
      "jqfioe03",
      "jqfioe04",
      "jqfioe05",
      "jqfioe06",
      "jqfioe07",
      "jqfioe08",
      "jqfioe09",
      "jqfioe10",
      "jqfioe11",
      "jqfioe12",
      "jqfioe13",
      "jqfioe14",
      "jqfioe15",
      "jqfioe16"
    ),
    canonical_name = c(
      "qfioe01",
      "qfioe02",
      "qfioe03",
      "qfioe04",
      "qfioe05",
      "qfioe06",
      "qfioe07",
      "qfioe08",
      "qfioe09",
      "qfioe10",
      "qfioe11",
      "qfioe12",
      "qfioe13",
      "qfioe14",
      "qfioe15",
      "qfioe16",
      "qfioe01",
      "qfioe02",
      "qfioe03",
      "qfioe04",
      "qfioe05",
      "qfioe06",
      "qfioe07",
      "qfioe08",
      "qfioe09",
      "qfioe10",
      "qfioe11",
      "qfioe12",
      "qfioe13",
      "qfioe14",
      "qfioe15",
      "qfioe16",
      "qfioe01",
      "qfioe02",
      "qfioe03",
      "qfioe04",
      "qfioe05",
      "qfioe06",
      "qfioe07",
      "qfioe08",
      "qfioe09",
      "qfioe10",
      "qfioe11",
      "qfioe12",
      "qfioe13",
      "qfioe14",
      "qfioe15",
      "qfioe16"
    ),
    variable_label = c(
      "Fil Obl Exp 01: live",
      "Fil Obl Exp 02: sick",
      "Fil Obl Exp 03: financial",
      "Fil Obl Exp 04: visit",
      "Fil Obl Exp 05: phone",
      "Fil Obl Exp 06: responsible",
      "Fil Obl Exp 07: together",
      "Fil Obl Exp 08: personal",
      "Fil Obl Exp 09: support",
      "Fil Obl Exp 10: time",
      "Fil Obl Exp 11: need",
      "Fil Obl Exp 12: advise",
      "Fil Obl Exp 13: work",
      "Fil Obl Exp 14: check",
      "Fil Obl Exp 15: help",
      "Fil Obl Exp 16: care",
      "Fil Obl Exp 01: live",
      "Fil Obl Exp 02: sick",
      "Fil Obl Exp 03: financial",
      "Fil Obl Exp 04: visit",
      "Fil Obl Exp 05: phone",
      "Fil Obl Exp 06: responsible",
      "Fil Obl Exp 07: together",
      "Fil Obl Exp 08: personal",
      "Fil Obl Exp 09: support",
      "Fil Obl Exp 10: time",
      "Fil Obl Exp 11: need",
      "Fil Obl Exp 12: advise",
      "Fil Obl Exp 13: work",
      "Fil Obl Exp 14: check",
      "Fil Obl Exp 15: help",
      "Fil Obl Exp 16: care",
      "Fil Obl Exp 01: live",
      "Fil Obl Exp 02: sick",
      "Fil Obl Exp 03: financial",
      "Fil Obl Exp 04: visit",
      "Fil Obl Exp 05: phone",
      "Fil Obl Exp 06: responsible",
      "Fil Obl Exp 07: together",
      "Fil Obl Exp 08: personal",
      "Fil Obl Exp 09: support",
      "Fil Obl Exp 10: time",
      "Fil Obl Exp 11: need",
      "Fil Obl Exp 12: advise",
      "Fil Obl Exp 13: work",
      "Fil Obl Exp 14: check",
      "Fil Obl Exp 15: help",
      "Fil Obl Exp 16: care"
    ),
    harmonized_var_label = c(
      "Fil Obl Exp 01: live",
      "Fil Obl Exp 02: sick",
      "Fil Obl Exp 03: financial",
      "Fil Obl Exp 04: visit",
      "Fil Obl Exp 05: phone",
      "Fil Obl Exp 06: responsible",
      "Fil Obl Exp 07: together",
      "Fil Obl Exp 08: personal",
      "Fil Obl Exp 09: support",
      "Fil Obl Exp 10: time",
      "Fil Obl Exp 11: need",
      "Fil Obl Exp 12: advise",
      "Fil Obl Exp 13: work",
      "Fil Obl Exp 14: check",
      "Fil Obl Exp 15: help",
      "Fil Obl Exp 16: care",
      "Fil Obl Exp 01: live",
      "Fil Obl Exp 02: sick",
      "Fil Obl Exp 03: financial",
      "Fil Obl Exp 04: visit",
      "Fil Obl Exp 05: phone",
      "Fil Obl Exp 06: responsible",
      "Fil Obl Exp 07: together",
      "Fil Obl Exp 08: personal",
      "Fil Obl Exp 09: support",
      "Fil Obl Exp 10: time",
      "Fil Obl Exp 11: need",
      "Fil Obl Exp 12: advise",
      "Fil Obl Exp 13: work",
      "Fil Obl Exp 14: check",
      "Fil Obl Exp 15: help",
      "Fil Obl Exp 16: care",
      "Fil Obl Exp 01: live",
      "Fil Obl Exp 02: sick",
      "Fil Obl Exp 03: financial",
      "Fil Obl Exp 04: visit",
      "Fil Obl Exp 05: phone",
      "Fil Obl Exp 06: responsible",
      "Fil Obl Exp 07: together",
      "Fil Obl Exp 08: personal",
      "Fil Obl Exp 09: support",
      "Fil Obl Exp 10: time",
      "Fil Obl Exp 11: need",
      "Fil Obl Exp 12: advise",
      "Fil Obl Exp 13: work",
      "Fil Obl Exp 14: check",
      "Fil Obl Exp 15: help",
      "Fil Obl Exp 16: care"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    qfioe01 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe02 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe03 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe04 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe05 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe06 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe07 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe08 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe09 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe10 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe11 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe12 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe13 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe14 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe15 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    ),
    qfioe16 = list(
      D = strongly_disagree_disagree_no_agreement_disagreement,
      E = strongly_disagree_disagree_no_agreement_disagreement,
      J = strongly_disagree_disagree_no_agreement_disagreement
    )
  ),

  value_labels_harmonized = list(
    qfioe01 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe02 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe03 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe04 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe05 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe06 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe07 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe08 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe09 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe10 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe11 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe12 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe13 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe14 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe15 = strongly_disagree_disagree_no_agreement_disagreement_2,
    qfioe16 = strongly_disagree_disagree_no_agreement_disagreement_2
  )
)
