## LASA filecode 091 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_091 <- list(
  variables = data.frame(
    wave = c(
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E"
    ),
    variable_name = c(
      "dptsd01",
      "dptsd02",
      "dptsd03",
      "dptsd04",
      "dptsd05",
      "dptsd06",
      "dptsd07",
      "dptsd08",
      "dptsd09",
      "dptsd10",
      "dptsd11",
      "dptsd12",
      "dptsd13",
      "dptsd14",
      "dptsd15",
      "dptsd16",
      "dptsd17",
      "dptsd18",
      "dptsd19",
      "dptsd20",
      "dptsd21",
      "dptsd22",
      "dptsd23",
      "eptsd01",
      "eptsd02",
      "eptsd03",
      "eptsd04",
      "eptsd05",
      "eptsd06",
      "eptsd07",
      "eptsd08",
      "eptsd09",
      "eptsd10",
      "eptsd11",
      "eptsd12",
      "eptsd13",
      "eptsd14",
      "eptsd15",
      "eptsd16",
      "eptsd17",
      "eptsd18",
      "eptsd19",
      "eptsd20",
      "eptsd21",
      "eptsd22",
      "eptsd23"
    ),
    canonical_name = c(
      "ptsd01",
      "ptsd02",
      "ptsd03",
      "ptsd04",
      "ptsd05",
      "ptsd06",
      "ptsd07",
      "ptsd08",
      "ptsd09",
      "ptsd10",
      "ptsd11",
      "ptsd12",
      "ptsd13",
      "ptsd14",
      "ptsd15",
      "ptsd16",
      "ptsd17",
      "ptsd18",
      "ptsd19",
      "ptsd20",
      "ptsd21",
      "ptsd22",
      "ptsd23",
      "ptsd01",
      "ptsd02",
      "ptsd03",
      "ptsd04",
      "ptsd05",
      "ptsd06",
      "ptsd07",
      "ptsd08",
      "ptsd09",
      "ptsd10",
      "ptsd11",
      "ptsd12",
      "ptsd13",
      "ptsd14",
      "ptsd15",
      "ptsd16",
      "ptsd17",
      "ptsd18",
      "ptsd19",
      "ptsd20",
      "ptsd21",
      "ptsd22",
      "ptsd23"
    ),
    variable_label = c(
      "1. Last 4 weeks: express",
      "2. Last 4 weeks: avoid thoughts",
      "3. Last 4 weeks: no recall",
      "4. Last 4 weeks: irritable",
      "5. Last 4 weeks: body sensations",
      "6. Last 4 weeks: sleep through",
      "7. Last 4 weeks: dreams",
      "8. Last 4 weeks: decreased interest",
      "9. Last 4 weeks: repetitive memories",
      "10. Last 4 weeks: reoccurrences",
      "11. Last 4 weeks: no future",
      "12. Last 4 weeks: difficulty concentrating",
      "13. Last 4 weeks: jumpy",
      "14. Last 4 weeks: avoid feelings",
      "15. Last 4 weeks: avoid memories",
      "16. Last 4 weeks: anger",
      "17. Last 4 weeks: sleep in",
      "18. Last 4 weeks: past experiences",
      "19. Last 4 weeks: estranged",
      "20. Last 4 weeks: apprehensive",
      "21. Last 4 weeks: nasty memories",
      "22. Last 4 weeks: unconnected",
      "23. Last 4 weeks: daily activities",
      "1. Last 4 weeks: express",
      "2. Last 4 weeks: avoid thoughts",
      "3. Last 4 weeks: no recall",
      "4. Last 4 weeks: irritable",
      "5. Last 4 weeks: body sensations",
      "6. Last 4 weeks: sleep through",
      "7. Last 4 weeks: dreams",
      "8. Last 4 weeks: decreased interest",
      "9. Last 4 weeks: repetitive memories",
      "10. Last 4 weeks: reoccurrences",
      "11. Last 4 weeks: no future",
      "12. Last 4 weeks: difficulty concentrating",
      "13. Last 4 weeks: jumpy",
      "14. Last 4 weeks: avoid feelings",
      "15. Last 4 weeks: avoid memories",
      "16. Last 4 weeks: anger",
      "17. Last 4 weeks: sleep in",
      "18. Last 4 weeks: past experiences",
      "19. Last 4 weeks: estranged",
      "20. Last 4 weeks: apprehensive",
      "21. Last 4 weeks: nasty memories",
      "22. Last 4 weeks: unconnected",
      "23. Last 4 weeks: daily activities"
    ),
    harmonized_var_label = c(
      "1. Last 4 weeks: express",
      "2. Last 4 weeks: avoid thoughts",
      "3. Last 4 weeks: no recall",
      "4. Last 4 weeks: irritable",
      "5. Last 4 weeks: body sensations",
      "6. Last 4 weeks: sleep through",
      "7. Last 4 weeks: dreams",
      "8. Last 4 weeks: decreased interest",
      "9. Last 4 weeks: repetitive memories",
      "10. Last 4 weeks: reoccurrences",
      "11. Last 4 weeks: no future",
      "12. Last 4 weeks: difficulty concentrating",
      "13. Last 4 weeks: jumpy",
      "14. Last 4 weeks: avoid feelings",
      "15. Last 4 weeks: avoid memories",
      "16. Last 4 weeks: anger",
      "17. Last 4 weeks: sleep in",
      "18. Last 4 weeks: past experiences",
      "19. Last 4 weeks: estranged",
      "20. Last 4 weeks: apprehensive",
      "21. Last 4 weeks: nasty memories",
      "22. Last 4 weeks: unconnected",
      "23. Last 4 weeks: daily activities",
      "1. Last 4 weeks: express",
      "2. Last 4 weeks: avoid thoughts",
      "3. Last 4 weeks: no recall",
      "4. Last 4 weeks: irritable",
      "5. Last 4 weeks: body sensations",
      "6. Last 4 weeks: sleep through",
      "7. Last 4 weeks: dreams",
      "8. Last 4 weeks: decreased interest",
      "9. Last 4 weeks: repetitive memories",
      "10. Last 4 weeks: reoccurrences",
      "11. Last 4 weeks: no future",
      "12. Last 4 weeks: difficulty concentrating",
      "13. Last 4 weeks: jumpy",
      "14. Last 4 weeks: avoid feelings",
      "15. Last 4 weeks: avoid memories",
      "16. Last 4 weeks: anger",
      "17. Last 4 weeks: sleep in",
      "18. Last 4 weeks: past experiences",
      "19. Last 4 weeks: estranged",
      "20. Last 4 weeks: apprehensive",
      "21. Last 4 weeks: nasty memories",
      "22. Last 4 weeks: unconnected",
      "23. Last 4 weeks: daily activities"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    ptsd01 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd02 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd03 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd04 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd05 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd06 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd07 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd08 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd09 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd10 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd11 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd12 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd13 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd14 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd15 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd16 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd17 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd18 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd19 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd20 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd21 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd22 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    ),
    ptsd23 = list(
      D = not_at_all_somewhat_considerably_very_much,
      E = not_at_all_somewhat_considerably_very_much
    )
  ),

  value_labels_harmonized = list(
    ptsd01 = not_at_all_somewhat_considerably_very_much_2,
    ptsd02 = not_at_all_somewhat_considerably_very_much_2,
    ptsd03 = not_at_all_somewhat_considerably_very_much_2,
    ptsd04 = not_at_all_somewhat_considerably_very_much_2,
    ptsd05 = not_at_all_somewhat_considerably_very_much_2,
    ptsd06 = not_at_all_somewhat_considerably_very_much_2,
    ptsd07 = not_at_all_somewhat_considerably_very_much_2,
    ptsd08 = not_at_all_somewhat_considerably_very_much_2,
    ptsd09 = not_at_all_somewhat_considerably_very_much_2,
    ptsd10 = not_at_all_somewhat_considerably_very_much_2,
    ptsd11 = not_at_all_somewhat_considerably_very_much_2,
    ptsd12 = not_at_all_somewhat_considerably_very_much_2,
    ptsd13 = not_at_all_somewhat_considerably_very_much_2,
    ptsd14 = not_at_all_somewhat_considerably_very_much_2,
    ptsd15 = not_at_all_somewhat_considerably_very_much_2,
    ptsd16 = not_at_all_somewhat_considerably_very_much_2,
    ptsd17 = not_at_all_somewhat_considerably_very_much_2,
    ptsd18 = not_at_all_somewhat_considerably_very_much_2,
    ptsd19 = not_at_all_somewhat_considerably_very_much_2,
    ptsd20 = not_at_all_somewhat_considerably_very_much_2,
    ptsd21 = not_at_all_somewhat_considerably_very_much_2,
    ptsd22 = not_at_all_somewhat_considerably_very_much_2,
    ptsd23 = not_at_all_somewhat_considerably_very_much_2
  )
)
