## LASA filecode 021 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_021 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "K",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB",
      "MB"
    ),
    variable_name = c(
      "bmemory1",
      "bmemory2",
      "bmmse01",
      "bmmse02",
      "bmmse03",
      "bmmse04",
      "bmmse05",
      "bmmse06",
      "bmmse07",
      "bmmse08",
      "bmmse09",
      "bmmse10",
      "bmmse11",
      "bmmse12",
      "bmmse13",
      "bmmse14",
      "bmmse15",
      "bmmse16",
      "bmmse17",
      "bmmse18",
      "bmmse19",
      "bmmse20",
      "bmmse21",
      "bmmse22",
      "bmmse23",
      "bmemory1",
      "bmemory2",
      "bmmse01",
      "bmmse02",
      "bmmse03",
      "bmmse04",
      "bmmse05",
      "bmmse06",
      "bmmse07",
      "bmmse08",
      "bmmse09",
      "bmmse10",
      "bmmse11",
      "bmmse12",
      "bmmse13",
      "bmmse14",
      "bmmse15",
      "bmmse16",
      "bmmse17",
      "bmmse18",
      "bmmse19",
      "bmmse20",
      "bmmse21",
      "bmmse22",
      "bmmse23",
      "bmemory1",
      "bmemory2",
      "bmmse01",
      "bmmse02",
      "bmmse03",
      "bmmse04",
      "bmmse05",
      "bmmse06",
      "bmmse07",
      "bmmse08",
      "bmmse09",
      "bmmse10",
      "bmmse11",
      "bmmse12",
      "bmmse13",
      "bmmse14",
      "bmmse15",
      "bmmse16",
      "bmmse17",
      "bmmse18",
      "bmmse19",
      "bmmse20",
      "bmmse21",
      "bmmse22",
      "bmmse23",
      "cmemory1",
      "cmemory2",
      "cmmse01",
      "cmmse02",
      "cmmse03",
      "cmmse04",
      "cmmse05",
      "cmmse06",
      "cmmse07",
      "cmmse08",
      "cmmse09",
      "cmmse10",
      "cmmse11",
      "cmmse12",
      "cmmse13",
      "cmmse14",
      "cmmse15",
      "cmmse16",
      "cmmse17",
      "cmmse18",
      "cmmse19",
      "cmmse20",
      "cmmse21",
      "cmmse22",
      "cmmse23",
      "dmemory1",
      "dmemory2",
      "dmmse01",
      "dmmse02",
      "dmmse03",
      "dmmse04",
      "dmmse05",
      "dmmse06",
      "dmmse07",
      "dmmse08",
      "dmmse09",
      "dmmse10",
      "dmmse11",
      "dmmse12",
      "dmmse13",
      "dmmse14",
      "dmmse15",
      "dmmse16",
      "dmmse17",
      "dmmse18",
      "dmmse19",
      "dmmse20",
      "dmmse21",
      "dmmse22",
      "dmmse23",
      "ememory1",
      "ememory2",
      "emmse01",
      "emmse02",
      "emmse03",
      "emmse04",
      "emmse05",
      "emmse06",
      "emmse07",
      "emmse08",
      "emmse09",
      "emmse10",
      "emmse11",
      "emmse12",
      "emmse13",
      "emmse14",
      "emmse15",
      "emmse16",
      "emmse17",
      "emmse18",
      "emmse19",
      "emmse20",
      "emmse21",
      "emmse22",
      "emmse23",
      "fmemory1",
      "fmemory2",
      "fmmse01",
      "fmmse02",
      "fmmse03",
      "fmmse04",
      "fmmse05",
      "fmmse06",
      "fmmse07",
      "fmmse08",
      "fmmse09",
      "fmmse10",
      "fmmse11",
      "fmmse12",
      "fmmse13",
      "fmmse14",
      "fmmse15",
      "fmmse16",
      "fmmse17",
      "fmmse18",
      "fmmse19",
      "fmmse20",
      "fmmse21",
      "fmmse22",
      "fmmse23",
      "gmemory1",
      "gmemory2",
      "gmmse01",
      "gmmse02",
      "gmmse03",
      "gmmse04",
      "gmmse05",
      "gmmse06",
      "gmmse07",
      "gmmse08",
      "gmmse09",
      "gmmse10",
      "gmmse11",
      "gmmse12",
      "gmmse13",
      "gmmse14",
      "gmmse15",
      "gmmse16",
      "gmmse17",
      "gmmse18",
      "gmmse19",
      "gmmse20",
      "gmmse21",
      "gmmse22",
      "gmmse23",
      "hmemory1",
      "hmemory2",
      "hmmse01",
      "hmmse02",
      "hmmse03",
      "hmmse04",
      "hmmse05",
      "hmmse06",
      "hmmse07",
      "hmmse08",
      "hmmse09",
      "hmmse10",
      "hmmse11",
      "hmmse12",
      "hmmse13",
      "hmmse14",
      "hmmse15",
      "hmmse16",
      "hmmse17",
      "hmmse18",
      "hmmse19",
      "hmmse20",
      "hmmse21",
      "hmmse22",
      "hmmse23",
      "imemory1",
      "imemory2",
      "immse01",
      "immse02",
      "immse03",
      "immse04",
      "immse05",
      "immse06",
      "immse07",
      "immse08",
      "immse09",
      "immse10",
      "immse11",
      "immse12",
      "immse13",
      "immse14",
      "immse15",
      "immse16",
      "immse17",
      "immse18",
      "immse19",
      "immse20",
      "immse21",
      "immse22",
      "immse23",
      "jmemory1",
      "jmemory2",
      "jmmse01",
      "jmmse02",
      "jmmse03",
      "jmmse04",
      "jmmse05",
      "jmmse06",
      "jmmse07",
      "jmmse08",
      "jmmse09",
      "jmmse10",
      "jmmse11",
      "jmmse12",
      "jmmse13",
      "jmmse14",
      "jmmse15",
      "jmmse16",
      "jmmse17",
      "jmmse18",
      "jmmse19",
      "jmmse20",
      "jmmse21",
      "jmmse22",
      "jmmse23",
      "kmemory1",
      "kmemory2",
      "kmmse01",
      "kmmse02",
      "kmmse03",
      "kmmse04",
      "kmmse05",
      "kmmse06",
      "kmmse07",
      "kmmse08",
      "kmmse09",
      "kmmse10",
      "kmmse11",
      "kmmse12",
      "kmmse13",
      "kmmse14",
      "kmmse15",
      "kmmse16",
      "kmmse17",
      "kmmse18",
      "kmmse19",
      "kmmse20",
      "kmmse21",
      "kmmse22",
      "kmmse23",
      "bimmse01",
      "bimmse02",
      "bimmse03",
      "bimmse04",
      "bimmse05",
      "bimmse06",
      "bimmse07",
      "bimmse08",
      "bimmse09",
      "bimmse10",
      "bimmse11",
      "bimmse13",
      "bimmse14",
      "bimmse15",
      "bimmse16",
      "bimmse17",
      "bimmse18",
      "bimmse19",
      "bimmse20",
      "bimmse21",
      "bimmse22",
      "bimmse23",
      "bmemory1",
      "bmemory2",
      "bmmse01",
      "bmmse02",
      "bmmse03",
      "bmmse04",
      "bmmse05",
      "bmmse06",
      "bmmse07",
      "bmmse08",
      "bmmse09",
      "bmmse10",
      "bmmse11",
      "bmmse12",
      "bmmse13",
      "bmmse14",
      "bmmse15",
      "bmmse16",
      "bmmse17",
      "bmmse18",
      "bmmse19",
      "bmmse20",
      "bmmse21",
      "bmmse22",
      "bmmse23",
      "bmmsevrs"
    ),
    canonical_name = c(
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "immse01",
      "immse02",
      "immse03",
      "immse04",
      "immse05",
      "immse06",
      "immse07",
      "immse08",
      "immse09",
      "immse10",
      "immse11",
      "immse13",
      "immse14",
      "immse15",
      "immse16",
      "immse17",
      "immse18",
      "immse19",
      "immse20",
      "immse21",
      "immse22",
      "immse23",
      "memory1",
      "memory2",
      "mmse01",
      "mmse02",
      "mmse03",
      "mmse04",
      "mmse05",
      "mmse06",
      "mmse07",
      "mmse08",
      "mmse09",
      "mmse10",
      "mmse11",
      "mmse12",
      "mmse13",
      "mmse14",
      "mmse15",
      "mmse16",
      "mmse17",
      "mmse18",
      "mmse19",
      "mmse20",
      "mmse21",
      "mmse22",
      "mmse23",
      "mmsevrs"
    ),
    variable_label = c(
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province",
      "MMSE item07: Municipality",
      "MMSE item08: Two main streets",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: subtraction of 7",
      "MMSE item13: Spelling backwards",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Illiterate MMSE: Part of the day",
      "Illiterate MMSE: Season",
      "Illiterate MMSE: Part of the month",
      "Illiterate MMSE: Day of the week",
      "Illiterate MMSE: Month",
      "Illiterate MMSE: Country",
      "Illiterate MMSE: City/Village",
      "Illiterate MMSE: District/neighbourhood",
      "Illiterate MMSE: Floor",
      "Illiterate MMSE: Address",
      "Illiterate MMSE: Three objects",
      "Illiterate MMSE: Days of the week in reverse order",
      "Illiterate MMSE: Remembering three objects",
      "Illiterate MMSE: Watch",
      "Illiterate MMSE: Pencil",
      "Illiterate MMSE: Remember sentence",
      "Illiterate MMSE: Close eyes",
      "Illiterate MMSE: Paper (1): Right hand",
      "Illiterate MMSE: Paper (2): Folds",
      "Illiterate MMSE: Paper (3): In lap",
      "Illiterate MMSE: Formulate question",
      "Illiterate MMSE: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE: Year",
      "MMSE: Season",
      "MMSE: Day of the month",
      "MMSE: Day of the week",
      "MMSE: Month",
      "MMSE: Country",
      "MMSE: City/Village",
      "MMSE: District/neighbourhood",
      "MMSE: Floor",
      "MMSE: Address",
      "MMSE: Three objects",
      "MMSE: Subtraction of 3",
      "MMSE: Days in reverse order/spelling backwards",
      "MMSE: Remembering three objects",
      "MMSE: Watch",
      "MMSE: Pencil",
      "MMSE: Remember sentence",
      "MMSE: Close eyes",
      "MMSE: Paper (1): Right hand",
      "MMSE: Paper (2): Folds",
      "MMSE: Paper (3): In lap",
      "MMSE: Write sentence",
      "MMSE: Drawing",
      "MMSE version"
    ),
    harmonized_var_label = c(
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "Illiterate MMSE: Part of the day",
      "Illiterate MMSE: Season",
      "Illiterate MMSE: Part of the month",
      "Illiterate MMSE: Day of the week",
      "Illiterate MMSE: Month",
      "Illiterate MMSE: Country",
      "Illiterate MMSE: City/Village",
      "Illiterate MMSE: District/neighbourhood",
      "Illiterate MMSE: Floor",
      "Illiterate MMSE: Address",
      "Illiterate MMSE: Three objects",
      "Illiterate MMSE: Days of the week in reverse order",
      "Illiterate MMSE: Remembering three objects",
      "Illiterate MMSE: Watch",
      "Illiterate MMSE: Pencil",
      "Illiterate MMSE: Remember sentence",
      "Illiterate MMSE: Close eyes",
      "Illiterate MMSE: Paper (1): Right hand",
      "Illiterate MMSE: Paper (2): Folds",
      "Illiterate MMSE: Paper (3): In lap",
      "Illiterate MMSE: Formulate question",
      "Illiterate MMSE: Drawing",
      "Problems with memory",
      "Consulted doctor for memory problems",
      "MMSE item01: Year",
      "MMSE item02: Season",
      "MMSE item03: Date/day of month",
      "MMSE item04: Day of the week",
      "MMSE item05: Month",
      "MMSE item06: Province/country",
      "MMSE item07: Municipality/city/village",
      "MMSE item08: Local-area orientation",
      "MMSE item09: Floor",
      "MMSE item10: Address",
      "MMSE item11: Three objects",
      "MMSE item12: Serial subtraction task",
      "MMSE item13: Reverse-order verbal task",
      "MMSE item14: Remembering three objects",
      "MMSE item15: Watch",
      "MMSE item16: Pencil",
      "MMSE item17: Remember sentence",
      "MMSE item18: close eyes",
      "MMSE item19: paper (1): Right hand",
      "MMSE item20: paper (2): Folds",
      "MMSE item21: paper (3): In lap",
      "MMSE item22: Write sentence",
      "MMSE item23: Drawing",
      "MMSE version"
    ),
    var_type = c(
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    memory1 = list(
      `2B` = no_yes_54,
      `3B` = no_yes_54,
      B = no_yes,
      C = no_yes,
      D = no_yes_54,
      E = no_yes_54,
      F = no_yes_54,
      G = no_yes_54,
      H = no_yes_54,
      I = no_yes_54,
      J = no_yes_54,
      K = no_yes_54,
      MB = c(`-2` = "na, see BMMSESC in LASMB221", `-1` = "na, asked", `1` = "no", `2` = "yes")
    ),
    memory2 = list(
      `2B` = no_yes_55,
      `3B` = no_yes_55,
      B = no_yes_264,
      C = no_yes_264,
      D = no_yes_55,
      E = no_yes_55,
      F = no_yes_55,
      G = no_yes_55,
      H = no_yes_55,
      I = no_yes_55,
      J = no_yes_55,
      K = no_yes_55,
      MB = c(
        `-3` = "na, wrong skip",
        `-2` = "na, see BMEMORY1",
        `-1` = "na, asked",
        `1` = "no",
        `2` = "yes"
      )
    ),
    mmse01 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse02 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse03 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse04 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse05 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse06 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse07 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse08 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse09 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse10 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse11 = list(
      `2B` = vs_0_right_1_right_2_right_3_right,
      `3B` = vs_0_right_1_right_2_right_3_right,
      B = vs_0_right_1_right_2_right_3_right_2,
      C = vs_0_right_1_right_2_right_3_right_2,
      D = vs_0_right_1_right_2_right_3_right,
      E = vs_0_right_1_right_2_right_3_right,
      F = vs_0_right_1_right_2_right_3_right,
      G = vs_0_right_1_right_2_right_3_right,
      H = vs_0_right_1_right_2_right_3_right,
      I = vs_0_right_1_right_2_right_3_right,
      J = vs_0_right_1_right_2_right_3_right,
      K = vs_0_right_1_right_2_right_3_right,
      MB = vs_0_right_1_right_2_right_3_right_3
    ),
    mmse12 = list(
      `2B` = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      `3B` = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      B = vs_0_right_1_right_2_right_3_right_4_right_5_right_2,
      C = vs_0_right_1_right_2_right_3_right_4_right_5_right_2,
      D = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      E = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      F = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      G = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      H = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      I = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      J = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      K = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      MB = wrong_correct_2
    ),
    mmse13 = list(
      `2B` = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      `3B` = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      B = vs_0_right_1_right_2_right_3_right_4_right_5_right_2,
      C = vs_0_right_1_right_2_right_3_right_4_right_5_right_2,
      D = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      E = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      F = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      G = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      H = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      I = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      J = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      K = vs_0_right_1_right_2_right_3_right_4_right_5_right,
      MB = vs_0_right_1_right_2_right_3_right_4_right_5_right_3
    ),
    mmse14 = list(
      `2B` = vs_0_right_1_right_2_right_3_right,
      `3B` = vs_0_right_1_right_2_right_3_right,
      B = vs_0_right_1_right_2_right_3_right_2,
      C = vs_0_right_1_right_2_right_3_right_2,
      D = vs_0_right_1_right_2_right_3_right,
      E = vs_0_right_1_right_2_right_3_right,
      F = vs_0_right_1_right_2_right_3_right,
      G = vs_0_right_1_right_2_right_3_right,
      H = vs_0_right_1_right_2_right_3_right,
      I = vs_0_right_1_right_2_right_3_right,
      J = vs_0_right_1_right_2_right_3_right,
      K = vs_0_right_1_right_2_right_3_right,
      MB = vs_0_right_1_right_2_right_3_right_3
    ),
    mmse15 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse16 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse17 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse18 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse19 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse20 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse21 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse22 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    mmse23 = list(
      `2B` = wrong_correct,
      `3B` = wrong_correct,
      B = wrong_correct_3,
      C = wrong_correct_3,
      D = wrong_correct,
      E = wrong_correct,
      F = wrong_correct,
      G = wrong_correct,
      H = wrong_correct,
      I = wrong_correct,
      J = wrong_correct,
      K = wrong_correct,
      MB = wrong_correct_2
    ),
    immse01 = list(
      MB = wrong_correct_2
    ),
    immse02 = list(
      MB = wrong_correct_2
    ),
    immse03 = list(
      MB = wrong_correct_2
    ),
    immse04 = list(
      MB = wrong_correct_2
    ),
    immse05 = list(
      MB = wrong_correct_2
    ),
    immse06 = list(
      MB = wrong_correct_2
    ),
    immse07 = list(
      MB = wrong_correct_2
    ),
    immse08 = list(
      MB = wrong_correct_2
    ),
    immse09 = list(
      MB = wrong_correct_2
    ),
    immse10 = list(
      MB = wrong_correct_2
    ),
    immse11 = list(
      MB = vs_0_right_1_right_2_right_3_right_3
    ),
    immse13 = list(
      MB = vs_0_right_1_right_2_right_3_right_4_right_5_right_3
    ),
    immse14 = list(
      MB = vs_0_right_1_right_2_right_3_right_3
    ),
    immse15 = list(
      MB = wrong_correct_2
    ),
    immse16 = list(
      MB = wrong_correct_2
    ),
    immse17 = list(
      MB = wrong_correct_2
    ),
    immse18 = list(
      MB = wrong_correct_2
    ),
    immse19 = list(
      MB = wrong_correct_2
    ),
    immse20 = list(
      MB = wrong_correct_2
    ),
    immse21 = list(
      MB = wrong_correct_2
    ),
    immse22 = list(
      MB = wrong_correct_2
    ),
    immse23 = list(
      MB = wrong_correct_2
    ),
    mmsevrs = list(
      MB = regular_version_mmse_regular_version_mmse
    )
  ),

  value_labels_harmonized = list(
    immse01 = wrong_correct_4,
    immse02 = wrong_correct_4,
    immse03 = wrong_correct_4,
    immse04 = wrong_correct_4,
    immse05 = wrong_correct_4,
    immse06 = wrong_correct_4,
    immse07 = wrong_correct_4,
    immse08 = wrong_correct_4,
    immse09 = wrong_correct_4,
    immse10 = wrong_correct_4,
    immse11 = vs_0_right_1_right_2_right_3_right_4,
    immse13 = vs_0_right_1_right_2_right_3_right_4_right_5_right_4,
    immse14 = vs_0_right_1_right_2_right_3_right_4,
    immse15 = wrong_correct_4,
    immse16 = wrong_correct_4,
    immse17 = wrong_correct_4,
    immse18 = wrong_correct_4,
    immse19 = wrong_correct_4,
    immse20 = wrong_correct_4,
    immse21 = wrong_correct_4,
    immse22 = wrong_correct_4,
    immse23 = wrong_correct_4,
    memory1 = no_yes_70,
    memory2 = no_yes_4,
    mmse01 = wrong_correct_4,
    mmse02 = wrong_correct_4,
    mmse03 = wrong_correct_4,
    mmse04 = wrong_correct_4,
    mmse05 = wrong_correct_4,
    mmse06 = wrong_correct_4,
    mmse07 = wrong_correct_4,
    mmse08 = wrong_correct_4,
    mmse09 = wrong_correct_4,
    mmse10 = wrong_correct_4,
    mmse11 = vs_0_right_1_right_2_right_3_right_4,
    mmse12 = c(
      `-2` = "not available, routing",
      `-1` = "not available, asked",
      `0` = "0 right",
      `1` = "MMSE item12 response category 1",
      `2` = "MMSE item12 response category 2",
      `3` = "3 right",
      `4` = "4 right",
      `5` = "5 right"
    ),
    mmse13 = vs_0_right_1_right_2_right_3_right_4_right_5_right_4,
    mmse14 = vs_0_right_1_right_2_right_3_right_4,
    mmse15 = wrong_correct_4,
    mmse16 = wrong_correct_4,
    mmse17 = wrong_correct_4,
    mmse18 = wrong_correct_4,
    mmse19 = wrong_correct_4,
    mmse20 = wrong_correct_4,
    mmse21 = wrong_correct_4,
    mmse22 = wrong_correct_4,
    mmse23 = wrong_correct_4,
    mmsevrs = regular_version_mmse_regular_version_mmse
  )
)
