## LASA filecode 228 -- variable labels, per-wave value labels, and
## harmonized (cross-wave-standardized) value labels.
##
## Generated once from the LASA variable-information transcription CSVs;
## maintained by hand from here on. To add a new wave: add row(s) to the
## `variables` data.frame below and, if the wave introduces value labels,
## a matching entry under `value_labels`. To add a new variable: same,
## plus (optionally) a `value_labels_harmonized` entry giving its
## cross-wave-standardized value labels.

.lasa_fc_228 <- list(
  variables = data.frame(
    wave = c(
      "2B",
      "2B",
      "2B",
      "2B",
      "2B",
      "3B",
      "3B",
      "3B",
      "3B",
      "3B",
      "B",
      "B",
      "B",
      "B",
      "B",
      "C",
      "C",
      "C",
      "C",
      "C",
      "D",
      "D",
      "D",
      "D",
      "D",
      "E",
      "E",
      "E",
      "E",
      "E",
      "F",
      "F",
      "F",
      "F",
      "F",
      "G",
      "G",
      "G",
      "G",
      "G",
      "H",
      "H",
      "H",
      "H",
      "H",
      "I",
      "I",
      "I",
      "I",
      "I",
      "J",
      "J",
      "J",
      "J",
      "J",
      "K",
      "K",
      "K",
      "K",
      "K"
    ),
    variable_name = c(
      "badversi",
      "balcos",
      "bcomple",
      "binitia",
      "brmalc",
      "badversi",
      "balcos",
      "bcomple",
      "binitia",
      "brmalc",
      "badversi",
      "balcos",
      "bcomple",
      "binitia",
      "brmalc",
      "cadversi",
      "calcos",
      "ccomple",
      "cinitia",
      "crmalc",
      "dadversi",
      "dalcos",
      "dcomple",
      "dinitia",
      "drmalc",
      "eadversi",
      "ealcos",
      "ecomple",
      "einitia",
      "ermalc",
      "fadversi",
      "falcos",
      "fcomple",
      "finitia",
      "frmalc",
      "gadversi",
      "galcos",
      "gcomple",
      "ginitia",
      "grmalc",
      "hadversi",
      "halcos",
      "hcomple",
      "hinitia",
      "hrmalc",
      "iadversi",
      "ialcos",
      "icomple",
      "iinitia",
      "irmalc",
      "jadversi",
      "jalcos",
      "jcomple",
      "jinitia",
      "jrmalc",
      "kadversi",
      "kalcos",
      "kcomple",
      "kinitia",
      "krmalc"
    ),
    canonical_name = c(
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc",
      "adversi",
      "alcos",
      "comple",
      "initia",
      "rmalc"
    ),
    variable_label = c(
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score",
      "persistence in the face of adversity",
      "alcos scale score",
      "effort completing behavior",
      "willingness to initiate behavior",
      "reason missing alcos score"
    ),
    harmonized_var_label = c(
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score",
      "Persistence in the face of adversity score",
      "Perceived self-efficacy scale score",
      "Effort completing behavior score",
      "Willingness to initiate behavior score",
      "Reason for missing perceived self-efficacy score"
    ),
    var_type = c(
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical",
      "numeric",
      "numeric",
      "numeric",
      "numeric",
      "categorical"
    ),
    stringsAsFactors = FALSE
  ),

  value_labels = list(
    adversi = list(
      `2B` = no_valid_data_3,
      `3B` = no_valid_data_3,
      B = c(`-2` = "na, see BRMALC", `4` = NA_character_, `20` = NA_character_),
      C = no_valid_data_3,
      D = no_valid_data_3,
      E = no_valid_data_3,
      F = no_valid_data_3,
      G = no_valid_data_3,
      H = no_valid_data_3,
      I = no_valid_data_3,
      J = no_valid_data_3,
      K = no_valid_data_3
    ),
    alcos = list(
      `2B` = no_valid_data_10,
      `3B` = no_valid_data_7,
      B = c(`-2` = "na, see BRMALC", `14` = NA_character_, `60` = NA_character_),
      C = no_valid_data_12,
      D = no_valid_data_12,
      E = no_valid_data_10,
      F = no_valid_data_10,
      G = no_valid_data_7,
      H = no_valid_data_7,
      I = no_valid_data_7,
      J = no_valid_data_7,
      K = no_valid_data_7
    ),
    comple = list(
      `2B` = no_valid_data_11,
      `3B` = no_valid_data_6,
      B = c(`-2` = "na, see BRMALC", `5` = NA_character_, `25` = NA_character_),
      C = no_valid_data_6,
      D = no_valid_data_6,
      E = no_valid_data_11,
      F = no_valid_data_11,
      G = no_valid_data_6,
      H = no_valid_data_6,
      I = no_valid_data_6,
      J = no_valid_data_6,
      K = no_valid_data_6
    ),
    initia = list(
      `2B` = no_valid_data_4,
      `3B` = no_valid_data_4,
      B = c(`-2` = "na, see BRMALC", `3` = NA_character_, `15` = NA_character_),
      C = no_valid_data_4,
      D = no_valid_data_4,
      E = no_valid_data_4,
      F = no_valid_data_4,
      G = no_valid_data_4,
      H = no_valid_data_4,
      I = no_valid_data_4,
      J = no_valid_data_4,
      K = no_valid_data_4
    ),
    rmalc = list(
      `2B` = short_interview_interview_terminated_too_many_missings,
      `3B` = short_interview_interview_terminated_too_many_missings_2,
      B = short_interview_interview_terminated_too_many_missings,
      C = short_interview_interview_terminated_too_many_missings,
      D = short_interview_interview_terminated_too_many_missings,
      E = short_interview_interview_terminated_too_many_missings,
      F = c(
        `-2` = "valid score",
        `1` = "short interview",
        `2` = "interview terminated",
        `3` = "too many missings",
        `4` = "refused to answer"
      ),
      G = short_interview_interview_terminated_too_many_missings_2,
      H = short_interview_interview_terminated_too_many_missings_2,
      I = short_interview_interview_terminated_too_many_missings_2,
      J = short_interview_interview_terminated_too_many_missings_2,
      K = short_interview_interview_terminated_too_many_missings_2
    )
  ),

  value_labels_harmonized = list(
    adversi = no_valid_data_3,
    alcos = c(
      `-2` = "no valid data",
      `14` = NA_character_,
      `20` = NA_character_,
      `22` = NA_character_,
      `23` = NA_character_,
      `60` = NA_character_
    ),
    comple = c(`-2` = "no valid data", `5` = NA_character_, `8` = NA_character_, `25` = NA_character_),
    initia = no_valid_data_4,
    rmalc = short_interview_interview_terminated_too_many_missings_2
  )
)
