## The manually-maintained LASA topic database.
##
## This is the single source of truth for `lasa_topics()`: every LASA topic,
## its theme/subtheme, file code(s), the waves it was collected in, and whether
## LASA links a variable-information PDF for it. Unlike the label database
## (data-raw/variable_<fc>.R), none of this is scraped -- the topic-table HTML
## on the LASA website is irregular enough (line-break-glued topics, several
## file codes sharing one row, compound labels) that parsing it didn't always
## go right, so it is transcribed here by hand instead, from LASA's own topic
## overview (https://lasa-vu.nl/en/topic-table/). `lasa_var_info()` still
## scrapes that page live, but only to resolve a file code's varinfo.pdf link
## (see R/lasa_var_info.R) -- never for topic/theme text.
##
## To add a new topic or file code: add one `add_topic()` call below, in the
## right `## ---- <Theme> ----` section (alphabetical by theme, then subtheme,
## then topic, matching lasa_topics()'s own sort order -- not required, just
## keeps this file easy to scan).
## To update which waves an existing file code is available in (e.g. a newly
## released wave "L"): edit that row's `waves = c(...)` vector directly.
## Then re-run this script to rebuild R/sysdata.rda.
##
## `subtheme` and `filecode` are `NA_character_` when LASA's topic table itself
## leaves them blank (a topic with no subtheme, or one with no file yet, e.g.
## "Exome Chip"). `has_varinfo` is independent of `filecode` -- a topic can have
## a file code but no linked PDF (e.g. a tel.-proxy variant LASA never wrote
## up separately) -- so it is recorded explicitly per row rather than derived.
## `lasa_topics()` still returns rows with a missing filecode/varinfo; only
## `lasa_var_info()` needs a matched file code to resolve an actual PDF link.
##
## Run from the package root.

Sys.setlocale("LC_CTYPE", "C.UTF-8") # guards UTF-8 topic text

devtools::load_all(".", quiet = TRUE) # for .lasa_validate_topic_database()

lasa_topic_database <- data.frame(
  theme = character(), subtheme = character(), topic = character(),
  filecode = character(), waves = character(), has_varinfo = logical(),
  stringsAsFactors = FALSE
)

add_topic <- function(theme, subtheme = NA_character_, topic,
                      filecode = NA_character_, waves = NA_character_,
                      has_varinfo = FALSE) {
  lasa_topic_database <<- rbind(lasa_topic_database, data.frame(
    theme = theme, subtheme = subtheme, topic = topic, filecode = filecode,
    waves = if (length(waves) > 1L || !is.na(waves)) paste(waves, collapse = ", ") else NA_character_,
    has_varinfo = has_varinfo, stringsAsFactors = FALSE
  ))
}

## ---- Biomaterial (25 rows) ----
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Adiponectin, leptin and ghrelin", filecode = "879", waves = c("G"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Apolipoprotein E (ApoE)", filecode = "870", waves = c("B", "2B"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Blood collection and overview (routine) measurements", filecode = "850", waves = c("B", "C", "2B", "G", "3B"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Bone-related hormones and bone turnover", filecode = "862", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Cholesterol, triglycerides and fructosamin", filecode = "867", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "COLIA1 (Collagen type I α1 Sp1 polymorphism in LASA)", filecode = "871", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Cortisol (total plasma cortisol, corticosteroid binding globuline, salivary cortisol) - plasma / serum cortisol", filecode = "864", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Cortisol (total plasma cortisol, corticosteroid binding globuline, salivary cortisol) - Salivary cortisol (non)response", filecode = "880", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Cortisol (total plasma cortisol, corticosteroid binding globuline, salivary cortisol) - Salivary cortisol, moment of day", filecode = "881", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Cortisol (total plasma cortisol, corticosteroid binding globuline, salivary cortisol) - Salivary cortisol, moment of day (constructed)", filecode = "882", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Exome Chip", filecode = NA_character_, waves = c("C", "G"), has_varinfo = FALSE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Genetic polymorphisms (VDR, GR, etc) - Glucocorticoid Receptor (GR) SNPs and haplotypes", filecode = "873", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Genetic polymorphisms (VDR, GR, etc) - Vitamin D Receptor (VDR) SNPs and haplotypes", filecode = "872", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "GWAS data", filecode = NA_character_, waves = c("C", "2B", "G", "3B"), has_varinfo = FALSE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Hair cortisol (LASA ancillary study)", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Homocysteine, vitamin B12, MMA", filecode = "866", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Inflammation factors", filecode = "861", waves = c("B", "C", "3B"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Plasma markers of Alzheimer's Disease", filecode = "868", waves = c("C", "G"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Plasma markers of endothelial dysfunction", filecode = "878", waves = c("G"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Response blood sampling / DNA Date blood sampling", filecode = "851", waves = c("B", "C", "2B", "G", "3B"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Routine measurements (Albumin and cholesterol)", filecode = "860", waves = c("B", "C", "2B", "G", "3B"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Serum 25-hydroxy-vitamin D (25(OH)D) and parathyroid hormone (PTH)", filecode = "862", waves = c("C", "2B", "G", "3B"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Sex hormones", filecode = "863", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Thyroid function", filecode = "865", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Biomaterial", subtheme = NA_character_, topic = "Vitamin K status", filecode = "869", waves = c("2B"), has_varinfo = TRUE)
## ---- Care (54 rows) ----
add_topic(theme = "Care", subtheme = "Adaptations and facilities", topic = "Adaptations in the house", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Care", subtheme = "Adaptations and facilities", topic = "Use of assistive devices or assistence", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Care", subtheme = "Contact with services", topic = "Care and contacts", filecode = "109", waves = c("I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Contact with services", topic = "Contact with health and social services", filecode = "044", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Contact with services", topic = "Health care in country of origin", filecode = "068", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Contact with services", topic = "Hospital admission", filecode = "045", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Contact with services", topic = "Hospital admission - tel. proxy", filecode = "603", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Contact with services", topic = "Hospital admission - tel. respondent", filecode = "703", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Contact with services", topic = "Outpatient contact with medical specialists last 6 months", filecode = "045", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Contact with services", topic = "Outpatient contact with medical specialists last 6 months - specification of specialist", filecode = "245", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "End of life care and preferences", topic = "Advance Care Planning (ACP)", filecode = "108", waves = c("I", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "End of life care and preferences", topic = "Advance Directives", filecode = "093", waves = c("D"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "End of life care and preferences", topic = "Advance Directives", filecode = "195", waves = c("F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "End of life care and preferences", topic = "Advance Directives - tel. respondent", filecode = "709", waves = c("D"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "End of life care and preferences", topic = "Decisions in eol situations", filecode = "148", waves = c("G"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "End of life care and preferences", topic = "End-of-life care: interviews with proxies (LASA ancillary study)", filecode = NA_character_, waves = c("E", "G"), has_varinfo = FALSE)
add_topic(theme = "Care", subtheme = "End of life care and preferences", topic = "Feelings and wishes about life and death", filecode = "127", waves = c("I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "End of life care and preferences", topic = "General eol goals; Subj. life exp.", filecode = "094", waves = c("G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "End of life care and preferences", topic = "Last wishes", filecode = "146", waves = c("F"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "End of life care and preferences", topic = "Opinions about euthanasia and end-of-life (eol) pill", filecode = "122", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Needs assessment", topic = "Needs assessment - Contact with WMO and application for facilities", filecode = "178", waves = c("G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Needs assessment", topic = "Needs assessment - medical care indication", filecode = "189", waves = c("E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Needs assessment", topic = "Needs assessment - Medical indication and facilities (tel. proxy)", filecode = "610", waves = c("E", "F", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Needs assessment", topic = "Needs assessment - Medical indication and facilities (tel. respondent)", filecode = "710", waves = c("E", "F", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Needs assessment", topic = "Needs assessment - Use WVG facilities", filecode = "177", waves = c("G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Needs assessment", topic = "Needs assessment - Use WVG facilities (tel. proxy)", filecode = "611", waves = c("G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Needs assessment", topic = "Needs assessment - Use WVG facilities (tel. respondent)", filecode = "711", waves = c("G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Providing care", topic = "Family caregiving to older adults (LASA ancillary study)", filecode = NA_character_, waves = c("E"), has_varinfo = FALSE)
add_topic(theme = "Care", subtheme = "Providing care", topic = "Providing assistance with personal/household care", filecode = "142", waves = c("2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Aggr. variables care network", filecode = "233", waves = c("H"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Care evaluation", filecode = "033", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Need for care", filecode = "033", waves = c("F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Perceived control in health care and scale (LASA ancillary study)", filecode = NA_character_, waves = c("H"), has_varinfo = FALSE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Perceived control of care", filecode = "033", waves = c("H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Personal budget (PGB)", filecode = "033", waves = c("H"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Satisfaction with care", filecode = "033", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Transitions in care (LASA ancillary study)*", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Use of nursing care", filecode = "033", waves = c("H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Use of nursing care - tel. proxy", filecode = "603", waves = c("H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Use of nursing care - tel. respondent", filecode = "703", waves = c("H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Use of personal/household care", filecode = "033", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Use of personal/household care - tel. proxy", filecode = "603", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Use of personal/household care - tel. respondent", filecode = "703", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Use of respite care by R (for partner)", filecode = "139", waves = c("I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Use of transport/admin. care", filecode = "033", waves = c("H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Use of transport/admin. care - tel. proxy", filecode = "603", waves = c("H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = "Use of care", topic = "Use of transport/admin. care - tel. respondent", filecode = "703", waves = c("H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = NA_character_, topic = "Attitudes about care", filecode = "032", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = NA_character_, topic = "Attitudes about care", filecode = "112", waves = c("B", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = NA_character_, topic = "Attitudes about care", filecode = "175", waves = c("J", "K"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = NA_character_, topic = "Filial responsibility expectations", filecode = "132", waves = c("D", "E", "J"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = NA_character_, topic = "Filial responsibility expectations - scaled", filecode = "332", waves = c("D", "E", "J"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = NA_character_, topic = "Vignettes about help", filecode = "074", waves = c("D"), has_varinfo = TRUE)
add_topic(theme = "Care", subtheme = NA_character_, topic = "Vignettes about help", filecode = "274", waves = c("D"), has_varinfo = TRUE)
## ---- Cognitive (32 rows) ----
add_topic(theme = "Cognitive", subtheme = "Dementia", topic = "Dementia algorithm", filecode = NA_character_, waves = c("C", "D", "E", "2B", "F", "G", "H", "I"), has_varinfo = FALSE)
add_topic(theme = "Cognitive", subtheme = "Dementia", topic = "Dementia parents", filecode = "092", waves = c("D", "2B"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Dementia", topic = "Dementia parents - tel. respondent", filecode = "702", waves = c("D"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Dementia", topic = "Dementia partner", filecode = "139", waves = c("E", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Executive functioning", topic = "Executive functioning (Digit span)", filecode = "020", waves = c("3B"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Executive functioning", topic = "Executive functioning (Digit span)", filecode = "166", waves = c("H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Executive functioning", topic = "Executive functioning (Digit span)", filecode = "220", waves = c("3B"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Executive functioning", topic = "Verbal fluency", filecode = "165", waves = c("H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Crystallized intelligence (GIT ©)", filecode = "037", waves = c("C", "F", "I"), has_varinfo = FALSE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Crystallized intelligence (GIT ©) - total scores", filecode = "237", waves = c("C", "F", "I"), has_varinfo = FALSE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Fluid intelligence (RAVEN)", filecode = "022", waves = c("B", "C", "D", "E", "2B", "F", "G"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Fluid intelligence (RAVEN)", filecode = "024", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Fluid intelligence (RAVEN) - scaled Evaluation RAVEN", filecode = "222", waves = c("B", "C", "D", "E", "2B", "F", "G"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Head trauma", filecode = "035", waves = c("D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Head trauma - tel. proxy", filecode = "602", waves = c("D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Head trauma - tel. respondent", filecode = "702", waves = c("D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Health literacy", filecode = "196", waves = c("K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Informant Quest. of COgn. DEcline (IQCODE) - tel. proxy", filecode = "607", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Informant Quest. of COgn. DEcline (IQCODE) - tel. respondent", filecode = "707", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Information processing speed (Coding task)", filecode = "155", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Mini-Mental State Examination (MMSE)", filecode = "021", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Mini-Mental State Examination (MMSE) - MMSE scaled", filecode = "221", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Mini-Mental State Examination (MMSE) - MMSE subtraction/spelling", filecode = "421", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Intelligence and cognition", topic = "Mini-Mental State Examination (MMSE) - tel. respondent", filecode = "707", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Memory", topic = "Episodic memory (15WT)", filecode = "156", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Memory", topic = "Episodic memory (15WT) - constructed", filecode = "356", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Memory", topic = "Everyday memory", filecode = "023", waves = c("B", "F"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Memory", topic = "Memory complaints", filecode = "021", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Memory", topic = "Memory complaints - tel. respondent", filecode = "707", waves = c("D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Memory", topic = "Memory partner", filecode = "139", waves = c("E", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Memory", topic = "Metamemory", filecode = "124", waves = c("B", "C", "D"), has_varinfo = TRUE)
add_topic(theme = "Cognitive", subtheme = "Memory", topic = "Metamemory - scaled", filecode = "324", waves = c("B", "C", "D"), has_varinfo = TRUE)
## ---- Demographics (39 rows) ----
add_topic(theme = "Demographics", subtheme = "General variables", topic = "(Non-)response; more detailed non-response", filecode = "z002", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Age at interview", filecode = "mb008", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Age at interview", filecode = "z008", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Education", filecode = "mb004", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Education", filecode = "z004", waves = c("B", "2B", "3B"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Ethnicity*", filecode = "mb004", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Ethnicity*", filecode = "z004", waves = c("B", "2B", "3B"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Nationality*", filecode = "mb004", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Nationality*", filecode = "z004", waves = c("B", "2B", "3B"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Sex", filecode = "mb004", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Sex", filecode = "z004", waves = c("B", "2B", "3B"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Time of measurement*", filecode = "mb008", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Time of measurement*", filecode = "z008", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "General variables", topic = "Weight factors", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Demographics", subtheme = "Geography", topic = "History of domestic addresses*", filecode = "z052", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Geography", topic = "Urbanization", filecode = "mb095", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Geography", topic = "Urbanization", filecode = "z095", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Living arrangements", topic = "Household composition", filecode = "011", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Living arrangements", topic = "Housing characteristics", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Demographics", subtheme = "Living arrangements", topic = "Marital and partner status", filecode = "z010", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Living arrangements", topic = "Marital and partner status - tel. proxy", filecode = "601", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = FALSE)
add_topic(theme = "Demographics", subtheme = "Living arrangements", topic = "Marital and partner status - tel. respondent", filecode = "701", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = FALSE)
add_topic(theme = "Demographics", subtheme = "Living arrangements", topic = "Marital and partner status (Migrant Cohort baseline)", filecode = "mb010", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Mortality", topic = "Mortality and cause of death", filecode = "z991", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Mortality", topic = "Mortality and cause of death - Specified", filecode = "z992", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Mortality", topic = "Mortality data", filecode = "z990", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Religion", topic = "Church affiliation", filecode = "038", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Religion", topic = "Church affiliation", filecode = "z038", waves = c("C", "D", "E", "2B", "3B"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Religion", topic = "Church attendance", filecode = "038", waves = c("MB", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Religion", topic = "Church attendance", filecode = "z038", waves = c("D", "E", "2B", "F", "G", "H", "3B", "I"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Socio-economic status", topic = "Health insurance", filecode = "018", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Socio-economic status", topic = "Income", filecode = "017", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Socio-economic status", topic = "Income - Income specification (wave B only)", filecode = "217", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Socio-economic status", topic = "Income and wealth", filecode = "015", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Socio-economic status", topic = "Income and wealth - house ownership", filecode = "017", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Socio-economic status", topic = "Income and wealth - income", filecode = "217", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Socio-economic status", topic = "Income and wealth - income specification", filecode = "019", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Socio-economic status", topic = "Income decline / evaluation", filecode = "019", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Demographics", subtheme = "Socio-economic status", topic = "Occupation", filecode = "016", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
## ---- Emotional (64 rows) ----
add_topic(theme = "Emotional", subtheme = "(In)dependence", topic = "Investment in independence", filecode = "144", waves = c("F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "ADHD", topic = "ADHD (LASA ancillary study)", filecode = "179", waves = c("G"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "ADHD", topic = "ADHD (LASA ancillary study) - constructed", filecode = "379", waves = c("G"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Anxiety", topic = "Anxiety diagnoses", filecode = NA_character_, waves = c("B", "D", "E", "2B", "G", "H", "I", "J"), has_varinfo = FALSE)
add_topic(theme = "Emotional", subtheme = "Anxiety", topic = "Anxiety symptoms", filecode = "026", waves = c("B", "C", "D", "E", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Anxiety", topic = "Anxiety symptoms - scaled", filecode = "226", waves = c("B", "C", "D", "E", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Anxiety", topic = "Posttraumatic stress (PTSD)", filecode = "091", waves = c("D", "E"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Anxiety", topic = "Posttraumatic stress (PTSD) - scaled", filecode = "291", waves = c("D", "E"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Depression", topic = "Depression diagnoses and depression algorithm", filecode = NA_character_, waves = c("J", "K"), has_varinfo = FALSE)
add_topic(theme = "Emotional", subtheme = "Depression", topic = "Depressive symptoms", filecode = "025", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Depression", topic = "Depressive symptoms - scaled", filecode = "225", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Depression", topic = "Depressive symptoms - tel. proxy", filecode = "606", waves = c("C", "D", "E"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Depression", topic = "Depressive symptoms - tel. respondent", filecode = "706", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Depression", topic = "Depressive symptoms and food-related behaviour (LASA ancillary study)", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Emotional", subtheme = "Depression", topic = "Lifetime Psychiatric Disorder (LIDAS)", filecode = "039", waves = c("K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Depression", topic = "Mental health problems and food-related behaviour (LASA ancillary study)", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Emotional", subtheme = "Evaluation of life", topic = "Awareness of Age-Related Change (AARC-SF)", filecode = "197", waves = c("K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Evaluation of life", topic = "Generativity", filecode = "802", waves = c("J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Evaluation of life", topic = "Important aspects of life", filecode = "110", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Evaluation of life", topic = "Satisfaction with life and happiness", filecode = "110", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Evaluation of life", topic = "Satisfaction with life and happiness - 'happiness-line'", filecode = "094", waves = c("D"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Evaluation of life", topic = "Valuation of life", filecode = "137", waves = c("E", "F"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Evaluation of life", topic = "Valuation of life - scaled", filecode = "337", waves = c("E", "F"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "General self-regulation (GSR)", filecode = "149", waves = c("G", "H"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "General self-regulation (GSR) - scaled", filecode = "349", waves = c("G", "H"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Humor", filecode = "111", waves = c("B", "D"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Humor - scaled", filecode = "311", waves = c("B", "D"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Mastery", filecode = "027", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Mastery - scaled", filecode = "227", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Meta-emotion", filecode = "029", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Meta-emotion", filecode = "143", waves = c("2B"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Neuroticism and soc. inadequacy", filecode = "123", waves = c("B", "C", "D", "E", "2B", "3B"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Neuroticism and soc. inadequacy - scaled", filecode = "323", waves = c("B", "C", "D", "E", "2B", "3B"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Perceived self-efficacy", filecode = "028", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Perceived self-efficacy - scaled", filecode = "228", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Self-esteem", filecode = "027", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Personality traits", topic = "Self-esteem - scaled", filecode = "227", waves = c("C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Gerotranscendence (Cosmic transcendence)", filecode = "038", waves = c("C", "D", "E", "2B", "F"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Gerotranscendence (Cosmic transcendence) - scaled", filecode = "238", waves = c("C", "D", "E", "2B", "F"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Orthodoxy (Main int.)", filecode = "038", waves = c("C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Orthodoxy (Main int.) - scaled", filecode = "138", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Orthodoxy (Self-adm. quest.)", filecode = "238", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Orthodoxy (Self-adm. quest.) - scaled", filecode = "338", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Praying", filecode = "038", waves = c("C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Religious coping", filecode = "105", waves = c("3B", "MB"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Salience of religion", filecode = "038", waves = c("C", "D", "E", "2B"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Salience of religion", filecode = "110", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Salience of religion - scaled", filecode = "238", waves = c("C", "D", "E", "2B"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Salience of religion - tel. proxy", filecode = "608", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Religiousness", topic = "Salience of religion - tel. respondent", filecode = "708", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Sexuality", topic = "Gender identity", filecode = "804", waves = c("J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Sexuality", topic = "Sexuality", filecode = "120", waves = c("B", "E", "2B", "F", "3B"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Singing and music", topic = "Singing and making music", filecode = "103", waves = c("H", "I", "J"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Sleep", topic = "Sleep quality", filecode = "117", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Sleep", topic = "Sleep quality - scaled", filecode = "317", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Stress and stressors", topic = "(Negative) life events", filecode = "272", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Stress and stressors", topic = "Perceived stress", filecode = "104", waves = c("H", "3B"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Stress and stressors", topic = "Perceived stress - scaled", filecode = "304", waves = c("H", "3B"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Subjective age", topic = "Age norms", filecode = "070", waves = c("B", "C", "D", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Subjective age", topic = "Attitude toward ageing", filecode = "071", waves = c("B", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Subjective age", topic = "Perceived discrimination", filecode = "169", waves = c("J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Subjective age", topic = "Subjective life expectancy/ subj. age", filecode = "094", waves = c("D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Worrying", topic = "Worrying", filecode = "136", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Emotional", subtheme = "Worrying", topic = "Worrying - scaled", filecode = "336", waves = c("E"), has_varinfo = TRUE)
## ---- Physical (126 rows) ----
add_topic(theme = "Physical", subtheme = "Blood pressure", topic = "Blood pressure/pulse - retests", filecode = "151", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "Anthropometry - Ankle, Knee and Pulse width", filecode = "185", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "Anthropometry - Calf measurement", filecode = "161", waves = c("I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "Anthropometry - Calf measurement", filecode = "171", waves = c("B", "D", "E", "2B", "F", "G", "H", "3B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "Anthropometry - Weight and height", filecode = "161", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "Bio-electrical impedance (BIA) (subsample)", filecode = "172", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "Birth weight", filecode = "134", waves = c("E", "2B", "3B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "DXA (LASA ancillary study) - Hip / lumbar spine scan", filecode = "o41", waves = c("C", "D"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "DXA (LASA ancillary study) - Whole body scan", filecode = "o42", waves = c("C", "D"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "Perceived body shape", filecode = "145", waves = c("F", "G", "3B", "MB"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "Perceived body shape - scaled", filecode = "345", waves = c("F", "G", "3B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "Weight and height:history and weight change", filecode = "160", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Body composition", topic = "Weight and height:history and weight change - tel. respondent", filecode = "714", waves = c("I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Allostatic Load (algorithm)", filecode = NA_character_, waves = c("C"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Aortic calcification (lateral radiographs)", filecode = "zo22", waves = c("C", "D"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Back pain", filecode = "182", waves = c("C", "D", "E"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Bedridden", filecode = "182", waves = c("C", "D", "F", "G", "H", "3B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Cardiovascular diseases (algorithm)", filecode = "zh01", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Decubitus (bedsores)", filecode = "116", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Decubitus (bedsores)", filecode = "159", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Diabetes mellitus (algorithm)", filecode = "zdc1", waves = c("B", "C", "D", "E", "F", "G", "H", "I"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Diabetes mellitus (algorithm)", filecode = "zdc2", waves = c("2B", "F", "G", "H", "I"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Diabetes mellitus (algorithm)", filecode = "zdc3", waves = c("3B", "I"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "GP information", filecode = "g01", waves = c("B", "C", "E", "2B", "H", "3B"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Hyperthyroidism", filecode = "182", waves = c("C", "D"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Intrinsic Capacity", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Metabolic syndrome", filecode = "ch02", waves = c("C"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Osteoarthritis hip and knee (algorithm) - cohort 1", filecode = "zoa1", waves = c("B", "C", "D", "E", "F", "G", "H", "I"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Osteoarthritis hip and knee (algorithm) - cohort 2", filecode = "zoa2", waves = c("2B", "F", "G", "H", "I"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Osteoarthritis hip and knee (algorithm) - cohort 3", filecode = "zoa3", waves = c("3B", "I"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Parkinson: early P. related signs", filecode = "096", waves = c("3B", "MB"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Rheumatoid Arthritis (algorithm)", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Self-report of chronic diseases", filecode = "035", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Self-report of chronic diseases - longitudinally cleaned", filecode = "435", waves = c("B", "C"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Self-report of chronic diseases - nr. of diseases reported", filecode = "235", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Self-report of chronic diseases - tel. proxy", filecode = "602", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Chronic diseases", topic = "Self-report of chronic diseases - tel. respondent", filecode = "702", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Dizziness", filecode = "187", waves = c("C", "D", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Falls", filecode = "187", waves = c("C", "D", "3B", "MB", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Falls - tel. proxy", filecode = "605", waves = c("C", "D"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Falls - tel. respondent", filecode = "705", waves = c("C", "D"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Falls: 1y prospective fall calendar (LASA ancillary study)", filecode = NA_character_, waves = c("G"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Falls: 3y prospective fall calendar (LASA ancillary study)", filecode = NA_character_, waves = c("C"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Falls: circumstances and consequences", filecode = "187", waves = c("D", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Falls: environmental conditions (home)", filecode = "180", waves = c("C", "D"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Falls: fear of falling (FES: Falls Efficacy Scale)", filecode = "183", waves = c("C", "D"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Falls: prevention of fall accidents (LASA ancillary study)", filecode = NA_character_, waves = c("D"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Foot problems", filecode = "185", waves = c("C", "D", "E", "F"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Falling", topic = "Walking aids", filecode = "187", waves = c("D", "E", "2B", "F", "G", "H", "3B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Fertility", topic = "Fertility (women)", filecode = "119", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Fertility", topic = "Fertility (women)", filecode = "181", waves = c("C", "2B", "3B", "MB"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Fractures", topic = "Fractures", filecode = "186", waves = c("C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Fractures", topic = "Fractures - tel. proxy", filecode = "605", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Fractures", topic = "Fractures - tel. respondent", filecode = "705", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Fractures", topic = "Fractures - total waves B-E", filecode = "ZFF1", waves = c("B", "C", "D", "E"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Fractures", topic = "Quantitative ultrasound of bone", filecode = "o31", waves = c("C", "G"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Fractures", topic = "Vertebral deformities", filecode = "zo22", waves = c("C", "D"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Frailty", topic = "Various definitions (e.g., frailty phenotype, frailty index)", filecode = NA_character_, waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Accelerometry (LASA ancillary studies) - subsample (St. 1) - subsample (St. 2) - subsample (St. 3) - subsample (St. 4)", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Alcohol use", filecode = "153", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Alcohol use - scaled", filecode = "353", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Coffee and tea consumption", filecode = "801", waves = c("J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Daily Physical Activity", filecode = "162", waves = c("J"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Diet and food consumption", filecode = "118", waves = c("B", "C", "D", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Diet and food consumption", filecode = "184", waves = c("C", "D"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Early life physical activity", filecode = "246", waves = c("C"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "MicMac study (LASA ancillary study)", filecode = NA_character_, waves = c("I"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Oral health", filecode = "126", waves = c("I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Oral health", filecode = NA_character_, waves = c("F"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Perceived physical activity (LIVAS)", filecode = "114", waves = c("B", "C", "D", "E", "2B", "F"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Perceived physical activity (LIVAS) - scaled", filecode = "314", waves = c("B", "C", "D", "E", "2B", "F"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Physical activity", filecode = "046", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Sedentary behavior", filecode = "101", waves = c("G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Sedentary behavior - longitudinally cleaned", filecode = "501", waves = c("G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Sedentary behavior - scaled", filecode = "301", waves = c("G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = FALSE)
add_topic(theme = "Physical", subtheme = "Lifestyle", topic = "Smoking", filecode = "154", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Medication/ supplements", topic = "Food supplement use", filecode = "174", waves = c("I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Medication/ supplements", topic = "Food supplement use - Vitamin D use included", filecode = "374", waves = c("I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Medication/ supplements", topic = "Medication and food supplement use", filecode = "152", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Medication/ supplements", topic = "Medication and food supplement use - types of medication", filecode = "352", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Pain", topic = "Dealing with pain", filecode = "188", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Pain", topic = "Pain drawing", filecode = "188", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Pain", topic = "Subjective pain", filecode = "115", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Pain", topic = "Subjective pain - scaled", filecode = "315", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Hearing", topic = "Hearing (self-report)", filecode = "031", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Hearing", topic = "Hearing (self-report) - tel. proxy", filecode = "604", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Hearing", topic = "Hearing (self-report) - tel. respondent", filecode = "704", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Hearing", topic = "Hearing (self-report) - total scores", filecode = "231", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Hearing", topic = "Hearing: SNT questionnaire", filecode = "194", waves = c("E", "F", "G", "I"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Hearing", topic = "Hearing: SNT technical measures", filecode = "193", waves = c("E", "F", "G", "I"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: smell", topic = "Olfactory function", filecode = "S00", waves = c("3B", "MB"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: smell", topic = "Olfactory function", filecode = "S01", waves = c("3B", "MB"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: smell", topic = "Olfactory function", filecode = "S02", waves = c("3B", "MB"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Vision", topic = "Vision (self-report)", filecode = "031", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Vision", topic = "Vision (self-report) - tel. proxy", filecode = "604", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Vision", topic = "Vision (self-report) - tel. respondent", filecode = "704", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Vision", topic = "Vision (self-report) - total scores", filecode = "231", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Vision", topic = "Vision: contrast sensitivity", filecode = "157", waves = c("B", "C", "D", "E", "2B", "F"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Vision", topic = "Visual acuity test", filecode = "191", waves = c("E", "F", "G", "H", "3B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Perception: Vision", topic = "Visual acuity test - Vision-related quality of life", filecode = "192", waves = c("E", "F", "G", "H"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Funct. limitations (ADL)", filecode = "030", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Funct. limitations (ADL) - constructed (sum scores)", filecode = "230", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Funct. limitations (ADL) - limitations in joint mobility (medical interview)", filecode = "183", waves = c("C", "D", "E"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Funct. limitations (ADL) - tel. proxy", filecode = "603", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Funct. limitations (ADL) - tel. respondent", filecode = "703", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Global Activity Limitations", filecode = "033", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Global Activity Limitations - tel. respondent", filecode = "703", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Grip strength", filecode = "161", waves = c("C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Partner relationship", filecode = "139", waves = c("E", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Peak Flow", filecode = "158", waves = c("B", "C", "D", "E", "G", "H"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Physical performance", filecode = "034", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Physical functioning", topic = "Spirometry (post bronchodilator)", filecode = "168", waves = c("3B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "EuroQol", filecode = "135", waves = c("E", "F", "G", "H", "3B", "I"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "EuroQol - scaled", filecode = "335", waves = c("E", "F", "G", "H", "3B", "I"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "Qualeffo-41", filecode = "o80", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "Qualeffo-41 - (non)response", filecode = "o81", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "Qualeffo-41 - Qualeffo scores", filecode = "o82", waves = c("E"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "Self-rated health", filecode = "036", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "Self-rated health - GHPQ", filecode = "113", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "Self-rated health - GHPQ: scaled", filecode = "313", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "Self-rated health - tel. proxy", filecode = "602", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "Self-rated health - tel. respondent", filecode = "702", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "SF-12 Health Survey", filecode = "133", waves = c("D", "E", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "SF-12 Health Survey - scaled", filecode = "333", waves = c("D", "E", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "SF-12 Health Survey - scaled (Am.)", filecode = "533", waves = c("D", "E", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Physical", subtheme = "Quality of life", topic = "WHO Quality of Life", filecode = "133", waves = c("I", "J", "K"), has_varinfo = TRUE)
## ---- Social (44 rows) ----
add_topic(theme = "Social", subtheme = "Affiliation", topic = "Need for affiliation", filecode = "078", waves = c("B", "E"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Affiliation", topic = "Need for affiliation", filecode = "141", waves = c("2B", "G"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Affiliation", topic = "Need for affiliation - scaled", filecode = "278", waves = c("B", "E"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Affiliation", topic = "Need for affiliation - scaled", filecode = "341", waves = c("2B", "G"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "House ownership", filecode = "015", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Housing characteristics - tel. proxy", filecode = "601", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Housing characteristics - tel. respondent", filecode = "701", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Housing characteristics and adaptations", filecode = "014", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Neighborhood characteristics", filecode = "015", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Neighborhood characteristics", filecode = "095", waves = c("K"), has_varinfo = FALSE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Neighborhood characteristics", filecode = "z095", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Neighborhood problems", filecode = "170", waves = c("J", "K"), has_varinfo = FALSE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Pets in household", filecode = "012", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Relocation", filecode = "014", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Relocation", filecode = "015", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Relocation - tel. proxy", filecode = "601", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Relocation - tel. respondent", filecode = "701", waves = c("C", "D", "E", "F", "G", "H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Housing", topic = "Residence in 1944", filecode = "013", waves = c("B"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Loneliness", topic = "Existential loneliness", filecode = "173", waves = c("J"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Loneliness", topic = "Loneliness", filecode = "073", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Loneliness", topic = "Loneliness - scaled", filecode = "273", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Loneliness", topic = "Loneliness - tel. respondent", filecode = "712", waves = c("H", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Partner relationship", topic = "Relationship quality", filecode = "139", waves = c("E", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Relationships between generations", topic = "Children", filecode = "048", waves = c("C", "E", "2B", "F", "3B", "MB", "I"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Relationships between generations", topic = "Children", filecode = "248", waves = c("E", "2B", "F", "3B", "MB"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Relationships between generations", topic = "Filial responsibility expectations", filecode = "132", waves = c("D", "E", "J"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Relationships between generations", topic = "Filial responsibility expectations - scaled", filecode = "332", waves = c("D", "E", "J"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Relationships between generations", topic = "Grandchildren", filecode = "049", waves = c("F"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Relationships between generations", topic = "Parental data", filecode = "140", waves = c("2B", "3B"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Relationships between generations", topic = "Vignettes about help", filecode = "074", waves = c("D"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Relationships between generations", topic = "Vignettes about help - total scores", filecode = "274", waves = c("D"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social network", topic = "Contact network", filecode = "167", waves = c("3B", "MB", "I"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social network", topic = "Personal network", filecode = "047", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social network", topic = "Personal network - network size", filecode = "247", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social norms", topic = "Donorship", filecode = "128", waves = c("I", "J"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social norms", topic = "Social desirability", filecode = "130", waves = c("C", "F"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social norms", topic = "Social desirability - scaled", filecode = "330", waves = c("C", "F"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social norms", topic = "Social identity", filecode = "131", waves = c("D", "E"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social norms", topic = "Social identity - scaled", filecode = "331", waves = c("D", "E"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social norms", topic = "Ties with country of origin", filecode = "069", waves = c("MB"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social norms", topic = "Values and norms", filecode = "122", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social participation", topic = "Environmental influence", filecode = "121", waves = c("B", "C", "D"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social participation", topic = "Social participation", filecode = "070", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Social", subtheme = "Social participation", topic = "Social participation", filecode = "125", waves = c("B", "C", "D", "E", "2B", "F", "G"), has_varinfo = TRUE)
## ---- Work (5 rows) ----
add_topic(theme = "Work", subtheme = NA_character_, topic = "General Population Job ExposureMatrix (GPJEM)", filecode = "016", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Work", subtheme = NA_character_, topic = "Perception of work conditions", filecode = "106", waves = c("3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Work", subtheme = NA_character_, topic = "Work (Employment) and Retirement", filecode = "016", waves = c("B", "C", "D", "E", "2B", "F", "G", "H", "3B", "MB", "I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Work", subtheme = NA_character_, topic = "Work (Employment) and Retirement - tel. respondent*", filecode = "713", waves = c("I", "J", "K"), has_varinfo = TRUE)
add_topic(theme = "Work", subtheme = NA_character_, topic = "Work and Retirement characteristics", filecode = NA_character_, waves = NA_character_, has_varinfo = FALSE)

problems <- .lasa_validate_topic_database(lasa_topic_database)
if (length(problems) > 0L) {
  stop(
    "The LASA topic database failed validation:\n- ",
    paste(problems, collapse = "\n- "),
    call. = FALSE
  )
}

cat("\nBuild summary:\n",
  " topics:   ", nrow(lasa_topic_database), "\n",
  " with a file code:  ", sum(!is.na(lasa_topic_database$filecode)), "\n",
  " with a varinfo PDF:", sum(lasa_topic_database$has_varinfo), "\n"
)

usethis::use_data(lasa_topic_database, internal = TRUE, overwrite = TRUE)
cat("\nWrote R/sysdata.rda\n")

