## LASA filecode 706 -- variable names, variable labels, value labels,
## and variable types. Sourced after data-raw/label_db_helpers.R.
##
## To add a wave: add its documented variables to variable_labels_list
## and (if it has value labels) value_labels_list below. To add a new
## variable: add it to harmonized_labels/standardized_value_labels/
## var_types_vec and to the wave(s) that document it.

harmonized_labels <- c(
  trcedep = "Telephone interview: depressive affect",
  trces01 = "1. Last week: bothered",
  trces02 = "2. Last week: appetite",
  trces03 = "3. Last week: blues",
  trces04 = "4. Last week: good: positive",
  trces05 = "5. Last week: mind",
  trces06 = "6. Last week: depressed",
  trces07 = "7. Last week: effort",
  trces08 = "8. Last week: hopeful: positive",
  trces09 = "9. Last week: failure",
  trces10 = "10. Last week: fearful",
  trces11 = "11. Last week: sleep",
  trces12 = "12. Last week: happy: positive",
  trces13 = "13. Last week: talk",
  trces14 = "14. Last week: lonely",
  trces15 = "15. Last week: unfriendly",
  trces16 = "16. Last week: enjoy: positive",
  trces17 = "17. Last week: cry",
  trces18 = "18. Last week: sad",
  trces19 = "19. Last week: dislike",
  trces20 = "20. Last week: get going"
)

variable_labels_list <- list(
  Wave_C_labels = .replace_labels(
    harmonized_labels[c("trcedep", "trces01", "trces06", "trces10", "trces14")],
    trcedep = "Telephone interview: depressive affect low-high"
  ),
  Wave_D_labels = harmonized_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_E_labels = harmonized_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_F_labels = harmonized_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_G_labels = harmonized_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_H_labels = harmonized_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_I_labels = harmonized_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_J_labels = harmonized_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_K_labels = harmonized_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Harmonized_labels = harmonized_labels
)

standardized_value_labels <- list(
  trcedep = c(`-1` = "missing values"),
  trces01 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces02 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces03 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces04 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces05 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces06 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces07 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces08 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces09 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces10 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces11 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces12 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces13 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces14 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces15 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces16 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces17 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces18 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces19 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  ),
  trces20 = c(
    `-1` = "asked, no answer",
    `0` = "rarely or never",
    `1` = "some of the time",
    `2` = "occasionally",
    `3` = "mostly or always"
  )
)

value_labels_list <- list(
  Wave_C_labels = standardized_value_labels[c("trcedep", "trces01", "trces06", "trces10", "trces14")],
  Wave_D_labels = standardized_value_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_E_labels = standardized_value_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_F_labels = standardized_value_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_G_labels = standardized_value_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_H_labels = standardized_value_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_I_labels = standardized_value_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_J_labels = standardized_value_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Wave_K_labels = standardized_value_labels[c(
    "trces01",
    "trces02",
    "trces03",
    "trces04",
    "trces05",
    "trces06",
    "trces07",
    "trces08",
    "trces09",
    "trces10",
    "trces11",
    "trces12",
    "trces13",
    "trces14",
    "trces15",
    "trces16",
    "trces17",
    "trces18",
    "trces19",
    "trces20"
  )],
  Harmonized_labels = standardized_value_labels
)

var_types_vec <- c(
  trcedep = "numeric",
  trces01 = "categorical",
  trces02 = "categorical",
  trces03 = "categorical",
  trces04 = "categorical",
  trces05 = "categorical",
  trces06 = "categorical",
  trces07 = "categorical",
  trces08 = "categorical",
  trces09 = "categorical",
  trces10 = "categorical",
  trces11 = "categorical",
  trces12 = "categorical",
  trces13 = "categorical",
  trces14 = "categorical",
  trces15 = "categorical",
  trces16 = "categorical",
  trces17 = "categorical",
  trces18 = "categorical",
  trces19 = "categorical",
  trces20 = "categorical"
)

.lasa_fc_706 <- list(
  variables = .lasa_build_name_table(variable_labels_list, filecode = "706", waves = .lasa_wave_rows()),
  variable_labels = .lasa_build_label_table(variable_labels_list, filecode = "706", waves = .lasa_wave_rows()),
  value_labels = .lasa_build_value_table(value_labels_list, filecode = "706", waves = .lasa_wave_rows()),
  variable_types = .lasa_build_type_table(var_types_vec, filecode = "706", waves = .lasa_wave_rows())
)
