## LASA filecode 703 -- variable names, variable labels, value labels,
## and variable types. Sourced after data-raw/label_db_helpers.R.
##
## To add a wave: add its documented variables to variable_labels_list
## and (if it has value labels) value_labels_list below. To add a new
## variable: add it to harmonized_labels/standardized_value_labels/
## var_types_vec and to the wave(s) that document it.

harmonized_labels <- c(
  tradl1a = "Stairs: 15 steps without stopping",
  tradl2a = "(Un)dress: self",
  tradl3a = "Chair: sit and rise from",
  tradl4a = "Toenails: cutting own",
  tradl5a = "Walking: 5 min. outside the house",
  tradl6a = "Transport: use of own or public",
  tradl7a = "Take a bath/shower: using aid",
  trerh = "Visited emergency room hospital past 6 months",
  `trflwd#6` = "Functional limitations, with difficulty #6",
  `trflwd#7` = "Functional limitations, with difficulty #7",
  trflwdiff = "Functional limitations, with difficulty #3",
  trhea01 = "Administrative help R: partner",
  trhea02 = "Administrative help R: resident child",
  trhea02a = "Administrative help R: resident child",
  trhea02b = "Administrative help R: resident child-in-law",
  trhea03 = "Administrative help R: resident other",
  trhea04 = "Administrative help R: non-resident child",
  trhea04a = "Administrative help R: non-resident child",
  trhea04b = "Administrative help R: non-resident child-in-law",
  trhea05 = "Administrative help R: non-resident other family",
  trhea06 = "Administrative help R: neighbours/friends/acquaintances",
  trhea06a = "Administrative help R: neighbours",
  trhea06b = "Administrative help R: friends/acquaintances",
  trhea07 = "Administrative help R: volunteers",
  trhea08 = "Administrative help R: district nurse",
  trhea09 = "Administrative help R: professional home care",
  trhea10 = "Administrative help R: private",
  trhea11 = "Administrative help R: personnel home/hospital",
  trhea12 = "Administrative help R: other",
  trheal1 = "Health problems limit normal activities",
  trheal2 = "How long limitations",
  trheayn = "Help R with administration Y/N",
  trhed01 = "Domestic help R: partner",
  trhed02 = "Domestic help R: resident child",
  trhed02a = "Domestic help R: resident child",
  trhed02b = "Domestic help R: resident child-in-law",
  trhed03 = "Domestic help R: resident other",
  trhed04 = "Domestic help R: non-resident child",
  trhed04a = "Domestic help R: non-resident child",
  trhed04b = "Domestic help R: non-resident child-in-law",
  trhed05 = "Domestic help R: non-resident other family",
  trhed06 = "Domestic help R: neighbours/friends/acquaintances",
  trhed06a = "Domestic help R: neighbours",
  trhed06b = "Domestic help R: friends/acquaintances",
  trhed07 = "Domestic help R: volunteers",
  trhed08 = "Domestic help R: district nurse",
  trhed09 = "Domestic help R: professional home care",
  trhed10 = "Domestic help R: private",
  trhed11 = "Domestic help R: personnel home/hospital",
  trhed12 = "Domestic help R: other",
  trhedyn = "Help R with domestic tasks Y/N",
  trheg01 = "Guidance help R: partner",
  trheg02 = "Guidance help R: resident child",
  trheg02a = "Guidance help R: resident child",
  trheg02b = "Guidance help R: resident child-in-law",
  trheg03 = "Guidance help R: resident other",
  trheg04 = "Guidance help R: non-resident child",
  trheg04a = "Guidance help R: non-resident child",
  trheg04b = "Guidance help R: non-resident child-in-law",
  trheg05 = "Guidance help R: non-resident other family",
  trheg06 = "Guidance help R: neighbours/friends/acquaintances",
  trheg06a = "Guidance help R: neighbours",
  trheg06b = "Guidance help R: friends/acquaintances",
  trheg07 = "Guidance help R: volunteers",
  trheg08 = "Guidance help R: district nurse",
  trheg09 = "Guidance help R: professional home care",
  trheg10 = "Guidance help R: private",
  trheg11 = "Guidance help R: personnel home/hospital",
  trheg12 = "Guidance help R: other",
  trhegyn = "Help R with guidance Y/N",
  trhen01 = "Nursing help R: partner",
  trhen02 = "Nursing help R: resident child",
  trhen02a = "Nursing help R: resident child",
  trhen02b = "Nursing help R: resident child-in-law",
  trhen03 = "Nursing help R: resident other",
  trhen04 = "Nursing help R: non-resident child",
  trhen04a = "Nursing help R: non-resident child",
  trhen04b = "Nursing help R: non-resident child-in-law",
  trhen05 = "Nursing help R: non-resident other family",
  trhen06 = "Nursing help R: neighbours/friends/acquaintances",
  trhen06a = "Nursing help R: neighbours",
  trhen06b = "Nursing help R: friends/acquaintances",
  trhen07 = "Nursing help R: volunteers",
  trhen08 = "Nursing help R: district nurse",
  trhen09 = "Nursing help R: professional home care",
  trhen10 = "Nursing help R: private",
  trhen11 = "Nursing help R: personnel home/hospital",
  trhen12 = "Nursing help R: other",
  trhenyn = "Help R with nursing tasks Y/N",
  trhep01 = "Personal help R: partner",
  trhep02 = "Personal help R: resident child",
  trhep02a = "Personal help R: resident child",
  trhep02b = "Personal help R: resident child-in-law",
  trhep03 = "Personal help R: resident other",
  trhep04 = "Personal help R: non-resident child",
  trhep04a = "Personal help R: non-resident child",
  trhep04b = "Personal help R: non-resident child-in-law",
  trhep05 = "Personal help R: non-resident other family",
  trhep06 = "Personal help R: neighbours/friends/acquaintances",
  trhep06a = "Personal help R: neighbours",
  trhep06b = "Personal help R: friends/acquaintances",
  trhep07 = "Personal help R: volunteers",
  trhep08 = "Personal help R: district nurse",
  trhep09 = "Personal help R: professional home care",
  trhep10 = "Personal help R: private",
  trhep11 = "Personal help R: personnel home/hospital",
  trhep12 = "Personal help R: other",
  trhepyn = "Help R with personal care Y/N",
  trhosp = "Hospitalization past 6 months",
  trmeds = "Contact with medical specialist past 6 months",
  trpha1 = "Physical condition respondent",
  trpsyc = "Contact with psychiatrist past 6 months",
  trpsyh = "Psychiatric hospitalization past 6 months",
  trstic1 = "Contact with family physician past 6 months",
  trsuffic = "Respondent gets sufficient help"
)

variable_labels_list <- list(
  Wave_C_labels = .replace_labels(
    harmonized_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    `trflwd#6` = "functional limitations, with difficulty #6",
    trflwdiff = "functional limitations, with difficulty #3"
  ),
  Wave_D_labels = .replace_labels(
    harmonized_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trheal1",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    `trflwd#6` = "functional limitations, with difficulty #6",
    trflwdiff = "functional limitations, with difficulty #3"
  ),
  Wave_E_labels = .replace_labels(
    harmonized_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trheal1",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    `trflwd#6` = "functional limitations, with difficulty #6",
    trflwdiff = "functional limitations, with difficulty #3"
  ),
  Wave_F_labels = .replace_labels(
    harmonized_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trheal1",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    `trflwd#6` = "functional limitations, with difficulty #6",
    trflwdiff = "functional limitations, with difficulty #3"
  ),
  Wave_G_labels = .replace_labels(
    harmonized_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trheal1",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    `trflwd#6` = "functional limitations, with difficulty #6",
    trflwdiff = "functional limitations, with difficulty #3"
  ),
  Wave_H_labels = .replace_labels(
    harmonized_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trhea01",
    "trhea02",
    "trhea03",
    "trhea04",
    "trhea05",
    "trhea06",
    "trhea07",
    "trhea08",
    "trhea09",
    "trhea10",
    "trhea11",
    "trhea12",
    "trheal1",
    "trheayn",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trheg01",
    "trheg02",
    "trheg03",
    "trheg04",
    "trheg05",
    "trheg06",
    "trheg07",
    "trheg08",
    "trheg09",
    "trheg10",
    "trheg11",
    "trheg12",
    "trhegyn",
    "trhen01",
    "trhen02",
    "trhen03",
    "trhen04",
    "trhen05",
    "trhen06",
    "trhen07",
    "trhen08",
    "trhen09",
    "trhen10",
    "trhen11",
    "trhen12",
    "trhenyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    `trflwd#6` = "functional limitations, with difficulty #6",
    trflwdiff = "functional limitations, with difficulty #3"
  ),
  Wave_I_labels = .replace_labels(
    harmonized_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trhea01",
    "trhea02",
    "trhea03",
    "trhea04",
    "trhea05",
    "trhea06",
    "trhea07",
    "trhea08",
    "trhea09",
    "trhea10",
    "trhea11",
    "trhea12",
    "trheal1",
    "trheayn",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trheg01",
    "trheg02",
    "trheg03",
    "trheg04",
    "trheg05",
    "trheg06",
    "trheg07",
    "trheg08",
    "trheg09",
    "trheg10",
    "trheg11",
    "trheg12",
    "trhegyn",
    "trhen01",
    "trhen02",
    "trhen03",
    "trhen04",
    "trhen05",
    "trhen06",
    "trhen07",
    "trhen08",
    "trhen09",
    "trhen10",
    "trhen11",
    "trhen12",
    "trhenyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    `trflwd#6` = "functional limitations, with difficulty #6",
    trflwdiff = "functional limitations, with difficulty #3"
  ),
  Wave_J_labels = .replace_labels(
    harmonized_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trerh",
    "trflwd#6",
    "trflwdiff",
    "trhea01",
    "trhea02a",
    "trhea02b",
    "trhea03",
    "trhea04a",
    "trhea04b",
    "trhea05",
    "trhea06a",
    "trhea06b",
    "trhea07",
    "trhea08",
    "trhea09",
    "trhea10",
    "trhea11",
    "trhea12",
    "trheal1",
    "trheal2",
    "trheayn",
    "trhed01",
    "trhed02a",
    "trhed02b",
    "trhed03",
    "trhed04a",
    "trhed04b",
    "trhed05",
    "trhed06a",
    "trhed06b",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trheg01",
    "trheg02a",
    "trheg02b",
    "trheg03",
    "trheg04a",
    "trheg04b",
    "trheg05",
    "trheg06a",
    "trheg06b",
    "trheg07",
    "trheg08",
    "trheg09",
    "trheg10",
    "trheg11",
    "trheg12",
    "trhegyn",
    "trhen01",
    "trhen02a",
    "trhen02b",
    "trhen03",
    "trhen04a",
    "trhen04b",
    "trhen05",
    "trhen06a",
    "trhen06b",
    "trhen07",
    "trhen08",
    "trhen09",
    "trhen10",
    "trhen11",
    "trhen12",
    "trhenyn",
    "trhep01",
    "trhep02a",
    "trhep02b",
    "trhep03",
    "trhep04a",
    "trhep04b",
    "trhep05",
    "trhep06a",
    "trhep06b",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    `trflwd#6` = "functional limitations, with difficulty #6",
    trflwdiff = "functional limitations, with difficulty #3",
    trmeds = "Contacted medical specialist past 6 months",
    trpsyc = "Contacted psychiatrist past 6 months"
  ),
  Wave_K_labels = .replace_labels(
    harmonized_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "tradl7a",
    "trerh",
    "trflwd#6",
    "trflwd#7",
    "trflwdiff",
    "trhea01",
    "trhea02a",
    "trhea02b",
    "trhea03",
    "trhea04a",
    "trhea04b",
    "trhea05",
    "trhea06a",
    "trhea06b",
    "trhea07",
    "trhea08",
    "trhea09",
    "trhea10",
    "trhea11",
    "trhea12",
    "trheal1",
    "trheal2",
    "trheayn",
    "trhed01",
    "trhed02a",
    "trhed02b",
    "trhed03",
    "trhed04a",
    "trhed04b",
    "trhed05",
    "trhed06a",
    "trhed06b",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trheg01",
    "trheg02a",
    "trheg02b",
    "trheg03",
    "trheg04a",
    "trheg04b",
    "trheg05",
    "trheg06a",
    "trheg06b",
    "trheg07",
    "trheg08",
    "trheg09",
    "trheg10",
    "trheg11",
    "trheg12",
    "trhegyn",
    "trhen01",
    "trhen02a",
    "trhen02b",
    "trhen03",
    "trhen04a",
    "trhen04b",
    "trhen05",
    "trhen06a",
    "trhen06b",
    "trhen07",
    "trhen08",
    "trhen09",
    "trhen10",
    "trhen11",
    "trhen12",
    "trhenyn",
    "trhep01",
    "trhep02a",
    "trhep02b",
    "trhep03",
    "trhep04a",
    "trhep04b",
    "trhep05",
    "trhep06a",
    "trhep06b",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1",
    "trsuffic"
  )],
    `trflwd#6` = "functional limitations, with difficulty #6",
    `trflwd#7` = "functional limitations, with difficulty #7",
    trflwdiff = "functional limitations, with difficulty #3",
    trmeds = "Contacted medical specialist past 6 months",
    trpsyc = "Contacted psychiatrist past 6 months"
  ),
  Harmonized_labels = harmonized_labels
)

standardized_value_labels <- list(
  tradl1a = c(
    `-2` = "na, see TRPHA1",
    `-1` = "not available after question asked",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
  tradl2a = c(
    `-2` = "na, see TRPHA1",
    `-1` = "not available after question asked",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
  tradl3a = c(
    `-2` = "na, see TRPHA1",
    `-1` = "not available after question asked",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
  tradl4a = c(
    `-2` = "na, see TRPHA1",
    `-1` = "not available after question asked",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
  tradl5a = c(
    `-2` = "na, see TRPHA1",
    `-1` = "not available after question asked",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
  tradl6a = c(
    `-2` = "na, see TRPHA1",
    `-1` = "not available after question asked",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
  tradl7a = c(
    `-2` = "na, see TRPHA1",
    `-1` = "not available after question asked",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
  trerh = c(`-1` = "na, asked / does not know", `1` = "no", `2` = "yes"),
  `trflwd#6` = c(
    `-2` = "na, see TRPHA1",
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "5 without difficulty",
    `2` = "4 without difficulty",
    `3` = "3 without difficulty",
    `4` = "2 without difficulty",
    `5` = "1 without difficulty",
    `6` = "all with difficulty"
  ),
  `trflwd#7` = c(
    `-2` = "na, see TRPHA1",
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "6 without difficulty",
    `2` = "5 without difficulty",
    `3` = "4 without difficulty",
    `4` = "3 without difficulty",
    `5` = "2 without difficulty",
    `6` = "1 without difficulty",
    `7` = "all with difficulty"
  ),
  trflwdiff = c(
    `-2` = "na, see TRPHA1",
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "2 without difficulty",
    `2` = "1 without difficulty",
    `3` = "all with difficulty"
  ),
  trhea01 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea02 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea02a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea02b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea03 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea04 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea04a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea04b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea05 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea06 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea06a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea06b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea07 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea08 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea09 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea10 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea11 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhea12 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheal1 = c(
    `-1` = "asked, no answer",
    `1` = "no",
    `2` = "yes, severely",
    `3` = "yes, slightly",
    `4` = "R does not know / refused to answer"
  ),
  trheal2 = c(
    `-2` = "na, see TRHEAL1",
    `-1` = "asked, no answer",
    `1` = "> 3 months",
    `2` = "< 3 months",
    `3` = "R does not know / refused to answer"
  ),
  trheayn = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes"),
  trhed01 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed02 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed02a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed02b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed03 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed04 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed04a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed04b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed05 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed06 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed06a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed06b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed07 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed08 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed09 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed10 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed11 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhed12 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhedyn = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes"),
  trheg01 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg02 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg02a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg02b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg03 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg04 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg04a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg04b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg05 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg06 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg06a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg06b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg07 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg08 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg09 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg10 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg11 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trheg12 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhegyn = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes"),
  trhen01 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen02 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen02a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen02b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen03 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen04 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen04a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen04b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen05 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen06 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen06a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen06b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen07 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen08 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen09 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen10 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen11 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhen12 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhenyn = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes"),
  trhep01 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep02 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep02a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep02b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep03 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep04 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep04a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep04b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep05 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep06 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep06a = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep06b = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep07 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep08 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep09 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep10 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep11 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhep12 = c(`-2` = "no help", `-1` = "asked, no answer", `0` = "not mentioned", `1` = "mentioned"),
  trhepyn = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes"),
  trhosp = c(`-1` = "not available after question asked", `1` = "no", `2` = "yes"),
  trmeds = c(`-1` = "not available after question asked", `1` = "no", `2` = "yes"),
  trpha1 = c(
    `-1` = "asked, no answer",
    `1` = "respondent bedridden",
    `2` = "R in wheelchair",
    `3` = "R with walking aid",
    `4` = "not 1, 2 or 3"
  ),
  trpsyc = c(`-1` = "not available after question asked", `1` = "no", `2` = "yes"),
  trpsyh = c(`-1` = "not available after question asked", `1` = "no", `2` = "yes"),
  trstic1 = c(`-1` = "not available after question asked", `1` = "no", `2` = "yes"),
  trsuffic = c(
    `-1` = "asked, no answer",
    `1` = "insufficient",
    `2` = "in between insufficient/sufficient",
    `3` = "sufficient"
  )
)

value_labels_list <- list(
  Wave_C_labels = .replace_in_list(
    standardized_value_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    tradl1a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl2a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl3a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl4a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl5a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl6a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    `trflwd#6` = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "5 without difficulty",
    `2` = "4 without difficulty",
    `3` = "3 without difficulty",
    `4` = "2 without difficulty",
    `5` = "1 without difficulty",
    `6` = "all with difficulty"
  ),
    trflwdiff = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "2 without difficulty",
    `2` = "1 without difficulty",
    `3` = "all with difficulty"
  ),
    trhosp = .replace_labels(
    standardized_value_labels$trhosp,
    `-1` = "asked, no answer"
  ),
    trmeds = .replace_labels(
    standardized_value_labels$trmeds,
    `-1` = "asked, no answer"
  ),
    trpha1 = .replace_labels(
    standardized_value_labels$trpha1,
    `1` = "R bedridden"
  ),
    trpsyc = .replace_labels(
    standardized_value_labels$trpsyc,
    `-1` = "asked, no answer"
  ),
    trpsyh = .replace_labels(
    standardized_value_labels$trpsyh,
    `-1` = "asked, no answer"
  ),
    trstic1 = .replace_labels(
    standardized_value_labels$trstic1,
    `-1` = "asked, no answer"
  )
  ),
  Wave_D_labels = .replace_in_list(
    standardized_value_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trheal1",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    tradl1a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl2a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl3a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl4a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl5a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl6a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    `trflwd#6` = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "5 without difficulty",
    `2` = "4 without difficulty",
    `3` = "3 without difficulty",
    `4` = "2 without difficulty",
    `5` = "1 without difficulty",
    `6` = "all with difficulty"
  ),
    trflwdiff = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "2 without difficulty",
    `2` = "1 without difficulty",
    `3` = "all with difficulty"
  ),
    trheal1 = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes, severely", `3` = "yes, slightly"),
    trhosp = .replace_labels(
    standardized_value_labels$trhosp,
    `-1` = "asked, no answer"
  ),
    trmeds = .replace_labels(
    standardized_value_labels$trmeds,
    `-1` = "asked, no answer"
  ),
    trpha1 = .replace_labels(
    standardized_value_labels$trpha1,
    `1` = "R bedridden"
  ),
    trpsyc = .replace_labels(
    standardized_value_labels$trpsyc,
    `-1` = "asked, no answer"
  ),
    trpsyh = .replace_labels(
    standardized_value_labels$trpsyh,
    `-1` = "asked, no answer"
  ),
    trstic1 = .replace_labels(
    standardized_value_labels$trstic1,
    `-1` = "asked, no answer"
  )
  ),
  Wave_E_labels = .replace_in_list(
    standardized_value_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trheal1",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    tradl1a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl2a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl3a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl4a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl5a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl6a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    `trflwd#6` = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "5 without difficulty",
    `2` = "4 without difficulty",
    `3` = "3 without difficulty",
    `4` = "2 without difficulty",
    `5` = "1 without difficulty",
    `6` = "all with difficulty"
  ),
    trflwdiff = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "2 without difficulty",
    `2` = "1 without difficulty",
    `3` = "all with difficulty"
  ),
    trheal1 = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes, severely", `3` = "yes, slightly"),
    trhosp = .replace_labels(
    standardized_value_labels$trhosp,
    `-1` = "asked, no answer"
  ),
    trmeds = .replace_labels(
    standardized_value_labels$trmeds,
    `-1` = "asked, no answer"
  ),
    trpha1 = .replace_labels(
    standardized_value_labels$trpha1,
    `1` = "R bedridden"
  ),
    trpsyc = .replace_labels(
    standardized_value_labels$trpsyc,
    `-1` = "asked, no answer"
  ),
    trpsyh = .replace_labels(
    standardized_value_labels$trpsyh,
    `-1` = "asked, no answer"
  ),
    trstic1 = .replace_labels(
    standardized_value_labels$trstic1,
    `-1` = "asked, no answer"
  )
  ),
  Wave_F_labels = .replace_in_list(
    standardized_value_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trheal1",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    tradl1a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl2a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl3a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl4a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl5a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl6a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    `trflwd#6` = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "5 without difficulty",
    `2` = "4 without difficulty",
    `3` = "3 without difficulty",
    `4` = "2 without difficulty",
    `5` = "1 without difficulty",
    `6` = "all with difficulty"
  ),
    trflwdiff = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "2 without difficulty",
    `2` = "1 without difficulty",
    `3` = "all with difficulty"
  ),
    trheal1 = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes, severely", `3` = "yes, slightly"),
    trhosp = .replace_labels(
    standardized_value_labels$trhosp,
    `-1` = "asked, no answer"
  ),
    trmeds = .replace_labels(
    standardized_value_labels$trmeds,
    `-1` = "asked, no answer"
  ),
    trpha1 = .replace_labels(
    standardized_value_labels$trpha1,
    `1` = "R bedridden"
  ),
    trpsyc = .replace_labels(
    standardized_value_labels$trpsyc,
    `-1` = "asked, no answer"
  ),
    trpsyh = .replace_labels(
    standardized_value_labels$trpsyh,
    `-1` = "asked, no answer"
  ),
    trstic1 = .replace_labels(
    standardized_value_labels$trstic1,
    `-1` = "asked, no answer"
  )
  ),
  Wave_G_labels = .replace_in_list(
    standardized_value_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trheal1",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    tradl1a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl2a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl3a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl4a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl5a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl6a = c(
    `-1` = "asked, no answer",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    `trflwd#6` = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "5 without difficulty",
    `2` = "4 without difficulty",
    `3` = "3 without difficulty",
    `4` = "2 without difficulty",
    `5` = "1 without difficulty",
    `6` = "all with difficulty"
  ),
    trflwdiff = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "2 without difficulty",
    `2` = "1 without difficulty",
    `3` = "all with difficulty"
  ),
    trheal1 = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes, severely", `3` = "yes, slightly"),
    trhosp = .replace_labels(
    standardized_value_labels$trhosp,
    `-1` = "asked, no answer"
  ),
    trmeds = .replace_labels(
    standardized_value_labels$trmeds,
    `-1` = "asked, no answer"
  ),
    trpha1 = .replace_labels(
    standardized_value_labels$trpha1,
    `1` = "R bedridden"
  ),
    trpsyc = .replace_labels(
    standardized_value_labels$trpsyc,
    `-1` = "asked, no answer"
  ),
    trpsyh = .replace_labels(
    standardized_value_labels$trpsyh,
    `-1` = "asked, no answer"
  ),
    trstic1 = .replace_labels(
    standardized_value_labels$trstic1,
    `-1` = "asked, no answer"
  )
  ),
  Wave_H_labels = .replace_in_list(
    standardized_value_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trhea01",
    "trhea02",
    "trhea03",
    "trhea04",
    "trhea05",
    "trhea06",
    "trhea07",
    "trhea08",
    "trhea09",
    "trhea10",
    "trhea11",
    "trhea12",
    "trheal1",
    "trheayn",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trheg01",
    "trheg02",
    "trheg03",
    "trheg04",
    "trheg05",
    "trheg06",
    "trheg07",
    "trheg08",
    "trheg09",
    "trheg10",
    "trheg11",
    "trheg12",
    "trhegyn",
    "trhen01",
    "trhen02",
    "trhen03",
    "trhen04",
    "trhen05",
    "trhen06",
    "trhen07",
    "trhen08",
    "trhen09",
    "trhen10",
    "trhen11",
    "trhen12",
    "trhenyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    tradl1a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl2a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl3a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl4a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl5a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl6a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    `trflwd#6` = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "5 without difficulty",
    `2` = "4 without difficulty",
    `3` = "3 without difficulty",
    `4` = "2 without difficulty",
    `5` = "1 without difficulty",
    `6` = "all with difficulty"
  ),
    trflwdiff = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "2 without difficulty",
    `2` = "1 without difficulty",
    `3` = "all with difficulty"
  ),
    trheal1 = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes, severely", `3` = "yes, slightly"),
    trhosp = .replace_labels(
    standardized_value_labels$trhosp,
    `-1` = "na, asked / does not know"
  ),
    trmeds = .replace_labels(
    standardized_value_labels$trmeds,
    `-1` = "na, asked / does not know"
  ),
    trpsyc = .replace_labels(
    standardized_value_labels$trpsyc,
    `-1` = "na, asked / does not know"
  ),
    trpsyh = .replace_labels(
    standardized_value_labels$trpsyh,
    `-1` = "na, asked / does not know"
  ),
    trstic1 = .replace_labels(
    standardized_value_labels$trstic1,
    `-1` = "na, asked / does not know"
  )
  ),
  Wave_I_labels = .replace_in_list(
    standardized_value_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trflwd#6",
    "trflwdiff",
    "trhea01",
    "trhea02",
    "trhea03",
    "trhea04",
    "trhea05",
    "trhea06",
    "trhea07",
    "trhea08",
    "trhea09",
    "trhea10",
    "trhea11",
    "trhea12",
    "trheal1",
    "trheayn",
    "trhed01",
    "trhed02",
    "trhed03",
    "trhed04",
    "trhed05",
    "trhed06",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trheg01",
    "trheg02",
    "trheg03",
    "trheg04",
    "trheg05",
    "trheg06",
    "trheg07",
    "trheg08",
    "trheg09",
    "trheg10",
    "trheg11",
    "trheg12",
    "trhegyn",
    "trhen01",
    "trhen02",
    "trhen03",
    "trhen04",
    "trhen05",
    "trhen06",
    "trhen07",
    "trhen08",
    "trhen09",
    "trhen10",
    "trhen11",
    "trhen12",
    "trhenyn",
    "trhep01",
    "trhep02",
    "trhep03",
    "trhep04",
    "trhep05",
    "trhep06",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    tradl1a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl2a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl3a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl4a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl5a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    tradl6a = c(
    `-1` = "asked, no answer / does not know",
    `1` = "no, R cannot",
    `2` = "yes, without difficulty",
    `3` = "yes, with some difficulty",
    `4` = "yes, with much difficulty",
    `5` = "only with help"
  ),
    `trflwd#6` = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "5 without difficulty",
    `2` = "4 without difficulty",
    `3` = "3 without difficulty",
    `4` = "2 without difficulty",
    `5` = "1 without difficulty",
    `6` = "all with difficulty"
  ),
    trflwdiff = c(
    `-1` = "no valid data",
    `0` = "no difficulties",
    `1` = "2 without difficulty",
    `2` = "1 without difficulty",
    `3` = "all with difficulty"
  ),
    trheal1 = c(`-1` = "asked, no answer", `1` = "no", `2` = "yes, severely", `3` = "yes, slightly"),
    trhosp = .replace_labels(
    standardized_value_labels$trhosp,
    `-1` = "na, asked / does not know"
  ),
    trmeds = .replace_labels(
    standardized_value_labels$trmeds,
    `-1` = "na, asked / does not know"
  ),
    trpsyc = .replace_labels(
    standardized_value_labels$trpsyc,
    `-1` = "na, asked / does not know"
  ),
    trpsyh = .replace_labels(
    standardized_value_labels$trpsyh,
    `-1` = "na, asked / does not know"
  ),
    trstic1 = .replace_labels(
    standardized_value_labels$trstic1,
    `-1` = "na, asked / does not know"
  )
  ),
  Wave_J_labels = .replace_in_list(
    standardized_value_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "trerh",
    "trflwd#6",
    "trflwdiff",
    "trhea01",
    "trhea02a",
    "trhea02b",
    "trhea03",
    "trhea04a",
    "trhea04b",
    "trhea05",
    "trhea06a",
    "trhea06b",
    "trhea07",
    "trhea08",
    "trhea09",
    "trhea10",
    "trhea11",
    "trhea12",
    "trheal1",
    "trheal2",
    "trheayn",
    "trhed01",
    "trhed02a",
    "trhed02b",
    "trhed03",
    "trhed04a",
    "trhed04b",
    "trhed05",
    "trhed06a",
    "trhed06b",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trheg01",
    "trheg02a",
    "trheg02b",
    "trheg03",
    "trheg04a",
    "trheg04b",
    "trheg05",
    "trheg06a",
    "trheg06b",
    "trheg07",
    "trheg08",
    "trheg09",
    "trheg10",
    "trheg11",
    "trheg12",
    "trhegyn",
    "trhen01",
    "trhen02a",
    "trhen02b",
    "trhen03",
    "trhen04a",
    "trhen04b",
    "trhen05",
    "trhen06a",
    "trhen06b",
    "trhen07",
    "trhen08",
    "trhen09",
    "trhen10",
    "trhen11",
    "trhen12",
    "trhenyn",
    "trhep01",
    "trhep02a",
    "trhep02b",
    "trhep03",
    "trhep04a",
    "trhep04b",
    "trhep05",
    "trhep06a",
    "trhep06b",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1"
  )],
    tradl1a = .replace_labels(
    standardized_value_labels$tradl1a,
    `-2` = "na, see JTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl2a = .replace_labels(
    standardized_value_labels$tradl2a,
    `-2` = "na, see JTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl3a = .replace_labels(
    standardized_value_labels$tradl3a,
    `-2` = "na, see JTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl4a = .replace_labels(
    standardized_value_labels$tradl4a,
    `-2` = "na, see JTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl5a = .replace_labels(
    standardized_value_labels$tradl5a,
    `-2` = "na, see JTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl6a = .replace_labels(
    standardized_value_labels$tradl6a,
    `-2` = "na, see JTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    `trflwd#6` = .replace_labels(
    standardized_value_labels$`trflwd#6`,
    `-2` = "na, see JTRPHA1"
  ),
    trflwdiff = .replace_labels(
    standardized_value_labels$trflwdiff,
    `-2` = "na, see JTRPHA1"
  ),
    trheal2 = .replace_labels(
    standardized_value_labels$trheal2,
    `-2` = "na, see JTRHEAL1"
  ),
    trhosp = .replace_labels(
    standardized_value_labels$trhosp,
    `-1` = "na, asked / does not know"
  ),
    trmeds = .replace_labels(
    standardized_value_labels$trmeds,
    `-1` = "na, asked / does not know"
  ),
    trpsyc = .replace_labels(
    standardized_value_labels$trpsyc,
    `-1` = "na, asked / does not know"
  ),
    trpsyh = .replace_labels(
    standardized_value_labels$trpsyh,
    `-1` = "na, asked / does not know"
  ),
    trstic1 = .replace_labels(
    standardized_value_labels$trstic1,
    `-1` = "na, asked / does not know"
  )
  ),
  Wave_K_labels = .replace_in_list(
    standardized_value_labels[c(
    "tradl1a",
    "tradl2a",
    "tradl3a",
    "tradl4a",
    "tradl5a",
    "tradl6a",
    "tradl7a",
    "trerh",
    "trflwd#6",
    "trflwd#7",
    "trflwdiff",
    "trhea01",
    "trhea02a",
    "trhea02b",
    "trhea03",
    "trhea04a",
    "trhea04b",
    "trhea05",
    "trhea06a",
    "trhea06b",
    "trhea07",
    "trhea08",
    "trhea09",
    "trhea10",
    "trhea11",
    "trhea12",
    "trheal1",
    "trheal2",
    "trheayn",
    "trhed01",
    "trhed02a",
    "trhed02b",
    "trhed03",
    "trhed04a",
    "trhed04b",
    "trhed05",
    "trhed06a",
    "trhed06b",
    "trhed07",
    "trhed08",
    "trhed09",
    "trhed10",
    "trhed11",
    "trhed12",
    "trhedyn",
    "trheg01",
    "trheg02a",
    "trheg02b",
    "trheg03",
    "trheg04a",
    "trheg04b",
    "trheg05",
    "trheg06a",
    "trheg06b",
    "trheg07",
    "trheg08",
    "trheg09",
    "trheg10",
    "trheg11",
    "trheg12",
    "trhegyn",
    "trhen01",
    "trhen02a",
    "trhen02b",
    "trhen03",
    "trhen04a",
    "trhen04b",
    "trhen05",
    "trhen06a",
    "trhen06b",
    "trhen07",
    "trhen08",
    "trhen09",
    "trhen10",
    "trhen11",
    "trhen12",
    "trhenyn",
    "trhep01",
    "trhep02a",
    "trhep02b",
    "trhep03",
    "trhep04a",
    "trhep04b",
    "trhep05",
    "trhep06a",
    "trhep06b",
    "trhep07",
    "trhep08",
    "trhep09",
    "trhep10",
    "trhep11",
    "trhep12",
    "trhepyn",
    "trhosp",
    "trmeds",
    "trpha1",
    "trpsyc",
    "trpsyh",
    "trstic1",
    "trsuffic"
  )],
    tradl1a = .replace_labels(
    standardized_value_labels$tradl1a,
    `-2` = "na, see KTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl2a = .replace_labels(
    standardized_value_labels$tradl2a,
    `-2` = "na, see KTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl3a = .replace_labels(
    standardized_value_labels$tradl3a,
    `-2` = "na, see KTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl4a = .replace_labels(
    standardized_value_labels$tradl4a,
    `-2` = "na, see KTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl5a = .replace_labels(
    standardized_value_labels$tradl5a,
    `-2` = "na, see KTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl6a = .replace_labels(
    standardized_value_labels$tradl6a,
    `-2` = "na, see KTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    tradl7a = .replace_labels(
    standardized_value_labels$tradl7a,
    `-2` = "na, see KTRPHA1",
    `-1` = "asked, no answer / does not know"
  ),
    `trflwd#6` = .replace_labels(
    standardized_value_labels$`trflwd#6`,
    `-2` = "na, see KTRPHA1"
  ),
    `trflwd#7` = .replace_labels(
    standardized_value_labels$`trflwd#7`,
    `-2` = "na, see KTRPHA1"
  ),
    trflwdiff = .replace_labels(
    standardized_value_labels$trflwdiff,
    `-2` = "na, see KTRPHA1"
  ),
    trheal2 = .replace_labels(
    standardized_value_labels$trheal2,
    `-2` = "na, see KTRHEAL1"
  ),
    trhosp = .replace_labels(
    standardized_value_labels$trhosp,
    `-1` = "na, asked / does not know"
  ),
    trmeds = .replace_labels(
    standardized_value_labels$trmeds,
    `-1` = "na, asked / does not know"
  ),
    trpsyc = .replace_labels(
    standardized_value_labels$trpsyc,
    `-1` = "na, asked / does not know"
  ),
    trpsyh = .replace_labels(
    standardized_value_labels$trpsyh,
    `-1` = "na, asked / does not know"
  ),
    trstic1 = .replace_labels(
    standardized_value_labels$trstic1,
    `-1` = "na, asked / does not know"
  )
  ),
  Harmonized_labels = standardized_value_labels
)

var_types_vec <- c(
  tradl1a = "categorical",
  tradl2a = "categorical",
  tradl3a = "categorical",
  tradl4a = "categorical",
  tradl5a = "categorical",
  tradl6a = "categorical",
  tradl7a = "categorical",
  trerh = "categorical",
  `trflwd#6` = "categorical",
  `trflwd#7` = "categorical",
  trflwdiff = "categorical",
  trhea01 = "categorical",
  trhea02 = "categorical",
  trhea02a = "categorical",
  trhea02b = "categorical",
  trhea03 = "categorical",
  trhea04 = "categorical",
  trhea04a = "categorical",
  trhea04b = "categorical",
  trhea05 = "categorical",
  trhea06 = "categorical",
  trhea06a = "categorical",
  trhea06b = "categorical",
  trhea07 = "categorical",
  trhea08 = "categorical",
  trhea09 = "categorical",
  trhea10 = "categorical",
  trhea11 = "categorical",
  trhea12 = "categorical",
  trheal1 = "categorical",
  trheal2 = "categorical",
  trheayn = "categorical",
  trhed01 = "categorical",
  trhed02 = "categorical",
  trhed02a = "categorical",
  trhed02b = "categorical",
  trhed03 = "categorical",
  trhed04 = "categorical",
  trhed04a = "categorical",
  trhed04b = "categorical",
  trhed05 = "categorical",
  trhed06 = "categorical",
  trhed06a = "categorical",
  trhed06b = "categorical",
  trhed07 = "categorical",
  trhed08 = "categorical",
  trhed09 = "categorical",
  trhed10 = "categorical",
  trhed11 = "categorical",
  trhed12 = "categorical",
  trhedyn = "categorical",
  trheg01 = "categorical",
  trheg02 = "categorical",
  trheg02a = "categorical",
  trheg02b = "categorical",
  trheg03 = "categorical",
  trheg04 = "categorical",
  trheg04a = "categorical",
  trheg04b = "categorical",
  trheg05 = "categorical",
  trheg06 = "categorical",
  trheg06a = "categorical",
  trheg06b = "categorical",
  trheg07 = "categorical",
  trheg08 = "categorical",
  trheg09 = "categorical",
  trheg10 = "categorical",
  trheg11 = "categorical",
  trheg12 = "categorical",
  trhegyn = "categorical",
  trhen01 = "categorical",
  trhen02 = "categorical",
  trhen02a = "categorical",
  trhen02b = "categorical",
  trhen03 = "categorical",
  trhen04 = "categorical",
  trhen04a = "categorical",
  trhen04b = "categorical",
  trhen05 = "categorical",
  trhen06 = "categorical",
  trhen06a = "categorical",
  trhen06b = "categorical",
  trhen07 = "categorical",
  trhen08 = "categorical",
  trhen09 = "categorical",
  trhen10 = "categorical",
  trhen11 = "categorical",
  trhen12 = "categorical",
  trhenyn = "categorical",
  trhep01 = "categorical",
  trhep02 = "categorical",
  trhep02a = "categorical",
  trhep02b = "categorical",
  trhep03 = "categorical",
  trhep04 = "categorical",
  trhep04a = "categorical",
  trhep04b = "categorical",
  trhep05 = "categorical",
  trhep06 = "categorical",
  trhep06a = "categorical",
  trhep06b = "categorical",
  trhep07 = "categorical",
  trhep08 = "categorical",
  trhep09 = "categorical",
  trhep10 = "categorical",
  trhep11 = "categorical",
  trhep12 = "categorical",
  trhepyn = "categorical",
  trhosp = "categorical",
  trmeds = "categorical",
  trpha1 = "categorical",
  trpsyc = "categorical",
  trpsyh = "categorical",
  trstic1 = "categorical",
  trsuffic = "categorical"
)

.lasa_fc_703 <- list(
  variables = .lasa_build_name_table(variable_labels_list, filecode = "703", waves = .lasa_wave_rows()),
  variable_labels = .lasa_build_label_table(variable_labels_list, filecode = "703", waves = .lasa_wave_rows()),
  value_labels = .lasa_build_value_table(value_labels_list, filecode = "703", waves = .lasa_wave_rows()),
  variable_types = .lasa_build_type_table(var_types_vec, filecode = "703", waves = .lasa_wave_rows())
)
