## LASA filecode 108 -- variable names, variable labels, value labels,
## and variable types. Sourced after data-raw/label_db_helpers.R.
##
## To add a wave: add its documented variables to variable_labels_list
## and (if it has value labels) value_labels_list below. To add a new
## variable: add it to harmonized_labels/standardized_value_labels/
## var_types_vec and to the wave(s) that document it.

harmonized_labels <- c(
  qacp10a = "acp 10a: sometimes think about wishes for my deathbed",
  qacp10b = "acp 10b: talk to people close to me about wishes for my deathbed",
  qacp10c = "acp 10c: talk to my general physician about wishes for my deathbed",
  qacp10d = "acp 10d: would like to talk to my general physician about wishes for my deathbed",
  qacp10e = "acp 10e: put something on paper about wishes for my deathbed",
  qacp1a = "Advance care planning item 1a",
  qacp1b = "Advance care planning item 1b",
  qacp1c = "Advance care planning item 1c",
  qacp1d = "Advance care planning item 1d",
  qacp1e = "Advanced care planning, staying at home: yes, living will (past months)",
  qacp2a = "Advance care planning item 2a",
  qacp2b = "Advance care planning item 2b",
  qacp2c = "Advance care planning item 2c",
  qacp2d = "Advance care planning item 2d",
  qacp2e = "Advanced care planning: going to hospital: yes, living will (past months)",
  qacp3a = "Advance care planning item 3a",
  qacp3b = "Advance care planning item 3b",
  qacp3c = "Advance care planning item 3c",
  qacp3d = "Advance care planning item 3d",
  qacp3e = "Advance care planning item 3e",
  qacp4a = "Advance care planning item 4a",
  qacp4b = "Advance care planning item 4b",
  qacp4c = "Advance care planning item 4c",
  qacp4d = "Advance care planning item 4d",
  qacp4e = "Advance care planning item 4e",
  qacp5a = "Advance care planning item 5a",
  qacp5b = "Advance care planning item 5b",
  qacp5c = "Advance care planning item 5c",
  qacp5d = "Advance care planning item 5d",
  qacp5e = "Advance care planning item 5e",
  qacp6a = "Advance care planning item 6a",
  qacp6b = "Advance care planning item 6b",
  qacp6c = "Advance care planning item 6c",
  qacp6d = "Advance care planning item 6d",
  qacp6e = "Advance care planning item 6e",
  qacp7a = "Advance care planning item 7a",
  qacp7b = "Advance care planning item 7b",
  qacp7c = "Advance care planning item 7c",
  qacp7d = "Advance care planning item 7d",
  qacp7e = "Advance care planning item 7e",
  qacp8a = "acp 8a: sometimes think about I would like to be resuscitated if I had a cardiac arrest",
  qacp8b = "acp 8b: talk to people close to me about I would like to be resuscitated if I had a cardiac arrest",
  qacp8c = "acp 8c: talk to my general physician about I would like to be resuscitated if I had a cardiac arrest",
  qacp8d = "acp 8d: would like to talk to my general physician about I would like to be resuscitated if I had a cardiac arrest",
  qacp8e = "acp 8e: put something on paper about I would like to be resuscitated if I had a cardiac arrest",
  qacp9a = "acp 9a: sometimes think about euthanasia as an option for me if life has become unbearable",
  qacp9b = "acp 9b: talk to people close to me about euthanasia as an option for me if life has become unbearable",
  qacp9c = "acp 9c: talk to my general physician about euthanasia as an option for me if life has become unbearable",
  qacp9d = "acp 9d: would like to talk to my general physician about euthanasia as an option for me if life has become unbearable",
  qacp9e = "acp 9e: put something on paper about future euthanasia as an option for me if life has become unbearable"
)

variable_labels_list <- list(
  Wave_I_labels = .replace_labels(
    harmonized_labels[c(
    "qacp10a",
    "qacp10b",
    "qacp10c",
    "qacp10d",
    "qacp10e",
    "qacp1a",
    "qacp1b",
    "qacp1c",
    "qacp1d",
    "qacp2a",
    "qacp2b",
    "qacp2c",
    "qacp2d",
    "qacp3a",
    "qacp3b",
    "qacp3c",
    "qacp3d",
    "qacp3e",
    "qacp4a",
    "qacp4b",
    "qacp4c",
    "qacp4d",
    "qacp4e",
    "qacp5a",
    "qacp5b",
    "qacp5c",
    "qacp5d",
    "qacp5e",
    "qacp6a",
    "qacp6b",
    "qacp6c",
    "qacp6d",
    "qacp6e",
    "qacp7a",
    "qacp7b",
    "qacp7c",
    "qacp7d",
    "qacp7e",
    "qacp8a",
    "qacp8b",
    "qacp8c",
    "qacp8d",
    "qacp8e",
    "qacp9a",
    "qacp9b",
    "qacp9c",
    "qacp9d",
    "qacp9e"
  )],
    qacp1a = "acp 1a: sometimes think about future health",
    qacp1b = "acp 1b: talk to people close to me about future health",
    qacp1c = "acp 1c: talk to my general physician about future health",
    qacp1d = "acp 1d: would like to talk to my general physician about future health",
    qacp2a = "acp 2a: sometimes think about future health partner",
    qacp2b = "acp 2b: talk to people close to me about future health partner",
    qacp2c = "acp 2c: talk to my general physician about future health partner",
    qacp2d = "acp 2d: would like to talk to my general physician about future health partner",
    qacp3a = "acp 3a: sometimes think about future medical care and guidance",
    qacp3b = "acp 3b: talk to people close to me about future medical care and guidance",
    qacp3c = "acp 3c: talk to my general physician about future medical care and guidance",
    qacp3d = "acp 3d: would like to talk to my general physician about future medical care and guidance",
    qacp3e = "acp 3e: put something on paper about future medical care and guidance",
    qacp4a = "acp 4a: sometimes think about who to take care of me not being able to care for myself",
    qacp4b = "acp 4b: talk to people close to me about who to take care of me not being able to care for myself",
    qacp4c = "acp 4c: talk to my general physician about who to take care of me not being able to care for myself",
    qacp4d = "acp 4d: would like to talk to my general physician who to take care of me not being able to care for myself",
    qacp4e = "acp 4e: put something on paper about who to take care of me not being able to care for myself",
    qacp5a = "acp 5a: sometimes think about who to take medical decisions for me not being able doing it myself",
    qacp5b = "acp 5b: talk to people close to me about who to take medical decisions for me not being able doing it myself",
    qacp5c = "acp 5c: talk to my general physician about who to take medical decisions for me not being able doing it myself",
    qacp5d = "acp 5d: would like to talk to my general physician about who to take medical decisions for me not being able doing it myself",
    qacp5e = "acp 5e: put something on paper about who to take medical decisions for me not being able doing it myself",
    qacp6a = "acp 6a: sometimes think about whether a nursing home is an option for me when not being able to stay at home",
    qacp6b = "acp 6b: talk to people close to me about whether a nursing home is an option for me when not being able to stay at home",
    qacp6c = "acp 6c: talk to my general physician about whether a nursing home is an option for me when not being able to stay at home",
    qacp6d = "acp 6d: would like to talk to my general physician about whether a nursing home is an option for me when not being able to stay at home",
    qacp6e = "acp 6e: put something on paper about whether a nursing home is an option for me when not being able to stay at home",
    qacp7a = "acp 7a: sometimes think about situations where I no longer want to have a life-extending treatment",
    qacp7b = "acp 7b: talk to people close to me about situations where I no longer want to have a life-extending treatment",
    qacp7c = "acp 7c: talk to my general physician about situations where I no longer want to have a life-extending treatment",
    qacp7d = "acp 7d: would like to talk to my general physician about situations where I no longer want to have a life-extending treatment",
    qacp7e = "acp 7e: put something on paper about situations where I no longer want to have a life-extending treatment"
  ),
  Wave_K_labels = .replace_labels(
    harmonized_labels[c(
    "qacp1a",
    "qacp1b",
    "qacp1c",
    "qacp1d",
    "qacp1e",
    "qacp2a",
    "qacp2b",
    "qacp2c",
    "qacp2d",
    "qacp2e",
    "qacp3a",
    "qacp3b",
    "qacp3c",
    "qacp3d",
    "qacp3e",
    "qacp4a",
    "qacp4b",
    "qacp4c",
    "qacp4d",
    "qacp4e",
    "qacp5a",
    "qacp5b",
    "qacp5c",
    "qacp5d",
    "qacp5e",
    "qacp6a",
    "qacp6b",
    "qacp6c",
    "qacp6d",
    "qacp6e",
    "qacp7a",
    "qacp7b",
    "qacp7c",
    "qacp7d",
    "qacp7e"
  )],
    qacp1a = "Advanced care planning, staying at home: no, not thought about (past months)",
    qacp1b = "Advanced care planning, staying at home: yes, thought about (past months)",
    qacp1c = "Advanced care planning, staying at home: yes, spoken about with doctor/healthcare provider (past months)",
    qacp1d = "Advanced care planning, staying at home: yes, spoken about with relatives (past months)",
    qacp2a = "Advanced care planning: going to hospital: no, not thought about (past months)",
    qacp2b = "Advanced care planning: going to hospital: yes, thought about (past months)",
    qacp2c = "Advanced care planning: going to hospital: yes, spoken about with doctor/healthcare provider (past months)",
    qacp2d = "Advanced care planning: going to hospital: yes, spoken about with relatives (past months)",
    qacp3a = "Advanced care planning: admitted to nursing home: no, not thought about (past months)",
    qacp3b = "Advanced care planning: admitted to nursing home: yes, thought about (past months)",
    qacp3c = "Advanced care planning: admitted to nursing home: yes, spoken about with doctor/healthcare provider (past months)",
    qacp3d = "Advanced care planning: admitted to nursing home: yes, spoken about with relatives (past months)",
    qacp3e = "Advanced care planning: admitted to nursing home: yes, living will (past months)",
    qacp4a = "Advanced care planning: desired treatments: no, not thought about (past months)",
    qacp4b = "Advanced care planning: desired treatments: yes, thought about (past months)",
    qacp4c = "Advanced care planning: desired treatments: yes, spoken about with doctor/healthcare provider (past months)",
    qacp4d = "Advanced care planning: desired treatments: yes, spoken about with relatives (past months)",
    qacp4e = "Advanced care planning: desired treatments: yes, living will (past months)",
    qacp5a = "Advanced care planning: who should make medical decisions: no, not thought about (past months)",
    qacp5b = "Advanced care planning: who should make medical decisions: yes, thought about (past months)",
    qacp5c = "Advanced care planning: who should make medical decisions: yes, spoken about with doctor/healthcare provider (past months)",
    qacp5d = "Advanced care planning: who should make medical decisions: yes, spoken about with relatives (past months)",
    qacp5e = "Advanced care planning: who should make medical decisions: yes, living will (past months)",
    qacp6a = "Advanced care planning: be resuscitated: no, not thought about (past months)",
    qacp6b = "Advanced care planning: be resuscitated: yes, thought about (past months)",
    qacp6c = "Advanced care planning: be resuscitated: yes, spoken about with doctor/healthcare provider (past months)",
    qacp6d = "Advanced care planning: be resuscitated: yes, spoken about with relatives (past months)",
    qacp6e = "Advanced care planning: be resuscitated: yes, living will (past months)",
    qacp7a = "Advanced care planning: euthanasia: no, not thought about (past months)",
    qacp7b = "Advanced care planning: euthanasia: yes, thought about (past months)",
    qacp7c = "Advanced care planning: euthanasia: yes, spoken about with doctor/healthcare provider (past months)",
    qacp7d = "Advanced care planning: euthanasia: yes, spoken about with relatives (past months)",
    qacp7e = "Advanced care planning: euthanasia: yes, living will (past months)"
  ),
  Harmonized_labels = harmonized_labels
)

standardized_value_labels <- list(
  qacp10a = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp10b = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp10c = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp10d = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp10e = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp1a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp1b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp1c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp1d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp1e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
  qacp2a = c(
    `-2` = "not applicable",
    `-1` = "no answer",
    `0` = "not mentioned",
    `1` = "coding category 1",
    `2` = "no"
  ),
  qacp2b = c(
    `-2` = "not applicable",
    `-1` = "no answer",
    `0` = "not mentioned",
    `1` = "coding category 1",
    `2` = "no"
  ),
  qacp2c = c(
    `-2` = "not applicable",
    `-1` = "no answer",
    `0` = "not mentioned",
    `1` = "coding category 1",
    `2` = "no"
  ),
  qacp2d = c(
    `-2` = "not applicable",
    `-1` = "no answer",
    `0` = "not mentioned",
    `1` = "coding category 1",
    `2` = "no"
  ),
  qacp2e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
  qacp3a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp3b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp3c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp3d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp3e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp4a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp4b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp4c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp4d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp4e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp5a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp5b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp5c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp5d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp5e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp6a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp6b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp6c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp6d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp6e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp7a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp7b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp7c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp7d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp7e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "coding category 1", `2` = "no"),
  qacp8a = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp8b = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp8c = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp8d = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp8e = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp9a = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp9b = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp9c = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp9d = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
  qacp9e = c(`-1` = "no answer", `1` = "yes", `2` = "no")
)

value_labels_list <- list(
  Wave_I_labels = .replace_in_list(
    standardized_value_labels[c(
    "qacp10a",
    "qacp10b",
    "qacp10c",
    "qacp10d",
    "qacp10e",
    "qacp1a",
    "qacp1b",
    "qacp1c",
    "qacp1d",
    "qacp2a",
    "qacp2b",
    "qacp2c",
    "qacp2d",
    "qacp3a",
    "qacp3b",
    "qacp3c",
    "qacp3d",
    "qacp3e",
    "qacp4a",
    "qacp4b",
    "qacp4c",
    "qacp4d",
    "qacp4e",
    "qacp5a",
    "qacp5b",
    "qacp5c",
    "qacp5d",
    "qacp5e",
    "qacp6a",
    "qacp6b",
    "qacp6c",
    "qacp6d",
    "qacp6e",
    "qacp7a",
    "qacp7b",
    "qacp7c",
    "qacp7d",
    "qacp7e",
    "qacp8a",
    "qacp8b",
    "qacp8c",
    "qacp8d",
    "qacp8e",
    "qacp9a",
    "qacp9b",
    "qacp9c",
    "qacp9d",
    "qacp9e"
  )],
    qacp1a = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp1b = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp1c = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp1d = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp2a = c(`-2` = "not applicable", `-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp2b = c(`-2` = "not applicable", `-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp2c = c(`-2` = "not applicable", `-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp2d = c(`-2` = "not applicable", `-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp3a = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp3b = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp3c = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp3d = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp3e = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp4a = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp4b = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp4c = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp4d = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp4e = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp5a = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp5b = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp5c = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp5d = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp5e = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp6a = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp6b = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp6c = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp6d = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp6e = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp7a = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp7b = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp7c = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp7d = c(`-1` = "no answer", `1` = "yes", `2` = "no"),
    qacp7e = c(`-1` = "no answer", `1` = "yes", `2` = "no")
  ),
  Wave_K_labels = .replace_in_list(
    standardized_value_labels[c(
    "qacp1a",
    "qacp1b",
    "qacp1c",
    "qacp1d",
    "qacp1e",
    "qacp2a",
    "qacp2b",
    "qacp2c",
    "qacp2d",
    "qacp2e",
    "qacp3a",
    "qacp3b",
    "qacp3c",
    "qacp3d",
    "qacp3e",
    "qacp4a",
    "qacp4b",
    "qacp4c",
    "qacp4d",
    "qacp4e",
    "qacp5a",
    "qacp5b",
    "qacp5c",
    "qacp5d",
    "qacp5e",
    "qacp6a",
    "qacp6b",
    "qacp6c",
    "qacp6d",
    "qacp6e",
    "qacp7a",
    "qacp7b",
    "qacp7c",
    "qacp7d",
    "qacp7e"
  )],
    qacp1a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp1b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp1c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp1d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp2a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp2b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp2c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp2d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp3a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp3b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp3c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp3d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp3e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp4a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp4b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp4c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp4d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp4e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp5a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp5b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp5c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp5d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp5e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp6a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp6b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp6c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp6d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp6e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp7a = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp7b = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp7c = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp7d = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned"),
    qacp7e = c(`-1` = "no answer", `0` = "not mentioned", `1` = "mentioned")
  ),
  Harmonized_labels = standardized_value_labels
)

var_types_vec <- c(
  qacp10a = "categorical",
  qacp10b = "categorical",
  qacp10c = "categorical",
  qacp10d = "categorical",
  qacp10e = "categorical",
  qacp1a = "categorical",
  qacp1b = "categorical",
  qacp1c = "categorical",
  qacp1d = "categorical",
  qacp1e = "categorical",
  qacp2a = "categorical",
  qacp2b = "categorical",
  qacp2c = "categorical",
  qacp2d = "categorical",
  qacp2e = "categorical",
  qacp3a = "categorical",
  qacp3b = "categorical",
  qacp3c = "categorical",
  qacp3d = "categorical",
  qacp3e = "categorical",
  qacp4a = "categorical",
  qacp4b = "categorical",
  qacp4c = "categorical",
  qacp4d = "categorical",
  qacp4e = "categorical",
  qacp5a = "categorical",
  qacp5b = "categorical",
  qacp5c = "categorical",
  qacp5d = "categorical",
  qacp5e = "categorical",
  qacp6a = "categorical",
  qacp6b = "categorical",
  qacp6c = "categorical",
  qacp6d = "categorical",
  qacp6e = "categorical",
  qacp7a = "categorical",
  qacp7b = "categorical",
  qacp7c = "categorical",
  qacp7d = "categorical",
  qacp7e = "categorical",
  qacp8a = "categorical",
  qacp8b = "categorical",
  qacp8c = "categorical",
  qacp8d = "categorical",
  qacp8e = "categorical",
  qacp9a = "categorical",
  qacp9b = "categorical",
  qacp9c = "categorical",
  qacp9d = "categorical",
  qacp9e = "categorical"
)

.lasa_fc_108 <- list(
  variables = .lasa_build_name_table(variable_labels_list, filecode = "108", waves = .lasa_wave_rows()),
  variable_labels = .lasa_build_label_table(variable_labels_list, filecode = "108", waves = .lasa_wave_rows()),
  value_labels = .lasa_build_value_table(value_labels_list, filecode = "108", waves = .lasa_wave_rows()),
  variable_types = .lasa_build_type_table(var_types_vec, filecode = "108", waves = .lasa_wave_rows())
)
